/******************************************************************************
 * (c) 2014 Broadcom Corporation
 *
 * This program is the proprietary software of Broadcom Corporation and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 *****************************************************************************/
/*******************************************************************
*               Do Not Edit Directly
* Auto-Generated from RTS environment:
*   at: Wed Sep 19 18:42:52 2012 GMT
*   by: robinc
*   for: Platform 7346_single_encode/MemC 0 (32-bit DDR3@866MHz) w/277.714285714286MHz clock)
*******************************************************************/

#define RTS_VER "20120919184252_7425_single_encode"

#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x002d800d	/*	XPT_WR_RS	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x802f400e	/*	XPT_WR_XC	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8032a012	/*	XPT_WR_CDB	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80a3a01e	/*	XPT_WR_ITB_MSG	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x805ec018	/*	XPT_RD_RS	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x834de026	/*	XPT_RD_XC_RMX_MSG	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8032a013	/*	XPT_RD_XC_RAVE	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8080801d	/*	XPT_RD_PB	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80000032	/*	SVD_DBLK	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x800d6002	/*	SVD_ILCPU	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8032c02d	/*	SVD_OLCPU	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x003ed016	/*	SVD_CAB	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0038c015	/*	SVD_ILSI	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x800ed003	/*	SVD_BLCPU	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x806ae01a	/*	SVD_BLSI	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x004bf017	/*	SVD_MVSCL	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80000035	/*	SVD_SPIXSTR	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x82a2e024	/*	BSP	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff040	/*	SVD_DBLK_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8065c02f	/*	SATA	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03d	/*	TPCAP	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8012f02a	/*	CPU_SCB	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8113d020	/*	GENET_WR	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x81398031	/*	GENET_RD	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80372014	/*	MOCA_DATA_WR	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x812cb030	/*	MOCA_DATA_RD	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x82cb6025	/*	MOCA_MIPS	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8026e02b	/*	USB_HI_0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff038	/*	USB_LO_0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x8026e02c	/*	USB_HI_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff039	/*	USB_LO_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x000d6001	/*	RAAGA	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x01350023	/*	AUD_AIO	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x00142004	/*	BVNF_RDC	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x002f6011	/*	BVNF_MFD1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0017a007	/*	BVNF_MFD1_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x002f6010	/*	BVNF_MFD0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0017a006	/*	BVNF_MFD0_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x00d6401f	/*	BVNF_CAP3	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x007cc01c	/*	BVNF_CAP2	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0018d009	/*	BVNF_CAP1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0018d008	/*	BVNF_CAP0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x011dc022	/*	BVNF_VFD3	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x011dc021	/*	BVNF_VFD2	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0018d00b	/*	BVNF_VFD1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0018d00a	/*	BVNF_VFD0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x002f400f	/*	BVN_MAD_PIX_CAP	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x00179005	/*	BVN_MAD_PIX_FD	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0021300c	/*	BVN_MAD_QUANT	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x0077c01b	/*	BVNF_GFD1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x000c4000	/*	BVNF_GFD0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x03526028	/*	VEC_VBI_ENC1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x03526027	/*	VEC_VBI_ENC0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x803e002e	/*	M2M_DMA0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03e	/*	VC4_3D_0	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03f	/*	VC4_3D_1	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03b	/*	M2MC	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03c	/*	MSA	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff03a	/*	DIS	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80000033	/*	SVD_MOCOMP	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80000034	/*	SVD_SPIXSCALE	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x07fff03f	/*	UNASSIGNED	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80096029	/*	CPU_LMB_HIGH	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x80000036	/*	CPU_LMB_LOW	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x87fff037	/*	DRAM_INIT	*/
#define	BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL	0x00695019	/*	REFRESH	*/
