#!/bin/sh
# Startup script for iperf
#
# $Id: 814e3133c33c422f7480b2883a2638b122270c60 $
# $Copyright Broadcom Corporation$
#
# chkconfig:  2345 81 81
# description: iperf server
#

[ -f /usr/local/bin/iperf ] || exit 0

prog="iperf"

if [ -f /etc/rc.d/init.d/functions ]; then
    # Source RedHat function library.
    . /etc/rc.d/init.d/functions

    start() {
	echo -n $"Starting $prog: "
	# Set iperf 20x tcp defaults to match iperf 170
	daemon /usr/local/bin/iperf -s -D -l 8k 2>/var/log/iperf.tcp
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/iperf
	echo
	return $RETVAL  
    }

    stop() {
	if test "x`pidof iperf`" != x; then
	    echo -n $"Stopping $prog: "
	    killproc iperf
	    echo
	fi
    }
else

# Source Debian function library.
. /lib/lsb/init-functions

    start() {
	echo -n $"Starting $prog: "

	# XXX Needs work.  Can't use -D or iperf hangs at the end of
	# every test.
	start_daemon /usr/local/bin/iperf -s 2 -l 8k >/var/log/iperf.tcp &
	RETVAL=$?
	#[ $RETVAL -eq 0 ] && touch /var/lock/subsys/iperf
	echo
	return $RETVAL  
    }

    stop() {
	if test "x`pidof iperf`" != x; then
	    echo -n $"Stopping $prog: "
	    killproc iperf
	    echo
	fi
    }
fi

case "$1" in
	start)
	    start
	    ;;
	
	stop)
	    stop
	    ;;
	
	status)
	    status iperf
	    ;;
	restart)
	    stop
	    start
	    ;;
	condrestart)
	    if test "x`pidof iperf`" != x; then
		stop
		start
	    fi
	    ;;
	
	*)
	    echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	    exit 1
esac
