/******************************************************************************
 * Copyright (C) 2018 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/

#ifndef MAGNUM_SYSLIB_MUXLIB_SRC_STREAM_TS_ASP_BMUXLIB_ASP_ITB_H_
#define MAGNUM_SYSLIB_MUXLIB_SRC_STREAM_TS_ASP_BMUXLIB_ASP_ITB_H_

/* ITB Requirements */
#define BMUXLIB_ASP_ITB_ENTRY_SIZE_IN_WORDS 4
#define BMUXLIB_ASP_ITB_ENTRY_SIZE_IN_BYTES (BMUXLIB_ASP_ITB_ENTRY_SIZE_IN_WORDS*sizeof(uint32_t))

#define BMUXLIB_ASP_ITBENTRY_TYPE_BASE 0x20 /* Indicates start of new frame (0x20) */
#define BMUXLIB_ASP_ITBENTRY_TYPE_BASE_OFFSET 0x28 /* Indicates start of new frame (0x28) with offset from beginning of CDB */
#define BMUXLIB_ASP_ITBENTRY_TYPE_TIMESTAMP 0x21 /* PTS/DTS Entry (0x21) */
#define BMUXLIB_ASP_ITBENTRY_TYPE_BITRATE 0x60 /* Bitrate Entry (0x60) */
#define BMUXLIB_ASP_ITBENTRY_TYPE_ESCR 0x61 /* ESCR Entry (0x61) */
#define BMUXLIB_ASP_ITBENTRY_TYPE_EOS 0x6D /* EOS Entry (0x6D) */

/* ITB accessor macros */
#define BMUXLIB_ASP_ITBENTRY_ENTRYTYPE_OFFSET 0
#define BMUXLIB_ASP_ITBENTRY_ENTRYTYPE_SHIFT 24
#define BMUXLIB_ASP_ITBENTRY_ENTRYTYPE_MASK 0xFF

/* Base Entry */
#define BMUXLIB_ASP_ITBENTRY_ERROR_OFFSET 0
#define BMUXLIB_ASP_ITBENTRY_ERROR_SHIFT 23
#define BMUXLIB_ASP_ITBENTRY_ERROR_MASK 0x00000001

#define BMUXLIB_ASP_ITBENTRY_CDBADDRESS_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_CDBADDRESS_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_CDBADDRESS_MASK 0xFFFFFFFF

/* Timestamp Entry */
#define BMUXLIB_ASP_ITBENTRY_DTSVALID_OFFSET 0
#define BMUXLIB_ASP_ITBENTRY_DTSVALID_SHIFT 15
#define BMUXLIB_ASP_ITBENTRY_DTSVALID_MASK 0x00000001

#define BMUXLIB_ASP_ITBENTRY_PTS32_OFFSET 0
#define BMUXLIB_ASP_ITBENTRY_PTS32_SHIFT 1
#define BMUXLIB_ASP_ITBENTRY_PTS32_MASK 0x00000001

#define BMUXLIB_ASP_ITBENTRY_DTS32_OFFSET 0
#define BMUXLIB_ASP_ITBENTRY_DTS32_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_DTS32_MASK 0x00000001

#define BMUXLIB_ASP_ITBENTRY_PTS_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_PTS_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_PTS_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBENTRY_DTS_OFFSET 2
#define BMUXLIB_ASP_ITBENTRY_DTS_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_DTS_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBENTRY_IFRAME_OFFSET 3
#define BMUXLIB_ASP_ITBENTRY_IFRAME_SHIFT 8
#define BMUXLIB_ASP_ITBENTRY_IFRAME_MASK 0x00000001

#define BMUXLIB_ASP_ITBENTRY_HDRONLY_OFFSET 3
#define BMUXLIB_ASP_ITBENTRY_HDRONLY_SHIFT 9
#define BMUXLIB_ASP_ITBENTRY_HDRONLY_MASK 0x00000001

/* Transmission Entry */
#define BMUXLIB_ASP_ITBENTRY_SHR_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_SHR_SHIFT 16
#define BMUXLIB_ASP_ITBENTRY_SHR_MASK 0x0000FFFF

#define BMUXLIB_ASP_ITBENTRY_TICKSPERBIT_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_TICKSPERBIT_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_TICKSPERBIT_MASK 0x0000FFFF

/* ESCR Entry */
#define BMUXLIB_ASP_ITBENTRY_ESCR_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_ESCR_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_ESCR_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBENTRY_OPTS_OFFSET 2
#define BMUXLIB_ASP_ITBENTRY_OPTS_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_OPTS_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBENTRY_METADATA_OFFSET 3
#define BMUXLIB_ASP_ITBENTRY_METADATA_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_METADATA_MASK 0xFFFFFFFF

/* EOS Entry */
#define BMUXLIB_ASP_ITBENTRY_EOS_CDBADDRESS_OFFSET 1
#define BMUXLIB_ASP_ITBENTRY_EOS_CDBADDRESS_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_EOS_CDBADDRESS_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBENTRY_EOS_ESCR_OFFSET 2
#define BMUXLIB_ASP_ITBENTRY_EOS_ESCR_SHIFT 0
#define BMUXLIB_ASP_ITBENTRY_EOS_ESCR_MASK 0xFFFFFFFF

#define BMUXLIB_ASP_ITBEntry_Get(_pentry, _field) ((((uint32_t*)(_pentry))[BMUXLIB_ASP_ITBENTRY_##_field##_OFFSET] >> BMUXLIB_ASP_ITBENTRY_##_field##_SHIFT ) & BMUXLIB_ASP_ITBENTRY_##_field##_MASK )

#define BMUXLIB_ASP_ITBEntry_GetEntryType(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, ENTRYTYPE)
#define BMUXLIB_ASP_ITBEntry_GetCDBOffset(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, CDBADDRESS)
#define BMUXLIB_ASP_ITBEntry_GetError(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, ERROR)
#define BMUXLIB_ASP_ITBEntry_GetDTS(_pentry) ( ( ( (uint64_t) BMUXLIB_ASP_ITBEntry_Get(_pentry, DTS32)) << 32 ) | BMUXLIB_ASP_ITBEntry_Get(_pentry, DTS) )
#define BMUXLIB_ASP_ITBEntry_GetDTSValid(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, DTSVALID)
#define BMUXLIB_ASP_ITBEntry_GetPTS(_pentry) ( ( ( (uint64_t) BMUXLIB_ASP_ITBEntry_Get(_pentry, PTS32)) << 32 ) | BMUXLIB_ASP_ITBEntry_Get(_pentry, PTS) )
#define BMUXLIB_ASP_ITBEntry_GetIFrame(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, IFRAME)
#define BMUXLIB_ASP_ITBEntry_GetHDROnly(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, HDRONLY)
#define BMUXLIB_ASP_ITBEntry_GetTicksPerBit(_pentry) ((uint16_t) BMUXLIB_ASP_ITBEntry_Get(_pentry, TICKSPERBIT))
#define BMUXLIB_ASP_ITBEntry_GetSHR(_pentry) ((short) BMUXLIB_ASP_ITBEntry_Get(_pentry, SHR))
#define BMUXLIB_ASP_ITBEntry_GetESCR(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, ESCR)
#define BMUXLIB_ASP_ITBEntry_GetOriginalPTS(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, OPTS)
#define BMUXLIB_ASP_ITBEntry_GetMetadata(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, METADATA)
#define BMUXLIB_ASP_ITBEntry_GetEOSCDBOffset(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, EOS_CDBADDRESS)
#define BMUXLIB_ASP_ITBEntry_GetEOSESCR(_pentry) BMUXLIB_ASP_ITBEntry_Get(_pentry, EOS_ESCR)

#define BMUXLIB_ASP_ITBEntry_IsIgnoreFrame(_pentry) ( 0 != ( ( BMUXLIB_ASP_ITBEntry_GetMetadata(_pentry) >> 29 ) & 0x1) )

#endif /* MAGNUM_SYSLIB_MUXLIB_SRC_STREAM_TS_ASP_BMUXLIB_ASP_ITB_H_ */
