/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Jun 19 19:50:14 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          unknown
 *                 RDB Parser           3.0
 *                 generate_int_id.pl   1.0
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#include "bchp.h"
#include "bchp_ds_topm.h"

#ifndef BCHP_INT_ID_DS_TOPM_H__
#define BCHP_INT_ID_DS_TOPM_H__

#define BCHP_INT_ID_DS0_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS0_1_IS_SHIFT)
#define BCHP_INT_ID_DS0_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS0_2_IS_SHIFT)
#define BCHP_INT_ID_DS1_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS1_1_IS_SHIFT)
#define BCHP_INT_ID_DS1_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS1_2_IS_SHIFT)
#define BCHP_INT_ID_DS2_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS2_1_IS_SHIFT)
#define BCHP_INT_ID_DS2_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS2_2_IS_SHIFT)
#define BCHP_INT_ID_DS3_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS3_1_IS_SHIFT)
#define BCHP_INT_ID_DS3_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS3_2_IS_SHIFT)
#define BCHP_INT_ID_DS4_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS4_1_IS_SHIFT)
#define BCHP_INT_ID_DS4_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS4_2_IS_SHIFT)
#define BCHP_INT_ID_DS5_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS5_1_IS_SHIFT)
#define BCHP_INT_ID_DS5_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS5_2_IS_SHIFT)
#define BCHP_INT_ID_DS6_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS6_1_IS_SHIFT)
#define BCHP_INT_ID_DS6_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS6_2_IS_SHIFT)
#define BCHP_INT_ID_DS7_1_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS7_1_IS_SHIFT)
#define BCHP_INT_ID_DS7_2_IS                  BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_DS7_2_IS_SHIFT)
#define BCHP_INT_ID_FSCNT1_IS                 BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_FSCNT1_IS_SHIFT)
#define BCHP_INT_ID_FSCNT2_IS                 BCHP_INT_ID_CREATE(BCHP_DS_TOPM_L2_IRQSTS, BCHP_DS_TOPM_L2_IRQSTS_FSCNT2_IS_SHIFT)

#endif /* #ifndef BCHP_INT_ID_DS_TOPM_H__ */

/* End of File */
