/******************************************************************************************************
 * Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *****************************************************************************************************/

"vkGetSwapchainGrallocUsageANDROID",
"vkAcquireImageANDROID",
"vkQueueSignalReleaseImageANDROID",
