/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Mon Sep 15 10:12:26 2014
 *                 Full Compile MD5 Checksum  ef22086ebd4065e4fea50dbc64f17e5e
 *                     (minus title and desc)
 *                 MD5 Checksum               39fcae49037a6337517df43bfc24b21f
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14796
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_DSMACOFDA_RESERVED_PER_H__
#define BCHP_DSMACOFDA_RESERVED_PER_H__

/***************************************************************************
 *DSMACOFDA_RESERVED_PER
 ***************************************************************************/
#define BCHP_DSMACOFDA_RESERVED_PER_REG_0        0x03c0f110 /* [RW] BPCM Reserved Register */
#define BCHP_DSMACOFDA_RESERVED_PER_REG_1        0x03c0f114 /* [RW] BPCM Reserved Register */
#define BCHP_DSMACOFDA_RESERVED_PER_REG_2        0x03c0f118 /* [RW] BPCM Reserved Register */
#define BCHP_DSMACOFDA_RESERVED_PER_REG_3        0x03c0f11c /* [RW] BPCM Reserved Register */

#endif /* #ifndef BCHP_DSMACOFDA_RESERVED_PER_H__ */

/* End of File */
