/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Mon Sep 15 10:12:24 2014
 *                 Full Compile MD5 Checksum  ef22086ebd4065e4fea50dbc64f17e5e
 *                     (minus title and desc)
 *                 MD5 Checksum               39fcae49037a6337517df43bfc24b21f
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14796
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_WOD_MEM_PROC8_A_H__
#define BCHP_WOD_MEM_PROC8_A_H__

/***************************************************************************
 *WOD_MEM_PROC8_A - WOD Memory Burst Processor 8
 ***************************************************************************/
#define BCHP_WOD_MEM_PROC8_A_PROC_CTRL           0x02350300 /* [RW] PROC Control */
#define BCHP_WOD_MEM_PROC8_A_PROC_STATUS         0x02350304 /* [RO] PROC Status */
#define BCHP_WOD_MEM_PROC8_A_PROC_ADDR_PATTERN   0x02350308 /* [RW] PROC Address Generation Pattern */
#define BCHP_WOD_MEM_PROC8_A_PROC_ADDR_OFFSET    0x0235030c /* [RW] PROC Starting Address */
#define BCHP_WOD_MEM_PROC8_A_PROC_INITCNT        0x02350310 /* [RW] PROC Starting Counter Value */
#define BCHP_WOD_MEM_PROC8_A_PROC_BURST_SIZE     0x02350314 /* [RW] PROC Burst Size */
#define BCHP_WOD_MEM_PROC8_A_PROC_MODULO_LO      0x02350318 /* [RW] PROC Lower Bound For Modulo Address Pattern */
#define BCHP_WOD_MEM_PROC8_A_PROC_MODULO_HI      0x0235031c /* [RW] PROC Upper Bound For Modulo Address Pattern */
#define BCHP_WOD_MEM_PROC8_A_PROC_MOD            0x02350320 /* [RW] PROC Modifier value */
#define BCHP_WOD_MEM_PROC8_A_PROC_HEADER         0x02350324 /* [RW] PROC Burst Output Header when used */

#endif /* #ifndef BCHP_WOD_MEM_PROC8_A_H__ */

/* End of File */
