/******************************************************************************
* Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
*
* This program is the proprietary software of Broadcom and/or its
* licensors, and may only be used, duplicated, modified or distributed pursuant
* to the terms and conditions of a separate, written license agreement executed
* between you and Broadcom (an "Authorized License").  Except as set forth in
* an Authorized License, Broadcom grants no license (express or implied), right
* to use, or waiver of any kind with respect to the Software, and Broadcom
* expressly reserves all rights in and to the Software and all intellectual
* property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
* HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
* NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
*
* Except as expressly set forth in the Authorized License,
*
* 1. This program, including its structure, sequence and organization,
*    constitutes the valuable trade secrets of Broadcom, and you shall use all
*    reasonable efforts to protect the confidentiality thereof, and to use
*    this information only in connection with your use of Broadcom integrated
*    circuit products.
*
* 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
*    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
*    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
*    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
*    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
*    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
*    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
*    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
*
* 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
*    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
*    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
*    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
*    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
*    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
*    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
*    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
#ifndef __BMEMPERF_H__
#define __BMEMPERF_H__

#include "bchp_common.h"
#include "bchp_memc_arb_0.h"
#include "bchp_memc_ddr_0.h"
#include "nexus_platform_features.h"
#include "nexus_base_types.h"
#include "bchp_memc_misc_0.h"
#include "bchp_memc_ddr_0.h"

#define BMEMPERF_INVALID  0xFFFFFFFF
#define BMEMPERF_NUM_MEMC NEXUS_NUM_MEMC

/** this is arranged like this , so that any memc's (0,1,2,3) registers can be accessed **/
#define BMEMPERF_RDB_REG_SIZE 4
#define BMEMPERF_MEMC_BASE    BCHP_MEMC_GEN_0_REG_START

#if ( NEXUS_NUM_MEMC==1 )
#define BMEMPERF_MEMC_REGISTER_SIZE ( BCHP_MEMC_MISC_0_SOFT_RESET - BCHP_MEMC_GEN_0_REG_START + BMEMPERF_RDB_REG_SIZE )
#else
#define BMEMPERF_MEMC_REGISTER_SIZE ( BCHP_MEMC_GEN_1_REG_START - BCHP_MEMC_GEN_0_REG_START )
#endif

#if defined ( BCHP_MEMC_DDR_0_STAT_CAS_CLIENT_128 )
#define BMEMPERF_MAX_NUM_CLIENT 256
#else
#define BMEMPERF_MAX_NUM_CLIENT 128
#endif
/*#define BMEMPERF_MEMC_ARB_REG_OFFSET              (BCHP_MEMC_ARB_0_REG_START - BCHP_MEMC_GEN_0_REG_START )    */
#define BMEMPERF_MEMC_ARB_CLIENT_INFO_OFFSET     ( BCHP_MEMC_ARB_0_CLIENT_INFO_0 - BCHP_MEMC_GEN_0_REG_START )
#define BMEMPERF_MEMC_DDR_STATS_REGISTER_OFFSET  ( BCHP_MEMC_DDR_0_STAT_CONTROL - BCHP_MEMC_GEN_0_REG_START )
#define BMEMPERF_MEMC_DDR_DRAM_TIMING_4          ( BCHP_MEMC_DDR_0_DRAM_TIMING_4 - BCHP_MEMC_GEN_0_REG_START )
#define BMEMPERF_MEMC_DDR_STAT_CAS_CLIENT_OFFSET ( BCHP_MEMC_DDR_0_STAT_CAS_CLIENT_0 - BCHP_MEMC_GEN_0_REG_START )

/** Here are the derived stat register , RDB change may need a review for this , if any new regs are inserted in between **/
#define BMEMPERF_MEMC_DDR_STAT_CONTROL      0x0
#define BMEMPERF_MEMC_DDR_STAT_TIMER        ( BMEMPERF_MEMC_DDR_STAT_CONTROL + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_STAT_IDLE_NOP     ( BMEMPERF_MEMC_DDR_STAT_TIMER + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_STAT_MAX_IDLE_NOP ( BMEMPERF_MEMC_DDR_STAT_IDLE_NOP + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_STAT_MIN_IDLE_NOP BMEMPERF_MEMC_DDR_STAT_MAX_IDLE_NOP

#if     0
#define BMEMPERF_MEMC_DDR_STAT_MIN_IDLE_NOP ( BMEMPERF_MEMC_DDR_STAT_MAX_IDLE_NOP + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_STAT_CAS_ALL      ( BMEMPERF_MEMC_DDR_STAT_MIN_IDLE_NOP + BMEMPERF_RDB_REG_SIZE )
#endif
#define BMEMPERF_MEMC_DDR_STAT_CAS_ALL        ( BCHP_MEMC_DDR_0_STAT_CAS_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MAX_CAS_ALL    ( BCHP_MEMC_DDR_0_STAT_MAX_CAS_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_CAS_ALL    ( BCHP_MEMC_DDR_0_STAT_MIN_CAS_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_PENALTY_ALL    ( BCHP_MEMC_DDR_0_STAT_PENALTY_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_PENALTY_GDDRWM ( BCHP_MEMC_DDR_0_STAT_PENALTY_ALL + BMEMPERF_RDB_REG_SIZE )

#if (( BCHP_CHIP == 7445 && BCHP_VER >= BCHP_VER_D0 ) || ( BCHP_CHIP == 7439 && BCHP_VER >= BCHP_VER_B0 ))
#define BMEMPERF_MEMC_DDR_STAT_PAGE_MERGE_ALL       ( BMEMPERF_MEMC_DDR_STAT_PENALTY_GDDRWM + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_STAT_MAX_TRANS_CYCLES_ALL ( BMEMPERF_MEMC_DDR_STAT_PAGE_MERGE_ALL + BMEMPERF_RDB_REG_SIZE )
#else
#define BMEMPERF_MEMC_DDR_STAT_MAX_TRANS_CYCLES_ALL ( BMEMPERF_MEMC_DDR_STAT_PENALTY_GDDRWM + BMEMPERF_RDB_REG_SIZE )
#endif

#define BMEMPERF_MEMC_DDR_STAT_MIN_TRANS_CYCLES_ALL        ( BCHP_MEMC_DDR_0_STAT_MIN_TRANS_CYCLES_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_TRANS_READ_ALL              ( BCHP_MEMC_DDR_0_STAT_TRANS_READ_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_TRANS_WRITE_ALL             ( BCHP_MEMC_DDR_0_STAT_TRANS_WRITE_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MAX_TRANS_ALL               ( BCHP_MEMC_DDR_0_STAT_MAX_TRANS_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_TRANS_ALL               ( BCHP_MEMC_DDR_0_STAT_MIN_TRANS_ALL - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_CAS          ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_CAS - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MAX_CLIENT_SERVICE_CAS      ( BCHP_MEMC_DDR_0_STAT_MAX_CLIENT_SERVICE_CAS - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_CLIENT_SERVICE_CAS      ( BCHP_MEMC_DDR_0_STAT_MIN_CLIENT_SERVICE_CAS - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_INTR_PENALTY ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_INTR_PENALTY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_POST_PENALTY ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_POST_PENALTY - BCHP_MEMC_DDR_0_STAT_CONTROL )

#define BMEMPERF_MEMC_DDR_STAT_MAX_CLIENT_SERVICE_CYCLES      ( BCHP_MEMC_DDR_0_STAT_MAX_CLIENT_SERVICE_CYCLES - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_CLIENT_SERVICE_CYCLES      ( BCHP_MEMC_DDR_0_STAT_MIN_CLIENT_SERVICE_CYCLES - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_TRANS_READ      ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_TRANS_READ - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_TRANS_WRITE     ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_TRANS_WRITE - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MAX_CLIENT_SERVICE_TRANS       ( BCHP_MEMC_DDR_0_STAT_MAX_CLIENT_SERVICE_TRANS - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_CLIENT_SERVICE_TRANS       ( BCHP_MEMC_DDR_0_STAT_MIN_CLIENT_SERVICE_TRANS - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_SERVICE_LATENCY         ( BCHP_MEMC_DDR_0_STAT_CLIENT_SERVICE_LATENCY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MAX_CLIENT_SERVICE_LATENCY     ( BCHP_MEMC_DDR_0_STAT_MAX_CLIENT_SERVICE_LATENCY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_CLIENT_SERVICE_LATENCY     ( BCHP_MEMC_DDR_0_STAT_MIN_CLIENT_SERVICE_LATENCY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_ABS_MAX_SERVICE_LATENCY ( BCHP_MEMC_DDR_0_STAT_CLIENT_ABS_MAX_SERVICE_LATENCY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_CLIENT_ABS_MIN_SERVICE_LATENCY ( BCHP_MEMC_DDR_0_STAT_CLIENT_ABS_MIN_SERVICE_LATENCY - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_REFRESH                        ( BCHP_MEMC_DDR_0_STAT_REFRESH - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_DQ_IDLE_WRITE              ( BCHP_MEMC_DDR_0_STAT_MIN_DQ_IDLE_WRITE - BCHP_MEMC_DDR_0_STAT_CONTROL )
#define BMEMPERF_MEMC_DDR_STAT_MIN_DQ_IDLE_READ               ( BCHP_MEMC_DDR_0_STAT_MIN_DQ_IDLE_READ - BCHP_MEMC_DDR_0_STAT_CONTROL )

#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_0   ( 0x0 )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_1   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_0 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_2   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_1 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_3   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_2 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_4   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_3 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_5   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_4 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_6   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_5 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_7   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_6 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_8   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_7 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_9   ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_8 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_10  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_9 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_11  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_10 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_12  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_11 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_13  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_12 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_14  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_13 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_15  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_14 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_16  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_15 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_17  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_16 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_18  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_17 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_19  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_18 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_20  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_19 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_21  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_20 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_22  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_21 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_23  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_22 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_24  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_23 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_25  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_24 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_26  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_25 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_27  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_26 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_28  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_27 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_29  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_28 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_30  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_29 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_31  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_30 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_32  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_31 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_33  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_32 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_34  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_33 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_35  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_34 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_36  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_35 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_37  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_36 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_38  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_37 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_39  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_38 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_40  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_39 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_41  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_40 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_42  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_41 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_43  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_42 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_44  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_43 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_45  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_44 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_46  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_45 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_47  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_46 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_48  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_47 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_49  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_48 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_50  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_49 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_51  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_50 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_52  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_51 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_53  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_52 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_54  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_53 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_55  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_54 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_56  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_55 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_57  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_56 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_58  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_57 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_59  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_58 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_60  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_59 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_61  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_60 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_62  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_61 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_63  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_62 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_64  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_63 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_65  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_64 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_66  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_65 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_67  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_66 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_68  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_67 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_69  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_68 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_70  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_69 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_71  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_70 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_72  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_71 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_73  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_72 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_74  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_73 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_75  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_74 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_76  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_75 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_77  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_76 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_78  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_77 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_79  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_78 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_80  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_79 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_81  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_80 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_82  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_81 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_83  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_82 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_84  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_83 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_85  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_84 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_86  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_85 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_87  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_86 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_88  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_87 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_89  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_88 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_90  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_89 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_91  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_90 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_92  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_91 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_93  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_92 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_94  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_93 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_95  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_94 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_96  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_95 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_97  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_96 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_98  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_97 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_99  ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_98 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_100 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_99 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_101 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_100 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_102 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_101 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_103 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_102 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_104 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_103 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_105 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_104 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_106 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_105 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_107 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_106 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_108 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_107 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_109 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_108 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_110 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_109 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_111 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_110 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_112 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_111 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_113 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_112 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_114 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_113 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_115 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_114 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_116 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_115 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_117 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_116 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_118 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_117 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_119 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_118 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_120 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_119 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_121 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_120 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_122 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_121 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_123 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_122 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_124 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_123 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_125 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_124 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_126 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_125 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_127 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_126 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_128 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_127 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_129 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_128 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_130 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_129 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_131 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_130 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_132 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_131 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_133 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_132 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_134 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_133 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_135 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_134 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_136 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_135 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_137 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_136 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_138 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_137 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_139 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_138 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_140 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_139 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_141 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_140 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_142 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_141 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_143 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_142 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_144 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_143 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_145 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_144 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_146 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_145 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_147 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_146 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_148 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_147 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_149 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_148 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_150 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_149 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_151 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_150 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_152 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_151 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_153 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_152 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_154 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_153 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_155 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_154 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_156 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_155 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_157 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_156 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_158 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_157 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_159 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_158 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_160 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_159 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_161 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_160 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_162 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_161 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_163 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_162 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_164 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_163 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_165 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_164 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_166 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_165 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_167 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_166 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_168 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_167 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_169 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_168 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_170 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_169 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_171 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_170 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_172 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_171 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_173 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_172 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_174 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_173 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_175 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_174 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_176 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_175 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_177 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_176 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_178 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_177 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_179 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_178 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_180 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_179 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_181 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_180 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_182 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_181 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_183 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_182 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_184 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_183 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_185 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_184 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_186 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_185 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_187 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_186 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_188 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_187 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_189 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_188 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_190 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_189 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_191 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_190 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_192 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_191 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_193 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_192 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_194 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_193 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_195 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_194 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_196 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_195 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_197 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_196 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_198 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_197 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_199 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_198 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_200 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_199 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_201 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_200 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_202 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_201 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_203 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_202 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_204 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_203 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_205 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_204 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_206 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_205 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_207 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_206 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_208 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_207 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_209 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_208 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_210 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_209 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_211 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_210 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_212 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_211 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_213 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_212 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_214 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_213 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_215 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_214 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_216 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_215 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_217 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_216 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_218 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_217 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_219 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_218 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_220 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_219 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_221 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_220 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_222 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_221 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_223 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_222 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_224 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_223 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_225 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_224 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_226 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_225 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_227 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_226 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_228 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_227 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_229 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_228 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_230 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_229 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_231 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_230 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_232 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_231 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_233 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_232 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_234 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_233 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_235 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_234 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_236 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_235 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_237 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_236 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_238 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_237 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_239 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_238 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_240 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_239 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_241 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_240 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_242 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_241 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_243 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_242 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_244 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_243 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_245 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_244 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_246 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_245 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_247 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_246 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_248 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_247 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_249 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_248 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_250 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_249 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_251 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_250 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_252 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_251 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_253 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_252 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_254 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_253 + BMEMPERF_RDB_REG_SIZE )
#define BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_255 ( BMEMPERF_MEMC_DDR_0_STAT_CAS_CLIENT_254 + BMEMPERF_RDB_REG_SIZE )

/*******************************************************/
#define BMEMPERF_DDR0_CLOCK_FREQ_UNIT 1000  /** since time -> i.e g_interval is in msec **/ /** 1000000 **/

#define BMEMPERF_NANO_SECOND_UNIT 1000000 /**since time -> i.e g_interval is in msec unit **/ /** 0x3B9ACA00  **/

typedef struct  bmemperf_data
{
    /** Normal mode overall service data **/
    unsigned int dataBW;        /** In Mbps **/
    unsigned int refreshBW;     /** In Mbps **/
    unsigned int transactionBW; /** In Mbps **/
    unsigned int idleBW;        /** In Mbps **/

    float dataUtil;

    /** Normal mode overall client data **/
    unsigned int rrEn;  /** round robin enable flag **/
    unsigned int boVal; /** BO_VAL from rdb in nsec **/

    unsigned int clientDataBW;  /** In Mbps **/
    unsigned int clientTransBW; /** In Mbps **/

    float clientDataUtil;

    unsigned int clientRdTransInPerc;
    unsigned int clientWrTransInPerc;
    unsigned int avgClientDataSizeInBits;
    unsigned int avgClientTransSizeInBits;
    unsigned int totalTrxnCount;
    unsigned int avgTimeBwnClientTransInNsec; /** average time between transactions in nano second **/

    /*** Max Min Mode data ***/
    /**Overall system data ***/
    unsigned int max_data_bw;
    unsigned int min_data_bw;

    unsigned int max_txn_bw;
    unsigned int min_txn_bw;

    unsigned int max_idle_bw;
    unsigned int min_idle_bw;

    float max_data_util;
    float min_data_util;

    /*** Client specific data ***/
    unsigned int max_client_data_bw;
    unsigned int min_client_data_bw;
    unsigned int max_client_txn_bw;
    unsigned int min_client_txn_bw;

    float max_client_data_util;
    float min_client_data_util;

    unsigned int max_client_srvc_txn;
    unsigned int min_client_srvc_txn;
} bmemperf_data;

typedef struct bmemperf_client_casdata_Index
{
    volatile unsigned int data;
    volatile unsigned int index;
} bmemperf_client_casdata_Index;

int          bmemperf_init( void );
unsigned int bmemperf_collect_arb_details( unsigned int client_id, unsigned int memc_index );
unsigned int bmemperf_get_arb_err( unsigned int client_id, unsigned int memc_index );
unsigned int bmemperf_clear_arb_err( unsigned int memc_index );
void         bmemperf_set_arb_vals( unsigned int client_id, unsigned int memc_index,  unsigned int bo_val, unsigned int rr_flag );
void         bmemperf_configure_stat_control_reg( unsigned int client_id, unsigned int memc_index );
void         bmemperf_normalmode_system_data( unsigned int memc_index );
void         bmemperf_normalmode_client_service_data( unsigned int memc_index );
void         bmemperf_maxminmode_system_data( unsigned int memc_index );
void         bmemperf_maxminmode_client_service_data( unsigned int memc_index );
unsigned int bmemperf_get_ddr_stat_cas_client_data( unsigned int client_id, unsigned int memc_index );
int          compare_cas_data( const void *a, const void *b );
float        bmemperf_computeBWinMbps( unsigned int cycles, unsigned int interval_in_MHZ, unsigned int memc_index );
volatile unsigned int *bmemperf_get_g_pMem( void );

#endif /*__BMEMPERF_H__ */
