#############################################################################
#  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
#############################################################################
CPP_PLATFORM_FILES += \
	bsg_platform_nexus.cpp \
	bsg_media_prober_nexus.cpp \
	bsg_video_nexus.cpp \
	bsg_video_decoder_nexus.cpp

H_PLATFORM_FILES += \
	bsg_platform_nexus.h \
	bsg_media_prober_nexus.h

INC_FILES += \
	bsg_nexus.inc
