/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Thu Dec  4 15:33:17 2014
 *                 Full Compile MD5 Checksum  56e4d67431c9c20b478163a0398e46d2
 *                     (minus title and desc)
 *                 MD5 Checksum               4f20593ca4d982166bb9cd16fec140cc
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15262
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_ODU_CHAN_CH1_1_H__
#define BCHP_ODU_CHAN_CH1_1_H__

/***************************************************************************
 *ODU_CHAN_CH1_1
 ***************************************************************************/
#define BCHP_ODU_CHAN_CH1_1_DEC_FCW              0x00249200 /* [RW] Decimation tile : Frequency control word */
#define BCHP_ODU_CHAN_CH1_1_ACI_H0               0x00249204 /* [RW] Baseband tile : Filter coefficient tap 0 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H1               0x00249208 /* [RW] Baseband tile : Filter coefficient tap 1 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H2               0x0024920c /* [RW] Baseband tile : Filter coefficient tap 2 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H3               0x00249210 /* [RW] Baseband tile : Filter coefficient tap 3 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H4               0x00249214 /* [RW] Baseband tile : Filter coefficient tap 4 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H5               0x00249218 /* [RW] Baseband tile : Filter coefficient tap 5 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H6               0x0024921c /* [RW] Baseband tile : Filter coefficient tap 6 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H7               0x00249220 /* [RW] Baseband tile : Filter coefficient tap 7 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H8               0x00249224 /* [RW] Baseband tile : Filter coefficient tap 8 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H9               0x00249228 /* [RW] Baseband tile : Filter coefficient tap 9 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H10              0x0024922c /* [RW] Baseband tile : Filter coefficient tap 10 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H11              0x00249230 /* [RW] Baseband tile : Filter coefficient tap 11 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H12              0x00249234 /* [RW] Baseband tile : Filter coefficient tap 12 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H13              0x00249238 /* [RW] Baseband tile : Filter coefficient tap 13 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H14              0x0024923c /* [RW] Baseband tile : Filter coefficient tap 14 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H15              0x00249240 /* [RW] Baseband tile : Filter coefficient tap 15 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H16              0x00249244 /* [RW] Baseband tile : Filter coefficient tap 16 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H17              0x00249248 /* [RW] Baseband tile : Filter coefficient tap 17 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H18              0x0024924c /* [RW] Baseband tile : Filter coefficient tap 18 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H19              0x00249250 /* [RW] Baseband tile : Filter coefficient tap 19 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H20              0x00249254 /* [RW] Baseband tile : Filter coefficient tap 20 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H21              0x00249258 /* [RW] Baseband tile : Filter coefficient tap 21 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H22              0x0024925c /* [RW] Baseband tile : Filter coefficient tap 22 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H23              0x00249260 /* [RW] Baseband tile : Filter coefficient tap 23 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H24              0x00249264 /* [RW] Baseband tile : Filter coefficient tap 24 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H25              0x00249268 /* [RW] Baseband tile : Filter coefficient tap 25 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H26              0x0024926c /* [RW] Baseband tile : Filter coefficient tap 26 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H27              0x00249270 /* [RW] Baseband tile : Filter coefficient tap 27 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H28              0x00249274 /* [RW] Baseband tile : Filter coefficient tap 28 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H29              0x00249278 /* [RW] Baseband tile : Filter coefficient tap 29 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H30              0x0024927c /* [RW] Baseband tile : Filter coefficient tap 30 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H31              0x00249280 /* [RW] Baseband tile : Filter coefficient tap 31 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H32              0x00249284 /* [RW] Baseband tile : Filter coefficient tap 32 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H33              0x00249288 /* [RW] Baseband tile : Filter coefficient tap 33 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H34              0x0024928c /* [RW] Baseband tile : Filter coefficient tap 34 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H35              0x00249290 /* [RW] Baseband tile : Filter coefficient tap 35 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H36              0x00249294 /* [RW] Baseband tile : Filter coefficient tap 36 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H37              0x00249298 /* [RW] Baseband tile : Filter coefficient tap 37 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H38              0x0024929c /* [RW] Baseband tile : Filter coefficient tap 38 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H39              0x002492a0 /* [RW] Baseband tile : Filter coefficient tap 39 */
#define BCHP_ODU_CHAN_CH1_1_ACI_H40              0x002492a4 /* [RW] Baseband tile : Filter coefficient tap 40 */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_0_CTRL         0x002492a8 /* [RW] Baseband tile : Notch 0 controls */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_0_FCW          0x002492ac /* [RW] Baseband tile : Notch 0 frequency control word */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_0_INT_I        0x002492b0 /* [RW] Baseband tile : Notch 0 DC notch filter integrator I */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_0_INT_Q        0x002492b4 /* [RW] Baseband tile : Notch 0 DC notch filter integrator Q */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_1_CTRL         0x002492b8 /* [RW] Baseband tile : Notch 1 controls */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_1_FCW          0x002492bc /* [RW] Baseband tile : Notch 1 frequency control word */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_1_INT_I        0x002492c0 /* [RW] Baseband tile : Notch 1 DC notch filter integrator I */
#define BCHP_ODU_CHAN_CH1_1_NOTCH_1_INT_Q        0x002492c4 /* [RW] Baseband tile : Notch 1 DC notch filter integrator Q */
#define BCHP_ODU_CHAN_CH1_1_AGC_CTRL             0x002492c8 /* [RW] Baseband tile : AGC controls */
#define BCHP_ODU_CHAN_CH1_1_AGC_LA_INT           0x002492cc /* [RO] Baseband tile : AGC leaky averager */
#define BCHP_ODU_CHAN_CH1_1_AGC_LF_INT           0x002492d0 /* [RW] Baseband tile : AGC integrator */
#define BCHP_ODU_CHAN_CH1_1_AGC_LF_INT_MIN       0x002492d4 /* [RW] Baseband tile : AGC integrator min limit */
#define BCHP_ODU_CHAN_CH1_1_AGC_LF_INT_MAX       0x002492d8 /* [RW] Baseband tile : AGC integrator max limit */
#define BCHP_ODU_CHAN_CH1_1_INT_FCW              0x002492dc /* [RW] Interpolation tile : Frequency control word */
#define BCHP_ODU_CHAN_CH1_1_INT_MIX              0x002492e0 /* [RW] Interpolation tile : mixer control */
#define BCHP_ODU_CHAN_CH1_1_INT_TONE             0x002492e4 /* [RW] Interpolation tile : mixer tone output amplitude (tc1.12) */
#define BCHP_ODU_CHAN_CH1_1_TIMERCTL0            0x002492e8 /* [RW] Timer 0 Control */
#define BCHP_ODU_CHAN_CH1_1_TIMERCTL1            0x002492ec /* [RW] Timer 1 Control */
#define BCHP_ODU_CHAN_CH1_1_SW_SPARE0            0x002492f0 /* [RW] Spare Register For Software Test */
#define BCHP_ODU_CHAN_CH1_1_SW_SPARE1            0x002492f4 /* [RW] Spare Register For Software Test */

#endif /* #ifndef BCHP_ODU_CHAN_CH1_1_H__ */

/* End of File */
