/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Thu Dec  4 15:33:17 2014
 *                 Full Compile MD5 Checksum  56e4d67431c9c20b478163a0398e46d2
 *                     (minus title and desc)
 *                 MD5 Checksum               4f20593ca4d982166bb9cd16fec140cc
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15262
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_AIF_WB_ODU_CORE1_2_H__
#define BCHP_AIF_WB_ODU_CORE1_2_H__

/***************************************************************************
 *AIF_WB_ODU_CORE1_2 - AIF WB ODU Core In 1 Register Set
 ***************************************************************************/
#define BCHP_AIF_WB_ODU_CORE1_2_RSTCTL           0x0023d000 /* [RW] RSTCTL */
#define BCHP_AIF_WB_ODU_CORE1_2_HDOFFCTL0        0x0023d004 /* [RW] HDOFFCTL0 */
#define BCHP_AIF_WB_ODU_CORE1_2_HDOFFCTL1        0x0023d008 /* [RW] HDOFFCTL1 */
#define BCHP_AIF_WB_ODU_CORE1_2_HDOFFCTL2        0x0023d00c /* [RW] HDOFFCTL2 */
#define BCHP_AIF_WB_ODU_CORE1_2_HDOFFSTS         0x0023d010 /* [RO] HDOFFSTS */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCTL_PI_SLC0   0x0023d014 /* [RW] DGSCTL_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCTL_PO_SLC0   0x0023d018 /* [RW] DGSCTL_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCTL_PI_SLC1   0x0023d01c /* [RW] DGSCTL_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCTL_PO_SLC1   0x0023d020 /* [RW] DGSCTL_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCTL2          0x0023d024 /* [RW] DGSCTL2 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLP_PI_SLC0   0x0023d028 /* [RW] DGSCLP_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLP_PO_SLC0   0x0023d02c /* [RW] DGSCLP_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLP_PI_SLC1   0x0023d030 /* [RW] DGSCLP_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLP_PO_SLC1   0x0023d034 /* [RW] DGSCLP_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSHIST_PI_SLC0  0x0023d038 /* [RW] DGSHIST_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSHIST_PO_SLC0  0x0023d03c /* [RW] DGSHIST_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSHIST_PI_SLC1  0x0023d040 /* [RW] DGSHIST_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSHIST_PO_SLC1  0x0023d044 /* [RW] DGSHIST_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLPCNT_PI_SLC0 0x0023d048 /* [RW] Clip counter */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLPCNT_PO_SLC0 0x0023d04c /* [RW] Clip counter */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLPCNT_PI_SLC1 0x0023d050 /* [RW] Clip counter */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCLPCNT_PO_SLC1 0x0023d054 /* [RW] Clip counter */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSACCUM_PI_SLC0 0x0023d058 /* [RO] Accumulator */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSACCUM_PO_SLC0 0x0023d05c /* [RO] Accumulator */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSACCUM_PI_SLC1 0x0023d060 /* [RO] Accumulator */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSACCUM_PO_SLC1 0x0023d064 /* [RO] Accumulator */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT011_PI_SLC0 0x0023d068 /* [RW] DGSLUT011_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT010_PI_SLC0 0x0023d06c /* [RW] DGSLUT010_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT001_PI_SLC0 0x0023d070 /* [RW] DGSLUT001_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT000_PI_SLC0 0x0023d074 /* [RW] DGSLUT000_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT111_PI_SLC0 0x0023d078 /* [RW] DGSLUT111_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT110_PI_SLC0 0x0023d07c /* [RW] DGSLUT110_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT101_PI_SLC0 0x0023d080 /* [RW] DGSLUT101_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT100_PI_SLC0 0x0023d084 /* [RW] DGSLUT100_PI_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT011_PO_SLC0 0x0023d088 /* [RW] DGSLUT011_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT010_PO_SLC0 0x0023d08c /* [RW] DGSLUT010_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT001_PO_SLC0 0x0023d090 /* [RW] DGSLUT001_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT000_PO_SLC0 0x0023d094 /* [RW] DGSLUT000_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT111_PO_SLC0 0x0023d098 /* [RW] DGSLUT111_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT110_PO_SLC0 0x0023d09c /* [RW] DGSLUT110_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT101_PO_SLC0 0x0023d0a0 /* [RW] DGSLUT101_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT100_PO_SLC0 0x0023d0a4 /* [RW] DGSLUT100_PO_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT011_PI_SLC1 0x0023d0a8 /* [RW] DGSLUT011_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT010_PI_SLC1 0x0023d0ac /* [RW] DGSLUT010_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT001_PI_SLC1 0x0023d0b0 /* [RW] DGSLUT001_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT000_PI_SLC1 0x0023d0b4 /* [RW] DGSLUT000_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT111_PI_SLC1 0x0023d0b8 /* [RW] DGSLUT111_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT110_PI_SLC1 0x0023d0bc /* [RW] DGSLUT110_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT101_PI_SLC1 0x0023d0c0 /* [RW] DGSLUT101_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT100_PI_SLC1 0x0023d0c4 /* [RW] DGSLUT100_PI_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT011_PO_SLC1 0x0023d0c8 /* [RW] DGSLUT011_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT010_PO_SLC1 0x0023d0cc /* [RW] DGSLUT010_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT001_PO_SLC1 0x0023d0d0 /* [RW] DGSLUT001_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT000_PO_SLC1 0x0023d0d4 /* [RW] DGSLUT000_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT111_PO_SLC1 0x0023d0d8 /* [RW] DGSLUT111_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT110_PO_SLC1 0x0023d0dc /* [RW] DGSLUT110_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT101_PO_SLC1 0x0023d0e0 /* [RW] DGSLUT101_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLUT100_PO_SLC1 0x0023d0e4 /* [RW] DGSLUT100_PO_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLMS_SLC0      0x0023d0e8 /* [RW] DGSLMS_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLMS_SLC1      0x0023d0ec /* [RW] DGSLMS_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSBGLMS_SLC0    0x0023d0f0 /* [RW] DGSBGLMS_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSBGLMS_SLC1    0x0023d0f4 /* [RW] DGSBGLMS_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLMSMU_SLC0    0x0023d0f8 /* [RW] DGSLMSMU_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSLMSMU_SLC1    0x0023d0fc /* [RW] DGSLMSMU_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFD_SLC0    0x0023d100 /* [RW] Digisum2 mdac compensation equalizer coefficient data */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFA_SLC0    0x0023d104 /* [RW] Digisum2 mdac compensation equalizer coefficient address */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFD_SLC1    0x0023d108 /* [RW] Digisum2 mdac compensation equalizer coefficient data */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFA_SLC1    0x0023d10c /* [RW] Digisum2 mdac compensation equalizer coefficient address */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFEN_SLC0   0x0023d110 /* [RW] DGSCOEFEN_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSCOEFEN_SLC1   0x0023d114 /* [RW] DGSCOEFEN_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSA_SLC0      0x0023d118 /* [RW] MDACSA_SLC0 */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSA_SLC1      0x0023d11c /* [RW] MDACSA_SLC1 */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSADU_SLC0    0x0023d120 /* [RW] MDAC Signature Analyzer Duration */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSADU_SLC1    0x0023d124 /* [RW] MDAC Signature Analyzer Duration */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSAOUT_SLC0   0x0023d128 /* [RO] MDAC Signature Analyzer Output */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSAOUT_SLC1   0x0023d12c /* [RO] MDAC Signature Analyzer Output */
#define BCHP_AIF_WB_ODU_CORE1_2_MDACSASTS        0x0023d130 /* [RO] MDACSASTS */
#define BCHP_AIF_WB_ODU_CORE1_2_DOUTCTL          0x0023d134 /* [RW] DOUTCTL */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRINSEL        0x0023d138 /* [RW] Correlator Input select */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRCTL          0x0023d13c /* [RW] CORRCTL */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRFCW          0x0023d140 /* [RW] Correlator DDFS FCW */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRTHR          0x0023d144 /* [RW] Correlator DDFS THR */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRFCWEN        0x0023d148 /* [RW] Correlator FCW and THR load enable. Toggle this bit when finish writing both fcw and thr to take effect. */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRLEN0         0x0023d14c /* [RW] Correlator Accumulation Duration Bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRLEN1         0x0023d150 /* [RW] Correlator Accumulation Duration Bits [35:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX0_PI_SLC0 0x0023d154 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX0_PI_SLC0 0x0023d158 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX0_PI_SLC1 0x0023d15c /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX0_PI_SLC1 0x0023d160 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX0_PO_SLC0 0x0023d164 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX0_PO_SLC0 0x0023d168 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX0_PO_SLC1 0x0023d16c /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX0_PO_SLC1 0x0023d170 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX1_PI_SLC0 0x0023d174 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX1_PI_SLC0 0x0023d178 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX1_PI_SLC1 0x0023d17c /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX1_PI_SLC1 0x0023d180 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX1_PO_SLC0 0x0023d184 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX1_PO_SLC0 0x0023d188 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX1_PO_SLC1 0x0023d18c /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX1_PO_SLC1 0x0023d190 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX2_PI_SLC0 0x0023d194 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX2_PI_SLC0 0x0023d198 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX2_PI_SLC1 0x0023d19c /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX2_PI_SLC1 0x0023d1a0 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX2_PO_SLC0 0x0023d1a4 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX2_PO_SLC0 0x0023d1a8 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX2_PO_SLC1 0x0023d1ac /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX2_PO_SLC1 0x0023d1b0 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX3_PI_SLC0 0x0023d1b4 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX3_PI_SLC0 0x0023d1b8 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX3_PI_SLC1 0x0023d1bc /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX3_PI_SLC1 0x0023d1c0 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX3_PO_SLC0 0x0023d1c4 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX3_PO_SLC0 0x0023d1c8 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI0_DMX3_PO_SLC1 0x0023d1cc /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 I output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRI1_DMX3_PO_SLC1 0x0023d1d0 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 I output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX0_PI_SLC0 0x0023d1d4 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX0_PI_SLC0 0x0023d1d8 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX0_PI_SLC1 0x0023d1dc /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX0_PI_SLC1 0x0023d1e0 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX0_PO_SLC0 0x0023d1e4 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX0_PO_SLC0 0x0023d1e8 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX0_PO_SLC1 0x0023d1ec /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX0_PO_SLC1 0x0023d1f0 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX1_PI_SLC0 0x0023d1f4 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX1_PI_SLC0 0x0023d1f8 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX1_PI_SLC1 0x0023d1fc /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX1_PI_SLC1 0x0023d200 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX1_PO_SLC0 0x0023d204 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX1_PO_SLC0 0x0023d208 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX1_PO_SLC1 0x0023d20c /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX1_PO_SLC1 0x0023d210 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX2_PI_SLC0 0x0023d214 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX2_PI_SLC0 0x0023d218 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX2_PI_SLC1 0x0023d21c /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX2_PI_SLC1 0x0023d220 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX2_PO_SLC0 0x0023d224 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX2_PO_SLC0 0x0023d228 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX2_PO_SLC1 0x0023d22c /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX2_PO_SLC1 0x0023d230 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX3_PI_SLC0 0x0023d234 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX3_PI_SLC0 0x0023d238 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX3_PI_SLC1 0x0023d23c /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX3_PI_SLC1 0x0023d240 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX3_PO_SLC0 0x0023d244 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX3_PO_SLC0 0x0023d248 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ0_DMX3_PO_SLC1 0x0023d24c /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 Q output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRQ1_DMX3_PO_SLC1 0x0023d250 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 Q output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX0_PI_SLC0 0x0023d254 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX0_PI_SLC0 0x0023d258 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX0_PI_SLC1 0x0023d25c /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX0_PI_SLC1 0x0023d260 /* [RO] Correlator Demux Path 0, Ping Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX0_PO_SLC0 0x0023d264 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX0_PO_SLC0 0x0023d268 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX0_PO_SLC1 0x0023d26c /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX0_PO_SLC1 0x0023d270 /* [RO] Correlator Demux Path 0, Pong Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX1_PI_SLC0 0x0023d274 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX1_PI_SLC0 0x0023d278 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX1_PI_SLC1 0x0023d27c /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX1_PI_SLC1 0x0023d280 /* [RO] Correlator Demux Path 1, Ping Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX1_PO_SLC0 0x0023d284 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX1_PO_SLC0 0x0023d288 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX1_PO_SLC1 0x0023d28c /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX1_PO_SLC1 0x0023d290 /* [RO] Correlator Demux Path 1, Pong Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX2_PI_SLC0 0x0023d294 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX2_PI_SLC0 0x0023d298 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX2_PI_SLC1 0x0023d29c /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX2_PI_SLC1 0x0023d2a0 /* [RO] Correlator Demux Path 2, Ping Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX2_PO_SLC0 0x0023d2a4 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX2_PO_SLC0 0x0023d2a8 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX2_PO_SLC1 0x0023d2ac /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX2_PO_SLC1 0x0023d2b0 /* [RO] Correlator Demux Path 2, Pong Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX3_PI_SLC0 0x0023d2b4 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX3_PI_SLC0 0x0023d2b8 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX3_PI_SLC1 0x0023d2bc /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX3_PI_SLC1 0x0023d2c0 /* [RO] Correlator Demux Path 3, Ping Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX3_PO_SLC0 0x0023d2c4 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX3_PO_SLC0 0x0023d2c8 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 0 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP0_DMX3_PO_SLC1 0x0023d2cc /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 P output bits [31:0] */
#define BCHP_AIF_WB_ODU_CORE1_2_CORRP1_DMX3_PO_SLC1 0x0023d2d0 /* [RO] Correlator Demux Path 3, Pong Lane, Slice 1 P output bits [59:32] */
#define BCHP_AIF_WB_ODU_CORE1_2_TIMERCTL0        0x0023d2d4 /* [RW] TIMERCTL0 */
#define BCHP_AIF_WB_ODU_CORE1_2_TIMERCTL1        0x0023d2d8 /* [RW] TIMERCTL1 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSEPCTL_SLC0    0x0023d2dc /* [RW] MDAC EQ Error Power Control Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX0_PI_SLC0_INT_WDATA 0x0023d2e0 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX0_PO_SLC0_INT_WDATA 0x0023d2e4 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX1_PI_SLC0_INT_WDATA 0x0023d2e8 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX1_PO_SLC0_INT_WDATA 0x0023d2ec /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX2_PI_SLC0_INT_WDATA 0x0023d2f0 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX2_PO_SLC0_INT_WDATA 0x0023d2f4 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX3_PI_SLC0_INT_WDATA 0x0023d2f8 /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX3_PO_SLC0_INT_WDATA 0x0023d2fc /* [RW] Leaky averager integrator write data (tc1.31) for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX0_PI_SLC0_ERRP 0x0023d300 /* [RO] Mdac eq err power estimate demux path 0, ping lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX0_PI_SLC0_ERRP 0x0023d304 /* [RO] Mdac eq err power estimate demux path 0, ping lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX0_PO_SLC0_ERRP 0x0023d308 /* [RO] Mdac eq err power estimate demux path 0, pong lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX0_PO_SLC0_ERRP 0x0023d30c /* [RO] Mdac eq err power estimate demux path 0, pong lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX1_PI_SLC0_ERRP 0x0023d310 /* [RO] Mdac eq err power estimate demux path 1, ping lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX1_PI_SLC0_ERRP 0x0023d314 /* [RO] Mdac eq err power estimate demux path 1, ping lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX1_PO_SLC0_ERRP 0x0023d318 /* [RO] Mdac eq err power estimate demux path 1, pong lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX1_PO_SLC0_ERRP 0x0023d31c /* [RO] Mdac eq err power estimate demux path 1, pong lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX2_PI_SLC0_ERRP 0x0023d320 /* [RO] Mdac eq err power estimate demux path 2, ping lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX2_PI_SLC0_ERRP 0x0023d324 /* [RO] Mdac eq err power estimate demux path 2, ping lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX2_PO_SLC0_ERRP 0x0023d328 /* [RO] Mdac eq err power estimate demux path 2, pong lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX2_PO_SLC0_ERRP 0x0023d32c /* [RO] Mdac eq err power estimate demux path 2, pong lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX3_PI_SLC0_ERRP 0x0023d330 /* [RO] Mdac eq err power estimate demux path 3, ping lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX3_PI_SLC0_ERRP 0x0023d334 /* [RO] Mdac eq err power estimate demux path 3, ping lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX3_PO_SLC0_ERRP 0x0023d338 /* [RO] Mdac eq err power estimate demux path 3, pong lane stage 1. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX3_PO_SLC0_ERRP 0x0023d33c /* [RO] Mdac eq err power estimate demux path 3, pong lane stage 2. for slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_DGSEPCTL_SLC1    0x0023d340 /* [RW] MDAC EQ Error Power Control Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX0_PI_SLC1_INT_WDATA 0x0023d344 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX0_PO_SLC1_INT_WDATA 0x0023d348 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX1_PI_SLC1_INT_WDATA 0x0023d34c /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX1_PO_SLC1_INT_WDATA 0x0023d350 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX2_PI_SLC1_INT_WDATA 0x0023d354 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX2_PO_SLC1_INT_WDATA 0x0023d358 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX3_PI_SLC1_INT_WDATA 0x0023d35c /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_DMX3_PO_SLC1_INT_WDATA 0x0023d360 /* [RW] Leaky averager integrator write data (tc1.31) for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX0_PI_SLC1_ERRP 0x0023d364 /* [RO] Mdac eq err power estimate demux path 0, ping lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX0_PI_SLC1_ERRP 0x0023d368 /* [RO] Mdac eq err power estimate demux path 0, ping lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX0_PO_SLC1_ERRP 0x0023d36c /* [RO] Mdac eq err power estimate demux path 0, pong lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX0_PO_SLC1_ERRP 0x0023d370 /* [RO] Mdac eq err power estimate demux path 0, pong lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX1_PI_SLC1_ERRP 0x0023d374 /* [RO] Mdac eq err power estimate demux path 1, ping lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX1_PI_SLC1_ERRP 0x0023d378 /* [RO] Mdac eq err power estimate demux path 1, ping lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX1_PO_SLC1_ERRP 0x0023d37c /* [RO] Mdac eq err power estimate demux path 1, pong lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX1_PO_SLC1_ERRP 0x0023d380 /* [RO] Mdac eq err power estimate demux path 1, pong lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX2_PI_SLC1_ERRP 0x0023d384 /* [RO] Mdac eq err power estimate demux path 2, ping lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX2_PI_SLC1_ERRP 0x0023d388 /* [RO] Mdac eq err power estimate demux path 2, ping lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX2_PO_SLC1_ERRP 0x0023d38c /* [RO] Mdac eq err power estimate demux path 2, pong lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX2_PO_SLC1_ERRP 0x0023d390 /* [RO] Mdac eq err power estimate demux path 2, pong lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX3_PI_SLC1_ERRP 0x0023d394 /* [RO] Mdac eq err power estimate demux path 3, ping lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX3_PI_SLC1_ERRP 0x0023d398 /* [RO] Mdac eq err power estimate demux path 3, ping lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S1_DMX3_PO_SLC1_ERRP 0x0023d39c /* [RO] Mdac eq err power estimate demux path 3, pong lane stage 1. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_DGSEP_S2_DMX3_PO_SLC1_ERRP 0x0023d3a0 /* [RO] Mdac eq err power estimate demux path 3, pong lane stage 2. for slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_AGCCTL2          0x0023d3a4 /* [RW] AGC Control 2 */
#define BCHP_AIF_WB_ODU_CORE1_2_AGCDECRATE       0x0023d3a8 /* [RW] Decimate rate */
#define BCHP_AIF_WB_ODU_CORE1_2_AGCCTL1          0x0023d3ac /* [RW] AGC Control 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_AGCTHRA1         0x0023d3b0 /* [RW] AGC Threshold Adjust Control 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_AGC_LF_INT_WDATA 0x0023d3b4 /* [RW] Shift accumulator integrator write data (tc8.26) */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_AGC_LA_INT_WDATA 0x0023d3b8 /* [RW] Leaky averager integrator write data (tc1.31) */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_AGC_CTRL_LF_INT_WDATA 0x0023d3bc /* [RW] Shift accumulator integrator write data (tc4.19) */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_AGC_CTRL_LA_INT_WDATA 0x0023d3c0 /* [RW] Leaky averager integrator write data (tc1.20) */
#define BCHP_AIF_WB_ODU_CORE1_2_AGCTHRA2         0x0023d3c4 /* [RW] AGC Threshold Adjust Control 2 */
#define BCHP_AIF_WB_ODU_CORE1_2_PGACLKCTL        0x0023d3c8 /* [RW] PGACLKCTL */
#define BCHP_AIF_WB_ODU_CORE1_2_PGALUTD          0x0023d3cc /* [RW] PGA Look up table data */
#define BCHP_AIF_WB_ODU_CORE1_2_PGALUTA          0x0023d3d0 /* [RW] PGALUTA */
#define BCHP_AIF_WB_ODU_CORE1_2_NRNOTCHCTL       0x0023d3d4 /* [RW] NR NOTCH Control */
#define BCHP_AIF_WB_ODU_CORE1_2_NRAGCTHR         0x0023d3d8 /* [RW] NR AGC Threshold Control */
#define BCHP_AIF_WB_ODU_CORE1_2_NRDCOCTL_PI_SLC0 0x0023d3dc /* [RW] NR DCO Control Ping Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_DCO_INT_WDATA_PI_SLC0 0x0023d3e0 /* [RW] DCO integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRDCOCTL_PO_SLC0 0x0023d3e4 /* [RW] NR DCO Control Pong Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_DCO_INT_WDATA_PO_SLC0 0x0023d3e8 /* [RW] DCO integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRDCOCTL_PI_SLC1 0x0023d3ec /* [RW] NR DCO Control Ping Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_DCO_INT_WDATA_PI_SLC1 0x0023d3f0 /* [RW] DCO integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRDCOCTL_PO_SLC1 0x0023d3f4 /* [RW] NR DCO Control Pong Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_DCO_INT_WDATA_PO_SLC1 0x0023d3f8 /* [RW] DCO integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRNOTCHCTL_PI_SLC0 0x0023d3fc /* [RW] NR NOTCH Control Ping Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_NOTCH_INT_WDATA_PI_SLC0 0x0023d400 /* [RW] NOTCH integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRNOTCHCTL_PO_SLC0 0x0023d404 /* [RW] NR NOTCH Control Pong Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_NOTCH_INT_WDATA_PO_SLC0 0x0023d408 /* [RW] NOTCH integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRNOTCHCTL_PI_SLC1 0x0023d40c /* [RW] NR NOTCH Control Ping Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_NOTCH_INT_WDATA_PI_SLC1 0x0023d410 /* [RW] NOTCH integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRNOTCHCTL_PO_SLC1 0x0023d414 /* [RW] NR NOTCH Control Pong Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_NOTCH_INT_WDATA_PO_SLC1 0x0023d418 /* [RW] NOTCH integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRDCOCTL_THR     0x0023d41c /* [RW] NR DCO Control AGC Threshold */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_DCO_INT_WDATA_THR 0x0023d420 /* [RW] DCO integrator write data */
#define BCHP_AIF_WB_ODU_CORE1_2_NRAGCCTL_PI_SLC0 0x0023d424 /* [RW] NR AGC Control Ping Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LF_INT_WDATA_PI_SLC0 0x0023d428 /* [RW] AGC Loop filter integrator write data (tc0.54) for lane 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LA_INT_WDATA_PI_SLC0 0x0023d42c /* [RW] AGC Leaky averager integrator write data (tc1.29) for lane 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_NRAGCCTL_PO_SLC0 0x0023d430 /* [RW] NR AGC Control Ping Lane Slice 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LF_INT_WDATA_PO_SLC0 0x0023d434 /* [RW] AGC Loop filter integrator write data (tc0.54) for lane 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LA_INT_WDATA_PO_SLC0 0x0023d438 /* [RW] AGC Leaky averager integrator write data (tc1.29) for lane 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_NRAGCCTL_PI_SLC1 0x0023d43c /* [RW] NR AGC Control Ping Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LF_INT_WDATA_PI_SLC1 0x0023d440 /* [RW] AGC Loop filter integrator write data (tc0.54) for lane 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LA_INT_WDATA_PI_SLC1 0x0023d444 /* [RW] AGC Leaky averager integrator write data (tc1.29) for lane 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_NRAGCCTL_PO_SLC1 0x0023d448 /* [RW] NR AGC Control Ping Lane Slice 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LF_INT_WDATA_PO_SLC1 0x0023d44c /* [RW] AGC Loop filter integrator write data (tc0.54) for lane 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_REG_NR_AGC_LA_INT_WDATA_PO_SLC1 0x0023d450 /* [RW] AGC Leaky averager integrator write data (tc1.29) for lane 1 */
#define BCHP_AIF_WB_ODU_CORE1_2_CORE_SW_SPARE0   0x0023d454 /* [RW] Core software spare register 0 */
#define BCHP_AIF_WB_ODU_CORE1_2_CORE_SW_SPARE1   0x0023d458 /* [RW] Core software spare register 1 */

#endif /* #ifndef BCHP_AIF_WB_ODU_CORE1_2_H__ */

/* End of File */
