#
# Build android CDC DHD and SDIO Dongle Image(on Ubuntu). Package DHD sources
# with all sdio dongle images
#
# $Id$
#

PARENT_MAKEFILE := android-dhd.mk
DEFAULT_TARGET  := default
ALL_TARGET      := all

$(DEFAULT_TARGET): $(ALL_TARGET)

# Common defs and undefs are in included common makefile
COMMONDEFS        := BCMDONGLEHOST DHD_GPL linux
COMMONUNDEFS      := BCMINTERNAL BCMDBG MACOSX _WIN32 _RTE_ EFI __NetBSD__
COMMONUNDEFS      += __ECOS vxworks TARGETOS_nucleus _MSC_VER _WIN64 MFGTEST WL_LOCATOR
COMMONUNDEFS      += BCMPERFSTATS BCMTSTAMPEDLOGS BCMDBG_PKT DSLCPE_DELAY
COMMONUNDEFS      += CONFIG_PCMCIA CONFIG_PCMCIA_MODULE BCMDBG_MEM ILSIM
COMMONUNDEFS      += DONGLEBUILD BCMROMOFFLOAD BCMROMBUILD
COMMONUNDEFS      += DOS PCBIOS NDIS _CFE_ _MINOSL_ UNDER_CE
COMMONUNDEFS      += WLLMAC WLLMAC_ENABLED OLYMPIC_RWL
COMMONUNDEFS      += __BOB__ CONFIG_XIP NDIS60
COMMONUNDEFS      += WLTEST DHD_SPROM BCMDBUS
COMMONUNDEFS      += BCMDBG_ERR BCMDBG_ASSERT BCMDBG_DUMP BCMDBG_TRAP
COMMONUNDEFS      += BCMJTAG NOTYET BCMECICOEX BINOSL mips __vxworks
COMMONUNDEFS      += USER_MODE IL_BIGENDIAN BCMHND74K
COMMONUNDEFS      += APSTA_PINGTEST WLC_HIGH WLC_LOW
COMMONUNDEFS      += SI_SPROM_PROBE SI_ENUM_BASE_VARIABLE OSLREGOPS BCMASSERT_SUPPORT
COMMONUNDEFS      += EXT_STA  ATE_BUILD PATCH_SDPCMDEV_STRUCT WLC_PATCH
COMMONUNDEFS      += SERDOWNLOAD BCM_BOOTLOADER
COMMONUNDEFS      += USBAP CTFMAP PKTCTFMAP __mips__ WLC_HIGH_ONLY
COMMONUNDEFS      += __FreeBSD__ BCM_ROUTER_DHD DHD_AWDL WLAWDL

BRAND       ?= android-external-dongle
OEM_LIST    ?= android
OEM_LIST_OPEN_SRC ?=

include $(PARENT_MAKEFILE)
