#
# Build Linux CDC DHD (on linux) from trunk. Package DHD sources
#
# $Id$
#

PARENT_MAKEFILE := linux-dhd.mk
DEFAULT_TARGET  := default
ALL_TARGET      := all

$(DEFAULT_TARGET): $(ALL_TARGET)

# Common defs and undefs are in included common makefile
COMMONDEFS        := BCMDONGLEHOST BCMSDIO DHD_GPL linux
COMMONUNDEFS      := BCMINTERNAL BCMDBG MACOSX _WIN32 _RTE_ EFI __NetBSD__
COMMONUNDEFS      += __ECOS vxworks TARGETOS_nucleus _MSC_VER _WIN64 MFGTEST
COMMONUNDEFS      += WL_LOCATOR BCMPERFSTATS BCMTSTAMPEDLOGS BCMDBG_PKT
COMMONUNDEFS      += CONFIG_PCMCIA CONFIG_PCMCIA_MODULE BCMDBG_MEM ILSIM
COMMONUNDEFS      += DONGLEBUILD BCMROMOFFLOAD BCMROMBUILD
COMMONUNDEFS      += DOS PCBIOS NDIS _CFE_ _MINOSL_ UNDER_CE
COMMONUNDEFS      += WIN7 WLLMAC WLLMAC_ENABLED OLYMPIC_RWL
COMMONUNDEFS      += __BOB__ BCMWAPI_WPI BCMWAPI_WAI CONFIG_XIP NDIS60
COMMONUNDEFS      += WLTEST DHD_SPROM BCMDBUS
COMMONUNDEFS      += BCMDBG_ERR BCMDBG_ASSERT BCMDBG_DUMP BCMDBG_TRAP
COMMONUNDEFS      += BCMJTAG NOTYET BCMECICOEX BINOSL mips __vxworks
COMMONUNDEFS      += USER_MODE IL_BIGENDIAN BCMHND74K
COMMONUNDEFS      += WLC_HIGH WLC_LOW SI_SPROM_PROBE SI_ENUM_BASE_VARIABLE
COMMONUNDEFS      += OSLREGOPS BCMASSERT_SUPPORT
COMMONUNDEFS      += EXT_STA  ATE_BUILD PATCH_SDPCMDEV_STRUCT WLC_PATCH
COMMONUNDEFS      += SERDOWNLOAD BCM_BOOTLOADER
COMMONUNDEFS      += USBAP CTFMAP PKTCTFMAP __mips__ WLC_HIGH_ONLY
COMMONUNDEFS      += __FreeBSD__

# Common defs and undefs: usb specified (this line can be delete later)
COMMONDEFS        += DHD_GPLBCMDBUS
COMMONUNDEFS      += BCMNVRAMR BCMNVRAMW WL_NVRAM_FILE
COMMONUNDEFS      += WLNOKIA


BRAND       ?= linux-external-dhd
OEM_LIST    ?= bcm android
OEM_LIST_OPEN_SRC ?= bcm android

include $(PARENT_MAKEFILE)

# Dongle image that needs to be embedded into host, if BCMEMBEDIMAGE is ON
# List images to be embedded for each oem
EMBED_IMAGE_bcm     ?= $(strip $(shell egrep "DNGL_IMAGE_NAME.*=" src/dhd/linux/Makefile 2> $(NULL) | awk -F= '{printf("%s",$$2);}'))
EMBED_IMAGE_android ?=

# WARN: Do not add mfgtest images to following list.
# NOTE: List images needed for each <oem>

RLS_IMAGES_bcm      +=

RLS_IMAGES_nokia    +=

RLS_IMAGES_android  +=
