#!/bin/bash
#
# Installer cleanup script for
# Broadcom 802.11abg Networking Device Driver Install Package
#
# $ Copyright Broadcom Corporation $
#
#
# <<Broadcom-WL-IPTag/Private1743:>>
#
# $Id: postflight,v 1.6.8.1 2010-10-25 17:43:31 Exp $
#

# Move the Apple distributed Brcm drivers out of the way by renaming
# them to <oldname>.hide

PRODUCT=AirPortBroadcom43XX
KEXT=${PRODUCT}.kext

VERT_PRODUCT=BrcmVirtEther
VERT_KEXT=${VERT_PRODUCT}.kext

oldkextdir=/System/Library/Extensions/IO80211Family.kext/Contents/PlugIns

if [ ! -d $oldkextdir ]; then
	exit
fi

cd $oldkextdir

for oldkext in `ls -d *Brcm*.kext`; do
	if [ -d $oldkext ]; then
		rm -f -r ${oldkext}.hide
		mv $oldkext ${oldkext}.hide
	fi
done

newkext=/System/Library/Extensions/${KEXT}

if [ -d $newkext ]; then
	sudo chown -R root:wheel $newkext
fi

virtkext=/System/Library/Extensions/${VERT_PRODUCT}
if [ -d $virtkext ]; then
	sudo chown -R root:wheel $virtkext
fi

sudo touch /System/Library/Extensions
