ifndef BCM_PRINT_KBUILD_ENV_ONLY

obj-m := astra_tdrv.o

ccflags-y := \
	-I$(TOP_DIR)/linux/bcm_astra

else

$(shell echo BCM_KBUILD_CFLAGS:=$(KBUILD_CFLAGS) $(KBUILD_CFLAGS_MODULE) >&2 )
$(shell echo BCM_KBUILD_LDFLAGS:=$(LDFLAGS) $(LDFLAGS_MODULE) $(KBUILD_LDFLAGS_MODULE) >&2)

endif
