#define B_ESTB_CFG_NUM_CFG_FILES 3
#define NUM_NODES_B_ESTB_CFG_LABEL_PERM  17
struct b_estb_cfg_node node_block_B_ESTB_CFG_LABEL_PERM [17];
struct b_estb_cfg_node default_node_block_B_ESTB_CFG_LABEL_PERM [17] = {
    /* idx, flag, type, label, parent, next, prev, field len, state, name, data ptr/sub dir, data len/data node, data pad/unused */
    {0, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/perm", {{IDX_INVALID, IDX_INVALID,0}}},
    {1, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/perm/estb", {{IDX_INVALID, IDX_INVALID,0}}},
    {2, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_ID, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/perm/estb/vendor_id", {{0,  4, 0}}},
    {3, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_MAC_ADDR, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  6, "/perm/estb/mac_addr", {{4,  6, 2}}},
    {4, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_ROOT_CA_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/root_ca_cert", {{12,  4096, 0}}},
    {5, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CA_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/device_ca_cert", {{4108,  4096, 0}}},
    {6, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/device_cert", {{8204,  4096, 0}}},
    {7, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_CV_ROOT_CA_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/cv_root_ca_cert", {{12300,  4096, 0}}},
    {8, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_CV_CA_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/cv_ca_cert", {{16396,  4096, 0}}},
    {9, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_APP_CV_CA_CERT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/app_cv_ca_cert", {{20492,  4096, 0}}},
    {10, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PUB_KEY, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/dev_cert_pub_key", {{24588,  4096, 0}}},
    {11, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PRIV_KEY, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/dev_cert_priv_key", {{28684,  4096, 0}}},
    {12, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DH_PRIME, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/dh_prime", {{32780,  4096, 0}}},
    {13, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_PERM_ESTB_DH_BASE, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/perm/estb/dh_base", {{36876,  4096, 0}}},
    {14, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_PERM_ESTB_HW_VERSION_ID, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/perm/estb/hw_version_id", {{40972,  4, 0}}},
    {15, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_PERM_ESTB_MODEL_NAME, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/perm/estb/model_name", {{40976,  128, 0}}},
    {16, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_NAME, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/perm/estb/vendor_name", {{41104,  128, 0}}},
};

unsigned int default_B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_ID =  0x0;

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_MAC_ADDR[] = {0x00,0x01,0x18,0xaa,0xbb,0xcc};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_ROOT_CA_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CA_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_CV_ROOT_CA_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_CV_CA_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_APP_CV_CA_CERT[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PUB_KEY[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PRIV_KEY[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DH_PRIME[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_PERM_ESTB_DH_BASE[] = {0x00,0x00,0x00,0x00};

unsigned int default_B_ESTB_CFG_LABEL_PERM_ESTB_HW_VERSION_ID =  0x7459;

char default_B_ESTB_CFG_LABEL_PERM_ESTB_MODEL_NAME[] =  "OCAP-STB";

char default_B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_NAME[] =  "BROADCOM";

#define NUM_NODES_B_ESTB_CFG_LABEL_DYN  32
struct b_estb_cfg_node node_block_B_ESTB_CFG_LABEL_DYN [32];
struct b_estb_cfg_node default_node_block_B_ESTB_CFG_LABEL_DYN [32] = {
    /* idx, flag, type, label, parent, next, prev, field len, state, name, data ptr/sub dir, data len/data node, data pad/unused */
    {0, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/dyn", {{IDX_INVALID, IDX_INVALID,0}}},
    {1, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/dyn/estb", {{IDX_INVALID, IDX_INVALID,0}}},
    {2, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_MANU_CVC, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/manu_cvc", {{0,  4096, 0}}},
    {3, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_COSIGNER_CVC, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/cosigner_cvc", {{4096,  4096, 0}}},
    {4, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_APP_MANU_CVC, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/app_manu_cvc", {{8192,  4096, 0}}},
    {5, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_APP_COSIGNER_CVC, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/app_cosigner_cvc", {{12288,  4096, 0}}},
    {6, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_DH_KEY, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/dh_key", {{16384,  4096, 0}}},
    {7, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_AUTH_KEY, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4096, "/dyn/estb/auth_key", {{20480,  4096, 0}}},
    {8, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_CARD_ID, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  8, "/dyn/estb/card_id", {{24576,  8, 0}}},
    {9, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_HOST_ID, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  5, "/dyn/estb/host_id", {{24584,  5, 3}}},
    {10, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name", {{24592,  128, 0}}},
    {11, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_1, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_1", {{24720,  128, 0}}},
    {12, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_2, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_2", {{24848,  128, 0}}},
    {13, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_3, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_3", {{24976,  128, 0}}},
    {14, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_4, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_4", {{25104,  128, 0}}},
    {15, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_5, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_5", {{25232,  128, 0}}},
    {16, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_6, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_6", {{25360,  128, 0}}},
    {17, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_7, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/fw_name_7", {{25488,  128, 0}}},
    {18, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name", {{25616,  128, 0}}},
    {19, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_1, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_1", {{25744,  128, 0}}},
    {20, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_2, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_2", {{25872,  128, 0}}},
    {21, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_3, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_3", {{26000,  128, 0}}},
    {22, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_4, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_4", {{26128,  128, 0}}},
    {23, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_5, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_5", {{26256,  128, 0}}},
    {24, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_6, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_6", {{26384,  128, 0}}},
    {25, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_7, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/dyn/estb/new_fw_name_7", {{26512,  128, 0}}},
    {26, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_DYN_ESTB_GROUP_ID, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/dyn/estb/group_id", {{26640,  4, 0}}},
    {27, 0,  NODE_TYPE_BIN,  B_ESTB_CFG_LABEL_DYN_ESTB_LANG_CODE, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  3, "/dyn/estb/lang_code", {{26644,  3, 1}}},
    {28, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_DYN_ESTB_IMAGE_STATUS, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/dyn/estb/image_status", {{26648,  4, 0}}},
    {29, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_COUNT, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/dyn/estb/download_count", {{26652,  4, 0}}},
    {30, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_FAILED_STATUS, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/dyn/estb/download_failed_status", {{26656,  4, 0}}},
    {31, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_DYN_ESTB_CODE_DOWNLOAD_STATUS, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/dyn/estb/code_download_status", {{26660,  4, 0}}},
};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_MANU_CVC[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_COSIGNER_CVC[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_APP_MANU_CVC[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_APP_COSIGNER_CVC[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_DH_KEY[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_AUTH_KEY[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_CARD_ID[] = {0x00,0x00,0x00,0x00};

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_HOST_ID[] = {0x00,0x00,0x00,0x00,0x00};

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME[] =  "obj";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_1[] =  "obj1";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_2[] =  "obj2";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_3[] =  "obj3";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_4[] =  "obj4";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_5[] =  "obj5";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_6[] =  "obj6";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_7[] =  "obj7";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME[] =  "tmp";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_1[] =  "tmp1";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_2[] =  "tmp2";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_3[] =  "tmp3";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_4[] =  "tmp4";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_5[] =  "tmp5";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_6[] =  "tmp6";

char default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_7[] =  "tmp7";

unsigned int default_B_ESTB_CFG_LABEL_DYN_ESTB_GROUP_ID =  0;

unsigned char default_B_ESTB_CFG_LABEL_DYN_ESTB_LANG_CODE[] = {0x65,0x6e,0x67};

unsigned int default_B_ESTB_CFG_LABEL_DYN_ESTB_IMAGE_STATUS =  1;

unsigned int default_B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_COUNT =  0;

unsigned int default_B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_FAILED_STATUS =  1;

unsigned int default_B_ESTB_CFG_LABEL_DYN_ESTB_CODE_DOWNLOAD_STATUS =  2;

#define NUM_NODES_B_ESTB_CFG_LABEL_SYS  6
struct b_estb_cfg_node node_block_B_ESTB_CFG_LABEL_SYS [6];
struct b_estb_cfg_node default_node_block_B_ESTB_CFG_LABEL_SYS [6] = {
    /* idx, flag, type, label, parent, next, prev, field len, state, name, data ptr/sub dir, data len/data node, data pad/unused */
    {0, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/sys", {{IDX_INVALID, IDX_INVALID,0}}},
    {1, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/sys/cfe/", {{IDX_INVALID, IDX_INVALID,0}}},
    {2, 0,  NODE_TYPE_TXT,  B_ESTB_CFG_LABEL_SYS_CFE_VER, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  128, "/sys/cfe/version", {{0,  128, 0}}},
    {3, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_SYS_CFE_CUR_BANK, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/sys/cfe/cur_bank", {{128,  4, 0}}},
    {4, 0,  NODE_TYPE_DIR, B_ESTB_CFG_LABEL_RSVD0, IDX_INVALID, IDX_INVALID, IDX_INVALID, 0, 0, "/sys/estb", {{IDX_INVALID, IDX_INVALID,0}}},
    {5, 0,  NODE_TYPE_UINT32,  B_ESTB_CFG_LABEL_SYS_ESTB_REBOOT_TYPE, IDX_INVALID, IDX_INVALID, IDX_INVALID, NODE_STATE_INIT,  4, "/sys/estb/reboot_type", {{132,  4, 0}}},
};

char default_B_ESTB_CFG_LABEL_SYS_CFE_VER[] =  "CFE version";

unsigned int default_B_ESTB_CFG_LABEL_SYS_CFE_CUR_BANK =  0;

unsigned int default_B_ESTB_CFG_LABEL_SYS_ESTB_REBOOT_TYPE =  0;

static struct b_estb_cfg_ctl default_ctl_block_B_ESTB_CFG_LABEL_PERM = {
      B_ESTB_CFG_LABEL_PERM,
      B_ESTB_CFG_DEFAULT_PERM_CFG,
      0,
      DEFAULT_B_ESTB_CFG_HDR,
      node_block_B_ESTB_CFG_LABEL_PERM,
      NUM_NODES_B_ESTB_CFG_LABEL_PERM,
      NULL,
      0,
      0,
      0,
};

static struct b_estb_cfg_ctl default_ctl_block_B_ESTB_CFG_LABEL_DYN = {
      B_ESTB_CFG_LABEL_DYN,
      B_ESTB_CFG_DEFAULT_DYN_CFG,
      0,
      DEFAULT_B_ESTB_CFG_HDR,
      node_block_B_ESTB_CFG_LABEL_DYN,
      NUM_NODES_B_ESTB_CFG_LABEL_DYN,
      NULL,
      0,
      0,
      0,
};

static struct b_estb_cfg_ctl default_ctl_block_B_ESTB_CFG_LABEL_SYS = {
      B_ESTB_CFG_LABEL_SYS,
      B_ESTB_CFG_DEFAULT_SYS_CFG,
      0,
      DEFAULT_B_ESTB_CFG_HDR,
      node_block_B_ESTB_CFG_LABEL_SYS,
      NUM_NODES_B_ESTB_CFG_LABEL_SYS,
      NULL,
      0,
      0,
      0,
};

static struct b_estb_cfg_ctl ctl_block[B_ESTB_CFG_NUM_CFG_FILES];
static struct b_estb_cfg_info info_block[B_ESTB_CFG_NUM_CFG_FILES] = {
        {B_ESTB_CFG_LABEL_PERM, "/perm"},
        {B_ESTB_CFG_LABEL_DYN, "/dyn"},
        {B_ESTB_CFG_LABEL_SYS, "/sys"},
};

static void b_estb_cfg_init_values(int idx) { 
        if (idx == B_ESTB_CFG_LABEL_PERM) {
                SET_DEFAULT_NODE_VALUE(node_block_B_ESTB_CFG_LABEL_PERM, default_node_block_B_ESTB_CFG_LABEL_PERM);
                SET_DEFAULT_CTL_VALUE(B_ESTB_CFG_LABEL_PERM, default_ctl_block_B_ESTB_CFG_LABEL_PERM);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 2, default_B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_ID);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 3, default_B_ESTB_CFG_LABEL_PERM_ESTB_MAC_ADDR);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 4, default_B_ESTB_CFG_LABEL_PERM_ESTB_ROOT_CA_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 5, default_B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CA_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 6, default_B_ESTB_CFG_LABEL_PERM_ESTB_DEVICE_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 7, default_B_ESTB_CFG_LABEL_PERM_ESTB_CV_ROOT_CA_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 8, default_B_ESTB_CFG_LABEL_PERM_ESTB_CV_CA_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 9, default_B_ESTB_CFG_LABEL_PERM_ESTB_APP_CV_CA_CERT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 10, default_B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PUB_KEY);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 11, default_B_ESTB_CFG_LABEL_PERM_ESTB_DEV_CERT_PRIV_KEY);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 12, default_B_ESTB_CFG_LABEL_PERM_ESTB_DH_PRIME);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 13, default_B_ESTB_CFG_LABEL_PERM_ESTB_DH_BASE);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 14, default_B_ESTB_CFG_LABEL_PERM_ESTB_HW_VERSION_ID);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 15, default_B_ESTB_CFG_LABEL_PERM_ESTB_MODEL_NAME);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_PERM, 16, default_B_ESTB_CFG_LABEL_PERM_ESTB_VENDOR_NAME);
        };

        if (idx == B_ESTB_CFG_LABEL_DYN) {
                SET_DEFAULT_NODE_VALUE(node_block_B_ESTB_CFG_LABEL_DYN, default_node_block_B_ESTB_CFG_LABEL_DYN);
                SET_DEFAULT_CTL_VALUE(B_ESTB_CFG_LABEL_DYN, default_ctl_block_B_ESTB_CFG_LABEL_DYN);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 2, default_B_ESTB_CFG_LABEL_DYN_ESTB_MANU_CVC);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 3, default_B_ESTB_CFG_LABEL_DYN_ESTB_COSIGNER_CVC);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 4, default_B_ESTB_CFG_LABEL_DYN_ESTB_APP_MANU_CVC);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 5, default_B_ESTB_CFG_LABEL_DYN_ESTB_APP_COSIGNER_CVC);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 6, default_B_ESTB_CFG_LABEL_DYN_ESTB_DH_KEY);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 7, default_B_ESTB_CFG_LABEL_DYN_ESTB_AUTH_KEY);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 8, default_B_ESTB_CFG_LABEL_DYN_ESTB_CARD_ID);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 9, default_B_ESTB_CFG_LABEL_DYN_ESTB_HOST_ID);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 10, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 11, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_1);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 12, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_2);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 13, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_3);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 14, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_4);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 15, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_5);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 16, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_6);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 17, default_B_ESTB_CFG_LABEL_DYN_ESTB_FW_NAME_7);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 18, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 19, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_1);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 20, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_2);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 21, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_3);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 22, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_4);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 23, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_5);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 24, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_6);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 25, default_B_ESTB_CFG_LABEL_DYN_ESTB_NEW_FW_NAME_7);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 26, default_B_ESTB_CFG_LABEL_DYN_ESTB_GROUP_ID);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 27, default_B_ESTB_CFG_LABEL_DYN_ESTB_LANG_CODE);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 28, default_B_ESTB_CFG_LABEL_DYN_ESTB_IMAGE_STATUS);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 29, default_B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_COUNT);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 30, default_B_ESTB_CFG_LABEL_DYN_ESTB_DOWNLOAD_FAILED_STATUS);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_DYN, 31, default_B_ESTB_CFG_LABEL_DYN_ESTB_CODE_DOWNLOAD_STATUS);
        };

        if (idx == B_ESTB_CFG_LABEL_SYS) {
                SET_DEFAULT_NODE_VALUE(node_block_B_ESTB_CFG_LABEL_SYS, default_node_block_B_ESTB_CFG_LABEL_SYS);
                SET_DEFAULT_CTL_VALUE(B_ESTB_CFG_LABEL_SYS, default_ctl_block_B_ESTB_CFG_LABEL_SYS);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_SYS, 2, default_B_ESTB_CFG_LABEL_SYS_CFE_VER);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_SYS, 3, default_B_ESTB_CFG_LABEL_SYS_CFE_CUR_BANK);
	        SET_DEFAULT_DATA_VALUE(B_ESTB_CFG_LABEL_SYS, 5, default_B_ESTB_CFG_LABEL_SYS_ESTB_REBOOT_TYPE);
        };

}

