/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Aug 26 10:56:51 2014
 *                 Full Compile MD5 Checksum  fe5bf937ded6451208bcd12a03dadcff
 *                     (minus title and desc)
 *                 MD5 Checksum               e67548d0bfc4c43233ca60dd5a6dc076
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14541
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_XPT_WDMA_OVERFLOW_INTR_L2_H__
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_H__

/***************************************************************************
 *XPT_WDMA_OVERFLOW_INTR_L2 - L2 Overflow Interrupts
 ***************************************************************************/
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_STATUS 0x00a68200 /* [RO] CPU interrupt Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_SET   0x00a68204 /* [WO] CPU interrupt Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_CLEAR 0x00a68208 /* [WO] CPU interrupt Clear Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_MASK_STATUS 0x00a6820c /* [RO] CPU interrupt Mask Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_MASK_SET 0x00a68210 /* [WO] CPU interrupt Mask Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_CPU_MASK_CLEAR 0x00a68214 /* [WO] CPU interrupt Mask Clear Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_STATUS 0x00a68218 /* [RO] PCI interrupt Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_SET   0x00a6821c /* [WO] PCI interrupt Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_CLEAR 0x00a68220 /* [WO] PCI interrupt Clear Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_MASK_STATUS 0x00a68224 /* [RO] PCI interrupt Mask Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_MASK_SET 0x00a68228 /* [WO] PCI interrupt Mask Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_PCI_MASK_CLEAR 0x00a6822c /* [WO] PCI interrupt Mask Clear Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_STATUS 0x00a68230 /* [RO] SCPU interrupt Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_SET  0x00a68234 /* [WO] SCPU interrupt Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_CLEAR 0x00a68238 /* [WO] SCPU interrupt Clear Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_MASK_STATUS 0x00a6823c /* [RO] SCPU interrupt Mask Status Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_MASK_SET 0x00a68240 /* [WO] SCPU interrupt Mask Set Register */
#define BCHP_XPT_WDMA_OVERFLOW_INTR_L2_SCPU_MASK_CLEAR 0x00a68244 /* [WO] SCPU interrupt Mask Clear Register */

#endif /* #ifndef BCHP_XPT_WDMA_OVERFLOW_INTR_L2_H__ */

/* End of File */
