/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Aug 26 10:56:51 2014
 *                 Full Compile MD5 Checksum  fe5bf937ded6451208bcd12a03dadcff
 *                     (minus title and desc)
 *                 MD5 Checksum               e67548d0bfc4c43233ca60dd5a6dc076
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14541
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_H__
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_H__

/***************************************************************************
 *XPT_WDMA_SCPU_INTR_AGGREGATOR - SCPU Interrupt Aggregator
 ***************************************************************************/
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W0_STATUS 0x00a68040 /* [RO] Interrupt Status Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W1_STATUS 0x00a68044 /* [RO] Interrupt Status Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS 0x00a68048 /* [RO] Interrupt Mask Status Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W1_MASK_STATUS 0x00a6804c /* [RO] Interrupt Mask Status Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W0_MASK_SET 0x00a68050 /* [WO] Interrupt Mask Set Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W1_MASK_SET 0x00a68054 /* [WO] Interrupt Mask Set Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR 0x00a68058 /* [WO] Interrupt Mask Clear Register */
#define BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_INTR_W1_MASK_CLEAR 0x00a6805c /* [WO] Interrupt Mask Clear Register */

#endif /* #ifndef BCHP_XPT_WDMA_SCPU_INTR_AGGREGATOR_H__ */

/* End of File */
