/***************************************************************************
*     (c)2015 Broadcom Corporation
*
*  This program is the proprietary software of Broadcom Corporation and/or its licensors,
*  and may only be used, duplicated, modified or distributed pursuant to the terms and
*  conditions of a separate, written license agreement executed between you and Broadcom
*  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
*  no license (express or implied), right to use, or waiver of any kind with respect to the
*  Software, and Broadcom expressly reserves all rights in and to the Software and all
*  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
*  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
*  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
*
*  Except as expressly set forth in the Authorized License,
*
*  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
*  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
*  and to use this information only in connection with your use of Broadcom integrated circuit products.
*
*  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
*  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
*  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
*  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
*  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
*  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
*  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
*  USE OR PERFORMANCE OF THE SOFTWARE.
*
*  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
*  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
*  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
*  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
*  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
*  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
*  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
*  ANY LIMITED REMEDY.
*
***************************************************************************/

static const NEXUS_GpioTable g_gpioTable[] = {
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_000_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_008_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_007_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_006_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_005_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_004_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_003_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_002_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_001_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_016_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_015_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_014_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_013_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_012_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_011_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_010_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_009_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_024_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_023_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_022_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_021_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_020_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_019_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_018_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_017_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_032_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_031_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_030_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_029_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_028_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_027_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_026_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_025_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_040_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_039_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_038_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_037_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_036_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_035_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_034_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_033_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_048_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_047_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_046_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_045_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_044_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_043_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_042_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_041_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_056_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_055_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_054_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_053_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_052_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_051_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_050_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_049_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_063_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_062_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_061_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_060_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_059_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_058_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_057_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_071_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_070_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_069_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_068_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_067_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_066_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_065_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_079_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_078_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_077_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_076_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_075_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_074_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_073_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_082_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_081_SHIFT }
};

static const NEXUS_GpioTable g_sgpioTable[] = {
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_sgpio_01_SHIFT } ,
    { BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_sgpio_00_SHIFT }
};

static const NEXUS_GpioTable g_aonGpioTable[] = {
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_25_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_25_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_24_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_24_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_23_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_23_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_22_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_22_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_21_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_21_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_20_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_19_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_gpio_18_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4_aon_gpio_27_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4_aon_gpio_27_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4_aon_gpio_26_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_4_aon_gpio_26_SHIFT }
};

static const NEXUS_GpioTable g_aonSgpioTable[] = {
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT } ,
    { BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT }
};
