#!/bin/bash
#
# Installer upgrade preparation script for
# Broadcom 802.11abg Networking Device Driver Install Package
#
# $ Copyright Broadcom Corporation $
#
#
# <<Broadcom-WL-IPTag/Private1743:>>
#
# $Id: preupgrade,v 1.3 2009-06-05 21:43:18 Exp $
#

# Delete any existing kext directory tree to get a clean install.
# Upgrade installs only add or replace files, but will leave files
# in the destination directory tree in place.

PRODUCT=AirPortBroadcom43XX
KEXT=${PRODUCT}.kext

VERT_PRODUCT=BrcmVirtEther
VERT_KEXT=${VERT_PRODUCT}.kext

newkext=/System/Library/Extensions/${KEXT}
if [ -d $newkext ]; then
	rm -r $newkext
fi

virtkext=/System/Library/Extensions/${VERT_KEXT}
if [ -d $virtkext ]; then
	rm -rf $virtkext
fi
