/******************************************************************************
 * Copyright (C) 2018 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/


#ifndef BMUXLIB_ASP_CAPABILITIES_H_
#define BMUXLIB_ASP_CAPABILITIES_H_

/* Max Inputs */
#define BMUXLIB_ASP_TS_MAX_VIDEO_SOURCE 1
#define BMUXLIB_ASP_TS_MAX_AUDIO_SOURCE 6
#define BMUXLIB_ASP_TS_MAX_AV_SOURCE (BMUXLIB_ASP_TS_MAX_VIDEO_SOURCE + BMUXLIB_ASP_TS_MAX_AUDIO_SOURCE)
#define BMUXLIB_ASP_TS_MAX_USERDATA_SOURCE (8 + BMUXLIB_ASP_TS_MAX_SYSTEMDATA_SOURCE)
#define BMUXLIB_ASP_TS_MAX_USERDATA_ENTRIES_PER_QUEUE 16
#define BMUXLIB_ASP_TS_MAX_SYSTEMDATA_SOURCE 1
#define BMUXLIB_ASP_TS_MAX_SOURCE ((BMUXLIB_ASP_TS_MAX_VIDEO_SOURCE) + (BMUXLIB_ASP_TS_MAX_AUDIO_SOURCE) + (BMUXLIB_ASP_TS_MAX_SYSTEMDATA_SOURCE) + (BMUXLIB_ASP_TS_MAX_USERDATA_SOURCE))

/* A/V/S Requirements */
#define BMUXLIB_ASP_TS_MAX_VIDEO_FRAME_RATE 16 /* Assume 60fps max */
#define BMUXLIB_ASP_TS_MAX_AUDIO_FRAME_RATE 20

#define BMUXLIB_ASP_TS_MAX_SYS_BITRATE 2000000
#define BMUXLIB_ASP_TS_MAX_SYS_PACKETS_PER_SECOND ( ( ( ( BMUXLIB_ASP_TS_MAX_SYS_BITRATE + 7 ) / 8 ) + 187 ) / 188 )

#define BMUXLIB_ASP_TS_MAX_AV_TS_PACKETS_PER_FRAME 2 /* PUSI BTP + PES Header */
#define BMUXLIB_ASP_TS_MAX_AV_OUTPUT_DESCRIPTORS_PER_FRAME 4 /* PUSI BTP, PES Header, Payload, Payload (wrap) */

#define BMUXLIB_ASP_TS_MAX_SYS_PACKETS_QUEUED BMUXLIB_ASP_TS_MAX_USERDATA_ENTRIES_PER_QUEUE

/* MSP Dependent Memory Calculations */
#define BMUXLIB_ASP_TS_MSP 20
#define BMUXLIB_ASP_TS_MUX_DELAY ( BMUXLIB_ASP_TS_MSP + 20 )
#define BMUXLIB_ASP_TS_MSP_MULTIPLIER 1

/* A/V */
#define BMUXLIB_ASP_TS_MAX_VIDEO_FRAMES ( ( BMUXLIB_ASP_TS_MUX_DELAY + BMUXLIB_ASP_TS_MAX_VIDEO_FRAME_RATE - 1 ) / BMUXLIB_ASP_TS_MAX_VIDEO_FRAME_RATE )
#define BMUXLIB_ASP_TS_MAX_AUDIO_FRAMES ( ( BMUXLIB_ASP_TS_MUX_DELAY + BMUXLIB_ASP_TS_MAX_AUDIO_FRAME_RATE - 1 ) / BMUXLIB_ASP_TS_MAX_AUDIO_FRAME_RATE )
#define BMUXLIB_ASP_TS_MAX_AV_FRAMES (( BMUXLIB_ASP_TS_MAX_VIDEO_FRAMES*BMUXLIB_ASP_TS_MAX_VIDEO_SOURCE ) + (BMUXLIB_ASP_TS_MAX_AUDIO_FRAMES*BMUXLIB_ASP_TS_MAX_AUDIO_SOURCE))

#define BMUXLIB_ASP_TS_MAX_AV_TS_PACKETS (BMUXLIB_ASP_TS_MAX_AV_FRAMES * BMUXLIB_ASP_TS_MAX_AV_TS_PACKETS_PER_FRAME)
#define BMUXLIB_ASP_TS_MAX_AV_OUTPUT_DESCRIPTORS (BMUXLIB_ASP_TS_MAX_AV_FRAMES * BMUXLIB_ASP_TS_MAX_AV_OUTPUT_DESCRIPTORS_PER_FRAME )

/* System Data Bit Rate */
#define BMUXLIB_ASP_TS_MAX_SYS_TS_PACKETS ( BMUXLIB_ASP_TS_MAX_SYS_PACKETS_PER_SECOND + BMUXLIB_ASP_TS_MUX_DELAY - 1 ) / BMUXLIB_ASP_TS_MUX_DELAY
#define BMUXLIB_ASP_TS_MAX_SYS_OUTPUT_DESCRIPTORS BMUXLIB_ASP_TS_MAX_SYS_TS_PACKETS

/* Memory Requirements (per instance) */
#define BMUXLIB_ASP_TS_MAX_TS_PACKETS_PER_INSTANCE ( ( BMUXLIB_ASP_TS_MAX_AV_TS_PACKETS + BMUXLIB_ASP_TS_MAX_SYS_TS_PACKETS ) * BMUXLIB_ASP_TS_MSP_MULTIPLIER )
#define BMUXLIB_ASP_TS_MAX_OUTPUT_DESCRIPTORS_PER_INSTANCE ( ( BMUXLIB_ASP_TS_MAX_AV_OUTPUT_DESCRIPTORS + BMUXLIB_ASP_TS_MAX_SYS_OUTPUT_DESCRIPTORS ) * BMUXLIB_ASP_TS_MSP_MULTIPLIER )

/* Memory Requirements (total) */
#define BMUXLIB_ASP_TS_MAX_INSTANCES 1
#define BMUXLIB_ASP_TS_MAX_TS_PACKETS ( BMUXLIB_ASP_TS_MAX_TS_PACKETS_PER_INSTANCE * BMUXLIB_ASP_TS_MAX_INSTANCES )
#define BMUXLIB_ASP_TS_MAX_OUTPUT_DESCRIPTORS ( BMUXLIB_ASP_TS_MAX_OUTPUT_DESCRIPTORS_PER_INSTANCE * BMUXLIB_ASP_TS_MAX_INSTANCES )

#endif /* BMUXLIB_ASP_CAPABILITIES_H_ */
