############################################################
#     Copyright (c) 2007-2011 Broadcom Corporation
#     All Rights Reserved
#     Confidential Property of Broadcom Corporation
#
#  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
#  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
#  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
#
# $brcm_Workfile: $
# $brcm_Revision: $
# $brcm_Date: $
#
# Module Description:
#
# Revision History:
#
# $brcm_Log: $
# 
############################################################

# ATOM module
BATOM_INCLUDES := ${BSEAV}/lib/utils
BATOM_SOURCES :=  \
	${BSEAV}/lib/utils/bioatom.c \
	${BSEAV}/lib/utils/bpool.c \
	${BSEAV}/lib/utils/balloc.c \
	${BSEAV}/lib/utils/barena.c

