###############################################################################
# Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
###############################################################################

APP  := logo_menu
DATA := menu_config.txt \
	menu_config_multi.txt

app:
	$(MAKE) -f $(APP).mk DATA="$(DATA)"

clean_app:
	$(MAKE) -f $(APP).mk clean_app

clean:
	$(MAKE) -f $(APP).mk clean
