##############################################################################
#  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
#
#  This program is the proprietary software of Broadcom and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
#  USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
#  ANY LIMITED REMEDY.
##############################################################################

NEXUS_PLATFORM ?= $(PLATFORM)
ifndef NEXUS_PLATFORM
$(error NEXUS_PLATFORM is not defined)
endif
ifndef B_REFSW_SHAREABLE
B_REFSW_SHAREABLE := y
endif

ifeq ($(NEXUS_PREBUILT_BINARY),y)
# do "make nexus" and "make nexus_headers" first, then "make NEXUS_PREBUILT_BINARY=y"
NEXUS_BIN_DIR ?= $(NEXUS_TOP)/../obj.${NEXUS_PLATFORM}/nexus/bin
include $(NEXUS_BIN_DIR)/include/platform_app.inc
Q_ ?= @
else
include $(NEXUS_TOP)/platforms/$(NEXUS_PLATFORM)/build/platform_app.inc
endif

LDFLAGS += $(NEXUS_CLIENT_LD_LIBRARIES)
ifeq ($(B_REFSW_ANDROID),y)
LDFLAGS += -nostdlib \
	-Wl,--gc-sections -Wl,-shared,-Bsymbolic \
	-L$(B_REFSW_ANDROID_LIB) \
	-Wl,--no-whole-archive -lcutils -lc -lm -ldl \
	-Wl,--whole-archive
ifeq ($(B_REFSW_USES_CLANG),y)
ifeq ($(B_REFSW_ARCH), aarch64-linux)
LDFLAGS += \
   ${ANDROID_TOP}/${ANDROID_PREBUILT_LIBGCC} \
   -target aarch64-linux-android \
   -B${ANDROID_TOP}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin
else
LDFLAGS += \
   ${ANDROID_TOP}/${ANDROID_PREBUILT_LIBGCC} \
   -target arm-linux-androideabi \
   -B${ANDROID_TOP}/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin
endif
endif
else
LDFLAGS += -Wl,-Map,$(BINDIR)/libnxclient.map -g
endif

ifeq ($(B_REFSW_SHAREABLE),y)
IPC_LIB=$(BINDIR)/libnxclient.so
LOCAL_LIB=$(BINDIR)/libnxclient_local.so
else
IPC_LIB=$(BINDIR)/libnxclient.a
LOCAL_LIB=$(BINDIR)/libnxclient_local.a
endif
Q_?=@

all: $(IPC_LIB) $(LOCAL_LIB)

B_LINKER=$(CC)

# allow override of socket interface
NXCLIENT_SOCKET_INTF ?= $(NEXUS_TOP)/nxclient/server/nxclient_socket.c
vpath %.c $(dir $(NXCLIENT_SOCKET_INTF))

IPC_SERVER_STUB := $(BINDIR)/stubs/ipc_stubs_server.h
IPC_CLIENT_STUB := $(BINDIR)/stubs/ipc_stubs_client.h
IPC_SERVER_VEFIFY_STUB := $(BINDIR)/stubs/ipc_stubs_verify.h
IPC :=  ${NEXUS_TOP}/lib/ipc
CFLAGS += -I${IPC} -I$(BINDIR)/stubs
vpath %.c ${IPC}

${IPC_CLIENT_STUB}: ${IPC_SERVER_STUB}
${IPC_SERVER_VEFIFY_STUB}: ${IPC_SERVER_STUB}

${IPC_SERVER_STUB}: ${NEXUS_TOP}/nxclient/server/nxserver_ipc.h
	${Q_}${MKDIR} -p $(BINDIR)/stubs
	${Q_}$(CC) -MM ${CFLAGS} $^ | ${PERL} -I ${NEXUS_TOP}/build/tools/common -I ${NEXUS_TOP}/build/tools/abiverify ${IPC}/build/bipc_build.pl -verify  ${IPC_SERVER_STUB} ${IPC_CLIENT_STUB} ${IPC_SERVER_VEFIFY_STUB} $^

$(BINDIR)/nxclient_ipc.o: ${IPC_SERVER_STUB} ${IPC_CLIENT_STUB}
$(BINDIR)/nxclient_ipc_verify.o: ${IPC_SERVER_VEFIFY_STUB}

# NEXUS flags
CFLAGS += -g $(NEXUS_CFLAGS) $(addprefix -I,$(NEXUS_APP_INCLUDE_PATHS)) $(addprefix -D,$(NEXUS_APP_DEFINES))

# nxclient
CFLAGS += -I$(NEXUS_TOP)/nxclient/include -I$(NEXUS_TOP)/nxclient/server
CFLAGS += -fPIC

$(BINDIR)/nxclient_local.o $(BINDIR)/nxclient_ipc.o: $(NEXUS_TOP)/nxclient/include/nxclient.h $(NEXUS_TOP)/nxclient/include/nxclient_config.h

# use special file to trigger relink of libnxclient.so (and then all client apps) if there's a switch between user and kernel modes
ifeq ($(NEXUS_MODE),proxy)
NXCLIENT_MODE_CHECK := $(B_REFSW_OBJ_ROOT)/nexus/nxclient/proxymode
$(NXCLIENT_MODE_CHECK):
	@$(RM) $(B_REFSW_OBJ_ROOT)/nexus/nxclient/clientmode
	@touch $@
else
NXCLIENT_MODE_CHECK := $(B_REFSW_OBJ_ROOT)/nexus/nxclient/clientmode
$(NXCLIENT_MODE_CHECK):
	@$(RM) $(B_REFSW_OBJ_ROOT)/nexus/nxclient/proxymode
	@touch $@
endif

IPC_LIB_OBJS := $(addprefix $(BINDIR)/,nxclient_ipc.o nxclient_common.o $(patsubst %.c,%.o,$(notdir $(NXCLIENT_SOCKET_INTF))) bipc_util.o bipc_client.o)

ifeq ($(B_REFSW_SHAREABLE),y)
$(IPC_LIB): $(IPC_LIB_OBJS) $(NXCLIENT_MODE_CHECK)
	${Q_}echo "[Linking $(notdir $@)]"
	${Q_}$(B_LINKER) ${LDFLAGS} -shared -Wl,--cref -Wl,-x -o $@ -Wl,-soname,libnxclient.so $(filter %.o,$^)

$(LOCAL_LIB): $(BINDIR)/nxclient_local.o $(BINDIR)/nxclient_common.o
	${Q_}echo "[Linking $(notdir $@)]"
	${Q_}$(B_LINKER) ${LDFLAGS} -shared -Wl,--cref -Wl,-x -o $@ -Wl,-soname,libnxclient_local.so $^
else
$(IPC_LIB): $(IPC_LIB_OBJS) $(NXCLIENT_MODE_CHECK)
	${Q_}echo "[Archive... $(notdir $@)]"
	$(Q_)$(AR) rcs $@ $(IPC_LIB_OBJS)

$(LOCAL_LIB): $(BINDIR)/nxclient_local.o $(BINDIR)/nxclient_common.o
	${Q_}echo "[Archive... $(notdir $@)]"
	$(Q_)$(AR) rcs $@ $(BINDIR)/nxclient_local.o $(BINDIR)/nxclient_common.o
endif

$(BINDIR)/%.o: %.c
	${Q_}$(CC) -c -o $@ $(filter %.c %.s %.o, $<) ${CFLAGS}

clean:
	$(RM) -r $(IPC_LIB) $(IPC_LIB_STATIC) $(LOCAL_LIB) $(BINDIR)/libnxclient.map $(BINDIR)/*.o $(BINDIR)/stubs $(NXCLIENT_MODE_CHECK)
