/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Mon Dec 23 13:19:24 2013
 *                 Full Compile MD5 Checksum e5d1378cc1475b750905e70cb70c73d9
 *                   (minus title and desc)  
 *                 MD5 Checksum              aa943f3142a624837db5321711723fcf
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_TFEC_1_H__
#define BCHP_TFEC_1_H__

/***************************************************************************
 *TFEC_1 - SDS TFEC Register Set
 ***************************************************************************/
#define BCHP_TFEC_1_TFECTL                       0x01249000 /* Advanced FEC Control */
#define BCHP_TFEC_1_TNBLK                        0x01249014 /* RS total block count */
#define BCHP_TFEC_1_TCBLK                        0x01249018 /* RS corrected block count */
#define BCHP_TFEC_1_TBBLK                        0x0124901c /* RS bad block count */
#define BCHP_TFEC_1_TCSYM                        0x01249020 /* RS corrected symbol count */
#define BCHP_TFEC_1_TFMT                         0x01249024 /* RS parameters */
#define BCHP_TFEC_1_TPAK                         0x01249028 /* MPEG packetizer parameters */
#define BCHP_TFEC_1_TSSQ                         0x0124902c /* Advanced FEC symbol sequence */
#define BCHP_TFEC_1_TSYN                         0x01249030 /* MPEG synchronizer parameters */
#define BCHP_TFEC_1_TTUR                         0x01249034 /* Advanced FEC configuration parameters */
#define BCHP_TFEC_1_TZPK                         0x01249038 /* RS synchronizer parameters */
#define BCHP_TFEC_1_TZSY                         0x0124903c /* RS synchronizer aquisition and retention parameters */
#define BCHP_TFEC_1_TITR                         0x01249040 /* Iterative decoder parameters */
#define BCHP_TFEC_1_TCIL                         0x01249044 /* Iterative decoder parameters */
#define BCHP_TFEC_1_TRSD                         0x01249048 /* RS decoder parameters */
#define BCHP_TFEC_1_TPN                          0x0124904c /* Iterative decoder internal point signature analyzer output */
#define BCHP_TFEC_1_TSIGCNT                      0x01249050 /* Signature analyzer data length count */
#define BCHP_TFEC_1_TSIGITD                      0x01249054 /* Iterative decoder signature analyzer output */
#define BCHP_TFEC_1_TSIGXPT                      0x01249058 /* Transport output signature analyzer output */
#define BCHP_TFEC_1_TTPCTL                       0x0124905c /* Advanced FEC testport control */
#define BCHP_TFEC_1_TRAWISR                      0x01249060 /* Advanced FEC raw interrupt status */

#endif /* #ifndef BCHP_TFEC_1_H__ */

/* End of File */
