/***************************************************************************
 *     Copyright (c) 2005-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Highly Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 ***************************************************************************/


#ifndef BSP_S_VERSION_NUMBER_H__
#define BSP_S_VERSION_NUMBER_H__


#define BSP_S_CHIP_NUMBER_SHIFT		24
#define BSP_S_CHIP_VERSION_SHIFT		16
#define BSP_S_MAJOR_VERSION_SHIFT		12
#define BSP_S_MINOR_VERSION_SHIFT		6
#define BSP_S_CUSTOMER_MODE_SHIFT	0


#define BSP_S_CHIP_NUMBER_7401		0x00L
#define BSP_S_CHIP_NUMBER_7400		0x01L
#define BSP_S_CHIP_NUMBER_7118		0x02L
#define BSP_S_CHIP_NUMBER_7440		0x03L
#define BSP_S_CHIP_NUMBER_3563		0x04L
#define BSP_S_CHIP_NUMBER_7405		0x07L
#define BSP_S_CHIP_NUMBER_7325		0x08L
#define BSP_S_CHIP_NUMBER_7335		0x09L
#define BSP_S_CHIP_NUMBER_3573		0x0AL
#define BSP_S_CHIP_NUMBER_3548      0x0bL
#define BSP_S_CHIP_NUMBER_7420		0x0BL
#define BSP_S_CHIP_NUMBER_7340		0x0CL
#define BSP_S_CHIP_NUMBER_7342	    0x0DL
#define BSP_S_CHIP_NUMBER_7125      0x0EL
#define BSP_S_CHIP_NUMBER_7468      0x0FL
#define BSP_S_CHIP_NUMBER_7346      0x10L
#define BSP_S_CHIP_NUMBER_7344      0x11L
#define BSP_S_CHIP_NUMBER_7422      0x12L
#define BSP_S_CHIP_NUMBER_7231      0x13L
#define BSP_S_CHIP_NUMBER_7425      0x14L
#define BSP_S_CHIP_NUMBER_7358      0x15L
#define BSP_S_CHIP_NUMBER_7552      0x16L
#define BSP_S_CHIP_NUMBER_7428      0x17L
#define BSP_S_CHIP_NUMBER_7435      0x18L
#define BSP_S_CHIP_NUMBER_7360      0x19L
#define BSP_S_CHIP_NUMBER_7584      0x1AL
#define BSP_S_CHIP_NUMBER_7445      0x1BL
#define BSP_S_CHIP_NUMBER_7563      0x1CL


#define BSP_S_A0_CHIP_VERSION			0xA0L
#define BSP_S_A1_CHIP_VERSION			0xA1L
#define BSP_S_A2_CHIP_VERSION			0xA2L
#define BSP_S_A3_CHIP_VERSION			0xA3L
#define BSP_S_B0_CHIP_VERSION			0xB0L
#define BSP_S_B1_CHIP_VERSION			0xB1L
#define BSP_S_B2_CHIP_VERSION			0xB2L
#define BSP_S_B3_CHIP_VERSION			0xB3L
#define BSP_S_C0_CHIP_VERSION			0xC0L
#define BSP_S_C1_CHIP_VERSION			0xC1L
#define BSP_S_C2_CHIP_VERSION			0xC2L
#define BSP_S_C3_CHIP_VERSION			0xC3L
#define BSP_S_D0_CHIP_VERSION			0xD0L
#define BSP_S_D1_CHIP_VERSION			0xD1L
#define BSP_S_D2_CHIP_VERSION			0xD2L
#define BSP_S_D3_CHIP_VERSION			0xD3L
#define BSP_S_E0_CHIP_VERSION			0xE0L
#define BSP_S_E1_CHIP_VERSION			0xE1L
#define BSP_S_E2_CHIP_VERSION			0xE2L
#define BSP_S_E3_CHIP_VERSION			0xE3L
#define BSP_S_F0_CHIP_VERSION			0xF0L
#define BSP_S_F1_CHIP_VERSION			0xF1L
#define BSP_S_F2_CHIP_VERSION			0xF2L
#define BSP_S_F3_CHIP_VERSION			0xF3L

#define BSP_S_GENERIC				0x00

#endif
