#!/bin/sh
#
# $Id$
# UTF test cron wrapper for systems with an SGE server
#

cd $(dirname $(dirname $0)) || exit -1
mkdir -p /var/tmp/hnd
log="/var/tmp/hnd/utf_$1.log"; shift
exec >$log 2>&1 </dev/null

# fix up path if utf isn't found
type utf 2>/dev/null|| PATH=$PATH:/projects/hnd/tools/linux/bin
if [ -d .svn ]; then
    svn up
elif git config --get-all svn-remote.svn.url; then
    echo "Rejecting attempt to update master git-svn workspace"
    exit 1
else
    # Note this may fail due to local changes.
    git pull
fi

[[ "$*" == *-email* ]] || set "$@" -email hnd-utf-list.pdl
"$@" &
