BCHP_V3D_HUB_CTL_H = $(MAGNUM_TOP)/basemodules/chp/include/$(BCHP_CHIP)/rdb/$(BCHP_VER_LOWER)/bchp_v3d_hub_ctl.h
V3D_TECH_VERSION = $(shell cat $(BCHP_V3D_HUB_CTL_H) | grep BCHP_V3D_HUB_CTL_IDENT1_TVER_DEFAULT | awk '{printf "%d", strtonum($$3)}')
V3D_REVISION = $(shell cat $(BCHP_V3D_HUB_CTL_H) | grep BCHP_V3D_HUB_CTL_IDENT1_REV_DEFAULT | awk '{printf "%d", strtonum($$3)}')
V3D_SUB_REV = $(shell cat $(BCHP_V3D_HUB_CTL_H) | grep BCHP_V3D_HUB_CTL_IDENT3_IPREV_DEFAULT | awk '{printf "%d", strtonum($$3)}')
V3D_VER_AT_LEAST_3_3_0 := $(shell expr `printf "%d%2.2d%2.2d\n" $(V3D_TECH_VERSION) $(V3D_REVISION) $(V3D_SUB_REV)` \>= 30300)
V3D_VER_AT_LEAST_4_1_0 := $(shell expr `printf "%d%2.2d%2.2d\n" $(V3D_TECH_VERSION) $(V3D_REVISION) $(V3D_SUB_REV)` \>= 40100)

# Sources common to both GLES and Vulkan
COMMON_SRC_FILES :=                                             \
	libs/khrn/common/khrn_int_hash.c                            \
	libs/khrn/common/khrn_options.c                             \
	libs/util/dglenum/dglenum.c                                 \
	libs/util/log/log.c                                         \
	libs/khrn/glsl/glsl_unique_index_queue.c                    \
	libs/khrn/glsl/glsl_mem_layout.c                            \
	libs/khrn/glsl/glsl_symbols.c                               \
	libs/khrn/glsl/glsl_symbol_table.c                          \
	libs/khrn/glsl/glsl_stringbuilder.c                         \
	libs/khrn/glsl/glsl_stackmem.c                              \
	libs/khrn/glsl/glsl_source.c                                \
	libs/khrn/glsl/glsl_shader_interfaces.c                     \
	libs/khrn/glsl/glsl_scoped_map.c                            \
	libs/khrn/glsl/glsl_safemem.c                               \
	libs/khrn/glsl/glsl_program.c                               \
	libs/khrn/glsl/glsl_ssa_convert.c                           \
	libs/khrn/glsl/glsl_precision.c                             \
	libs/khrn/glsl/glsl_map.c                                   \
	libs/khrn/glsl/glsl_layout.c                                \
	libs/khrn/glsl/glsl_ir_shader.c                             \
	libs/khrn/glsl/glsl_ir_program.c                            \
	libs/khrn/glsl/glsl_intrinsic_ir_builder.c                  \
	libs/khrn/glsl/glsl_intrinsic.c                             \
	libs/khrn/glsl/glsl_intern.c                                \
	libs/khrn/glsl/glsl_globals.c                               \
	libs/khrn/glsl/glsl_fastmem.c                               \
	libs/khrn/glsl/glsl_extensions.c                            \
	libs/khrn/glsl/glsl_errors.c                                \
	libs/khrn/glsl/glsl_dataflow_visitor.c                      \
	libs/khrn/glsl/glsl_dataflow_simplify.c                     \
	libs/khrn/glsl/glsl_dataflow_print.c                        \
	libs/khrn/glsl/glsl_dataflow_builder.c                      \
	libs/khrn/glsl/glsl_dataflow_cse.c                          \
	libs/khrn/glsl/glsl_dataflow.c                              \
	libs/khrn/glsl/glsl_dataflow_image.c                        \
	libs/khrn/glsl/glsl_linker.c                                \
	libs/khrn/glsl/glsl_compiler.c                              \
	libs/khrn/glsl/glsl_builders.c                              \
	libs/khrn/glsl/glsl_binary_shader.c                         \
	libs/khrn/glsl/glsl_binary_program.c                        \
	libs/khrn/glsl/glsl_backflow_visitor.c                      \
	libs/khrn/glsl/glsl_backflow_print.c                        \
	libs/khrn/glsl/glsl_backflow.c                              \
	libs/khrn/glsl/glsl_qbe_fragment.c                          \
	libs/khrn/glsl/glsl_qbe_fragment_adv_blend.c                \
	libs/khrn/glsl/glsl_qbe_vertex.c                            \
	libs/khrn/glsl/glsl_backflow_combine.c                      \
	libs/khrn/glsl/glsl_backend.c                               \
	libs/khrn/glsl/glsl_ast_visitor.c                           \
	libs/khrn/glsl/glsl_ast_print.c                             \
	libs/khrn/glsl/glsl_ast.c                                   \
	libs/khrn/glsl/glsl_arenamem.c                              \
	libs/khrn/glsl/glsl_alloc_tracker.c                         \
	libs/khrn/glsl/glsl_basic_block.c                           \
	libs/khrn/glsl/glsl_basic_block_builder.c                   \
	libs/khrn/glsl/glsl_basic_block_elim_dead.c                 \
	libs/khrn/glsl/glsl_basic_block_flatten.c                   \
	libs/khrn/glsl/glsl_basic_block_print.c                     \
	libs/khrn/glsl/glsl_nast.c                                  \
	libs/khrn/glsl/glsl_nast_builder.c                          \
	libs/khrn/glsl/glsl_nast_print.c                            \
	libs/khrn/glsl/glsl_dominators.c                            \
	libs/khrn/glsl/glsl_scheduler.c                             \
	libs/khrn/glsl/glsl_quals.c                                 \
	libs/khrn/glsl/glsl_inline_asm.c                            \
	libs/khrn/glsl/glsl_sim_scheduler.c                         \
	libs/khrn/glsl/glsl_stable_sort.cpp                         \
	libs/khrn/glsl/prepro/glsl_prepro_directive.c               \
	libs/khrn/glsl/prepro/glsl_prepro_expand.c                  \
	libs/khrn/glsl/prepro/glsl_prepro_token.c                   \
	libs/khrn/glsl/prepro/glsl_prepro_eval.c                    \
	libs/khrn/glsl/prepro/glsl_prepro_macro.c                   \
	libs/util/desc_map/desc_map.c                               \
	libs/util/gfx_util/gfx_util_conv.c                          \
	libs/util/gfx_util/gfx_util_morton.c                        \
	libs/util/gfx_util/gfx_util_hrsize.c                        \
	libs/util/gfx_util/gfx_util_file.c                          \
	libs/util/gfx_util/gfx_util.c                               \
	libs/util/gfx_util/gfx_util_term_col.c                      \
	libs/util/gfx_util/gfx_util_wildcard.c                      \
	libs/util/gfx_options/gfx_options.c                         \
	libs/core/lfmt/lfmt_translate_v3d.c                         \
	libs/core/lfmt/lfmt_fmt_detail.c                            \
	libs/core/lfmt/lfmt.c                                       \
	libs/core/lfmt/lfmt_block.c                                 \
	libs/core/lfmt/lfmt_desc.c                                  \
	libs/core/lfmt/lfmt_desc_maps.c                             \
	libs/core/lfmt_translate_gl/lfmt_translate_gl.c             \
	libs/core/gfx_buffer/gfx_buffer_v3d_tfu_srgb_conversions.c  \
	libs/core/gfx_buffer/gfx_buffer_uif_config.c                \
	libs/core/gfx_buffer/gfx_buffer_translate_v3d.c             \
	libs/core/gfx_buffer/gfx_buffer_compare.c                   \
	libs/core/gfx_buffer/gfx_buffer_bc.c                        \
	libs/core/gfx_buffer/gfx_buffer.c                           \
	libs/core/gfx_buffer/gfx_buffer_bstc.c                      \
	libs/core/gfx_buffer/gfx_buffer_desc_gen.c                  \
	libs/core/gfx_buffer/gfx_buffer_slow_conv_compr.c           \
	libs/core/gfx_buffer/gfx_buffer_slow_conv_xform.c           \
	libs/core/gfx_buffer/gfx_buffer_slow_conv.c                 \
	libs/core/gfx_buffer/gfx_buffer_astc_stub.c                 \
	libs/core/gfx_buffer/gfx_buffer_etc_stub.c                  \
	libs/util/gfx_args/gfx_args.c                               \
	libs/core/v3d/v3d_supertile.c                               \
	libs/core/v3d/v3d_shadrec.c                                 \
	libs/core/v3d/v3d_cl.c                                      \
	libs/core/v3d/v3d_cl_compr.c                                \
	libs/core/v3d/v3d_clear_shader.c                            \
	libs/core/v3d/v3d_barrier.c                                 \
	libs/core/v3d/v3d_gen.c                                     \
	libs/core/v3d/v3d_gmp.c                                     \
	libs/core/v3d/v3d_ident.c                                   \
	libs/core/v3d/v3d_printer.c                                 \
	libs/core/v3d/v3d_qpu_instr.c                               \
	libs/core/v3d/v3d_tfu.c                                     \
	libs/core/v3d/v3d_tlb_decimate.c                            \
	libs/core/v3d/v3d_tmu.c                                     \
	libs/core/v3d/v3d_vpm.c                                     \
	libs/compute/compute.cpp                                    \
	libs/platform/v3d_imgconv.c                                 \
	libs/platform/v3d_imgconv_c.c                               \
	libs/platform/v3d_imgconv_neon.c                            \
	libs/platform/v3d_imgconv_extra_neon.c                      \
	libs/platform/v3d_imgconv_gfx_blit.c                        \
	libs/platform/v3d_scheduler.c                               \
	libs/platform/v3d_scheduler_graph.c                         \
	libs/platform/v3d_imgconv_tfu.c                             \
	libs/platform/v3d_imgconv_m2mc.c                            \
	libs/platform/v3d_parallel.c                                \
	libs/platform/bcg_abstract/gmem_abstract.c                  \
	libs/platform/bcg_abstract/gmem_talloc.c                    \
	libs/platform/bcg_abstract/sched_abstract.c                 \
	libs/core/vcos/posix/vcos_pthreads.c                        \
	libs/core/vcos/posix/vcos_thread_posix.c                    \
	libs/core/vcos/posix/vcos_mutex_posix.c                     \
	libs/core/vcos/generic/vcos_generic_safe_string.c           \
	libs/core/vcos/generic/vcos_init.c                          \
	libs/core/vcos/generic/vcos_properties.c                    \
	libs/sim/qpu_float/qpu_float.c                              \
	libs/sim/sfu/sfu.c

COMMON_GENERATED_SRC_FILES :=                                   \
	glsl_primitive_types.auto.c                                 \
	glsl_stdlib.auto.c

GLES_GENERATED_SRC_FILES :=                                    \
	glsl_lexer.c                                                \
	glsl_parser.c                                               \
	glsl_numbers.c                                              \
	glsl_version.c

# sources for stdlib
STDLIB_SOURCES :=                                               \
	stdlib/atomics.glsl                                         \
	stdlib/common.glsl                                          \
	stdlib/derivatives.glsl                                     \
	stdlib/exponential.glsl                                     \
	stdlib/extensions.glsl                                      \
	stdlib/geometry.glsl                                        \
	stdlib/geom_shade.glsl                                      \
	stdlib/hyperbolic.glsl                                      \
	stdlib/image.glsl                                           \
	stdlib/integer.glsl                                         \
	stdlib/matrix.glsl                                          \
	stdlib/packing.glsl                                         \
	stdlib/synchronisation.glsl                                 \
	stdlib/texture_gather.glsl                                  \
	stdlib/trigonometry.glsl                                    \
	stdlib/vector_relational.glsl                               \
	stdlib/common.inl                                           \
	stdlib/derivatives.inl                                      \
	stdlib/exponential.inl                                      \
	stdlib/geometry.inl                                         \
	stdlib/hyperbolic.inl                                       \
	stdlib/integer.inl                                          \
	stdlib/matrix.inl                                           \
	stdlib/packing.inl                                          \
	stdlib/trigonometry.inl                                     \
	stdlib/vector_relational.inl                                \
	stdlib/texture.glsl                                         \
	stdlib/globals.glsl                                         \
	stdlib/stages.props                                         \
	stdlib/v100_only.props                                      \
	stdlib/v300_only.props                                      \
	stdlib/v310_only.props                                      \
	stdlib/v320_only.props                                      \
	stdlib/extensions.props                                     \
	stdlib/restrictions.props

STDLIB_AUTO_SOURCES =                                           \
	$(GLSL_INTERMEDIATE_ABS_PATH)/glsl_primitive_types.auto.table        \
	$(GLSL_INTERMEDIATE_ABS_PATH)/textures.auto.glsl                     \
	$(GLSL_INTERMEDIATE_ABS_PATH)/textures.auto.props

AUTO_FILES =                                                    \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_primitive_types.auto.table        \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_primitive_type_index.auto.h       \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_primitive_types.auto.h            \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_primitive_types.auto.c            \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_intrinsic_lookup.auto.h           \
	$(GLSL_INTERMEDIATE_REL_PATH)/textures.auto.glsl                     \
	$(GLSL_INTERMEDIATE_REL_PATH)/textures.auto.props                    \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_stdlib.auto.c                     \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_stdlib.auto.h                     \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_parser.c                          \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_parser.h                          \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_parser.output                     \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_lexer.c                           \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_numbers.c                         \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_version.c                         \
	$(GLSL_INTERMEDIATE_REL_PATH)/glsl_layout.auto.h                     \
	$(DGLENUM_INTERMEDIATE_REL_PATH)/dglenum_gen.h

# Sources specific to GLES
GLES_SRC_FILES :=                                                          \
	libs/khrn/glxx/glxx_client_skin.c                                      \
	libs/khrn/common/khrn_fmem.c                                           \
	libs/khrn/common/khrn_fmem_pool.c                                      \
	libs/khrn/common/khrn_fmem_debug_info.c                                \
	libs/khrn/common/khrn_fmem_tmu_config.c                                \
	libs/khrn/common/khrn_counters.c                                       \
	libs/khrn/common/khrn_render_state.c                                   \
	libs/khrn/common/khrn_blob.c                                           \
	libs/khrn/common/khrn_image.c                                          \
	libs/khrn/common/khrn_map.c                                            \
	libs/khrn/common/khrn_resource.c                                       \
	libs/khrn/common/khrn_mem.c                                            \
	libs/khrn/common/khrn_process.c                                        \
	libs/khrn/common/khrn_process_debug.c                                  \
	libs/khrn/common/khrn_uintptr_vector.c                                 \
	libs/khrn/common/khrn_vector.c                                         \
	libs/khrn/common/khrn_fence.c                                          \
	libs/khrn/common/khrn_tile_state.c                                     \
	libs/khrn/common/khrn_timeline.c                                       \
	libs/khrn/egl/egl_attrib_list.c                                        \
	libs/khrn/egl/egl_config.c                                             \
	libs/khrn/egl/egl_context_base.c                                       \
	libs/khrn/egl/egl_context.c                                            \
	libs/khrn/egl/egl_context_gl.c                                         \
	libs/khrn/egl/egl_display.c                                            \
	libs/khrn/egl/egl_map.c                                                \
	libs/khrn/egl/egl_pbuffer_surface.c                                    \
	libs/khrn/egl/egl_process.c                                            \
	libs/khrn/egl/egl_surface_base.c                                       \
	libs/khrn/egl/egl_surface.c                                            \
	libs/khrn/egl/egl_thread.c                                             \
	libs/khrn/egl/egl_image.c                                              \
	libs/khrn/egl/egl_image_texture.c                                      \
	libs/khrn/egl/egl_image_renderbuffer.c                                 \
	libs/khrn/egl/egl_image_framebuffer.c                                  \
	libs/khrn/egl/egl_sync.c                                               \
	libs/khrn/egl/egl_synckhr.c                                            \
	libs/khrn/egl/egl_partial_update.c                                     \
	libs/khrn/egl/egl_proc_address.c                                       \
	libs/khrn/egl/egl_platform.c                                           \
	libs/khrn/ext/egl_brcm_perf_counters.c                                 \
	libs/khrn/ext/egl_brcm_event_monitor.c                                 \
	libs/khrn/ext/gl_ext_base_instance.c                                   \
	libs/khrn/ext/gl_ext_copy_image.c                                      \
	libs/khrn/ext/gl_ext_multi_draw_indirect.c                             \
	libs/khrn/ext/gl_ext_texture_border_clamp.c                            \
	libs/khrn/ext/gl_brcm_polygon_mode.c                                   \
	libs/khrn/ext/gl_brcm_provoking_vertex.c                               \
	libs/khrn/ext/gl_ext_draw_elements_base_vertex.c                       \
	libs/khrn/ext/gl_oes_draw_texture.c                                    \
	libs/khrn/ext/gl_oes_map_buffer.c                                      \
	libs/khrn/ext/gl_oes_matrix_palette.c                                  \
	libs/khrn/ext/gl_oes_query_matrix.c                                    \
	libs/khrn/ext/gl_oes_texture_border_clamp.c                            \
	libs/khrn/gl11/gl11_shader.c                                           \
	libs/khrn/gl11/gl11_vshader.c                                          \
	libs/khrn/gl11/gl11_fshader.c                                          \
	libs/khrn/gl11/gl11_shadercache.c                                      \
	libs/khrn/gl11/gl11_matrix.c                                           \
	libs/khrn/gl11/gl11_server.c                                           \
	libs/khrn/gl11/gl11_draw.c                                             \
	libs/khrn/gl11/gl_oes_framebuffer_object.c                             \
	libs/khrn/gl20/gl20_program.c                                          \
	libs/khrn/gl20/gl20_server.c                                           \
	libs/khrn/gl20/gl20_shader.c                                           \
	libs/khrn/glxx/glxx_ez.c                                               \
	libs/khrn/glxx/glxx_hw.c                                               \
	libs/khrn/glxx/glxx_inner.c                                            \
	libs/khrn/glxx/glxx_shader_ops.c                                       \
	libs/khrn/glxx/glxx_shader.c                                           \
	libs/khrn/glxx/glxx_hw_tile_list.c                                     \
	libs/khrn/glxx/glxx_hw_clear.c                                         \
	libs/khrn/glxx/glxx_hw_render_state.c                                  \
	libs/khrn/glxx/glxx_buffer.c                                           \
	libs/khrn/glxx/glxx_ds_to_color.c                                      \
	libs/khrn/glxx/glxx_draw.c                                             \
	libs/khrn/glxx/glxx_framebuffer.c                                      \
	libs/khrn/glxx/glxx_renderbuffer.c                                     \
	libs/khrn/glxx/glxx_server.c                                           \
	libs/khrn/glxx/glxx_server_barrier.c                                   \
	libs/khrn/glxx/glxx_server_debug.c                                     \
	libs/khrn/glxx/glxx_textures.c                                         \
	libs/khrn/glxx/glxx_server_texture.c                                   \
	libs/khrn/glxx/glxx_server_buffer.c                                    \
	libs/khrn/glxx/glxx_query.c                                            \
	libs/khrn/glxx/glxx_server_query.c                                     \
	libs/khrn/glxx/glxx_server_get.c                                       \
	libs/khrn/glxx/glxx_server_framebuffer.c                               \
	libs/khrn/glxx/glxx_server_transform_feedback.c                        \
	libs/khrn/glxx/glxx_server_vao.c                                       \
	libs/khrn/glxx/glxx_server_sampler.c                                   \
	libs/khrn/glxx/glxx_server_pipeline.c                                  \
	libs/khrn/glxx/glxx_server_sync.c                                      \
	libs/khrn/glxx/glxx_server_program_interface.c                         \
	libs/khrn/glxx/glxx_shader_cache.c                                     \
	libs/khrn/glxx/glxx_shared.c                                           \
	libs/khrn/glxx/glxx_compressed_paletted_texture.c                      \
	libs/khrn/glxx/glxx_texture.c                                          \
	libs/khrn/glxx/glxx_texture_utils.c                                    \
	libs/khrn/glxx/glxx_fencesync.c                                        \
	libs/khrn/glxx/glxx_blit.c                                             \
	libs/khrn/glxx/glxx_tmu_blit.c                                         \
	libs/khrn/glxx/glxx_tlb_blit.c                                         \
	libs/khrn/glxx/glxx_utils.c                                            \
	libs/khrn/glxx/glxx_compute.c                                          \
	libs/khrn/glxx/glxx_texlevel_param.c                                   \
	libs/khrn/glxx/glxx_image_unit.c                                       \
	libs/khrn/glxx/glxx_tf.c                                               \
	libs/khrn/glxx/glxx_debug.c                                            \
	libs/khrn/glxx/glxx_rect.c                                             \
	libs/khrn/glxx/glxx_clear_layers.c                                     \
	libs/khrn/egl/platform/bcg_abstract/egl_platform_abstract.c            \
	libs/khrn/egl/platform/bcg_abstract/egl_window_surface_abstract.c      \
	libs/khrn/egl/platform/bcg_abstract/egl_surface_common_abstract.c      \
	libs/khrn/egl/platform/bcg_abstract/egl_pixmap_surface_abstract.c      \
	libs/khrn/egl/platform/bcg_abstract/egl_image_native_buffer_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_wl_bind_display_abstract.c

# Sources specific to Vulkan
VULKAN_SRC_FILES :=                                                 \
	libs/vulkan/driver/Allocator.cpp                            \
	libs/vulkan/driver/APIVersion.cpp                           \
	libs/vulkan/driver/Buffer.cpp                               \
	libs/vulkan/driver/BufferView.cpp                           \
	libs/vulkan/driver/CBBlitImage.cpp                          \
	libs/vulkan/driver/CBClearColorImage.cpp                    \
	libs/vulkan/driver/CBDrawRect.cpp                           \
	libs/vulkan/driver/CBResolveImage.cpp                       \
	libs/vulkan/driver/ClifRecorder.cpp                         \
	libs/vulkan/driver/CmdBufState.cpp                          \
	libs/vulkan/driver/ColorAspectCommandBuilder.cpp            \
	libs/vulkan/driver/CommandBufferBuilder.cpp                 \
	libs/vulkan/driver/CommandBuffer.cpp                        \
	libs/vulkan/driver/Command.cpp                              \
	libs/vulkan/driver/CommandPool.cpp                          \
	libs/vulkan/driver/Common.cpp                               \
	libs/vulkan/driver/ControlListBuilder.cpp                   \
	libs/vulkan/driver/DebugReportCallbackEXT.cpp               \
	libs/vulkan/driver/DerivedViewportState.cpp                 \
	libs/vulkan/driver/DescriptorPool.cpp                       \
	libs/vulkan/driver/DescriptorSet.cpp                        \
	libs/vulkan/driver/DescriptorSetLayout.cpp                  \
	libs/vulkan/driver/Device.cpp                               \
	libs/vulkan/driver/DeviceMemory.cpp                         \
	libs/vulkan/driver/DevMemCmdBlock.cpp                       \
	libs/vulkan/driver/DevMemDataBlock.cpp                      \
	libs/vulkan/driver/DevMemHeap.cpp                           \
	libs/vulkan/driver/DSAspectCommandBuilder.cpp               \
	libs/vulkan/driver/entrypoints.cpp                          \
	libs/vulkan/driver/Event.cpp                                \
	libs/vulkan/driver/Extensions.cpp                           \
	libs/vulkan/driver/Fence.cpp                                \
	libs/vulkan/driver/Formats.cpp                              \
	libs/vulkan/driver/Framebuffer.cpp                          \
	libs/vulkan/driver/HeapManager.cpp                          \
	libs/vulkan/driver/Image.cpp                                \
	libs/vulkan/driver/ImageView.cpp                            \
	libs/vulkan/driver/Instance.cpp                             \
	libs/vulkan/driver/LinkResult.cpp                           \
	libs/vulkan/driver/lunargicd.cpp                            \
	libs/vulkan/driver/Options.cpp                              \
	libs/vulkan/driver/PhysicalDevice.cpp                       \
	libs/vulkan/driver/PipelineCache.cpp                        \
	libs/vulkan/driver/Pipeline.cpp                             \
	libs/vulkan/driver/PipelineLayout.cpp                       \
	libs/vulkan/driver/ProcAddressFinder.cpp                    \
	libs/vulkan/driver/QueryManager.cpp                         \
	libs/vulkan/driver/QueryPool.cpp                            \
	libs/vulkan/driver/Queue.cpp                                \
	libs/vulkan/driver/RenderPass.cpp                           \
	libs/vulkan/driver/Sampler.cpp                              \
	libs/vulkan/driver/SchedTask.cpp                            \
	libs/vulkan/driver/Semaphore.cpp                            \
	libs/vulkan/driver/ShaderModule.cpp                         \
	libs/vulkan/driver/SwapchainKHR.cpp                         \
	libs/vulkan/driver/TileStateMemory.cpp                      \
	libs/vulkan/driver/spirv/Module.cpp                         \
	libs/vulkan/driver/spirv/ModuleAllocator.cpp                \
	libs/vulkan/driver/spirv/Compiler.cpp                       \
	libs/vulkan/driver/spirv/Linker.cpp                         \
	libs/vulkan/driver/spirv/Dflow.cpp                          \
	libs/vulkan/driver/spirv/DflowScalars.cpp                   \
	libs/vulkan/driver/spirv/DflowBuilder.cpp                   \
	libs/vulkan/driver/spirv/TypeBuilder.cpp                    \
	libs/vulkan/driver/spirv/GatherNodes.cpp                    \
	libs/vulkan/driver/spirv/SymbolHandle.cpp                   \
	libs/vulkan/driver/spirv/SymbolTypeHandle.cpp               \
	libs/vulkan/driver/spirv/BasicBlock.cpp                     \
	libs/vulkan/driver/spirv/Nodes.cpp                          \
	libs/vulkan/driver/spirv/NodeData.cpp                       \
	libs/vulkan/driver/spirv/Decoration.cpp                     \
	libs/vulkan/driver/spirv/ImageOperands.cpp                  \
	libs/vulkan/driver/spirv/Extractor.cpp                      \
	libs/vulkan/driver/spirv/NodeIndex.cpp                      \
	libs/vulkan/driver/spirv/Composite.cpp                      \
	libs/vulkan/driver/spirv/FunctionContext.cpp                \
	libs/vulkan/driver/spirv/Pointer.cpp                        \
	libs/vulkan/driver/spirv/DescriptorMap.cpp                  \
	libs/vulkan/driver/spirv/Specialization.cpp                 \
	libs/vulkan/driver/spirv/TextureLookup.cpp                  \
	libs/vulkan/driver/spirv/CompiledShaderHandle.cpp           \
	libs/vulkan/driver/platforms/BVKPlatform.cpp                \
	libs/vulkan/driver/platforms/V3DPlatformBase.cpp            \
	libs/vulkan/driver/platforms/V3DPlatformNexusCommon.cpp     \
	libs/vulkan/driver/platforms/V3DPlatformNexusExclusive.cpp  \
	libs/vulkan/driver/platforms/V3DPlatformNxClient.cpp        \
	libs/vulkan/driver/platforms/V3DPlatformWayland.cpp         \
	libs/vulkan/driver/platforms/V3DPlatformAndroid.cpp         \
	../platform/common/memory_drm.c                             \
	../platform/common/memory_convert.c                         \
	../platform/common/display_helpers.c                        \
	../platform/common/sched_nexus.c
