/******************************************************************************
 * Copyright (C) 2018 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *****************************************************************************/

#ifndef BCHP_CDB_ITB_RDB_REMAP_H__
#define BCHP_CDB_ITB_RDB_REMAP_H__

#include "bchp_common.h"

#ifdef BCHP_OTT_XPT_CDB_ITB_REG_START
#include "bchp_ott_xpt_cdb_itb.h"

#define BCHP_XPT_RAVE_CX0_AV_ITB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_BASE_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_BASE_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_BASE_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_BASE_PTR

#define BCHP_XPT_RAVE_CX0_AV_ITB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_END_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_END_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_END_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_END_PTR

#define BCHP_XPT_RAVE_CX0_AV_ITB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_READ_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_READ_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_READ_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_READ_PTR

#define BCHP_XPT_RAVE_CX0_AV_ITB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_WRITE_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_WRITE_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_WRITE_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_WRITE_PTR

#define BCHP_XPT_RAVE_CX0_AV_ITB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX0_ITB_DEPTH
#define BCHP_XPT_RAVE_CX1_AV_ITB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX1_ITB_DEPTH
#define BCHP_XPT_RAVE_CX2_AV_ITB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX2_ITB_DEPTH
#define BCHP_XPT_RAVE_CX3_AV_ITB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX3_ITB_DEPTH

#define BCHP_XPT_RAVE_CX0_AV_ITB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_VALID_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_VALID_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_VALID_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_VALID_PTR

#define BCHP_XPT_RAVE_CX0_AV_ITB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX0_ITB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX1_AV_ITB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX1_ITB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX2_AV_ITB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX2_ITB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX3_AV_ITB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX3_ITB_WRAPAROUND_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_BASE_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_BASE_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_BASE_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_BASE_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_BASE_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_END_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_END_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_END_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_END_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_END_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_READ_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_READ_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_READ_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_READ_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_READ_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_WRITE_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_WRITE_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_WRITE_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_WRITE_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_WRITE_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX0_CDB_DEPTH
#define BCHP_XPT_RAVE_CX1_AV_CDB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX1_CDB_DEPTH
#define BCHP_XPT_RAVE_CX2_AV_CDB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX2_CDB_DEPTH
#define BCHP_XPT_RAVE_CX3_AV_CDB_DEPTH BCHP_OTT_XPT_CDB_ITB_CX3_CDB_DEPTH

#define BCHP_XPT_RAVE_CX0_AV_CDB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_VALID_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_VALID_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_VALID_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_VALID_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_VALID_PTR

#define BCHP_XPT_RAVE_CX0_AV_CDB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX0_CDB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX1_AV_CDB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX1_CDB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX2_AV_CDB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX2_CDB_WRAPAROUND_PTR
#define BCHP_XPT_RAVE_CX3_AV_CDB_WRAPAROUND_PTR BCHP_OTT_XPT_CDB_ITB_CX3_CDB_WRAPAROUND_PTR

#define BCHP_XPT_RAVE_CX0_AV_THRESHOLDS BCHP_OTT_XPT_CDB_ITB_CX0_THRESHOLDS
#define BCHP_XPT_RAVE_CX1_AV_THRESHOLDS BCHP_OTT_XPT_CDB_ITB_CX1_THRESHOLDS
#define BCHP_XPT_RAVE_CX2_AV_THRESHOLDS BCHP_OTT_XPT_CDB_ITB_CX2_THRESHOLDS
#define BCHP_XPT_RAVE_CX3_AV_THRESHOLDS BCHP_OTT_XPT_CDB_ITB_CX3_THRESHOLDS

#define XPT_RAVE_CX0_AV_THRESHOLDS OTT_XPT_CDB_ITB_CX0_THRESHOLDS

#define BCHP_XPT_RAVE_CX0_AV_THRESHOLDS_CONTEXT_OVERFLOW_THRESHOLD_MASK BCHP_OTT_XPT_CDB_ITB_CX0_THRESHOLDS_CONTEXT_OVERFLOW_THRESHOLD_MASK
#define BCHP_XPT_RAVE_CX0_AV_THRESHOLDS_CONTEXT_WRAPAROUND_THRESHOLD_MASK BCHP_OTT_XPT_CDB_ITB_CX0_THRESHOLDS_CONTEXT_WRAPAROUND_THRESHOLD_MASK
#endif /*BCHP_OTT_XPT_CDB_ITB_REG_START */

#endif /*  BCHP_CDB_ITB_RDB_REMAP_H__*/
