/******************************************************************************
 * Copyright (C) 2018 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/

#ifndef BCHP_I2C_RDB_REMAP_H__
#define BCHP_I2C_RDB_REMAP_H__

#include "bchp_common.h"

#ifdef BCHP_BSC_REG_START
#include "bchp_bsc.h"

#define BCHP_BSCA_IIC_ENABLE_NO_START_MASK BCHP_BSC_IIC_ENABLE_NO_START_MASK
#define BCHP_BSCA_IIC_ENABLE_NO_STOP_MASK BCHP_BSC_IIC_ENABLE_NO_STOP_MASK

#define BCHP_BSCA_IIC_ENABLE_NO_START_SHIFT BCHP_BSC_IIC_ENABLE_NO_START_SHIFT
#define BCHP_BSCA_IIC_ENABLE_NO_STOP_SHIFT BCHP_BSC_IIC_ENABLE_NO_STOP_SHIFT

#define BCHP_BSCA_IIC_ENABLE_RESTART_MASK BCHP_BSC_IIC_ENABLE_RESTART_MASK
#define BCHP_BSCA_IIC_ENABLE_RESTART_SHIFT BCHP_BSC_IIC_ENABLE_RESTART_SHIFT

#define BCHP_BSCA_IIC_ENABLE_ENABLE_MASK BCHP_BSC_IIC_ENABLE_ENABLE_MASK
#define BCHP_BSCA_IIC_ENABLE_ENABLE_SHIFT BCHP_BSC_IIC_ENABLE_ENABLE_SHIFT

#define BCHP_BSCA_CTL_REG_DIV_CLK_MASK BCHP_BSC_CTL_REG_DIV_CLK_MASK
#define BCHP_BSCA_CTL_REG_DIV_CLK_SHIFT BCHP_BSC_CTL_REG_DIV_CLK_SHIFT

#define BCHP_BSCA_CTL_REG_SCL_SEL_MASK BCHP_BSC_CTL_REG_SCL_SEL_MASK
#define BCHP_BSCA_CTL_REG_SCL_SEL_SHIFT BCHP_BSC_CTL_REG_SCL_SEL_SHIFT

#define BCHP_BSCA_CTL_REG_DTF_MASK BCHP_BSC_CTL_REG_DTF_MASK
#define BCHP_BSCA_CTL_REG_DTF_SHIFT BCHP_BSC_CTL_REG_DTF_SHIFT

#define BCHP_BSCA_CTL_REG_INT_EN_MASK BCHP_BSC_CTL_REG_INT_EN_MASK
#define BCHP_BSCA_CTL_REG_INT_EN_SHIFT BCHP_BSC_CTL_REG_INT_EN_SHIFT

#define BCHP_BSCA_CTLHI_REG_IGNORE_ACK_SHIFT BCHP_BSC_CTLHI_REG_IGNORE_ACK_SHIFT
#define BCHP_BSCA_CTLHI_REG_IGNORE_ACK_MASK BCHP_BSC_CTLHI_REG_IGNORE_ACK_MASK

#define BCHP_BSCA_CTLHI_REG_DATA_REG_SIZE_SHIFT BCHP_BSC_CTLHI_REG_DATA_REG_SIZE_SHIFT
#define BCHP_BSCA_CTLHI_REG_DATA_REG_SIZE_MASK BCHP_BSC_CTLHI_REG_DATA_REG_SIZE_MASK

#define BCHP_BSCA_CTLHI_REG_INPUT_SWITCHING_LEVEL_MASK BCHP_BSC_CTLHI_REG_INPUT_SWITCHING_LEVEL_MASK
#define BCHP_BSCA_CTLHI_REG_INPUT_SWITCHING_LEVEL_SHIFT BCHP_BSC_CTLHI_REG_INPUT_SWITCHING_LEVEL_SHIFT

#define BCHP_BSCA_CTL_REG BCHP_BSC_CTL_REG
#define BCHP_BSCA_CTLHI_REG BCHP_BSC_CTLHI_REG

#define BCHP_BSCA_IIC_ENABLE BCHP_BSC_IIC_ENABLE

#define BCHP_BSCA_IIC_ENABLE_INTRP_MASK BCHP_BSC_IIC_ENABLE_INTRP_MASK
#define BCHP_BSCA_IIC_ENABLE_NO_ACK_MASK BCHP_BSC_IIC_ENABLE_NO_ACK_MASK

#define BCHP_BSCA_CNT_REG BCHP_BSC_CNT_REG

#define BCHP_BSCA_CTL_REG_reserved0_MASK BCHP_BSC_CTL_REG_reserved0_MASK

#define BCHP_BSCA_DATA_IN0 BCHP_BSC_DATA_IN0
#define BCHP_BSCA_DATA_IN1 BCHP_BSC_DATA_IN1

#define BCHP_BSCA_DATA_OUT0 BCHP_BSC_DATA_OUT0

#define BCHP_BSCA_CHIP_ADDRESS BCHP_BSC_CHIP_ADDRESS

#define BCHP_BSCA_CNT_REG_CNT_REG1_SHIFT BCHP_BSC_CNT_REG_CNT_REG1_SHIFT
#define BCHP_BSCA_CNT_REG_CNT_REG1_MASK BCHP_BSC_CNT_REG_CNT_REG1_MASK
#define BCHP_BSCA_CNT_REG_CNT_REG2_SHIFT BCHP_BSC_CNT_REG_CNT_REG2_SHIFT
#define BCHP_BSCA_CNT_REG_CNT_REG2_MASK BCHP_BSC_CNT_REG_CNT_REG2_MASK

#endif /* BCHP_BSC_REG_START */

#endif /* BCHP_I2C_RDB_REMAP_H__ */
