/***************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *
 * Module Description:
 *
 ***************************************************************************/
#ifndef BVDC_ERRORS_H__
#define BVDC_ERRORS_H__

#include "berr_ids.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Error codes unique to BVDC.  Error has been reserved by berr module.
 * Each module has 0xfffff (64k) of errors. */

/* */
#define BVDC_ERR_VIDEOFMT_OUTPUT_MISMATCH            BERR_MAKE_CODE(BERR_VDC_ID, 0x0000)
#define BVDC_ERR_INVALID_656OUT_MODE                 BERR_MAKE_CODE(BERR_VDC_ID, 0x0001)
#define BVDC_ERR_INVALID_656OUT_USE                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0002)
#define BVDC_ERR_INVALID_HDMI_MODE                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0003)
#define BVDC_ERR_INVALID_HDMI_PATH                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0004)
#define BVDC_ERR_INVALID_HDMI_USE                    BERR_MAKE_CODE(BERR_VDC_ID, 0x0005)
#define BVDC_ERR_INVALID_MACROVISON_MODE             BERR_MAKE_CODE(BERR_VDC_ID, 0x0006)
#define BVDC_ERR_INVALID_MACROVISON_PATH             BERR_MAKE_CODE(BERR_VDC_ID, 0x0007)
#define BVDC_ERR_INVALID_MPAA_MODE                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0008)
#define BVDC_ERR_INVALID_MPAA_PATH                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0009)
#define BVDC_ERR_INVALID_DAC_SETTINGS                BERR_MAKE_CODE(BERR_VDC_ID, 0x000a)
#define BVDC_ERR_INVALID_RFM_PATH                    BERR_MAKE_CODE(BERR_VDC_ID, 0x000b)
#define BVDC_ERR_INVALID_FRAMERATE_USE               BERR_MAKE_CODE(BERR_VDC_ID, 0x000c)
#define BVDC_ERR_RFMOUT_WITHOUT_COMPOSITE            BERR_MAKE_CODE(BERR_VDC_ID, 0x000d)
#define BVDC_ERR_RFMOUT_MORE_THAN_ONE                BERR_MAKE_CODE(BERR_VDC_ID, 0x000e)
#define BVDC_ERR_HDMIOUT_MORE_THAN_ONE               BERR_MAKE_CODE(BERR_VDC_ID, 0x000f)
#define BVDC_ERR_656OUT_MORE_THAN_ONE                BERR_MAKE_CODE(BERR_VDC_ID, 0x0010)
#define BVDC_ERR_INVALID_MODE_PATH                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0011)
#define BVDC_ERR_DISPLAY_ALREADY_CREATED             BERR_MAKE_CODE(BERR_VDC_ID, 0x0012)
#define BVDC_ERR_INVALID_DCS_MODE                    BERR_MAKE_CODE(BERR_VDC_ID, 0x0013)
#define BVDC_ERR_INVALID_DCS_PATH                    BERR_MAKE_CODE(BERR_VDC_ID, 0x0014)
#define BVDC_ERR_UNSUPPORTED_PIXEL_RATE              BERR_MAKE_CODE(BERR_VDC_ID, 0x0015)


/* gfx feeder error code: 0x0100 - 0x01ff */
#define BVDC_ERR_GFX_SUR_SIZE_MISMATCH               BERR_MAKE_CODE(BERR_VDC_ID, 0x0100)
#define BVDC_ERR_GFX_SUR_FMT_MISMATCH                BERR_MAKE_CODE(BERR_VDC_ID, 0x0101)
#define BVDC_ERR_GFX_HORIZONTAL_SHRINK               BERR_MAKE_CODE(BERR_VDC_ID, 0x0102)
#define BVDC_ERR_GFX_VERTICAL_SCALE                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0103)
#define BVDC_ERR_GFX_SRC_OVER_CLIP                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0104)
#define BVDC_ERR_GFX_CLUT_REUSE                      BERR_MAKE_CODE(BERR_VDC_ID, 0x0105)
#define BVDC_ERR_GFX_INFINITE_SCALE                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0106)
#define BVDC_ERR_GFX_SUR_UNSURE                      BERR_MAKE_CODE(BERR_VDC_ID, 0x0107)
#define BVDC_ERR_GFX_HSCL_OUT_OF_RANGE               BERR_MAKE_CODE(BERR_VDC_ID, 0x0108)
#define BVDC_ERR_GFX_VSCL_OUT_OF_RANGE               BERR_MAKE_CODE(BERR_VDC_ID, 0x0109)
#define BVDC_ERR_GFX_UNSUPPORTED_GAMMATABLE          BERR_MAKE_CODE(BERR_VDC_ID, 0x010a)

#define BVDC_ERR_SRC_IS_NOT_MPEG                     BERR_MAKE_CODE(BERR_VDC_ID, 0x0200)

#define BVDC_ERR_SOURCE_WINDOW_MISMATCH              BERR_MAKE_CODE(BERR_VDC_ID, 0x0300)
#define BVDC_ERR_VIDEO_FORMAT_NOT_SUPPORTED          BERR_MAKE_CODE(BERR_VDC_ID, 0x0301)
#define BVDC_ERR_DST_SIZE_LARGER_THAN_CANVAS         BERR_MAKE_CODE(BERR_VDC_ID, 0x0302)
#define BVDC_ERR_APL_SIZE_LARGER_THAN_CANVAS         BERR_MAKE_CODE(BERR_VDC_ID, 0x0303)
#define BVDC_ERR_DST_SIZE_LARGER_THAN_SCL_OUTPUT     BERR_MAKE_CODE(BERR_VDC_ID, 0x0304)
#define BVDC_ERR_SOURCE_ALREADY_CREATED              BERR_MAKE_CODE(BERR_VDC_ID, 0x0305)
#define BVDC_ERR_WINDOW_ALREADY_CREATED              BERR_MAKE_CODE(BERR_VDC_ID, 0x0306)
#define BVDC_ERR_COMPOSITOR_ALREADY_CREATED          BERR_MAKE_CODE(BERR_VDC_ID, 0x0307)
#define BVDC_ERR_DUPLICATED_ZORDER                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0308)
#define BVDC_ERR_WINDOW_NOT_AVAILABLE                BERR_MAKE_CODE(BERR_VDC_ID, 0x0309)
#define BVDC_ERR_INVALID_ADC_FOR_COMPOSITE           BERR_MAKE_CODE(BERR_VDC_ID, 0x030A)
#define BVDC_ERR_INVALID_ADC_FOR_SVIDEO              BERR_MAKE_CODE(BERR_VDC_ID, 0x030B)
#define BVDC_ERR_INVALID_ADC_FOR_COMPONENT           BERR_MAKE_CODE(BERR_VDC_ID, 0x030C)
#define BVDC_ERR_INVALID_ADC_FOR_IFDEMOD             BERR_MAKE_CODE(BERR_VDC_ID, 0x030D)
#define BVDC_ERR_ILLEGAL_CLIPPING_VALUES             BERR_MAKE_CODE(BERR_VDC_ID, 0x030E)
#define BVDC_ERR_ILLEGAL_GFX_WIN_BLEND               BERR_MAKE_CODE(BERR_VDC_ID, 0x030F)
#define BVDC_ERR_SCALER_OUTPUT_OUT_OF_BOUND          BERR_MAKE_CODE(BERR_VDC_ID, 0x0310)
#define BVDC_ERR_DEINTERLACE_TO_INTERLACED_FORMAT    BERR_MAKE_CODE(BERR_VDC_ID, 0x0311)
#define BVDC_ERR_DEINTERLACE_NON_MAIN_WINDOW         BERR_MAKE_CODE(BERR_VDC_ID, 0x0312)
#define BVDC_ERR_MULTI_PHASE_ADJUST_VALUES           BERR_MAKE_CODE(BERR_VDC_ID, 0x0313)
#define BVDC_ERR_BOX_DETECT_GFX                      BERR_MAKE_CODE(BERR_VDC_ID, 0x0314)
#define BVDC_ERR_BOX_DETECT_HW_NOT_AVAILABLE         BERR_MAKE_CODE(BERR_VDC_ID, 0x0315)
#define BVDC_ERR_ADC_NOT_SUPPORTED                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0317)
#define BVDC_ERR_COMPONENT_VDEC_DISABLED_BY_DEFAULT  BERR_MAKE_CODE(BERR_VDC_ID, 0x0318)
#define BVDC_ERR_PHASE_ADJUST_ON_ILLEGAL_SOURCE      BERR_MAKE_CODE(BERR_VDC_ID, 0x0319)
#define BVDC_ERR_PHASE_ADJUST_ON_DOWNSCALED_WINDOWS  BERR_MAKE_CODE(BERR_VDC_ID, 0x031A)
#define BVDC_ERR_LIP_SYNC_DELAY_MORE_THAN_MAX        BERR_MAKE_CODE(BERR_VDC_ID, 0x031B)
#define BVDC_ERR_BYPASS_SOURCE_DISPLAY_MISMATCH      BERR_MAKE_CODE(BERR_VDC_ID, 0x031C)
#define BVDC_ERR_INVALID_NONLINEAR_SCALE             BERR_MAKE_CODE(BERR_VDC_ID, 0x031D)
#define BVDC_ERR_INVALID_SRC_ASPECT_RATIO_RECT       BERR_MAKE_CODE(BERR_VDC_ID, 0x031E)
#define BVDC_ERR_INVALID_DISP_ASPECT_RATIO_RECT      BERR_MAKE_CODE(BERR_VDC_ID, 0x031F)
#define BVDC_ERR_CAPTURE_BUFFERS_MORE_THAN_MAX       BERR_MAKE_CODE(BERR_VDC_ID, 0x0320)
#define BVDC_ERR_CAPTURED_BUFFER_NOT_FOUND           BERR_MAKE_CODE(BERR_VDC_ID, 0x0321)
#define BVDC_ERR_USER_STILL_HAS_CAPTURE_BUFFER       BERR_MAKE_CODE(BERR_VDC_ID, 0x0322)
#define BVDC_ERR_NO_AVAIL_CAPTURE_BUFFER             BERR_MAKE_CODE(BERR_VDC_ID, 0x0323)
#define BVDC_ERR_NO_VIDEO_SOURCE                     BERR_MAKE_CODE(BERR_VDC_ID, 0x0324)
#define BVDC_ERR_BYPASS_WINDOW_NOT_FULL_SCREEN       BERR_MAKE_CODE(BERR_VDC_ID, 0x0325)
#define BVDC_ERR_BYPASS_WINDOW_INVALID_AR_MODE       BERR_MAKE_CODE(BERR_VDC_ID, 0x0326)
#define BVDC_ERR_INVALID_HD_BUFFER_FORMAT            BERR_MAKE_CODE(BERR_VDC_ID, 0x0327)
#define BVDC_ERR_DST_RECT_OUT_OF_BOUND               BERR_MAKE_CODE(BERR_VDC_ID, 0x0328)
#define BVDC_ERR_MAD_NOT_SUPPORTED                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0329)
#define BVDC_ERR_RESOURCE_NOT_AVAILABLE              BERR_MAKE_CODE(BERR_VDC_ID, 0x0330)
#define BVDC_ERR_RESOURCE_NOT_RECORDED               BERR_MAKE_CODE(BERR_VDC_ID, 0x0331)
#define BVDC_ERR_RESOURCE_NOT_ACQUIRED               BERR_MAKE_CODE(BERR_VDC_ID, 0x0332)
#define BVDC_ERR_ANR_HW_NOT_AVAILABLE                BERR_MAKE_CODE(BERR_VDC_ID, 0x0333)
#define BVDC_ERR_BAD_SRC_TYPE                        BERR_MAKE_CODE(BERR_VDC_ID, 0x0334)
#define BVDC_ERR_INVALID_HVSTART                     BERR_MAKE_CODE(BERR_VDC_ID, 0x0335)
#define BVDC_ERR_INVALID_TOLERANCE                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0336)
#define BVDC_ERR_FGT_NOT_SUPPORTED                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0337)
#define BVDC_ERR_INVALID_ADC_FOR_SCART               BERR_MAKE_CODE(BERR_VDC_ID, 0x0338)
#define BVDC_ERR_MCVP_NOT_SUPPORTED                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0339)
#define BVDC_ERR_BAD_BUFFER_HEAP_NODE                BERR_MAKE_CODE(BERR_VDC_ID, 0x033A)

#define BVDC_ERR_PEP_WINDOW_NOT_SUPPORT              BERR_MAKE_CODE(BERR_VDC_ID, 0x0400)
#define BVDC_ERR_PEP_INVALID_PARAMETER               BERR_MAKE_CODE(BERR_VDC_ID, 0x0401)
#define BVDC_ERR_TNT_WINDOW_NOT_SUPPORTED            BERR_MAKE_CODE(BERR_VDC_ID, 0x0402)
#define BVDC_ERR_INVALID_TARGET_DISPLAY              BERR_MAKE_CODE(BERR_VDC_ID, 0x0403)
#define BVDC_ERR_INVALID_TIMESTAMP                   BERR_MAKE_CODE(BERR_VDC_ID, 0x0404)
#define BVDC_ERR_3D_INDEP_SRC_CLIP_NOT_SUPPORTED     BERR_MAKE_CODE(BERR_VDC_ID, 0x0405)

#define BVDC_ERR_INVALID_MOSAIC_MODE                 BERR_MAKE_CODE(BERR_VDC_ID, 0x0501)
#define BVDC_ERR_INVALID_TUNE_INTERFACE              BERR_MAKE_CODE(BERR_VDC_ID, 0x0502)
#define BVDC_ERR_INVALID_TUNE_STRUCTURE              BERR_MAKE_CODE(BERR_VDC_ID, 0x0503)
#define BVDC_ERR_INVALID_TUNE_FIELD                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0504)
#define BVDC_ERR_TUNE_NOT_SUPPORTED                  BERR_MAKE_CODE(BERR_VDC_ID, 0x0505)

#define BVDC_ERR_FORMAT_NOT_SUPPORT_ANALOG_OUTPUT    BERR_MAKE_CODE(BERR_VDC_ID, 0x0600)

#define BVDC_ERR_FEATURE_NOT_SUPPORTED               BERR_MAKE_CODE(BERR_VDC_ID, 0x0700)

#ifdef __cplusplus
}
#endif

#endif /* #ifndef BVDC_ERRORS_H__ */
/* End of file. */
