/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Fri Aug 15 15:20:53 2014
 *                 Full Compile MD5 Checksum  a68bc62e9dd3be19fcad480c369d60fd
 *                     (minus title and desc)
 *                 MD5 Checksum               14382795d76d8497c2dd1bcf3f5d36da
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14541
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_BVN_RGR_H__
#define BCHP_BVN_RGR_H__

/***************************************************************************
 *BVN_RGR - BVN RGR Bridge Registers
 ***************************************************************************/
#define BCHP_BVN_RGR_REVISION                    0x006c0000 /* [RO] RGR Bridge Revision */
#define BCHP_BVN_RGR_CTRL                        0x006c0004 /* [RW] RGR Bridge Control Register */
#define BCHP_BVN_RGR_RBUS_TIMER                  0x006c0008 /* [RW] RGR Bridge RBUS Timer Register */
#define BCHP_BVN_RGR_SW_INIT_0                   0x006c000c /* [RW] RGR Bridge Software Init 0 Register */
#define BCHP_BVN_RGR_SW_INIT_1                   0x006c0010 /* [RW] RGR Bridge Software Init 1 Register */

/***************************************************************************
 *REVISION - RGR Bridge Revision
 ***************************************************************************/
/* BVN_RGR :: REVISION :: reserved0 [31:16] */
#define BCHP_BVN_RGR_REVISION_reserved0_MASK                       0xffff0000
#define BCHP_BVN_RGR_REVISION_reserved0_SHIFT                      16

/* BVN_RGR :: REVISION :: MAJOR [15:08] */
#define BCHP_BVN_RGR_REVISION_MAJOR_MASK                           0x0000ff00
#define BCHP_BVN_RGR_REVISION_MAJOR_SHIFT                          8
#define BCHP_BVN_RGR_REVISION_MAJOR_DEFAULT                        0x00000002

/* BVN_RGR :: REVISION :: MINOR [07:00] */
#define BCHP_BVN_RGR_REVISION_MINOR_MASK                           0x000000ff
#define BCHP_BVN_RGR_REVISION_MINOR_SHIFT                          0
#define BCHP_BVN_RGR_REVISION_MINOR_DEFAULT                        0x00000000

/***************************************************************************
 *CTRL - RGR Bridge Control Register
 ***************************************************************************/
/* BVN_RGR :: CTRL :: reserved0 [31:02] */
#define BCHP_BVN_RGR_CTRL_reserved0_MASK                           0xfffffffc
#define BCHP_BVN_RGR_CTRL_reserved0_SHIFT                          2

/* BVN_RGR :: CTRL :: rbus_error_intr [01:01] */
#define BCHP_BVN_RGR_CTRL_rbus_error_intr_MASK                     0x00000002
#define BCHP_BVN_RGR_CTRL_rbus_error_intr_SHIFT                    1
#define BCHP_BVN_RGR_CTRL_rbus_error_intr_DEFAULT                  0x00000000
#define BCHP_BVN_RGR_CTRL_rbus_error_intr_INTR_DISABLE             0
#define BCHP_BVN_RGR_CTRL_rbus_error_intr_INTR_ENABLE              1

/* BVN_RGR :: CTRL :: gisb_error_intr [00:00] */
#define BCHP_BVN_RGR_CTRL_gisb_error_intr_MASK                     0x00000001
#define BCHP_BVN_RGR_CTRL_gisb_error_intr_SHIFT                    0
#define BCHP_BVN_RGR_CTRL_gisb_error_intr_DEFAULT                  0x00000000
#define BCHP_BVN_RGR_CTRL_gisb_error_intr_INTR_DISABLE             0
#define BCHP_BVN_RGR_CTRL_gisb_error_intr_INTR_ENABLE              1

/***************************************************************************
 *RBUS_TIMER - RGR Bridge RBUS Timer Register
 ***************************************************************************/
/* BVN_RGR :: RBUS_TIMER :: reserved0 [31:16] */
#define BCHP_BVN_RGR_RBUS_TIMER_reserved0_MASK                     0xffff0000
#define BCHP_BVN_RGR_RBUS_TIMER_reserved0_SHIFT                    16

/* BVN_RGR :: RBUS_TIMER :: timer_value [15:00] */
#define BCHP_BVN_RGR_RBUS_TIMER_timer_value_MASK                   0x0000ffff
#define BCHP_BVN_RGR_RBUS_TIMER_timer_value_SHIFT                  0
#define BCHP_BVN_RGR_RBUS_TIMER_timer_value_DEFAULT                0x0000ffff

/***************************************************************************
 *SW_INIT_0 - RGR Bridge Software Init 0 Register
 ***************************************************************************/
/* BVN_RGR :: SW_INIT_0 :: reserved0 [31:00] */
#define BCHP_BVN_RGR_SW_INIT_0_reserved0_MASK                      0xffffffff
#define BCHP_BVN_RGR_SW_INIT_0_reserved0_SHIFT                     0

/***************************************************************************
 *SW_INIT_1 - RGR Bridge Software Init 1 Register
 ***************************************************************************/
/* BVN_RGR :: SW_INIT_1 :: reserved0 [31:00] */
#define BCHP_BVN_RGR_SW_INIT_1_reserved0_MASK                      0xffffffff
#define BCHP_BVN_RGR_SW_INIT_1_reserved0_SHIFT                     0

#endif /* #ifndef BCHP_BVN_RGR_H__ */

/* End of File */
