/******************************************************************************
 *  Copyright (C) 2017 Broadcom.  The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 ******************************************************************************/

#ifdef BCHP_PWR_RESOURCE_XPT
#if ( BCHP_CHIP==7271 || BCHP_CHIP==7268 || BCHP_CHIP==7260 )
#include "bchp_xpt_pmu_scb.h"
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_FE_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_MCPB_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_MEMDMA_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_MSG_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_RAVE_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_TSIO_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_PCROFFSET_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_PSUB_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_RSBUFF_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_XCBUFF_SP_PD_MEM_PWR_DN_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_HWG_CLK_GATE_SUB_MODULE_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_PMU_SCB_SCB_HWG_CLK_GATE_SUB_MODULE_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR0_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR1_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR2_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR3_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR4_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_DPCR5_PCR_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB0_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB0_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB1_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB1_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB2_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB2_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB3_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB3_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB4_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB4_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB5_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB5_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB6_STAT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PSUB_PSUB6_STAT2)
BXPT_REGISTER_READONLY(BCHP_XPT_MPOD_RES_FIELD)
BXPT_REGISTER_READONLY(BCHP_XPT_RSBUFF_PAUSE_STATUS_PBP)
BXPT_REGISTER_READONLY(BCHP_XPT_RSBUFF_WR_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_RSBUFF_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_RSBUFF_MPOD_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_RSBUFF_TSIO_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_XCBUFF_WR_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_XCBUFF_RMX0_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_XCBUFF_RMX1_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_XCBUFF_MSG_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_XCBUFF_RAVE_RD_DEBUG)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT0)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT0_HI)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT0_LO)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT1)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT1_HI)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT1_LO)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT2)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT2_HI)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT2_LO)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT3)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT3_HI)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT3_LO)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT4)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT4_HI)
BXPT_REGISTER_READONLY(BCHP_XPT_PCROFFSET_STC_SNAPSHOT4_LO)
BXPT_REGISTER_READONLY(BCHP_XPT_TSIO_CALIB_REGISTERS_CURR_TRAINING_MEMORY_ADDR)
BXPT_REGISTER_READONLY(BCHP_XPT_TSIO_CALIB_REGISTERS_VDL_CALIB_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_TSIO_CALIB_REGISTERS_CURR_XVDL_A_VALUE)
BXPT_REGISTER_READONLY(BCHP_XPT_TSIO_CALIB_REGISTERS_CURR_XVDL_B_VALUE)
BXPT_REGISTER_READONLY(BCHP_XPT_TSIO_CALIB_REGISTERS_CURR_XVDL_C_VALUE)
BXPT_REGISTER_READONLY(BCHP_XPT_FULL_PID_PARSER_LATEST_INTR_CH_NUM)
BXPT_REGISTER_READONLY(BCHP_XPT_FE_TSMF0_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_RAVE_AV_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_RAVE_PACKET_COUNT)
BXPT_REGISTER_READONLY(BCHP_XPT_RAVE_AV_STATUS2)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_READ_INTR_L2_CPU_MASK_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_READ_INTR_L2_PCI_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_READ_INTR_L2_PCI_MASK_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_END_INTR_L2_CPU_MASK_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_END_INTR_L2_PCI_STATUS)
BXPT_REGISTER_READONLY(BCHP_XPT_MCPB_MISC_PAUSE_AT_DESC_END_INTR_L2_PCI_MASK_STATUS)
#endif
#endif
