# All router Apps, NIC drivers sources Directories.
export STBAP_APPS_DIR=./
export STBAP_NIC_DRIVER_DIR=../

# Build environment variables
export TOOLCHAIN=/projects/hnd/tools/linux/BCG/stbgcc-4.8-1.5
export LINUX=/projects/hnd/tools/linux/BCG/stblinux-4.1-1.2-netfilter/linux
export LINUXVER=4.1.2
export LINUX_VERSION=4_1_2
export PATH=${TOOLCHAIN}/bin:$PATH
export ARCHTOOL=arm-linux
export WLARCH=arm
export TARGETENV=linuxarm_le
