/***************************************************************************
 *     Copyright (c) 2005-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 * Revision History:
 * $brcm_Log: $
 * 
 ***************************************************************/
#ifndef BRAP_IMG_H__
#define BRAP_IMG_H__

#include "bimg.h"

#if((BCHP_CHIP == 7405)||(BCHP_CHIP == 7325) || (BCHP_CHIP == 7335))
#define BRAP_7405_FAMILY    1
#endif

#if ((BCHP_CHIP == 7440)||(BCHP_CHIP == 7601))
#define BRAP_DVD_FAMILY     1
#endif

#if (BCHP_CHIP == 7403)
#define BRAP_DTS_SUPPORTED    1
#endif

#if (BCHP_CHIP == 7400)
#define BRAP_DTS_PASSTHRU_SUPPORTED    1
#endif

/* 
	Firmware Image IDs that are to be used in the BRAP_IMG_Open function of the BRAP_IMG_Interface
*/
#define BRAP_IMG_IBOOT_ID 0

#define BRAP_IMG_SCHEDULER_CODE_ID 1
#define BRAP_IMG_SCHEDULER_DATA_ID 2

#define BRAP_IMG_MPEG_FRAMESYNC_ID 3
#define BRAP_IMG_AC3_FRAMESYNC_ID 4

#define BRAP_IMG_MPEG_L1_DECODE_ID 5
#define BRAP_IMG_MPEG_L2_DECODE_ID 6
#define BRAP_IMG_MP3_DECODE_ID 7
#define BRAP_IMG_AC3_DECODE_ID 8

#define BRAP_IMG_MPEG_DECODE_TABLE_ID 9
#define BRAP_IMG_AC3_DECODE_TABLE_ID 10

#define BRAP_IMG_AC3_DOWNMIX_CODE_ID 11
#define BRAP_IMG_AC3_DOWNMIX_TABLE_ID 12

#define BRAP_IMG_AC3_PASSTHRU_ID 13
#define BRAP_IMG_MPEG_PASSTHRU_ID 14

#define BRAP_IMG_MPEG_INTERFRAME_ID 15

#define BRAP_IMG_AAC_FRAMESYNC_ID 16
#define BRAP_IMG_AAC_DECODE_ID 17
#define BRAP_IMG_AAC_DECODE_TABLE_ID 18
#define BRAP_IMG_AAC_INTERFRAME_ID 19
#define BRAP_IMG_AAC_PASSTHRU_ID 20
#define BRAP_IMG_AAC_DOWNMIX_ID 21

#define BRAP_IMG_AACHE_FRAMESYNC_ID 22
#define BRAP_IMG_AACHE_DECODE_ID 23
#define BRAP_IMG_AACHE_DECODE_TABLE_ID 24
#define BRAP_IMG_AACHE_INTERFRAME_ID 25

#define BRAP_IMG_DDP_FRAMESYNC_ID 26
#define BRAP_IMG_DDP_BE_DECODE_ID 27
#define BRAP_IMG_DDP_FE_DECODE_ID 28
#define BRAP_IMG_DDP_DECODE_TABLE_ID 29
#define BRAP_IMG_DDP_INTERFRAME_ID 30

#define BRAP_IMG_DDP_PASSTHRU_ID 31
#define BRAP_IMG_DDP_PASSTHRU_INTERFRAME_ID 32
#define BRAP_IMG_DDP_PASSTHRU_TABLE_ID 33

#define BRAP_IMG_DTS_FRAMESYNC_ID 34
#define BRAP_IMG_DTS_DECODE_ID 35
#define BRAP_IMG_DTS_DECODE_TABLE_ID 36
#define BRAP_IMG_DTS_INTERFRAME_ID 37
#define BRAP_IMG_DTS_PASSTHRU_ID 38

#define BRAP_IMG_BD_LPCM_FRAMESYNC_ID 39
#define BRAP_IMG_BD_LPCM_DECODE_ID 40

/* Merging Decoder & Encoder */
#define BRAP_IMG_ENC_IBOOT_ID 41

#define BRAP_IMG_ENC_SCHEDULER_CODE_ID 42
#define BRAP_IMG_ENC_SCHEDULER_DATA_ID 43

#define BRAP_IMG_MP3_ENCODE_TABLE_ID 44
#define BRAP_IMG_MP3_ENCODE_INTER_FRAME_ID 45
#define BRAP_IMG_MP3_ENCODE_INTER_STAGE_ID 46
#define BRAP_IMG_MP3_ENCODE_SCRATCH_ID 47
#define BRAP_IMG_MP3_ENCODE_STG0_ID 48
#define BRAP_IMG_MP3_ENCODE_STG1_ID 49
#define BRAP_IMG_MP3_ENCODE_STG2_ID 50
#define BRAP_IMG_MP3_ENCODE_STG3_ID 51
#define BRAP_IMG_MP3_ENCODE_STG4_ID 52


#define BRAP_IMG_LPCM_HDDVD_FRAMESYNC_ID 53 
#define BRAP_IMG_LPCM_HDDVD_DECODE_ID 54 


/* Note: Except for the frame-sync, all other fw is common between DTS and DTS-HD */
#define BRAP_IMG_DTSHD_FRAMESYNC_ID 55
#define BRAP_IMG_DTSHD_DECODE_ID BRAP_IMG_DTS_DECODE_ID
#define BRAP_IMG_DTSHD_DECODE_TABLE_ID BRAP_IMG_DTS_DECODE_TABLE_ID
#define BRAP_IMG_DTSHD_INTERFRAME_ID BRAP_IMG_DTS_INTERFRAME_ID
#define BRAP_IMG_DTSHD_PASSTHRU_ID BRAP_IMG_DTS_PASSTHRU_ID
/*#define BRAP_IMG_LPCM_HDDVD_FRAMESYNC_ID 56
#define BRAP_IMG_LPCM_HDDVD_DECODE_ID 57*/

#define BRAP_IMG_DDBM_ID 56
#define BRAP_IMG_DDBM_TABLE_ID 57

#define BRAP_IMG_LPCM_DVD_FRAMESYNC_ID 58 
#define BRAP_IMG_LPCM_DVD_DECODE_ID 59 

#if (BRAP_DVD_FAMILY == 1)
#define BRAP_IMG_WMA_STD_FRAMESYNC_ID 60
#define BRAP_IMG_WMA_STD_STG0_DECODE_ID 61
#define BRAP_IMG_WMA_STD_STG0_DECODE_TABLE_ID 62
#define BRAP_IMG_WMA_STD_INTERFRAME_ID 63


#else
#define BRAP_IMG_WMA_STD_FRAMESYNC_ID 60
#define BRAP_IMG_WMA_STD_STG1_DECODE_ID 61
#define BRAP_IMG_WMA_STD_STG1_DECODE_TABLE_ID 62
#define BRAP_IMG_WMA_STD_INTERFRAME_ID 63
#endif

/* Note: Except for the frame-sync, all other fw is common between AC3 Lossless and AC3 */
#define BRAP_IMG_AC3LOSSLESS_FRAMESYNC_ID 64
#define BRAP_IMG_AC3LOSSLESS_BE_DECODE_ID BRAP_IMG_DDP_BE_DECODE_ID
#define BRAP_IMG_AC3LOSSLESS_FE_DECODE_ID BRAP_IMG_DDP_FE_DECODE_ID
#define BRAP_IMG_AC3LOSSLESS_DECODE_TABLE_ID BRAP_IMG_DDP_DECODE_TABLE_ID
#define BRAP_IMG_AC3LOSSLESS_INTERFRAME_ID BRAP_IMG_DDP_INTERFRAME_ID

#define BRAP_IMG_AC3LOSSLESS_PASSTHRU_ID BRAP_IMG_DDP_PASSTHRU_ID
#define BRAP_IMG_AC3LOSSLESS_PASSTHRU_INTERFRAME_ID BRAP_IMG_DDP_PASSTHRU_INTERFRAME_ID
#define BRAP_IMG_AC3LOSSLESS_PASSTHRU_TABLE_ID BRAP_IMG_DDP_PASSTHRU_TABLE_ID

#define BRAP_IMG_DTSHD_HDDVD_FRAMESYNC_ID 65

#define BRAP_IMG_BD_LPCM_INTERFRAME_ID 66
#define BRAP_IMG_LPCM_DVD_INTERFRAME_ID 67
#define BRAP_IMG_LPCM_HDDVD_INTERFRAME_ID 68

#define BRAP_IMG_MLP_DECODE_ID 69
#define BRAP_IMG_MLP_DECODE_TABLE_ID 70
#define BRAP_IMG_MLP_FRAMESYNC_ID 71
#define BRAP_IMG_MLP_HDDVD_FRAMESYNC_ID 72

#define BRAP_IMG_DTS_ENCODE_CODE_ID 73
#define BRAP_IMG_DTS_ENCODE_TABLE_ID 74
#define BRAP_IMG_DTS_ENCODE_INTER_FRAME_ID 75
#define BRAP_IMG_DTS_ENCODE_INTER_STAGE_ID 76
#define BRAP_IMG_DTS_ENCODE_SCRATCH_ID 77

#define BRAP_IMG_DDP_CONVERT_ID 78

#define BRAP_IMG_BTSC_US_ID 79
#define BRAP_IMG_BTSC_JAPAN_ID 80
#define BRAP_IMG_BTSC_KOREA_ID 81

#define BRAP_IMG_PES_FRAMESYNC_ID   82
#define BRAP_IMG_LPCM_CUSTOM_CODE_ID    83

/* DTS and DTS-HD extensions */
#define BRAP_IMG_DTS_1_DECODE_ID 84
#define BRAP_IMG_DTSHD_1_DECODE_ID BRAP_IMG_DTS_1_DECODE_ID


#define BRAP_IMG_SRC_ID 85
#define BRAP_IMG_SRC_TABLE_ID 86
#define BRAP_IMG_SRC_INTERFRAME_ID 87

#define BRAP_IMG_PL2_ID 88
#define BRAP_IMG_PL2_TABLE_ID 89
#define BRAP_IMG_PL2_INTERFRAME_ID 90
#define BRAP_IMG_SRSXT_ID 91
#define BRAP_IMG_SRSXT_TABLE_ID 92
#define BRAP_IMG_SRSXT_INTERFRAME_ID 93
#define BRAP_IMG_AVL_ID 94
#define BRAP_IMG_AVL_TABLE_ID 95
#define BRAP_IMG_AVL_INTERFRAME_ID 96

#define BRAP_IMG_DDBM_INTERFRAME_ID 97

/* DSP1 scheduler */
#define BRAP_IMG_SCHEDULER_DSP1_CODE_ID 98
#define BRAP_IMG_SCHEDULER_DSP1_DATA_ID 99

/* DTS-LBR to be contd later.. */
#define BRAP_IMG_DTSLBR_FRAMESYNC_ID    	100
#define BRAP_IMG_DTSLBR_0_DECODE_ID     	101
#define BRAP_IMG_DTSLBR_DECODE_TABLE_ID 	102
#define BRAP_IMG_DTSLBR_INTERFRAME_ID   	103

/* MLP interframe */
#define BRAP_IMG_MLP_INTERFRAME_ID      104

/* XEN post processing algorithm */
#define BRAP_IMG_XEN_ID	105
#define BRAP_IMG_XEN_TABLE_ID		106
#define BRAP_IMG_XEN_INTERFRAME_ID	107

/* BBE post processing algorithm */
#define BRAP_IMG_BBE_ID	108
#define BRAP_IMG_BBE_TABLE_ID	109
#define BRAP_IMG_BBE_INTERFRAME_ID	110

/* For DSOLA post processing */
#define BRAP_IMG_DSOLA_ID 111
#define BRAP_IMG_DSOLA_TABLE_ID 112
#define BRAP_IMG_DSOLA_INTERFRAME_ID 113

/* AAC HE Low power SBR */
#define BRAP_IMG_AACHE_LP_DECODE_STG0_ID	114
#define BRAP_IMG_AACHE_LP_DECODE_STG1_ID	115
#define BRAP_IMG_AACHE_LP_DECODE_STG2_ID	116
#define BRAP_IMG_AACHE_LP_INTERFRAME_ID		117
#define BRAP_IMG_AACHE_LP_TABLE_STG0_ID		118
#define BRAP_IMG_AACHE_LP_TABLE_STG1_ID		119

/* AAC HE pass through */
#define BRAP_IMG_AACHE_PASSTHRU_ID	120

#define BRAP_IMG_DDP_7_1_FRAMESYNC_ID 121
#define BRAP_IMG_DDP_7_1_BE_DECODE_ID 122
#define BRAP_IMG_DDP_7_1_FE_DECODE_ID 123
#define BRAP_IMG_DDP_7_1_DECODE_TABLE_ID 124
#define BRAP_IMG_DDP_7_1_INTERFRAME_ID 125

#define BRAP_IMG_MPEG_MC_FRAMESYNC_ID 126
#define BRAP_IMG_MPEG_MC_DECODE_ID 127
#define BRAP_IMG_MPEG_MC_DECODE_TABLE_ID 128
#define BRAP_IMG_MPEG_MC_PASSTHRU_ID 129

/* For DTS-NEO post processing */
#define BRAP_IMG_DTS_NEO_ID             130
#define BRAP_IMG_DTS_NEO_TABLE_ID       131
#define BRAP_IMG_DTS_NEO_INTERFRAME_ID  132

#define BRAP_IMG_DTSHD_2_DECODE_ID 133
#define BRAP_IMG_DTSHD_3_DECODE_ID 134
#define BRAP_IMG_DTSHD_4_DECODE_ID 135


#define BRAP_IMG_WMA_PRO_FRAMESYNC_ID 136
#define BRAP_IMG_WMA_PRO_DECODE_STG0_ID 137
#define BRAP_IMG_WMA_PRO_DECODE_STG1_ID 138
#define BRAP_IMG_WMA_PRO_DECODE_TABLE_ID 139
#define BRAP_IMG_WMA_PRO_PASSTHRU_ID 140

/* DTS-LBR contd */
#define BRAP_IMG_DTSLBR_EXSS_DECODE_ID       141

#define BRAP_IMG_DDP_7_1_PASSTHRU_ID   142
#define BRAP_IMG_MLP_PASSTHRU_ID   	   143	
#define BRAP_IMG_DTSHD_HBR_PASSTHRU_ID 144

/* Custom Surround post processing algorithm */
#define BRAP_IMG_CUSTOM_SURROUND_ID	145
#define BRAP_IMG_CUSTOM_SURROUND_TABLE_ID	146
#define BRAP_IMG_CUSTOM_SURROUND_INTERFRAME_ID	147

/* Custom Bass post processing algorithm */
#define BRAP_IMG_CUSTOM_BASS_ID	148
#define BRAP_IMG_CUSTOM_BASS_TABLE_ID	149
#define BRAP_IMG_CUSTOM_BASS_INTERFRAME_ID	150

/* Custom Voice post processing algorithm */
#define BRAP_IMG_CUSTOM_VOICE_ID	151
#define BRAP_IMG_CUSTOM_VOICE_TABLE_ID	152
#define BRAP_IMG_CUSTOM_VOICE_INTERFRAME_ID	153

/* DTS-LBR contd */
#define BRAP_IMG_DTSLBR_1_DECODE_ID     154

/* Peq post processing algorithm */
#define BRAP_IMG_PEQ_ID	155
#define BRAP_IMG_PEQ_TABLE_ID	156
#define BRAP_IMG_PEQ_INTERFRAME_ID	157


/*DTSHD Sub Audio algorithm*/
#define BRAP_IMG_DTSHD_SUB_TABLE_ID	158
#define BRAP_IMG_DTSHD_SUB_INTERFRAME_ID	159
#define BRAP_IMG_DTSHD_SUB_FRAMESYNC_ID	160
#define BRAP_IMG_DTSHD_SUB_0_DECODE_ID     	161
#define BRAP_IMG_DTSHD_SUB_1_DECODE_ID     	162

/*DVD_A_LPCm Algorithm */
#define BRAP_IMG_DVD_A_LPCM_INTERFRAME_ID	163
#define BRAP_IMG_DVD_A_LPCM_FRAMESYNC_ID	164
#define BRAP_IMG_DVD_A_LPCM_DECODE_ID     	165

#define BRAP_IMG_DTSHD_NBC_CORE_FRAMESYNC_ID    166

/* AAC V2 Executables */
#define BRAP_IMG_AACHE_DECODE_STG0_ID	167
#define BRAP_IMG_AACHE_DECODE_STG1_ID	168
#define BRAP_IMG_AACHE_DECODE_STG2_ID	169
#define BRAP_IMG_AACHE_DECODE_STG3_ID	170
#define BRAP_IMG_AACHE_DECODE_STG4_ID	171

#define BRAP_IMG_AACHE_TABLE_STG0_ID		172
#define BRAP_IMG_AACHE_TABLE_STG1_ID		173
#define BRAP_IMG_AACHE_TABLE_STG2_ID		174
#define BRAP_IMG_AACHE_TABLE_STG3_ID		175
#define BRAP_IMG_AACHE_TABLE_STG4_ID		176

/* DTS HD MA STG1 Frame Sync */
#define BRAP_IMG_DTSHD_STG1_FRAMESYNC_ID        177
#define BRAP_IMG_DTSHD_STG1_DECODE_TABLE_ID     178
#define BRAP_IMG_DTSHD_STG1_INTERFRAME_ID       179

#define BRAP_IMG_SCHEDULER_DNLD_CODE_ID         180
#define BRAP_IMG_SCHEDULER_DSP1_DNLD_CODE_ID    181

#define BRAP_IMG_AACHE_DECODE_TABLE_STG0_ID     182
#define BRAP_IMG_AACHE_DECODE_TABLE_STG1_ID     183
#define BRAP_IMG_AACHE_DECODE_TABLE_STG2_ID     184
#define BRAP_IMG_AACHE_DECODE_TABLE_STG3_ID     185
#define BRAP_IMG_AACHE_DECODE_TABLE_STG4_ID     186


#define BRAP_IMG_AD_FADECTRL_ID 187
#define BRAP_IMG_AD_FADECTRL_TABLE_ID 188
#define BRAP_IMG_AD_FADECTRL_INTERFRAME_ID 189

#define BRAP_IMG_AD_PANCTRL_ID 190
#define BRAP_IMG_AD_PANCTRL_TABLE_ID 191
#define BRAP_IMG_AD_PANCTRL_INTERFRAME_ID 192

#define BRAP_IMG_DRA_PASSTHRU_ID			193
#define BRAP_IMG_DRA_FRAMESYNC_ID		194
#define BRAP_IMG_DRA_INTERFRAME_ID 		195

#define BRAP_IMG_DOLBYVOLUME_ID 196
#define BRAP_IMG_DOLBYVOLUME_TABLE_ID 197
#define BRAP_IMG_DOLBYVOLUME_INTERFRAME_ID 198

#define BRAP_IMG_SRSTRUVOL_ID 199
#define BRAP_IMG_SRSTRUVOL_TABLE_ID 200
#define BRAP_IMG_SRSTRUVOL_INTERFRAME_ID 201

#define BRAP_IMG_PCM_PASSTTHRU_ID 202
#define BRAP_IMG_PCM_PASSTTHRU_FRAMESYNC_ID 203

#define BRAP_IMG_DRA_ID 204
#define BRAP_IMG_DRA_TABLE_ID 205

#define BRAP_IMG_PCMWAV_ID 206
#define BRAP_IMG_PCMWAV_FRAMESYNC_ID 207
#define BRAP_IMG_PCMWAV_INTERFRAME_ID		208

/* 
	This chunk size will be used when the firmware binary is actually present in multiple chunks.
	The BRAP_IMG_CHUNK_SIZE will then give the size of each such chunk
*/
#define BRAP_IMG_CHUNK_SIZE	65532


extern void *BRAP_IMG_Context;
extern const BIMG_Interface BRAP_IMG_Interface;

#endif /* BRAP_IMG_H__ */


