/***************************************************************************
 *     Copyright (c) 2003-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/
/* this file should not be directly included, and it could be included multiple times  */
BCHP_P_MEMC_DEFINE_HWBLOCK(3D)
BCHP_P_MEMC_DEFINE_HWBLOCK(AUD)
BCHP_P_MEMC_DEFINE_HWBLOCK(AVD)
BCHP_P_MEMC_DEFINE_HWBLOCK(BSP)
BCHP_P_MEMC_DEFINE_HWBLOCK(BVN)
BCHP_P_MEMC_DEFINE_HWBLOCK(CPU)
BCHP_P_MEMC_DEFINE_HWBLOCK(DOCSIS)
BCHP_P_MEMC_DEFINE_HWBLOCK(EBI)
BCHP_P_MEMC_DEFINE_HWBLOCK(ETHERNET)
BCHP_P_MEMC_DEFINE_HWBLOCK(FLASH)
BCHP_P_MEMC_DEFINE_HWBLOCK(FRONTEND)
BCHP_P_MEMC_DEFINE_HWBLOCK(GFAP)
BCHP_P_MEMC_DEFINE_HWBLOCK(IEEE_1394)
BCHP_P_MEMC_DEFINE_HWBLOCK(M2M)
BCHP_P_MEMC_DEFINE_HWBLOCK(M2MC)
BCHP_P_MEMC_DEFINE_HWBLOCK(MCARD)
BCHP_P_MEMC_DEFINE_HWBLOCK(MCP)
BCHP_P_MEMC_DEFINE_HWBLOCK(MEMC)
BCHP_P_MEMC_DEFINE_HWBLOCK(MOCA)
BCHP_P_MEMC_DEFINE_HWBLOCK(MSA)
BCHP_P_MEMC_DEFINE_HWBLOCK(PCI)
BCHP_P_MEMC_DEFINE_HWBLOCK(PREFETCH)
BCHP_P_MEMC_DEFINE_HWBLOCK(RESERVED)
BCHP_P_MEMC_DEFINE_HWBLOCK(SATA)
BCHP_P_MEMC_DEFINE_HWBLOCK(SCPU)
BCHP_P_MEMC_DEFINE_HWBLOCK(SDIO)
BCHP_P_MEMC_DEFINE_HWBLOCK(SID)
BCHP_P_MEMC_DEFINE_HWBLOCK(T2_TDI)
BCHP_P_MEMC_DEFINE_HWBLOCK(TPCAP)
BCHP_P_MEMC_DEFINE_HWBLOCK(TRACE)
BCHP_P_MEMC_DEFINE_HWBLOCK(UART)
BCHP_P_MEMC_DEFINE_HWBLOCK(UBUS)
BCHP_P_MEMC_DEFINE_HWBLOCK(USB)
BCHP_P_MEMC_DEFINE_HWBLOCK(VEC)
BCHP_P_MEMC_DEFINE_HWBLOCK(VEC_VBI)
BCHP_P_MEMC_DEFINE_HWBLOCK(VICE)
BCHP_P_MEMC_DEFINE_HWBLOCK(WIFI)
BCHP_P_MEMC_DEFINE_HWBLOCK(XPT)
