/***************************************************************************
 *     Copyright (c) 2003-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/
/* this file should not be directly included, and it could be included multiple times  */
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_0,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_1,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_2,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_3,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_4,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_5,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_6,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(SCL_7,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_0,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_1,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_2,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_3,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_4,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_5,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CMP_6,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_0,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_1,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_2,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_3,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_4,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MFD_5,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MVP_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_1,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_2,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_3,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_4,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(MAD_5,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_0,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_1,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_2,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_3,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_4,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_5,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_6,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(CAP_7,WO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_0,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_1,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_2,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_3,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_4,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_5,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_6,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VFD_7,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_0,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_1,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_2,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_3,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_4,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_5,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFD_6,RO)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFX_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFX_1,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(GFX_2,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VIP_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VIP_1,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(VIP_2,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(V3D_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(V3D_1,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(HVD_0,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(HVD_1,RW)
BCHP_P_MEMC_DEFINE_SVP_HWBLOCK(HVD_2,RW)
