#!/usr/bin/env python2.7

"""
Compare build_config.sh with "hnd enabled" per tag.

Example:

  config-diff -t DINGO_BRANCH_9_10

"""

from __future__ import print_function
from __future__ import unicode_literals

# Imported first to fix up sys.path etc.
import preface

import argparse
import os
import subprocess
import sys

BUILD_CONFIG = '/projects/hnd/software/gallery/src/tools/build/build_config.sh'


def main(argv):
    """Compare build_config.sh with "hnd enabled" per tag."""

    parser = argparse.ArgumentParser(
        epilog=__doc__.strip(),
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        '-b', '--build-config', default=BUILD_CONFIG,
        help="path to version of build_config.sh")
    parser.add_argument(
        '-t', '--tag', default='trunk',
        help="tag to compare (default=%(default)s")
    opts = parser.parse_args(argv[1:])

    oldfile = '/tmp/%s.old.tmp' % opts.tag
    cmd = r"%s -r %s | sed 's@^[ \t]*@@' | grep '^[a-z]' | sort >%s" %\
          (opts.build_config, opts.tag, oldfile)
    subprocess.check_call(cmd, shell=True)

    newfile = '/tmp/%s.new.tmp' % opts.tag
    cmd = r"hnd query -t %s enabled > %s" % (opts.tag, newfile)
    subprocess.check_call(cmd, shell=True)

    cmd = 'set -x; diff %s %s' % (oldfile, newfile)
    subprocess.call(cmd, shell=True)

    os.unlink(oldfile)
    os.unlink(newfile)


if __name__ == '__main__':
    main(sys.argv)

# vim: ts=8:sw=4:tw=80:et:
