################################################################################
#  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
################################################################################

SOURCES := \
	pg.cpp									\
	pg_panel.cpp							\
	pg_controller.cpp						\
	pg_channel_node.cpp					\
	pg_dummyData.cpp						\
	pg_info.cpp								\
	pg_interval_node.cpp					\
	pg_region.cpp							\
	pg_timebar_node.cpp					\
	pg_channelbar_node.cpp				\
	pg_longscrolling.cpp					\
	pg_mycallbackmodelviewmatrix.cpp	\
	pg_gui_display.cpp

TARGET := pg
