/******************************************************************************
 * Copyright (C) 2018 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *****************************************************************************/

#include "bmon_convert.h"

STRING_MAP_START(audioCodecNameMap)
STRING_MAP_ENTRY(NEXUS_AudioCodec_eUnknown, "unknown")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eMpeg, "mpeg")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eMp3, "mp3")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAac, "aac")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAacLoas, "loas")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAacPlus, "aacplus")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAacPlusAdts, "aacplusadts")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAc3, "ac3")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAc3Plus, "ac3plus")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eDts, "dts")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eLpcmDvd, "lpcmdvd")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eLpcmHdDvd, "lpcmhddvd")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eLpcmBluRay, "lpcmbluray")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eDtsHd, "dtshd")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eWmaStd, "wmastd")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eWmaStdTs, "wmastdts")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eWmaPro, "wmapro")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAvs, "avs")
STRING_MAP_ENTRY(NEXUS_AudioCodec_ePcm, "pcm")
STRING_MAP_ENTRY(NEXUS_AudioCodec_ePcmWav, "pcmwav")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAmrNb, "amr")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAmrWb, "amrwb")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eDra, "dra")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eCook, "cook")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAdpcm, "adpcm")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eSbc, "sbc")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eDtsCd, "dtscd")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eDtsExpress, "dtsexpress")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eVorbis, "vorbis")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eLpcm1394, "lpcm1394")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eG711, "g711")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eG723_1, "g723_1")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eG726, "g726")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eG729, "g729")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eFlac, "flac")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eMlp, "mlp")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eApe, "ape")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eIlbc, "ilbc")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eIsac, "isac")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eOpus, "opus")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAls, "als")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAlsLoas, "alsloas")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eAc4, "ac4")
STRING_MAP_ENTRY(NEXUS_AudioCodec_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(audioCodecToString, NEXUS_AudioCodec, audioCodecNameMap)
STRING_TO_ENUM_FUNCTION(stringToAudioCodec, NEXUS_AudioCodec, audioCodecNameMap)

STRING_MAP_START(videoCodecNameMap)
STRING_MAP_ENTRY(NEXUS_VideoCodec_eUnknown, "unknown")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eMpeg1, "mpeg1")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eMpeg2, "mpeg2")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eMpeg4Part2, "mpeg4part2")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eH263, "h263")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eH264, "h264")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eH264_Svc, "h264_svc")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eH264_Mvc, "h264_mvc")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVc1, "vc1")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVc1SimpleMain, "vc1simplemain")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eDivx311, "divx311")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eAvs, "avs")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eRv40, "rv40")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVp6, "vp6")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVp7, "vp7")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVp8, "vp8")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eVp9, "vp9")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eSpark, "spark")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eMotionJpeg, "motionjpeg")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eH265, "h265")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eAvs2, "avs2")
STRING_MAP_ENTRY(NEXUS_VideoCodec_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(videoCodecToString, NEXUS_VideoCodec, videoCodecNameMap)
STRING_TO_ENUM_FUNCTION(stringToVideoCodec, NEXUS_VideoCodec, videoCodecNameMap)

STRING_MAP_START(videoFormatNameMap)
STRING_MAP_ENTRY(NEXUS_VideoFormat_eUnknown, "Unknown")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eNtsc, "NTSC")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eNtsc443, "NTSC 443")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eNtscJapan, "NTSC Japan")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalM, "Pal-M")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalN, "Pal-N")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalNc, "Pal-Nc")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalB, "Pal-B")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalB1, "Pal-B1")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalD, "Pal-D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalD1, "Pal-D1")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalDK2, "Pal-DK2")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalDK3, "Pal-DK3")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalG, "Pal-G")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalH, "Pal-H")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalK, "Pal-K")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePalI, "Pal-I")
STRING_MAP_ENTRY(NEXUS_VideoFormat_ePal60hz, "Pal 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamL, "Secam L")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamB, "Secam B")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamG, "Secam G")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamD, "Secam D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamK, "Secam K")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eSecamH, "Secam H")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e480p, "480p")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e576p, "576p")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080i, "1080i")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080i50hz, "1080i 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p24hz, "1080p 24Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p25hz, "1080p 25Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p30hz, "1080p 30Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p50hz, "1080p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p60hz, "1080p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p100hz, "1080p 100Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p120hz, "1080p 120Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1250i50hz, "1250i 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p, "720p")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p50hz, "720p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p24hz, "720p 24Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p25hz, "720p 25Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p30hz, "720p 30Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e240p60hz, "240p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e288p50hz, "288p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1440x480p60hz, "1440x480p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1440x576p50hz, "1440x576p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e3840x2160p24hz, "2160p 24Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e3840x2160p25hz, "2160p 25Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e3840x2160p30hz, "2160p 30Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e3840x2160p50hz, "2160p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e3840x2160p60hz, "2160p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e4096x2160p24hz, "4096x2160p 24Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e4096x2160p25hz, "4096x2160p 25Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e4096x2160p30hz, "4096x2160p 30Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e4096x2160p50hz, "4096x2160p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e4096x2160p60hz, "4096x2160p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustomer1440x240p60hz, "1440x240p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustomer1440x288p50hz, "1440x288p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustomer1366x768p60hz, "1366x768p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustomer1366x768p50hz, "1366x768p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p60hz, "Vesa 640x480p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p60hz, "Vesa 800x600p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p60hz, "Vesa 1024x768p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x768p60hz, "Vesa 1280x768p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x768p60hzRed, "Vesa 1280x768p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p50hz, "Vesa 1280x720p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p60hz, "Vesa 1280x720p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720pReducedBlank, "Vesa 1280x720p Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x350p60hz, "Vesa 640x350p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x350p70hz, "Vesa 640x350p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x350p72hz, "Vesa 640x350p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x350p75hz, "Vesa 640x350p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x350p85hz, "Vesa 640x350p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x400p60hz, "Vesa 640x400p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x400p70hz, "Vesa 640x400p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x400p72hz, "Vesa 640x400p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x400p75hz, "Vesa 640x400p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x400p85hz, "Vesa 640x400p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p66hz, "Vesa 640x480p 66Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p70hz, "Vesa 640x480p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p72hz, "Vesa 640x480p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p75hz, "Vesa 640x480p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa640x480p85hz, "Vesa 640x480p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa720x400p60hz, "Vesa 720x400p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa720x400p70hz, "Vesa 720x400p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa720x400p72hz, "Vesa 720x400p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa720x400p75hz, "Vesa 720x400p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa720x400p85hz, "Vesa 720x400p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p56hz, "Vesa 800x600p 56Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p59hzRed, "Vesa 800x600p 59Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p70hz, "Vesa 800x600p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p72hz, "Vesa 800x600p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p75hz, "Vesa 800x600p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p85hz, "Vesa 800x600p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa848x480p60hz, "Vesa 848x480p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p66hz, "Vesa 1024x768p 66Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p70hz, "Vesa 1024x768p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p72hz, "Vesa 1024x768p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p75hz, "Vesa 1024x768p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768p85hz, "Vesa 1024x768p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1064x600p60hz, "Vesa 1064x600p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p70hz, "Vesa 1280x720p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p72hz, "Vesa 1280x720p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p75hz, "Vesa 1280x720p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x720p85hz, "Vesa 1280x720p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1024x768i87hz, "Vesa 1024x768i 87Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x864p75hz, "Vesa 1152x864p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x768p75hz, "Vesa 1280x768p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x768p85hz, "Vesa 1280x768p 85hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x800p_60Hz, "Vesa 1280x800p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x960p60hz, "Vesa 1280x960p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x960p85hz, "Vesa 1280x960p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p60hz, "Vesa 1280x1024p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p69hz, "Vesa 1280x1024p 69Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p75hz, "Vesa 1280x1024p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p85hz, "Vesa 1280x1024p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa832x624p75hz, "Vesa 832x624p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1360x768p60hz, "Vesa 1360x768p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1366x768p60hz, "Vesa 1366x768p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1400x1050p60hz, "Vesa 1400x1050p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1400x1050p60hzReducedBlank, "Vesa 1400x1050p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1400x1050p75hz, "Vesa 1400x1050p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1440x900p60hz, "Vesa 1440x900p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1600x1200p60hz, "Vesa 1600x1200p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1920x1080p60hzReducedBlank, "Vesa 1920x1080p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p_3DOU_AS, "720p 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p50hz_3DOU_AS, "720p 50Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p30hz_3DOU_AS, "720p 30Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720p24hz_3DOU_AS, "720p 24Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p24hz_3DOU_AS, "1080p 24Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e1080p30hz_3DOU_AS, "1080p 30Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1680x1050p_60Hz, "Vesa 1680x1050p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x800p_60Hz_Red, "Vesa 1280x800p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1600x1200p_75Hz, "Vesa 1600x1200p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1600x900p_60Hz_Red, "Vesa 1600x900p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1680x1050p_60Hz_Red, "Vesa 1680x1050p 60hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1920x1200p_60Hz, "Vesa 1920x1200p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1920x1200p_60Hz_Red, "Vesa 1920x1200p 60Hz Red")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x720p_60Hz, "Vesa 1152x720p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x720p_75Hz, "Vesa 1152x720p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x720p_85Hz, "Vesa 1152x720p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x864p_60Hz, "Vesa 1152x720p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x864p_85Hz, "Vesa 1152x720p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x870p_75Hz, "Vesa 1152x720p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x900p_66Hz, "Vesa 1152x720p 66Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1152x900p_76Hz, "Vesa 1152x720p 76Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1170x584p_50Hz, "Vesa 1170x584p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p_70Hz, "Vesa 1280x1024p 70Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p_72Hz, "Vesa 1280x1024p 72Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x1024p_76Hz, "Vesa 1280x1024p 76Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x768p_50Hz, "Vesa 1280x768p 50Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1280x960p_75Hz, "Vesa 1280x960p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1600x1024p_60Hz, "Vesa 1600x1024p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1600x1024p_76Hz, "Vesa 1600x1024p 76Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa1728x1080p_60Hz, "Vesa 1728x1080p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p_100Hz, "Vesa 800x600p 100Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa800x600p_90Hz, "Vesa 800x600p 90Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa848x480p_75Hz, "Vesa 848x480p 75Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa848x480p_85Hz, "Vesa 848x480p 85Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eVesa852x480p_60Hz, "Vesa 852x480p 60Hz")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720x482_NTSC, "720x482 NTSC")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720x482_NTSC_J, "720x482 NTSC J")
STRING_MAP_ENTRY(NEXUS_VideoFormat_e720x483p, "720x483p")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom0, "Custom 0")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom1, "Custom 1")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom2, "Custom 2")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom1920x2160i_48Hz, "Custom 1920x2160i 48Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_720p, "Custom 720p 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_720p_50hz, "Custom 720p 50Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_720p_30hz, "Custom 720p 30Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_720p_24hz, "Custom 720p 24Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_1080p_24hz, "Custom 1080p 24Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eCustom_3D_1080p_30hz, "Custom 1080p 30Hz 3D")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eMax, "Invalid")
STRING_MAP_ENTRY(NEXUS_VideoFormat_eMax, "0")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(videoFormatToString, NEXUS_VideoFormat, videoFormatNameMap)
STRING_TO_ENUM_FUNCTION(stringToVideoFormat, NEXUS_VideoFormat, videoFormatNameMap)

STRING_MAP_START(aspectRatioNameMap)
STRING_MAP_ENTRY(NEXUS_AspectRatio_eUnknown, "Unknown")
STRING_MAP_ENTRY(NEXUS_AspectRatio_eSquarePixel, "Square")
STRING_MAP_ENTRY(NEXUS_AspectRatio_e4x3, "4x3")
STRING_MAP_ENTRY(NEXUS_AspectRatio_e16x9, "16x9")
STRING_MAP_ENTRY(NEXUS_AspectRatio_e221x1, "2.21x1")
STRING_MAP_ENTRY(NEXUS_AspectRatio_e15x9, "15x9")
STRING_MAP_ENTRY(NEXUS_AspectRatio_eSar, "SAR")
STRING_MAP_ENTRY(NEXUS_AspectRatio_eMax, "Invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(aspectRatioToString, NEXUS_AspectRatio, aspectRatioNameMap)
STRING_TO_ENUM_FUNCTION(stringToAspectRatio, NEXUS_AspectRatio, aspectRatioNameMap)

STRING_MAP_START(colorSpaceNameMap)
STRING_MAP_ENTRY(NEXUS_ColorSpace_eAuto, "Auto")
STRING_MAP_ENTRY(NEXUS_ColorSpace_eRgb, "RGB")
STRING_MAP_ENTRY(NEXUS_ColorSpace_eYCbCr422, "4:2:2")
STRING_MAP_ENTRY(NEXUS_ColorSpace_eYCbCr444, "4:4:4")
STRING_MAP_ENTRY(NEXUS_ColorSpace_eYCbCr420, "4:2:0")
STRING_MAP_ENTRY(NEXUS_ColorSpace_eMax, "Invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(colorSpaceToString, NEXUS_ColorSpace, colorSpaceNameMap)
STRING_TO_ENUM_FUNCTION(stringToColorSpace, NEXUS_ColorSpace, colorSpaceNameMap)

STRING_MAP_START(edidColorimetryDbNameMap)
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_exvYCC601, "xvYCC601")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_exvYCC709, "xvYCC709")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_esYCC601, "sYCC601")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eAdobeYCC601, "AdobeYCC601")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eAdobeRGB, "AdobeRgb")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eBT2020cYCC, "BT2020cYCC")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eBT2020YCC, "BT2020YCC")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eBT2020RGB, "BT2020RGB")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbSupport_eMax, "Invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(edidColorimetryDbToString, NEXUS_HdmiEdidColorimetryDbSupport, edidColorimetryDbNameMap)
STRING_TO_ENUM_FUNCTION(stringToEdidColorimetryDb, NEXUS_HdmiEdidColorimetryDbSupport, edidColorimetryDbNameMap)

STRING_MAP_START(edidColorimetryDbMetadataProfileNameMap)
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbMetadataProfile_e0, "e0")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbMetadataProfile_e1, "e1")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbMetadataProfile_e2, "e2")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbMetadataProfile_e3, "e3")
STRING_MAP_ENTRY(NEXUS_HdmiEdidColorimetryDbMetadataProfile_eMax, "Invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(edidColorimetryDbMetadataProfileToString, NEXUS_HdmiEdidColorimetryDbMetadataProfile, edidColorimetryDbMetadataProfileNameMap)
STRING_TO_ENUM_FUNCTION(stringToEdidColorimetryDbMetadataProfile, NEXUS_HdmiEdidColorimetryDbMetadataProfile, edidColorimetryDbMetadataProfileNameMap)

STRING_MAP_START(eotfNameMap)
STRING_MAP_ENTRY(NEXUS_VideoEotf_eSdr, "sdr")
STRING_MAP_ENTRY(NEXUS_VideoEotf_eAribStdB67, "aribStdB67")
STRING_MAP_ENTRY(NEXUS_VideoEotf_eSmpteSt2084, "smpteSt2084")
STRING_MAP_ENTRY(NEXUS_VideoEotf_eInvalid, "invalid")
STRING_MAP_ENTRY(NEXUS_VideoEotf_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(eotfToString, NEXUS_VideoEotf, eotfNameMap)
STRING_TO_ENUM_FUNCTION(stringToEotf, NEXUS_VideoEotf, eotfNameMap)

STRING_MAP_START(videoFrameRateNameMap)
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_eUnknown, "0")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e23_976, "23.976")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e24, "24")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e25, "25")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e29_97, "29.97")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e30, "30")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e50, "50")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e59_94, "59.94")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e60, "60")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e14_985, "14.985")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e7_493, "7.493")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e10, "10")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e15, "15")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_e20, "20")
STRING_MAP_ENTRY(NEXUS_VideoFrameRate_eMax, "0")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(videoFrameRateToString, NEXUS_VideoFrameRate, videoFrameRateNameMap)
STRING_TO_ENUM_FUNCTION(stringToVideoFrameRate, NEXUS_VideoFrameRate, videoFrameRateNameMap)

STRING_MAP_START(videoProtocolLevelNameMap)
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eUnknown, "unknown")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e00, "00")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e10, "10")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e1B, "1B")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e11, "11")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e12, "12")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e13, "13")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e20, "20")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e21, "21")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e22, "22")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e30, "30")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e31, "31")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e32, "32")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e40, "40")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e41, "41")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e42, "42")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e50, "50")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e51, "51")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e60, "60")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e62, "62")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eLow, "low")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eMain, "main")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eHigh, "high")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eHigh1440, "high1440")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eL0, "L0")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eL1, "L1")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eL2, "L2")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eL3, "L3")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e80, "80")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_e52, "52")
STRING_MAP_ENTRY(NEXUS_VideoProtocolLevel_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(videoProtocolLevelToString, NEXUS_VideoProtocolLevel, videoProtocolLevelNameMap)
STRING_TO_ENUM_FUNCTION(stringToVideoProtocolLevel, NEXUS_VideoProtocolLevel, videoProtocolLevelNameMap)

STRING_MAP_START(videoProtocolProfileNameMap)
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eUnknown, "unknown")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eSimple, "simple")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eMain, "main")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eHigh, "high")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eAdvanced, "advanced")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eJizhun, "jizhun")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eSnrScalable, "snrScalable")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eSpatiallyScalable, "spatiallyScalable")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eAdvancedSimple, "advancedSimple")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eBaseline, "baseline")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eMultiHigh, "multiHigh")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eStereoHigh, "stereoHigh")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eMain10, "main10")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_e0, "e0")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_e2, "e2")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eGuango, "guango")
STRING_MAP_ENTRY(NEXUS_VideoProtocolProfile_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(videoProtocolProfileToString, NEXUS_VideoProtocolProfile, videoProtocolProfileNameMap)
STRING_TO_ENUM_FUNCTION(stringToVideoProtocolProfile, NEXUS_VideoProtocolProfile, videoProtocolProfileNameMap)

STRING_MAP_START(pictureCodingNameMap)
STRING_MAP_ENTRY(NEXUS_PictureCoding_eUnknown, "unknown")
STRING_MAP_ENTRY(NEXUS_PictureCoding_eI, "I")
STRING_MAP_ENTRY(NEXUS_PictureCoding_eP, "P")
STRING_MAP_ENTRY(NEXUS_PictureCoding_eB, "B")
STRING_MAP_ENTRY(NEXUS_PictureCoding_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(pictureCodingToString, NEXUS_PictureCoding, pictureCodingNameMap)
STRING_TO_ENUM_FUNCTION(stringToPictureCoding, NEXUS_PictureCoding, pictureCodingNameMap)

STRING_MAP_START(ptsTypeNameMap)
STRING_MAP_ENTRY(NEXUS_PtsType_eCoded, "unknown")
STRING_MAP_ENTRY(NEXUS_PtsType_eInterpolatedFromValidPTS, "interpolatedFromValidPTS")
STRING_MAP_ENTRY(NEXUS_PtsType_eHostProgrammedPTS, "hostProgrammed")
STRING_MAP_ENTRY(NEXUS_PtsType_eInterpolatedFromInvalidPTS, "interpolatedFromInvalidPTS")
STRING_MAP_ENTRY(NEXUS_PtsType_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(ptsTypeToString, NEXUS_PtsType, ptsTypeNameMap)
STRING_TO_ENUM_FUNCTION(stringToPtsType, NEXUS_PtsType, ptsTypeNameMap)

STRING_MAP_START(irInputModeNameMap)
STRING_MAP_ENTRY(NEXUS_IrInputMode_eTwirpKbd, "twirpKeyboard")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eSejin38KhzKbd, "sejinIrKeyboard_38.4KHz")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eSejin56KhzKbd, "sejinIrKeyboard_56.0KHz")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eRemoteA, "remoteA")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eRemoteB, "remoteB")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirGI, "gi")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirSaE2050, "sa_e2050")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirTwirp, "twirp")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirSony, "sony")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRecs80, "rec580")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRc5, "rc5")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirUei, "uei")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRfUei, "rf_uei")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirEchoStar, "echostarRemote")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eSonySejin, "sonySejinKeyboardUartD")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirNec, "nec")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRC6, "rc6")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirGISat, "giSatellite")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCustom, "custom")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirDirectvUhfr, "directvUhfrIr")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirEchostarUhfr, "echostarUhfrIr")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRcmmRcu, "rcmmRemote")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRstep, "rStep")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirXmp, "xmp2")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirXmp2Ack, "xmp2Ack")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRC6Mode0, "rc6Mode0")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirRca, "rca")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirToshibaTC9012, "toshiba")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eCirXip, "tech4HomeXip")
STRING_MAP_ENTRY(NEXUS_IrInputMode_eMax, "invalid")
STRING_MAP_END()

ENUM_TO_STRING_FUNCTION(irInputModeToString, NEXUS_IrInputMode, irInputModeNameMap)
STRING_TO_ENUM_FUNCTION(stringToIrInputMode, NEXUS_IrInputMode, irInputModeNameMap)