/******************************************************************************
 * Copyright (C) 2017 Broadcom.  The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/

#include <arch.h>
#include <arch_helpers.h>

#include "monitor.h"
#include "delay.h"
#include "platform_power.h"
#include "brcmstb_params.h"
#include "brcmstb_priv.h"

/***************************************************************************
 *HIF_CPUBIUCTRL - CPU BIU Control registers
 ***************************************************************************/
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG 0x000000c4 /* [RW][32] CPU0 Power Zone Control Register */
#define BCHP_HIF_CPUBIUCTRL_CPU1_PWR_ZONE_CNTRL_REG 0x000000c8 /* [RW][32] CPU1 Power Zone Control Register */

#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_STRIDE \
    (BCHP_HIF_CPUBIUCTRL_CPU1_PWR_ZONE_CNTRL_REG - \
     BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG)

#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG 0x0000008c /* [RW][32] CPU Reset Configuration Register */

/***************************************************************************
 *CPU0_PWR_ZONE_CNTRL_REG - CPU0 Power Zone Control Register
 ***************************************************************************/
/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_RESET_STATE [31:31] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_RESET_STATE_MASK 0x80000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_RESET_STATE_SHIFT 31

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_ISO_STATE [30:30] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_ISO_STATE_MASK 0x40000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_ISO_STATE_SHIFT 30

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MEM_PWR_STATE [29:29] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_PWR_STATE_MASK 0x20000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_PWR_STATE_SHIFT 29

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_DPG_PWR_STATE [28:28] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_PWR_STATE_MASK 0x10000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_PWR_STATE_SHIFT 28

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_POWER_GOOD [27:27] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_POWER_GOOD_MASK 0x08000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_POWER_GOOD_SHIFT 27

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_PWR_ON_STATE [26:26] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_ON_STATE_MASK 0x04000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_ON_STATE_SHIFT 26

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_PWR_OFF_STATE [25:25] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_OFF_STATE_MASK 0x02000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_OFF_STATE_SHIFT 25

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: FREQ_SCALAR_DYNAMIC_SEL [24:24] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_FREQ_SCALAR_DYNAMIC_SEL_MASK 0x01000000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_FREQ_SCALAR_DYNAMIC_SEL_SHIFT 24

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_PWR_CNTL_STATE [23:19] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_CNTL_STATE_MASK 0x00f80000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_CNTL_STATE_SHIFT 19

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: reserved0 [18:14] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_reserved0_MASK 0x0007c000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_reserved0_SHIFT 14

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MEM_STBY [13:13] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_STBY_MASK 0x00002000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_STBY_SHIFT 13

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_BLK_RST_ASSERT [12:12] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_BLK_RST_ASSERT_MASK 0x00001000
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_BLK_RST_ASSERT_SHIFT 12
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_BLK_RST_ASSERT_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MEM_PWR_CNTL_EN [11:11] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_PWR_CNTL_EN_MASK 0x00000800
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_PWR_CNTL_EN_SHIFT 11
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MEM_PWR_CNTL_EN_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_PWR_UP_REQ [10:10] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_UP_REQ_MASK 0x00000400
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_UP_REQ_SHIFT 10
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_UP_REQ_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_PWR_DN_REQ [09:09] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_DN_REQ_MASK 0x00000200
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_DN_REQ_SHIFT 9
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_PWR_DN_REQ_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_DPG_CNTL_EN [08:08] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CNTL_EN_MASK 0x00000100
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CNTL_EN_SHIFT 8
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CNTL_EN_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MANUAL_CONTROL [07:07] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MANUAL_CONTROL_MASK 0x00000080
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MANUAL_CONTROL_SHIFT 7
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MANUAL_CONTROL_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MAN_ISO_CNTL [06:06] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_ISO_CNTL_MASK 0x00000040
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_ISO_CNTL_SHIFT 6
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_ISO_CNTL_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: reserved1 [05:05] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_reserved1_MASK 0x00000020
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_reserved1_SHIFT 5

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MAN_MEM_PWR [04:04] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_MEM_PWR_MASK 0x00000010
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_MEM_PWR_SHIFT 4
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_MEM_PWR_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_DPG_CAPABLE [03:03] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CAPABLE_MASK 0x00000008
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CAPABLE_SHIFT 3
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_DPG_CAPABLE_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_FREQ_SCALE_USED [02:02] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_FREQ_SCALE_USED_MASK 0x00000004
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_FREQ_SCALE_USED_SHIFT 2

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MAN_RESET_CNTL [01:01] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_RESET_CNTL_MASK 0x00000002
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_RESET_CNTL_SHIFT 1
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_RESET_CNTL_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU0_PWR_ZONE_CNTRL_REG :: ZONE_MAN_CLKEN [00:00] */
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_CLKEN_MASK 0x00000001
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_CLKEN_SHIFT 0
#define BCHP_HIF_CPUBIUCTRL_CPU0_PWR_ZONE_CNTRL_REG_ZONE_MAN_CLKEN_DEFAULT 0x00000000

/***************************************************************************
 *CPU_RESET_CONFIG_REG - CPU Reset Configuration Register
 ***************************************************************************/
/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: reserved0 [31:10] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_reserved0_MASK    0xfffffc00
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_reserved0_SHIFT   10

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CL1L2_RESET [09:09] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL1L2_RESET_MASK  0x00000200
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL1L2_RESET_SHIFT 9
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL1L2_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CL0L2_RESET [08:08] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL0L2_RESET_MASK  0x00000100
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL0L2_RESET_SHIFT 8
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CL0L2_RESET_DEFAULT 0x00000000

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU7_RESET [07:07] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU7_RESET_MASK   0x00000080
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU7_RESET_SHIFT  7
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU7_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU6_RESET [06:06] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU6_RESET_MASK   0x00000040
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU6_RESET_SHIFT  6
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU6_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU5_RESET [05:05] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU5_RESET_MASK   0x00000020
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU5_RESET_SHIFT  5
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU5_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU4_RESET [04:04] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU4_RESET_MASK   0x00000010
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU4_RESET_SHIFT  4
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU4_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU3_RESET [03:03] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU3_RESET_MASK   0x00000008
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU3_RESET_SHIFT  3
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU3_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU2_RESET [02:02] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU2_RESET_MASK   0x00000004
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU2_RESET_SHIFT  2
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU2_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU1_RESET [01:01] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU1_RESET_MASK   0x00000002
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU1_RESET_SHIFT  1
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU1_RESET_DEFAULT 0x00000001

/* HIF_CPUBIUCTRL :: CPU_RESET_CONFIG_REG :: CPU0_RESET [00:00] */
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU0_RESET_MASK   0x00000001
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU0_RESET_SHIFT  0
#define BCHP_HIF_CPUBIUCTRL_CPU_RESET_CONFIG_REG_CPU0_RESET_DEFAULT 0x00000000

/***************************************************************************
 *HIF_CONTINUATION - HIF Boot Continuation Registers
 ***************************************************************************/
#define BCHP_HIF_CONTINUATION_STB_BOOT_HI_ADDR0  0x00000000 /* [RO][32] Higher 8-bit of HIF's Read-only STB Boot Continuation Address 0 Register */
#define BCHP_HIF_CONTINUATION_STB_BOOT_ADDR0     0x00000004 /* [RO][32] Lower 32-bit of HIF's Read-only STB Boot Continuation Address 0 Register */
#define BCHP_HIF_CONTINUATION_STB_BOOT_HI_ADDR1  0x00000008 /* [RW][32] Higher 8-bit of HIF's STB Boot Continuation Address 1 Register */
#define BCHP_HIF_CONTINUATION_STB_BOOT_ADDR1     0x0000000c /* [RW][32] Lower 32-bit of HIF's STB Boot Continuation Address 1 Register */

#define BCHP_HIF_CONTINUATION_STB_BOOT_HI_ADDR0_STRIDE \
    (BCHP_HIF_CONTINUATION_STB_BOOT_HI_ADDR1 - \
     BCHP_HIF_CONTINUATION_STB_BOOT_HI_ADDR0)

/***************************************************************************
 *SUN_TOP_CTRL - Top Control registers
 ***************************************************************************/
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE    0x00000304 /* [RW][32] Reset source enable */
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET        0x00000308 /* [RW][32] Software master reset */

/***************************************************************************
 *RESET_SOURCE_ENABLE - Reset source enable
 ***************************************************************************/
/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: reserved0 [31:10] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_reserved0_MASK       0xfffffc00
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_reserved0_SHIFT      10

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_level_reset_1_en_lock [09:09] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_en_lock_MASK 0x00000200
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_en_lock_SHIFT 9
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_en_lock_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_level_reset_1_enable [08:08] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_enable_MASK 0x00000100
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_enable_SHIFT 8
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_1_enable_DEFAULT 0x00000001

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_level_reset_0_en_lock [07:07] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_en_lock_MASK 0x00000080
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_en_lock_SHIFT 7
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_en_lock_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_level_reset_0_enable [06:06] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_enable_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_enable_SHIFT 6
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_level_reset_0_enable_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_edge_reset_1_en_lock [05:05] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_en_lock_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_en_lock_SHIFT 5
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_en_lock_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_edge_reset_1_enable [04:04] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_enable_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_enable_SHIFT 4
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_1_enable_DEFAULT 0x00000001

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_edge_reset_0_en_lock [03:03] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_en_lock_MASK 0x00000008
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_en_lock_SHIFT 3
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_en_lock_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: aux_chip_edge_reset_0_enable [02:02] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_enable_MASK 0x00000004
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_enable_SHIFT 2
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_aux_chip_edge_reset_0_enable_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: sw_master_reset_en_lock [01:01] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_en_lock_MASK 0x00000002
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_en_lock_SHIFT 1
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_en_lock_DEFAULT 0x00000000

/* SUN_TOP_CTRL :: RESET_SOURCE_ENABLE :: sw_master_reset_enable [00:00] */
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_enable_MASK 0x00000001
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_enable_SHIFT 0
#define BCHP_SUN_TOP_CTRL_RESET_SOURCE_ENABLE_sw_master_reset_enable_DEFAULT 0x00000000

/***************************************************************************
 *SW_MASTER_RESET - Software master reset
 ***************************************************************************/
/* SUN_TOP_CTRL :: SW_MASTER_RESET :: reserved0 [31:01] */
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET_reserved0_MASK           0xfffffffe
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET_reserved0_SHIFT          1

/* SUN_TOP_CTRL :: SW_MASTER_RESET :: chip_master_reset [00:00] */
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET_chip_master_reset_MASK   0x00000001
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET_chip_master_reset_SHIFT  0
#define BCHP_SUN_TOP_CTRL_SW_MASTER_RESET_chip_master_reset_DEFAULT 0x00000000


#define BRCMSTB_POWER_TIMEOUT 50000 /* 50000us = 50ms */
#define BRCMSTB_POWER_RETRIES 10    /* Max time = 50ms * 10 */

static inline int wait_bits_set(uintptr_t raddr, uint32_t bits)
{
    int retry = BRCMSTB_POWER_RETRIES;

    while (retry--) {
        if (MMIO32(raddr) & bits)
            return 0;
        udelay(BRCMSTB_POWER_TIMEOUT);
    }
    return -1;
}

static inline int wait_bits_clr(uintptr_t raddr, uint32_t bits)
{
    int retry = BRCMSTB_POWER_RETRIES;

    while (retry--) {
        if (~(MMIO32(raddr) & bits))
            return 0;
        udelay(BRCMSTB_POWER_TIMEOUT);
    }
    return -1;
}

int plat_cpu_power_up(
    uint32_t cpu_index,
    uintptr_t entry_point)
{
    uintptr_t raddr;

    /* Turn on CPU power zone */
    raddr = BRCMSTB_REG_ADDR_WITH_INDEX(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, cpu_index);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_ISO_CNTL);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MANUAL_CONTROL);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, reserved1);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_MEM_PWR);

    if (wait_bits_set(raddr, BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_MEM_PWR)))
        return MON_ERR;

    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_CLKEN);

    if (wait_bits_set(raddr, BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_DPG_PWR_STATE)))
        return MON_ERR;

    MMIO32(raddr) &= ~BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_ISO_CNTL);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_RESET_CNTL);

    /* Program CPU entry point */
    raddr = BRCMSTB_REG_ADDR_WITH_INDEX(HIF_CONTINUATION, STB_BOOT_HI_ADDR0, cpu_index);
    MMIO32(raddr    ) = entry_point >> 32;
    MMIO32(raddr + 4) = entry_point & 0xffffffff;

    dsb();

    /* Take CPU out of reset */
    raddr = BRCMSTB_REG_ADDR(HIF_CPUBIUCTRL, CPU_RESET_CONFIG_REG);
    MMIO32(raddr) &= ~(1 << cpu_index);

    return MON_OK;
}

int plat_cpu_power_down(uint32_t cpu_index)
{
    uintptr_t raddr;

    /* Turn off CPU power zone */
    raddr = BRCMSTB_REG_ADDR_WITH_INDEX(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, cpu_index);

    /* It's important to do ZONE_MAN_ISO_CNTL *first* */
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_ISO_CNTL);
    MMIO32(raddr) |=  BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MANUAL_CONTROL);
    MMIO32(raddr) &= ~BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_RESET_CNTL);
    MMIO32(raddr) &= ~BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_CLKEN);
    MMIO32(raddr) &= ~BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_MAN_MEM_PWR);

    if (wait_bits_clr(raddr, BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_DPG_PWR_STATE)))
        return MON_ERR;

    /* This is actually DPG */
    MMIO32(raddr) &= ~BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, reserved1);

    if (wait_bits_clr(raddr, BRCMSTB_FIELD_MASK(HIF_CPUBIUCTRL, CPU0_PWR_ZONE_CNTRL_REG, ZONE_DPG_PWR_STATE)))
        return MON_ERR;

    /* If CPU power zone goes wrong, it can read zero. Catch it here */
    if (!MMIO32(raddr))
        return MON_ERR;

    dsb();

    /* Put CPU in reset */
    raddr = BRCMSTB_REG_ADDR(HIF_CPUBIUCTRL, CPU_RESET_CONFIG_REG);
    MMIO32(raddr) |= (1 << cpu_index);

    return MON_OK;
}

int plat_system_off(uint32_t last_cpu_index)
{
    uintptr_t raddr;

    /* All other CPU's should have already been powered down !!! */

    /* Put last CPU in reset */
    raddr = BRCMSTB_REG_ADDR(HIF_CPUBIUCTRL, CPU_RESET_CONFIG_REG);
    MMIO32(raddr) |= (1 << last_cpu_index);

    return MON_OK;
}

int plat_system_reset(void)
{
    uintptr_t raddr;

    /* Enable software master reset source */
    raddr = BRCMSTB_REG_ADDR(SUN_TOP_CTRL, RESET_SOURCE_ENABLE);
    MMIO32(raddr) |= BRCMSTB_FIELD_MASK(SUN_TOP_CTRL, RESET_SOURCE_ENABLE, sw_master_reset_enable);

    /* Hit chip reset in software master reset */
    raddr = BRCMSTB_REG_ADDR(SUN_TOP_CTRL, SW_MASTER_RESET);
    MMIO32(raddr) |= BRCMSTB_FIELD_MASK(SUN_TOP_CTRL, SW_MASTER_RESET, chip_master_reset);

    return MON_OK;
}
