############################################################
# Broadcom Proprietary and Confidential. (c)2016 Broadcom.
# All rights reserved.
############################################################

ccflags-y := -Iinclude/drm -I$(M)/include

brcmv3d-y := v3d_drv.o
brcmv3d-$(CONFIG_DEBUG_FS) += v3d_debugfs.o

obj-m += brcmv3d.o
