/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Fri Jul 11 11:35:55 2014
 *                 Full Compile MD5 Checksum  74317a30eab2c0396bb2d7c2dd9c02f7
 *                     (minus title and desc)
 *                 MD5 Checksum               2e09daa633013a10114c0860c809d8eb
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     14441
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_AUD_FMM_BF_ESR0_D0_H__
#define BCHP_AUD_FMM_BF_ESR0_D0_H__

/***************************************************************************
 *AUD_FMM_BF_ESR0_D0 - FMM-BF Error Status 0 (for DSP0)
 ***************************************************************************/
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS           0x008a3100 /* Error Status Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS_SET       0x008a3104 /* Error Set Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS_CLEAR     0x008a3108 /* Error Clear Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK             0x008a310c /* Mask Status Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK_SET         0x008a3110 /* Mask Set Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK_CLEAR       0x008a3114 /* Mask Clear Register */

#endif /* #ifndef BCHP_AUD_FMM_BF_ESR0_D0_H__ */

/* End of File */
