/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 18 01:14:34 2009
 *                 MD5 Checksum         8e4822e2d8c445f841e653dc06da5e41
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_RM_1_H__
#define BCHP_RM_1_H__

/***************************************************************************
 *RM_1 - Rate Manger RM_1
 ***************************************************************************/
#define BCHP_RM_1_CONTROL                        0x00183a40 /* Rate Manager Controls */
#define BCHP_RM_1_RATE_RATIO                     0x00183a44 /* Rate Manager Output Rate Setting I */
#define BCHP_RM_1_SAMPLE_INC                     0x00183a48 /* Rate Manager Output Rate Setting II */
#define BCHP_RM_1_PHASE_INC                      0x00183a4c /* Rate Manager NCO Phase Increment */
#define BCHP_RM_1_INTEGRATOR                     0x00183a50 /* Loop Filter Integrator Value */
#define BCHP_RM_1_SKIP_REPEAT_CONTROL            0x00183a54 /* Time Base Skip or Repeat Control Register */
#define BCHP_RM_1_SKIP_REPEAT_GAP                0x00183a58 /* Time Base Skip or Repeat Gap Count Register */
#define BCHP_RM_1_SKIP_REPEAT_NUMBER             0x00183a5c /* Time Base Skip or Repeat Count Register */
#define BCHP_RM_1_STATUS                         0x00183a60 /* Rate Manager Status Register */
#define BCHP_RM_1_STATUS_CLEAR                   0x00183a64 /* Rate Manager Status Clear Register */

#endif /* #ifndef BCHP_RM_1_H__ */

/* End of File */
