/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Fri Oct 18 11:45:08 2013
 *                 Full Compile MD5 Checksum 32c6546d3ec1c83fbf8bc6d4e3ec46d1
 *                   (minus title and desc)  
 *                 MD5 Checksum              839f407f1c04ba70b32cb458815eb9b4
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_STB_CHAN_CH2_H__
#define BCHP_STB_CHAN_CH2_H__

/***************************************************************************
 *STB_CHAN_CH2
 ***************************************************************************/
#define BCHP_STB_CHAN_CH2_DEC_FCW                0x000a8300 /* Decimation tile : Frequency control word */
#define BCHP_STB_CHAN_CH2_ACI_H0                 0x000a8304 /* Baseband tile : Filter coefficient tap 0 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H1                 0x000a8308 /* Baseband tile : Filter coefficient tap 1 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H2                 0x000a830c /* Baseband tile : Filter coefficient tap 2 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H3                 0x000a8310 /* Baseband tile : Filter coefficient tap 3 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H4                 0x000a8314 /* Baseband tile : Filter coefficient tap 4 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H5                 0x000a8318 /* Baseband tile : Filter coefficient tap 5 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H6                 0x000a831c /* Baseband tile : Filter coefficient tap 6 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H7                 0x000a8320 /* Baseband tile : Filter coefficient tap 7 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H8                 0x000a8324 /* Baseband tile : Filter coefficient tap 8 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H9                 0x000a8328 /* Baseband tile : Filter coefficient tap 9 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H10                0x000a832c /* Baseband tile : Filter coefficient tap 10 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H11                0x000a8330 /* Baseband tile : Filter coefficient tap 11 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H12                0x000a8334 /* Baseband tile : Filter coefficient tap 12 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H13                0x000a8338 /* Baseband tile : Filter coefficient tap 13 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H14                0x000a833c /* Baseband tile : Filter coefficient tap 14 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H15                0x000a8340 /* Baseband tile : Filter coefficient tap 15 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H16                0x000a8344 /* Baseband tile : Filter coefficient tap 16 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H17                0x000a8348 /* Baseband tile : Filter coefficient tap 17 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H18                0x000a834c /* Baseband tile : Filter coefficient tap 18 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H19                0x000a8350 /* Baseband tile : Filter coefficient tap 19 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H20                0x000a8354 /* Baseband tile : Filter coefficient tap 20 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H21                0x000a8358 /* Baseband tile : Filter coefficient tap 21 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H22                0x000a835c /* Baseband tile : Filter coefficient tap 22 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H23                0x000a8360 /* Baseband tile : Filter coefficient tap 23 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H24                0x000a8364 /* Baseband tile : Filter coefficient tap 24 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H25                0x000a8368 /* Baseband tile : Filter coefficient tap 25 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H26                0x000a836c /* Baseband tile : Filter coefficient tap 26 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H27                0x000a8370 /* Baseband tile : Filter coefficient tap 27 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H28                0x000a8374 /* Baseband tile : Filter coefficient tap 28 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H29                0x000a8378 /* Baseband tile : Filter coefficient tap 29 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H30                0x000a837c /* Baseband tile : Filter coefficient tap 30 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H31                0x000a8380 /* Baseband tile : Filter coefficient tap 31 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H32                0x000a8384 /* Baseband tile : Filter coefficient tap 32 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H33                0x000a8388 /* Baseband tile : Filter coefficient tap 33 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H34                0x000a838c /* Baseband tile : Filter coefficient tap 34 (tc1.15) */
#define BCHP_STB_CHAN_CH2_ACI_H35                0x000a8390 /* Baseband tile : Filter coefficient tap 35 (tc1.15) */
#define BCHP_STB_CHAN_CH2_NOTCH_0_CTRL           0x000a8394 /* Baseband tile : Notch 0 controls */
#define BCHP_STB_CHAN_CH2_NOTCH_0_FCW            0x000a8398 /* Baseband tile : Notch 0 frequency control word */
#define BCHP_STB_CHAN_CH2_NOTCH_0_INT_I          0x000a839c /* Baseband tile : Notch 0 DC notch filter integrator I */
#define BCHP_STB_CHAN_CH2_NOTCH_0_INT_Q          0x000a83a0 /* Baseband tile : Notch 0 DC notch filter integrator Q */
#define BCHP_STB_CHAN_CH2_NOTCH_0_INT_LF         0x000a83a4 /* Baseband tile : Notch 0 tracking loop filter integrator */
#define BCHP_STB_CHAN_CH2_NOTCH_1_CTRL           0x000a83a8 /* Baseband tile : Notch 1 controls */
#define BCHP_STB_CHAN_CH2_NOTCH_1_FCW            0x000a83ac /* Baseband tile : Notch 1 frequency control word */
#define BCHP_STB_CHAN_CH2_NOTCH_1_INT_I          0x000a83b0 /* Baseband tile : Notch 1 DC notch filter integrator I */
#define BCHP_STB_CHAN_CH2_NOTCH_1_INT_Q          0x000a83b4 /* Baseband tile : Notch 1 DC notch filter integrator Q */
#define BCHP_STB_CHAN_CH2_NOTCH_1_INT_LF         0x000a83b8 /* Baseband tile : Notch 1 tracking loop filter integrator */
#define BCHP_STB_CHAN_CH2_NOTCH_LF_CTRL          0x000a83bc /* Baseband tile : Notch tracking loop filter control */
#define BCHP_STB_CHAN_CH2_AGC_CTRL               0x000a83c0 /* Baseband tile : AGC controls */
#define BCHP_STB_CHAN_CH2_AGC_LA_INT             0x000a83c4 /* Baseband tile : AGC Leaky averager integrator write data (tc2.18) */
#define BCHP_STB_CHAN_CH2_AGC_LF_INT             0x000a83c8 /* Baseband tile : AGC Shift accumulator integrator write data (tc1.27) */
#define BCHP_STB_CHAN_CH2_CLIP_CTRL              0x000a83cc /* Baseband tile : Clip counter related controls */
#define BCHP_STB_CHAN_CH2_CLIP_COUNT             0x000a83d0 /* Baseband tile : Clip counter read value */
#define BCHP_STB_CHAN_CH2_CRC_COUNT              0x000a83d4 /* Interpolation tile : CRC count */
#define BCHP_STB_CHAN_CH2_CRC_VALUE              0x000a83d8 /* Interpolation tile : CRC read value */
#define BCHP_STB_CHAN_CH2_FREQ_ERR_CTRL          0x000a83dc /* Frequency error from SDS */
#define BCHP_STB_CHAN_CH2_TP_OUT_CTRL            0x000a83e0 /* Testport out controls */
#define BCHP_STB_CHAN_CH2_SW_SPARE0              0x000a83e4 /* Spare Register For Software Test */
#define BCHP_STB_CHAN_CH2_SW_SPARE1              0x000a83e8 /* Spare Register For Software Test */

#endif /* #ifndef BCHP_STB_CHAN_CH2_H__ */

/* End of File */
