/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Fri Oct 18 11:45:08 2013
 *                 Full Compile MD5 Checksum 32c6546d3ec1c83fbf8bc6d4e3ec46d1
 *                   (minus title and desc)  
 *                 MD5 Checksum              839f407f1c04ba70b32cb458815eb9b4
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_AIF_WB_SAT_ANA_U1_1_H__
#define BCHP_AIF_WB_SAT_ANA_U1_1_H__

/***************************************************************************
 *AIF_WB_SAT_ANA_U1_1 - ANA WBADC Register Set
 ***************************************************************************/
#define BCHP_AIF_WB_SAT_ANA_U1_1_ADC_CNTL0       0x000b5000 /* adc_cntl0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_ADC_CNTL1       0x000b5004 /* adc_cntl1 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_ADC_CNTL2       0x000b5008 /* adc_cntl2 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_ADC_CNTL3       0x000b500c /* adc_cntl3 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_DPM_CNTL0_IN0   0x000b5010 /* dpm_cntl0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_DPM_CNTL1_IN0   0x000b5014 /* dpm_cntl1 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_DPM_PLL_CNTL0_IN0 0x000b5018 /* dpm_pll_cntl0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_DPM_PLL_CNTL1_IN0 0x000b501c /* dpm_pll_cntl1 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_DPM_PLL_CNTL2_IN0 0x000b5020 /* dpm_pll_cntl2 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_RFFE_CNTL0_IN0  0x000b5024 /* rffe_cntl0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_RFFE_CNTL1_IN0  0x000b5028 /* rffe_cntl1 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_WBADC_CAL_CNTL_IN0 0x000b502c /* wbadc_cal_cntl */
#define BCHP_AIF_WB_SAT_ANA_U1_1_WBADC_SYS_CNTL_IN0 0x000b5030 /* wbadc_sys_cntl */
#define BCHP_AIF_WB_SAT_ANA_U1_1_WBADC_TIMING_CNTL1_IN0 0x000b503c /* wbadc_timing_cntl1 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_WBADC_TIMING_CNTL_IN0 0x000b5038 /* wbadc_timing_cntl */
#define BCHP_AIF_WB_SAT_ANA_U1_1_WBADC_TOP_CNTL_IN0 0x000b5034 /* wbadc_top_cntl */
#define BCHP_AIF_WB_SAT_ANA_U1_1_CLK_CTRL_IN0    0x000b5040 /* clk_ctrl_in0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_PGA_GAIN_IN0    0x000b5044 /* pga_gain_in0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_SW_SPARE0       0x000b5048 /* sw_spare0 */
#define BCHP_AIF_WB_SAT_ANA_U1_1_SW_SPARE1       0x000b504c /* sw_spare1 */

#endif /* #ifndef BCHP_AIF_WB_SAT_ANA_U1_1_H__ */

/* End of File */
