#
# Linux 2.4 Makefile for remote socket client kernel module
#
# Broadcom Proprietary and Confidential. Copyright (C) 2017,
# All Rights Reserved.
# 
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom;
# the contents of this file may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior
# written permission of Broadcom.
# $Id$
#

# Now try a couple of places for LINUXDIR if not specified
ifeq ($(LINUXDIR),)
  ifeq ($(LINUXVER),)
    # Neither one is specified, use uname for version
    LINUXVER := $(shell uname -r)
  endif
  ifneq ($(wildcard /lib/modules/$(LINUXVER)/build/include/linux/version.h),)
    LINUXDIR := /lib/modules/$(LINUXVER)/build
  else
    ifneq ($(wildcard /tools/linux/src/linux-$(LINUXVER)/include/linux/version.h),)
      LINUXDIR := /tools/linux/src/linux-$(LINUXVER)
    else
      LINUXDIR := /usr/src/linux
    endif
  endif
endif

ifeq ($(filter 2.6.%, $(LINUXVER)), )
  LINUX26REL=0
else
  LINUX26REL=1
  LINUX26DIR=linux26
  LINUX26MAKEFILE=makefile.26
endif

# driver source base
SRCBASE := ../..

# basic options
LOCALCFLAGS := -I. -I../../toe/rsock/exe -I$(SRCBASE)/include
LOCALCFLAGS += -MD
LOCALCFLAGS += -fshort-wchar
LOCALCFLAGS += -DBCMDRIVER
#LOCALCFLAGS += -DDEBUG

RSTEST_OBJ = rstest.o rstest_cmd.o rsock.o ifconfig.o ttcp.o util.o os.o

ifeq ($(LINUX26REL), 0)
KCFLAGS := $(shell $(MAKE) --no-print-directory -s -C $(LINUXDIR) script 'SCRIPT=@echo $$(CFLAGS) $$(MODFLAGS)')
TARGETS := rstest_mod.o

vpath %.c ../../toe/rsock/exe

all: $(TARGETS)

sinclude *.d

CFLAGS = $(LOCALCFLAGS) $(KCFLAGS)

%.o: %.c
	$(CC) -c $(CFLAGS) $<

RSOCK_C = $(SRCBASE)/toe/rsock/rsock.c

rsock.o: $(RSOCK_C)
	$(CC) -c $(CFLAGS) $(RSOCK_C)

rstest_mod.o: $(RSTEST_OBJ)
	$(LD) -r -o $@ $(RSTEST_OBJ)

else

EXTRA_FLAGS += $(LOCALCFLAGS) $(KCFLAGS)

obj-m := rstest_mod.o

modules: $(RSTEST_OBJ)
	$(MAKE) -C $(LINUXDIR) M=$(PWD) modules

endif

clean:
	$(RM) *.o *.ko
