#!/bin/sh
# this script sets LD_LIBRARY_PATH environment variable
# and checks consistence of the system configuration

LD_LIBRARY_PATH=.:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH
PATH=.:${PATH}
export PATH

if [ $UID -ne "0" ]; then
	echo "You need to run $@ as root."
	exit 1
fi

# stop any currently running version of boa
RUNNING=`ps -eaf | grep boa_server | grep -v grep | awk '{print $2;}'`
if [[ -z "$RUNNING" ]]; then
  echo "boa is not currently running."
else
  echo "boa is currently running as pid $RUNNING; killing it."
  kill -9 $RUNNING
fi

# start boa web server
TEMPDIR=$B_ANDROID_TEMP

if [[ -z "$TEMPDIR" ]]; then
  ### echo "TEMPDIR is not set"
  ./boa_server -c ./
else
  ### echo "TEMPDIR is currently set to $TEMPDIR"
  ./boa_server -c $TEMPDIR
fi

### NEWPID=`ps -eaf | grep boa | grep -v grep | awk '{print $2;}'`
### echo "The new boa PID is: [$NEWPID]"
echo " "

### IPADDR=`ifconfig | grep "inet addr" | grep Bcast | awk '{print $2;}' | awk -F ":" '{print $2}'`
### echo "Connect to the STB using http://$IPADDR"
ifconfig | egrep 'Link encap|inet addr' | awk '{if ( $1 == "inet"  && substr($2,6,3) != "127" ) { print "Connect to the STB using: http://" substr($2,6) "/index.html";} else {PREV=$1;} }'
echo " "

# start the nexus drivers
if [ -e nexus ]; then
nexus > /dev/null
fi

# if bmemperf.sh exists, start the server
if [ -e bmemperf.sh ]; then
source bmemperf.sh
fi

# if bperf.sh exists, start the server
if [ -e bperf.sh ]; then
./bperf.sh
fi

# if bsysperf.sh exists, start the server
if [ -e bsysperf.sh ]; then
source bsysperf.sh
fi
