#############################################################################
#  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
#############################################################################

APP := spytool_replay

app:
	$(MAKE) -f $(APP).mk

clean_app:
	$(MAKE) -f $(APP).mk clean_app

clean:
	$(MAKE) -f $(APP).mk clean
