/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Mar 27 10:49:16 2013
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_SDS_FE_7_H__
#define BCHP_SDS_FE_7_H__

/***************************************************************************
 *SDS_FE_7 - 7 SDS Frontend Register Set
 ***************************************************************************/
#define BCHP_SDS_FE_7_ADCPCTL                    0x01247080 /* ADC Capture Control (Formerly, ADCDBIT, ADCPCLP, ADCPCTL) */
#define BCHP_SDS_FE_7_DCOCTL                     0x01247088 /* DC Offset Cancellor Control (Formerly, DCOLKCTL, DCOCTL2, DCOCTL1) */
#define BCHP_SDS_FE_7_DCOI                       0x0124708c /* DCO Integrator Values (Formerly, DCO) */
#define BCHP_SDS_FE_7_IQCTL                      0x01247094 /* I/Q Imbalance Control (Formerly, IQAMP, IQPHS) */
#define BCHP_SDS_FE_7_IQAEST                     0x01247098 /* IQ Imbalance Amplitude Integrator Value (Formerly, AEST) */
#define BCHP_SDS_FE_7_IQPEST                     0x0124709c /* IQ Imbalance Phase Integrator Value (Formerly, PEST) */
#define BCHP_SDS_FE_7_MIXCTL                     0x012470a0 /* Frontend Mixer Control */
#define BCHP_SDS_FE_7_DSTGCTL                    0x012470a4 /* Destagger Control */
#define BCHP_SDS_FE_7_FILTCTL                    0x012470a8 /* Decimating Halfband Filter/Non-decimating Filter Control (Formerly, NDFCTL,FILTCTL) */
#define BCHP_SDS_FE_7_DFCTL                      0x012470ac /* Decimation Filter Bank Upsampling Control */
#define BCHP_SDS_FE_7_AGFCTL                     0x012470b0 /* Automatic Fine Gain Control */
#define BCHP_SDS_FE_7_AGF                        0x012470b4 /* AGF Gain and Threshold Control */
#define BCHP_SDS_FE_7_AIF                        0x012470b8 /* AGF Integrator Value */
#define BCHP_SDS_FE_7_NVCTL                      0x012470bc /* Nyquist and VID Filter Control */

#endif /* #ifndef BCHP_SDS_FE_7_H__ */

/* End of File */
