/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Feb 11 10:13:59 2015
 *                 Full Compile MD5 Checksum  f7f4bd55341805fcfe958ba5e47e65f4
 *                     (minus title and desc)
 *                 MD5 Checksum               95b679a9655597a92593cae55222c397
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15653
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_HEVD_FILTER_2_0_H__
#define BCHP_HEVD_FILTER_2_0_H__

/***************************************************************************
 *HEVD_FILTER_2_0
 ***************************************************************************/
#define BCHP_HEVD_FILTER_2_0_DBLK_TU_INFO        0x00144400 /* [WO] Deblock TU Info */
#define BCHP_HEVD_FILTER_2_0_DBLK_MV_INFO        0x00144404 /* [WO] Deblock Motion Vector Info */
#define BCHP_HEVD_FILTER_2_0_DBLK_QP             0x00144408 /* [WO] Deblock QP values */
#define BCHP_HEVD_FILTER_2_0_INFO                0x0014440c /* [WO] Filter Information */
#define BCHP_HEVD_FILTER_2_0_SLICE               0x00144410 /* [WO] Slice-level deblocking info */
#define BCHP_HEVD_FILTER_2_0_SAO                 0x00144414 /* [WO] SAO information for one component */
#define BCHP_HEVD_FILTER_2_0_SAO_OFFSET          0x00144418 /* [WO] SAO offsets for one component */
#define BCHP_HEVD_FILTER_2_0_TOP_DEBUG           0x001444c0 /* [RO] Top-level Debug */
#define BCHP_HEVD_FILTER_2_0_DBLK_DEBUG          0x001444c4 /* [RO] Deblock debug */
#define BCHP_HEVD_FILTER_2_0_CHECKSUM            0x001444f0 /* [RO] Output Pipebuf Checksum */
#define BCHP_HEVD_FILTER_2_0_STATUS              0x001444fc /* [RO] Status */

#endif /* #ifndef BCHP_HEVD_FILTER_2_0_H__ */

/* End of File */
