/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Feb 11 10:13:59 2015
 *                 Full Compile MD5 Checksum  f7f4bd55341805fcfe958ba5e47e65f4
 *                     (minus title and desc)
 *                 MD5 Checksum               95b679a9655597a92593cae55222c397
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15653
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_RF4CE_CPU_HOST_RG_L2_H__
#define BCHP_RF4CE_CPU_HOST_RG_L2_H__

/***************************************************************************
 *RF4CE_CPU_HOST_RG_L2 - Host RG L2 Interrupt Controller Registers
 ***************************************************************************/
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_STATUS0    0x01480a00 /* [RO] CPU interrupt Status Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_SET0       0x01480a04 /* [WO] CPU interrupt Set Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_CLEAR0     0x01480a08 /* [WO] CPU interrupt Clear Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_STATUS0 0x01480a0c /* [RO] CPU interrupt Mask Status Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_SET0  0x01480a10 /* [WO] CPU interrupt Mask Set Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_CLEAR0 0x01480a14 /* [WO] CPU interrupt Mask Clear Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_STATUS1    0x01480a18 /* [RO] Host Interrupt Status Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_SET1       0x01480a1c /* [WO] Host Interrupt Set Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_CLEAR1     0x01480a20 /* [WO] Host Interrupt Clear Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_STATUS1 0x01480a24 /* [RO] Host Interrupt Mask Status Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_SET1  0x01480a28 /* [WO] Host Interrupt Mask Set Register */
#define BCHP_RF4CE_CPU_HOST_RG_L2_CPU_MASK_CLEAR1 0x01480a2c /* [WO] Host Interrupt Mask Clear Register */

#endif /* #ifndef BCHP_RF4CE_CPU_HOST_RG_L2_H__ */

/* End of File */
