/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Aug 25 10:46:55 2015
 *                 Full Compile MD5 Checksum  add20cb7888302c2ee8be1277223a4e4
 *                     (minus title and desc)
 *                 MD5 Checksum               f64b4ec86ad9ad7523e5d75b1dc732c5
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     126
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /tools/dvtsw/current/Linux/combo_header.pl
 *                 DVTSWVER                   current
 *
 *
 ***************************************************************************/

#ifndef BCHP_GIO_AON_H__
#define BCHP_GIO_AON_H__

/***************************************************************************
 *GIO_AON - GPIO
 ***************************************************************************/
#define BCHP_GIO_AON_ODEN_LO                     0x00408c00 /* [RW] GENERAL PURPOSE I/O OPEN DRAIN ENABLE [26:0] */
#define BCHP_GIO_AON_DATA_LO                     0x00408c04 /* [RW] GENERAL PURPOSE I/O DATA [26:0] */
#define BCHP_GIO_AON_IODIR_LO                    0x00408c08 /* [RW] GENERAL PURPOSE I/O DIRECTION [26:0] */
#define BCHP_GIO_AON_EC_LO                       0x00408c0c /* [RW] GENERAL PURPOSE I/O EDGE CONFIGURATION [26:0] */
#define BCHP_GIO_AON_EI_LO                       0x00408c10 /* [RW] GENERAL PURPOSE I/O EDGE INSENSITIVE [26:0] */
#define BCHP_GIO_AON_MASK_LO                     0x00408c14 /* [RW] GENERAL PURPOSE I/O INTERRUPT MASK [26:0] */
#define BCHP_GIO_AON_LEVEL_LO                    0x00408c18 /* [RW] GENERAL PURPOSE I/O INTERRUPT TYPE [26:0] */
#define BCHP_GIO_AON_STAT_LO                     0x00408c1c /* [RW] GENERAL PURPOSE I/O INTERRUPT STATUS [26:0] */
#define BCHP_GIO_AON_ODEN_EXT                    0x00408c40 /* [RW] GENERAL PURPOSE I/O OPEN DRAIN ENABLE [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_DATA_EXT                    0x00408c44 /* [RW] GENERAL PURPOSE I/O DATA [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_IODIR_EXT                   0x00408c48 /* [RW] GENERAL PURPOSE I/O DIRECTION [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_EC_EXT                      0x00408c4c /* [RW] GENERAL PURPOSE I/O EDGE CONFIGURATION [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_EI_EXT                      0x00408c50 /* [RW] GENERAL PURPOSE I/O EDGE INSENSITIVE [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_MASK_EXT                    0x00408c54 /* [RW] GENERAL PURPOSE I/O INTERRUPT MASK [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_LEVEL_EXT                   0x00408c58 /* [RW] GENERAL PURPOSE I/O INTERRUPT TYPE [65:64] (SGPIO[3:2]) */
#define BCHP_GIO_AON_STAT_EXT                    0x00408c5c /* [RW] GENERAL PURPOSE I/O INTERRUPT STATUS [65:64] (SGPIO[3:2]) */

/***************************************************************************
 *ODEN_LO - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [26:0]
 ***************************************************************************/
/* GIO_AON :: ODEN_LO :: spare [31:27] */
#define BCHP_GIO_AON_ODEN_LO_spare_MASK                            0xf8000000
#define BCHP_GIO_AON_ODEN_LO_spare_SHIFT                           27
#define BCHP_GIO_AON_ODEN_LO_spare_DEFAULT                         0x00000000

/* GIO_AON :: ODEN_LO :: oden [26:00] */
#define BCHP_GIO_AON_ODEN_LO_oden_MASK                             0x07ffffff
#define BCHP_GIO_AON_ODEN_LO_oden_SHIFT                            0
#define BCHP_GIO_AON_ODEN_LO_oden_DEFAULT                          0x00000000

/***************************************************************************
 *DATA_LO - GENERAL PURPOSE I/O DATA [26:0]
 ***************************************************************************/
/* GIO_AON :: DATA_LO :: spare [31:27] */
#define BCHP_GIO_AON_DATA_LO_spare_MASK                            0xf8000000
#define BCHP_GIO_AON_DATA_LO_spare_SHIFT                           27
#define BCHP_GIO_AON_DATA_LO_spare_DEFAULT                         0x00000000

/* GIO_AON :: DATA_LO :: data [26:00] */
#define BCHP_GIO_AON_DATA_LO_data_MASK                             0x07ffffff
#define BCHP_GIO_AON_DATA_LO_data_SHIFT                            0
#define BCHP_GIO_AON_DATA_LO_data_DEFAULT                          0x00000000

/***************************************************************************
 *IODIR_LO - GENERAL PURPOSE I/O DIRECTION [26:0]
 ***************************************************************************/
/* GIO_AON :: IODIR_LO :: spare [31:27] */
#define BCHP_GIO_AON_IODIR_LO_spare_MASK                           0xf8000000
#define BCHP_GIO_AON_IODIR_LO_spare_SHIFT                          27
#define BCHP_GIO_AON_IODIR_LO_spare_DEFAULT                        0x0000001f

/* GIO_AON :: IODIR_LO :: iodir [26:00] */
#define BCHP_GIO_AON_IODIR_LO_iodir_MASK                           0x07ffffff
#define BCHP_GIO_AON_IODIR_LO_iodir_SHIFT                          0
#define BCHP_GIO_AON_IODIR_LO_iodir_DEFAULT                        0x07ffffff

/***************************************************************************
 *EC_LO - GENERAL PURPOSE I/O EDGE CONFIGURATION [26:0]
 ***************************************************************************/
/* GIO_AON :: EC_LO :: spare [31:27] */
#define BCHP_GIO_AON_EC_LO_spare_MASK                              0xf8000000
#define BCHP_GIO_AON_EC_LO_spare_SHIFT                             27
#define BCHP_GIO_AON_EC_LO_spare_DEFAULT                           0x00000000

/* GIO_AON :: EC_LO :: edge_config [26:00] */
#define BCHP_GIO_AON_EC_LO_edge_config_MASK                        0x07ffffff
#define BCHP_GIO_AON_EC_LO_edge_config_SHIFT                       0
#define BCHP_GIO_AON_EC_LO_edge_config_DEFAULT                     0x00000000

/***************************************************************************
 *EI_LO - GENERAL PURPOSE I/O EDGE INSENSITIVE [26:0]
 ***************************************************************************/
/* GIO_AON :: EI_LO :: spare [31:27] */
#define BCHP_GIO_AON_EI_LO_spare_MASK                              0xf8000000
#define BCHP_GIO_AON_EI_LO_spare_SHIFT                             27
#define BCHP_GIO_AON_EI_LO_spare_DEFAULT                           0x00000000

/* GIO_AON :: EI_LO :: edge_insensitive [26:00] */
#define BCHP_GIO_AON_EI_LO_edge_insensitive_MASK                   0x07ffffff
#define BCHP_GIO_AON_EI_LO_edge_insensitive_SHIFT                  0
#define BCHP_GIO_AON_EI_LO_edge_insensitive_DEFAULT                0x00000000

/***************************************************************************
 *MASK_LO - GENERAL PURPOSE I/O INTERRUPT MASK [26:0]
 ***************************************************************************/
/* GIO_AON :: MASK_LO :: spare [31:27] */
#define BCHP_GIO_AON_MASK_LO_spare_MASK                            0xf8000000
#define BCHP_GIO_AON_MASK_LO_spare_SHIFT                           27
#define BCHP_GIO_AON_MASK_LO_spare_DEFAULT                         0x00000000

/* GIO_AON :: MASK_LO :: irq_mask [26:00] */
#define BCHP_GIO_AON_MASK_LO_irq_mask_MASK                         0x07ffffff
#define BCHP_GIO_AON_MASK_LO_irq_mask_SHIFT                        0
#define BCHP_GIO_AON_MASK_LO_irq_mask_DEFAULT                      0x00000000

/***************************************************************************
 *LEVEL_LO - GENERAL PURPOSE I/O INTERRUPT TYPE [26:0]
 ***************************************************************************/
/* GIO_AON :: LEVEL_LO :: spare [31:27] */
#define BCHP_GIO_AON_LEVEL_LO_spare_MASK                           0xf8000000
#define BCHP_GIO_AON_LEVEL_LO_spare_SHIFT                          27
#define BCHP_GIO_AON_LEVEL_LO_spare_DEFAULT                        0x00000000

/* GIO_AON :: LEVEL_LO :: level [26:00] */
#define BCHP_GIO_AON_LEVEL_LO_level_MASK                           0x07ffffff
#define BCHP_GIO_AON_LEVEL_LO_level_SHIFT                          0
#define BCHP_GIO_AON_LEVEL_LO_level_DEFAULT                        0x00000000

/***************************************************************************
 *STAT_LO - GENERAL PURPOSE I/O INTERRUPT STATUS [26:0]
 ***************************************************************************/
/* GIO_AON :: STAT_LO :: spare [31:27] */
#define BCHP_GIO_AON_STAT_LO_spare_MASK                            0xf8000000
#define BCHP_GIO_AON_STAT_LO_spare_SHIFT                           27
#define BCHP_GIO_AON_STAT_LO_spare_DEFAULT                         0x00000000

/* GIO_AON :: STAT_LO :: irq_status [26:00] */
#define BCHP_GIO_AON_STAT_LO_irq_status_MASK                       0x07ffffff
#define BCHP_GIO_AON_STAT_LO_irq_status_SHIFT                      0
#define BCHP_GIO_AON_STAT_LO_irq_status_DEFAULT                    0x00000000

/***************************************************************************
 *ODEN_EXT - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: ODEN_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_ODEN_EXT_reserved0_MASK                       0xfffffffc
#define BCHP_GIO_AON_ODEN_EXT_reserved0_SHIFT                      2

/* GIO_AON :: ODEN_EXT :: oden [01:00] */
#define BCHP_GIO_AON_ODEN_EXT_oden_MASK                            0x00000003
#define BCHP_GIO_AON_ODEN_EXT_oden_SHIFT                           0
#define BCHP_GIO_AON_ODEN_EXT_oden_DEFAULT                         0x00000000

/***************************************************************************
 *DATA_EXT - GENERAL PURPOSE I/O DATA [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: DATA_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_DATA_EXT_reserved0_MASK                       0xfffffffc
#define BCHP_GIO_AON_DATA_EXT_reserved0_SHIFT                      2

/* GIO_AON :: DATA_EXT :: data [01:00] */
#define BCHP_GIO_AON_DATA_EXT_data_MASK                            0x00000003
#define BCHP_GIO_AON_DATA_EXT_data_SHIFT                           0
#define BCHP_GIO_AON_DATA_EXT_data_DEFAULT                         0x00000000

/***************************************************************************
 *IODIR_EXT - GENERAL PURPOSE I/O DIRECTION [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: IODIR_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_IODIR_EXT_reserved0_MASK                      0xfffffffc
#define BCHP_GIO_AON_IODIR_EXT_reserved0_SHIFT                     2

/* GIO_AON :: IODIR_EXT :: iodir [01:00] */
#define BCHP_GIO_AON_IODIR_EXT_iodir_MASK                          0x00000003
#define BCHP_GIO_AON_IODIR_EXT_iodir_SHIFT                         0
#define BCHP_GIO_AON_IODIR_EXT_iodir_DEFAULT                       0x00000003

/***************************************************************************
 *EC_EXT - GENERAL PURPOSE I/O EDGE CONFIGURATION [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: EC_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_EC_EXT_reserved0_MASK                         0xfffffffc
#define BCHP_GIO_AON_EC_EXT_reserved0_SHIFT                        2

/* GIO_AON :: EC_EXT :: edge_config [01:00] */
#define BCHP_GIO_AON_EC_EXT_edge_config_MASK                       0x00000003
#define BCHP_GIO_AON_EC_EXT_edge_config_SHIFT                      0
#define BCHP_GIO_AON_EC_EXT_edge_config_DEFAULT                    0x00000000

/***************************************************************************
 *EI_EXT - GENERAL PURPOSE I/O EDGE INSENSITIVE [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: EI_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_EI_EXT_reserved0_MASK                         0xfffffffc
#define BCHP_GIO_AON_EI_EXT_reserved0_SHIFT                        2

/* GIO_AON :: EI_EXT :: edge_insensitive [01:00] */
#define BCHP_GIO_AON_EI_EXT_edge_insensitive_MASK                  0x00000003
#define BCHP_GIO_AON_EI_EXT_edge_insensitive_SHIFT                 0
#define BCHP_GIO_AON_EI_EXT_edge_insensitive_DEFAULT               0x00000000

/***************************************************************************
 *MASK_EXT - GENERAL PURPOSE I/O INTERRUPT MASK [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: MASK_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_MASK_EXT_reserved0_MASK                       0xfffffffc
#define BCHP_GIO_AON_MASK_EXT_reserved0_SHIFT                      2

/* GIO_AON :: MASK_EXT :: irq_mask [01:00] */
#define BCHP_GIO_AON_MASK_EXT_irq_mask_MASK                        0x00000003
#define BCHP_GIO_AON_MASK_EXT_irq_mask_SHIFT                       0
#define BCHP_GIO_AON_MASK_EXT_irq_mask_DEFAULT                     0x00000000

/***************************************************************************
 *LEVEL_EXT - GENERAL PURPOSE I/O INTERRUPT TYPE [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: LEVEL_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_LEVEL_EXT_reserved0_MASK                      0xfffffffc
#define BCHP_GIO_AON_LEVEL_EXT_reserved0_SHIFT                     2

/* GIO_AON :: LEVEL_EXT :: level [01:00] */
#define BCHP_GIO_AON_LEVEL_EXT_level_MASK                          0x00000003
#define BCHP_GIO_AON_LEVEL_EXT_level_SHIFT                         0
#define BCHP_GIO_AON_LEVEL_EXT_level_DEFAULT                       0x00000000

/***************************************************************************
 *STAT_EXT - GENERAL PURPOSE I/O INTERRUPT STATUS [65:64] (SGPIO[3:2])
 ***************************************************************************/
/* GIO_AON :: STAT_EXT :: reserved0 [31:02] */
#define BCHP_GIO_AON_STAT_EXT_reserved0_MASK                       0xfffffffc
#define BCHP_GIO_AON_STAT_EXT_reserved0_SHIFT                      2

/* GIO_AON :: STAT_EXT :: irq_status [01:00] */
#define BCHP_GIO_AON_STAT_EXT_irq_status_MASK                      0x00000003
#define BCHP_GIO_AON_STAT_EXT_irq_status_SHIFT                     0
#define BCHP_GIO_AON_STAT_EXT_irq_status_DEFAULT                   0x00000000

#endif /* #ifndef BCHP_GIO_AON_H__ */

/* End of File */
