/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Aug 25 10:46:54 2015
 *                 Full Compile MD5 Checksum  add20cb7888302c2ee8be1277223a4e4
 *                     (minus title and desc)
 *                 MD5 Checksum               f64b4ec86ad9ad7523e5d75b1dc732c5
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     126
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /tools/dvtsw/current/Linux/combo_header.pl
 *                 DVTSWVER                   current
 *
 *
 ***************************************************************************/

#ifndef BCHP_XPT_PB9_H__
#define BCHP_XPT_PB9_H__

/***************************************************************************
 *XPT_PB9 - Playback 9 Control Registers
 ***************************************************************************/
#define BCHP_XPT_PB9_CTRL1                       0x00a08580 /* [RW] Playback Control 1 Register */
#define BCHP_XPT_PB9_CTRL2                       0x00a08584 /* [RW] Playback Control 2 Register */
#define BCHP_XPT_PB9_CTRL3                       0x00a08588 /* [RW] Playback Control 3 Register */
#define BCHP_XPT_PB9_CTRL4                       0x00a0858c /* [RW] Playback Control 4 Register */
#define BCHP_XPT_PB9_FIRST_DESC_ADDR             0x00a08590 /* [RW] Playback First Descriptor Address Register */
#define BCHP_XPT_PB9_CURR_DESC_ADDR              0x00a08594 /* [RO] Playback Current Descriptor Address Register */
#define BCHP_XPT_PB9_CURR_BUFF_ADDR              0x00a08598 /* [RO] Playback Current Buffer Address Register */
#define BCHP_XPT_PB9_BLOCKOUT                    0x00a0859c /* [RW] Data Transport Playback Block Out Control */
#define BCHP_XPT_PB9_PKTZ_CONTEXT0               0x00a085a0 /* [RW] Data Transport Playback Packetize Mode Context 0 Control */
#define BCHP_XPT_PB9_TS_ERR_BOUND_EARLY          0x00a085a4 /* [RW] Data Transport Playback Timestamp Error Bound Register */
#define BCHP_XPT_PB9_TS_ERR_BOUND_LATE           0x00a085a8 /* [RW] Data Transport Playback Timestamp Error Bound Register */
#define BCHP_XPT_PB9_PARSER_CTRL1                0x00a085ac /* [RW] Data Transport Playback Parser Control Register */
#define BCHP_XPT_PB9_PARSER_CTRL2                0x00a085b0 /* [RW] Data Transport Playback Parser Control Register 2 */
#define BCHP_XPT_PB9_PARSER_TIMESTAMP            0x00a085b4 /* [RO] Data Transport Playback Parser Local Timestamp */
#define BCHP_XPT_PB9_INTR                        0x00a085b8 /* [RW] Playback Processing Error and Status Interrupt Register */
#define BCHP_XPT_PB9_INTR_EN                     0x00a085bc /* [RW] Playback Processing Error and Status Interrupt Enable Register */
#define BCHP_XPT_PB9_INTR_TAGS                   0x00a085c0 /* [RW] Playback Interrupt Tag Register */
#define BCHP_XPT_PB9_PACING_PCR_PID              0x00a085c4 /* [RW] Playback PCR Based Pacing PCR Pid */
#define BCHP_XPT_PB9_PWR_CTRL                    0x00a085c8 /* [RW] Playback Power Control Register */
#define BCHP_XPT_PB9_MISC_STATUS_REG             0x00a085cc /* [RW] Miscellaneous Playback Status Registers */
#define BCHP_XPT_PB9_ASF_CTRL                    0x00a085d0 /* [RW] ASF Control Register */
#define BCHP_XPT_PB9_ASF_DATA_PACKET_LENGTH      0x00a085d4 /* [RW] ASF_DATA_PACKET_LENGTH */
#define BCHP_XPT_PB9_ASF_SUB_PAYLOAD_PKT_TYPE    0x00a085d8 /* [RW] ASF_SUB_PAYLOAD_PKT_TYPE */
#define BCHP_XPT_PB9_ASF_PAYLOAD_PKT_TYPE        0x00a085dc /* [RW] ASF_PAYLOAD_PKT_TYPE */
#define BCHP_XPT_PB9_PLAYBACK_PARSER_BAND_ID     0x00a085e0 /* [RW] PLAYBACK_PARSER_BAND_ID */
#define BCHP_XPT_PB9_NEXT_PACKET_PACING_TIMESTAMP 0x00a085e4 /* [RW] Next Packet Pacing Timestamp Value */
#define BCHP_XPT_PB9_PKT2PKT_PACING_TIMESTAMP_DELTA 0x00a085e8 /* [RW] PKT2PKT Pacing TimeStamp Delta */
#define BCHP_XPT_PB9_PACING_COUNTER              0x00a085ec /* [RW] Pacing Counter Instantaneous value */
#define BCHP_XPT_PB9_ERROR_VALUE_WATERMARK       0x00a085f0 /* [RW] WaterMark level of the Pacing Error Bound Reached */
#define BCHP_XPT_PB9_PES_BASED_PACING_CTRL       0x00a085f4 /* [RW] PES Based Pacing Controls */

#endif /* #ifndef BCHP_XPT_PB9_H__ */

/* End of File */
