/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Aug 25 10:46:55 2015
 *                 Full Compile MD5 Checksum  add20cb7888302c2ee8be1277223a4e4
 *                     (minus title and desc)
 *                 MD5 Checksum               f64b4ec86ad9ad7523e5d75b1dc732c5
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     126
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /tools/dvtsw/current/Linux/combo_header.pl
 *                 DVTSWVER                   current
 *
 *
 ***************************************************************************/

#ifndef BCHP_VEC_CFG_H__
#define BCHP_VEC_CFG_H__

/***************************************************************************
 *VEC_CFG - Top-Level Controls
 ***************************************************************************/
#define BCHP_VEC_CFG_REVISION_ID                 0x00685000 /* [RO] Revision ID Register for Video Encoder */
#define BCHP_VEC_CFG_TP_CTRL                     0x00685004 /* [RW] Test port control Register for Video Encoder */
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0           0x00685008 /* [RW] ITU656 test control register for path 0 */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR          0x0068500c /* [RW] RAM test control for CBAR RAM */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0          0x00685010 /* [RW] RAM test control for IT_0 RAM */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1          0x00685014 /* [RW] RAM test control for IT_1 RAM */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0       0x00685018 /* [RW] RAM test control for DTRAM_0 RAM */
#define BCHP_VEC_CFG_VF_0_SOURCE                 0x0068501c /* [RW] Source Select Register for VF_0 */
#define BCHP_VEC_CFG_VF_1_SOURCE                 0x00685020 /* [RW] Source Select Register for VF_1 */
#define BCHP_VEC_CFG_SECAM_0_SOURCE              0x00685024 /* [RW] Source Select Register for SECAM_0 */
#define BCHP_VEC_CFG_SECAM_1_SOURCE              0x00685028 /* [RW] Source Select Register for SECAM_1 */
#define BCHP_VEC_CFG_SECAM_2_SOURCE              0x0068502c /* [RW] Source Select Register for SECAM_2 */
#define BCHP_VEC_CFG_SDSRC_0_SOURCE              0x00685030 /* [RW] Source Select Register for SDSRC_0 */
#define BCHP_VEC_CFG_HDSRC_0_SOURCE              0x00685034 /* [RW] Source Select Register for HDSRC_0 */
#define BCHP_VEC_CFG_IT_0_SOURCE                 0x00685038 /* [RW] Source Select Register for IT_0 */
#define BCHP_VEC_CFG_IT_1_SOURCE                 0x0068503c /* [RW] Source Select Register for IT_1 */
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE            0x00685040 /* [RW] Source Select Register for DVI_DTG_0 */
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE         0x00685044 /* [RW] Source Select Register for ITU656_DTG_0 */
#define BCHP_VEC_CFG_DECIM_0_SOURCE              0x00685048 /* [RW] Source Select Register for DECIM_0 */
#define BCHP_VEC_CFG_SW_INIT_IT_0                0x0068504c /* [RW] Software Init register for IT_0 */
#define BCHP_VEC_CFG_SW_INIT_IT_1                0x00685050 /* [RW] Software Init register for IT_1 */
#define BCHP_VEC_CFG_SW_INIT_VF_0                0x00685054 /* [RW] Software Init register for VF_0 */
#define BCHP_VEC_CFG_SW_INIT_VF_1                0x00685058 /* [RW] Software Init register for VF_1 */
#define BCHP_VEC_CFG_SW_INIT_SECAM_0             0x0068505c /* [RW] Software Init register for SECAM_0 */
#define BCHP_VEC_CFG_SW_INIT_SECAM_1             0x00685060 /* [RW] Software Init register for SECAM_1 */
#define BCHP_VEC_CFG_SW_INIT_SECAM_2             0x00685064 /* [RW] Software Init register for SECAM_2 */
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0             0x00685068 /* [RW] Software Init register for SDSRC_0 */
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0             0x0068506c /* [RW] Software Init register for HDSRC_0 */
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC            0x00685070 /* [RW] Software Init register for ANA_MISC */
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0             0x00685074 /* [RW] Software Init register for DTRAM_0 */
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC            0x00685078 /* [RW] Software Init register for VEC MISC */
#define BCHP_VEC_CFG_SW_INIT_TPG_0               0x0068507c /* [RW] Software Init register for TPG_0 */
#define BCHP_VEC_CFG_SW_INIT_MISC                0x00685080 /* [RW] Software Init register for MISC */
#define BCHP_VEC_CFG_SW_INIT_DECIM_0             0x00685084 /* [RW] Software Init register for DECIM_0 */
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0      0x00685088 /* [RW] Software Init register for CABLE_DETECT_0 */
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0           0x0068508c /* [RW] Software Init register for DVI DTG_0 */
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0           0x00685090 /* [RW] Software Init register for DVI CSC_0 */
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0           0x00685094 /* [RW] Software Init register for DVI DVF_0 */
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0          0x00685098 /* [RW] Software Init register for DVI MISC_0 */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0        0x0068509c /* [RW] Software Init register for ITU656 DTG_0 */
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0        0x006850a0 /* [RW] Software Init register for 656 CSC_0 */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0        0x006850a4 /* [RW] Software Init register for 656 DVF_0 */
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0  0x006850a8 /* [RW] Software Init register for 656 Formatter 0 */
#define BCHP_VEC_CFG_SW_INIT_CCE_0               0x006850ac /* [RW] Software Init register for CCE_0 */
#define BCHP_VEC_CFG_SW_INIT_CCE_1               0x006850b0 /* [RW] Software Init register for CCE_1 */
#define BCHP_VEC_CFG_SW_INIT_WSE_0               0x006850b4 /* [RW] Software Init register for WSE_0 */
#define BCHP_VEC_CFG_SW_INIT_WSE_1               0x006850b8 /* [RW] Software Init register for WSE_1 */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0            0x006850bc /* [RW] Software Init register for CGMSAE_0 */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1            0x006850c0 /* [RW] Software Init register for CGMSAE_1 */
#define BCHP_VEC_CFG_SW_INIT_TTE_0               0x006850c4 /* [RW] Software Init register for TTE_0 */
#define BCHP_VEC_CFG_SW_INIT_TTE_1               0x006850c8 /* [RW] Software Init register for TTE_1 */
#define BCHP_VEC_CFG_SW_INIT_GSE_0               0x006850cc /* [RW] Software Init register for GSE_0 */
#define BCHP_VEC_CFG_SW_INIT_GSE_1               0x006850d0 /* [RW] Software Init register for GSE_1 */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0             0x006850d4 /* [RW] Software Init register for AMOLE_0 */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1             0x006850d8 /* [RW] Software Init register for AMOLE_1 */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0          0x006850dc /* [RW] Software Init register for PASSTHRU_0 */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1          0x006850e0 /* [RW] Software Init register for PASSTHRU_1 */
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0         0x006850e4 /* [RW] Software Init register for CCE_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0         0x006850e8 /* [RW] Software Init register for WSE_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0         0x006850ec /* [RW] Software Init register for TTE_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0         0x006850f0 /* [RW] Software Init register for GSE_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0       0x006850f4 /* [RW] Software Init register for AMOLE_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0     0x006850f8 /* [RW] Software Init register for ANCI656_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0    0x006850fc /* [RW] Software Init register for PASSTHRU_ANCIL_0 */
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC            0x00685100 /* [RW] Software Init register for VBI_MISC */

/***************************************************************************
 *REVISION_ID - Revision ID Register for Video Encoder
 ***************************************************************************/
/* VEC_CFG :: REVISION_ID :: reserved0 [31:16] */
#define BCHP_VEC_CFG_REVISION_ID_reserved0_MASK                    0xffff0000
#define BCHP_VEC_CFG_REVISION_ID_reserved0_SHIFT                   16

/* VEC_CFG :: REVISION_ID :: REVISION_ID [15:00] */
#define BCHP_VEC_CFG_REVISION_ID_REVISION_ID_MASK                  0x0000ffff
#define BCHP_VEC_CFG_REVISION_ID_REVISION_ID_SHIFT                 0
#define BCHP_VEC_CFG_REVISION_ID_REVISION_ID_DEFAULT               0x00005010

/***************************************************************************
 *TP_CTRL - Test port control Register for Video Encoder
 ***************************************************************************/
/* VEC_CFG :: TP_CTRL :: reserved0 [31:03] */
#define BCHP_VEC_CFG_TP_CTRL_reserved0_MASK                        0xfffffff8
#define BCHP_VEC_CFG_TP_CTRL_reserved0_SHIFT                       3

/* VEC_CFG :: TP_CTRL :: TP_SELECT [02:00] */
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_MASK                        0x00000007
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_SHIFT                       0
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_DEFAULT                     0x00000000
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_0                        0
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_1                        1
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_2                        2
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_3                        3
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_4                        4
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_5                        5
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_6                        6
#define BCHP_VEC_CFG_TP_CTRL_TP_SELECT_TP_7                        7

/***************************************************************************
 *ITU656_TEST_SEL_0 - ITU656 test control register for path 0
 ***************************************************************************/
/* VEC_CFG :: ITU656_TEST_SEL_0 :: reserved0 [31:05] */
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0_reserved0_MASK              0xffffffe0
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0_reserved0_SHIFT             5

/* VEC_CFG :: ITU656_TEST_SEL_0 :: SEL [04:00] */
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0_SEL_MASK                    0x0000001f
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0_SEL_SHIFT                   0
#define BCHP_VEC_CFG_ITU656_TEST_SEL_0_SEL_DEFAULT                 0x00000000

/***************************************************************************
 *RAM_TEST_CTRL_CBAR - RAM test control for CBAR RAM
 ***************************************************************************/
/* VEC_CFG :: RAM_TEST_CTRL_CBAR :: reserved0 [31:12] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR_reserved0_MASK             0xfffff000
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR_reserved0_SHIFT            12

/* VEC_CFG :: RAM_TEST_CTRL_CBAR :: TM [11:00] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR_TM_MASK                    0x00000fff
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR_TM_SHIFT                   0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_CBAR_TM_DEFAULT                 0x00000000

/***************************************************************************
 *RAM_TEST_CTRL_IT_0 - RAM test control for IT_0 RAM
 ***************************************************************************/
/* VEC_CFG :: RAM_TEST_CTRL_IT_0 :: reserved0 [31:04] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0_reserved0_MASK             0xfffffff0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0_reserved0_SHIFT            4

/* VEC_CFG :: RAM_TEST_CTRL_IT_0 :: TM [03:00] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0_TM_MASK                    0x0000000f
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0_TM_SHIFT                   0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_0_TM_DEFAULT                 0x00000000

/***************************************************************************
 *RAM_TEST_CTRL_IT_1 - RAM test control for IT_1 RAM
 ***************************************************************************/
/* VEC_CFG :: RAM_TEST_CTRL_IT_1 :: reserved0 [31:04] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1_reserved0_MASK             0xfffffff0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1_reserved0_SHIFT            4

/* VEC_CFG :: RAM_TEST_CTRL_IT_1 :: TM [03:00] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1_TM_MASK                    0x0000000f
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1_TM_SHIFT                   0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_IT_1_TM_DEFAULT                 0x00000000

/***************************************************************************
 *RAM_TEST_CTRL_DTRAM_0 - RAM test control for DTRAM_0 RAM
 ***************************************************************************/
/* VEC_CFG :: RAM_TEST_CTRL_DTRAM_0 :: reserved0 [31:04] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0_reserved0_MASK          0xfffffff0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0_reserved0_SHIFT         4

/* VEC_CFG :: RAM_TEST_CTRL_DTRAM_0 :: TM [03:00] */
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0_TM_MASK                 0x0000000f
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0_TM_SHIFT                0
#define BCHP_VEC_CFG_RAM_TEST_CTRL_DTRAM_0_TM_DEFAULT              0x00000000

/***************************************************************************
 *VF_0_SOURCE - Source Select Register for VF_0
 ***************************************************************************/
/* VEC_CFG :: VF_0_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_VF_0_SOURCE_reserved0_MASK                    0xfffffffc
#define BCHP_VEC_CFG_VF_0_SOURCE_reserved0_SHIFT                   2

/* VEC_CFG :: VF_0_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_MASK                       0x00000003
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_SHIFT                      0
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_DEFAULT                    0x00000002
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_IT_0                       0
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_IT_1                       1
#define BCHP_VEC_CFG_VF_0_SOURCE_SOURCE_DISABLE                    2

/***************************************************************************
 *VF_1_SOURCE - Source Select Register for VF_1
 ***************************************************************************/
/* VEC_CFG :: VF_1_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_VF_1_SOURCE_reserved0_MASK                    0xfffffffc
#define BCHP_VEC_CFG_VF_1_SOURCE_reserved0_SHIFT                   2

/* VEC_CFG :: VF_1_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_MASK                       0x00000003
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_SHIFT                      0
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_DEFAULT                    0x00000002
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_IT_0                       0
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_IT_1                       1
#define BCHP_VEC_CFG_VF_1_SOURCE_SOURCE_DISABLE                    2

/***************************************************************************
 *SECAM_0_SOURCE - Source Select Register for SECAM_0
 ***************************************************************************/
/* VEC_CFG :: SECAM_0_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_SECAM_0_SOURCE_reserved0_MASK                 0xfffffffc
#define BCHP_VEC_CFG_SECAM_0_SOURCE_reserved0_SHIFT                2

/* VEC_CFG :: SECAM_0_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_MASK                    0x00000003
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_DEFAULT                 0x00000002
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_VF_0                    0
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_VF_1                    1
#define BCHP_VEC_CFG_SECAM_0_SOURCE_SOURCE_DISABLE                 2

/***************************************************************************
 *SECAM_1_SOURCE - Source Select Register for SECAM_1
 ***************************************************************************/
/* VEC_CFG :: SECAM_1_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_SECAM_1_SOURCE_reserved0_MASK                 0xfffffffc
#define BCHP_VEC_CFG_SECAM_1_SOURCE_reserved0_SHIFT                2

/* VEC_CFG :: SECAM_1_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_MASK                    0x00000003
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_DEFAULT                 0x00000002
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_VF_0                    0
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_VF_1                    1
#define BCHP_VEC_CFG_SECAM_1_SOURCE_SOURCE_DISABLE                 2

/***************************************************************************
 *SECAM_2_SOURCE - Source Select Register for SECAM_2
 ***************************************************************************/
/* VEC_CFG :: SECAM_2_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_SECAM_2_SOURCE_reserved0_MASK                 0xfffffffc
#define BCHP_VEC_CFG_SECAM_2_SOURCE_reserved0_SHIFT                2

/* VEC_CFG :: SECAM_2_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_MASK                    0x00000003
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_DEFAULT                 0x00000002
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_VF_0                    0
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_VF_1                    1
#define BCHP_VEC_CFG_SECAM_2_SOURCE_SOURCE_DISABLE                 2

/***************************************************************************
 *SDSRC_0_SOURCE - Source Select Register for SDSRC_0
 ***************************************************************************/
/* VEC_CFG :: SDSRC_0_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_reserved0_MASK                 0xfffffffc
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_reserved0_SHIFT                2

/* VEC_CFG :: SDSRC_0_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_MASK                    0x00000003
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_DEFAULT                 0x00000003
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_SSP_0                   0
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_SSP_1                   1
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_SSP_2                   2
#define BCHP_VEC_CFG_SDSRC_0_SOURCE_SOURCE_DISABLE                 3

/***************************************************************************
 *HDSRC_0_SOURCE - Source Select Register for HDSRC_0
 ***************************************************************************/
/* VEC_CFG :: HDSRC_0_SOURCE :: reserved0 [31:02] */
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_reserved0_MASK                 0xfffffffc
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_reserved0_SHIFT                2

/* VEC_CFG :: HDSRC_0_SOURCE :: SOURCE [01:00] */
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_MASK                    0x00000003
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_DEFAULT                 0x00000003
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_SSP_0                   0
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_SSP_1                   1
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_SSP_2                   2
#define BCHP_VEC_CFG_HDSRC_0_SOURCE_SOURCE_DISABLE                 3

/***************************************************************************
 *IT_0_SOURCE - Source Select Register for IT_0
 ***************************************************************************/
/* VEC_CFG :: IT_0_SOURCE :: reserved0 [31:03] */
#define BCHP_VEC_CFG_IT_0_SOURCE_reserved0_MASK                    0xfffffff8
#define BCHP_VEC_CFG_IT_0_SOURCE_reserved0_SHIFT                   3

/* VEC_CFG :: IT_0_SOURCE :: SOURCE [02:00] */
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_MASK                       0x00000007
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_SHIFT                      0
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_DEFAULT                    0x00000004
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_S_0                        0
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_S_1                        1
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_DECIM_0                    2
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_TPG_0                      3
#define BCHP_VEC_CFG_IT_0_SOURCE_SOURCE_DISABLE                    4

/***************************************************************************
 *IT_1_SOURCE - Source Select Register for IT_1
 ***************************************************************************/
/* VEC_CFG :: IT_1_SOURCE :: reserved0 [31:03] */
#define BCHP_VEC_CFG_IT_1_SOURCE_reserved0_MASK                    0xfffffff8
#define BCHP_VEC_CFG_IT_1_SOURCE_reserved0_SHIFT                   3

/* VEC_CFG :: IT_1_SOURCE :: SOURCE [02:00] */
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_MASK                       0x00000007
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_SHIFT                      0
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_DEFAULT                    0x00000004
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_S_0                        0
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_S_1                        1
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_DECIM_0                    2
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_TPG_0                      3
#define BCHP_VEC_CFG_IT_1_SOURCE_SOURCE_DISABLE                    4

/***************************************************************************
 *DVI_DTG_0_SOURCE - Source Select Register for DVI_DTG_0
 ***************************************************************************/
/* VEC_CFG :: DVI_DTG_0_SOURCE :: reserved0 [31:03] */
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_reserved0_MASK               0xfffffff8
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_reserved0_SHIFT              3

/* VEC_CFG :: DVI_DTG_0_SOURCE :: SOURCE [02:00] */
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_MASK                  0x00000007
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_SHIFT                 0
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_DEFAULT               0x00000004
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_S_0                   0
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_S_1                   1
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_DECIM_0               2
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_TPG_0                 3
#define BCHP_VEC_CFG_DVI_DTG_0_SOURCE_SOURCE_DISABLE               4

/***************************************************************************
 *ITU656_DTG_0_SOURCE - Source Select Register for ITU656_DTG_0
 ***************************************************************************/
/* VEC_CFG :: ITU656_DTG_0_SOURCE :: reserved0 [31:03] */
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_reserved0_MASK            0xfffffff8
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_reserved0_SHIFT           3

/* VEC_CFG :: ITU656_DTG_0_SOURCE :: SOURCE [02:00] */
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_MASK               0x00000007
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_SHIFT              0
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_DEFAULT            0x00000004
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_S_0                0
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_S_1                1
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_DECIM_0            2
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_TPG_0              3
#define BCHP_VEC_CFG_ITU656_DTG_0_SOURCE_SOURCE_DISABLE            4

/***************************************************************************
 *DECIM_0_SOURCE - Source Select Register for DECIM_0
 ***************************************************************************/
/* VEC_CFG :: DECIM_0_SOURCE :: reserved0 [31:03] */
#define BCHP_VEC_CFG_DECIM_0_SOURCE_reserved0_MASK                 0xfffffff8
#define BCHP_VEC_CFG_DECIM_0_SOURCE_reserved0_SHIFT                3

/* VEC_CFG :: DECIM_0_SOURCE :: SOURCE [02:00] */
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_MASK                    0x00000007
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_SHIFT                   0
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_DEFAULT                 0x00000004
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_S_0                     0
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_S_1                     1
#define BCHP_VEC_CFG_DECIM_0_SOURCE_SOURCE_DISABLE                 4

/***************************************************************************
 *SW_INIT_IT_0 - Software Init register for IT_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_IT_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_IT_0_reserved0_MASK                   0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_IT_0_reserved0_SHIFT                  1

/* VEC_CFG :: SW_INIT_IT_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_IT_0_INIT_MASK                        0x00000001
#define BCHP_VEC_CFG_SW_INIT_IT_0_INIT_SHIFT                       0
#define BCHP_VEC_CFG_SW_INIT_IT_0_INIT_DEFAULT                     0x00000000

/***************************************************************************
 *SW_INIT_IT_1 - Software Init register for IT_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_IT_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_IT_1_reserved0_MASK                   0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_IT_1_reserved0_SHIFT                  1

/* VEC_CFG :: SW_INIT_IT_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_IT_1_INIT_MASK                        0x00000001
#define BCHP_VEC_CFG_SW_INIT_IT_1_INIT_SHIFT                       0
#define BCHP_VEC_CFG_SW_INIT_IT_1_INIT_DEFAULT                     0x00000000

/***************************************************************************
 *SW_INIT_VF_0 - Software Init register for VF_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_VF_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_VF_0_reserved0_MASK                   0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_VF_0_reserved0_SHIFT                  1

/* VEC_CFG :: SW_INIT_VF_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_VF_0_INIT_MASK                        0x00000001
#define BCHP_VEC_CFG_SW_INIT_VF_0_INIT_SHIFT                       0
#define BCHP_VEC_CFG_SW_INIT_VF_0_INIT_DEFAULT                     0x00000000

/***************************************************************************
 *SW_INIT_VF_1 - Software Init register for VF_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_VF_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_VF_1_reserved0_MASK                   0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_VF_1_reserved0_SHIFT                  1

/* VEC_CFG :: SW_INIT_VF_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_VF_1_INIT_MASK                        0x00000001
#define BCHP_VEC_CFG_SW_INIT_VF_1_INIT_SHIFT                       0
#define BCHP_VEC_CFG_SW_INIT_VF_1_INIT_DEFAULT                     0x00000000

/***************************************************************************
 *SW_INIT_SECAM_0 - Software Init register for SECAM_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_SECAM_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_SECAM_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_SECAM_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_SECAM_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_SECAM_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_SECAM_1 - Software Init register for SECAM_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_SECAM_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_1_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_SECAM_1_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_SECAM_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_1_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_SECAM_1_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_SECAM_1_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_SECAM_2 - Software Init register for SECAM_2
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_SECAM_2 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_2_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_SECAM_2_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_SECAM_2 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_SECAM_2_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_SECAM_2_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_SECAM_2_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_SDSRC_0 - Software Init register for SDSRC_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_SDSRC_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_SDSRC_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_SDSRC_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_HDSRC_0 - Software Init register for HDSRC_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_HDSRC_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_HDSRC_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_HDSRC_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_ANA_MISC - Software Init register for ANA_MISC
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ANA_MISC :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC_reserved0_MASK               0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC_reserved0_SHIFT              1

/* VEC_CFG :: SW_INIT_ANA_MISC :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC_INIT_MASK                    0x00000001
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC_INIT_SHIFT                   0
#define BCHP_VEC_CFG_SW_INIT_ANA_MISC_INIT_DEFAULT                 0x00000000

/***************************************************************************
 *SW_INIT_DTRAM_0 - Software Init register for DTRAM_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DTRAM_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_DTRAM_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_DTRAM_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_VEC_MISC - Software Init register for VEC MISC
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_VEC_MISC :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC_reserved0_MASK               0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC_reserved0_SHIFT              1

/* VEC_CFG :: SW_INIT_VEC_MISC :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC_INIT_MASK                    0x00000001
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC_INIT_SHIFT                   0
#define BCHP_VEC_CFG_SW_INIT_VEC_MISC_INIT_DEFAULT                 0x00000000

/***************************************************************************
 *SW_INIT_TPG_0 - Software Init register for TPG_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_TPG_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_TPG_0_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_TPG_0_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_TPG_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_TPG_0_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_TPG_0_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_TPG_0_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_MISC - Software Init register for MISC
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_MISC :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_MISC_reserved0_MASK                   0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_MISC_reserved0_SHIFT                  1

/* VEC_CFG :: SW_INIT_MISC :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_MISC_INIT_MASK                        0x00000001
#define BCHP_VEC_CFG_SW_INIT_MISC_INIT_SHIFT                       0
#define BCHP_VEC_CFG_SW_INIT_MISC_INIT_DEFAULT                     0x00000000

/***************************************************************************
 *SW_INIT_DECIM_0 - Software Init register for DECIM_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DECIM_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DECIM_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DECIM_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_DECIM_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DECIM_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_DECIM_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_DECIM_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_CABLE_DETECT_0 - Software Init register for CABLE_DETECT_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CABLE_DETECT_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0_reserved0_MASK         0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0_reserved0_SHIFT        1

/* VEC_CFG :: SW_INIT_CABLE_DETECT_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0_INIT_MASK              0x00000001
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0_INIT_SHIFT             0
#define BCHP_VEC_CFG_SW_INIT_CABLE_DETECT_0_INIT_DEFAULT           0x00000000

/***************************************************************************
 *SW_INIT_DVI_DTG_0 - Software Init register for DVI DTG_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DVI_DTG_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0_reserved0_MASK              0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0_reserved0_SHIFT             1

/* VEC_CFG :: SW_INIT_DVI_DTG_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0_INIT_MASK                   0x00000001
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0_INIT_SHIFT                  0
#define BCHP_VEC_CFG_SW_INIT_DVI_DTG_0_INIT_DEFAULT                0x00000000

/***************************************************************************
 *SW_INIT_DVI_CSC_0 - Software Init register for DVI CSC_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DVI_CSC_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0_reserved0_MASK              0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0_reserved0_SHIFT             1

/* VEC_CFG :: SW_INIT_DVI_CSC_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0_INIT_MASK                   0x00000001
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0_INIT_SHIFT                  0
#define BCHP_VEC_CFG_SW_INIT_DVI_CSC_0_INIT_DEFAULT                0x00000000

/***************************************************************************
 *SW_INIT_DVI_DVF_0 - Software Init register for DVI DVF_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DVI_DVF_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0_reserved0_MASK              0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0_reserved0_SHIFT             1

/* VEC_CFG :: SW_INIT_DVI_DVF_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0_INIT_MASK                   0x00000001
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0_INIT_SHIFT                  0
#define BCHP_VEC_CFG_SW_INIT_DVI_DVF_0_INIT_DEFAULT                0x00000000

/***************************************************************************
 *SW_INIT_DVI_MISC_0 - Software Init register for DVI MISC_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_DVI_MISC_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0_reserved0_MASK             0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0_reserved0_SHIFT            1

/* VEC_CFG :: SW_INIT_DVI_MISC_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0_INIT_MASK                  0x00000001
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0_INIT_SHIFT                 0
#define BCHP_VEC_CFG_SW_INIT_DVI_MISC_0_INIT_DEFAULT               0x00000000

/***************************************************************************
 *SW_INIT_ITU656_DTG_0 - Software Init register for ITU656 DTG_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ITU656_DTG_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0_reserved0_MASK           0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0_reserved0_SHIFT          1

/* VEC_CFG :: SW_INIT_ITU656_DTG_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0_INIT_MASK                0x00000001
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0_INIT_SHIFT               0
#define BCHP_VEC_CFG_SW_INIT_ITU656_DTG_0_INIT_DEFAULT             0x00000000

/***************************************************************************
 *SW_INIT_ITU656_CSC_0 - Software Init register for 656 CSC_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ITU656_CSC_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0_reserved0_MASK           0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0_reserved0_SHIFT          1

/* VEC_CFG :: SW_INIT_ITU656_CSC_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0_INIT_MASK                0x00000001
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0_INIT_SHIFT               0
#define BCHP_VEC_CFG_SW_INIT_ITU656_CSC_0_INIT_DEFAULT             0x00000000

/***************************************************************************
 *SW_INIT_ITU656_DVF_0 - Software Init register for 656 DVF_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ITU656_DVF_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0_reserved0_MASK           0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0_reserved0_SHIFT          1

/* VEC_CFG :: SW_INIT_ITU656_DVF_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0_INIT_MASK                0x00000001
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0_INIT_SHIFT               0
#define BCHP_VEC_CFG_SW_INIT_ITU656_DVF_0_INIT_DEFAULT             0x00000000

/***************************************************************************
 *SW_INIT_ITU656_FORMATTER_0 - Software Init register for 656 Formatter 0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ITU656_FORMATTER_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0_reserved0_MASK     0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0_reserved0_SHIFT    1

/* VEC_CFG :: SW_INIT_ITU656_FORMATTER_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0_INIT_MASK          0x00000001
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0_INIT_SHIFT         0
#define BCHP_VEC_CFG_SW_INIT_ITU656_FORMATTER_0_INIT_DEFAULT       0x00000000

/***************************************************************************
 *SW_INIT_CCE_0 - Software Init register for CCE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CCE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CCE_0_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CCE_0_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_CCE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CCE_0_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_CCE_0_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_CCE_0_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_CCE_1 - Software Init register for CCE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CCE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CCE_1_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CCE_1_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_CCE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CCE_1_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_CCE_1_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_CCE_1_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_WSE_0 - Software Init register for WSE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_WSE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_WSE_0_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_WSE_0_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_WSE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_WSE_0_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_WSE_0_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_WSE_0_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_WSE_1 - Software Init register for WSE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_WSE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_WSE_1_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_WSE_1_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_WSE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_WSE_1_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_WSE_1_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_WSE_1_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_CGMSAE_0 - Software Init register for CGMSAE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CGMSAE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0_reserved0_MASK               0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0_reserved0_SHIFT              1

/* VEC_CFG :: SW_INIT_CGMSAE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0_INIT_MASK                    0x00000001
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0_INIT_SHIFT                   0
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_0_INIT_DEFAULT                 0x00000000

/***************************************************************************
 *SW_INIT_CGMSAE_1 - Software Init register for CGMSAE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CGMSAE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1_reserved0_MASK               0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1_reserved0_SHIFT              1

/* VEC_CFG :: SW_INIT_CGMSAE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1_INIT_MASK                    0x00000001
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1_INIT_SHIFT                   0
#define BCHP_VEC_CFG_SW_INIT_CGMSAE_1_INIT_DEFAULT                 0x00000000

/***************************************************************************
 *SW_INIT_TTE_0 - Software Init register for TTE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_TTE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_TTE_0_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_TTE_0_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_TTE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_TTE_0_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_TTE_0_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_TTE_0_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_TTE_1 - Software Init register for TTE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_TTE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_TTE_1_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_TTE_1_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_TTE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_TTE_1_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_TTE_1_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_TTE_1_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_GSE_0 - Software Init register for GSE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_GSE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_GSE_0_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_GSE_0_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_GSE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_GSE_0_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_GSE_0_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_GSE_0_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_GSE_1 - Software Init register for GSE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_GSE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_GSE_1_reserved0_MASK                  0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_GSE_1_reserved0_SHIFT                 1

/* VEC_CFG :: SW_INIT_GSE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_GSE_1_INIT_MASK                       0x00000001
#define BCHP_VEC_CFG_SW_INIT_GSE_1_INIT_SHIFT                      0
#define BCHP_VEC_CFG_SW_INIT_GSE_1_INIT_DEFAULT                    0x00000000

/***************************************************************************
 *SW_INIT_AMOLE_0 - Software Init register for AMOLE_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_AMOLE_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_AMOLE_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_AMOLE_0_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_AMOLE_1 - Software Init register for AMOLE_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_AMOLE_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1_reserved0_MASK                0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1_reserved0_SHIFT               1

/* VEC_CFG :: SW_INIT_AMOLE_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1_INIT_MASK                     0x00000001
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1_INIT_SHIFT                    0
#define BCHP_VEC_CFG_SW_INIT_AMOLE_1_INIT_DEFAULT                  0x00000000

/***************************************************************************
 *SW_INIT_PASSTHRU_0 - Software Init register for PASSTHRU_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_PASSTHRU_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0_reserved0_MASK             0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0_reserved0_SHIFT            1

/* VEC_CFG :: SW_INIT_PASSTHRU_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0_INIT_MASK                  0x00000001
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0_INIT_SHIFT                 0
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_0_INIT_DEFAULT               0x00000000

/***************************************************************************
 *SW_INIT_PASSTHRU_1 - Software Init register for PASSTHRU_1
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_PASSTHRU_1 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1_reserved0_MASK             0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1_reserved0_SHIFT            1

/* VEC_CFG :: SW_INIT_PASSTHRU_1 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1_INIT_MASK                  0x00000001
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1_INIT_SHIFT                 0
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_1_INIT_DEFAULT               0x00000000

/***************************************************************************
 *SW_INIT_CCE_ANCIL_0 - Software Init register for CCE_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_CCE_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0_reserved0_MASK            0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0_reserved0_SHIFT           1

/* VEC_CFG :: SW_INIT_CCE_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0_INIT_MASK                 0x00000001
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0_INIT_SHIFT                0
#define BCHP_VEC_CFG_SW_INIT_CCE_ANCIL_0_INIT_DEFAULT              0x00000000

/***************************************************************************
 *SW_INIT_WSE_ANCIL_0 - Software Init register for WSE_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_WSE_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0_reserved0_MASK            0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0_reserved0_SHIFT           1

/* VEC_CFG :: SW_INIT_WSE_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0_INIT_MASK                 0x00000001
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0_INIT_SHIFT                0
#define BCHP_VEC_CFG_SW_INIT_WSE_ANCIL_0_INIT_DEFAULT              0x00000000

/***************************************************************************
 *SW_INIT_TTE_ANCIL_0 - Software Init register for TTE_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_TTE_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0_reserved0_MASK            0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0_reserved0_SHIFT           1

/* VEC_CFG :: SW_INIT_TTE_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0_INIT_MASK                 0x00000001
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0_INIT_SHIFT                0
#define BCHP_VEC_CFG_SW_INIT_TTE_ANCIL_0_INIT_DEFAULT              0x00000000

/***************************************************************************
 *SW_INIT_GSE_ANCIL_0 - Software Init register for GSE_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_GSE_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0_reserved0_MASK            0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0_reserved0_SHIFT           1

/* VEC_CFG :: SW_INIT_GSE_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0_INIT_MASK                 0x00000001
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0_INIT_SHIFT                0
#define BCHP_VEC_CFG_SW_INIT_GSE_ANCIL_0_INIT_DEFAULT              0x00000000

/***************************************************************************
 *SW_INIT_AMOLE_ANCIL_0 - Software Init register for AMOLE_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_AMOLE_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0_reserved0_MASK          0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0_reserved0_SHIFT         1

/* VEC_CFG :: SW_INIT_AMOLE_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0_INIT_MASK               0x00000001
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0_INIT_SHIFT              0
#define BCHP_VEC_CFG_SW_INIT_AMOLE_ANCIL_0_INIT_DEFAULT            0x00000000

/***************************************************************************
 *SW_INIT_ANCI656_ANCIL_0 - Software Init register for ANCI656_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_ANCI656_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0_reserved0_MASK        0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0_reserved0_SHIFT       1

/* VEC_CFG :: SW_INIT_ANCI656_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0_INIT_MASK             0x00000001
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0_INIT_SHIFT            0
#define BCHP_VEC_CFG_SW_INIT_ANCI656_ANCIL_0_INIT_DEFAULT          0x00000000

/***************************************************************************
 *SW_INIT_PASSTHRU_ANCIL_0 - Software Init register for PASSTHRU_ANCIL_0
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_PASSTHRU_ANCIL_0 :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0_reserved0_MASK       0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0_reserved0_SHIFT      1

/* VEC_CFG :: SW_INIT_PASSTHRU_ANCIL_0 :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0_INIT_MASK            0x00000001
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0_INIT_SHIFT           0
#define BCHP_VEC_CFG_SW_INIT_PASSTHRU_ANCIL_0_INIT_DEFAULT         0x00000000

/***************************************************************************
 *SW_INIT_VBI_MISC - Software Init register for VBI_MISC
 ***************************************************************************/
/* VEC_CFG :: SW_INIT_VBI_MISC :: reserved0 [31:01] */
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC_reserved0_MASK               0xfffffffe
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC_reserved0_SHIFT              1

/* VEC_CFG :: SW_INIT_VBI_MISC :: INIT [00:00] */
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC_INIT_MASK                    0x00000001
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC_INIT_SHIFT                   0
#define BCHP_VEC_CFG_SW_INIT_VBI_MISC_INIT_DEFAULT                 0x00000000

#endif /* #ifndef BCHP_VEC_CFG_H__ */

/* End of File */
