/***************************************************************************
 *     Copyright (c) 1999-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Apr 22 17:20:06 2010
 *                 MD5 Checksum         e645cb91be669b614b9400e5da71f4fa
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_AVLINK_HOST_H__
#define BCHP_AVLINK_HOST_H__

/***************************************************************************
 *AVLINK_HOST - AVLINK HOST Registers
 ***************************************************************************/
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR       0x0048a0b4 /* Asynchronous Transmit Response DMA Quadlet Header Pointer Register */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS 0x0048a0b8 /* Asynchronous Transmit Response DMA Control and Status Register */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_DATA_PTR    0x0048a0bc /* Asynchronous Transmit Response DMA Data Pointer Register */
#define BCHP_AVLINK_HOST_AV_PATH_SEL             0x0048a0c0 /* AV Path Select Register */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE            0x0048a0c4 /* AV Path Size Register */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR        0x0048a0c8 /* Asynchronous Transmit Request DMA Quadlet Header Pointer Register */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS  0x0048a0cc /* Asynchronous Transmit Request DMA Control and Status Register */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_DATA_PTR     0x0048a0d0 /* Asynchronous Transmit Request DMA Data Pointer Register */
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR            0x0048a0d4 /* Asynchronous Receive DMA Quadlet Header Pointer Register */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS      0x0048a0d8 /* Asynchronous Receive DMA Control and Status Register */
#define BCHP_AVLINK_HOST_AR_DMA_DATA_PTR         0x0048a0dc /* Asynchronous Receive DMA Data Pointer Register */
#define BCHP_AVLINK_HOST_AR_FIFO_STATUS          0x0048a0e0 /* Asynchronous Receive FIFO Status Register */
#define BCHP_AVLINK_HOST_IR_FIFO_STATUS          0x0048a0e4 /* Isochronous Receive FIFO Status Register */
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR            0x0048a0e8 /* Isochronous Transmit DMA Quadlet Header Pointer Register */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS      0x0048a0ec /* Isochronous Transmit DMA Control and Status Register */
#define BCHP_AVLINK_HOST_IT_DMA_DATA_PTR         0x0048a0f0 /* Isochronous Transmit DMA Data Pointer Register */
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR            0x0048a0f4 /* Isochronous Receive DMA Quadlet Header Pointer Register */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS      0x0048a0f8 /* Isochronous Receive DMA Control and Status Register */
#define BCHP_AVLINK_HOST_IR_DMA_DATA_PTR         0x0048a0fc /* Isochronous Receive DMA Data Pointer Register */

/***************************************************************************
 *AT_RESP_DMA_QHPTR - Asynchronous Transmit Response DMA Quadlet Header Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_RESP_DMA_QHPTR :: DMA_QHPtr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_DMA_QHPtr_Addr_MASK     0xfffffffc
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_DMA_QHPtr_Addr_SHIFT    2

/* AVLINK_HOST :: AT_RESP_DMA_QHPTR :: reserved0 [01:01] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_reserved0_MASK          0x00000002
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_reserved0_SHIFT         1

/* AVLINK_HOST :: AT_RESP_DMA_QHPTR :: DMA_QHPtr_Addr_Valid [00:00] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_DMA_QHPtr_Addr_Valid_MASK 0x00000001
#define BCHP_AVLINK_HOST_AT_RESP_DMA_QHPTR_DMA_QHPtr_Addr_Valid_SHIFT 0

/***************************************************************************
 *AT_RESP_DMA_CTRL_STATUS - Asynchronous Transmit Response DMA Control and Status Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: Dma_Wake [31:31] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_Dma_Wake_MASK     0x80000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_Dma_Wake_SHIFT    31

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: DMA_Dead [30:30] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Dead_MASK     0x40000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Dead_SHIFT    30

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: DMA_Halted [29:29] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Halted_MASK   0x20000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Halted_SHIFT  29

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: DMA_Event_Code [28:26] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Event_Code_MASK 0x1c000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Event_Code_SHIFT 26

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: DMA_Run [25:25] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Run_MASK      0x02000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Run_SHIFT     25

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: DMA_Reset [24:24] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Reset_MASK    0x01000000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_DMA_Reset_SHIFT   24

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: data_Buffer_Size [23:12] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_data_Buffer_Size_MASK 0x00fff000
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_data_Buffer_Size_SHIFT 12

/* AVLINK_HOST :: AT_RESP_DMA_CTRL_STATUS :: res_Count [11:00] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_res_Count_MASK    0x00000fff
#define BCHP_AVLINK_HOST_AT_RESP_DMA_CTRL_STATUS_res_Count_SHIFT   0

/***************************************************************************
 *AT_RESP_DMA_DATA_PTR - Asynchronous Transmit Response DMA Data Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_RESP_DMA_DATA_PTR :: data_Buffer_Ptr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_DATA_PTR_data_Buffer_Ptr_Addr_MASK 0xfffffffc
#define BCHP_AVLINK_HOST_AT_RESP_DMA_DATA_PTR_data_Buffer_Ptr_Addr_SHIFT 2

/* AVLINK_HOST :: AT_RESP_DMA_DATA_PTR :: reserved0 [01:00] */
#define BCHP_AVLINK_HOST_AT_RESP_DMA_DATA_PTR_reserved0_MASK       0x00000003
#define BCHP_AVLINK_HOST_AT_RESP_DMA_DATA_PTR_reserved0_SHIFT      0

/***************************************************************************
 *AV_PATH_SEL - AV Path Select Register
 ***************************************************************************/
/* AVLINK_HOST :: AV_PATH_SEL :: reserved0 [31:09] */
#define BCHP_AVLINK_HOST_AV_PATH_SEL_reserved0_MASK                0xfffffe00
#define BCHP_AVLINK_HOST_AV_PATH_SEL_reserved0_SHIFT               9

/* AVLINK_HOST :: AV_PATH_SEL :: deb_Path_Sel [08:05] */
#define BCHP_AVLINK_HOST_AV_PATH_SEL_deb_Path_Sel_MASK             0x000001e0
#define BCHP_AVLINK_HOST_AV_PATH_SEL_deb_Path_Sel_SHIFT            5

/* AVLINK_HOST :: AV_PATH_SEL :: av_RMX_Sel_Tx [04:04] */
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_RMX_Sel_Tx_MASK            0x00000010
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_RMX_Sel_Tx_SHIFT           4

/* AVLINK_HOST :: AV_PATH_SEL :: av_Path_Num [03:01] */
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_Path_Num_MASK              0x0000000e
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_Path_Num_SHIFT             1

/* AVLINK_HOST :: AV_PATH_SEL :: av_Rx_Sel [00:00] */
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_Rx_Sel_MASK                0x00000001
#define BCHP_AVLINK_HOST_AV_PATH_SEL_av_Rx_Sel_SHIFT               0

/***************************************************************************
 *AV_PATH_SIZE - AV Path Size Register
 ***************************************************************************/
/* AVLINK_HOST :: AV_PATH_SIZE :: reserved0 [31:16] */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_reserved0_MASK               0xffff0000
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_reserved0_SHIFT              16

/* AVLINK_HOST :: AV_PATH_SIZE :: Av_Rx_Path_Valid [15:12] */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Rx_Path_Valid_MASK        0x0000f000
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Rx_Path_Valid_SHIFT       12

/* AVLINK_HOST :: AV_PATH_SIZE :: Av_Rx_Path_Max [11:08] */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Rx_Path_Max_MASK          0x00000f00
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Rx_Path_Max_SHIFT         8

/* AVLINK_HOST :: AV_PATH_SIZE :: Av_Tx_Path_Valid [07:04] */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Tx_Path_Valid_MASK        0x000000f0
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Tx_Path_Valid_SHIFT       4

/* AVLINK_HOST :: AV_PATH_SIZE :: Av_Tx_Path_Max [03:00] */
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Tx_Path_Max_MASK          0x0000000f
#define BCHP_AVLINK_HOST_AV_PATH_SIZE_Av_Tx_Path_Max_SHIFT         0

/***************************************************************************
 *AT_REQ_DMA_QHPTR - Asynchronous Transmit Request DMA Quadlet Header Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_REQ_DMA_QHPTR :: DMA_QHPtr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_DMA_QHPtr_Addr_MASK      0xfffffffc
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_DMA_QHPtr_Addr_SHIFT     2

/* AVLINK_HOST :: AT_REQ_DMA_QHPTR :: reserved0 [01:01] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_reserved0_MASK           0x00000002
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_reserved0_SHIFT          1

/* AVLINK_HOST :: AT_REQ_DMA_QHPTR :: DMA_QHPtr_Addr_Valid [00:00] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_DMA_QHPtr_Addr_Valid_MASK 0x00000001
#define BCHP_AVLINK_HOST_AT_REQ_DMA_QHPTR_DMA_QHPtr_Addr_Valid_SHIFT 0

/***************************************************************************
 *AT_REQ_DMA_CTRL_STATUS - Asynchronous Transmit Request DMA Control and Status Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: Dma_Wake [31:31] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_Dma_Wake_MASK      0x80000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_Dma_Wake_SHIFT     31

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: DMA_Dead [30:30] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Dead_MASK      0x40000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Dead_SHIFT     30

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: DMA_Halted [29:29] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Halted_MASK    0x20000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Halted_SHIFT   29

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: DMA_Event_Code [28:26] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Event_Code_MASK 0x1c000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Event_Code_SHIFT 26

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: DMA_Run [25:25] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Run_MASK       0x02000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Run_SHIFT      25

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: DMA_Reset [24:24] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Reset_MASK     0x01000000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_DMA_Reset_SHIFT    24

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: data_Buffer_Size [23:12] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_data_Buffer_Size_MASK 0x00fff000
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_data_Buffer_Size_SHIFT 12

/* AVLINK_HOST :: AT_REQ_DMA_CTRL_STATUS :: res_Count [11:00] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_res_Count_MASK     0x00000fff
#define BCHP_AVLINK_HOST_AT_REQ_DMA_CTRL_STATUS_res_Count_SHIFT    0

/***************************************************************************
 *AT_REQ_DMA_DATA_PTR - Asynchronous Transmit Request DMA Data Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AT_REQ_DMA_DATA_PTR :: data_Buffer_Ptr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_DATA_PTR_data_Buffer_Ptr_Addr_MASK 0xfffffffc
#define BCHP_AVLINK_HOST_AT_REQ_DMA_DATA_PTR_data_Buffer_Ptr_Addr_SHIFT 2

/* AVLINK_HOST :: AT_REQ_DMA_DATA_PTR :: reserved0 [01:00] */
#define BCHP_AVLINK_HOST_AT_REQ_DMA_DATA_PTR_reserved0_MASK        0x00000003
#define BCHP_AVLINK_HOST_AT_REQ_DMA_DATA_PTR_reserved0_SHIFT       0

/***************************************************************************
 *AR_DMA_QHPTR - Asynchronous Receive DMA Quadlet Header Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AR_DMA_QHPTR :: DMA_QHPtr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_DMA_QHPtr_Addr_MASK          0xfffffffc
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_DMA_QHPtr_Addr_SHIFT         2

/* AVLINK_HOST :: AR_DMA_QHPTR :: reserved0 [01:01] */
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_reserved0_MASK               0x00000002
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_reserved0_SHIFT              1

/* AVLINK_HOST :: AR_DMA_QHPTR :: DMA_QHPtr_Addr_Valid [00:00] */
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_DMA_QHPtr_Addr_Valid_MASK    0x00000001
#define BCHP_AVLINK_HOST_AR_DMA_QHPTR_DMA_QHPtr_Addr_Valid_SHIFT   0

/***************************************************************************
 *AR_DMA_CTRL_STATUS - Asynchronous Receive DMA Control and Status Register
 ***************************************************************************/
/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: Dma_Wake [31:31] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_Dma_Wake_MASK          0x80000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_Dma_Wake_SHIFT         31

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: DMA_Dead [30:30] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Dead_MASK          0x40000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Dead_SHIFT         30

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: DMA_Halted [29:29] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Halted_MASK        0x20000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Halted_SHIFT       29

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: DMA_Event_Code [28:26] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Event_Code_MASK    0x1c000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Event_Code_SHIFT   26

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: DMA_Run [25:25] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Run_MASK           0x02000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Run_SHIFT          25

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: DMA_Reset [24:24] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Reset_MASK         0x01000000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_DMA_Reset_SHIFT        24

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: data_Buffer_Size [23:12] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_data_Buffer_Size_MASK  0x00fff000
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_data_Buffer_Size_SHIFT 12

/* AVLINK_HOST :: AR_DMA_CTRL_STATUS :: res_Count [11:00] */
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_res_Count_MASK         0x00000fff
#define BCHP_AVLINK_HOST_AR_DMA_CTRL_STATUS_res_Count_SHIFT        0

/***************************************************************************
 *AR_DMA_DATA_PTR - Asynchronous Receive DMA Data Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: AR_DMA_DATA_PTR :: data_Buffer_Ptr_Addr [31:02] */
#define BCHP_AVLINK_HOST_AR_DMA_DATA_PTR_data_Buffer_Ptr_Addr_MASK 0xfffffffc
#define BCHP_AVLINK_HOST_AR_DMA_DATA_PTR_data_Buffer_Ptr_Addr_SHIFT 2

/* AVLINK_HOST :: AR_DMA_DATA_PTR :: reserved0 [01:00] */
#define BCHP_AVLINK_HOST_AR_DMA_DATA_PTR_reserved0_MASK            0x00000003
#define BCHP_AVLINK_HOST_AR_DMA_DATA_PTR_reserved0_SHIFT           0

/***************************************************************************
 *AR_FIFO_STATUS - Asynchronous Receive FIFO Status Register
 ***************************************************************************/
/* AVLINK_HOST :: AR_FIFO_STATUS :: reserved0 [31:10] */
#define BCHP_AVLINK_HOST_AR_FIFO_STATUS_reserved0_MASK             0xfffffc00
#define BCHP_AVLINK_HOST_AR_FIFO_STATUS_reserved0_SHIFT            10

/* AVLINK_HOST :: AR_FIFO_STATUS :: packet_Size [09:00] */
#define BCHP_AVLINK_HOST_AR_FIFO_STATUS_packet_Size_MASK           0x000003ff
#define BCHP_AVLINK_HOST_AR_FIFO_STATUS_packet_Size_SHIFT          0

/***************************************************************************
 *IR_FIFO_STATUS - Isochronous Receive FIFO Status Register
 ***************************************************************************/
/* AVLINK_HOST :: IR_FIFO_STATUS :: reserved0 [31:10] */
#define BCHP_AVLINK_HOST_IR_FIFO_STATUS_reserved0_MASK             0xfffffc00
#define BCHP_AVLINK_HOST_IR_FIFO_STATUS_reserved0_SHIFT            10

/* AVLINK_HOST :: IR_FIFO_STATUS :: packet_Size [09:00] */
#define BCHP_AVLINK_HOST_IR_FIFO_STATUS_packet_Size_MASK           0x000003ff
#define BCHP_AVLINK_HOST_IR_FIFO_STATUS_packet_Size_SHIFT          0

/***************************************************************************
 *IT_DMA_QHPTR - Isochronous Transmit DMA Quadlet Header Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: IT_DMA_QHPTR :: DMA_QHPtr_Addr [31:02] */
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_DMA_QHPtr_Addr_MASK          0xfffffffc
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_DMA_QHPtr_Addr_SHIFT         2

/* AVLINK_HOST :: IT_DMA_QHPTR :: reserved0 [01:01] */
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_reserved0_MASK               0x00000002
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_reserved0_SHIFT              1

/* AVLINK_HOST :: IT_DMA_QHPTR :: DMA_QHPtr_Addr_Valid [00:00] */
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_DMA_QHPtr_Addr_Valid_MASK    0x00000001
#define BCHP_AVLINK_HOST_IT_DMA_QHPTR_DMA_QHPtr_Addr_Valid_SHIFT   0

/***************************************************************************
 *IT_DMA_CTRL_STATUS - Isochronous Transmit DMA Control and Status Register
 ***************************************************************************/
/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: Dma_Wake [31:31] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_Dma_Wake_MASK          0x80000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_Dma_Wake_SHIFT         31

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: DMA_Dead [30:30] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Dead_MASK          0x40000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Dead_SHIFT         30

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: DMA_Halted [29:29] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Halted_MASK        0x20000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Halted_SHIFT       29

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: DMA_Event_Code [28:26] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Event_Code_MASK    0x1c000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Event_Code_SHIFT   26

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: DMA_Run [25:25] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Run_MASK           0x02000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Run_SHIFT          25

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: DMA_Reset [24:24] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Reset_MASK         0x01000000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_DMA_Reset_SHIFT        24

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: data_Buffer_Size [23:12] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_data_Buffer_Size_MASK  0x00fff000
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_data_Buffer_Size_SHIFT 12

/* AVLINK_HOST :: IT_DMA_CTRL_STATUS :: res_Count [11:00] */
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_res_Count_MASK         0x00000fff
#define BCHP_AVLINK_HOST_IT_DMA_CTRL_STATUS_res_Count_SHIFT        0

/***************************************************************************
 *IT_DMA_DATA_PTR - Isochronous Transmit DMA Data Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: IT_DMA_DATA_PTR :: data_Buffer_Ptr_Addr [31:02] */
#define BCHP_AVLINK_HOST_IT_DMA_DATA_PTR_data_Buffer_Ptr_Addr_MASK 0xfffffffc
#define BCHP_AVLINK_HOST_IT_DMA_DATA_PTR_data_Buffer_Ptr_Addr_SHIFT 2

/* AVLINK_HOST :: IT_DMA_DATA_PTR :: reserved0 [01:00] */
#define BCHP_AVLINK_HOST_IT_DMA_DATA_PTR_reserved0_MASK            0x00000003
#define BCHP_AVLINK_HOST_IT_DMA_DATA_PTR_reserved0_SHIFT           0

/***************************************************************************
 *IR_DMA_QHPTR - Isochronous Receive DMA Quadlet Header Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: IR_DMA_QHPTR :: DMA_QHPtr_Addr [31:02] */
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_DMA_QHPtr_Addr_MASK          0xfffffffc
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_DMA_QHPtr_Addr_SHIFT         2

/* AVLINK_HOST :: IR_DMA_QHPTR :: reserved0 [01:01] */
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_reserved0_MASK               0x00000002
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_reserved0_SHIFT              1

/* AVLINK_HOST :: IR_DMA_QHPTR :: DMA_QHPtr_Addr_Valid [00:00] */
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_DMA_QHPtr_Addr_Valid_MASK    0x00000001
#define BCHP_AVLINK_HOST_IR_DMA_QHPTR_DMA_QHPtr_Addr_Valid_SHIFT   0

/***************************************************************************
 *IR_DMA_CTRL_STATUS - Isochronous Receive DMA Control and Status Register
 ***************************************************************************/
/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: Dma_Wake [31:31] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_Dma_Wake_MASK          0x80000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_Dma_Wake_SHIFT         31

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: DMA_Dead [30:30] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Dead_MASK          0x40000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Dead_SHIFT         30

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: DMA_Halted [29:29] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Halted_MASK        0x20000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Halted_SHIFT       29

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: DMA_Event_Code [28:26] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Event_Code_MASK    0x1c000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Event_Code_SHIFT   26

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: DMA_Run [25:25] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Run_MASK           0x02000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Run_SHIFT          25

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: DMA_Reset [24:24] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Reset_MASK         0x01000000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_DMA_Reset_SHIFT        24

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: data_Buffer_Size [23:12] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_data_Buffer_Size_MASK  0x00fff000
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_data_Buffer_Size_SHIFT 12

/* AVLINK_HOST :: IR_DMA_CTRL_STATUS :: res_Count [11:00] */
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_res_Count_MASK         0x00000fff
#define BCHP_AVLINK_HOST_IR_DMA_CTRL_STATUS_res_Count_SHIFT        0

/***************************************************************************
 *IR_DMA_DATA_PTR - Isochronous Receive DMA Data Pointer Register
 ***************************************************************************/
/* AVLINK_HOST :: IR_DMA_DATA_PTR :: data_Buffer_Ptr_Addr [31:02] */
#define BCHP_AVLINK_HOST_IR_DMA_DATA_PTR_data_Buffer_Ptr_Addr_MASK 0xfffffffc
#define BCHP_AVLINK_HOST_IR_DMA_DATA_PTR_data_Buffer_Ptr_Addr_SHIFT 2

/* AVLINK_HOST :: IR_DMA_DATA_PTR :: reserved0 [01:00] */
#define BCHP_AVLINK_HOST_IR_DMA_DATA_PTR_reserved0_MASK            0x00000003
#define BCHP_AVLINK_HOST_IR_DMA_DATA_PTR_reserved0_SHIFT           0

#endif /* #ifndef BCHP_AVLINK_HOST_H__ */

/* End of File */
