/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Thu Mar 10 13:57:24 2016
 *                 Full Compile MD5 Checksum  628af85e282e26d7aa8cb3039beb3dda
 *                     (minus title and desc)
 *                 MD5 Checksum               4a24f3aa9cf80f1b639f46df03606df9
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     871
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/combo_header.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_ODS_FE_0_H__
#define BCHP_ODS_FE_0_H__

/***************************************************************************
 *ODS_FE_0 - ODS Frontend Registers
 ***************************************************************************/
#define BCHP_ODS_FE_0_FE                         0x04600600 /* [RW] Front End Control */
#define BCHP_ODS_FE_0_IMPE                       0x04600604 /* [RW] Impulse Erasure Control */
#define BCHP_ODS_FE_0_IMPE_ERASE                 0x04600608 /* [RW] Impulse Erasure Values */
#define BCHP_ODS_FE_0_IMPE_INST_THR              0x0460060c /* [RW] Impulse Erasure Instantaneous Threshold */
#define BCHP_ODS_FE_0_IMPE_MA_THR                0x04600610 /* [RW] Impulse Erasure Moving Average Threshold */
#define BCHP_ODS_FE_0_IMPE_ERASE_CNT             0x04600614 /* [RW] Impulse Erasure Count */
#define BCHP_ODS_FE_0_CL                         0x04600618 /* [RW] Carrier Loop Control */
#define BCHP_ODS_FE_0_CL_FCW                     0x0460061c /* [RW] Carrier Loop Frequency Control Word */
#define BCHP_ODS_FE_0_CL_COEF                    0x04600620 /* [RW] Carrier Loop Coefficients */
#define BCHP_ODS_FE_0_CL_FEST                    0x04600624 /* [RO] Carrier Loop Fractional Estimates */
#define BCHP_ODS_FE_0_CL_IEST                    0x04600628 /* [RO] Carrier Loop Integer Estimate */
#define BCHP_ODS_FE_0_CL_INT                     0x0460062c /* [RW] Carrier Loop Integrator */
#define BCHP_ODS_FE_0_CL_LFO                     0x04600630 /* [RO] Carrier Loop Filter Output */
#define BCHP_ODS_FE_0_CL_PA                      0x04600634 /* [RW] Carrier Loop Phase Accumulator */
#define BCHP_ODS_FE_0_TL_FCW                     0x04600638 /* [RW] Timing Loop Frequency Control Word */
#define BCHP_ODS_FE_0_TL_COEF                    0x0460063c /* [RW] Timing Loop Coefficients */
#define BCHP_ODS_FE_0_TL_LEAK_COEF               0x04600640 /* [RW] Timing Loop Coefficients */
#define BCHP_ODS_FE_0_TL_EST                     0x04600644 /* [RO] Timing Loop Estimate */
#define BCHP_ODS_FE_0_TL_INT                     0x04600648 /* [RW] Timing Loop Integrator */
#define BCHP_ODS_FE_0_TL_LFO                     0x0460064c /* [RO] Timing Loop Filter Output */
#define BCHP_ODS_FE_0_TL_NCO                     0x04600650 /* [RW] Timing Loop NCO */
#define BCHP_ODS_FE_0_DAGC                       0x04600654 /* [RW] Digital AGC2 Loop Control */
#define BCHP_ODS_FE_0_DAGC_INT                   0x04600658 /* [RW] Digital AGC2 Loop Filter Output */
#define BCHP_ODS_FE_0_DAGC_UPDATE                0x0460065c /* [RW] Digital AGC2 Loop Update Control */
#define BCHP_ODS_FE_0_NOTCH_CTL                  0x04600660 /* [RW] Notch Control */
#define BCHP_ODS_FE_0_NOTCH_WIDTH                0x04600664 /* [RW] Notch Width */
#define BCHP_ODS_FE_0_NOTCH_DEPTH                0x04600668 /* [RW] Notch Depth */
#define BCHP_ODS_FE_0_NOTCH0_FCW                 0x0460066c /* [RW] Notch0 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH1_FCW                 0x04600670 /* [RW] Notch1 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH2_FCW                 0x04600674 /* [RW] Notch2 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH3_FCW                 0x04600678 /* [RW] Notch3 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH4_FCW                 0x0460067c /* [RW] Notch4 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH5_FCW                 0x04600680 /* [RO] Notch5 Frequency Control Word */
#define BCHP_ODS_FE_0_NOTCH0_INT                 0x04600684 /* [RW] Notch0 Integrator */
#define BCHP_ODS_FE_0_NOTCH1_INT                 0x04600688 /* [RW] Notch1 Integrator */
#define BCHP_ODS_FE_0_NOTCH2_INT                 0x0460068c /* [RW] Notch2 Integrator */
#define BCHP_ODS_FE_0_NOTCH3_INT                 0x04600690 /* [RW] Notch3 Integrator */
#define BCHP_ODS_FE_0_NOTCH4_INT                 0x04600694 /* [RW] Notch4 Integrator */
#define BCHP_ODS_FE_0_ECO_SPARE0                 0x04600698 /* [RW] ECO Spare 0 Register */
#define BCHP_ODS_FE_0_ECO_SPARE1                 0x0460069c /* [RW] ECO Spare 1 Register */

/***************************************************************************
 *FE - Front End Control
 ***************************************************************************/
/* ODS_FE_0 :: FE :: reserved0 [31:09] */
#define BCHP_ODS_FE_0_FE_reserved0_MASK                            0xfffffe00
#define BCHP_ODS_FE_0_FE_reserved0_SHIFT                           9

/* ODS_FE_0 :: FE :: FIR2_COEF_SEL [08:08] */
#define BCHP_ODS_FE_0_FE_FIR2_COEF_SEL_MASK                        0x00000100
#define BCHP_ODS_FE_0_FE_FIR2_COEF_SEL_SHIFT                       8
#define BCHP_ODS_FE_0_FE_FIR2_COEF_SEL_DEFAULT                     0x00000000

/* ODS_FE_0 :: FE :: INPUT_CLKINV [07:07] */
#define BCHP_ODS_FE_0_FE_INPUT_CLKINV_MASK                         0x00000080
#define BCHP_ODS_FE_0_FE_INPUT_CLKINV_SHIFT                        7
#define BCHP_ODS_FE_0_FE_INPUT_CLKINV_DEFAULT                      0x00000000

/* ODS_FE_0 :: FE :: INPUT_ALIGN [06:05] */
#define BCHP_ODS_FE_0_FE_INPUT_ALIGN_MASK                          0x00000060
#define BCHP_ODS_FE_0_FE_INPUT_ALIGN_SHIFT                         5
#define BCHP_ODS_FE_0_FE_INPUT_ALIGN_DEFAULT                       0x00000000

/* ODS_FE_0 :: FE :: SWAP_IQ [04:04] */
#define BCHP_ODS_FE_0_FE_SWAP_IQ_MASK                              0x00000010
#define BCHP_ODS_FE_0_FE_SWAP_IQ_SHIFT                             4
#define BCHP_ODS_FE_0_FE_SWAP_IQ_DEFAULT                           0x00000000

/* ODS_FE_0 :: FE :: NEGATE_I [03:03] */
#define BCHP_ODS_FE_0_FE_NEGATE_I_MASK                             0x00000008
#define BCHP_ODS_FE_0_FE_NEGATE_I_SHIFT                            3
#define BCHP_ODS_FE_0_FE_NEGATE_I_DEFAULT                          0x00000000

/* ODS_FE_0 :: FE :: NEGATE_Q [02:02] */
#define BCHP_ODS_FE_0_FE_NEGATE_Q_MASK                             0x00000004
#define BCHP_ODS_FE_0_FE_NEGATE_Q_SHIFT                            2
#define BCHP_ODS_FE_0_FE_NEGATE_Q_DEFAULT                          0x00000000

/* ODS_FE_0 :: FE :: SPINV [01:01] */
#define BCHP_ODS_FE_0_FE_SPINV_MASK                                0x00000002
#define BCHP_ODS_FE_0_FE_SPINV_SHIFT                               1
#define BCHP_ODS_FE_0_FE_SPINV_DEFAULT                             0x00000000

/* ODS_FE_0 :: FE :: INPUT_EDGE [00:00] */
#define BCHP_ODS_FE_0_FE_INPUT_EDGE_MASK                           0x00000001
#define BCHP_ODS_FE_0_FE_INPUT_EDGE_SHIFT                          0
#define BCHP_ODS_FE_0_FE_INPUT_EDGE_DEFAULT                        0x00000000

/***************************************************************************
 *IMPE - Impulse Erasure Control
 ***************************************************************************/
/* ODS_FE_0 :: IMPE :: reserved0 [31:05] */
#define BCHP_ODS_FE_0_IMPE_reserved0_MASK                          0xffffffe0
#define BCHP_ODS_FE_0_IMPE_reserved0_SHIFT                         5

/* ODS_FE_0 :: IMPE :: PWRDN [04:04] */
#define BCHP_ODS_FE_0_IMPE_PWRDN_MASK                              0x00000010
#define BCHP_ODS_FE_0_IMPE_PWRDN_SHIFT                             4
#define BCHP_ODS_FE_0_IMPE_PWRDN_DEFAULT                           0x00000000

/* ODS_FE_0 :: IMPE :: reserved1 [03:03] */
#define BCHP_ODS_FE_0_IMPE_reserved1_MASK                          0x00000008
#define BCHP_ODS_FE_0_IMPE_reserved1_SHIFT                         3

/* ODS_FE_0 :: IMPE :: NSEL [02:00] */
#define BCHP_ODS_FE_0_IMPE_NSEL_MASK                               0x00000007
#define BCHP_ODS_FE_0_IMPE_NSEL_SHIFT                              0
#define BCHP_ODS_FE_0_IMPE_NSEL_DEFAULT                            0x00000000

/***************************************************************************
 *IMPE_ERASE - Impulse Erasure Values
 ***************************************************************************/
/* ODS_FE_0 :: IMPE_ERASE :: reserved0 [31:30] */
#define BCHP_ODS_FE_0_IMPE_ERASE_reserved0_MASK                    0xc0000000
#define BCHP_ODS_FE_0_IMPE_ERASE_reserved0_SHIFT                   30

/* ODS_FE_0 :: IMPE_ERASE :: VAL_I [29:16] */
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_I_MASK                        0x3fff0000
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_I_SHIFT                       16
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: IMPE_ERASE :: reserved1 [15:14] */
#define BCHP_ODS_FE_0_IMPE_ERASE_reserved1_MASK                    0x0000c000
#define BCHP_ODS_FE_0_IMPE_ERASE_reserved1_SHIFT                   14

/* ODS_FE_0 :: IMPE_ERASE :: VAL_Q [13:00] */
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_Q_MASK                        0x00003fff
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_Q_SHIFT                       0
#define BCHP_ODS_FE_0_IMPE_ERASE_VAL_Q_DEFAULT                     0x00000000

/***************************************************************************
 *IMPE_INST_THR - Impulse Erasure Instantaneous Threshold
 ***************************************************************************/
/* ODS_FE_0 :: IMPE_INST_THR :: reserved0 [31:24] */
#define BCHP_ODS_FE_0_IMPE_INST_THR_reserved0_MASK                 0xff000000
#define BCHP_ODS_FE_0_IMPE_INST_THR_reserved0_SHIFT                24

/* ODS_FE_0 :: IMPE_INST_THR :: INST_THR [23:00] */
#define BCHP_ODS_FE_0_IMPE_INST_THR_INST_THR_MASK                  0x00ffffff
#define BCHP_ODS_FE_0_IMPE_INST_THR_INST_THR_SHIFT                 0
#define BCHP_ODS_FE_0_IMPE_INST_THR_INST_THR_DEFAULT               0x000404de

/***************************************************************************
 *IMPE_MA_THR - Impulse Erasure Moving Average Threshold
 ***************************************************************************/
/* ODS_FE_0 :: IMPE_MA_THR :: reserved0 [31:24] */
#define BCHP_ODS_FE_0_IMPE_MA_THR_reserved0_MASK                   0xff000000
#define BCHP_ODS_FE_0_IMPE_MA_THR_reserved0_SHIFT                  24

/* ODS_FE_0 :: IMPE_MA_THR :: MA_THR [23:00] */
#define BCHP_ODS_FE_0_IMPE_MA_THR_MA_THR_MASK                      0x00ffffff
#define BCHP_ODS_FE_0_IMPE_MA_THR_MA_THR_SHIFT                     0
#define BCHP_ODS_FE_0_IMPE_MA_THR_MA_THR_DEFAULT                   0x0009a549

/***************************************************************************
 *IMPE_ERASE_CNT - Impulse Erasure Count
 ***************************************************************************/
/* ODS_FE_0 :: IMPE_ERASE_CNT :: ERASE_CNT [31:00] */
#define BCHP_ODS_FE_0_IMPE_ERASE_CNT_ERASE_CNT_MASK                0xffffffff
#define BCHP_ODS_FE_0_IMPE_ERASE_CNT_ERASE_CNT_SHIFT               0
#define BCHP_ODS_FE_0_IMPE_ERASE_CNT_ERASE_CNT_DEFAULT             0x00000000

/***************************************************************************
 *CL - Carrier Loop Control
 ***************************************************************************/
/* ODS_FE_0 :: CL :: reserved0 [31:01] */
#define BCHP_ODS_FE_0_CL_reserved0_MASK                            0xfffffffe
#define BCHP_ODS_FE_0_CL_reserved0_SHIFT                           1

/* ODS_FE_0 :: CL :: LFO_NEG [00:00] */
#define BCHP_ODS_FE_0_CL_LFO_NEG_MASK                              0x00000001
#define BCHP_ODS_FE_0_CL_LFO_NEG_SHIFT                             0
#define BCHP_ODS_FE_0_CL_LFO_NEG_DEFAULT                           0x00000000

/***************************************************************************
 *CL_FCW - Carrier Loop Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: CL_FCW :: FCW [31:00] */
#define BCHP_ODS_FE_0_CL_FCW_FCW_MASK                              0xffffffff
#define BCHP_ODS_FE_0_CL_FCW_FCW_SHIFT                             0
#define BCHP_ODS_FE_0_CL_FCW_FCW_DEFAULT                           0x40000000

/***************************************************************************
 *CL_COEF - Carrier Loop Coefficients
 ***************************************************************************/
/* ODS_FE_0 :: CL_COEF :: KI [31:16] */
#define BCHP_ODS_FE_0_CL_COEF_KI_MASK                              0xffff0000
#define BCHP_ODS_FE_0_CL_COEF_KI_SHIFT                             16
#define BCHP_ODS_FE_0_CL_COEF_KI_DEFAULT                           0x00000000

/* ODS_FE_0 :: CL_COEF :: KL [15:00] */
#define BCHP_ODS_FE_0_CL_COEF_KL_MASK                              0x0000ffff
#define BCHP_ODS_FE_0_CL_COEF_KL_SHIFT                             0
#define BCHP_ODS_FE_0_CL_COEF_KL_DEFAULT                           0x00000000

/***************************************************************************
 *CL_FEST - Carrier Loop Fractional Estimates
 ***************************************************************************/
/* ODS_FE_0 :: CL_FEST :: reserved0 [31:16] */
#define BCHP_ODS_FE_0_CL_FEST_reserved0_MASK                       0xffff0000
#define BCHP_ODS_FE_0_CL_FEST_reserved0_SHIFT                      16

/* ODS_FE_0 :: CL_FEST :: FRAC_EST [15:00] */
#define BCHP_ODS_FE_0_CL_FEST_FRAC_EST_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_CL_FEST_FRAC_EST_SHIFT                       0
#define BCHP_ODS_FE_0_CL_FEST_FRAC_EST_DEFAULT                     0x00000000

/***************************************************************************
 *CL_IEST - Carrier Loop Integer Estimate
 ***************************************************************************/
/* ODS_FE_0 :: CL_IEST :: reserved0 [31:30] */
#define BCHP_ODS_FE_0_CL_IEST_reserved0_MASK                       0xc0000000
#define BCHP_ODS_FE_0_CL_IEST_reserved0_SHIFT                      30

/* ODS_FE_0 :: CL_IEST :: INT_EST [29:00] */
#define BCHP_ODS_FE_0_CL_IEST_INT_EST_MASK                         0x3fffffff
#define BCHP_ODS_FE_0_CL_IEST_INT_EST_SHIFT                        0
#define BCHP_ODS_FE_0_CL_IEST_INT_EST_DEFAULT                      0x00000000

/***************************************************************************
 *CL_INT - Carrier Loop Integrator
 ***************************************************************************/
/* ODS_FE_0 :: CL_INT :: INT [31:00] */
#define BCHP_ODS_FE_0_CL_INT_INT_MASK                              0xffffffff
#define BCHP_ODS_FE_0_CL_INT_INT_SHIFT                             0
#define BCHP_ODS_FE_0_CL_INT_INT_DEFAULT                           0x00000000

/***************************************************************************
 *CL_LFO - Carrier Loop Filter Output
 ***************************************************************************/
/* ODS_FE_0 :: CL_LFO :: LFO [31:00] */
#define BCHP_ODS_FE_0_CL_LFO_LFO_MASK                              0xffffffff
#define BCHP_ODS_FE_0_CL_LFO_LFO_SHIFT                             0
#define BCHP_ODS_FE_0_CL_LFO_LFO_DEFAULT                           0x00000000

/***************************************************************************
 *CL_PA - Carrier Loop Phase Accumulator
 ***************************************************************************/
/* ODS_FE_0 :: CL_PA :: PA [31:00] */
#define BCHP_ODS_FE_0_CL_PA_PA_MASK                                0xffffffff
#define BCHP_ODS_FE_0_CL_PA_PA_SHIFT                               0
#define BCHP_ODS_FE_0_CL_PA_PA_DEFAULT                             0x00000000

/***************************************************************************
 *TL_FCW - Timing Loop Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: TL_FCW :: FCW [31:00] */
#define BCHP_ODS_FE_0_TL_FCW_FCW_MASK                              0xffffffff
#define BCHP_ODS_FE_0_TL_FCW_FCW_SHIFT                             0
#define BCHP_ODS_FE_0_TL_FCW_FCW_DEFAULT                           0x80000000

/***************************************************************************
 *TL_COEF - Timing Loop Coefficients
 ***************************************************************************/
/* ODS_FE_0 :: TL_COEF :: KI [31:16] */
#define BCHP_ODS_FE_0_TL_COEF_KI_MASK                              0xffff0000
#define BCHP_ODS_FE_0_TL_COEF_KI_SHIFT                             16
#define BCHP_ODS_FE_0_TL_COEF_KI_DEFAULT                           0x00000000

/* ODS_FE_0 :: TL_COEF :: KL [15:00] */
#define BCHP_ODS_FE_0_TL_COEF_KL_MASK                              0x0000ffff
#define BCHP_ODS_FE_0_TL_COEF_KL_SHIFT                             0
#define BCHP_ODS_FE_0_TL_COEF_KL_DEFAULT                           0x00000000

/***************************************************************************
 *TL_LEAK_COEF - Timing Loop Coefficients
 ***************************************************************************/
/* ODS_FE_0 :: TL_LEAK_COEF :: KI [31:16] */
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KI_MASK                         0xffff0000
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KI_SHIFT                        16
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KI_DEFAULT                      0x00000000

/* ODS_FE_0 :: TL_LEAK_COEF :: KL [15:00] */
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KL_MASK                         0x0000ffff
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KL_SHIFT                        0
#define BCHP_ODS_FE_0_TL_LEAK_COEF_KL_DEFAULT                      0x00000000

/***************************************************************************
 *TL_EST - Timing Loop Estimate
 ***************************************************************************/
/* ODS_FE_0 :: TL_EST :: reserved0 [31:16] */
#define BCHP_ODS_FE_0_TL_EST_reserved0_MASK                        0xffff0000
#define BCHP_ODS_FE_0_TL_EST_reserved0_SHIFT                       16

/* ODS_FE_0 :: TL_EST :: FRAC_EST [15:00] */
#define BCHP_ODS_FE_0_TL_EST_FRAC_EST_MASK                         0x0000ffff
#define BCHP_ODS_FE_0_TL_EST_FRAC_EST_SHIFT                        0
#define BCHP_ODS_FE_0_TL_EST_FRAC_EST_DEFAULT                      0x00000000

/***************************************************************************
 *TL_INT - Timing Loop Integrator
 ***************************************************************************/
/* ODS_FE_0 :: TL_INT :: INT [31:00] */
#define BCHP_ODS_FE_0_TL_INT_INT_MASK                              0xffffffff
#define BCHP_ODS_FE_0_TL_INT_INT_SHIFT                             0
#define BCHP_ODS_FE_0_TL_INT_INT_DEFAULT                           0x00000000

/***************************************************************************
 *TL_LFO - Timing Loop Filter Output
 ***************************************************************************/
/* ODS_FE_0 :: TL_LFO :: LFO [31:00] */
#define BCHP_ODS_FE_0_TL_LFO_LFO_MASK                              0xffffffff
#define BCHP_ODS_FE_0_TL_LFO_LFO_SHIFT                             0
#define BCHP_ODS_FE_0_TL_LFO_LFO_DEFAULT                           0x00000000

/***************************************************************************
 *TL_NCO - Timing Loop NCO
 ***************************************************************************/
/* ODS_FE_0 :: TL_NCO :: NCO [31:00] */
#define BCHP_ODS_FE_0_TL_NCO_NCO_MASK                              0xffffffff
#define BCHP_ODS_FE_0_TL_NCO_NCO_SHIFT                             0
#define BCHP_ODS_FE_0_TL_NCO_NCO_DEFAULT                           0x00000000

/***************************************************************************
 *DAGC - Digital AGC2 Loop Control
 ***************************************************************************/
/* ODS_FE_0 :: DAGC :: reserved0 [31:28] */
#define BCHP_ODS_FE_0_DAGC_reserved0_MASK                          0xf0000000
#define BCHP_ODS_FE_0_DAGC_reserved0_SHIFT                         28

/* ODS_FE_0 :: DAGC :: K [27:24] */
#define BCHP_ODS_FE_0_DAGC_K_MASK                                  0x0f000000
#define BCHP_ODS_FE_0_DAGC_K_SHIFT                                 24
#define BCHP_ODS_FE_0_DAGC_K_DEFAULT                               0x00000005

/* ODS_FE_0 :: DAGC :: reserved1 [23:22] */
#define BCHP_ODS_FE_0_DAGC_reserved1_MASK                          0x00c00000
#define BCHP_ODS_FE_0_DAGC_reserved1_SHIFT                         22

/* ODS_FE_0 :: DAGC :: BETA [21:20] */
#define BCHP_ODS_FE_0_DAGC_BETA_MASK                               0x00300000
#define BCHP_ODS_FE_0_DAGC_BETA_SHIFT                              20
#define BCHP_ODS_FE_0_DAGC_BETA_DEFAULT                            0x00000002

/* ODS_FE_0 :: DAGC :: reserved2 [19:19] */
#define BCHP_ODS_FE_0_DAGC_reserved2_MASK                          0x00080000
#define BCHP_ODS_FE_0_DAGC_reserved2_SHIFT                         19

/* ODS_FE_0 :: DAGC :: THRESH [18:00] */
#define BCHP_ODS_FE_0_DAGC_THRESH_MASK                             0x0007ffff
#define BCHP_ODS_FE_0_DAGC_THRESH_SHIFT                            0
#define BCHP_ODS_FE_0_DAGC_THRESH_DEFAULT                          0x00020000

/***************************************************************************
 *DAGC_INT - Digital AGC2 Loop Filter Output
 ***************************************************************************/
/* ODS_FE_0 :: DAGC_INT :: INT [31:00] */
#define BCHP_ODS_FE_0_DAGC_INT_INT_MASK                            0xffffffff
#define BCHP_ODS_FE_0_DAGC_INT_INT_SHIFT                           0
#define BCHP_ODS_FE_0_DAGC_INT_INT_DEFAULT                         0x02000000

/***************************************************************************
 *DAGC_UPDATE - Digital AGC2 Loop Update Control
 ***************************************************************************/
/* ODS_FE_0 :: DAGC_UPDATE :: reserved0 [31:24] */
#define BCHP_ODS_FE_0_DAGC_UPDATE_reserved0_MASK                   0xff000000
#define BCHP_ODS_FE_0_DAGC_UPDATE_reserved0_SHIFT                  24

/* ODS_FE_0 :: DAGC_UPDATE :: DURATION [23:08] */
#define BCHP_ODS_FE_0_DAGC_UPDATE_DURATION_MASK                    0x00ffff00
#define BCHP_ODS_FE_0_DAGC_UPDATE_DURATION_SHIFT                   8
#define BCHP_ODS_FE_0_DAGC_UPDATE_DURATION_DEFAULT                 0x00000001

/* ODS_FE_0 :: DAGC_UPDATE :: reserved1 [07:01] */
#define BCHP_ODS_FE_0_DAGC_UPDATE_reserved1_MASK                   0x000000fe
#define BCHP_ODS_FE_0_DAGC_UPDATE_reserved1_SHIFT                  1

/* ODS_FE_0 :: DAGC_UPDATE :: MODE [00:00] */
#define BCHP_ODS_FE_0_DAGC_UPDATE_MODE_MASK                        0x00000001
#define BCHP_ODS_FE_0_DAGC_UPDATE_MODE_SHIFT                       0
#define BCHP_ODS_FE_0_DAGC_UPDATE_MODE_DEFAULT                     0x00000000

/***************************************************************************
 *NOTCH_CTL - Notch Control
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH_CTL :: reserved0 [31:02] */
#define BCHP_ODS_FE_0_NOTCH_CTL_reserved0_MASK                     0xfffffffc
#define BCHP_ODS_FE_0_NOTCH_CTL_reserved0_SHIFT                    2

/* ODS_FE_0 :: NOTCH_CTL :: FCW0_ADJ_NEG [01:01] */
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_NEG_MASK                  0x00000002
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_NEG_SHIFT                 1
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_NEG_DEFAULT               0x00000000

/* ODS_FE_0 :: NOTCH_CTL :: FCW0_ADJ_EN [00:00] */
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_EN_MASK                   0x00000001
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_EN_SHIFT                  0
#define BCHP_ODS_FE_0_NOTCH_CTL_FCW0_ADJ_EN_DEFAULT                0x00000000

/***************************************************************************
 *NOTCH_WIDTH - Notch Width
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH_WIDTH :: reserved0 [31:20] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_reserved0_MASK                   0xfff00000
#define BCHP_ODS_FE_0_NOTCH_WIDTH_reserved0_SHIFT                  20

/* ODS_FE_0 :: NOTCH_WIDTH :: WIDTH4 [19:16] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH4_MASK                      0x000f0000
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH4_SHIFT                     16
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH4_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_WIDTH :: WIDTH3 [15:12] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH3_MASK                      0x0000f000
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH3_SHIFT                     12
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH3_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_WIDTH :: WIDTH2 [11:08] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH2_MASK                      0x00000f00
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH2_SHIFT                     8
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH2_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_WIDTH :: WIDTH1 [07:04] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH1_MASK                      0x000000f0
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH1_SHIFT                     4
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH1_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_WIDTH :: WIDTH0 [03:00] */
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH0_MASK                      0x0000000f
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH0_SHIFT                     0
#define BCHP_ODS_FE_0_NOTCH_WIDTH_WIDTH0_DEFAULT                   0x00000000

/***************************************************************************
 *NOTCH_DEPTH - Notch Depth
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH_DEPTH :: reserved0 [31:20] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_reserved0_MASK                   0xfff00000
#define BCHP_ODS_FE_0_NOTCH_DEPTH_reserved0_SHIFT                  20

/* ODS_FE_0 :: NOTCH_DEPTH :: DEPTH4 [19:16] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH4_MASK                      0x000f0000
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH4_SHIFT                     16
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH4_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_DEPTH :: DEPTH3 [15:12] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH3_MASK                      0x0000f000
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH3_SHIFT                     12
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH3_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_DEPTH :: DEPTH2 [11:08] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH2_MASK                      0x00000f00
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH2_SHIFT                     8
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH2_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_DEPTH :: DEPTH1 [07:04] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH1_MASK                      0x000000f0
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH1_SHIFT                     4
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH1_DEFAULT                   0x00000000

/* ODS_FE_0 :: NOTCH_DEPTH :: DEPTH0 [03:00] */
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH0_MASK                      0x0000000f
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH0_SHIFT                     0
#define BCHP_ODS_FE_0_NOTCH_DEPTH_DEPTH0_DEFAULT                   0x00000000

/***************************************************************************
 *NOTCH0_FCW - Notch0 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH0_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH0_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH0_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH0_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH0_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH0_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH0_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH1_FCW - Notch1 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH1_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH1_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH1_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH1_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH1_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH1_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH1_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH2_FCW - Notch2 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH2_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH2_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH2_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH2_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH2_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH2_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH2_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH3_FCW - Notch3 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH3_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH3_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH3_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH3_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH3_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH3_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH3_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH4_FCW - Notch4 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH4_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH4_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH4_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH4_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH4_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH4_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH4_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH5_FCW - Notch5 Frequency Control Word
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH5_FCW :: FCW [31:12] */
#define BCHP_ODS_FE_0_NOTCH5_FCW_FCW_MASK                          0xfffff000
#define BCHP_ODS_FE_0_NOTCH5_FCW_FCW_SHIFT                         12
#define BCHP_ODS_FE_0_NOTCH5_FCW_FCW_DEFAULT                       0x00000000

/* ODS_FE_0 :: NOTCH5_FCW :: reserved0 [11:00] */
#define BCHP_ODS_FE_0_NOTCH5_FCW_reserved0_MASK                    0x00000fff
#define BCHP_ODS_FE_0_NOTCH5_FCW_reserved0_SHIFT                   0

/***************************************************************************
 *NOTCH0_INT - Notch0 Integrator
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH0_INT :: INT_I [31:16] */
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_I_MASK                        0xffff0000
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_I_SHIFT                       16
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: NOTCH0_INT :: INT_Q [15:00] */
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_Q_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_Q_SHIFT                       0
#define BCHP_ODS_FE_0_NOTCH0_INT_INT_Q_DEFAULT                     0x00000000

/***************************************************************************
 *NOTCH1_INT - Notch1 Integrator
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH1_INT :: INT_I [31:16] */
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_I_MASK                        0xffff0000
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_I_SHIFT                       16
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: NOTCH1_INT :: INT_Q [15:00] */
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_Q_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_Q_SHIFT                       0
#define BCHP_ODS_FE_0_NOTCH1_INT_INT_Q_DEFAULT                     0x00000000

/***************************************************************************
 *NOTCH2_INT - Notch2 Integrator
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH2_INT :: INT_I [31:16] */
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_I_MASK                        0xffff0000
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_I_SHIFT                       16
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: NOTCH2_INT :: INT_Q [15:00] */
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_Q_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_Q_SHIFT                       0
#define BCHP_ODS_FE_0_NOTCH2_INT_INT_Q_DEFAULT                     0x00000000

/***************************************************************************
 *NOTCH3_INT - Notch3 Integrator
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH3_INT :: INT_I [31:16] */
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_I_MASK                        0xffff0000
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_I_SHIFT                       16
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: NOTCH3_INT :: INT_Q [15:00] */
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_Q_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_Q_SHIFT                       0
#define BCHP_ODS_FE_0_NOTCH3_INT_INT_Q_DEFAULT                     0x00000000

/***************************************************************************
 *NOTCH4_INT - Notch4 Integrator
 ***************************************************************************/
/* ODS_FE_0 :: NOTCH4_INT :: INT_I [31:16] */
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_I_MASK                        0xffff0000
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_I_SHIFT                       16
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_I_DEFAULT                     0x00000000

/* ODS_FE_0 :: NOTCH4_INT :: INT_Q [15:00] */
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_Q_MASK                        0x0000ffff
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_Q_SHIFT                       0
#define BCHP_ODS_FE_0_NOTCH4_INT_INT_Q_DEFAULT                     0x00000000

/***************************************************************************
 *ECO_SPARE0 - ECO Spare 0 Register
 ***************************************************************************/
/* ODS_FE_0 :: ECO_SPARE0 :: SPARE [31:00] */
#define BCHP_ODS_FE_0_ECO_SPARE0_SPARE_MASK                        0xffffffff
#define BCHP_ODS_FE_0_ECO_SPARE0_SPARE_SHIFT                       0
#define BCHP_ODS_FE_0_ECO_SPARE0_SPARE_DEFAULT                     0x00000000

/***************************************************************************
 *ECO_SPARE1 - ECO Spare 1 Register
 ***************************************************************************/
/* ODS_FE_0 :: ECO_SPARE1 :: SPARE [31:00] */
#define BCHP_ODS_FE_0_ECO_SPARE1_SPARE_MASK                        0xffffffff
#define BCHP_ODS_FE_0_ECO_SPARE1_SPARE_SHIFT                       0
#define BCHP_ODS_FE_0_ECO_SPARE1_SPARE_DEFAULT                     0x00000000

#endif /* #ifndef BCHP_ODS_FE_0_H__ */

/* End of File */
