/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Fri Apr  1 16:47:49 2016
 *                 Full Compile MD5 Checksum  984a9ce5f12e06c211b099d45a86700d
 *                     (minus title and desc)
 *                 MD5 Checksum               4a93ec675dafca14940fe2131c3e7f4b
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     899
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/combo_header.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_VICE_ARCSS_ESS_ADI_0_0_H__
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_H__

/***************************************************************************
 *VICE_ARCSS_ESS_ADI_0_0 - VICE ARC0 DINO Registers
 ***************************************************************************/

/***************************************************************************
 *ADI_RX_FIFO%i - ADI RX FIFO
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ARRAY_BASE        0x01518000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ARRAY_START       0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ARRAY_END         2
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_RX_FIFO%i - ADI RX FIFO
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_FIFOi :: reserved0 [31:28] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_reserved0_MASK    0xf0000000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_reserved0_SHIFT   28

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_FIFOi :: ADDR_OFFSET [27:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ADDR_OFFSET_MASK  0x0fffc000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ADDR_OFFSET_SHIFT 14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_ADDR_OFFSET_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_FIFOi :: SIZE [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_SIZE_MASK         0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_SIZE_SHIFT        0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFOi_SIZE_DEFAULT      0x00000000


/***************************************************************************
 *ADI_RX_WRITE%i - ADI RX WRITE
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_ARRAY_BASE       0x01518040
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_ARRAY_START      0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_ARRAY_END        2
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_RX_WRITE%i - ADI RX WRITE
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_WRITEi :: reserved0 [31:15] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_reserved0_MASK   0xffff8000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_reserved0_SHIFT  15

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_WRITEi :: FULL [14:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_FULL_MASK        0x00004000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_FULL_SHIFT       14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_FULL_DEFAULT     0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_WRITEi :: POINTER [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_POINTER_MASK     0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_POINTER_SHIFT    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_WRITEi_POINTER_DEFAULT  0x00000000


/***************************************************************************
 *ADI_RX_READ%i - ADI RX POINTERS
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_ARRAY_BASE        0x01518060
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_ARRAY_START       0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_ARRAY_END         2
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_RX_READ%i - ADI RX POINTERS
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_READi :: reserved0 [31:17] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_reserved0_MASK    0xfffe0000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_reserved0_SHIFT   17

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_READi :: CLEAR_WP [16:16] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_WP_MASK     0x00010000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_WP_SHIFT    16
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_WP_DEFAULT  0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_READi :: CLEAR_PHASE [15:15] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_PHASE_MASK  0x00008000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_PHASE_SHIFT 15
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_CLEAR_PHASE_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_READi :: SET_PHASE [14:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_SET_PHASE_MASK    0x00004000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_SET_PHASE_SHIFT   14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_SET_PHASE_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_READi :: POINTER [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_POINTER_MASK      0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_POINTER_SHIFT     0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_READi_POINTER_DEFAULT   0x00000000


/***************************************************************************
 *ADI_RX_FIFO_EN%i - ADI RX FIFO_EN
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ARRAY_BASE     0x01518080
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ARRAY_START    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ARRAY_END      2
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_RX_FIFO_EN%i - ADI RX FIFO_EN
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_FIFO_ENi :: reserved0 [31:01] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_reserved0_MASK 0xfffffffe
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_reserved0_SHIFT 1

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_RX_FIFO_ENi :: ENABLE [00:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ENABLE_MASK    0x00000001
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ENABLE_SHIFT   0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_RX_FIFO_ENi_ENABLE_DEFAULT 0x00000000


/***************************************************************************
 *ADI_TX_FIFO%i - ADI TX FIFO
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ARRAY_BASE        0x01518200
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ARRAY_START       0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ARRAY_END         3
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_TX_FIFO%i - ADI TX FIFO
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_FIFOi :: reserved0 [31:28] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_reserved0_MASK    0xf0000000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_reserved0_SHIFT   28

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_FIFOi :: ADDR_OFFSET [27:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ADDR_OFFSET_MASK  0x0fffc000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ADDR_OFFSET_SHIFT 14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_ADDR_OFFSET_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_FIFOi :: SIZE [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_SIZE_MASK         0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_SIZE_SHIFT        0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFOi_SIZE_DEFAULT      0x00000000


/***************************************************************************
 *ADI_TX_READ%i - ADI TX READ
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_ARRAY_BASE        0x01518240
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_ARRAY_START       0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_ARRAY_END         3
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_TX_READ%i - ADI TX READ
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_READi :: reserved0 [31:15] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_reserved0_MASK    0xffff8000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_reserved0_SHIFT   15

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_READi :: EMPTY [14:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_EMPTY_MASK        0x00004000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_EMPTY_SHIFT       14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_EMPTY_DEFAULT     0x00000001

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_READi :: POINTER [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_POINTER_MASK      0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_POINTER_SHIFT     0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_READi_POINTER_DEFAULT   0x00000000


/***************************************************************************
 *ADI_TX_WRITE%i - ADI TX POINTERS
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_ARRAY_BASE       0x01518260
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_ARRAY_START      0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_ARRAY_END        3
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_TX_WRITE%i - ADI TX POINTERS
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_WRITEi :: reserved0 [31:17] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_reserved0_MASK   0xfffe0000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_reserved0_SHIFT  17

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_WRITEi :: CLEAR_RP [16:16] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_RP_MASK    0x00010000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_RP_SHIFT   16
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_RP_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_WRITEi :: CLEAR_PHASE [15:15] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_PHASE_MASK 0x00008000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_PHASE_SHIFT 15
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_CLEAR_PHASE_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_WRITEi :: SET_PHASE [14:14] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_SET_PHASE_MASK   0x00004000
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_SET_PHASE_SHIFT  14
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_SET_PHASE_DEFAULT 0x00000000

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_WRITEi :: POINTER [13:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_POINTER_MASK     0x00003fff
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_POINTER_SHIFT    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_WRITEi_POINTER_DEFAULT  0x00000000


/***************************************************************************
 *ADI_TX_FIFO_EN%i - ADI TX FIFO_EN
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ARRAY_BASE     0x01518280
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ARRAY_START    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ARRAY_END      3
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_TX_FIFO_EN%i - ADI TX FIFO_EN
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_FIFO_ENi :: reserved0 [31:01] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_reserved0_MASK 0xfffffffe
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_reserved0_SHIFT 1

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_FIFO_ENi :: ENABLE [00:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ENABLE_MASK    0x00000001
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ENABLE_SHIFT   0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_FIFO_ENi_ENABLE_DEFAULT 0x00000000


/***************************************************************************
 *ADI_TX_COMMAND%i - ADI TX COMMAND
 ***************************************************************************/
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_ARRAY_BASE     0x015182a0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_ARRAY_START    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_ARRAY_END      3
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *ADI_TX_COMMAND%i - ADI TX COMMAND
 ***************************************************************************/
/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_COMMANDi :: reserved0 [31:01] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_reserved0_MASK 0xfffffffe
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_reserved0_SHIFT 1

/* VICE_ARCSS_ESS_ADI_0_0 :: ADI_TX_COMMANDi :: FORCE [00:00] */
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_FORCE_MASK     0x00000001
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_FORCE_SHIFT    0
#define BCHP_VICE_ARCSS_ESS_ADI_0_0_ADI_TX_COMMANDi_FORCE_DEFAULT  0x00000000


#endif /* #ifndef BCHP_VICE_ARCSS_ESS_ADI_0_0_H__ */

/* End of File */
