# All router Apps, NIC drivers, DHD driver and FW souces Directories.
export STBAP_APPS_DIR=router
export STBAP_NIC_DRIVER_DIR=..
export STBAP_FD_DRIVER_DIR=DHD45RC91024_REL_1_363_5
export STBAP_FW_DIR=FW_BISON04T_REL_7_14_170_2605

# Router DHD drivers targets
export STBAP_WIFI_FD_DRIVER=dhd-msgbuf-pciefd-mfp-wmf-psta-wet-reqfw-stbap-armv7l
export STBAP_WIFI_FD_SECDMA_DRIVER=dhd-msgbuf-pciefd-mfp-wmf-psta-wet-secdma-reqfw-stbap-armv7l

# REL Package name
export STBAP_VER=7_14_170_2605_17.3
export STBAP_DOTTED_REL_NAME=7_14_170_2605_17.3

# Router NIC drivers targets
export STBAP_WIFI_NIC_DRIVER=nodebug-apdef-stadef-extnvm-mfp-wet-pspretend-wmf-stbapbison-stbsoc-armv7l

# Router 43602 TARGETS
export STBAP_FW_43602A1_NAME=pcie-ag-splitrx-fdap-mbss-mfp-osen-wl11k-wl11u-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-obss-ringer-dmaindex16-bssload-dhdhdr
export STBAP_FW_43602A1_MFG_NAME=pcie-ag-splitrx-fdap-mbss-mfgtest-seqcmds-phydbg-phydump-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-ringer-dmaindex16

# Router 43602 TAG and built date
export STBAP_FW_43602A3_NAME=pcie-ag-splitrx-fdap-mbss-mfp-osen-wl11k-wl11u-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-obss-ringer-dmaindex16-bssload-wnm-splitassoc-dbwsw-stamon-acksupr-authrmf-dhdhdr-assoc_lt-fbt
export STBAP_FW_43602A3_MFG_NAME=pcie-ag-splitrx-fdap-mbss-mfgtest-seqcmds-phydbg-phydump-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-ringer-dmaindex16-assoc_lt-fbt

# Router 4366C0 TARGETS
export STBAP_FW_4366C0_NAME=pcie-ag-splitrx-fdap-mbss-mfp-wnm-osen-wl11k-wl11u-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-obss-dbwsw-ringer-dmaindex16-bgdfs-stamon-hostpmac-murx-splitassoc-hostmemucode-dyn160-dhdhdr-fbt-htxhdr-amsdufrag-stb
export STBAP_FW_4366C0_MFG_NAME=pcie-ag-splitrx-fdap-mbss-mfgtest-seqcmds-phydbg-phydump-txbf-pktctx-amsdutx-ampduretry-chkd2hdma-proptxstatus-11nprop-dbgam-dbgams-ringer-dmaindex16-bgdfs-hostpmac-murx-splitassoc-hostmemucode-dyn160-fbt-stb
