/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Thu Dec  4 13:59:00 2014
 *                 Full Compile MD5 Checksum  7f8620d6db569529bdb0529f9fa1fcf2
 *                     (minus title and desc)
 *                 MD5 Checksum               48c8fdf2af4291bac0fa2b0d5245d05c
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15262
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_CMP_5_H__
#define BCHP_CMP_5_H__

/***************************************************************************
 *CMP_5 - Video Compositor 5 Registers
 ***************************************************************************/
#define BCHP_CMP_5_REVISION                      0x00644c00 /* [RO] Compositor Revision ID */
#define BCHP_CMP_5_HW_CONFIGURATION              0x00644c04 /* [RO] Compositor HW Configuration */
#define BCHP_CMP_5_CANVAS_CTRL                   0x00644c08 /* [XRW] Canvas control */
#define BCHP_CMP_5_CANVAS_SIZE                   0x00644c0c /* [RW] Canvas Vertical and Horizontal Size */
#define BCHP_CMP_5_BG_COLOR                      0x00644c10 /* [RW] Background color register */
#define BCHP_CMP_5_BLEND_0_CTRL                  0x00644c14 /* [RW] Blending Control for First stage Blender */
#define BCHP_CMP_5_BLEND_1_CTRL                  0x00644c18 /* [RW] Blending Control for Second stage Blender */
#define BCHP_CMP_5_CMP_CTRL                      0x00644c28 /* [RW] Compositor Control */
#define BCHP_CMP_5_CMP_OUT_CTRL                  0x00644c40 /* [RW] Compositor Output Control */
#define BCHP_CMP_5_CRC_CTRL                      0x00644c44 /* [RW] BVN CRC Control Register */
#define BCHP_CMP_5_CRC_Y_STATUS                  0x00644c48 /* [RO] BVN CRC Luma Status Register */
#define BCHP_CMP_5_CRC_CB_STATUS                 0x00644c4c /* [RO] BVN CRC Chroma(Cb) Status Register */
#define BCHP_CMP_5_CRC_CR_STATUS                 0x00644c50 /* [RO] BVN CRC Chroma(Cr) Status Register */
#define BCHP_CMP_5_READBACK_POSITION             0x00644c54 /* [RW] Compositor Position For CMP Output Readback */
#define BCHP_CMP_5_READBACK_VALUE                0x00644c58 /* [RO] Compositor Readback Value at Specified Position */
#define BCHP_CMP_5_CSC_DEMO_SETTING              0x00644c5c /* [RW] Compositor Color Space Converter Demo Setting */
#define BCHP_CMP_5_SCRATCH_REGISTER              0x00644c60 /* [RW] Compositor Scratch Register */
#define BCHP_CMP_5_TEST_REGISTER                 0x00644c68 /* [RW] Compositor Test Register */
#define BCHP_CMP_5_TEST_REGISTER1                0x00644c6c /* [RO] Compositor Test Register1 */
#define BCHP_CMP_5_G0_SURFACE_SIZE               0x00644c80 /* [RW] Graphics Surface 0 Vertical and Horizontal Size */
#define BCHP_CMP_5_G0_SURFACE_OFFSET             0x00644c84 /* [RW] Graphics Surface 0 Vertical and Horizontal Offset */
#define BCHP_CMP_5_G0_DISPLAY_SIZE               0x00644c88 /* [RW] Graphics Surface 0 Display Vertical and Horizontal Size */
#define BCHP_CMP_5_G0_CANVAS_OFFSET              0x00644c8c /* [RW] Graphics Surface 0 Canvas Vertical and Horizontal Offset */
#define BCHP_CMP_5_G0_CANVAS_X_OFFSET_R          0x00644c90 /* [RW] Graphics Surface 0 Canvas Horizontal Offset For Right or Under Window in 3D mode */
#define BCHP_CMP_5_G0_SURFACE_CTRL               0x00644c94 /* [RW] Graphics Surface 0 Control */
#define BCHP_CMP_5_G0_BVB_IN_STATUS_CLEAR        0x00644c98 /* [WO] Graphics Surface 0 BVB Input Status Clear */
#define BCHP_CMP_5_G0_BVB_IN_STATUS              0x00644c9c /* [RO] Graphics Surface 0 BVB Input Status */
#define BCHP_CMP_5_V0_SURFACE_SIZE               0x00644cb0 /* [RW] Video Surface 0 Vertical and Horizontal Size */
#define BCHP_CMP_5_V0_SURFACE_OFFSET             0x00644cb4 /* [RW] Video Surface 0 Vertical and Horizontal Offset */
#define BCHP_CMP_5_V0_DISPLAY_SIZE               0x00644cb8 /* [RW] Video Surface 0 Display Vertical and Horizontal Size */
#define BCHP_CMP_5_V0_CANVAS_OFFSET              0x00644cbc /* [RW] Video Surface 0 Canvas Vertical and Horizontal Offset */
#define BCHP_CMP_5_V0_CANVAS_X_OFFSET_R          0x00644cc0 /* [RW] Video Surface 0 Canvas Horizontal Offset For Right or Under Window in 3D mode */
#define BCHP_CMP_5_V0_SURFACE_CTRL               0x00644cc4 /* [RW] Video Surface 0 Control */
#define BCHP_CMP_5_V0_BVB_IN_STATUS_CLEAR        0x00644cc8 /* [WO] Video Surface 0 BVB Input Status Clear */
#define BCHP_CMP_5_V0_BVB_IN_STATUS              0x00644ccc /* [RO] Video Surface 0 BVB Input Status */
#define BCHP_CMP_5_V0_CONST_COLOR                0x00644cd0 /* [RW] Video Surface 0 Constant Color Register */
#define BCHP_CMP_5_V0_CB_KEYING                  0x00644cd4 /* [RW] Video Surface 0 Chroma (Blue) Key */
#define BCHP_CMP_5_V0_CR_KEYING                  0x00644cd8 /* [RW] Video Surface 0 Chroma (Red) Key */
#define BCHP_CMP_5_V0_LUMA_KEYING                0x00644cdc /* [RW] Video Surface 0 Luma Key */
#define BCHP_CMP_5_V0_RECT_CSC_INDEX_0           0x00644ce0 /* [RW] Video Surface 0 rectangle CSC index 0 */
#define BCHP_CMP_5_V0_RECT_CSC_INDEX_1           0x00644ce4 /* [RW] Video Surface 0 rectangle CSC index 1 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C00            0x00644ce8 /* [RW] Video Surface 0 Color Matrix R0 coefficient c00 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C01            0x00644cec /* [RW] Video Surface 0 Color Matrix R0 coefficient c01 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C02            0x00644cf0 /* [RW] Video Surface 0 Color Matrix R0 coefficient c02 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C03            0x00644cf4 /* [RW] Video Surface 0 Color Matrix R0 coefficient c03 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C10            0x00644cf8 /* [RW] Video Surface 0 Color Matrix R0 coefficient c10 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C11            0x00644cfc /* [RW] Video Surface 0 Color Matrix R0 coefficient c11 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C12            0x00644d00 /* [RW] Video Surface 0 Color Matrix R0 coefficient c12 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C13            0x00644d04 /* [RW] Video Surface 0 Color Matrix R0 coefficient c13 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C20            0x00644d08 /* [RW] Video Surface 0 Color Matrix R0 coefficient c20 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C21            0x00644d0c /* [RW] Video Surface 0 Color Matrix R0 coefficient c21 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C22            0x00644d10 /* [RW] Video Surface 0 Color Matrix R0 coefficient c22 */
#define BCHP_CMP_5_V0_R0_MC_COEFF_C23            0x00644d14 /* [RW] Video Surface 0 Color Matrix R0 coefficient c23 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C00            0x00644d18 /* [RW] Video Surface 0 Color Matrix R1 coefficient c00 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C01            0x00644d1c /* [RW] Video Surface 0 Color Matrix R1 coefficient c01 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C02            0x00644d20 /* [RW] Video Surface 0 Color Matrix R1 coefficient c02 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C03            0x00644d24 /* [RW] Video Surface 0 Color Matrix R1 coefficient c03 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C10            0x00644d28 /* [RW] Video Surface 0 Color Matrix R1 coefficient c10 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C11            0x00644d2c /* [RW] Video Surface 0 Color Matrix R1 coefficient c11 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C12            0x00644d30 /* [RW] Video Surface 0 Color Matrix R1 coefficient c12 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C13            0x00644d34 /* [RW] Video Surface 0 Color Matrix R1 coefficient c13 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C20            0x00644d38 /* [RW] Video Surface 0 Color Matrix R1 coefficient c20 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C21            0x00644d3c /* [RW] Video Surface 0 Color Matrix R1 coefficient c21 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C22            0x00644d40 /* [RW] Video Surface 0 Color Matrix R1 coefficient c22 */
#define BCHP_CMP_5_V0_R1_MC_COEFF_C23            0x00644d44 /* [RW] Video Surface 0 Color Matrix R1 coefficient c23 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C00            0x00644d48 /* [RW] Video Surface 0 Color Matrix R2 coefficient c00 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C01            0x00644d4c /* [RW] Video Surface 0 Color Matrix R2 coefficient c01 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C02            0x00644d50 /* [RW] Video Surface 0 Color Matrix R2 coefficient c02 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C03            0x00644d54 /* [RW] Video Surface 0 Color Matrix R2 coefficient c03 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C10            0x00644d58 /* [RW] Video Surface 0 Color Matrix R2 coefficient c10 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C11            0x00644d5c /* [RW] Video Surface 0 Color Matrix R2 coefficient c11 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C12            0x00644d60 /* [RW] Video Surface 0 Color Matrix R2 coefficient c12 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C13            0x00644d64 /* [RW] Video Surface 0 Color Matrix R2 coefficient c13 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C20            0x00644d68 /* [RW] Video Surface 0 Color Matrix R2 coefficient c20 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C21            0x00644d6c /* [RW] Video Surface 0 Color Matrix R2 coefficient c21 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C22            0x00644d70 /* [RW] Video Surface 0 Color Matrix R2 coefficient c22 */
#define BCHP_CMP_5_V0_R2_MC_COEFF_C23            0x00644d74 /* [RW] Video Surface 0 Color Matrix R2 coefficient c23 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C00            0x00644d78 /* [RW] Video Surface 0 Color Matrix R3 coefficient c00 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C01            0x00644d7c /* [RW] Video Surface 0 Color Matrix R3 coefficient c01 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C02            0x00644d80 /* [RW] Video Surface 0 Color Matrix R3 coefficient c02 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C03            0x00644d84 /* [RW] Video Surface 0 Color Matrix R3 coefficient c03 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C10            0x00644d88 /* [RW] Video Surface 0 Color Matrix R3 coefficient c10 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C11            0x00644d8c /* [RW] Video Surface 0 Color Matrix R3 coefficient c11 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C12            0x00644d90 /* [RW] Video Surface 0 Color Matrix R3 coefficient c12 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C13            0x00644d94 /* [RW] Video Surface 0 Color Matrix R3 coefficient c13 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C20            0x00644d98 /* [RW] Video Surface 0 Color Matrix R3 coefficient c20 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C21            0x00644d9c /* [RW] Video Surface 0 Color Matrix R3 coefficient c21 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C22            0x00644da0 /* [RW] Video Surface 0 Color Matrix R3 coefficient c22 */
#define BCHP_CMP_5_V0_R3_MC_COEFF_C23            0x00644da4 /* [RW] Video Surface 0 Color Matrix R3 coefficient c23 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C00            0x00644da8 /* [RW] Video Surface 0 Color Matrix R4 coefficient c00 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C01            0x00644dac /* [RW] Video Surface 0 Color Matrix R4 coefficient c01 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C02            0x00644db0 /* [RW] Video Surface 0 Color Matrix R4 coefficient c02 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C03            0x00644db4 /* [RW] Video Surface 0 Color Matrix R4 coefficient c03 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C10            0x00644db8 /* [RW] Video Surface 0 Color Matrix R4 coefficient c10 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C11            0x00644dbc /* [RW] Video Surface 0 Color Matrix R4 coefficient c11 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C12            0x00644dc0 /* [RW] Video Surface 0 Color Matrix R4 coefficient c12 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C13            0x00644dc4 /* [RW] Video Surface 0 Color Matrix R4 coefficient c13 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C20            0x00644dc8 /* [RW] Video Surface 0 Color Matrix R4 coefficient c20 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C21            0x00644dcc /* [RW] Video Surface 0 Color Matrix R4 coefficient c21 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C22            0x00644dd0 /* [RW] Video Surface 0 Color Matrix R4 coefficient c22 */
#define BCHP_CMP_5_V0_R4_MC_COEFF_C23            0x00644dd4 /* [RW] Video Surface 0 Color Matrix R4 coefficient c23 */
#define BCHP_CMP_5_V0_RECT_COLOR                 0x00644dd8 /* [RW] Video Surface 0 Rectangle Function Color Register */
#define BCHP_CMP_5_V0_RECT_TOP_CTRL              0x00644ddc /* [RW] Video Surface 0 Top Level Rectangle Control for Mosaic or See Through. */
#define BCHP_CMP_5_V0_RECT_ENABLE_MASK           0x00644de0 /* [RW] Video Surface 0 Rectangle Function Enable Mask */

/***************************************************************************
 *V0_RECT_SIZE%i - Rectangle Vertical and Horizontal Size.
 ***************************************************************************/
#define BCHP_CMP_5_V0_RECT_SIZEi_ARRAY_BASE                        0x00644de4
#define BCHP_CMP_5_V0_RECT_SIZEi_ARRAY_START                       0
#define BCHP_CMP_5_V0_RECT_SIZEi_ARRAY_END                         15
#define BCHP_CMP_5_V0_RECT_SIZEi_ARRAY_ELEMENT_SIZE                32

/***************************************************************************
 *V0_RECT_SIZE%i - Rectangle Vertical and Horizontal Size.
 ***************************************************************************/
/* CMP_5 :: V0_RECT_SIZEi :: reserved0 [31:29] */
#define BCHP_CMP_5_V0_RECT_SIZEi_reserved0_MASK                    0xe0000000
#define BCHP_CMP_5_V0_RECT_SIZEi_reserved0_SHIFT                   29

/* CMP_5 :: V0_RECT_SIZEi :: HSIZE [28:16] */
#define BCHP_CMP_5_V0_RECT_SIZEi_HSIZE_MASK                        0x1fff0000
#define BCHP_CMP_5_V0_RECT_SIZEi_HSIZE_SHIFT                       16
#define BCHP_CMP_5_V0_RECT_SIZEi_HSIZE_DEFAULT                     0x00000000

/* CMP_5 :: V0_RECT_SIZEi :: reserved1 [15:12] */
#define BCHP_CMP_5_V0_RECT_SIZEi_reserved1_MASK                    0x0000f000
#define BCHP_CMP_5_V0_RECT_SIZEi_reserved1_SHIFT                   12

/* CMP_5 :: V0_RECT_SIZEi :: VSIZE [11:00] */
#define BCHP_CMP_5_V0_RECT_SIZEi_VSIZE_MASK                        0x00000fff
#define BCHP_CMP_5_V0_RECT_SIZEi_VSIZE_SHIFT                       0
#define BCHP_CMP_5_V0_RECT_SIZEi_VSIZE_DEFAULT                     0x00000000


/***************************************************************************
 *V0_RECT_OFFSET%i - Rectangle Starting Point Offset from Surface Origin.
 ***************************************************************************/
#define BCHP_CMP_5_V0_RECT_OFFSETi_ARRAY_BASE                      0x00644e24
#define BCHP_CMP_5_V0_RECT_OFFSETi_ARRAY_START                     0
#define BCHP_CMP_5_V0_RECT_OFFSETi_ARRAY_END                       15
#define BCHP_CMP_5_V0_RECT_OFFSETi_ARRAY_ELEMENT_SIZE              32

/***************************************************************************
 *V0_RECT_OFFSET%i - Rectangle Starting Point Offset from Surface Origin.
 ***************************************************************************/
/* CMP_5 :: V0_RECT_OFFSETi :: reserved0 [31:29] */
#define BCHP_CMP_5_V0_RECT_OFFSETi_reserved0_MASK                  0xe0000000
#define BCHP_CMP_5_V0_RECT_OFFSETi_reserved0_SHIFT                 29

/* CMP_5 :: V0_RECT_OFFSETi :: X_OFFSET [28:16] */
#define BCHP_CMP_5_V0_RECT_OFFSETi_X_OFFSET_MASK                   0x1fff0000
#define BCHP_CMP_5_V0_RECT_OFFSETi_X_OFFSET_SHIFT                  16
#define BCHP_CMP_5_V0_RECT_OFFSETi_X_OFFSET_DEFAULT                0x00000000

/* CMP_5 :: V0_RECT_OFFSETi :: reserved1 [15:12] */
#define BCHP_CMP_5_V0_RECT_OFFSETi_reserved1_MASK                  0x0000f000
#define BCHP_CMP_5_V0_RECT_OFFSETi_reserved1_SHIFT                 12

/* CMP_5 :: V0_RECT_OFFSETi :: Y_OFFSET [11:00] */
#define BCHP_CMP_5_V0_RECT_OFFSETi_Y_OFFSET_MASK                   0x00000fff
#define BCHP_CMP_5_V0_RECT_OFFSETi_Y_OFFSET_SHIFT                  0
#define BCHP_CMP_5_V0_RECT_OFFSETi_Y_OFFSET_DEFAULT                0x00000000


#endif /* #ifndef BCHP_CMP_5_H__ */

/* End of File */
