/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Mon Sep 12 16:49:50 2016
 *                 Full Compile MD5 Checksum  2c753a6ff9f24b6ac602c21018c4b7f4
 *                     (minus title and desc)
 *                 MD5 Checksum               ad217b051860840cb47ca1b2b0397a1f
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1119
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/combo_header.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_MT_CBUS_H__
#define BCHP_MT_CBUS_H__

/***************************************************************************
 *MT_CBUS - CBUS Translation Layer, Link Layer, and Interrupt Registers
 ***************************************************************************/
#define BCHP_MT_CBUS_SCHEDULER_CFG               0x20d83a00 /* [RW][32] CBUS Translation Layer Scheduler Configuration Register */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0          0x20d83a04 /* [RO][32] CBUS Translation Layer Scheduler Status Register 0 */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1          0x20d83a08 /* [RO][32] CBUS Translation Layer Scheduler Status Register 1 */
#define BCHP_MT_CBUS_ABORT_CTRL                  0x20d83a0c /* [WO][32] CBUS Abort Packet Control Register */
#define BCHP_MT_CBUS_ABORT_CFG                   0x20d83a10 /* [RW][32] CBUS Abort Packet Configuration Register */
#define BCHP_MT_CBUS_ABORT_STATUS                0x20d83a14 /* [RO][32] CBUS Abort Packet Status Register */
#define BCHP_MT_CBUS_LINK_CTRL_0                 0x20d83a18 /* [WO][32] CBUS Link Control Register 0 */
#define BCHP_MT_CBUS_LINK_CTRL_1                 0x20d83a1c /* [RW][32] CBUS Link Control Register 1 */
#define BCHP_MT_CBUS_LINK_STATUS                 0x20d83a20 /* [RO][32] CBUS Link Status Register */
#define BCHP_MT_CBUS_LINK_ERROR                  0x20d83a24 /* [RO][32] CBUS Link Error Register */
#define BCHP_MT_CBUS_LINK_TEST                   0x20d83a28 /* [RW][32] CBUS Link Layer Test Register */
#define BCHP_MT_CBUS_LINK_CFG_0                  0x20d83a2c /* [RW][32] CBUS Link Configuration Register 0 */
#define BCHP_MT_CBUS_LINK_CFG_1                  0x20d83a30 /* [RW][32] CBUS Link Configuration Register 1 */
#define BCHP_MT_CBUS_WAKE_CFG_0                  0x20d83a34 /* [RW][32] CBUS Wake Up Configuration Register 0 */
#define BCHP_MT_CBUS_WAKE_CFG_1                  0x20d83a38 /* [RW][32] CBUS Wake Up Configuration Register 1 */
#define BCHP_MT_CBUS_DISCOVERY_CFG               0x20d83a3c /* [RW][32] CBUS Discovery Configuration Register */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0           0x20d83a40 /* [RW][32] CBUS Link Layer Arbitration Configuration Register 0 */
#define BCHP_MT_CBUS_ARBITRATION_CFG_1           0x20d83a44 /* [RW][32] CBUS Link Layer Arbitration Configuration Register 1 */
#define BCHP_MT_CBUS_ARBITRATION_CFG_2           0x20d83a48 /* [RW][32] CBUS Link Layer Arbitration Configuration Register 2 */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3           0x20d83a4c /* [RW][32] CBUS Link Layer Arbitration Configuration Register 3 */
#define BCHP_MT_CBUS_INITIATOR_CFG_0             0x20d83a50 /* [RW][32] CBUS Initiator Configuration Register 0 */
#define BCHP_MT_CBUS_INITIATOR_CFG_1             0x20d83a54 /* [RW][32] CBUS Initiator Configuration Register 1 */
#define BCHP_MT_CBUS_INITIATOR_STATUS            0x20d83a58 /* [RO][32] CBUS Initiator Status Register */
#define BCHP_MT_CBUS_FOLLOWER_CFG                0x20d83a5c /* [RW][32] CBUS Follower Configuration Register */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0           0x20d83a60 /* [RO][32] CBUS Follower Status Register 0 */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1           0x20d83a64 /* [RO][32] CBUS Follower Status Register 1 */
#define BCHP_MT_CBUS_RX_FILTER_CFG               0x20d83a68 /* [RW][32] Rx Filter Configuration Register */
#define BCHP_MT_CBUS_RX_CDR_CFG_0                0x20d83a6c /* [RW][32] Rx Clock and Data Recovery Configuration Register 0 */
#define BCHP_MT_CBUS_RX_CDR_CFG_1                0x20d83a70 /* [RW][32] Rx Clock and Data Recovery Configuration Register 1 */
#define BCHP_MT_CBUS_RX_CDR_CFG_2                0x20d83a74 /* [RW][32] Rx Clock and Data Recovery Configuration Register 2 */
#define BCHP_MT_CBUS_RX_CDR_STATUS_0             0x20d83a78 /* [RO][32] Rx Clock and Data Recovery Status Register 0 */
#define BCHP_MT_CBUS_RX_CDR_STATUS_1             0x20d83a7c /* [RO][32] Rx Clock and Data Recovery Status Register 1 */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER           0x20d83a80 /* [RW][32] CBUS Impedance Change Filter Configuration Register */
#define BCHP_MT_CBUS_SPARE_REG_0                 0x20d83af0 /* [RW][32] Spare Register 0 */
#define BCHP_MT_CBUS_SPARE_REG_1                 0x20d83af4 /* [RW][32] Spare Register 1 */
#define BCHP_MT_CBUS_SPARE_REG_2                 0x20d83af8 /* [RW][32] Spare Register 2 */
#define BCHP_MT_CBUS_SPARE_REG_3                 0x20d83afc /* [RW][32] Spare Register 3 */

/***************************************************************************
 *SCHEDULER_CFG - CBUS Translation Layer Scheduler Configuration Register
 ***************************************************************************/
/* MT_CBUS :: SCHEDULER_CFG :: reserved0 [31:04] */
#define BCHP_MT_CBUS_SCHEDULER_CFG_reserved0_MASK                  0xfffffff0
#define BCHP_MT_CBUS_SCHEDULER_CFG_reserved0_SHIFT                 4

/* MT_CBUS :: SCHEDULER_CFG :: DISABLE_INBOUND [03:03] */
#define BCHP_MT_CBUS_SCHEDULER_CFG_DISABLE_INBOUND_MASK            0x00000008
#define BCHP_MT_CBUS_SCHEDULER_CFG_DISABLE_INBOUND_SHIFT           3
#define BCHP_MT_CBUS_SCHEDULER_CFG_DISABLE_INBOUND_DEFAULT         0x00000000

/* MT_CBUS :: SCHEDULER_CFG :: CLEAR_UNEXPECTED [02:02] */
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_UNEXPECTED_MASK           0x00000004
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_UNEXPECTED_SHIFT          2
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_UNEXPECTED_DEFAULT        0x00000000

/* MT_CBUS :: SCHEDULER_CFG :: CLEAR_DROP_CNT [01:01] */
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_DROP_CNT_MASK             0x00000002
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_DROP_CNT_SHIFT            1
#define BCHP_MT_CBUS_SCHEDULER_CFG_CLEAR_DROP_CNT_DEFAULT          0x00000000

/* MT_CBUS :: SCHEDULER_CFG :: INTERLEAVE_PACKETS [00:00] */
#define BCHP_MT_CBUS_SCHEDULER_CFG_INTERLEAVE_PACKETS_MASK         0x00000001
#define BCHP_MT_CBUS_SCHEDULER_CFG_INTERLEAVE_PACKETS_SHIFT        0
#define BCHP_MT_CBUS_SCHEDULER_CFG_INTERLEAVE_PACKETS_DEFAULT      0x00000000

/***************************************************************************
 *SCHEDULER_STATUS_0 - CBUS Translation Layer Scheduler Status Register 0
 ***************************************************************************/
/* MT_CBUS :: SCHEDULER_STATUS_0 :: reserved0 [31:27] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved0_MASK             0xf8000000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved0_SHIFT            27

/* MT_CBUS :: SCHEDULER_STATUS_0 :: UNEXPECTED_HEADER [26:25] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_HEADER_MASK     0x06000000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_HEADER_SHIFT    25

/* MT_CBUS :: SCHEDULER_STATUS_0 :: UNEXPECTED_CONTROL [24:24] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_CONTROL_MASK    0x01000000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_CONTROL_SHIFT   24

/* MT_CBUS :: SCHEDULER_STATUS_0 :: UNEXPECTED_PAYLOAD [23:16] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_PAYLOAD_MASK    0x00ff0000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_UNEXPECTED_PAYLOAD_SHIFT   16

/* MT_CBUS :: SCHEDULER_STATUS_0 :: reserved1 [15:10] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved1_MASK             0x0000fc00
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved1_SHIFT            10

/* MT_CBUS :: SCHEDULER_STATUS_0 :: CURRENT_STATE [09:08] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_CURRENT_STATE_MASK         0x00000300
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_CURRENT_STATE_SHIFT        8

/* MT_CBUS :: SCHEDULER_STATUS_0 :: DDC_REQUESTER_ABORT_ACTIVE [07:07] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_DDC_REQUESTER_ABORT_ACTIVE_MASK 0x00000080
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_DDC_REQUESTER_ABORT_ACTIVE_SHIFT 7

/* MT_CBUS :: SCHEDULER_STATUS_0 :: MSC_RESPONDER_OB_ABORT_ACTIVE [06:06] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_OB_ABORT_ACTIVE_MASK 0x00000040
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_OB_ABORT_ACTIVE_SHIFT 6

/* MT_CBUS :: SCHEDULER_STATUS_0 :: MSC_RESPONDER_IB_ABORT_ACTIVE [05:05] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_IB_ABORT_ACTIVE_MASK 0x00000020
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_IB_ABORT_ACTIVE_SHIFT 5

/* MT_CBUS :: SCHEDULER_STATUS_0 :: MSC_REQUESTER_ABORT_ACTIVE [04:04] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_REQUESTER_ABORT_ACTIVE_MASK 0x00000010
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_REQUESTER_ABORT_ACTIVE_SHIFT 4

/* MT_CBUS :: SCHEDULER_STATUS_0 :: reserved2 [03:03] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved2_MASK             0x00000008
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_reserved2_SHIFT            3

/* MT_CBUS :: SCHEDULER_STATUS_0 :: DDC_REQUESTER_ACTIVE [02:02] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_DDC_REQUESTER_ACTIVE_MASK  0x00000004
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_DDC_REQUESTER_ACTIVE_SHIFT 2

/* MT_CBUS :: SCHEDULER_STATUS_0 :: MSC_RESPONDER_ACTIVE [01:01] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_ACTIVE_MASK  0x00000002
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_RESPONDER_ACTIVE_SHIFT 1

/* MT_CBUS :: SCHEDULER_STATUS_0 :: MSC_REQUESTER_ACTIVE [00:00] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_REQUESTER_ACTIVE_MASK  0x00000001
#define BCHP_MT_CBUS_SCHEDULER_STATUS_0_MSC_REQUESTER_ACTIVE_SHIFT 0

/***************************************************************************
 *SCHEDULER_STATUS_1 - CBUS Translation Layer Scheduler Status Register 1
 ***************************************************************************/
/* MT_CBUS :: SCHEDULER_STATUS_1 :: RSVD_PACKET_DROP_CNT [31:24] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_RSVD_PACKET_DROP_CNT_MASK  0xff000000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_RSVD_PACKET_DROP_CNT_SHIFT 24

/* MT_CBUS :: SCHEDULER_STATUS_1 :: VSC_PACKET_DROP_CNT [23:16] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_VSC_PACKET_DROP_CNT_MASK   0x00ff0000
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_VSC_PACKET_DROP_CNT_SHIFT  16

/* MT_CBUS :: SCHEDULER_STATUS_1 :: DDC_PACKET_DROP_CNT [15:08] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_DDC_PACKET_DROP_CNT_MASK   0x0000ff00
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_DDC_PACKET_DROP_CNT_SHIFT  8

/* MT_CBUS :: SCHEDULER_STATUS_1 :: MSC_PACKET_DROP_CNT [07:00] */
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_MSC_PACKET_DROP_CNT_MASK   0x000000ff
#define BCHP_MT_CBUS_SCHEDULER_STATUS_1_MSC_PACKET_DROP_CNT_SHIFT  0

/***************************************************************************
 *ABORT_CTRL - CBUS Abort Packet Control Register
 ***************************************************************************/
/* MT_CBUS :: ABORT_CTRL :: reserved0 [31:04] */
#define BCHP_MT_CBUS_ABORT_CTRL_reserved0_MASK                     0xfffffff0
#define BCHP_MT_CBUS_ABORT_CTRL_reserved0_SHIFT                    4

/* MT_CBUS :: ABORT_CTRL :: CLEAR_DDC [03:03] */
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_DDC_MASK                     0x00000008
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_DDC_SHIFT                    3
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_DDC_DEFAULT                  0x00000000

/* MT_CBUS :: ABORT_CTRL :: CLEAR_MSC [02:02] */
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_MSC_MASK                     0x00000004
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_MSC_SHIFT                    2
#define BCHP_MT_CBUS_ABORT_CTRL_CLEAR_MSC_DEFAULT                  0x00000000

/* MT_CBUS :: ABORT_CTRL :: START_DDC [01:01] */
#define BCHP_MT_CBUS_ABORT_CTRL_START_DDC_MASK                     0x00000002
#define BCHP_MT_CBUS_ABORT_CTRL_START_DDC_SHIFT                    1
#define BCHP_MT_CBUS_ABORT_CTRL_START_DDC_DEFAULT                  0x00000000

/* MT_CBUS :: ABORT_CTRL :: START_MSC [00:00] */
#define BCHP_MT_CBUS_ABORT_CTRL_START_MSC_MASK                     0x00000001
#define BCHP_MT_CBUS_ABORT_CTRL_START_MSC_SHIFT                    0
#define BCHP_MT_CBUS_ABORT_CTRL_START_MSC_DEFAULT                  0x00000000

/***************************************************************************
 *ABORT_CFG - CBUS Abort Packet Configuration Register
 ***************************************************************************/
/* MT_CBUS :: ABORT_CFG :: reserved0 [31:26] */
#define BCHP_MT_CBUS_ABORT_CFG_reserved0_MASK                      0xfc000000
#define BCHP_MT_CBUS_ABORT_CFG_reserved0_SHIFT                     26

/* MT_CBUS :: ABORT_CFG :: OUTBOUND_ABORT_ALL [25:25] */
#define BCHP_MT_CBUS_ABORT_CFG_OUTBOUND_ABORT_ALL_MASK             0x02000000
#define BCHP_MT_CBUS_ABORT_CFG_OUTBOUND_ABORT_ALL_SHIFT            25
#define BCHP_MT_CBUS_ABORT_CFG_OUTBOUND_ABORT_ALL_DEFAULT          0x00000000

/* MT_CBUS :: ABORT_CFG :: INBOUND_ABORT_ALL [24:24] */
#define BCHP_MT_CBUS_ABORT_CFG_INBOUND_ABORT_ALL_MASK              0x01000000
#define BCHP_MT_CBUS_ABORT_CFG_INBOUND_ABORT_ALL_SHIFT             24
#define BCHP_MT_CBUS_ABORT_CFG_INBOUND_ABORT_ALL_DEFAULT           0x00000000

/* MT_CBUS :: ABORT_CFG :: RESPONDER_DELAY [23:12] */
#define BCHP_MT_CBUS_ABORT_CFG_RESPONDER_DELAY_MASK                0x00fff000
#define BCHP_MT_CBUS_ABORT_CFG_RESPONDER_DELAY_SHIFT               12
#define BCHP_MT_CBUS_ABORT_CFG_RESPONDER_DELAY_DEFAULT             0x00000000

/* MT_CBUS :: ABORT_CFG :: ABORT_DELAY [11:00] */
#define BCHP_MT_CBUS_ABORT_CFG_ABORT_DELAY_MASK                    0x00000fff
#define BCHP_MT_CBUS_ABORT_CFG_ABORT_DELAY_SHIFT                   0
#define BCHP_MT_CBUS_ABORT_CFG_ABORT_DELAY_DEFAULT                 0x000007d0

/***************************************************************************
 *ABORT_STATUS - CBUS Abort Packet Status Register
 ***************************************************************************/
/* MT_CBUS :: ABORT_STATUS :: DDC_TIMEOUT_CNT [31:20] */
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_TIMEOUT_CNT_MASK             0xfff00000
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_TIMEOUT_CNT_SHIFT            20

/* MT_CBUS :: ABORT_STATUS :: DDC_STATE_SW_ABORT_WAIT [19:19] */
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_SW_ABORT_WAIT_MASK     0x00080000
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_SW_ABORT_WAIT_SHIFT    19

/* MT_CBUS :: ABORT_STATUS :: DDC_STATE_RESPONDER_OK [18:18] */
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_RESPONDER_OK_MASK      0x00040000
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_RESPONDER_OK_SHIFT     18

/* MT_CBUS :: ABORT_STATUS :: DDC_STATE_ABORT_WAIT [17:17] */
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_ABORT_WAIT_MASK        0x00020000
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_ABORT_WAIT_SHIFT       17

/* MT_CBUS :: ABORT_STATUS :: DDC_STATE_IDLE [16:16] */
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_IDLE_MASK              0x00010000
#define BCHP_MT_CBUS_ABORT_STATUS_DDC_STATE_IDLE_SHIFT             16

/* MT_CBUS :: ABORT_STATUS :: MSC_TIMEOUT_CNT [15:04] */
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_TIMEOUT_CNT_MASK             0x0000fff0
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_TIMEOUT_CNT_SHIFT            4

/* MT_CBUS :: ABORT_STATUS :: MSC_STATE_SW_ABORT_WAIT [03:03] */
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_SW_ABORT_WAIT_MASK     0x00000008
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_SW_ABORT_WAIT_SHIFT    3

/* MT_CBUS :: ABORT_STATUS :: MSC_STATE_RESPONDER_OK [02:02] */
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_RESPONDER_OK_MASK      0x00000004
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_RESPONDER_OK_SHIFT     2

/* MT_CBUS :: ABORT_STATUS :: MSC_STATE_ABORT_WAIT [01:01] */
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_ABORT_WAIT_MASK        0x00000002
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_ABORT_WAIT_SHIFT       1

/* MT_CBUS :: ABORT_STATUS :: MSC_STATE_IDLE [00:00] */
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_IDLE_MASK              0x00000001
#define BCHP_MT_CBUS_ABORT_STATUS_MSC_STATE_IDLE_SHIFT             0

/***************************************************************************
 *LINK_CTRL_0 - CBUS Link Control Register 0
 ***************************************************************************/
/* MT_CBUS :: LINK_CTRL_0 :: reserved0 [31:04] */
#define BCHP_MT_CBUS_LINK_CTRL_0_reserved0_MASK                    0xfffffff0
#define BCHP_MT_CBUS_LINK_CTRL_0_reserved0_SHIFT                   4

/* MT_CBUS :: LINK_CTRL_0 :: START_DISCONNECT [03:03] */
#define BCHP_MT_CBUS_LINK_CTRL_0_START_DISCONNECT_MASK             0x00000008
#define BCHP_MT_CBUS_LINK_CTRL_0_START_DISCONNECT_SHIFT            3
#define BCHP_MT_CBUS_LINK_CTRL_0_START_DISCONNECT_DEFAULT          0x00000000

/* MT_CBUS :: LINK_CTRL_0 :: FORCE_DISCOVERED [02:02] */
#define BCHP_MT_CBUS_LINK_CTRL_0_FORCE_DISCOVERED_MASK             0x00000004
#define BCHP_MT_CBUS_LINK_CTRL_0_FORCE_DISCOVERED_SHIFT            2
#define BCHP_MT_CBUS_LINK_CTRL_0_FORCE_DISCOVERED_DEFAULT          0x00000000

/* MT_CBUS :: LINK_CTRL_0 :: STOP_WAKE_UP [01:01] */
#define BCHP_MT_CBUS_LINK_CTRL_0_STOP_WAKE_UP_MASK                 0x00000002
#define BCHP_MT_CBUS_LINK_CTRL_0_STOP_WAKE_UP_SHIFT                1
#define BCHP_MT_CBUS_LINK_CTRL_0_STOP_WAKE_UP_DEFAULT              0x00000000

/* MT_CBUS :: LINK_CTRL_0 :: START_WAKE_UP [00:00] */
#define BCHP_MT_CBUS_LINK_CTRL_0_START_WAKE_UP_MASK                0x00000001
#define BCHP_MT_CBUS_LINK_CTRL_0_START_WAKE_UP_SHIFT               0
#define BCHP_MT_CBUS_LINK_CTRL_0_START_WAKE_UP_DEFAULT             0x00000000

/***************************************************************************
 *LINK_CTRL_1 - CBUS Link Control Register 1
 ***************************************************************************/
/* MT_CBUS :: LINK_CTRL_1 :: reserved0 [31:09] */
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved0_MASK                    0xfffffe00
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved0_SHIFT                   9

/* MT_CBUS :: LINK_CTRL_1 :: CLEAR_LINK_ERROR [08:08] */
#define BCHP_MT_CBUS_LINK_CTRL_1_CLEAR_LINK_ERROR_MASK             0x00000100
#define BCHP_MT_CBUS_LINK_CTRL_1_CLEAR_LINK_ERROR_SHIFT            8
#define BCHP_MT_CBUS_LINK_CTRL_1_CLEAR_LINK_ERROR_DEFAULT          0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: reserved1 [07:07] */
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved1_MASK                    0x00000080
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved1_SHIFT                   7

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_PULL_UP [06:06] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_PULL_UP_MASK             0x00000040
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_PULL_UP_SHIFT            6
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_PULL_UP_DEFAULT          0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_Z_SRC_ON_EN [05:05] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_ON_EN_MASK         0x00000020
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_ON_EN_SHIFT        5
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_ON_EN_DEFAULT      0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_Z_SRC_DISCOVER_EN [04:04] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_DISCOVER_EN_MASK   0x00000010
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_DISCOVER_EN_SHIFT  4
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_Z_SRC_DISCOVER_EN_DEFAULT 0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: reserved2 [03:03] */
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved2_MASK                    0x00000008
#define BCHP_MT_CBUS_LINK_CTRL_1_reserved2_SHIFT                   3

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_OUTPUT [02:02] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_MASK              0x00000004
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_SHIFT             2
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_DEFAULT           0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_OUTPUT_DATA [01:01] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_DATA_MASK         0x00000002
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_DATA_SHIFT        1
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_DATA_DEFAULT      0x00000000

/* MT_CBUS :: LINK_CTRL_1 :: OVERRIDE_OUTPUT_ENABLE [00:00] */
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_ENABLE_MASK       0x00000001
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_ENABLE_SHIFT      0
#define BCHP_MT_CBUS_LINK_CTRL_1_OVERRIDE_OUTPUT_ENABLE_DEFAULT    0x00000000

/***************************************************************************
 *LINK_STATUS - CBUS Link Status Register
 ***************************************************************************/
/* MT_CBUS :: LINK_STATUS :: reserved0 [31:09] */
#define BCHP_MT_CBUS_LINK_STATUS_reserved0_MASK                    0xfffffe00
#define BCHP_MT_CBUS_LINK_STATUS_reserved0_SHIFT                   9

/* MT_CBUS :: LINK_STATUS :: CBUS_DIN [08:08] */
#define BCHP_MT_CBUS_LINK_STATUS_CBUS_DIN_MASK                     0x00000100
#define BCHP_MT_CBUS_LINK_STATUS_CBUS_DIN_SHIFT                    8

/* MT_CBUS :: LINK_STATUS :: reserved1 [07:06] */
#define BCHP_MT_CBUS_LINK_STATUS_reserved1_MASK                    0x000000c0
#define BCHP_MT_CBUS_LINK_STATUS_reserved1_SHIFT                   6

/* MT_CBUS :: LINK_STATUS :: BUS_OWNER [05:04] */
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_MASK                    0x00000030
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_SHIFT                   4
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_none                    0
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_wake_up_and_discovery   1
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_me                      2
#define BCHP_MT_CBUS_LINK_STATUS_BUS_OWNER_ext                     3

/* MT_CBUS :: LINK_STATUS :: reserved2 [03:03] */
#define BCHP_MT_CBUS_LINK_STATUS_reserved2_MASK                    0x00000008
#define BCHP_MT_CBUS_LINK_STATUS_reserved2_SHIFT                   3

/* MT_CBUS :: LINK_STATUS :: BUS_STATE [02:00] */
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_MASK                    0x00000007
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_SHIFT                   0
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_initial                 0
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_wake_up_in_progress     1
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_discovery_in_progress   2
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_discovery_failed        3
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_discovery_successful    4
#define BCHP_MT_CBUS_LINK_STATUS_BUS_STATE_active                  5

/***************************************************************************
 *LINK_ERROR - CBUS Link Error Register
 ***************************************************************************/
/* MT_CBUS :: LINK_ERROR :: reserved0 [31:05] */
#define BCHP_MT_CBUS_LINK_ERROR_reserved0_MASK                     0xffffffe0
#define BCHP_MT_CBUS_LINK_ERROR_reserved0_SHIFT                    5

/* MT_CBUS :: LINK_ERROR :: NACK_DETECTED [04:04] */
#define BCHP_MT_CBUS_LINK_ERROR_NACK_DETECTED_MASK                 0x00000010
#define BCHP_MT_CBUS_LINK_ERROR_NACK_DETECTED_SHIFT                4

/* MT_CBUS :: LINK_ERROR :: INVALID_PARITY [03:03] */
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_PARITY_MASK                0x00000008
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_PARITY_SHIFT               3

/* MT_CBUS :: LINK_ERROR :: INVALID_CODE [02:02] */
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_CODE_MASK                  0x00000004
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_CODE_SHIFT                 2

/* MT_CBUS :: LINK_ERROR :: INVALID_SYNC [01:01] */
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_SYNC_MASK                  0x00000002
#define BCHP_MT_CBUS_LINK_ERROR_INVALID_SYNC_SHIFT                 1

/* MT_CBUS :: LINK_ERROR :: UNSTABLE_UI [00:00] */
#define BCHP_MT_CBUS_LINK_ERROR_UNSTABLE_UI_MASK                   0x00000001
#define BCHP_MT_CBUS_LINK_ERROR_UNSTABLE_UI_SHIFT                  0

/***************************************************************************
 *LINK_TEST - CBUS Link Layer Test Register
 ***************************************************************************/
/* MT_CBUS :: LINK_TEST :: reserved0 [31:15] */
#define BCHP_MT_CBUS_LINK_TEST_reserved0_MASK                      0xffff8000
#define BCHP_MT_CBUS_LINK_TEST_reserved0_SHIFT                     15

/* MT_CBUS :: LINK_TEST :: LOOPBACK_TX2RX [14:14] */
#define BCHP_MT_CBUS_LINK_TEST_LOOPBACK_TX2RX_MASK                 0x00004000
#define BCHP_MT_CBUS_LINK_TEST_LOOPBACK_TX2RX_SHIFT                14
#define BCHP_MT_CBUS_LINK_TEST_LOOPBACK_TX2RX_DEFAULT              0x00000000

/* MT_CBUS :: LINK_TEST :: SEND_CONTINUOUS [13:13] */
#define BCHP_MT_CBUS_LINK_TEST_SEND_CONTINUOUS_MASK                0x00002000
#define BCHP_MT_CBUS_LINK_TEST_SEND_CONTINUOUS_SHIFT               13
#define BCHP_MT_CBUS_LINK_TEST_SEND_CONTINUOUS_DEFAULT             0x00000000

/* MT_CBUS :: LINK_TEST :: SEND_SINGLE [12:12] */
#define BCHP_MT_CBUS_LINK_TEST_SEND_SINGLE_MASK                    0x00001000
#define BCHP_MT_CBUS_LINK_TEST_SEND_SINGLE_SHIFT                   12
#define BCHP_MT_CBUS_LINK_TEST_SEND_SINGLE_DEFAULT                 0x00000000

/* MT_CBUS :: LINK_TEST :: reserved1 [11:11] */
#define BCHP_MT_CBUS_LINK_TEST_reserved1_MASK                      0x00000800
#define BCHP_MT_CBUS_LINK_TEST_reserved1_SHIFT                     11

/* MT_CBUS :: LINK_TEST :: HEADER [10:09] */
#define BCHP_MT_CBUS_LINK_TEST_HEADER_MASK                         0x00000600
#define BCHP_MT_CBUS_LINK_TEST_HEADER_SHIFT                        9
#define BCHP_MT_CBUS_LINK_TEST_HEADER_DEFAULT                      0x00000000

/* MT_CBUS :: LINK_TEST :: CONTROL [08:08] */
#define BCHP_MT_CBUS_LINK_TEST_CONTROL_MASK                        0x00000100
#define BCHP_MT_CBUS_LINK_TEST_CONTROL_SHIFT                       8
#define BCHP_MT_CBUS_LINK_TEST_CONTROL_DEFAULT                     0x00000000

/* MT_CBUS :: LINK_TEST :: PAYLOAD [07:00] */
#define BCHP_MT_CBUS_LINK_TEST_PAYLOAD_MASK                        0x000000ff
#define BCHP_MT_CBUS_LINK_TEST_PAYLOAD_SHIFT                       0
#define BCHP_MT_CBUS_LINK_TEST_PAYLOAD_DEFAULT                     0x00000000

/***************************************************************************
 *LINK_CFG_0 - CBUS Link Configuration Register 0
 ***************************************************************************/
/* MT_CBUS :: LINK_CFG_0 :: reserved0 [31:23] */
#define BCHP_MT_CBUS_LINK_CFG_0_reserved0_MASK                     0xff800000
#define BCHP_MT_CBUS_LINK_CFG_0_reserved0_SHIFT                    23

/* MT_CBUS :: LINK_CFG_0 :: INVERT_INPUT_DATA [22:22] */
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_INPUT_DATA_MASK             0x00400000
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_INPUT_DATA_SHIFT            22
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_INPUT_DATA_DEFAULT          0x00000000

/* MT_CBUS :: LINK_CFG_0 :: INVERT_OUTPUT_DATA [21:21] */
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_DATA_MASK            0x00200000
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_DATA_SHIFT           21
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_DATA_DEFAULT         0x00000000

/* MT_CBUS :: LINK_CFG_0 :: INVERT_OUTPUT_ENABLE [20:20] */
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_ENABLE_MASK          0x00100000
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_ENABLE_SHIFT         20
#define BCHP_MT_CBUS_LINK_CFG_0_INVERT_OUTPUT_ENABLE_DEFAULT       0x00000000

/* MT_CBUS :: LINK_CFG_0 :: T_DRV_HI_CBUS [19:12] */
#define BCHP_MT_CBUS_LINK_CFG_0_T_DRV_HI_CBUS_MASK                 0x000ff000
#define BCHP_MT_CBUS_LINK_CFG_0_T_DRV_HI_CBUS_SHIFT                12
#define BCHP_MT_CBUS_LINK_CFG_0_T_DRV_HI_CBUS_DEFAULT              0x0000000f

/* MT_CBUS :: LINK_CFG_0 :: FASTEST [11:11] */
#define BCHP_MT_CBUS_LINK_CFG_0_FASTEST_MASK                       0x00000800
#define BCHP_MT_CBUS_LINK_CFG_0_FASTEST_SHIFT                      11
#define BCHP_MT_CBUS_LINK_CFG_0_FASTEST_DEFAULT                    0x00000000

/* MT_CBUS :: LINK_CFG_0 :: reserved1 [10:09] */
#define BCHP_MT_CBUS_LINK_CFG_0_reserved1_MASK                     0x00000600
#define BCHP_MT_CBUS_LINK_CFG_0_reserved1_SHIFT                    9

/* MT_CBUS :: LINK_CFG_0 :: TX_UI_PERIOD [08:00] */
#define BCHP_MT_CBUS_LINK_CFG_0_TX_UI_PERIOD_MASK                  0x000001ff
#define BCHP_MT_CBUS_LINK_CFG_0_TX_UI_PERIOD_SHIFT                 0
#define BCHP_MT_CBUS_LINK_CFG_0_TX_UI_PERIOD_DEFAULT               0x00000036

/***************************************************************************
 *LINK_CFG_1 - CBUS Link Configuration Register 1
 ***************************************************************************/
/* MT_CBUS :: LINK_CFG_1 :: reserved0 [31:22] */
#define BCHP_MT_CBUS_LINK_CFG_1_reserved0_MASK                     0xffc00000
#define BCHP_MT_CBUS_LINK_CFG_1_reserved0_SHIFT                    22

/* MT_CBUS :: LINK_CFG_1 :: T_DISCONNECT_IN [21:12] */
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_IN_MASK               0x003ff000
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_IN_SHIFT              12
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_IN_DEFAULT            0x000000f0

/* MT_CBUS :: LINK_CFG_1 :: reserved1 [11:10] */
#define BCHP_MT_CBUS_LINK_CFG_1_reserved1_MASK                     0x00000c00
#define BCHP_MT_CBUS_LINK_CFG_1_reserved1_SHIFT                    10

/* MT_CBUS :: LINK_CFG_1 :: T_DISCONNECT_OUT [09:00] */
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_OUT_MASK              0x000003ff
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_OUT_SHIFT             0
#define BCHP_MT_CBUS_LINK_CFG_1_T_DISCONNECT_OUT_DEFAULT           0x000000f0

/***************************************************************************
 *WAKE_CFG_0 - CBUS Wake Up Configuration Register 0
 ***************************************************************************/
/* MT_CBUS :: WAKE_CFG_0 :: reserved0 [31:14] */
#define BCHP_MT_CBUS_WAKE_CFG_0_reserved0_MASK                     0xffffc000
#define BCHP_MT_CBUS_WAKE_CFG_0_reserved0_SHIFT                    14

/* MT_CBUS :: WAKE_CFG_0 :: INVERT_Z_SRC_ON_EN [13:13] */
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_ON_EN_MASK            0x00002000
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_ON_EN_SHIFT           13
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_ON_EN_DEFAULT         0x00000000

/* MT_CBUS :: WAKE_CFG_0 :: INVERT_Z_SRC_DISCOVER_EN [12:12] */
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_DISCOVER_EN_MASK      0x00001000
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_DISCOVER_EN_SHIFT     12
#define BCHP_MT_CBUS_WAKE_CFG_0_INVERT_Z_SRC_DISCOVER_EN_DEFAULT   0x00000000

/* MT_CBUS :: WAKE_CFG_0 :: reserved1 [11:10] */
#define BCHP_MT_CBUS_WAKE_CFG_0_reserved1_MASK                     0x00000c00
#define BCHP_MT_CBUS_WAKE_CFG_0_reserved1_SHIFT                    10

/* MT_CBUS :: WAKE_CFG_0 :: T_SRC_WAKE_START [09:00] */
#define BCHP_MT_CBUS_WAKE_CFG_0_T_SRC_WAKE_START_MASK              0x000003ff
#define BCHP_MT_CBUS_WAKE_CFG_0_T_SRC_WAKE_START_SHIFT             0
#define BCHP_MT_CBUS_WAKE_CFG_0_T_SRC_WAKE_START_DEFAULT           0x00000064

/***************************************************************************
 *WAKE_CFG_1 - CBUS Wake Up Configuration Register 1
 ***************************************************************************/
/* MT_CBUS :: WAKE_CFG_1 :: reserved0 [31:28] */
#define BCHP_MT_CBUS_WAKE_CFG_1_reserved0_MASK                     0xf0000000
#define BCHP_MT_CBUS_WAKE_CFG_1_reserved0_SHIFT                    28

/* MT_CBUS :: WAKE_CFG_1 :: reserved1 [27:26] */
#define BCHP_MT_CBUS_WAKE_CFG_1_reserved1_MASK                     0x0c000000
#define BCHP_MT_CBUS_WAKE_CFG_1_reserved1_SHIFT                    26

/* MT_CBUS :: WAKE_CFG_1 :: T_SRC_WAKE_TO_DISCOVER [25:16] */
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_TO_DISCOVER_MASK        0x03ff0000
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_TO_DISCOVER_SHIFT       16
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_TO_DISCOVER_DEFAULT     0x00000064

/* MT_CBUS :: WAKE_CFG_1 :: T_SRC_WAKE_PULSE_WIDTH_2 [15:08] */
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_2_MASK      0x0000ff00
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_2_SHIFT     8
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_2_DEFAULT   0x0000003c

/* MT_CBUS :: WAKE_CFG_1 :: T_SRC_WAKE_PULSE_WIDTH_1 [07:00] */
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_1_MASK      0x000000ff
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_1_SHIFT     0
#define BCHP_MT_CBUS_WAKE_CFG_1_T_SRC_WAKE_PULSE_WIDTH_1_DEFAULT   0x00000014

/***************************************************************************
 *DISCOVERY_CFG - CBUS Discovery Configuration Register
 ***************************************************************************/
/* MT_CBUS :: DISCOVERY_CFG :: reserved0 [31:30] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_reserved0_MASK                  0xc0000000
#define BCHP_MT_CBUS_DISCOVERY_CFG_reserved0_SHIFT                 30

/* MT_CBUS :: DISCOVERY_CFG :: N_SRC_PULSE_COUNT_MAX [29:24] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MAX_MASK      0x3f000000
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MAX_SHIFT     24
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MAX_DEFAULT   0x00000014

/* MT_CBUS :: DISCOVERY_CFG :: reserved1 [23:22] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_reserved1_MASK                  0x00c00000
#define BCHP_MT_CBUS_DISCOVERY_CFG_reserved1_SHIFT                 22

/* MT_CBUS :: DISCOVERY_CFG :: N_SRC_PULSE_COUNT_MIN [21:16] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MIN_MASK      0x003f0000
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MIN_SHIFT     16
#define BCHP_MT_CBUS_DISCOVERY_CFG_N_SRC_PULSE_COUNT_MIN_DEFAULT   0x00000006

/* MT_CBUS :: DISCOVERY_CFG :: T_SRC_CONN [15:08] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_CONN_MASK                 0x0000ff00
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_CONN_SHIFT                8
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_CONN_DEFAULT              0x00000064

/* MT_CBUS :: DISCOVERY_CFG :: T_SRC_PULSE_WIDTH [07:00] */
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_PULSE_WIDTH_MASK          0x000000ff
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_PULSE_WIDTH_SHIFT         0
#define BCHP_MT_CBUS_DISCOVERY_CFG_T_SRC_PULSE_WIDTH_DEFAULT       0x00000064

/***************************************************************************
 *ARBITRATION_CFG_0 - CBUS Link Layer Arbitration Configuration Register 0
 ***************************************************************************/
/* MT_CBUS :: ARBITRATION_CFG_0 :: T_REQ_CONT_FOLLOWER [31:30] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_FOLLOWER_MASK    0xc0000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_FOLLOWER_SHIFT   30
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_FOLLOWER_DEFAULT 0x00000002

/* MT_CBUS :: ARBITRATION_CFG_0 :: T_REQ_CONT_INITIATOR [29:28] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_INITIATOR_MASK   0x30000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_INITIATOR_SHIFT  28
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_CONT_INITIATOR_DEFAULT 0x00000002

/* MT_CBUS :: ARBITRATION_CFG_0 :: reserved0 [27:26] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved0_MASK              0x0c000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved0_SHIFT             26

/* MT_CBUS :: ARBITRATION_CFG_0 :: T_REQ_OPP [25:24] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_OPP_MASK              0x03000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_OPP_SHIFT             24
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_OPP_DEFAULT           0x00000001

/* MT_CBUS :: ARBITRATION_CFG_0 :: reserved1 [23:22] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved1_MASK              0x00c00000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved1_SHIFT             22

/* MT_CBUS :: ARBITRATION_CFG_0 :: T_REQ_HOLD [21:16] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_HOLD_MASK             0x003f0000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_HOLD_SHIFT            16
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_REQ_HOLD_DEFAULT          0x00000008

/* MT_CBUS :: ARBITRATION_CFG_0 :: reserved2 [15:14] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved2_MASK              0x0000c000
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved2_SHIFT             14

/* MT_CBUS :: ARBITRATION_CFG_0 :: T_WAIT [13:08] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_WAIT_MASK                 0x00003f00
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_WAIT_SHIFT                8
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_T_WAIT_DEFAULT              0x0000000c

/* MT_CBUS :: ARBITRATION_CFG_0 :: reserved3 [07:06] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved3_MASK              0x000000c0
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_reserved3_SHIFT             6

/* MT_CBUS :: ARBITRATION_CFG_0 :: MAX_PACKETS [05:00] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_MAX_PACKETS_MASK            0x0000003f
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_MAX_PACKETS_SHIFT           0
#define BCHP_MT_CBUS_ARBITRATION_CFG_0_MAX_PACKETS_DEFAULT         0x00000018

/***************************************************************************
 *ARBITRATION_CFG_1 - CBUS Link Layer Arbitration Configuration Register 1
 ***************************************************************************/
/* MT_CBUS :: ARBITRATION_CFG_1 :: CHANNEL_SWITCH_DELAY [31:26] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_CHANNEL_SWITCH_DELAY_MASK   0xfc000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_CHANNEL_SWITCH_DELAY_SHIFT  26
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_CHANNEL_SWITCH_DELAY_DEFAULT 0x00000000

/* MT_CBUS :: ARBITRATION_CFG_1 :: T_START_ARBITRATE [25:16] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_START_ARBITRATE_MASK      0x03ff0000
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_START_ARBITRATE_SHIFT     16
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_START_ARBITRATE_DEFAULT   0x000001f4

/* MT_CBUS :: ARBITRATION_CFG_1 :: T_RESP_HOLD [15:12] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_RESP_HOLD_MASK            0x0000f000
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_RESP_HOLD_SHIFT           12
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_T_RESP_HOLD_DEFAULT         0x00000004

/* MT_CBUS :: ARBITRATION_CFG_1 :: ARB_HIGH_MIN [11:00] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_ARB_HIGH_MIN_MASK           0x00000fff
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_ARB_HIGH_MIN_SHIFT          0
#define BCHP_MT_CBUS_ARBITRATION_CFG_1_ARB_HIGH_MIN_DEFAULT        0x00000103

/***************************************************************************
 *ARBITRATION_CFG_2 - CBUS Link Layer Arbitration Configuration Register 2
 ***************************************************************************/
/* MT_CBUS :: ARBITRATION_CFG_2 :: reserved0 [31:24] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_reserved0_MASK              0xff000000
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_reserved0_SHIFT             24

/* MT_CBUS :: ARBITRATION_CFG_2 :: ARB_LOW_MAX [23:12] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MAX_MASK            0x00fff000
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MAX_SHIFT           12
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MAX_DEFAULT         0x00000082

/* MT_CBUS :: ARBITRATION_CFG_2 :: ARB_LOW_MIN [11:00] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MIN_MASK            0x00000fff
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MIN_SHIFT           0
#define BCHP_MT_CBUS_ARBITRATION_CFG_2_ARB_LOW_MIN_DEFAULT         0x00000056

/***************************************************************************
 *ARBITRATION_CFG_3 - CBUS Link Layer Arbitration Configuration Register 3
 ***************************************************************************/
/* MT_CBUS :: ARBITRATION_CFG_3 :: reserved0 [31:20] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_reserved0_MASK              0xfff00000
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_reserved0_SHIFT             20

/* MT_CBUS :: ARBITRATION_CFG_3 :: KEEP_OUT [19:16] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_KEEP_OUT_MASK               0x000f0000
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_KEEP_OUT_SHIFT              16
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_KEEP_OUT_DEFAULT            0x00000004

/* MT_CBUS :: ARBITRATION_CFG_3 :: reserved1 [15:14] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_reserved1_MASK              0x0000c000
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_reserved1_SHIFT             14

/* MT_CBUS :: ARBITRATION_CFG_3 :: LOOPBACK_LATENCY [13:08] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_LOOPBACK_LATENCY_MASK       0x00003f00
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_LOOPBACK_LATENCY_SHIFT      8
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_LOOPBACK_LATENCY_DEFAULT    0x0000000e

/* MT_CBUS :: ARBITRATION_CFG_3 :: COOL_OFF [07:00] */
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_COOL_OFF_MASK               0x000000ff
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_COOL_OFF_SHIFT              0
#define BCHP_MT_CBUS_ARBITRATION_CFG_3_COOL_OFF_DEFAULT            0x00000005

/***************************************************************************
 *INITIATOR_CFG_0 - CBUS Initiator Configuration Register 0
 ***************************************************************************/
/* MT_CBUS :: INITIATOR_CFG_0 :: reserved0 [31:21] */
#define BCHP_MT_CBUS_INITIATOR_CFG_0_reserved0_MASK                0xffe00000
#define BCHP_MT_CBUS_INITIATOR_CFG_0_reserved0_SHIFT               21

/* MT_CBUS :: INITIATOR_CFG_0 :: MAX_ACK_DURATION [20:12] */
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MAX_ACK_DURATION_MASK         0x001ff000
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MAX_ACK_DURATION_SHIFT        12
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MAX_ACK_DURATION_DEFAULT      0x0000003c

/* MT_CBUS :: INITIATOR_CFG_0 :: reserved1 [11:09] */
#define BCHP_MT_CBUS_INITIATOR_CFG_0_reserved1_MASK                0x00000e00
#define BCHP_MT_CBUS_INITIATOR_CFG_0_reserved1_SHIFT               9

/* MT_CBUS :: INITIATOR_CFG_0 :: MIN_ACK_DURATION [08:00] */
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MIN_ACK_DURATION_MASK         0x000001ff
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MIN_ACK_DURATION_SHIFT        0
#define BCHP_MT_CBUS_INITIATOR_CFG_0_MIN_ACK_DURATION_DEFAULT      0x00000001

/***************************************************************************
 *INITIATOR_CFG_1 - CBUS Initiator Configuration Register 1
 ***************************************************************************/
/* MT_CBUS :: INITIATOR_CFG_1 :: reserved0 [31:22] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved0_MASK                0xffc00000
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved0_SHIFT               22

/* MT_CBUS :: INITIATOR_CFG_1 :: FAST_TERMINATE [21:21] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_FAST_TERMINATE_MASK           0x00200000
#define BCHP_MT_CBUS_INITIATOR_CFG_1_FAST_TERMINATE_SHIFT          21
#define BCHP_MT_CBUS_INITIATOR_CFG_1_FAST_TERMINATE_DEFAULT        0x00000000

/* MT_CBUS :: INITIATOR_CFG_1 :: CLEAR_STATUS [20:20] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_CLEAR_STATUS_MASK             0x00100000
#define BCHP_MT_CBUS_INITIATOR_CFG_1_CLEAR_STATUS_SHIFT            20
#define BCHP_MT_CBUS_INITIATOR_CFG_1_CLEAR_STATUS_DEFAULT          0x00000000

/* MT_CBUS :: INITIATOR_CFG_1 :: reserved1 [19:18] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved1_MASK                0x000c0000
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved1_SHIFT               18

/* MT_CBUS :: INITIATOR_CFG_1 :: MAX_RETRIES [17:12] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_RETRIES_MASK              0x0003f000
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_RETRIES_SHIFT             12
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_RETRIES_DEFAULT           0x00000020

/* MT_CBUS :: INITIATOR_CFG_1 :: reserved2 [11:09] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved2_MASK                0x00000e00
#define BCHP_MT_CBUS_INITIATOR_CFG_1_reserved2_SHIFT               9

/* MT_CBUS :: INITIATOR_CFG_1 :: MAX_ACK_WAIT [08:00] */
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_ACK_WAIT_MASK             0x000001ff
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_ACK_WAIT_SHIFT            0
#define BCHP_MT_CBUS_INITIATOR_CFG_1_MAX_ACK_WAIT_DEFAULT          0x0000003c

/***************************************************************************
 *INITIATOR_STATUS - CBUS Initiator Status Register
 ***************************************************************************/
/* MT_CBUS :: INITIATOR_STATUS :: reserved0 [31:22] */
#define BCHP_MT_CBUS_INITIATOR_STATUS_reserved0_MASK               0xffc00000
#define BCHP_MT_CBUS_INITIATOR_STATUS_reserved0_SHIFT              22

/* MT_CBUS :: INITIATOR_STATUS :: RETRIES [21:16] */
#define BCHP_MT_CBUS_INITIATOR_STATUS_RETRIES_MASK                 0x003f0000
#define BCHP_MT_CBUS_INITIATOR_STATUS_RETRIES_SHIFT                16

/* MT_CBUS :: INITIATOR_STATUS :: NACK_RECEIVED [15:08] */
#define BCHP_MT_CBUS_INITIATOR_STATUS_NACK_RECEIVED_MASK           0x0000ff00
#define BCHP_MT_CBUS_INITIATOR_STATUS_NACK_RECEIVED_SHIFT          8

/* MT_CBUS :: INITIATOR_STATUS :: ACK_RECEIVED [07:00] */
#define BCHP_MT_CBUS_INITIATOR_STATUS_ACK_RECEIVED_MASK            0x000000ff
#define BCHP_MT_CBUS_INITIATOR_STATUS_ACK_RECEIVED_SHIFT           0

/***************************************************************************
 *FOLLOWER_CFG - CBUS Follower Configuration Register
 ***************************************************************************/
/* MT_CBUS :: FOLLOWER_CFG :: reserved0 [31:01] */
#define BCHP_MT_CBUS_FOLLOWER_CFG_reserved0_MASK                   0xfffffffe
#define BCHP_MT_CBUS_FOLLOWER_CFG_reserved0_SHIFT                  1

/* MT_CBUS :: FOLLOWER_CFG :: CLEAR_STATUS [00:00] */
#define BCHP_MT_CBUS_FOLLOWER_CFG_CLEAR_STATUS_MASK                0x00000001
#define BCHP_MT_CBUS_FOLLOWER_CFG_CLEAR_STATUS_SHIFT               0
#define BCHP_MT_CBUS_FOLLOWER_CFG_CLEAR_STATUS_DEFAULT             0x00000000

/***************************************************************************
 *FOLLOWER_STATUS_0 - CBUS Follower Status Register 0
 ***************************************************************************/
/* MT_CBUS :: FOLLOWER_STATUS_0 :: reserved0 [31:28] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_reserved0_MASK              0xf0000000
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_reserved0_SHIFT             28

/* MT_CBUS :: FOLLOWER_STATUS_0 :: NACK_TRANSMITTED [27:20] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_NACK_TRANSMITTED_MASK       0x0ff00000
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_NACK_TRANSMITTED_SHIFT      20

/* MT_CBUS :: FOLLOWER_STATUS_0 :: ACK_TRANSMITTED [19:12] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_ACK_TRANSMITTED_MASK        0x000ff000
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_ACK_TRANSMITTED_SHIFT       12

/* MT_CBUS :: FOLLOWER_STATUS_0 :: reserved1 [11:11] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_reserved1_MASK              0x00000800
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_reserved1_SHIFT             11

/* MT_CBUS :: FOLLOWER_STATUS_0 :: HEADER [10:09] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_HEADER_MASK                 0x00000600
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_HEADER_SHIFT                9

/* MT_CBUS :: FOLLOWER_STATUS_0 :: CONTROL [08:08] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_CONTROL_MASK                0x00000100
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_CONTROL_SHIFT               8

/* MT_CBUS :: FOLLOWER_STATUS_0 :: PAYLOAD [07:00] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_PAYLOAD_MASK                0x000000ff
#define BCHP_MT_CBUS_FOLLOWER_STATUS_0_PAYLOAD_SHIFT               0

/***************************************************************************
 *FOLLOWER_STATUS_1 - CBUS Follower Status Register 1
 ***************************************************************************/
/* MT_CBUS :: FOLLOWER_STATUS_1 :: reserved0 [31:16] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_reserved0_MASK              0xffff0000
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_reserved0_SHIFT             16

/* MT_CBUS :: FOLLOWER_STATUS_1 :: TRUNCATED_PKT_CNT [15:08] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_TRUNCATED_PKT_CNT_MASK      0x0000ff00
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_TRUNCATED_PKT_CNT_SHIFT     8

/* MT_CBUS :: FOLLOWER_STATUS_1 :: DROP_CNT [07:00] */
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_DROP_CNT_MASK               0x000000ff
#define BCHP_MT_CBUS_FOLLOWER_STATUS_1_DROP_CNT_SHIFT              0

/***************************************************************************
 *RX_FILTER_CFG - Rx Filter Configuration Register
 ***************************************************************************/
/* MT_CBUS :: RX_FILTER_CFG :: reserved0 [31:14] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved0_MASK                  0xffffc000
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved0_SHIFT                 14

/* MT_CBUS :: RX_FILTER_CFG :: HYSTERESIS [13:08] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_HYSTERESIS_MASK                 0x00003f00
#define BCHP_MT_CBUS_RX_FILTER_CFG_HYSTERESIS_SHIFT                8
#define BCHP_MT_CBUS_RX_FILTER_CFG_HYSTERESIS_DEFAULT              0x00000004

/* MT_CBUS :: RX_FILTER_CFG :: reserved1 [07:06] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved1_MASK                  0x000000c0
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved1_SHIFT                 6

/* MT_CBUS :: RX_FILTER_CFG :: FILTER_LENGTH [05:04] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_LENGTH_MASK              0x00000030
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_LENGTH_SHIFT             4
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_LENGTH_DEFAULT           0x00000000

/* MT_CBUS :: RX_FILTER_CFG :: reserved2 [03:02] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved2_MASK                  0x0000000c
#define BCHP_MT_CBUS_RX_FILTER_CFG_reserved2_SHIFT                 2

/* MT_CBUS :: RX_FILTER_CFG :: FILTER_MODE [01:00] */
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_MODE_MASK                0x00000003
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_MODE_SHIFT               0
#define BCHP_MT_CBUS_RX_FILTER_CFG_FILTER_MODE_DEFAULT             0x00000002

/***************************************************************************
 *RX_CDR_CFG_0 - Rx Clock and Data Recovery Configuration Register 0
 ***************************************************************************/
/* MT_CBUS :: RX_CDR_CFG_0 :: reserved0 [31:28] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_reserved0_MASK                   0xf0000000
#define BCHP_MT_CBUS_RX_CDR_CFG_0_reserved0_SHIFT                  28

/* MT_CBUS :: RX_CDR_CFG_0 :: CLEAR_UI_PERIOD_STAT [27:27] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_CLEAR_UI_PERIOD_STAT_MASK        0x08000000
#define BCHP_MT_CBUS_RX_CDR_CFG_0_CLEAR_UI_PERIOD_STAT_SHIFT       27
#define BCHP_MT_CBUS_RX_CDR_CFG_0_CLEAR_UI_PERIOD_STAT_DEFAULT     0x00000000

/* MT_CBUS :: RX_CDR_CFG_0 :: EDGE_TOLERANCE [26:20] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_EDGE_TOLERANCE_MASK              0x07f00000
#define BCHP_MT_CBUS_RX_CDR_CFG_0_EDGE_TOLERANCE_SHIFT             20
#define BCHP_MT_CBUS_RX_CDR_CFG_0_EDGE_TOLERANCE_DEFAULT           0x00000005

/* MT_CBUS :: RX_CDR_CFG_0 :: FORCE_UI_PERIOD_ENABLE [19:19] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_ENABLE_MASK      0x00080000
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_ENABLE_SHIFT     19
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_ENABLE_DEFAULT   0x00000000

/* MT_CBUS :: RX_CDR_CFG_0 :: reserved1 [18:17] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_reserved1_MASK                   0x00060000
#define BCHP_MT_CBUS_RX_CDR_CFG_0_reserved1_SHIFT                  17

/* MT_CBUS :: RX_CDR_CFG_0 :: FORCE_UI_PERIOD [16:08] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_MASK             0x0001ff00
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_SHIFT            8
#define BCHP_MT_CBUS_RX_CDR_CFG_0_FORCE_UI_PERIOD_DEFAULT          0x00000036

/* MT_CBUS :: RX_CDR_CFG_0 :: SAMPLING_OFFSET [07:00] */
#define BCHP_MT_CBUS_RX_CDR_CFG_0_SAMPLING_OFFSET_MASK             0x000000ff
#define BCHP_MT_CBUS_RX_CDR_CFG_0_SAMPLING_OFFSET_SHIFT            0
#define BCHP_MT_CBUS_RX_CDR_CFG_0_SAMPLING_OFFSET_DEFAULT          0x0000001a

/***************************************************************************
 *RX_CDR_CFG_1 - Rx Clock and Data Recovery Configuration Register 1
 ***************************************************************************/
/* MT_CBUS :: RX_CDR_CFG_1 :: reserved0 [31:22] */
#define BCHP_MT_CBUS_RX_CDR_CFG_1_reserved0_MASK                   0xffc00000
#define BCHP_MT_CBUS_RX_CDR_CFG_1_reserved0_SHIFT                  22

/* MT_CBUS :: RX_CDR_CFG_1 :: SYNC_LOW_MAX [21:12] */
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MAX_MASK                0x003ff000
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MAX_SHIFT               12
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MAX_DEFAULT             0x000000c3

/* MT_CBUS :: RX_CDR_CFG_1 :: reserved1 [11:10] */
#define BCHP_MT_CBUS_RX_CDR_CFG_1_reserved1_MASK                   0x00000c00
#define BCHP_MT_CBUS_RX_CDR_CFG_1_reserved1_SHIFT                  10

/* MT_CBUS :: RX_CDR_CFG_1 :: SYNC_LOW_MIN [09:00] */
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MIN_MASK                0x000003ff
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MIN_SHIFT               0
#define BCHP_MT_CBUS_RX_CDR_CFG_1_SYNC_LOW_MIN_DEFAULT             0x00000081

/***************************************************************************
 *RX_CDR_CFG_2 - Rx Clock and Data Recovery Configuration Register 2
 ***************************************************************************/
/* MT_CBUS :: RX_CDR_CFG_2 :: reserved0 [31:21] */
#define BCHP_MT_CBUS_RX_CDR_CFG_2_reserved0_MASK                   0xffe00000
#define BCHP_MT_CBUS_RX_CDR_CFG_2_reserved0_SHIFT                  21

/* MT_CBUS :: RX_CDR_CFG_2 :: SYNC_HIGH_MAX [20:12] */
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MAX_MASK               0x001ff000
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MAX_SHIFT              12
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MAX_DEFAULT            0x00000041

/* MT_CBUS :: RX_CDR_CFG_2 :: reserved1 [11:09] */
#define BCHP_MT_CBUS_RX_CDR_CFG_2_reserved1_MASK                   0x00000e00
#define BCHP_MT_CBUS_RX_CDR_CFG_2_reserved1_SHIFT                  9

/* MT_CBUS :: RX_CDR_CFG_2 :: SYNC_HIGH_MIN [08:00] */
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MIN_MASK               0x000001ff
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MIN_SHIFT              0
#define BCHP_MT_CBUS_RX_CDR_CFG_2_SYNC_HIGH_MIN_DEFAULT            0x0000002b

/***************************************************************************
 *RX_CDR_STATUS_0 - Rx Clock and Data Recovery Status Register 0
 ***************************************************************************/
/* MT_CBUS :: RX_CDR_STATUS_0 :: reserved0 [31:09] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_0_reserved0_MASK                0xfffffe00
#define BCHP_MT_CBUS_RX_CDR_STATUS_0_reserved0_SHIFT               9

/* MT_CBUS :: RX_CDR_STATUS_0 :: UI_PERIOD [08:00] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_0_UI_PERIOD_MASK                0x000001ff
#define BCHP_MT_CBUS_RX_CDR_STATUS_0_UI_PERIOD_SHIFT               0

/***************************************************************************
 *RX_CDR_STATUS_1 - Rx Clock and Data Recovery Status Register 1
 ***************************************************************************/
/* MT_CBUS :: RX_CDR_STATUS_1 :: reserved0 [31:21] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_reserved0_MASK                0xffe00000
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_reserved0_SHIFT               21

/* MT_CBUS :: RX_CDR_STATUS_1 :: UI_PERIOD_MAX [20:12] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_UI_PERIOD_MAX_MASK            0x001ff000
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_UI_PERIOD_MAX_SHIFT           12

/* MT_CBUS :: RX_CDR_STATUS_1 :: reserved1 [11:09] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_reserved1_MASK                0x00000e00
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_reserved1_SHIFT               9

/* MT_CBUS :: RX_CDR_STATUS_1 :: UI_PERIOD_MIN [08:00] */
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_UI_PERIOD_MIN_MASK            0x000001ff
#define BCHP_MT_CBUS_RX_CDR_STATUS_1_UI_PERIOD_MIN_SHIFT           0

/***************************************************************************
 *IMP_CHANGE_FILTER - CBUS Impedance Change Filter Configuration Register
 ***************************************************************************/
/* MT_CBUS :: IMP_CHANGE_FILTER :: reserved0 [31:30] */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_reserved0_MASK              0xc0000000
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_reserved0_SHIFT             30

/* MT_CBUS :: IMP_CHANGE_FILTER :: BYPASS_FILTER [29:29] */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_BYPASS_FILTER_MASK          0x20000000
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_BYPASS_FILTER_SHIFT         29
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_BYPASS_FILTER_DEFAULT       0x00000000

/* MT_CBUS :: IMP_CHANGE_FILTER :: OVERRIDE [28:28] */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_MASK               0x10000000
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_SHIFT              28
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_DEFAULT            0x00000000

/* MT_CBUS :: IMP_CHANGE_FILTER :: OVERRIDE_VALUE [27:27] */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_VALUE_MASK         0x08000000
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_VALUE_SHIFT        27
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_OVERRIDE_VALUE_DEFAULT      0x00000000

/* MT_CBUS :: IMP_CHANGE_FILTER :: MAX_THRESHOLD [26:00] */
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_MAX_THRESHOLD_MASK          0x07ffffff
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_MAX_THRESHOLD_SHIFT         0
#define BCHP_MT_CBUS_IMP_CHANGE_FILTER_MAX_THRESHOLD_DEFAULT       0x000137b8

/***************************************************************************
 *SPARE_REG_0 - Spare Register 0
 ***************************************************************************/
/* MT_CBUS :: SPARE_REG_0 :: SPARE_31_0 [31:00] */
#define BCHP_MT_CBUS_SPARE_REG_0_SPARE_31_0_MASK                   0xffffffff
#define BCHP_MT_CBUS_SPARE_REG_0_SPARE_31_0_SHIFT                  0
#define BCHP_MT_CBUS_SPARE_REG_0_SPARE_31_0_DEFAULT                0x00000000

/***************************************************************************
 *SPARE_REG_1 - Spare Register 1
 ***************************************************************************/
/* MT_CBUS :: SPARE_REG_1 :: SPARE_31_0 [31:00] */
#define BCHP_MT_CBUS_SPARE_REG_1_SPARE_31_0_MASK                   0xffffffff
#define BCHP_MT_CBUS_SPARE_REG_1_SPARE_31_0_SHIFT                  0
#define BCHP_MT_CBUS_SPARE_REG_1_SPARE_31_0_DEFAULT                0x00000000

/***************************************************************************
 *SPARE_REG_2 - Spare Register 2
 ***************************************************************************/
/* MT_CBUS :: SPARE_REG_2 :: SPARE_31_0 [31:00] */
#define BCHP_MT_CBUS_SPARE_REG_2_SPARE_31_0_MASK                   0xffffffff
#define BCHP_MT_CBUS_SPARE_REG_2_SPARE_31_0_SHIFT                  0
#define BCHP_MT_CBUS_SPARE_REG_2_SPARE_31_0_DEFAULT                0x00000000

/***************************************************************************
 *SPARE_REG_3 - Spare Register 3
 ***************************************************************************/
/* MT_CBUS :: SPARE_REG_3 :: SPARE_31_0 [31:00] */
#define BCHP_MT_CBUS_SPARE_REG_3_SPARE_31_0_MASK                   0xffffffff
#define BCHP_MT_CBUS_SPARE_REG_3_SPARE_31_0_SHIFT                  0
#define BCHP_MT_CBUS_SPARE_REG_3_SPARE_31_0_DEFAULT                0x00000000

#endif /* #ifndef BCHP_MT_CBUS_H__ */

/* End of File */
