/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Jan 27 12:19:19 2015
 *                 Full Compile MD5 Checksum  3788d4127f6320d7294fc780a1f038a5
 *                     (minus title and desc)
 *                 MD5 Checksum               bc21cc7e43ef60b83e7c02281647c8e6
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15579
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_UFE_HRC0_H__
#define BCHP_UFE_HRC0_H__

/***************************************************************************
 *UFE_HRC0 - UFE core registers
 ***************************************************************************/
#define BCHP_UFE_HRC0_CTRL                       0x00e20a00 /* [RW] clock/misc control register */
#define BCHP_UFE_HRC0_BYP                        0x00e20a04 /* [RW] bypass register */
#define BCHP_UFE_HRC0_RST                        0x00e20a08 /* [RW] reset control register */
#define BCHP_UFE_HRC0_FRZ                        0x00e20a0c /* [RW] freeze control register */
#define BCHP_UFE_HRC0_AGC1                       0x00e20a10 /* [RW] AGC1 control register */
#define BCHP_UFE_HRC0_AGC2                       0x00e20a14 /* [RW] AGC2 control register */
#define BCHP_UFE_HRC0_AGC3                       0x00e20a18 /* [RW] AGC3 control register */
#define BCHP_UFE_HRC0_AGC1_THRESH                0x00e20a1c /* [RW] AGC1 threshold register */
#define BCHP_UFE_HRC0_AGC2_THRESH                0x00e20a20 /* [RW] AGC2 threshold register */
#define BCHP_UFE_HRC0_AGC3_THRESH                0x00e20a24 /* [RW] AGC3 threshold register */
#define BCHP_UFE_HRC0_AGC1_LF                    0x00e20a28 /* [RW] AGC1 loop filter register */
#define BCHP_UFE_HRC0_AGC2_LF                    0x00e20a2c /* [RW] AGC2 loop filter register */
#define BCHP_UFE_HRC0_AGC3_LF                    0x00e20a30 /* [RW] AGC3 loop filter register */
#define BCHP_UFE_HRC0_IQIMB_AMP_CTRL             0x00e20a34 /* [RW] IQ-Imbalance amplitude correction control register */
#define BCHP_UFE_HRC0_IQIMB_PHS_CTRL             0x00e20a38 /* [RW] IQ-Imbalance phase     correction control register */
#define BCHP_UFE_HRC0_IQIMB_AMP_LF               0x00e20a3c /* [RW] IQ-Imbalance amplitude loop filter register */
#define BCHP_UFE_HRC0_IQIMB_PHS_LF               0x00e20a40 /* [RW] IQ-Imbalance phase     loop filter register */
#define BCHP_UFE_HRC0_DCO_CTRL                   0x00e20a44 /* [RW] DCO canceller control register */
#define BCHP_UFE_HRC0_DCOINTI                    0x00e20a48 /* [RW] DCO integrator I */
#define BCHP_UFE_HRC0_DCOINTQ                    0x00e20a4c /* [RW] DCO integrator Q */
#define BCHP_UFE_HRC0_BMIX_FCW                   0x00e20a50 /* [RW] FCW register for back mixer */
#define BCHP_UFE_HRC0_FMIX_FCW                   0x00e20a54 /* [RW] FCW register for front mixer */
#define BCHP_UFE_HRC0_CRC_EN                     0x00e20a58 /* [RW] CRC enable register */
#define BCHP_UFE_HRC0_CRC                        0x00e20a5c /* [RO] CRC signature analyzer register */
#define BCHP_UFE_HRC0_LFSR_SEED                  0x00e20a60 /* [RW] LFSR initial seed */
#define BCHP_UFE_HRC0_TP                         0x00e20a64 /* [RW] Testport register */
#define BCHP_UFE_HRC0_SPARE                      0x00e20a68 /* [RW] Software spare register */

#endif /* #ifndef BCHP_UFE_HRC0_H__ */

/* End of File */
