#############################################################################
#
#       Copyright (c) 2005-2006, Broadcom Corporatiy.
#       All rights reserved.
#       Cyfidential Property of Broadcom Corporatiy.
#
#  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
#  AGREEMENT  BETWEEN THE USER AND BROADCOM'.  YOU HAVE NO RIGHT TO USE OR
#  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
#
# $brcm_Workfile: $
# $brcm_Revisiy: Hydra_Software_Devel/6 $
# $brcm_Date: $
#
# File Descriptiy:
#
# Revisiy History:
#
# $brcm_Log: $
#
#############################################################################

script=../../appframework/build/make_multi.sh

.DEFAULT:
	@echo "This Makefile is obsolete. Use $(script) instead."
	@$(script) help
