/******************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/

#include "bstd.h"
#include "bkni.h"
#include "breg_mem.h"
#include "breg_mem_priv.h"
#include "bchp_common.h"

BDBG_MODULE(breg_mem);

BDBG_OBJECT_ID(BREG);

#define BCHP_GISB_REGISTER_OFFSET 0

static void BREG_P_systemUpdate32_isrsafe(void *context, uint32_t reg, uint32_t mask, uint32_t value, bool atomic)
{
    BREG_Handle regHandle = context;
    uint32_t temp;

    BSTD_UNUSED(atomic);
    BDBG_OBJECT_ASSERT(regHandle, BREG);
    temp = value;
    if(mask!=0xFFFFFFFF) {
        mask = ~mask;
        if( (mask&value) != 0) {
            BDBG_ERR(("BREG_Update32: %p:%#x attempting to access bits outside of mask %#x(%#x)", (void*)regHandle, (unsigned)reg, (unsigned)~mask, (unsigned)value));
            if(0) BDBG_ASSERT(0);
        }
        if(0) BDBG_ASSERT((mask&value)==0);
        temp = BREG_P_Read32(regHandle, reg);
        temp = (temp&mask)|value;
    }
    BREG_P_Write32(regHandle, reg, temp);
    return;
}

static bool BREG_P_isRegisterAtomic_isrsafe(void *unused, uint32_t reg );

static bool BREG_P_isRegisterReadOnly_isrsafe(uint32_t reg) {
#if defined(BCHP_REGISTER_HAS_READONLY)
#define BCHP_REGISTER_READONLY_32BIT(name, offset) case (offset/4): BDBG_CASSERT((offset%4)==0);return true;
    switch(reg/4) {
#include "bchp_readonly.h"
    default: break;
    }
#else
    BSTD_UNUSED(reg);
#endif
    return false;
}

static bool BREG_P_Test32RegReadOnly_isrsafe(uint32_t reg)
{
    bool result = BREG_P_isRegisterReadOnly_isrsafe(reg);
    if(result) {
        BDBG_ERR(("Register %#x is read-only, write operation is not allowed", reg));
        BDBG_ASSERT(0);
    }
    return result;
}

#if defined(BCHP_HIF_MSAT_REG_START) /* MSAT is hw atomizer for 64-bit register access from 32-bit host */

static bool BREG_P_Test64RegReadOnly_isrsafe(uint32_t reg)
{
    bool result = BREG_P_isRegisterReadOnly_isrsafe(reg) || BREG_P_isRegisterReadOnly_isrsafe(reg+4);
    if(result) {
        BDBG_ERR(("Register %#x is read-only, write operation is not allowed", reg));
        BDBG_ASSERT(0);
    }
    return result;
}

#if BDBG_DEBUG_BUILD
static bool BREG_P_Test64RegOffset_isrsafe(uint32_t regOffset)
{
#define BCHP_REGISTER_64BIT(name, offset) case (offset/8): BDBG_CASSERT((offset%8)==0);return true;
    switch(regOffset) {
#include "bchp_64bit.h"
    default: break;
    }
    return false;
}

static bool BREG_P_Test64Reg_isrsafe(uint32_t reg)
{
    return reg%8==0 && BREG_P_Test64RegOffset_isrsafe(reg/8);
}
#endif /* BDBG_DEBUG_BUILD */

static void BREG_P_Test32Reg_isrsafe(uint32_t reg)
{
    BSTD_UNUSED(reg);
#if BDBG_DEBUG_BUILD
    if(reg%4!=0 || BREG_P_Test64RegOffset_isrsafe(reg/8)) {
        BDBG_ERR(("Invalid 32-bit register access %#x", reg));
    }
#endif
    return;
}
#else
static void BREG_P_Test32Reg_isrsafe(uint32_t reg)
{
    BSTD_UNUSED(reg);
    return ;
}
#endif

static void BREG_P_runSerialized_isrsafe(void *context, void (*action)(BREG_Handle, void *), void *action_context)
{
    BSTD_UNUSED(context);
    BSTD_UNUSED(action);
    BSTD_UNUSED(action_context);
    BDBG_ERR(("runSerialized is not supported"));
    BDBG_ASSERT(0);
    return ;
}
static const BREG_OpenSettings BREG_OpenSettings_Default = {
    NULL,
    BREG_P_isRegisterAtomic_isrsafe,
    BREG_P_systemUpdate32_isrsafe,
    BREG_P_runSerialized_isrsafe,
    0
};

void BREG_GetDefaultOpenSettings(BREG_OpenSettings *pSettings)
{
    *pSettings = BREG_OpenSettings_Default;
    return;
}

BERR_Code BREG_Open( BREG_Handle *pRegHandle, void *Address, size_t MaxRegOffset, const BREG_OpenSettings *pSettings)
{
    BREG_Handle regHandle;
    *pRegHandle = NULL;

    if(pSettings==NULL) {
        pSettings = &BREG_OpenSettings_Default;
    }
    if(pSettings->isRegisterAtomic_isrsafe == NULL || pSettings->systemUpdate32_isrsafe == NULL) {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }
    regHandle = BKNI_Malloc( sizeof(*regHandle) );
    if(regHandle==NULL) {
        return BERR_TRACE(BERR_OUT_OF_SYSTEM_MEMORY);
    }
    BDBG_OBJECT_SET(regHandle, BREG);
    regHandle->openSettings = *pSettings;
    if(pSettings->systemUpdate32_isrsafe == BREG_P_systemUpdate32_isrsafe) {
        regHandle->openSettings.callbackContext = regHandle;
    }
    regHandle->MaxRegOffset = MaxRegOffset;
    regHandle->BaseAddr = Address;
    *pRegHandle = regHandle;
    return BERR_SUCCESS;
}

void BREG_Close( BREG_Handle RegHandle )
{
    BDBG_OBJECT_ASSERT(RegHandle, BREG);
    BDBG_OBJECT_DESTROY(RegHandle, BREG);
    BKNI_Free(RegHandle);
}

/* compile the register access functions even for the release build */
#undef  BREG_Write32
#undef  BREG_Write16
#undef  BREG_Write8

#undef  BREG_Read32
#undef  BREG_Read16
#undef  BREG_Read8

#include "bchp_sun_top_ctrl.h"

/**
BREG_P_CheckAtomicRegister_isrsafe is a development-time debug function. It's purpose is to warn the developer that a non-atomic
read/modify/write is being done on a register that requires BREG_AtomicUpdate32 access. If you see a warning, you should
modify the code to use BREG_AtomicUpdate32 or BREG_AtomicUpdate32_isr.
See BREG_AtomicUpdate32 and BREG_SetAtomicUpdate32Callback in breg_mem.h for more information on atomic access.
**/
#define BREG_P_ATOMIC_REG(reg) case reg: regAtomic=true;break
static bool BREG_P_isRegisterAtomic_isrsafe(void *unused, uint32_t reg)
{
    bool regAtomic;
    BSTD_UNUSED(unused);

    switch(reg) {
#ifdef BCHP_SUN_TOP_CTRL_SW_RESET
    BREG_P_ATOMIC_REG(BCHP_SUN_TOP_CTRL_SW_RESET);
#endif

#if (BCHP_CHIP==7231)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_PWRDN );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_ANA_QDAC40G_M7FC_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_4);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_MEMORY_STANDBY_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_MEMORY_STANDBY_ENABLE_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_OBSERVE_CLOCK);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_CLOCK_ENABLE_M2MDMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_MEMORY_STANDBY_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_MEMORY_STANDBY_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HIF_CLOCK_ENABLE_SID);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
#elif ((BCHP_CHIP==7429) || (BCHP_CHIP==74295))
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_INST_CLOCK_ENABLE);
#elif (BCHP_CHIP==7425)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD1_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD1_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO2_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO2_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_VEC_DACADC_CLOCK_DISABLE);
#if (BCHP_VER == BCHP_VER_A0 || BCHP_VER == BCHP_VER_A1)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_A);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_V3D_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_4);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_ENABLE);
#elif (BCHP_VER >= BCHP_VER_B0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_V3D_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE_M2MDMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MCVP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_5);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PAD_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_M2MC_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_UHFR_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_POWER_SWITCH_MEMORY);
#elif (BCHP_CHIP==7435)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_1_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_1_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_AIO);
#if (BCHP_VER >= BCHP_VER_B0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_0_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_0_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_1_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_1_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_Async_ALIVE_SEL);
#else
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_CLOCK_ENABLE0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_POWER_SWITCH_MEMORY0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_CLOCK_ENABLE1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_POWER_SWITCH_MEMORY1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MVP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MVP_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY_M2MC0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE_M2MDMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_UHFR_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_INST_CLOCK_ENABLE_SID);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO2_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO2_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_MOCA_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_XPT_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_XPT_PLL_CHANNEL_CTRL_CH_2);
#elif (BCHP_CHIP==7552)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_A);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_MEMORY_STANDBY_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
#elif (BCHP_CHIP==7344)
   #include "bchp_clkgen.h"
       BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
#if BCHP_VER == BCHP_VER_A0
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_A);
#else
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_AIO);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY);
#if BCHP_VER == BCHP_VER_A0
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
#else
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE_M2MDMA);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD0_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_POWER_SWITCH_MEMORY);
#elif ((BCHP_CHIP==7346) || (BCHP_CHIP==73465))
   #include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_M2MC_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_V3D_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_MIPS_PLL_DIV);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_108_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE_M2MDMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SVD_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_INST_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_POWER_SWITCH_MEMORY);
#elif (BCHP_CHIP==7358) || (BCHP_CHIP==7360) || (BCHP_CHIP==7362) || (BCHP_CHIP==73625) || (BCHP_CHIP==7228)
   #include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_A);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
#elif ((BCHP_CHIP==7584) || (BCHP_CHIP==75845))
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_CHANNEL_CTRL_CH_4);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_PWRDN );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_ANA_QDAC40G_M7FC_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_MEMORY_STANDBY_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_MEMORY_STANDBY_ENABLE_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_OBSERVE_CLOCK);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_CLOCK_ENABLE_M2MDMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_MEMORY_STANDBY_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_MEMORY_STANDBY_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE_SID);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
#elif ((BCHP_CHIP==7563) || (BCHP_CHIP==75635))
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_B);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_A);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
#elif (BCHP_CHIP==75525)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_B);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_A);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SECTOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_INST_CLOCK_ENABLE);
#elif (BCHP_CHIP==7445)
#include "bchp_clkgen.h"
#include "bchp_avs_top_ctrl.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_SHVD0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD_SID1_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_HVD1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD2_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_HVD2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_0_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_VICE2_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_1_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_VICE2_1);
#if (BCHP_VER >= BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_CLOCK_ENABLE_RAAGA0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_WRAP_INST_CLOCK_ENABLE_RAAGA1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_EDGE_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MIDDLE_TOP_INST_CLOCK_ENABLE);
#else
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_0_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_1_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
#endif
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_AIO);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_RAAGA0);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_RAAGA1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MVP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVND);
#if (BCHP_VER >= BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVNE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVNM);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE_VEC_QDAC_INTF);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE);
#else
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC_QDAC_INTF);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHT);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_ANA_QDAC_TS28HPM_6MX_2MR_FC_H_E_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_Async_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE2);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHR);
#if (BCHP_VER >= BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE_M2MC0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_GFX_TOP_INST_CLOCK_ENABLE_M2MC1);
#else
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE1);
#endif
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_M2MC0);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD_SID1_TOP_INST_CLOCK_ENABLE_SID);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_SID);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_LDO_PWRON);
#if (BCHP_VER < BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0);
#endif

#if (BCHP_VER < BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1);
#endif

#if (BCHP_VER < BCHP_VER_D0)
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO2);
#endif
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO2_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON);
#elif (BCHP_CHIP==7271 || BCHP_CHIP==7268 || BCHP_CHIP==7260 || BCHP_CHIP==7278)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
#elif (BCHP_CHIP==7439 && (BCHP_VER < BCHP_VER_B0))
#include "bchp_clkgen.h"
#include "bchp_avs_top_ctrl.h"
#include "bchp_aud_fmm_iop_pll_0.h"
#include "bchp_aud_fmm_iop_pll_1.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VICE2_0_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_VICE2_0);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_AIO);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_RAAGA0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_MVP_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVND);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_BVN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_ANA_QDAC_TS28HPM_6MX_2MR_FC_H_E_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_HVD);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD_SID0_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RAAGA_DSP_TOP_0_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE_VEC_QDAC_INTF);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_DUAL_WRAPPER_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_DUAL_WRAPPER_INST_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHT);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHR);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_CLOCK_ENABLE_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_GRAPHICS_INST_ALT_CLOCK_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_V3D_TOP_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_HVD_SID0_TOP_INST_CLOCK_ENABLE_SID);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_SID);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_Async_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HR_INST_CLOCK_ENABLE0);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_M2MC1);
    BREG_P_ATOMIC_REG(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_V3D);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_INST_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_HVD_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_LDO_POWERUP);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_0_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_0_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_0_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_0_RESET);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_1_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_1_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_1_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_AUD_FMM_IOP_PLL_1_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_BG_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_SC1_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_MOCA_PLL_CHANNEL_CTRL_CH_3);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_MOCA_PLL_CHANNEL_CTRL_CH_4);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_INST_CLOCK_ENABLE);
#elif (BCHP_CHIP==7439 && (BCHP_VER >= BCHP_VER_B0))
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
#elif (BCHP_CHIP==74371)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET);
#elif (BCHP_CHIP==7366)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET );
#elif (BCHP_CHIP==7364) || (BCHP_CHIP==7250)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET );
#elif (BCHP_CHIP==7586)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO0_PLL_RESET );
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO1_PLL_RESET );
#elif (BCHP_CHIP==7543)
#include "bchp_clkgen.h"
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_MEMORY_STANDBY_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_0);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_1);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_VCXO_PLL_CHANNEL_CTRL_CH_2);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_CLOCK_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AUDIO0_PLL_PWRDN);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_RFM_TOP_MEMORY_STANDBY_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DFE_CORE_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_OBSERVE_CLOCK_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_VEC);

    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_AVD0_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_POWER_SWITCH_MEMORY_AIO);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_CORE_XPT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_CLOCK_216_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PM_PLL_ALIVE_SEL);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DVP_HT_POWER_SWITCH_MEMORY);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_SYS_CTRL_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_PLL_AVD_MIPS_PLL_RESET);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_VEC_AIO_TOP_CLOCK_ENABLE_VEC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_MEM_DMA_MEMORY_STANDBY_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_MEM_DMA_M2M_DMA);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DFE_CORE_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_DFE_CORE_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_MEMORY_STANDBY_ENABLE_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_BVN_M2MC_TOP_POWER_SWITCH_MEMORY_M2MC);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_USB_CLOCK_DISABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_USB_CLOCK_ENABLE);
    BREG_P_ATOMIC_REG(BCHP_CLKGEN_USB_MEMORY_STANDBY_ENABLE);
    /* TODO set OTP related registers if needed */
#endif
    default:
        regAtomic = false;
        break;
    }
    return regAtomic;
}

#if BDBG_DEBUG_BUILD
static void BREG_P_CheckAtomicRegister_isrsafe(BREG_Handle regHandle, uint32_t reg, const char *function, bool atomic )
{
    bool regAtomic = regHandle->openSettings.isRegisterAtomic_isrsafe(regHandle->openSettings.callbackContext, reg);

    if(regAtomic!=atomic) {
        if(!atomic) {
            BDBG_ERR(("%s: register %#lx should only be used with atomic access", function, (unsigned long)reg));
        } else {
            BDBG_ERR(("%s: register %#lx shouldn't be used for atomic access", function, (unsigned long)reg));
        }
    }
    return;
}
#else
#define BREG_P_CheckAtomicRegister_isrsafe(regHandle, reg, function, atomic)
#endif


uint32_t BREG_Read32(BREG_Handle RegHandle, uint32_t reg)
{
    /* BDBG_OBJECT_ASSERT(RegHandle, BREG); */
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_Test32Reg_isrsafe(reg);

    return BREG_P_Read32(RegHandle, reg);
}

uint16_t BREG_Read16(BREG_Handle RegHandle, uint32_t reg)
{
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);

    return BREG_P_Read16(RegHandle, reg);
}

uint8_t BREG_Read8(BREG_Handle RegHandle, uint32_t reg)
{
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);

    return BREG_P_Read8(RegHandle, reg);
}

#if BREG_CAPTURE
/* BREG_CAPTURE is a hook to capture all register writes from magnum. It is used by the splashgen utility.
The feature should not be enabled for a production system. */
extern void APP_BREG_Write32(BREG_Handle RegHandle, uint32_t reg, uint32_t data);
#endif


void BREG_Write32(BREG_Handle RegHandle, uint32_t reg, uint32_t data)
{
    /* BDBG_OBJECT_ASSERT(RegHandle, BREG); */
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_Test32Reg_isrsafe(reg);
    BREG_P_CheckAtomicRegister_isrsafe(RegHandle, reg, "BREG_Write32", false);

#if BREG_CAPTURE
    {
        static int warning_count = 0;
        if (warning_count < 5) {
            warning_count++;
            BDBG_WRN(("You are running with BREG_CAPTURE defined. This utility mode is used for running the register capture utility, not production code."));
        }
    }
    APP_BREG_Write32(RegHandle, reg, data) ;
#endif
    if(BREG_P_Test32RegReadOnly_isrsafe(reg)) {
        return;
    }
    BREG_P_Write32(RegHandle, reg, data);
}

void BREG_Write16(BREG_Handle RegHandle, uint32_t reg, uint16_t data)
{
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_CheckAtomicRegister_isrsafe(RegHandle, reg, "BREG_Write16", false);

    BREG_P_Write16(RegHandle, reg, data);
}

void BREG_Write8(BREG_Handle RegHandle, uint32_t reg, uint8_t data)
{
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_CheckAtomicRegister_isrsafe(RegHandle, reg, "BREG_Write8", false);

    BREG_P_Write8(RegHandle, reg, data);
}

void BREG_AtomicUpdate32_isrsafe(BREG_Handle RegHandle, uint32_t reg, uint32_t mask, uint32_t value)
{
    BDBG_OBJECT_ASSERT(RegHandle, BREG);
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_Test32Reg_isrsafe(reg);
    BREG_P_CheckAtomicRegister_isrsafe(RegHandle, reg, "BREG_AtomicUpdate32_isr", true);
    if(BREG_P_Test32RegReadOnly_isrsafe(reg)) {
        return;
    }
    RegHandle->openSettings.systemUpdate32_isrsafe(RegHandle->openSettings.callbackContext, reg, mask, value, true);
#if BREG_CAPTURE
    APP_BREG_Write32(RegHandle,reg,BREG_Read32(RegHandle,reg));
#endif
}

void BREG_Update32_isrsafe(BREG_Handle RegHandle, uint32_t reg, uint32_t mask, uint32_t value)
{
    BDBG_OBJECT_ASSERT(RegHandle, BREG);
    BDBG_ASSERT(reg < RegHandle->MaxRegOffset);
    BREG_P_Test32Reg_isrsafe(reg);

    if(BREG_P_Test32RegReadOnly_isrsafe(reg)) {
        return;
    }
    RegHandle->openSettings.systemUpdate32_isrsafe(RegHandle->openSettings.callbackContext, reg, mask, value, false);
    return;
}

BDBG_FILE_MODULE(breg_tracelog);
#define BDBG_MODULE_MSG_TRACE(m,x)

void BREG_P_Tracelog_Event_isrsafe( BREG_Handle RegHandle, unsigned offset, uint32_t data)
{
#if BCHP_MEMC_SENTINEL_0_0_REG_START
    uint32_t sentinel;
    BDBG_OBJECT_ASSERT(RegHandle, BREG);
    BDBG_MODULE_MSG_TRACE(breg_tracelog, ("EVENT:%#x:%u -> %#x", offset/BREG_P_TRACELOG_MAX_EVENTS_PER_DEVICE, offset%BREG_P_TRACELOG_MAX_EVENTS_PER_DEVICE, (unsigned)data));
    BDBG_CASSERT(BREG_P_TRACELOG_MAX_MODULES * BREG_P_TRACELOG_MAX_EVENTS_PER_DEVICE * 4 <= (BCHP_MEMC_SENTINEL_0_0_REG_END - BCHP_MEMC_SENTINEL_0_0_REG_START));
    sentinel = offset*4+BCHP_MEMC_SENTINEL_0_0_REG_START;
    if(sentinel > BCHP_MEMC_SENTINEL_0_0_REG_END) {
        BDBG_ASSERT(0);
    }
    BREG_Write32(RegHandle, sentinel, data);
#else
    BSTD_UNUSED(RegHandle);
    BSTD_UNUSED(offset);
    BSTD_UNUSED(data);
#endif
    return;
}

void BREG_P_Tracelog_Register(BREG_Handle RegHandle, unsigned moduleId, const char *moduleName)
{
    BDBG_OBJECT_ASSERT(RegHandle, BREG);
#if BCHP_MEMC_SENTINEL_0_0_REG_START
    if(moduleName) {
        unsigned sentinel;
        sentinel = moduleId*BREG_P_TRACELOG_MAX_EVENTS_PER_DEVICE*4+BCHP_MEMC_SENTINEL_0_0_REG_START;
        sentinel += (BCHP_PHYSICAL_OFFSET+BCHP_REGISTER_START);
        BDBG_MODULE_LOG(breg_tracelog,("DEVICE:%s(%#x) uses gisb %#x .. %#x",moduleName,moduleId,sentinel,sentinel+BREG_P_TRACELOG_MAX_EVENTS_PER_DEVICE*4));
    }
#else
    BSTD_UNUSED(moduleId);
    BSTD_UNUSED(moduleName);
#endif
}

#if defined(BCHP_HIF_MSAT_REG_START) /* MSAT is hw atomizer for 64-bit register access from 32-bit host */

static void BREG_P_Write64_Native_isrsafe(BREG_Handle regHandle, uint32_t reg, uint64_t data)
{
    BREG_P_Write64(regHandle, reg, data);
    return;
}

static uint64_t BREG_P_Read64_Native_isrsafe(BREG_Handle regHandle, uint32_t reg)
{
    uint64_t data;
    data = BREG_P_Read64(regHandle, reg);
    return data;
}

#include "bchp_hif_msat.h"
    /* 64-bits Migration: Control/Busses/Register Update */
    /* 5.7  Managed SAT */

static void BREG_P_Msat_SetAddress_isrsafe(BREG_Handle regHandle, unsigned offset, uint32_t reg)
{
    uint64_t deviceOffset = reg + (uint64_t)BCHP_PHYSICAL_OFFSET;
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_LO_ADDR + offset, (uint32_t)deviceOffset);
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_HI_ADDR + offset, (uint32_t)(deviceOffset>>32));
    return;
}

struct BREG_P_Msat_ActionContext {
    uint32_t reg;
    uint64_t data;
};

static void BREG_P_Msat_Write64_isrsafe(BREG_Handle regHandle, unsigned index, uint32_t reg, uint64_t data)
{
    unsigned offset = (BCHP_HIF_MSAT_CHANNEL_1_LO_ADDR - BCHP_HIF_MSAT_CHANNEL_0_LO_ADDR)*index;
    BREG_P_Msat_SetAddress_isrsafe(regHandle, offset, reg);
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_LO_DATA + offset, (uint32_t)data);
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_HI_DATA + offset, (uint32_t)(data>>32));
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_ACTION + offset, BCHP_FIELD_ENUM(HIF_MSAT_CHANNEL_0_ACTION, WRITE, WRITE_CYC));
    return;
}

static void BREG_P_Msat_Action_Write64_isrsafe(BREG_Handle regHandle, void *_context)
{
    struct BREG_P_Msat_ActionContext *context = _context;
    BREG_P_Msat_Write64_isrsafe(regHandle, regHandle->openSettings.msatChannel, context->reg, context->data);
    return;
}


static void BREG_P_Write64_Msat_isrsafe(BREG_Handle regHandle, uint32_t reg, uint64_t data)
{
    uint32_t tmp;
    unsigned index;

    tmp = BREG_P_Read32(regHandle, BCHP_HIF_MSAT_ACQUIRE);
    index = BCHP_GET_FIELD_DATA(tmp, HIF_MSAT_ACQUIRE, CHANNEL_INDEX);
    if(index!=0xFF) {
        BREG_P_Msat_Write64_isrsafe(regHandle, index, reg, data);
        BREG_P_Write32(regHandle, BCHP_HIF_MSAT_RELEASE, BCHP_FIELD_DATA(HIF_MSAT_RELEASE, CHANNEL_INDEX, index));
    } else {
        struct BREG_P_Msat_ActionContext context;
        context.reg = reg;
        context.data = data;
        regHandle->openSettings.runSerialized_isrsafe(regHandle->openSettings.callbackContext, BREG_P_Msat_Action_Write64_isrsafe, &context);
    }
    return ;
}

static uint64_t BREG_P_Msat_Read64_isrsafe(BREG_Handle regHandle, unsigned index, uint32_t reg)
{
    unsigned offset = (BCHP_HIF_MSAT_CHANNEL_1_LO_ADDR - BCHP_HIF_MSAT_CHANNEL_0_LO_ADDR)*index;
    uint64_t data;
    uint32_t tmp;
    BREG_P_Msat_SetAddress_isrsafe(regHandle, offset, reg);
    BREG_P_Write32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_ACTION + offset, BCHP_FIELD_ENUM(HIF_MSAT_CHANNEL_0_ACTION, READ, READ_CYC));
    tmp = BREG_P_Read32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_LO_DATA + offset);
    data = BREG_P_Read32(regHandle, BCHP_HIF_MSAT_CHANNEL_0_HI_DATA + offset);
    data = (data<<32) | tmp;
    return data;
}

static void BREG_P_Msat_Action_Read64_isrsafe(BREG_Handle regHandle, void *_context)
{
    struct BREG_P_Msat_ActionContext *context = _context;
    context->data = BREG_P_Msat_Read64_isrsafe(regHandle, regHandle->openSettings.msatChannel, context->reg);
    return;
}

static uint64_t BREG_P_Read64_Msat_isrsafe(BREG_Handle regHandle, uint32_t reg)
{
    uint64_t data;
    uint32_t tmp;
    unsigned index;

    tmp = BREG_P_Read32(regHandle, BCHP_HIF_MSAT_ACQUIRE);
    index = BCHP_GET_FIELD_DATA(tmp, HIF_MSAT_ACQUIRE, CHANNEL_INDEX);
    if(index!=0xFF) {
        data = BREG_P_Msat_Read64_isrsafe(regHandle, index, reg);
        BREG_P_Write32(regHandle, BCHP_HIF_MSAT_RELEASE, BCHP_FIELD_DATA(HIF_MSAT_RELEASE, CHANNEL_INDEX, index));
    } else {
        struct BREG_P_Msat_ActionContext context;
        context.reg = reg;
        regHandle->openSettings.runSerialized_isrsafe(regHandle->openSettings.callbackContext, BREG_P_Msat_Action_Read64_isrsafe, &context);
        data = context.data;
    }
    return data;
}

uint64_t BREG_Read64_isrsafe(BREG_Handle regHandle, uint32_t reg)
{
    uint64_t data;
    bool native = false;

    BDBG_ASSERT(reg < regHandle->MaxRegOffset);
    BDBG_ASSERT(BREG_P_Test64Reg_isrsafe(reg));
#if defined(BREG_64_NATIVE_SUPPORT) /* allow native 64-bit register access from 64-bit host interface */
    native = true;
#endif /*  #if defined(BREG_64_NATIVE_SUPPORT)  */
    if(native) {
        data = BREG_P_Read64_Native_isrsafe(regHandle, reg);
    } else {
        data = BREG_P_Read64_Msat_isrsafe(regHandle, reg);
    }
    return data;
}

void BREG_Write64_isrsafe(BREG_Handle regHandle, uint32_t reg, uint64_t data)
{
    bool native = false;

    BDBG_ASSERT(reg < regHandle->MaxRegOffset);
    BDBG_ASSERT(BREG_P_Test64Reg_isrsafe(reg));
#if defined(BREG_64_NATIVE_SUPPORT) /* allow native 64-bit register access from 64-bit host interface */
    native = true;
#endif /*  #if defined(BREG_64_NATIVE_SUPPORT)  */
    if(BREG_P_Test64RegReadOnly_isrsafe(reg)) {
        return;
    }
    if(native) {
        BREG_P_Write64_Native_isrsafe(regHandle, reg, data);
    } else {
        BREG_P_Write64_Msat_isrsafe(regHandle, reg, data);
    }
    return;
}
#else /*  #if defined(BCHP_HIF_MSAT_REG_START)  */

void BREG_Write64_isrsafe(BREG_Handle regHandle, uint32_t reg, uint64_t data)
{
    if((data>>32)!= 0) {
        BDBG_ERR(("BREG_Write64_isrsafe: will drop " BDBG_UINT64_FMT "  when writing " BDBG_UINT64_FMT " to %#x", BDBG_UINT64_ARG((data>>32)<<32), BDBG_UINT64_ARG(data), reg));
        /* BDBG_ASSERT(data>>32==0); */
    }
    if(BREG_P_Test32RegReadOnly_isrsafe(reg)) {
        return;
    }
    BREG_Write32(regHandle, reg, data);
    return;
}

uint64_t BREG_Read64_isrsafe(BREG_Handle regHandle, uint32_t reg)
{
    uint32_t data;
    data = BREG_Read32(regHandle, reg);
    return data;
}
#endif /*  #if defined(BCHP_HIF_MSAT_REG_START)  */


/* End of File */
