/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Thu May 14 18:20:32 2015
 *                 Full Compile MD5 Checksum  2c0afe5af8c5001bc7ee85f3b37a072f
 *                     (minus title and desc)
 *                 MD5 Checksum               ff107b9f712c3c7698da495b543748f9
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     16137
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /tools/dvtsw/current/Linux/combo_header.pl
 *                 DVTSWVER                   current
 *
 *
 ***************************************************************************/

#ifndef BCHP_KBD2_H__
#define BCHP_KBD2_H__

/***************************************************************************
 *KBD2 - IR Keyboard/Remote Receiver 2
 ***************************************************************************/
#define BCHP_KBD2_STATUS                         0x00409100 /* [RO] KEYBOARD/REMOTE RECEIVER STATUS REGISTER */
#define BCHP_KBD2_DIVISOR                        0x00409104 /* [RW] KEYBOARD/REMOTE RECEIVER DIVISOR */
#define BCHP_KBD2_FILTER1                        0x00409108 /* [RW] KEYBOARD FILTER1 */
#define BCHP_KBD2_DATA1                          0x0040910c /* [RW] KEYBOARD/REMOTE RECEIVER DATA WORD 1 (MS Word) */
#define BCHP_KBD2_DATA0                          0x00409110 /* [RW] KEYBOARD/REMOTE RECEIVER DATA WORD 0 (LS Word) */
#define BCHP_KBD2_CMD                            0x00409114 /* [RW] KEYBOARD/REMOTE RECEIVER COMMAND REGISTER */
#define BCHP_KBD2_CIR_ADDR                       0x00409118 /* [RW] CONSUMER IR DECODER ADDRESS REGISTER */
#define BCHP_KBD2_CIR_DATA                       0x0040911c /* [RW] CONSUMER IR DECODER DATA (LSB) */
#define BCHP_KBD2_KBD_MASK0                      0x00409120 /* [RW] KEBOARD INPUT MASK 0 */
#define BCHP_KBD2_KBD_MASK1                      0x00409124 /* [RW] KEBOARD INPUT MASK 1 */
#define BCHP_KBD2_KBD_MASK2                      0x00409128 /* [RW] KEBOARD INPUT MASK 2 */
#define BCHP_KBD2_KBD_PAT0                       0x0040912c /* [RW] KEBOARD INPUT PATTERN MATCH 0 */
#define BCHP_KBD2_KBD_PAT1                       0x00409130 /* [RW] KEBOARD INPUT PATTERN MATCH 1 */
#define BCHP_KBD2_KBD_PAT2                       0x00409134 /* [RW] KEBOARD INPUT PATTERN MATCH 2 */
#define BCHP_KBD2_STATUS2                        0x0040913c /* [RO] KEYBOARD/REMOTE RECEIVER STATUS2 REGISTER */

#endif /* #ifndef BCHP_KBD2_H__ */

/* End of File */
