/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 ******************************************************************************/
#ifndef BVC5_REGISTERS_PRIV_H
#define BVC5_REGISTERS_PRIV_H

#ifdef BVC5_HARDWARE_REAL

/* This will define the start and end address defines for each register block */
#include "bchp_common.h"

/* Some useful macros to determine the V3D version at compile time */
#define V3D_MAKE_VER(TECH_VERSION, REVISION, SUB_REV, COMPAT_REV) \
   (((TECH_VERSION) << 24) | ((REVISION) << 16) | ((SUB_REV) << 8) | (COMPAT_REV))
#define V3D_EXTRACT_TECH_VERSION(VER) ((VER) >> 24)
#define V3D_EXTRACT_REVISION(VER) (((VER) >> 16) & 0xff)
#define V3D_EXTRACT_SUB_REV(VER) (((VER) >> 8) & 0xff)
#define V3D_EXTRACT_COMPAT_REV(VER) ((VER) & 0xff)

#define V3D_VER (V3D_MAKE_VER(V3D_TECH_VERSION, V3D_REVISION, V3D_SUB_REV, V3D_COMPAT_REV))
#define V3D_VER_AT_LEAST(TECH_VERSION, REVISION, SUB_REV, COMPAT_REV) \
   (V3D_VER >= V3D_MAKE_VER(TECH_VERSION, REVISION, SUB_REV, COMPAT_REV))

/* Determine the core revision */
#include "bchp_v3d_hub_ctl.h"
#define V3D_TECH_VERSION   BCHP_V3D_HUB_CTL_IDENT1_TVER_DEFAULT
#define V3D_REVISION       BCHP_V3D_HUB_CTL_IDENT1_REV_DEFAULT
#ifdef BCHP_V3D_HUB_CTL_IDENT3_IPREV_DEFAULT
#define V3D_SUB_REV        BCHP_V3D_HUB_CTL_IDENT3_IPREV_DEFAULT
#else
#define V3D_SUB_REV        BCHP_V3D_HUB_CTL_IDENT3_SUBREV_DEFAULT
#endif
#ifdef BCHP_V3D_HUB_CTL_IDENT3_COMPATREV_DEFAULT
#define V3D_COMPAT_REV     BCHP_V3D_HUB_CTL_IDENT3_COMPATREV_DEFAULT
#else
#define V3D_COMPAT_REV     0
#endif

#if V3D_VER_AT_LEAST(3,3,0,0)
/* These files are now per core */
#include "bchp_v3d_ctl_0.h"
#include "bchp_v3d_qpudbg_0.h"
#include "bchp_v3d_cle_0.h"
#include "bchp_v3d_gmp_0.h"
#include "bchp_v3d_ptb_0.h"
#include "bchp_v3d_qps_0.h"
#include "bchp_v3d_vpm_0.h"
#include "bchp_v3d_pctr_0.h"
#include "bchp_v3d_err_0.h"

#if V3D_VER_AT_LEAST(4,1,34,0)
#include "bchp_v3d_mmu.h"
#include "bchp_v3d_mmuc.h"
#include "bchp_v3d_csd_0.h"
#else
#include "bchp_v3d_mmu_0.h"
#include "bchp_v3d_mmu_t.h"
#include "bchp_v3d_mmuc.h"
#endif
#else
/* These files were not per core */
#include "bchp_v3d_ctl.h"
#include "bchp_v3d_qpudbg.h"
#include "bchp_v3d_cle.h"
#include "bchp_v3d_gmp.h"
#include "bchp_v3d_ptb.h"
#include "bchp_v3d_qps.h"
#include "bchp_v3d_vpm.h"
#include "bchp_v3d_pctr.h"
#include "bchp_v3d_error.h"
#endif

/* These are not core specific */
#if !V3D_VER_AT_LEAST(4,1,34,0)
#include "bchp_v3d_gca.h"
#endif
#include "bchp_v3d_tfu.h"
#include "bchp_v3d_hub_ctl.h"
#ifdef BCHP_V3D_TOP_GR_BRIDGE_REG_START
#include "bchp_v3d_top_gr_bridge.h"
#endif
#ifdef BCHP_HIF_CPU_INTR1_REG_START
#include "bchp_hif_cpu_intr1.h"
#endif
#include "bchp_sun_top_ctrl.h"
#include "bchp_clkgen.h"

#ifdef V3D_HAS_BPCM
#if V3D_VER_AT_LEAST(3,3,0,0)
#include "bchp_cfgctl.h"
#include "bchp_zone0_fs.h"
#else
#include "bchp_v3d_bpcm.h"
#endif
#endif

#if V3D_VER_AT_LEAST(3,3,0,0)
/* Map the register names to core 0 addresses.
 * Address arithmetic in Read & WriteRegister will then
 * do the right thing. */
#define BCHP_V3D_CLE_CT0CA     BCHP_V3D_CLE_0_CT0CA
#define BCHP_V3D_CLE_CT0CS     BCHP_V3D_CLE_0_CT0CS
#define BCHP_V3D_CLE_CT1EA     BCHP_V3D_CLE_0_CT1EA
#define BCHP_V3D_CLE_CT0RA0    BCHP_V3D_CLE_0_CT0RA0
#define BCHP_V3D_CLE_CT0PC     BCHP_V3D_CLE_0_CT0PC
#define BCHP_V3D_CLE_CT1LC     BCHP_V3D_CLE_0_CT1LC
#define BCHP_V3D_CLE_TFBC      BCHP_V3D_CLE_0_TFBC
#define BCHP_V3D_CLE_CT1CFG    BCHP_V3D_CLE_0_CT1CFG
#define BCHP_V3D_CLE_CT1TSKIP  BCHP_V3D_CLE_0_CT1TSKIP
#define BCHP_V3D_CLE_CT0SYNC   BCHP_V3D_CLE_0_CT0SYNC
#define BCHP_V3D_CLE_CT0QEA    BCHP_V3D_CLE_0_CT0QEA
#define BCHP_V3D_CLE_CT1QBA    BCHP_V3D_CLE_0_CT1QBA
#define BCHP_V3D_CLE_CT0QMA    BCHP_V3D_CLE_0_CT0QMA
#define BCHP_V3D_CLE_CT1QCFG   BCHP_V3D_CLE_0_CT1QCFG
#define BCHP_V3D_CLE_CT0CA     BCHP_V3D_CLE_0_CT0CA
#define BCHP_V3D_CLE_CT1EA     BCHP_V3D_CLE_0_CT1EA
#define BCHP_V3D_CLE_CT0RA0    BCHP_V3D_CLE_0_CT0RA0
#define BCHP_V3D_CLE_CT0PC     BCHP_V3D_CLE_0_CT0PC
#define BCHP_V3D_CLE_CT1LC     BCHP_V3D_CLE_0_CT1LC
#define BCHP_V3D_CLE_TFBC      BCHP_V3D_CLE_0_TFBC
#define BCHP_V3D_CLE_CT0EA     BCHP_V3D_CLE_0_CT0EA
#define BCHP_V3D_CLE_CT1CA     BCHP_V3D_CLE_0_CT1CA
#define BCHP_V3D_CLE_CT1CS     BCHP_V3D_CLE_0_CT1CS
#define BCHP_V3D_CLE_CT0LC     BCHP_V3D_CLE_0_CT0LC
#define BCHP_V3D_CLE_CT1RA0    BCHP_V3D_CLE_0_CT1RA0
#define BCHP_V3D_CLE_CT1PC     BCHP_V3D_CLE_0_CT1PC
#define BCHP_V3D_CLE_TFIT      BCHP_V3D_CLE_0_TFIT
#define BCHP_V3D_CLE_CT1TILECT BCHP_V3D_CLE_0_CT1TILECT
#define BCHP_V3D_CLE_CT1PTCT   BCHP_V3D_CLE_0_CT1PTCT
#define BCHP_V3D_CLE_CT0QBA    BCHP_V3D_CLE_0_CT0QBA
#define BCHP_V3D_CLE_CT1SYNC   BCHP_V3D_CLE_0_CT1SYNC
#define BCHP_V3D_CLE_CT1QEA    BCHP_V3D_CLE_0_CT1QEA
#define BCHP_V3D_CLE_CT0QMS    BCHP_V3D_CLE_0_CT0QMS
#define BCHP_V3D_CLE_CT1QTSKIP BCHP_V3D_CLE_0_CT1QTSKIP
#define BCHP_V3D_CLE_CT1QBASE0 BCHP_V3D_CLE_0_CT1QBASE0
#define BCHP_V3D_CLE_CT1QBASE1 BCHP_V3D_CLE_0_CT1QBASE1
#define BCHP_V3D_CLE_CT1QBASE2 BCHP_V3D_CLE_0_CT1QBASE2
#define BCHP_V3D_CLE_CT1QBASE3 BCHP_V3D_CLE_0_CT1QBASE3
#define BCHP_V3D_CLE_CT1QBASE4 BCHP_V3D_CLE_0_CT1QBASE4
#define BCHP_V3D_CLE_CT1QBASE5 BCHP_V3D_CLE_0_CT1QBASE5
#define BCHP_V3D_CLE_CT1QBASE6 BCHP_V3D_CLE_0_CT1QBASE6
#define BCHP_V3D_CLE_CT1QBASE7 BCHP_V3D_CLE_0_CT1QBASE7
#define BCHP_V3D_CLE_CT0QSYNC  BCHP_V3D_CLE_0_CT0QSYNC
#define BCHP_V3D_CLE_CT1QSYNC  BCHP_V3D_CLE_0_CT1QSYNC
#define BCHP_V3D_CLE_PCS       BCHP_V3D_CLE_0_PCS
#define BCHP_V3D_CLE_BFC       BCHP_V3D_CLE_0_BFC
#define BCHP_V3D_CLE_RFC       BCHP_V3D_CLE_0_RFC
#define BCHP_V3D_CLE_CT0CA     BCHP_V3D_CLE_0_CT0CA
#define BCHP_V3D_CLE_CT0QMA    BCHP_V3D_CLE_0_CT0QMA
#define BCHP_V3D_CLE_CT0QMS    BCHP_V3D_CLE_0_CT0QMS
#define BCHP_V3D_CLE_CT0QBA    BCHP_V3D_CLE_0_CT0QBA
#define BCHP_V3D_CLE_CT0QEA    BCHP_V3D_CLE_0_CT0QEA
#define BCHP_V3D_CLE_CT1QCFG   BCHP_V3D_CLE_0_CT1QCFG
#define BCHP_V3D_CLE_CCNTCS    BCHP_V3D_CLE_0_CCNTCS

#define V3D_CLE_CT1QCFG        V3D_CLE_0_CT1QCFG
#define V3D_CLE_PCS            V3D_CLE_0_PCS
#define V3D_CLE_CCNTCS         V3D_CLE_0_CCNTCS

#define BCHP_V3D_CLE_CCBSLO    BCHP_V3D_CLE_0_CCBSLO
#define BCHP_V3D_CLE_CCBSHI    BCHP_V3D_CLE_0_CCBSHI
#define BCHP_V3D_CLE_CCBELO    BCHP_V3D_CLE_0_CCBELO
#define BCHP_V3D_CLE_CCBEHI    BCHP_V3D_CLE_0_CCBEHI
#define BCHP_V3D_CLE_CPBSLO    BCHP_V3D_CLE_0_CPBSLO
#define BCHP_V3D_CLE_CPBSHI    BCHP_V3D_CLE_0_CPBSHI
#define BCHP_V3D_CLE_CPBELO    BCHP_V3D_CLE_0_CPBELO
#define BCHP_V3D_CLE_CPBEHI    BCHP_V3D_CLE_0_CPBEHI
#define BCHP_V3D_CLE_CCRSLO    BCHP_V3D_CLE_0_CCRSLO
#define BCHP_V3D_CLE_CCRSHI    BCHP_V3D_CLE_0_CCRSHI
#define BCHP_V3D_CLE_CCRELO    BCHP_V3D_CLE_0_CCRELO
#define BCHP_V3D_CLE_CCREHI    BCHP_V3D_CLE_0_CCREHI
#define BCHP_V3D_CLE_CTRSLO    BCHP_V3D_CLE_0_CTRSLO
#define BCHP_V3D_CLE_CTRSHI    BCHP_V3D_CLE_0_CTRSHI
#define BCHP_V3D_CLE_CTRELO    BCHP_V3D_CLE_0_CTRELO
#define BCHP_V3D_CLE_CTREHI    BCHP_V3D_CLE_0_CTREHI

#define BCHP_V3D_PTB_BPCA BCHP_V3D_PTB_0_BPCA
#define BCHP_V3D_PTB_BPCS BCHP_V3D_PTB_0_BPCS
#define BCHP_V3D_PTB_BPOA BCHP_V3D_PTB_0_BPOA
#define BCHP_V3D_PTB_BPOS BCHP_V3D_PTB_0_BPOS
#define BCHP_V3D_PTB_BXCF BCHP_V3D_PTB_0_BXCF

#define BCHP_V3D_CTL_L2CACTL     BCHP_V3D_CTL_0_L2CACTL
#define BCHP_V3D_CTL_SLCACTL     BCHP_V3D_CTL_0_SLCACTL
#define BCHP_V3D_CTL_SCRATCH     BCHP_V3D_CTL_0_SCRATCH
#define BCHP_V3D_CTL_IDENT0      BCHP_V3D_CTL_0_IDENT0
#define BCHP_V3D_CTL_IDENT1      BCHP_V3D_CTL_0_IDENT1
#define BCHP_V3D_CTL_IDENT2      BCHP_V3D_CTL_0_IDENT2
#define BCHP_V3D_CTL_IDENT3      BCHP_V3D_CTL_0_IDENT3
#define BCHP_V3D_CTL_INT_STS     BCHP_V3D_CTL_0_INT_STS
#define BCHP_V3D_CTL_INT_MSK_STS BCHP_V3D_CTL_0_INT_MSK_STS
#define BCHP_V3D_CTL_L2TFLSTA    BCHP_V3D_CTL_0_L2TFLSTA
#define BCHP_V3D_CTL_L2TFLEND    BCHP_V3D_CTL_0_L2TFLEND
#define BCHP_V3D_CTL_L2TCACTL    BCHP_V3D_CTL_0_L2TCACTL
#define BCHP_V3D_CTL_L2CACTL     BCHP_V3D_CTL_0_L2CACTL
#define BCHP_V3D_CTL_SLCACTL     BCHP_V3D_CTL_0_SLCACTL
#define V3D_CTL_INT_MSK_CLR_INT  V3D_CTL_0_INT_MSK_CLR_INT
#define V3D_CTL_L2CACTL          V3D_CTL_0_L2CACTL
#define V3D_CTL_SLCACTL          V3D_CTL_0_SLCACTL
#define V3D_CTL_INT_STS_INT      V3D_CTL_0_INT_STS_INT
#define V3D_CTL_INT_STS          V3D_CTL_0_INT_STS
#define V3D_CTL_INT_CLR          V3D_CTL_0_INT_CLR
#define BCHP_V3D_CTL_INT_MSK_SET BCHP_V3D_CTL_0_INT_MSK_SET
#define BCHP_V3D_CTL_INT_CLR     BCHP_V3D_CTL_0_INT_CLR
#define BCHP_V3D_CTL_INT_MSK_CLR BCHP_V3D_CTL_0_INT_MSK_CLR
#define BCHP_V3D_CTL_MISCCFG     BCHP_V3D_CTL_0_MISCCFG

#define BCHP_V3D_QPS_SQRSV0      BCHP_V3D_QPS_0_SQRSV0
#define BCHP_V3D_QPS_SQRSV1      BCHP_V3D_QPS_0_SQRSV1
#define BCHP_V3D_QPS_SQCNTL      BCHP_V3D_QPS_0_SQCNTL

#define BCHP_V3D_VPM_VPACNTL     BCHP_V3D_VPM_0_ACNTL
#define BCHP_V3D_VPM_VPMBASE     BCHP_V3D_VPM_0_MEMBASE

#define BCHP_V3D_TFU_TFUCS          BCHP_V3D_TFU_CS
#define BCHP_V3D_TFU_TFUICFG        BCHP_V3D_TFU_ICFG
#define BCHP_V3D_TFU_TFUIIS         BCHP_V3D_TFU_IIS
#define BCHP_V3D_TFU_TFUIIA         BCHP_V3D_TFU_IIA
#define BCHP_V3D_TFU_TFUICA         BCHP_V3D_TFU_ICA
#define BCHP_V3D_TFU_TFUIUA         BCHP_V3D_TFU_IUA
#define BCHP_V3D_TFU_TFUSU          BCHP_V3D_TFU_SU
#define BCHP_V3D_TFU_TFUIOA         BCHP_V3D_TFU_IOA
#define BCHP_V3D_TFU_TFUIOS         BCHP_V3D_TFU_IOS
#define BCHP_V3D_TFU_TFUCOEF0       BCHP_V3D_TFU_COEF0
#define BCHP_V3D_TFU_TFUCOEF1       BCHP_V3D_TFU_COEF1
#define BCHP_V3D_TFU_TFUCOEF2       BCHP_V3D_TFU_COEF2
#define BCHP_V3D_TFU_TFUCOEF3       BCHP_V3D_TFU_COEF3
#define BCHP_V3D_TFU_TFUCRC         BCHP_V3D_TFU_CRC
#define BCHP_V3D_TFU_TFUINT_MSK_STS BCHP_V3D_TFU_INT_MSK_STS
#define BCHP_V3D_TFU_TFUINT_STS     BCHP_V3D_TFU_INT_STS
#define BCHP_V3D_TFU_TFUSYNC        BCHP_V3D_TFU_SYNC
#define BCHP_V3D_TFU_TFUINT_CLR     BCHP_V3D_TFU_INT_CLR
#define BCHP_V3D_TFU_TFUINT_MSK_STS BCHP_V3D_TFU_INT_MSK_STS
#define BCHP_V3D_PTB_BPOA           BCHP_V3D_PTB_0_BPOA
#define V3D_TFU_TFUINT_STS_INT      V3D_TFU_INT_STS_INT
#define V3D_TFU_TFUIOS              V3D_TFU_IOS
#define V3D_TFU_TFUINT_STS          V3D_TFU_INT_STS
#define V3D_TFU_TFUICFG             V3D_TFU_ICFG
#define V3D_TFU_TFUCOEF0            V3D_TFU_COEF0
#define V3D_TFU_TFUCOEF1            V3D_TFU_COEF1
#define V3D_TFU_TFUCOEF2            V3D_TFU_COEF2
#define V3D_TFU_TFUCOEF3            V3D_TFU_COEF3
#define V3D_TFU_TFUIOA              V3D_TFU_IOA
#define V3D_TFU_TFUIIS              V3D_TFU_IIS
#define V3D_TFU_TFUINT_CLR          V3D_TFU_INT_CLR
#define BCHP_V3D_TFU_TFUIOA_OADDR_SHIFT BCHP_V3D_TFU_IOA_OADDR_SHIFT
#define BCHP_V3D_TFU_TFUIOA_OADDR_MASK  BCHP_V3D_TFU_IOA_OADDR_MASK

#define BCHP_V3D_ERROR_ERRSTAT BCHP_V3D_ERR_0_STAT
#define BCHP_V3D_ERROR_DBGE    BCHP_V3D_ERR_0_DBGE
#define BCHP_V3D_ERROR_FDBGR   BCHP_V3D_ERR_0_FDBGR
#define BCHP_V3D_ERROR_FDBG0   BCHP_V3D_ERR_0_FDBG0
#define BCHP_V3D_ERROR_FDBGS   BCHP_V3D_ERR_0_FDBGS
#define BCHP_V3D_ERROR_FDBGB   BCHP_V3D_ERR_0_FDBGB

#define BCHP_V3D_PCTR_PCTR0   BCHP_V3D_PCTR_0_PCTR0
#define BCHP_V3D_PCTR_PCTR1   BCHP_V3D_PCTR_0_PCTR1
#define BCHP_V3D_PCTR_PCTRC   BCHP_V3D_PCTR_0_PCTRC
#define BCHP_V3D_PCTR_PCTRS0  BCHP_V3D_PCTR_0_PCTRS0
#define BCHP_V3D_PCTR_PCTRE   BCHP_V3D_PCTR_0_PCTRE
#define V3D_PCTR_PCTRE        V3D_PCTR_0_PCTRE

#define BCHP_V3D_GMP_CFG         BCHP_V3D_GMP_0_CFG
#define BCHP_V3D_GMP_STATUS      BCHP_V3D_GMP_0_STATUS
#define BCHP_V3D_GMP_TABLE_ADDR  BCHP_V3D_GMP_0_TABLE_ADDR
#define BCHP_V3D_GMP_CLEAR_LOAD  BCHP_V3D_GMP_0_CLEAR_LOAD
#define BCHP_V3D_GMP_VIO_TYPE    BCHP_V3D_GMP_0_VIO_TYPE
#define BCHP_V3D_GMP_VIO_ADDR    BCHP_V3D_GMP_0_VIO_ADDR

#define V3D_GMP_STATUS           V3D_GMP_0_STATUS
#define V3D_GMP_CFG              V3D_GMP_0_CFG
#define V3D_GMP_VIO_TYPE         V3D_GMP_0_VIO_TYPE

#if V3D_VER_AT_LEAST(4,1,34,0)
/* MMU registers unified on 4.0 onwards */
#define BCHP_V3D_MMU_0_CTRL         BCHP_V3D_MMU_CTRL
#define BCHP_V3D_MMU_0_PT_PA_BASE   BCHP_V3D_MMU_PT_PA_BASE
#define BCHP_V3D_MMU_0_ADDR_CAP     BCHP_V3D_MMU_ADDR_CAP
#define BCHP_V3D_MMU_0_ILLEGAL_ADR  BCHP_V3D_MMU_ILLEGAL_ADR
#define BCHP_V3D_MMU_0_VIO_ADDR     BCHP_V3D_MMU_VIO_ADDR
#define BCHP_V3D_MMU_0_VIO_ID       BCHP_V3D_MMU_VIO_ID
#define BCHP_V3D_MMU_0_MISSES       BCHP_V3D_MMU_MISSES
#define BCHP_V3D_MMU_0_STALLS       BCHP_V3D_MMU_STALLS
#define BCHP_V3D_MMU_0_HITS         BCHP_V3D_MMU_HITS

#define BCHP_V3D_MMU_0_PT_PA_BASE_PAGE_MASK     BCHP_V3D_MMU_PT_PA_BASE_PAGE_MASK
#define BCHP_V3D_MMU_0_CTRL_CAP_EXCEEDED_MASK   BCHP_V3D_MMU_CTRL_CAP_EXCEEDED_MASK
#define BCHP_V3D_MMU_0_CTRL_CAP_EXCEEDED_SHIFT  BCHP_V3D_MMU_CTRL_CAP_EXCEEDED_SHIFT
#define BCHP_V3D_MMU_0_CTRL_WRITE_VIOLATION_MASK   BCHP_V3D_MMU_CTRL_WRITE_VIOLATION_MASK
#define BCHP_V3D_MMU_0_CTRL_WRITE_VIOLATION_SHIFT  BCHP_V3D_MMU_CTRL_WRITE_VIOLATION_SHIFT
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_MASK     BCHP_V3D_MMU_CTRL_PT_INVALID_MASK
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_SHIFT    BCHP_V3D_MMU_CTRL_PT_INVALID_SHIFT
#define BCHP_V3D_MMU_0_CTRL_STATS_CLEAR         BCHP_V3D_MMU_CTRL_STATS_CLEAR
#define BCHP_V3D_MMU_0_ADDR_CAP_ENABLE_MASK     BCHP_V3D_MMU_ADDR_CAP_ENABLE_MASK
#define BCHP_V3D_MMU_0_ADDR_CAP_ENABLE_SHIFT    BCHP_V3D_MMU_ADDR_CAP_ENABLE_SHIFT
#define BCHP_V3D_MMU_0_ILLEGAL_ADR_ENABLE_MASK  BCHP_V3D_MMU_ILLEGAL_ADR_ENABLE_MASK
#define BCHP_V3D_MMU_0_ILLEGAL_ADR_ENABLE_SHIFT BCHP_V3D_MMU_ILLEGAL_ADR_ENABLE_SHIFT
#define BCHP_V3D_MMU_0_CTRL_CAP_EXCEEDED_ABORT_EN_MASK   BCHP_V3D_MMU_CTRL_CAP_EXCEEDED_ABORT_EN_MASK
#define BCHP_V3D_MMU_0_CTRL_CAP_EXCEEDED_ABORT_EN_SHIFT  BCHP_V3D_MMU_CTRL_CAP_EXCEEDED_ABORT_EN_SHIFT
#define BCHP_V3D_MMU_0_CTRL_WRITE_VIOLATION_ABORT_EN_MASK   BCHP_V3D_MMU_CTRL_WRITE_VIOLATION_ABORT_EN_MASK
#define BCHP_V3D_MMU_0_CTRL_WRITE_VIOLATION_ABORT_EN_SHIFT  BCHP_V3D_MMU_CTRL_WRITE_VIOLATION_ABORT_EN_SHIFT
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_ABORT_EN_MASK  BCHP_V3D_MMU_CTRL_PT_INVALID_ABORT_EN_MASK
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_ABORT_EN_SHIFT BCHP_V3D_MMU_CTRL_PT_INVALID_ABORT_EN_SHIFT
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_EN_MASK  BCHP_V3D_MMU_CTRL_PT_INVALID_EN_MASK
#define BCHP_V3D_MMU_0_CTRL_PT_INVALID_EN_SHIFT BCHP_V3D_MMU_CTRL_PT_INVALID_EN_SHIFT
#define BCHP_V3D_MMU_0_CTRL_STATS_ENABLE_MASK   BCHP_V3D_MMU_CTRL_STATS_ENABLE_MASK
#define BCHP_V3D_MMU_0_CTRL_STATS_ENABLE_SHIFT  BCHP_V3D_MMU_CTRL_STATS_ENABLE_SHIFT
#define BCHP_V3D_MMU_0_CTRL_ENABLE_MASK         BCHP_V3D_MMU_CTRL_ENABLE_MASK
#define BCHP_V3D_MMU_0_CTRL_ENABLE_SHIFT        BCHP_V3D_MMU_CTRL_ENABLE_SHIFT
#define BCHP_V3D_MMU_0_CTRL_TLB_CLEAR_MASK      BCHP_V3D_MMU_CTRL_TLB_CLEAR_MASK
#define BCHP_V3D_MMU_0_CTRL_TLB_CLEAR_SHIFT     BCHP_V3D_MMU_CTRL_TLB_CLEAR_SHIFT
#define BCHP_V3D_MMU_0_CTRL_TLB_CLEARING_MASK      BCHP_V3D_MMU_CTRL_TLB_CLEARING_MASK
#define BCHP_V3D_MMU_0_CTRL_TLB_CLEARING_SHIFT     BCHP_V3D_MMU_CTRL_TLB_CLEARING_SHIFT
#define BCHP_V3D_MMU_0_CTRL_STATS_CLEAR_MASK    BCHP_V3D_MMU_CTRL_STATS_CLEAR_MASK
#define BCHP_V3D_MMU_0_CTRL_STATS_CLEAR_SHIFT   BCHP_V3D_MMU_CTRL_STATS_CLEAR_SHIFT

#define BCHP_V3D_PCTR_0_PCTRE       BCHP_V3D_PCTR_0_EN
#define BCHP_V3D_PCTR_0_PCTRC       BCHP_V3D_PCTR_0_CLR

#define V3D_PCTR_0_PCTRE            V3D_PCTR_0_EN
#define CTEN                        CTEN0_CTEN31

#define BCHP_V3D_ERR_0_FDBG0        BCHP_V3D_ERR_0_FDBGO

#define BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_V3D_CLK_108_SW_INIT_ASSERT     BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_SPARE_SW_INIT_ASSERT
#define BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_V3D_CLK_108_SW_INIT_DEASSERT   BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_SPARE_SW_INIT_DEASSERT
#define BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_V3D_CLK_108_SW_INIT_MASK       BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_SPARE_SW_INIT_MASK
#define BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_V3D_CLK_108_SW_INIT_SHIFT      BCHP_V3D_TOP_GR_BRIDGE_SW_INIT_0_SPARE_SW_INIT_SHIFT
#endif

#endif /* Ver 3.3 */

#define BCHP_INT_ID_V3D_INTR              BCHP_INT_ID_CREATE(BCHP_V3D_CTL_INT_STS, 0)
#define BCHP_INT_ID_V3D_HUB_INTR          BCHP_INT_ID_CREATE(BCHP_V3D_HUB_CTL_INT_STS, 0)

#endif /* BVC5_HARDWARE_REAL */

#ifdef BVC5_HARDWARE_SIMPENROSE

#include "bvc5_simpenrose_hw_regs.h"
#include "bvc5_simpenrose_priv.h"

#endif /* BVC5_HARDWARE_SIMPENROSE */

#if V3D_VER_AT_LEAST(4,1,34,0)

#define V3D_AXI_ID_L2T 0
#define V3D_AXI_ID_PTB 1
#define V3D_AXI_ID_PSE 2
#define V3D_AXI_ID_TLB 3
#define V3D_AXI_ID_CLE 4
#define V3D_AXI_ID_TFU 5
#define V3D_AXI_ID_MMU 6
#define V3D_AXI_ID_GMP 7

#elif V3D_VER_AT_LEAST(3,3,0,0)

#define V3D_AXI_ID_L2T 0
#define V3D_AXI_ID_CLE 1
#define V3D_AXI_ID_PTB 2
#define V3D_AXI_ID_PSE 3
#define V3D_AXI_ID_TLB 4
#define V3D_AXI_ID_GMP 7
#define V3D_AXI_ID_TFU 8

#else

#define V3D_AXI_ID_L2C 0
#define V3D_AXI_ID_CLE 1
#define V3D_AXI_ID_PTB 2
#define V3D_AXI_ID_PSE 3
#define V3D_AXI_ID_VCD 4
#define V3D_AXI_ID_L2T 6
#define V3D_AXI_ID_TLB 7
#define V3D_AXI_ID_TFU 8

#endif

#endif /* BVC5_REGISTERS_PRIV_H */
