/************************************************************************
 *             Copyright (c) 2015 Broadcom Corporation                  *
 *                                                                      *
 *  This material is the confidential trade secret and proprietary      *
 *  information of Broadcom Corporation. It may not be reproduced,      *
 *  used, sold or transferred to any third party without the prior      *
 *  written consent of Broadcom Corporation. All rights reserved.       *
 *                                                                      *
 ************************************************************************/

/***
 *                           ##                   #
 *                          #  # #####  ##  ###  ###
 *                          #      #   #  # #  # ###
 *                           ##    #   #  # #  #  #
 *                             #   #   #  # ###   #
 *                          #  #   #   #  # #
 *                           ##    #    ##  #     #
 *
 *
 *    #   #  # ###  ##       ###  #### #    # #### ###    #   ### #### ###
 *   # #  #  #  #  #  #     #     #    ##   # #    #  #  # #   #  #    #  #
 *  #   # #  #  #  #  # ### #  ## ###  # #  # ###  ###  #   #  #  ###  #  #
 *  ##### #  #  #  #  #     #   # #    #  # # #    # #  #####  #  #    #  #
 *  #   #  ##   #   ##       ###  #### #   ## #### #  # #   #  #  #### ###
 */

/* Check for legacy configuration macros */
#ifndef _CHIP_H_
#if defined(HOST_BM)
#  error "Found HOST_BM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(HOST_SI)
#  error "Found HOST_SI already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_POSIX)
#  error "Found OS_POSIX already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_FREERTOS)
#  error "Found OS_FREERTOS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_CIRCULAR)
#  error "Found TB_CIRCULAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_LINEAR)
#  error "Found TB_LINEAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPLOG_MEMORY_SINK)
#  error "Found DSPLOG_MEMORY_SINK already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_MAGNUM)
#  error "Found RAAGA_HOST_SI_MAGNUM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_ROCKFORD)
#  error "Found RAAGA_HOST_SI_ROCKFORD already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_BIG_ENDIAN)
#  error "Found BCM_BIG_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_LITTLE_ENDIAN)
#  error "Found BCM_LITTLE_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPCONTROL_VOM)
#  error "Found DSPCONTROL_VOM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(LIBDSPCONTROL_DSPLESS)
#  error "Found LIBDSPCONTROL_DSPLESS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#endif /* _CHIP_H_*/

#ifndef _CHIP_H_
#define _CHIP_H_

/* We have to give a value to any macro we use as a literal or they will all default to 0 */
#define BCM93160A0_bm                                            42
#define BCM93160A0_si                                            43
#define BCM93160A0_wkstn                                         44
#define BCM960500_bm                                             45
#define BCM960500_si                                             46
#define BCM960500_wkstn                                          47
#define BCM961750_bm                                             48
#define BCM961750_si                                             49
#define BCM961750_si_no_dsp                                      50
#define BCM961750_wkstn                                          51
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF        52
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF      53
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE               54
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE            55
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET          56
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE 57
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_LOOPBACK      58
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE          59
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY          60
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL            61
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO           62
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG               63
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE            64
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE           65
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE         66
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_SUPPORTED     67
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED   68
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_SUPPORTED         69
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED       70
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING           71
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED                 72
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED           73
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED         74
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS            75
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX               76
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM        77
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD      78
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR         79
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER      80
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE             81
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_BM                         82
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS                   83
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON                    84
#define Pike_bm                                                  85
#define Pike_haps                                                86
#define Pike_wkstn                                               87
#define RaagaFP2008_bm                                           88
#define RaagaFP2008_si_magnum                                    89
#define RaagaFP2008_si_rockford_no_dsp                           90
#define RaagaFP2008_wkstn                                        91
#define RaagaFP2011_bm                                           92
#define RaagaFP2011_si_magnum                                    93
#define RaagaFP2011_si_rockford                                  94
#define RaagaFP2011_si_rockford_no_dsp                           95
#define RaagaFP2011_wkstn                                        96
#define RaagaFP2012_bm                                           97
#define RaagaFP2012_si_magnum                                    98
#define RaagaFP2012_si_rockford                                  99
#define RaagaFP2012_si_rockford_no_dsp                           100
#define RaagaFP2012_wkstn                                        101

/* Only one, recognisable, TARGET_SOC defined */
#if !defined(BFPSDK_LIBDSPCONTROL_TARGET_SOC)
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be defined and be one of RaagaFP2008_si_rockford_no_dsp, BCM961750_si_no_dsp, BCM93160A0_wkstn, RaagaFP2011_si_magnum, RaagaFP2012_si_rockford_no_dsp, RaagaFP2012_bm, BCM961750_si, BCM961750_wkstn, BCM93160A0_si, Pike_bm, RaagaFP2011_bm, RaagaFP2012_si_rockford, RaagaFP2011_si_rockford_no_dsp, RaagaFP2011_si_rockford, BCM960500_si, RaagaFP2012_wkstn, RaagaFP2008_bm, BCM93160A0_bm, RaagaFP2012_si_magnum, Pike_haps, RaagaFP2008_si_magnum, RaagaFP2011_wkstn, BCM960500_wkstn, Pike_wkstn, BCM961750_bm, RaagaFP2008_wkstn, BCM960500_bm"
#elif !((BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_rockford_no_dsp) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si_no_dsp) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_magnum) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford_no_dsp) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford_no_dsp) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_magnum) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_magnum) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_bm))
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be one of RaagaFP2008_si_rockford_no_dsp, BCM961750_si_no_dsp, BCM93160A0_wkstn, RaagaFP2011_si_magnum, RaagaFP2012_si_rockford_no_dsp, RaagaFP2012_bm, BCM961750_si, BCM961750_wkstn, BCM93160A0_si, Pike_bm, RaagaFP2011_bm, RaagaFP2012_si_rockford, RaagaFP2011_si_rockford_no_dsp, RaagaFP2011_si_rockford, BCM960500_si, RaagaFP2012_wkstn, RaagaFP2008_bm, BCM93160A0_bm, RaagaFP2012_si_magnum, Pike_haps, RaagaFP2008_si_magnum, RaagaFP2011_wkstn, BCM960500_wkstn, Pike_wkstn, BCM961750_bm, RaagaFP2008_wkstn, BCM960500_bm"
#endif

/* Is CHIP defined from outside or should we set it from the TARGET_SOC? */
#if (defined(MCPHY) || defined(PIKE) || defined(DUNA) || defined(CELIVERO) || defined(RAAGA))
/* Check if multiple CHIPs are defined */
#  if !(!((defined(MCPHY) && ((defined(PIKE) || defined(DUNA) || defined(CELIVERO) || defined(RAAGA)))) || (defined(PIKE) && ((defined(MCPHY) || defined(DUNA) || defined(CELIVERO) || defined(RAAGA)))) || (defined(DUNA) && ((defined(MCPHY) || defined(PIKE) || defined(CELIVERO) || defined(RAAGA)))) || (defined(CELIVERO) && ((defined(MCPHY) || defined(PIKE) || defined(DUNA) || defined(RAAGA)))) || (defined(RAAGA) && ((defined(MCPHY) || defined(PIKE) || defined(DUNA) || defined(CELIVERO))))))
#    error "Multiple 'CHIP' macros defined - check your external defines"
#  endif
#else
/* Define CHIP from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_rockford_no_dsp
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si_no_dsp
#    define CELIVERO
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_wkstn
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_magnum
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford_no_dsp
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_bm
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si
#    define CELIVERO
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_wkstn
#    define CELIVERO
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_si
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define PIKE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_bm
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford_no_dsp
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_si
#    define DUNA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_wkstn
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_bm
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_bm
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_magnum
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define PIKE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_magnum
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_wkstn
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_wkstn
#    define DUNA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define PIKE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_bm
#    define CELIVERO
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_wkstn
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_bm
#    define DUNA
#  endif
#endif

/* Is MACH defined from outside or should we set it from the TARGET_SOC? */
#if (defined(__FP2011__) || defined(__FP2008__) || defined(__FP4014__) || defined(__FP2012__))
/* Check if multiple MACHs are defined */
#  if !(!((defined(__FP2011__) && ((defined(__FP2008__) || defined(__FP4014__) || defined(__FP2012__)))) || (defined(__FP2008__) && ((defined(__FP2011__) || defined(__FP4014__) || defined(__FP2012__)))) || (defined(__FP2012__) && ((defined(__FP2011__) || defined(__FP2008__) || defined(__FP4014__)))) || (defined(__FP4014__) && ((defined(__FP2011__) || defined(__FP2008__) || defined(__FP2012__))))))
#    error "Multiple 'MACH' macros defined - check your external defines"
#  endif
#else
/* Define MACH from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_rockford_no_dsp
#    define __FP2008__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si_no_dsp
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_wkstn
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_magnum
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford_no_dsp
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_bm
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_wkstn
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_si
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_bm
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford_no_dsp
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_si
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_wkstn
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_bm
#    define __FP2008__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_bm
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_magnum
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_magnum
#    define __FP2008__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_wkstn
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_wkstn
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_bm
#    define __FP2011__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_wkstn
#    define __FP2008__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_bm
#    define __FP2011__
#  endif
#endif

/* Per-TARGET_SOC features */
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_rockford_no_dsp
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si_no_dsp
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_magnum
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford_no_dsp
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_si
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_si
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_LOOPBACK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_rockford
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford_no_dsp
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_si_rockford
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_ROCKFORD
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_si
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2012_si_magnum
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_si_magnum
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2011_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM961750_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP2008_wkstn
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM960500_bm
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV              BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_DEBUG_CONSOLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE      BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC          BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM     BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT    BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS     BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK   BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST       BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS       BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO       BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif

/* Utility macros */
#define IS_TARGET(target)      (BFPSDK_LIBDSPCONTROL_TARGET_SOC == target)
#define IS_HOST(host)          (BFPSDK_LIBDSPCONTROL_HOST_ENV == BFPSDK_LIBDSPCONTROL_HOST_ENV_ ## host)
#define HAS_FEATURE(feat)      (defined(BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat))
#define FEATURE_IS(feat,value) (BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat == BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat ## _ ## value)

#endif /* _CHIP_H_ */
