/******************************************************************************
 *  Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 ******************************************************************************/

#ifndef BMXT_DEBUG_RDB__
#define BMXT_DEBUG_RDB__

/* 45308B0 extra debug registers */
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W0_STATUS      0x7105a00
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W1_STATUS      0x7105a04
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS 0x7105a08
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W1_MASK_STATUS 0x7105a0c
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W0_MASK_SET    0x7105a10
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W1_MASK_SET    0x7105a14
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR  0x7105a18
#define BCHP_DEMOD_XPT_FE_CPU_INTR_AGGREGATOR_INTR_W1_MASK_CLEAR  0x7105a1c

#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_STATUS      0x7105a80
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_SET         0x7105a84
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_CLEAR       0x7105a88
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_MASK_STATUS 0x7105a8c
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_MASK_SET    0x7105a90
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_CPU_MASK_CLEAR  0x7105a94
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_STATUS      0x7105a98
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_SET         0x7105a9c
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_CLEAR       0x7105aa0
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_MASK_STATUS 0x7105aa4
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_MASK_SET    0x7105aa8
#define BCHP_DEMOD_XPT_FE_PARSER_LENGTH_ERROR_L2_INTR_W0_PCI_MASK_CLEAR  0x7105aac

#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_STATUS      0x7105b00
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_SET         0x7105b04
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_CLEAR       0x7105b08
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_MASK_STATUS 0x7105b0c
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_MASK_SET    0x7105b10
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_CPU_MASK_CLEAR  0x7105b14
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_STATUS      0x7105b18
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_SET         0x7105b1c
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_CLEAR       0x7105b20
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_MASK_STATUS 0x7105b24
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_MASK_SET    0x7105b28
#define BCHP_DEMOD_XPT_FE_PARSER_TRANSPORT_ERROR_L2_INTR_W2_PCI_MASK_CLEAR  0x7105b2c

#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_STATUS      0x7105e00
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_SET         0x7105e04
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_CLEAR       0x7105e08
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_MASK_STATUS 0x7105e0c
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_MASK_SET    0x7105e10
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_CPU_MASK_CLEAR  0x7105e14
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_STATUS      0x7105e18
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_SET         0x7105e1c
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_CLEAR       0x7105e20
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_MASK_STATUS 0x7105e24
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_MASK_SET    0x7105e28
#define BCHP_DEMOD_XPT_FE_ISSY_DISCONT_ERROR_L2_INTR_W14_PCI_MASK_CLEAR  0x7105e2c

#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_STATUS      0x7105e40
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_SET         0x7105e44
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_CLEAR       0x7105e48
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_MASK_STATUS 0x7105e4c
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_MASK_SET    0x7105e50
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_CPU_MASK_CLEAR  0x7105e54
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_STATUS      0x7105e58
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_SET         0x7105e5c
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_CLEAR       0x7105e60
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_MASK_STATUS 0x7105e64
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_MASK_SET    0x7105e68
#define BCHP_DEMOD_XPT_FE_ISSY_PACING_ERROR_L2_INTR_W15_PCI_MASK_CLEAR  0x7105e6c

#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_STATUS      0x7105e80
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_SET         0x7105e84
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_CLEAR       0x7105e88
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_MASK_STATUS 0x7105e8c
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_MASK_SET    0x7105e90
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_CPU_MASK_CLEAR  0x7105e94
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_STATUS      0x7105e98
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_SET         0x7105e9c
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_CLEAR       0x7105ea0
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_MASK_STATUS 0x7105ea4
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_MASK_SET    0x7105ea8
#define BCHP_DEMOD_XPT_FE_DCBG_ISSY_PID_MATCH_ERROR_L2_INTR_W16_PCI_MASK_CLEAR  0x7105eac

#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_STATUS      0x7105ec0
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_SET         0x7105ec4
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_CLEAR       0x7105ec8
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_MASK_STATUS 0x7105ecc
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_MASK_SET    0x7105ed0
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_CPU_MASK_CLEAR  0x7105ed4
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_STATUS      0x7105ed8
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_SET         0x7105edc
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_CLEAR       0x7105ee0
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_MASK_STATUS 0x7105ee4
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_MASK_SET    0x7105ee8
#define BCHP_DEMOD_XPT_FE_ATS_ISSY_RATIO_SNAPSHOT_VALID_L2_INTR_W17_PCI_MASK_CLEAR  0x7105eec

#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_STATUS      0x7105f00
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_SET         0x7105f04
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_CLEAR       0x7105f08
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_MASK_STATUS 0x7105f0c
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_MASK_SET    0x7105f10
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_CPU_MASK_CLEAR  0x7105f14
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_STATUS      0x7105f18
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_SET         0x7105f1c
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_CLEAR       0x7105f20
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_MASK_STATUS 0x7105f24
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_MASK_SET    0x7105f28
#define BCHP_DEMOD_XPT_FE_FALSE_WAKE_ERROR_L2_INTR_W18_PCI_MASK_CLEAR  0x7105f2c

#endif
