############################################################
#  Copyright (C) 2017 Broadcom.  The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
#
#  This program is the proprietary software of Broadcom and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
#  USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
#  ANY LIMITED REMEDY.
#
############################################################


##############################
#
# exluded NEXUS modules
#

export NEXUS_PWM_SUPPORT=n
export NEXUS_LED_SUPPORT=n
export NEXUS_IR_INPUT_SUPPORT=n
export NEXUS_IR_BLASTER_SUPPORT=n
export NEXUS_INPUT_CAPTURE_SUPPORT=n
export NEXUS_UHF_INPUT_SUPPORT=n
export NEXUS_KEYPAD_SUPPORT=n
export NEXUS_FRONTEND_SUPPORT=n
export NEXUS_SPI_SUPPORT=n
export NEXUS_SECURITY_SUPPORT=n
export SAGE_SUPPORT=n
export NEXUS_PICTURE_DECODER_SUPPORT=n
export NEXUS_HDMI_INPUT_SUPPORT=n
export V3D_SUPPORT=n
export NEXUS_DMA_SUPPORT=n
export NEXUS_TRANSPORT_SUPPORT=n
export NEXUS_VIDEO_DECODER_SUPPORT=n
export NEXUS_AUDIO_SUPPORT=n
export NEXUS_ASTM_SUPPORT=n
export NEXUS_GRAPHICS2D_SUPPORT=n
export NEXUS_SYNC_CHANNEL_SUPPORT=n
export NEXUS_CEC_SUPPORT=n
export NEXUS_SMARTCARD_SUPPORT=n
export NSK2_SUPPORT=n
export NSK2_EMM_SUPPORT=n
export NSK2_SMARTCARD_SUPPORT=n
export NEXUS_DVB_CI_SUPPORT=n
export NEXUS_SURFACE_COMPOSITOR_SUPPORT=n
export NEXUS_INPUT_ROUTER_SUPPORT=n
export NEXUS_SIMPLE_DECODER_SUPPORT=n
export NEXUS_UART_SUPPORT=n
export NEXUS_VIDEO_ENCODER_SUPPORT=n
export NEXUS_STREAM_MUX_SUPPORT=n
export NEXUS_FILE_MUX_SUPPORT=n
export NEXUS_FILE_SUPPORT=n
export NEXUS_PLAYBACK_SUPPORT=n
export NEXUS_RECORD_SUPPORT=n
export NEXUS_ASP_SUPPORT=n
export NEXUS_TOUCHPAD_SUPPORT=n
export NEXUS_TEMP_MONITOR_SUPPORT=n
export SCM_SUPPORT=n
export NEXUS_MPOD_SUPPORT=n
export NEXUS_VBI_SUPPORT=n
export NEXUS_XDM_SUPPORT=n
export NEXUS_DBV_SUPPORT=n
export NEXUS_DISPLAY_DYNRNG_EXTENSION_SUPPORT=n