/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Apr  1 11:25:04 2015
 *                 Full Compile MD5 Checksum  267f8e92d9b43928c0a06f1ab29c511c
 *                     (minus title and desc)
 *                 MD5 Checksum               0548f7f0a8e20364fd383a7aa29c0b86
 *
 * Compiled with:  RDB Utility                unknown
 *                 RDB.pm                     15956
 *                 generate_int_id.pl         1.0
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/generate_int_id.pl
 *                 DVTSWVER                   n/a
 *
 *
 ***************************************************************************/

#include "bchp.h"
#include "bchp_bvnm_intr2_0.h"

#ifndef BCHP_INT_ID_BVNM_INTR2_0_H__
#define BCHP_INT_ID_BVNM_INTR2_0_H__

#define BCHP_INT_ID_DNR_0_ERR_INTR            BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_DNR_0_ERR_INTR_SHIFT)
#define BCHP_INT_ID_DNR_1_ERR_INTR            BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_DNR_1_ERR_INTR_SHIFT)
#define BCHP_INT_ID_HSCL_0_INTR               BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_HSCL_0_INTR_SHIFT)
#define BCHP_INT_ID_MDI_0_BVB_IN_INTR         BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_MDI_0_BVB_IN_INTR_SHIFT)
#define BCHP_INT_ID_MVP_TOP_0_INTR            BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_MVP_TOP_0_INTR_SHIFT)
#define BCHP_INT_ID_SCL_0_ERR_INTR            BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_SCL_0_ERR_INTR_SHIFT)
#define BCHP_INT_ID_SCL_1_ERR_INTR            BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_SCL_1_ERR_INTR_SHIFT)
#define BCHP_INT_ID_XSRC_0_ERR_INTR           BCHP_INT_ID_CREATE(BCHP_BVNM_INTR2_0_R5F_STATUS, BCHP_BVNM_INTR2_0_R5F_STATUS_XSRC_0_ERR_INTR_SHIFT)

#endif /* #ifndef BCHP_INT_ID_BVNM_INTR2_0_H__ */

/* End of File */
