/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Apr  1 11:23:10 2015
 *                 Full Compile MD5 Checksum  267f8e92d9b43928c0a06f1ab29c511c
 *                     (minus title and desc)
 *                 MD5 Checksum               0548f7f0a8e20364fd383a7aa29c0b86
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15956
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/combo_header.pl
 *                 DVTSWVER                   n/a
 *
 *
 ***************************************************************************/

#ifndef BCHP_DFE_OFSDEC_H__
#define BCHP_DFE_OFSDEC_H__

/***************************************************************************
 *DFE_OFSDEC
 ***************************************************************************/
#define BCHP_DFE_OFSDEC_OFS_CONTROL              0x133d200 /* [RW] OFS_CONTROL */
#define BCHP_DFE_OFSDEC_OFS_TARGET               0x133d204 /* [RW] OFS_TARGET */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_2        0x133d208 /* [RW] OFS_NOMINAL_NCO_2 */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_1        0x133d20c /* [RW] OFS_NOMINAL_NCO_1 */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_0        0x133d210 /* [RW] OFS_NOMINAL_NCO_0 */
#define BCHP_DFE_OFSDEC_OFS_NCO_2                0x133d214 /* [RO] OFS_NCO_2 */
#define BCHP_DFE_OFSDEC_OFS_NCO_1                0x133d218 /* [RO] OFS_NCO_1 */
#define BCHP_DFE_OFSDEC_OFS_NCO_0                0x133d21c /* [RO] OFS_NCO_0 */
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH            0x133d220 /* [RW] OFS_BANDWIDTH */
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_1           0x133d224 /* [RO] OFS_ERR_CNTR_1 */
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_0           0x133d228 /* [RO] OFS_ERR_CNTR_0 */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL       0x133d22c /* [RW] OFS_INSERT_CONTROL */
#define BCHP_DFE_OFSDEC_OFS_INSERT_COUNT         0x133d230 /* [RW] OFS_INSERT_COUNT */
#define BCHP_DFE_OFSDEC_OFS_START_TARGET         0x133d234 /* [RW] OFS_START_TARGET */

/***************************************************************************
 *OFS_CONTROL - OFS_CONTROL
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_CONTROL :: mpeg_error_type [07:07] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_mpeg_error_type_MASK           0x80
#define BCHP_DFE_OFSDEC_OFS_CONTROL_mpeg_error_type_SHIFT          7
#define BCHP_DFE_OFSDEC_OFS_CONTROL_mpeg_error_type_DEFAULT        0x00

/* DFE_OFSDEC :: OFS_CONTROL :: go_bit_ofs [06:06] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_go_bit_ofs_MASK                0x40
#define BCHP_DFE_OFSDEC_OFS_CONTROL_go_bit_ofs_SHIFT               6
#define BCHP_DFE_OFSDEC_OFS_CONTROL_go_bit_ofs_DEFAULT             0x00

/* DFE_OFSDEC :: OFS_CONTROL :: buffer_underflow [05:05] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_underflow_MASK          0x20
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_underflow_SHIFT         5
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_underflow_DEFAULT       0x00

/* DFE_OFSDEC :: OFS_CONTROL :: buffer_overflow [04:04] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_overflow_MASK           0x10
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_overflow_SHIFT          4
#define BCHP_DFE_OFSDEC_OFS_CONTROL_buffer_overflow_DEFAULT        0x00

/* DFE_OFSDEC :: OFS_CONTROL :: disable_error_filter [03:03] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_error_filter_MASK      0x08
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_error_filter_SHIFT     3
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_error_filter_DEFAULT   0x00

/* DFE_OFSDEC :: OFS_CONTROL :: resume_data_output [02:02] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_resume_data_output_MASK        0x04
#define BCHP_DFE_OFSDEC_OFS_CONTROL_resume_data_output_SHIFT       2
#define BCHP_DFE_OFSDEC_OFS_CONTROL_resume_data_output_DEFAULT     0x00

/* DFE_OFSDEC :: OFS_CONTROL :: disable_output_of_mpeg_packets_with_mpeg_errors [01:01] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_output_of_mpeg_packets_with_mpeg_errors_MASK 0x02
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_output_of_mpeg_packets_with_mpeg_errors_SHIFT 1
#define BCHP_DFE_OFSDEC_OFS_CONTROL_disable_output_of_mpeg_packets_with_mpeg_errors_DEFAULT 0x00

/* DFE_OFSDEC :: OFS_CONTROL :: enable_loop [00:00] */
#define BCHP_DFE_OFSDEC_OFS_CONTROL_enable_loop_MASK               0x01
#define BCHP_DFE_OFSDEC_OFS_CONTROL_enable_loop_SHIFT              0
#define BCHP_DFE_OFSDEC_OFS_CONTROL_enable_loop_DEFAULT            0x00

/***************************************************************************
 *OFS_TARGET - OFS_TARGET
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_TARGET :: buffer_fill_target_level [07:00] */
#define BCHP_DFE_OFSDEC_OFS_TARGET_buffer_fill_target_level_MASK   0xff
#define BCHP_DFE_OFSDEC_OFS_TARGET_buffer_fill_target_level_SHIFT  0
#define BCHP_DFE_OFSDEC_OFS_TARGET_buffer_fill_target_level_DEFAULT 0x60

/***************************************************************************
 *OFS_NOMINAL_NCO_2 - OFS_NOMINAL_NCO_2
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NOMINAL_NCO_2 :: nominal_nco_2 [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_2_nominal_nco_2_MASK       0xff
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_2_nominal_nco_2_SHIFT      0
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_2_nominal_nco_2_DEFAULT    0x80

/***************************************************************************
 *OFS_NOMINAL_NCO_1 - OFS_NOMINAL_NCO_1
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NOMINAL_NCO_1 :: nominal_nco_middle_byte [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_1_nominal_nco_middle_byte_MASK 0xff
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_1_nominal_nco_middle_byte_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_1_nominal_nco_middle_byte_DEFAULT 0x00

/***************************************************************************
 *OFS_NOMINAL_NCO_0 - OFS_NOMINAL_NCO_0
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NOMINAL_NCO_0 :: nominal_nco_lsb [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_0_nominal_nco_lsb_MASK     0xff
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_0_nominal_nco_lsb_SHIFT    0
#define BCHP_DFE_OFSDEC_OFS_NOMINAL_NCO_0_nominal_nco_lsb_DEFAULT  0x00

/***************************************************************************
 *OFS_NCO_2 - OFS_NCO_2
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NCO_2 :: current_nco_msb [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NCO_2_current_nco_msb_MASK             0xff
#define BCHP_DFE_OFSDEC_OFS_NCO_2_current_nco_msb_SHIFT            0
#define BCHP_DFE_OFSDEC_OFS_NCO_2_current_nco_msb_DEFAULT          0x80

/***************************************************************************
 *OFS_NCO_1 - OFS_NCO_1
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NCO_1 :: current_nco_middle_byte [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NCO_1_current_nco_middle_byte_MASK     0xff
#define BCHP_DFE_OFSDEC_OFS_NCO_1_current_nco_middle_byte_SHIFT    0
#define BCHP_DFE_OFSDEC_OFS_NCO_1_current_nco_middle_byte_DEFAULT  0x00

/***************************************************************************
 *OFS_NCO_0 - OFS_NCO_0
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_NCO_0 :: current_nco_lsb [07:00] */
#define BCHP_DFE_OFSDEC_OFS_NCO_0_current_nco_lsb_MASK             0xff
#define BCHP_DFE_OFSDEC_OFS_NCO_0_current_nco_lsb_SHIFT            0
#define BCHP_DFE_OFSDEC_OFS_NCO_0_current_nco_lsb_DEFAULT          0x00

/***************************************************************************
 *OFS_BANDWIDTH - OFS_BANDWIDTH
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_BANDWIDTH :: reserved0 [07:07] */
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_reserved0_MASK               0x80
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_reserved0_SHIFT              7

/* DFE_OFSDEC :: OFS_BANDWIDTH :: zeta [06:04] */
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_zeta_MASK                    0x70
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_zeta_SHIFT                   4
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_zeta_DEFAULT                 0x07

/* DFE_OFSDEC :: OFS_BANDWIDTH :: ofs_bandwidth [03:00] */
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_ofs_bandwidth_MASK           0x0f
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_ofs_bandwidth_SHIFT          0
#define BCHP_DFE_OFSDEC_OFS_BANDWIDTH_ofs_bandwidth_DEFAULT        0x08

/***************************************************************************
 *OFS_ERR_CNTR_1 - OFS_ERR_CNTR_1
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_ERR_CNTR_1 :: mpeg_packet_error_counter_msb [07:00] */
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_1_mpeg_packet_error_counter_msb_MASK 0xff
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_1_mpeg_packet_error_counter_msb_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_1_mpeg_packet_error_counter_msb_DEFAULT 0x00

/***************************************************************************
 *OFS_ERR_CNTR_0 - OFS_ERR_CNTR_0
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_ERR_CNTR_0 :: mpeg_packet_error_counter_lsb [07:00] */
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_0_mpeg_packet_error_counter_lsb_MASK 0xff
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_0_mpeg_packet_error_counter_lsb_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_ERR_CNTR_0_mpeg_packet_error_counter_lsb_DEFAULT 0x00

/***************************************************************************
 *OFS_INSERT_CONTROL - OFS_INSERT_CONTROL
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: reserved0 [07:06] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_reserved0_MASK          0xc0
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_reserved0_SHIFT         6

/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: serial_sync_control [05:05] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_serial_sync_control_MASK 0x20
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_serial_sync_control_SHIFT 5
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_serial_sync_control_DEFAULT 0x00

/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: dummy_insert_fail_flag [04:04] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insert_fail_flag_MASK 0x10
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insert_fail_flag_SHIFT 4
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insert_fail_flag_DEFAULT 0x00

/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: dummy_insertion_value [03:02] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insertion_value_MASK 0x0c
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insertion_value_SHIFT 2
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_insertion_value_DEFAULT 0x00

/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: mpeg_error_gated [01:01] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_mpeg_error_gated_MASK   0x02
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_mpeg_error_gated_SHIFT  1
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_mpeg_error_gated_DEFAULT 0x00

/* DFE_OFSDEC :: OFS_INSERT_CONTROL :: dummy_removal_enable [00:00] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_removal_enable_MASK 0x01
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_removal_enable_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_INSERT_CONTROL_dummy_removal_enable_DEFAULT 0x00

/***************************************************************************
 *OFS_INSERT_COUNT - OFS_INSERT_COUNT
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_INSERT_COUNT :: insert_num_of_bytes [07:00] */
#define BCHP_DFE_OFSDEC_OFS_INSERT_COUNT_insert_num_of_bytes_MASK  0xff
#define BCHP_DFE_OFSDEC_OFS_INSERT_COUNT_insert_num_of_bytes_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_INSERT_COUNT_insert_num_of_bytes_DEFAULT 0x00

/***************************************************************************
 *OFS_START_TARGET - OFS_START_TARGET
 ***************************************************************************/
/* DFE_OFSDEC :: OFS_START_TARGET :: start_buffer_fill_target_level [07:00] */
#define BCHP_DFE_OFSDEC_OFS_START_TARGET_start_buffer_fill_target_level_MASK 0xff
#define BCHP_DFE_OFSDEC_OFS_START_TARGET_start_buffer_fill_target_level_SHIFT 0
#define BCHP_DFE_OFSDEC_OFS_START_TARGET_start_buffer_fill_target_level_DEFAULT 0x00

#endif /* #ifndef BCHP_DFE_OFSDEC_H__ */

/* End of File */
