/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#ifndef __DRM_LIBS_H__
#define __DRM_LIBS_H__

#pragma comment(lib, "drmactivationstub.lib")
#pragma comment(lib, "drmapppolicystub.lib")
#pragma comment(lib, "drmapprevocationreal.lib")
#pragma comment(lib, "drmantirollbackclockreal.lib")
#pragma comment(lib, "drmbase64real.lib")
#pragma comment(lib, "drmblackbox.lib")
#pragma comment(lib, "drmbbxslkstub.lib")
#pragma comment(lib, "drmbbxlegacyreal.lib")
#pragma comment(lib, "drmcertcachereal.lib")
#pragma comment(lib, "drmcertparsercachereal.lib")
#pragma comment(lib, "drmcerts.lib")
#pragma comment(lib, "drmchkdebugreal.lib")
#pragma comment(lib, "drmcleanstorereal.lib")
#pragma comment(lib, "drmcontentrevocationreal.lib")
#pragma comment(lib, "drmcontractreal.lib")
#pragma comment(lib, "drmcopyoplreal.lib")
#pragma comment(lib, "drmcore.lib")
#pragma comment(lib, "drmcrtreal.lib")
#pragma comment(lib, "drmdatastorereal.lib")
#pragma comment(lib, "drmdeletedstorereal.lib")
#pragma comment(lib, "drmdevcertkeygenreal.lib")
#pragma comment(lib, "drmdeviceassetsreal.lib")
#pragma comment(lib, "drmdevicerevocationreal.lib")
#pragma comment(lib, "drmdevicestorestub.lib")
#pragma comment(lib, "drmdlareal.lib")
#pragma comment(lib, "drmdomainreal.lib")
#pragma comment(lib, "drmestreal.lib")
#pragma comment(lib, "drmhdsblockheadercachereal.lib")
#pragma comment(lib, "drmhdsreal.lib")
#pragma comment(lib, "drmheaderparserreal.lib")
#pragma comment(lib, "drmkeyfile.lib")
#pragma comment(lib, "drmkeyfileformat.lib")
#pragma comment(lib, "drmlicensesyncreal.lib")
#pragma comment(lib, "drmlicgenstub.lib")
#pragma comment(lib, "drmlicstorereal.lib")
#pragma comment(lib, "drmmanager.lib")
#pragma comment(lib, "drmmetercertrevocationreal.lib")
#pragma comment(lib, "drmmeteringreal.lib")
#pragma comment(lib, "drmmodelrevocationstub.lib")
#pragma comment(lib, "drmmovestub.lib")
#pragma comment(lib, "drmnoncestorereal.lib")
#pragma comment(lib, "drmperformancereal.lib")
#pragma comment(lib, "drmplayreadyobjreal.lib")
#pragma comment(lib, "drmprndstub.lib")
#pragma comment(lib, "drmprndrxstub.lib")
#pragma comment(lib, "drmprndtxstub.lib")
#pragma comment(lib, "drmremovaldatestorereal.lib")
#pragma comment(lib, "drmsecureclockreal.lib")
#pragma comment(lib, "drmstkallocreal.lib")
#pragma comment(lib, "drmstrsafereal.lib")
#pragma comment(lib, "drmsymoptreal.lib")
#pragma comment(lib, "drmthumbnailreal.lib")
#pragma comment(lib, "drmutfreal.lib")
#pragma comment(lib, "drmutilitiescrypto.lib")
#pragma comment(lib, "drmutilitiesgeneral.lib")
#pragma comment(lib, "drmviewrightsreal.lib")
#pragma comment(lib, "drmwmdrmreal.lib")
#pragma comment(lib, "drmwmdrmnetreal.lib")
#pragma comment(lib, "drmxbinaryreal.lib")
#pragma comment(lib, "drmxmlbuildergeneral.lib")
#pragma comment(lib, "drmxmlhashreal.lib")
#pragma comment(lib, "drmxmlparsergeneral.lib")
#pragma comment(lib, "drmxmlbuildercrypto.lib")
#pragma comment(lib, "drmxmlbuildergeneral.lib")
#pragma comment(lib, "drmxmlsigbuilder.lib")
#pragma comment(lib, "drmxmlsiggeneral.lib")
#pragma comment(lib, "drmxmrbuilder.lib")
#pragma comment(lib, "drmxmrcommon.lib")
#pragma comment(lib, "drmxmrparser.lib")
#pragma comment(lib, "drmxmlparsercrypto.lib")

#pragma comment(lib, "oemaes.lib")
#pragma comment(lib, "oem_ansi.lib")
#pragma comment(lib, "oembignum.lib")
#pragma comment(lib, "oemcbc.lib")
#pragma comment(lib, "oemcipher.lib")
#pragma comment(lib, "oem_common.lib")
#pragma comment(lib, "oemdes.lib")
#pragma comment(lib, "oemeccbase.lib")
#pragma comment(lib, "oemeccbaseimpl.lib")
#pragma comment(lib, "oemhaloemimpl.lib")
#pragma comment(lib, "oemhalshared.lib")
#pragma comment(lib, "oem_keyfile.lib")
#pragma comment(lib, "oemmd5.lib")
#pragma comment(lib, "oempkcrypto.lib")
#pragma comment(lib, "oemrc4.lib")
#pragma comment(lib, "oemrsabase.lib")
#pragma comment(lib, "oemrsaoaeppss.lib")
#pragma comment(lib, "oemrsaoaeppssimpl.lib")
#pragma comment(lib, "oemsha1.lib")
#pragma comment(lib, "oemsha256.lib")
#pragma comment(lib, "oemshahash.lib")
#pragma comment(lib, "oemshahmac.lib")

#pragma comment(lib, "wmdrmcert.lib")

#endif  // __DRM_LIBS_H__
