/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 20 11:24:20 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_SDS_CL_7_H__
#define BCHP_SDS_CL_7_H__

/***************************************************************************
 *SDS_CL_7 - SDS Carrier Loop Register Set 7
 ***************************************************************************/
#define BCHP_SDS_CL_7_CLCTL1                     0x000ea180 /* Carrier Loop Control 1 (Formerly, CLQCFD,CLPDCTL,CLCTL) */
#define BCHP_SDS_CL_7_CLCTL2                     0x000ea184 /* Carrier Loop Control 2 (Formerly, CLOON,CLSTS,CLMISC2,CLMISC) */
#define BCHP_SDS_CL_7_FLLC                       0x000ea188 /* Set 1 front carrier loop linear coefficient and scaling values */
#define BCHP_SDS_CL_7_FLLC1                      0x000ea18c /* Set 2 front carrier loop linear coefficient and scaling values */
#define BCHP_SDS_CL_7_FLIC                       0x000ea190 /* Set 1 front carrier loop integrator coefficient and scaling values */
#define BCHP_SDS_CL_7_FLIC1                      0x000ea194 /* Set 2 front carrier loop integrator coefficient and scaling values */
#define BCHP_SDS_CL_7_FLSW                       0x000ea198 /* Front carrier loop sweep rate */
#define BCHP_SDS_CL_7_FLI                        0x000ea19c /* Front carrier loop integrator value */
#define BCHP_SDS_CL_7_FLIF                       0x000ea1a0 /* Front carrier loop IF frequency control word */
#define BCHP_SDS_CL_7_FLPA                       0x000ea1a4 /* Front carrier loop phase accumulator value */
#define BCHP_SDS_CL_7_FLTD                       0x000ea1a8 /* Front carrier loop frequency detector threshold */
#define BCHP_SDS_CL_7_PEEST                      0x000ea1ac /* Back carrier loop phase error estimator output */
#define BCHP_SDS_CL_7_PLTD                       0x000ea1b0 /* Back carrier loop frequency detector threshold */
#define BCHP_SDS_CL_7_PLC                        0x000ea1b4 /* 1st set of back carrier loop linear and integrator coefficients and scaling values */
#define BCHP_SDS_CL_7_PLC1                       0x000ea1b8 /* 2nd set of back carrier loop linear and integrator coefficients and scaling values */
#define BCHP_SDS_CL_7_PLSW                       0x000ea1bc /* Back carrier loop sweep rate */
#define BCHP_SDS_CL_7_PLI                        0x000ea1c0 /* Back carrier loop integrator value */
#define BCHP_SDS_CL_7_PLPA                       0x000ea1c4 /* Back carrier loop phase accumulator value */
#define BCHP_SDS_CL_7_CRBFD                      0x000ea1c8 /* Carrier loop QAM/8PSK phase detector threshold */
#define BCHP_SDS_CL_7_CLHT                       0x000ea1cc /* Carrier loop lock high threshold value */
#define BCHP_SDS_CL_7_CLLT                       0x000ea1d0 /* Carrier loop lock low threshold value */
#define BCHP_SDS_CL_7_CLLA                       0x000ea1d4 /* Carrier loop lock accumulator value */
#define BCHP_SDS_CL_7_CLCT                       0x000ea1d8 /* Carrier loop lock control */
#define BCHP_SDS_CL_7_CLFFCTL                    0x000ea1dc /* Fine Frequency Mixer Control */
#define BCHP_SDS_CL_7_FFLPA                      0x000ea1e0 /* Fine frequency adjustment phase accumulator */
#define BCHP_SDS_CL_7_CLFBCTL                    0x000ea1e4 /* Forward Backward Loop Control (Formerly, CLFBCTL2,CLFBCTL) */
#define BCHP_SDS_CL_7_FBLC                       0x000ea1e8 /* Forward Backward Loop Filter Coefficient */
#define BCHP_SDS_CL_7_FBLI                       0x000ea1ec /* Forward Backward Loop Filter Integrator */
#define BCHP_SDS_CL_7_FBPA                       0x000ea1f0 /* Forward Backward Loop Phase Accumulator */
#define BCHP_SDS_CL_7_CLDAFECTL                  0x000ea1f4 /* DAFE Loop Control */
#define BCHP_SDS_CL_7_DAFELI                     0x000ea1f8 /* DAFE Loop Filter Integrator */
#define BCHP_SDS_CL_7_DAFEINT                    0x000ea1fc /* DAFE Loop Filter Integrator */

#endif /* #ifndef BCHP_SDS_CL_7_H__ */

/* End of File */
