/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Nov 17 17:31:36 2009
 *                 MD5 Checksum         c5a869a181cd53ce96d34b0e7ab357f3
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_VF_2_H__
#define BCHP_VF_2_H__

/***************************************************************************
 *VF_2 - Video Formatter VF_2
 ***************************************************************************/
#define BCHP_VF_2_VF_REV_ID                      0x007a4400 /* Revision ID register */
#define BCHP_VF_2_FORMAT_ADDER                   0x007a4408 /* Video formatter adder register */
#define BCHP_VF_2_MISC                           0x007a440c /* Miscellaneous register */
#define BCHP_VF_2_NEG_SYNC_VALUES                0x007a4410 /* Negative Sync and Blank amplitude register */
#define BCHP_VF_2_POS_SYNC_VALUES                0x007a4414 /* Positive Sync amplitude register */
#define BCHP_VF_2_SYNC_TRANS_0                   0x007a4418 /* Sync pulse transition 0 register */
#define BCHP_VF_2_SYNC_TRANS_1                   0x007a441c /* Sync pulse transition 1 register */
#define BCHP_VF_2_CH0_TAP1                       0x007a4420 /* Channel 0 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_2_CH0_TAP2                       0x007a4424 /* Channel 0 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_2_CH0_TAP3                       0x007a4428 /* Channel 0 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_2_CH0_TAP4                       0x007a442c /* Channel 0 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_2_CH0_TAP5                       0x007a4430 /* Channel 0 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_2_CH0_TAP6                       0x007a4434 /* Channel 0 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_2_CH0_TAP7                       0x007a4438 /* Channel 0 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_2_CH0_TAP8                       0x007a443c /* Channel 0 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_2_CH0_TAP9                       0x007a4440 /* Channel 0 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_2_CH0_TAP10                      0x007a4444 /* Channel 0 band-limiting filter (tap 10  ) */
#define BCHP_VF_2_CH1_TAP1                       0x007a4448 /* Channel 1 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_2_CH1_TAP2                       0x007a444c /* Channel 1 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_2_CH1_TAP3                       0x007a4450 /* Channel 1 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_2_CH1_TAP4                       0x007a4454 /* Channel 1 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_2_CH1_TAP5                       0x007a4458 /* Channel 1 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_2_CH1_TAP6                       0x007a445c /* Channel 1 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_2_CH1_TAP7                       0x007a4460 /* Channel 1 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_2_CH1_TAP8                       0x007a4464 /* Channel 1 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_2_CH1_TAP9                       0x007a4468 /* Channel 1 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_2_CH1_TAP10                      0x007a446c /* Channel 1 band-limiting filter (tap 10  ) */
#define BCHP_VF_2_CH2_TAP1                       0x007a4470 /* Channel 2 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_2_CH2_TAP2                       0x007a4474 /* Channel 2 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_2_CH2_TAP3                       0x007a4478 /* Channel 2 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_2_CH2_TAP4                       0x007a447c /* Channel 2 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_2_CH2_TAP5                       0x007a4480 /* Channel 2 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_2_CH2_TAP6                       0x007a4484 /* Channel 2 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_2_CH2_TAP7                       0x007a4488 /* Channel 2 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_2_CH2_TAP8                       0x007a448c /* Channel 2 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_2_CH2_TAP9                       0x007a4490 /* Channel 2 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_2_CH2_TAP10                      0x007a4494 /* Channel 2 band-limiting filter (tap 10  ) */
#define BCHP_VF_2_BVB_STATUS                     0x007a4498 /* VEC's BVB Status Register */
#define BCHP_VF_2_SHAPER                         0x007a449c /* VEC's Shaper Register */
#define BCHP_VF_2_HSYNC_AMP                      0x007a4500 /* VEC's Hsync Amplitude Register */
#define BCHP_VF_2_VIDEOBUS_SA_CONFIG             0x007a4504 /* VIDEO-BUS SA CONFIGURATION REGISTER */
#define BCHP_VF_2_VIDEOBUS_SA_CH0_STATUS         0x007a4508 /* VIDEO-BUS CHANNEL0 SA  STATUS REGISTER */
#define BCHP_VF_2_VIDEOBUS_SA_CH1_STATUS         0x007a450c /* VIDEO-BUS CHANNEL1 SA  STATUS REGISTER */
#define BCHP_VF_2_VIDEOBUS_SA_CH2_STATUS         0x007a4510 /* VIDEO-BUS CHANNEL2 SA  STATUS REGISTER */
#define BCHP_VF_2_CONTROLBUS_SA_CONFIG           0x007a4514 /* CONTROL-BUS SA CONFIGURATION REGISTER */
#define BCHP_VF_2_CONTROLBUS_SA_STATUS           0x007a4518 /* CONTROL-BUS SA STATUS REGISTER */
#define BCHP_VF_2_ENVELOPE_GENERATOR             0x007a451c /* ENVELOPE GENERATOR CONTROL REGISTER */
#define BCHP_VF_2_NEG_SYNC_AMPLITUDE_EXTN        0x007a4520 /* Negative Sync amplitude extension register */
#define BCHP_VF_2_POS_SYNC_AMPLITUDE_EXTN        0x007a4524 /* Positive Sync amplitude extension register */

#endif /* #ifndef BCHP_VF_2_H__ */

/* End of File */
