/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Nov 17 17:18:02 2009
 *                 MD5 Checksum         c5a869a181cd53ce96d34b0e7ab357f3
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef BCHP_SM_1_H__
#define BCHP_SM_1_H__

/***************************************************************************
 *SM_1 - Subcarrier Modulator SM_1
 ***************************************************************************/
#define BCHP_SM_1_SM_REV_ID                      0x007a4a00 /* REVISION ID REGISTER */
#define BCHP_SM_1_PG_CNTRL                       0x007a4a0c /* PHASE GENERATOR CONTROL REGISTER */
#define BCHP_SM_1_PG_CONFIG                      0x007a4a10 /* PHASE GENERATOR CONFIG REGISTER */
#define BCHP_SM_1_SC_FREQ_0                      0x007a4a14 /* SUBCARRIER FREQUENCY 0 */
#define BCHP_SM_1_COMP_CNTRL                     0x007a4a18 /* COMPOSITOR CONTROL REGISTER */
#define BCHP_SM_1_SA_CH2                         0x007a4a1c /* CHANNEL2 SA STATUS REGISTER */
#define BCHP_SM_1_SA_CH1                         0x007a4a20 /* CHANNEL1 SA STATUS REGISTER */
#define BCHP_SM_1_SA_CH0                         0x007a4a24 /* CHANNEL0 SA STATUS REGISTER */
#define BCHP_SM_1_SA_CONFIG                      0x007a4a28 /* SA CONFIGURATION REGISTER */
#define BCHP_SM_1_COMP_CONFIG                    0x007a4a2c /* COMPOSITOR CONFIG REGISTER */

#endif /* #ifndef BCHP_SM_1_H__ */

/* End of File */
