/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Mon Sep 23 09:50:33 2013
 *                 Full Compile MD5 Checksum fcccce298b546dd6a1f4cbad288478da
 *                   (minus title and desc)
 *                 MD5 Checksum              211556602e37a33262598b3d5eeba81c
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DMISC_H__
#define BCHP_DMISC_H__

/***************************************************************************
 *DMISC - BVN Deinterlace Control Registers
 ***************************************************************************/
#define BCHP_DMISC_SW_INIT                       0x00680000 /* BVN Deinterlace Soft Init */
#define BCHP_DMISC_BVND_CLOCK_CTRL               0x00680004 /* BVN Deinterlace clock control register */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS           0x00680008 /* BVN Deinterlace PDA Out Status */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS        0x0068000c /* BVN Deinterlace PDA Power Up Status */
#define BCHP_DMISC_SCRATCH_0                     0x0068001c /* Scratch Register */

/***************************************************************************
 *SW_INIT - BVN Deinterlace Soft Init
 ***************************************************************************/
/* DMISC :: SW_INIT :: reserved0 [31:06] */
#define BCHP_DMISC_SW_INIT_reserved0_MASK                          0xffffffc0
#define BCHP_DMISC_SW_INIT_reserved0_SHIFT                         6

/* DMISC :: SW_INIT :: MVP_5 [05:05] */
#define BCHP_DMISC_SW_INIT_MVP_5_MASK                              0x00000020
#define BCHP_DMISC_SW_INIT_MVP_5_SHIFT                             5
#define BCHP_DMISC_SW_INIT_MVP_5_DEFAULT                           0x00000000

/* DMISC :: SW_INIT :: MVP_4 [04:04] */
#define BCHP_DMISC_SW_INIT_MVP_4_MASK                              0x00000010
#define BCHP_DMISC_SW_INIT_MVP_4_SHIFT                             4
#define BCHP_DMISC_SW_INIT_MVP_4_DEFAULT                           0x00000000

/* DMISC :: SW_INIT :: MVP_3 [03:03] */
#define BCHP_DMISC_SW_INIT_MVP_3_MASK                              0x00000008
#define BCHP_DMISC_SW_INIT_MVP_3_SHIFT                             3
#define BCHP_DMISC_SW_INIT_MVP_3_DEFAULT                           0x00000000

/* DMISC :: SW_INIT :: MVP_2 [02:02] */
#define BCHP_DMISC_SW_INIT_MVP_2_MASK                              0x00000004
#define BCHP_DMISC_SW_INIT_MVP_2_SHIFT                             2
#define BCHP_DMISC_SW_INIT_MVP_2_DEFAULT                           0x00000000

/* DMISC :: SW_INIT :: MVP_1 [01:01] */
#define BCHP_DMISC_SW_INIT_MVP_1_MASK                              0x00000002
#define BCHP_DMISC_SW_INIT_MVP_1_SHIFT                             1
#define BCHP_DMISC_SW_INIT_MVP_1_DEFAULT                           0x00000000

/* DMISC :: SW_INIT :: MVP_0 [00:00] */
#define BCHP_DMISC_SW_INIT_MVP_0_MASK                              0x00000001
#define BCHP_DMISC_SW_INIT_MVP_0_SHIFT                             0
#define BCHP_DMISC_SW_INIT_MVP_0_DEFAULT                           0x00000000

/***************************************************************************
 *BVND_CLOCK_CTRL - BVN Deinterlace clock control register
 ***************************************************************************/
/* DMISC :: BVND_CLOCK_CTRL :: reserved0 [31:01] */
#define BCHP_DMISC_BVND_CLOCK_CTRL_reserved0_MASK                  0xfffffffe
#define BCHP_DMISC_BVND_CLOCK_CTRL_reserved0_SHIFT                 1

/* DMISC :: BVND_CLOCK_CTRL :: CLK_FREE_RUN_MODE [00:00] */
#define BCHP_DMISC_BVND_CLOCK_CTRL_CLK_FREE_RUN_MODE_MASK          0x00000001
#define BCHP_DMISC_BVND_CLOCK_CTRL_CLK_FREE_RUN_MODE_SHIFT         0
#define BCHP_DMISC_BVND_CLOCK_CTRL_CLK_FREE_RUN_MODE_DEFAULT       0x00000000

/***************************************************************************
 *BVND_PDA_OUT_STATUS - BVN Deinterlace PDA Out Status
 ***************************************************************************/
/* DMISC :: BVND_PDA_OUT_STATUS :: reserved0 [31:11] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_reserved0_MASK              0xfffff800
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_reserved0_SHIFT             11

/* DMISC :: BVND_PDA_OUT_STATUS :: MCVP_SIOB [10:10] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCVP_SIOB_MASK              0x00000400
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCVP_SIOB_SHIFT             10

/* DMISC :: BVND_PDA_OUT_STATUS :: MCTF [09:09] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCTF_MASK                   0x00000200
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCTF_SHIFT                  9

/* DMISC :: BVND_PDA_OUT_STATUS :: MCDI [08:08] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCDI_MASK                   0x00000100
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MCDI_SHIFT                  8

/* DMISC :: BVND_PDA_OUT_STATUS :: MADR_0 [07:07] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_0_MASK                 0x00000080
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_0_SHIFT                7

/* DMISC :: BVND_PDA_OUT_STATUS :: MADR_1 [06:06] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_1_MASK                 0x00000040
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_1_SHIFT                6

/* DMISC :: BVND_PDA_OUT_STATUS :: MADR_2 [05:05] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_2_MASK                 0x00000020
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_2_SHIFT                5

/* DMISC :: BVND_PDA_OUT_STATUS :: MADR_3 [04:04] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_3_MASK                 0x00000010
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_3_SHIFT                4

/* DMISC :: BVND_PDA_OUT_STATUS :: MADR_4 [03:03] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_4_MASK                 0x00000008
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_MADR_4_SHIFT                3

/* DMISC :: BVND_PDA_OUT_STATUS :: reserved1 [02:00] */
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_reserved1_MASK              0x00000007
#define BCHP_DMISC_BVND_PDA_OUT_STATUS_reserved1_SHIFT             0

/***************************************************************************
 *BVND_PDA_PWR_UP_STATUS - BVN Deinterlace PDA Power Up Status
 ***************************************************************************/
/* DMISC :: BVND_PDA_PWR_UP_STATUS :: reserved0 [31:11] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_reserved0_MASK           0xfffff800
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_reserved0_SHIFT          11

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MCVP_SIOB [10:10] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCVP_SIOB_MASK           0x00000400
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCVP_SIOB_SHIFT          10

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MCTF [09:09] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCTF_MASK                0x00000200
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCTF_SHIFT               9

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MCDI [08:08] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCDI_MASK                0x00000100
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MCDI_SHIFT               8

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MADR_0 [07:07] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_0_MASK              0x00000080
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_0_SHIFT             7

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MADR_1 [06:06] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_1_MASK              0x00000040
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_1_SHIFT             6

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MADR_2 [05:05] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_2_MASK              0x00000020
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_2_SHIFT             5

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MADR_3 [04:04] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_3_MASK              0x00000010
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_3_SHIFT             4

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: MADR_4 [03:03] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_4_MASK              0x00000008
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_MADR_4_SHIFT             3

/* DMISC :: BVND_PDA_PWR_UP_STATUS :: reserved1 [02:00] */
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_reserved1_MASK           0x00000007
#define BCHP_DMISC_BVND_PDA_PWR_UP_STATUS_reserved1_SHIFT          0

/***************************************************************************
 *SCRATCH_0 - Scratch Register
 ***************************************************************************/
/* DMISC :: SCRATCH_0 :: VALUE [31:00] */
#define BCHP_DMISC_SCRATCH_0_VALUE_MASK                            0xffffffff
#define BCHP_DMISC_SCRATCH_0_VALUE_SHIFT                           0
#define BCHP_DMISC_SCRATCH_0_VALUE_DEFAULT                         0x00000000

#endif /* #ifndef BCHP_DMISC_H__ */

/* End of File */
