/***************************************************************************
 * Copyright (C) 2017 Broadcom.  The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *
 * [File Description:]
 *
 ***************************************************************************/

#ifndef BVCE_CORE_H_
#define BVCE_CORE_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifndef BVCE_P_CORE_MAJOR
#error BVCE_P_CORE_MAJOR undefined
#endif
#ifndef BVCE_P_CORE_MINOR
#error BVCE_P_CORE_MINOR undefined
#endif
#ifndef BVCE_P_CORE_SUBMINOR
#error BVCE_P_CORE_SUBMINOR undefined
#endif
#ifndef BVCE_P_CORE_REVISION
#error BVCE_P_CORE_REVISION undefined
#endif

/* Core 0.1.8.2 */
#if ( ( BVCE_P_CORE_MAJOR == 0 ) && ( BVCE_P_CORE_MINOR == 1 ) && ( BVCE_P_CORE_SUBMINOR == 8 ) && ( BVCE_P_CORE_REVISION == 2 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 2
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 2
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 128

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V1_AND_V2_0
#endif

#define CORE_VERSION BVCE_FW_P_COREVERSION_V1
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 0

/* Core 1.1.1.1 */
#elif ( ( BVCE_P_CORE_MAJOR == 1 ) && ( BVCE_P_CORE_MINOR == 1 ) && ( BVCE_P_CORE_SUBMINOR == 1 ) && ( BVCE_P_CORE_REVISION == 1 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 2
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 2
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 128

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V1_AND_V2_0
#endif

#define CORE_VERSION BVCE_FW_P_COREVERSION_V1
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 0

/* Core 2.1.0.3 */
#elif ( ( BVCE_P_CORE_MAJOR == 2 ) && ( BVCE_P_CORE_MINOR == 1 ) && ( BVCE_P_CORE_SUBMINOR == 0 ) && ( BVCE_P_CORE_REVISION == 3 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 3
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 3
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 160

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V2_1
#endif

#define BVCE_PLATFORM_P_SUPPORT_MULTIPLE_SLICES 1

#define CORE_VERSION BVCE_FW_P_COREVERSION_V2_1_0_3
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 0

/* Core 2.1.2.2 */
#elif ( ( BVCE_P_CORE_MAJOR == 2 ) && ( BVCE_P_CORE_MINOR == 1 ) && ( BVCE_P_CORE_SUBMINOR == 2 ) && ( BVCE_P_CORE_REVISION == 2 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 2
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 2
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 160

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V2_1
#endif

#define BVCE_PLATFORM_P_SUPPORT_MULTIPLE_SLICES 1

#define CORE_VERSION BVCE_FW_P_COREVERSION_V2_1_2_2
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 0

/* Core 2.1.3.2 */
#elif ( ( BVCE_P_CORE_MAJOR == 2 ) && ( BVCE_P_CORE_MINOR == 1 ) && ( BVCE_P_CORE_SUBMINOR == 3 ) && ( BVCE_P_CORE_REVISION == 2 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 2
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 2
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 160

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V2_1
#endif

#define BVCE_PLATFORM_P_SUPPORT_MULTIPLE_SLICES 1

#define CORE_VERSION BVCE_FW_P_COREVERSION_V2_1_3_2
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 0

/* Core 3.0.1.2 */
#elif ( ( BVCE_P_CORE_MAJOR == 3 ) && ( BVCE_P_CORE_MINOR == 0 ) && ( BVCE_P_CORE_SUBMINOR == 1 ) && ( BVCE_P_CORE_REVISION == 2 ) )
#define BVCE_PLATFORM_P_NUM_ENCODE_CHANNELS 2
#define BVCE_PLATFORM_P_NUM_OUTPUT_CHANNELS 2
#define BVCE_PLATFORM_P_ITB_ALIGNMENT 160

#ifndef MIN_SECURE_BUFFER_SIZE_IN_BYTES
#define MIN_SECURE_BUFFER_SIZE_IN_BYTES MIN_SECURE_BUFFER_SIZE_IN_BYTES_FOR_VICE2_V2_1
#endif

#define BVCE_PLATFORM_P_SUPPORT_MULTIPLE_SLICES 1

#define CORE_VERSION BVCE_FW_P_COREVERSION_V3_0_1_2
#define BVCE_PLATFORM_P_SUPPORTS_GROUPAGE 1
#define BVCE_PLATFORM_P_SUPPORTS_64_BIT 1
#define BVCE_PLATFORM_P_SUPPORTS_ITB_NAL 1
#define BVCE_PLATFORM_P_SUPPORTS_ITB_EOS 1
#define BVCE_PLATFORM_P_DISABLE_FME_RR 1

#define BVCE_PLATFORM_P_MAX_B_PICTURES_PROGRESSIVE 7
#define BVCE_PLATFORM_P_MAX_B_PICTURES_INTERLACED 3
/* Core Unknown */
#else
#error Unrecognized core version
#endif

#if (BVCE_P_CORE_MAJOR < 3)
#define BVCE_P_CORE_FREQUENCY 351000000
#else
#define BVCE_P_CORE_FREQUENCY 432000000
#endif

#define BVCE_P_VIDEOCOMPRESSIONSTD_UNSUPPORTED 0xFFFFFFFF

typedef struct BVCE_P_SupportedProtocolEntry
{
   BAVC_VideoCompressionStd eProtocol;
   unsigned uiEncodingStd;
} BVCE_P_SupportedProtocolEntry;

extern const BVCE_P_SupportedProtocolEntry BVCE_P_SupportedProtocols[];

unsigned
BVCE_P_ProtocolLUT(
   BAVC_VideoCompressionStd eProtocol
   );

#ifdef __cplusplus
}
#endif

#endif /* BVCE_CORE_H_ */
/* End of File */
