/******************************************************************************
 * Copyright (C) 2017 Broadcom.  The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *****************************************************************************/

#include "bvce_platform.h"
const BVCE_Platform_P_Register s_astViceHardwareRegisters[]=
{
#if BDBG_DEBUG_BUILD
{ 0x00000000, BDBG_STRING("BCHP_VICE_CABAC_0_DEBUG"), BDBG_STRING("CABAC Debug"), false },
{ 0x00000010, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_BASE_PTR"), BDBG_STRING("CDB Buffer 0 Start Address"), true },
{ 0x00000018, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_END_PTR"), BDBG_STRING("CDB Buffer 0 End Address"), true },
{ 0x00000020, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_READ_PTR"), BDBG_STRING("CDB Buffer 0 Read Address"), true },
{ 0x00000028, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_WRITE_PTR"), BDBG_STRING("CDB Buffer 0 Write Address"), true },
{ 0x00000030, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_VALID_PTR"), BDBG_STRING("CDB Buffer 0 Valid Address"), true },
{ 0x00000038, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_BASE_PTR"), BDBG_STRING("ITB Buffer 0 Start Address"), true },
{ 0x00000040, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_END_PTR"), BDBG_STRING("ITB Buffer 0 End Address"), true },
{ 0x00000048, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_READ_PTR"), BDBG_STRING("ITB Buffer 0 Read Address"), true },
{ 0x00000050, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_WRITE_PTR"), BDBG_STRING("ITB Buffer 0 Write Address"), true },
{ 0x00000058, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_VALID_PTR"), BDBG_STRING("ITB Buffer 0 Valid Address"), true },
{ 0x00000060, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_BASE_PTR"), BDBG_STRING("CDB Buffer 1 Start Address"), true },
{ 0x00000068, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_END_PTR"), BDBG_STRING("CDB Buffer 1 End Address"), true },
{ 0x00000070, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_READ_PTR"), BDBG_STRING("CDB Buffer 1 Read Address"), true },
{ 0x00000078, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_WRITE_PTR"), BDBG_STRING("CDB Buffer 1 Write Address"), true },
{ 0x00000080, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_VALID_PTR"), BDBG_STRING("CDB Buffer 1 Valid Address"), true },
{ 0x00000088, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_BASE_PTR"), BDBG_STRING("ITB Buffer 1 Start Address"), true },
{ 0x00000090, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_END_PTR"), BDBG_STRING("ITB Buffer 1 End Address"), true },
{ 0x00000098, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_READ_PTR"), BDBG_STRING("ITB Buffer 1 Read Address"), true },
{ 0x000000a0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_WRITE_PTR"), BDBG_STRING("ITB Buffer 1 Write Address"), true },
{ 0x000000a8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_VALID_PTR"), BDBG_STRING("ITB Buffer 1 Valid Address"), true },
{ 0x000000b0, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_BASE_PTR"), BDBG_STRING("CDB Buffer 2 Start Address"), true },
{ 0x000000b8, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_END_PTR"), BDBG_STRING("CDB Buffer 2 End Address"), true },
{ 0x000000c0, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_READ_PTR"), BDBG_STRING("CDB Buffer 2 Read Address"), true },
{ 0x000000c8, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_WRITE_PTR"), BDBG_STRING("CDB Buffer 2 Write Address"), true },
{ 0x000000d0, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_VALID_PTR"), BDBG_STRING("CDB Buffer 2 Valid Address"), true },
{ 0x000000d8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_BASE_PTR"), BDBG_STRING("ITB Buffer 2 Start Address"), true },
{ 0x000000e0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_END_PTR"), BDBG_STRING("ITB Buffer 2 End Address"), true },
{ 0x000000e8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_READ_PTR"), BDBG_STRING("ITB Buffer 2 Read Address"), true },
{ 0x000000f0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_WRITE_PTR"), BDBG_STRING("ITB Buffer 2 Write Address"), true },
{ 0x000000f8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_VALID_PTR"), BDBG_STRING("ITB Buffer 2 Valid Address"), true },
{ 0x00000100, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_BASE_PTR"), BDBG_STRING("CDB Buffer 3 Start Address"), true },
{ 0x00000108, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_END_PTR"), BDBG_STRING("CDB Buffer 3 End Address"), true },
{ 0x00000110, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_READ_PTR"), BDBG_STRING("CDB Buffer 3 Read Address"), true },
{ 0x00000118, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_WRITE_PTR"), BDBG_STRING("CDB Buffer 3 Write Address"), true },
{ 0x00000120, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_VALID_PTR"), BDBG_STRING("CDB Buffer 3 Valid Address"), true },
{ 0x00000128, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_BASE_PTR"), BDBG_STRING("ITB Buffer 3 Start Address"), true },
{ 0x00000130, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_END_PTR"), BDBG_STRING("ITB Buffer 3 End Address"), true },
{ 0x00000138, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_READ_PTR"), BDBG_STRING("ITB Buffer 3 Read Address"), true },
{ 0x00000140, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_WRITE_PTR"), BDBG_STRING("ITB Buffer 3 Write Address"), true },
{ 0x00000148, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_VALID_PTR"), BDBG_STRING("ITB Buffer 3 Valid Address"), true },
{ 0x00000150, BDBG_STRING("BCHP_VICE_CABAC_0_SW_INIT_STR0"), BDBG_STRING("CABAC Stream 0 sw_init"), false },
{ 0x00000154, BDBG_STRING("BCHP_VICE_CABAC_0_SW_INIT_STR1"), BDBG_STRING("CABAC Stream 1 sw_init"), false },
{ 0x00000158, BDBG_STRING("BCHP_VICE_CABAC_0_SW_INIT_STR2"), BDBG_STRING("CABAC Stream 2 sw_init"), false },
{ 0x0000015c, BDBG_STRING("BCHP_VICE_CABAC_0_SW_INIT_STR3"), BDBG_STRING("CABAC Stream 3 sw_init"), false },
{ 0x00000160, BDBG_STRING("BCHP_VICE_CABAC_0_CDB0_FULL_WATERMARK"), BDBG_STRING("CDB0 Fullness watermark"), true },
{ 0x00000168, BDBG_STRING("BCHP_VICE_CABAC_0_CDB0_EMPTY_WATERMARK"), BDBG_STRING("CDB0 Emptiness watermark"), true },
{ 0x00000170, BDBG_STRING("BCHP_VICE_CABAC_0_CDB1_FULL_WATERMARK"), BDBG_STRING("CDB1 Fullness watermark"), true },
{ 0x00000178, BDBG_STRING("BCHP_VICE_CABAC_0_CDB1_EMPTY_WATERMARK"), BDBG_STRING("CDB1 Emptiness watermark"), true },
{ 0x00000180, BDBG_STRING("BCHP_VICE_CABAC_0_CDB2_FULL_WATERMARK"), BDBG_STRING("CDB2 Fullness watermark"), true },
{ 0x00000188, BDBG_STRING("BCHP_VICE_CABAC_0_CDB2_EMPTY_WATERMARK"), BDBG_STRING("CDB2 Emptiness watermark"), true },
{ 0x00000190, BDBG_STRING("BCHP_VICE_CABAC_0_CDB3_FULL_WATERMARK"), BDBG_STRING("CDB3 Fullness watermark"), true },
{ 0x00000198, BDBG_STRING("BCHP_VICE_CABAC_0_CDB3_EMPTY_WATERMARK"), BDBG_STRING("CDB3 Emptiness watermark"), true },
{ 0x000001a0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB0_FULL_WATERMARK"), BDBG_STRING("ITB0 Fullness watermark"), true },
{ 0x000001a8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB0_EMPTY_WATERMARK"), BDBG_STRING("ITB0 Emptiness watermark"), true },
{ 0x000001b0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB1_FULL_WATERMARK"), BDBG_STRING("ITB1 Fullness watermark"), true },
{ 0x000001b8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB1_EMPTY_WATERMARK"), BDBG_STRING("ITB1 Emptiness watermark"), true },
{ 0x000001c0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB2_FULL_WATERMARK"), BDBG_STRING("ITB2 Fullness watermark"), true },
{ 0x000001c8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB2_EMPTY_WATERMARK"), BDBG_STRING("ITB2 Emptiness watermark"), true },
{ 0x000001d0, BDBG_STRING("BCHP_VICE_CABAC_0_ITB3_FULL_WATERMARK"), BDBG_STRING("ITB3 Fullness watermark"), true },
{ 0x000001d8, BDBG_STRING("BCHP_VICE_CABAC_0_ITB3_EMPTY_WATERMARK"), BDBG_STRING("ITB3 Emptiness watermark"), true },
{ 0x000001e0, BDBG_STRING("BCHP_VICE_CABAC_0_CDB0_CRC_INIT_OPTION"), BDBG_STRING("CDB0 CRC initialization option"), false },
{ 0x000001e4, BDBG_STRING("BCHP_VICE_CABAC_0_CDB0_CRC_INIT_VALUE"), BDBG_STRING("CDB0 CRC initialization value"), false },
{ 0x000001e8, BDBG_STRING("BCHP_VICE_CABAC_0_CDB1_CRC_INIT_OPTION"), BDBG_STRING("CDB1 CRC initialization option"), false },
{ 0x000001ec, BDBG_STRING("BCHP_VICE_CABAC_0_CDB1_CRC_INIT_VALUE"), BDBG_STRING("CDB1 CRC initialization value"), false },
{ 0x000001f0, BDBG_STRING("BCHP_VICE_CABAC_0_CDB2_CRC_INIT_OPTION"), BDBG_STRING("CDB2 CRC initialization option"), false },
{ 0x000001f4, BDBG_STRING("BCHP_VICE_CABAC_0_CDB2_CRC_INIT_VALUE"), BDBG_STRING("CDB2 CRC initialization value"), false },
{ 0x000001f8, BDBG_STRING("BCHP_VICE_CABAC_0_CDB3_CRC_INIT_OPTION"), BDBG_STRING("CDB3 CRC initialization option"), false },
{ 0x000001fc, BDBG_STRING("BCHP_VICE_CABAC_0_CDB3_CRC_INIT_VALUE"), BDBG_STRING("CDB3 CRC initialization value"), false },
{ 0x00000200, BDBG_STRING("BCHP_VICE_CABAC_0_CTRL"), BDBG_STRING("CABAC Control Register"), false },
{ 0x00000204, BDBG_STRING("BCHP_VICE_CABAC_0_SCRATCH"), BDBG_STRING("CABAC Scratch"), false },
{ 0x00000208, BDBG_STRING("BCHP_VICE_CABAC_0_ERR_STATUS_ENABLE"), BDBG_STRING("CABAC error status enable"), false },
{ 0x0000020c, BDBG_STRING("BCHP_VICE_CABAC_0_ERR_STATUS_CLEAR"), BDBG_STRING("CABAC error status clear"), false },
{ 0x00000210, BDBG_STRING("BCHP_VICE_CABAC_0_PROG_WATCHDOG"), BDBG_STRING("Programmable Watchdog value"), false },
{ 0x00000214, BDBG_STRING("BCHP_VICE_CABAC_0_ERR_STATUS"), BDBG_STRING("CABAC error status"), false },
{ 0x00000218, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX0_DEPTH"), BDBG_STRING("CDB Buffer 0 Fullness"), true },
{ 0x00000220, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX0_DEPTH"), BDBG_STRING("ITB Buffer 0 Fullness"), true },
{ 0x00000228, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX1_DEPTH"), BDBG_STRING("CDB Buffer 1 Fullness"), true },
{ 0x00000230, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX1_DEPTH"), BDBG_STRING("ITB Buffer 1 Fullness"), true },
{ 0x00000238, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX2_DEPTH"), BDBG_STRING("CDB Buffer 2 Fullness"), true },
{ 0x00000240, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX2_DEPTH"), BDBG_STRING("ITB Buffer 2 Fullness"), true },
{ 0x00000248, BDBG_STRING("BCHP_VICE_CABAC_0_CDB_CTX3_DEPTH"), BDBG_STRING("CDB Buffer 3 Fullness"), true },
{ 0x00000250, BDBG_STRING("BCHP_VICE_CABAC_0_ITB_CTX3_DEPTH"), BDBG_STRING("ITB Buffer 3 Fullness"), true },
{ 0x00000258, BDBG_STRING("BCHP_VICE_CABAC_0_CDB0_CRC_REM_VALUE"), BDBG_STRING("CDB0 CRC Remainder value"), false },
{ 0x0000025c, BDBG_STRING("BCHP_VICE_CABAC_0_CDB1_CRC_REM_VALUE"), BDBG_STRING("CDB1 CRC Remainder value"), false },
{ 0x00000260, BDBG_STRING("BCHP_VICE_CABAC_0_CDB2_CRC_REM_VALUE"), BDBG_STRING("CDB2 CRC Remainder value"), false },
{ 0x00000264, BDBG_STRING("BCHP_VICE_CABAC_0_CDB3_CRC_REM_VALUE"), BDBG_STRING("CDB3 CRC Remainder value"), false },
{ 0x00000268, BDBG_STRING("BCHP_VICE_CABAC_0_STATUS"), BDBG_STRING("CABAC Status"), false },
{ 0x0000026c, BDBG_STRING("BCHP_VICE_CABAC_0_ENC_ERR_INFO"), BDBG_STRING("CABAC encoder error info"), false },
{ 0x00000270, BDBG_STRING("BCHP_VICE_CABAC_0_STR0_ACTIVE"), BDBG_STRING("CABAC Stream 0 active"), false },
{ 0x00000274, BDBG_STRING("BCHP_VICE_CABAC_0_STR1_ACTIVE"), BDBG_STRING("CABAC Stream 1 active"), false },
{ 0x00000278, BDBG_STRING("BCHP_VICE_CABAC_0_STR2_ACTIVE"), BDBG_STRING("CABAC Stream 2 active"), false },
{ 0x0000027c, BDBG_STRING("BCHP_VICE_CABAC_0_STR3_ACTIVE"), BDBG_STRING("CABAC Stream 3 active"), false },
{ 0x00000280, BDBG_STRING("BCHP_VICE_CABAC_0_DEBUG_0"), BDBG_STRING("CABAC Debug 0 register"), false },
{ 0x00000284, BDBG_STRING("BCHP_VICE_CABAC_0_DEBUG_1"), BDBG_STRING("CABAC Debug 1 register"), false },
{ 0x00000288, BDBG_STRING("BCHP_VICE_CABAC_0_DEBUG_2"), BDBG_STRING("CABAC Debug 2 register"), false },
{ 0x0000028c, BDBG_STRING("BCHP_VICE_CABAC_0_DEBUG_3"), BDBG_STRING("CABAC Debug 3 register"), false },
{ 0x00000290, BDBG_STRING("BCHP_VICE_CABAC_0_CABAC_PIC_COUNTER"), BDBG_STRING("CABAC total picture counter"), false },
{ 0x00000298, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX0_BASE_PTR"), BDBG_STRING("PROB Buffer 0 Start Address"), true },
{ 0x000002a0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX0_WRITE_PTR"), BDBG_STRING("PROB Buffer 0 Write Address"), true },
{ 0x000002a8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX0_READ_PTR"), BDBG_STRING("PROB Buffer 0 Read Address"), true },
{ 0x000002b0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX0_WRITE_DONE"), BDBG_STRING("PROB Buffer 0 Write Done"), false },
{ 0x000002b4, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX0_READ_DONE"), BDBG_STRING("PROB Buffer 0 Read Done"), false },
{ 0x000002b8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX1_BASE_PTR"), BDBG_STRING("PROB Buffer 1 Start Address"), true },
{ 0x000002c0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX1_WRITE_PTR"), BDBG_STRING("PROB Buffer 1 Write Address"), true },
{ 0x000002c8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX1_READ_PTR"), BDBG_STRING("PROB Buffer 1 Read Address"), true },
{ 0x000002d0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX1_WRITE_DONE"), BDBG_STRING("PROB Buffer 1 Write Done"), false },
{ 0x000002d4, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX1_READ_DONE"), BDBG_STRING("PROB Buffer 1 Read Done"), false },
{ 0x000002d8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX2_BASE_PTR"), BDBG_STRING("PROB Buffer 2 Start Address"), true },
{ 0x000002e0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX2_WRITE_PTR"), BDBG_STRING("PROB Buffer 2 Write Address"), true },
{ 0x000002e8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX2_READ_PTR"), BDBG_STRING("PROB Buffer 2 Read Address"), true },
{ 0x000002f0, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX2_WRITE_DONE"), BDBG_STRING("PROB Buffer 2 Write Done"), false },
{ 0x000002f4, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX2_READ_DONE"), BDBG_STRING("PROB Buffer 2 Read Done"), false },
{ 0x000002f8, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX3_BASE_PTR"), BDBG_STRING("PROB Buffer 3 Start Address"), true },
{ 0x00000300, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX3_WRITE_PTR"), BDBG_STRING("PROB Buffer 3 Write Address"), true },
{ 0x00000308, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX3_READ_PTR"), BDBG_STRING("PROB Buffer 3 Read Address"), true },
{ 0x00000310, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX3_WRITE_DONE"), BDBG_STRING("PROB Buffer 3 Write Done"), false },
{ 0x00000314, BDBG_STRING("BCHP_VICE_CABAC_0_PROB_CTX3_READ_DONE"), BDBG_STRING("PROB Buffer 3 Write Done"), false },
{ 0x00000400, BDBG_STRING("BCHP_VICE_CME_0_FW_CONTROL"), BDBG_STRING("CME Firmware Control"), false },
{ 0x00000404, BDBG_STRING("BCHP_VICE_CME_0_TOP_CONFIG"), BDBG_STRING("CME Top Configuration"), false },
{ 0x00000408, BDBG_STRING("BCHP_VICE_CME_0_SEARCH_CONFIG"), BDBG_STRING("CME Search Control"), false },
{ 0x0000040c, BDBG_STRING("BCHP_VICE_CME_0_REFINEMENT_SEARCH_CONFIG"), BDBG_STRING("CME Refinement Search Control"), false },
{ 0x00000410, BDBG_STRING("BCHP_VICE_CME_0_COST_BIAS"), BDBG_STRING("CME Bias for Motion Partition Decision"), false },
{ 0x00000414, BDBG_STRING("BCHP_VICE_CME_0_LOW_LATENCY_CONFIG"), BDBG_STRING("CME Low Latency Control"), false },
{ 0x00000418, BDBG_STRING("BCHP_VICE_CME_0_PICTURE_SIZE"), BDBG_STRING("Current and Reference Picture Size in 8x8"), false },
{ 0x0000041c, BDBG_STRING("BCHP_VICE_CME_0_SLICE_HEIGHT"), BDBG_STRING("Current and Reference Slice Height in MB Rows"), false },
{ 0x00000420, BDBG_STRING("BCHP_VICE_CME_0_DRAM_MAPPING"), BDBG_STRING("DRAM image mapping"), false },
{ 0x00000424, BDBG_STRING("BCHP_VICE_CME_0_CSC_PITCH"), BDBG_STRING("CSC Memory Pitch Size"), false },
{ 0x00000428, BDBG_STRING("BCHP_VICE_CME_0_DCDV_CONFIG"), BDBG_STRING("DCDV Configuration"), false },
{ 0x0000042c, BDBG_STRING("BCHP_VICE_CME_0_PIC_COUNTER"), BDBG_STRING("CME Picture Counter"), false },
{ 0x00000430, BDBG_STRING("BCHP_VICE_CME_0_CUR_MSTART"), BDBG_STRING("Current Picture Memory Start address in 40 bit"), true },
{ 0x00000438, BDBG_STRING("BCHP_VICE_CME_0_REF0_MSTART"), BDBG_STRING("Reference Picture 0 Memory Start address in 40 bit"), true },
{ 0x00000440, BDBG_STRING("BCHP_VICE_CME_0_REF0_MSTART_CSC"), BDBG_STRING("Reference Picture 0 CSC Memory Start address in 40 bit"), true },
{ 0x00000448, BDBG_STRING("BCHP_VICE_CME_0_REF1_MSTART"), BDBG_STRING("Reference Picture 1 Memory Start address in 40 bit"), true },
{ 0x00000450, BDBG_STRING("BCHP_VICE_CME_0_REF1_MSTART_CSC"), BDBG_STRING("Reference Picture 1 CSC Memory Start address in 40 bit"), true },
{ 0x00000458, BDBG_STRING("BCHP_VICE_CME_0_REF2_MSTART"), BDBG_STRING("Reference Picture 2 Memory Start address in 40 bit"), true },
{ 0x00000460, BDBG_STRING("BCHP_VICE_CME_0_REF2_MSTART_CSC"), BDBG_STRING("Reference Picture 2 CSC Memory Start address in 40 bit"), true },
{ 0x00000468, BDBG_STRING("BCHP_VICE_CME_0_REF3_MSTART"), BDBG_STRING("Reference Picture 3 Memory Start address in 40 bit"), true },
{ 0x00000470, BDBG_STRING("BCHP_VICE_CME_0_REF3_MSTART_CSC"), BDBG_STRING("Reference Picture 3 CSC Memory Start address in 40 bit"), true },
{ 0x00000478, BDBG_STRING("BCHP_VICE_CME_0_REF0_PIC_SAD"), BDBG_STRING("Reference Picture 0 Accumulated SAD Value"), false },
{ 0x0000047c, BDBG_STRING("BCHP_VICE_CME_0_REF1_PIC_SAD"), BDBG_STRING("Reference Picture 1 Accumulated SAD Value"), false },
{ 0x00000480, BDBG_STRING("BCHP_VICE_CME_0_REF2_PIC_SAD"), BDBG_STRING("Reference Picture 2 Accumulated SAD Value"), false },
{ 0x00000484, BDBG_STRING("BCHP_VICE_CME_0_REF3_PIC_SAD"), BDBG_STRING("Reference Picture 3 Accumulated SAD Value"), false },
{ 0x00000488, BDBG_STRING("BCHP_VICE_CME_0_SHADOW_REG_STATE"), BDBG_STRING("CME Shadow Registers State"), false },
{ 0x0000048c, BDBG_STRING("BCHP_VICE_CME_0_STATUS"), BDBG_STRING("CME core status."), false },
{ 0x00000490, BDBG_STRING("BCHP_VICE_CME_0_DEBUG_STATUS"), BDBG_STRING("Internal Status for Debugging in CME."), false },
{ 0x00000494, BDBG_STRING("BCHP_VICE_CME_0_PICTURE_INDEX"), BDBG_STRING("Index of Latest Completed Picture in CME."), false },
{ 0x00000498, BDBG_STRING("BCHP_VICE_CME_0_PIC_INFO"), BDBG_STRING("Stream information from ARC"), false },
{ 0x0000049c, BDBG_STRING("BCHP_VICE_CME_0_DCDV_HOR_INFO"), BDBG_STRING("Internal DCDV Horizontal Status for Debugging in CME."), false },
{ 0x000004a0, BDBG_STRING("BCHP_VICE_CME_0_DCDV_VERT_INFO"), BDBG_STRING("Internal DCDV Vertical Status for Debugging in CME."), false },
{ 0x000004a4, BDBG_STRING("BCHP_VICE_CME_0_DEBUG_STATUS_1"), BDBG_STRING("Internal Status for Debugging in CME."), false },
{ 0x000004a8, BDBG_STRING("BCHP_VICE_CME_0_DEBUG_STATUS_2"), BDBG_STRING("Internal Status for Debugging in CME."), false },
{ 0x000004ac, BDBG_STRING("BCHP_VICE_CME_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00000800, BDBG_STRING("BCHP_VICE_ILF_0_FW_CONTROL"), BDBG_STRING("ILF Write Action control"), false },
{ 0x00000804, BDBG_STRING("BCHP_VICE_ILF_0_CONFIG"), BDBG_STRING("ILF config"), false },
{ 0x00000808, BDBG_STRING("BCHP_VICE_ILF_0_PICTURE_SIZE"), BDBG_STRING("Current picture size"), false },
{ 0x0000080c, BDBG_STRING("BCHP_VICE_ILF_0_DBLK_FILTEROFFSET"), BDBG_STRING("AVC/HEVC DBLK Filter Offset"), false },
{ 0x00000810, BDBG_STRING("BCHP_VICE_ILF_0_LUMA_BUF_BASE"), BDBG_STRING("ILF Luma Buffer Base Address"), true },
{ 0x00000818, BDBG_STRING("BCHP_VICE_ILF_0_CHROMA_BUF_BASE"), BDBG_STRING("ILF Chroma Buffer Base Address"), true },
{ 0x00000820, BDBG_STRING("BCHP_VICE_ILF_0_LUMA_BUF_NMBY"), BDBG_STRING("ILF Luma Buffer DRAM Mapping"), false },
{ 0x00000824, BDBG_STRING("BCHP_VICE_ILF_0_CHROMA_BUF_NMBY"), BDBG_STRING("ILF Chroma Buffer DRAM Mapping"), false },
{ 0x00000828, BDBG_STRING("BCHP_VICE_ILF_0_CRC_SEED"), BDBG_STRING("ILF CRC SEED register"), false },
{ 0x0000082c, BDBG_STRING("BCHP_VICE_ILF_0_DEBUG_DBLK"), BDBG_STRING("DBLK FILTER DEBUG register"), false },
{ 0x00000830, BDBG_STRING("BCHP_VICE_ILF_0_SCRATCH"), BDBG_STRING("ILF scratch register"), false },
{ 0x00000834, BDBG_STRING("BCHP_VICE_ILF_0_ERR_ENABLE"), BDBG_STRING("ILF Error Status Enable register"), false },
{ 0x00000838, BDBG_STRING("BCHP_VICE_ILF_0_ERR_CLEAR"), BDBG_STRING("ILF Error Status Clear register"), false },
{ 0x000008b0, BDBG_STRING("BCHP_VICE_ILF_0_REF_ADJ_TABLE"), BDBG_STRING("VP9 Reference Adjust Block Filter Level"), false },
{ 0x000008b4, BDBG_STRING("BCHP_VICE_ILF_0_MODE_ADJ_TABLE"), BDBG_STRING("VP9 Mode Adjust Block Filter Level"), false },
{ 0x000008b8, BDBG_STRING("BCHP_VICE_ILF_0_VP9_CONFIG"), BDBG_STRING("VP9 Configuration Registers"), false },
{ 0x00000900, BDBG_STRING("BCHP_VICE_ILF_0_STATUS"), BDBG_STRING("ILF status"), false },
{ 0x00000904, BDBG_STRING("BCHP_VICE_ILF_0_CRC_CHKSUM_Y"), BDBG_STRING("ILF Luma CRC/Checksum result register"), false },
{ 0x00000908, BDBG_STRING("BCHP_VICE_ILF_0_CRC_CHKSUM_CB"), BDBG_STRING("ILF Chroma (Cb) CRC/Checksum result register"), false },
{ 0x0000090c, BDBG_STRING("BCHP_VICE_ILF_0_CRC_CHKSUM_CR"), BDBG_STRING("ILF Chroma (Cr) CRC/Checksum result register"), false },
{ 0x00000910, BDBG_STRING("BCHP_VICE_ILF_0_DBG_STATUS0"), BDBG_STRING("ILF Status Register0 for debugging purpose"), false },
{ 0x00000914, BDBG_STRING("BCHP_VICE_ILF_0_DBG_STATUS1"), BDBG_STRING("ILF Status Register1 for debugging purpose"), false },
{ 0x00000918, BDBG_STRING("BCHP_VICE_ILF_0_DBG_STATUS2"), BDBG_STRING("ILF Status Register2 for debugging purpose"), false },
{ 0x0000091c, BDBG_STRING("BCHP_VICE_ILF_0_DINO_XQ_DEBUG"), BDBG_STRING("ILF DINO XQ debug register"), false },
{ 0x00000920, BDBG_STRING("BCHP_VICE_ILF_0_DINO_CABAC_DEBUG"), BDBG_STRING("ILF DINO CABAC debug register"), false },
{ 0x00000924, BDBG_STRING("BCHP_VICE_ILF_0_ERR_STATUS"), BDBG_STRING("ILF Error Status register"), false },
{ 0x00001000, BDBG_STRING("BCHP_VICE_FME_0_FW_CONTROL"), BDBG_STRING("FME FW control"), false },
{ 0x00001004, BDBG_STRING("BCHP_VICE_FME_0_CONFIG"), BDBG_STRING("FME configuration"), false },
{ 0x00001008, BDBG_STRING("BCHP_VICE_FME_0_PICTURE_SIZE"), BDBG_STRING("Current and reference picture size"), false },
{ 0x0000100c, BDBG_STRING("BCHP_VICE_FME_0_PICTURE_COUNTER"), BDBG_STRING("Current picture counter for low latency mode"), false },
{ 0x00001010, BDBG_STRING("BCHP_VICE_FME_0_REF_CONFIG"), BDBG_STRING("FME reference picture configuration"), false },
{ 0x00001014, BDBG_STRING("BCHP_VICE_FME_0_CSC_CONFIG"), BDBG_STRING("FME CSC configuration"), false },
{ 0x00001018, BDBG_STRING("BCHP_VICE_FME_0_PRG_CONFIG"), BDBG_STRING("FME Patch request configuration"), false },
{ 0x0000101c, BDBG_STRING("BCHP_VICE_FME_0_TMVP_CONFIG"), BDBG_STRING("FME TMVP configuration"), false },
{ 0x00001020, BDBG_STRING("BCHP_VICE_FME_0_TMVP_PITCH"), BDBG_STRING("FME TMVP Pitch"), false },
{ 0x00001024, BDBG_STRING("BCHP_VICE_FME_0_OFI_CONFIG"), BDBG_STRING("FME OFI configuration"), false },
{ 0x00001028, BDBG_STRING("BCHP_VICE_FME_0_FORCE_INTRA_CTRL"), BDBG_STRING("Force Intra Control"), false },
{ 0x00001030, BDBG_STRING("BCHP_VICE_FME_0_CSC_REF0_BASE"), BDBG_STRING("DRAM 40-bit starting address for reference picture 0 CSC data"), true },
{ 0x00001038, BDBG_STRING("BCHP_VICE_FME_0_CSC_REF1_BASE"), BDBG_STRING("DRAM 40-bit starting address for reference picture 1 CSC data"), true },
{ 0x00001040, BDBG_STRING("BCHP_VICE_FME_0_TMVP_READ_BASE"), BDBG_STRING("DRAM 40-bit starting address for reading TMVP data."), true },
{ 0x00001048, BDBG_STRING("BCHP_VICE_FME_0_TMVP_WRITE_BASE"), BDBG_STRING("DRAM 40-bit starting address for writing TMVP data."), true },
{ 0x00001050, BDBG_STRING("BCHP_VICE_FME_0_CU_HEADER"), BDBG_STRING("CU Header for the Merge/Skip mode of the Merge RDO."), false },
{ 0x00001054, BDBG_STRING("BCHP_VICE_FME_0_BIN_BIAS"), BDBG_STRING("Skip and Inter bin bias for inter mode decision or inter vs. intra mode decision."), false },
{ 0x00001058, BDBG_STRING("BCHP_VICE_FME_0_MV_COST_OVERHEAD_BIN"), BDBG_STRING("CU/Partition based overhead bins for FMV MV cost evaluation"), false },
{ 0x0000105c, BDBG_STRING("BCHP_VICE_FME_0_RDO_QUANT_OFFSET"), BDBG_STRING("Quantization offset for FME RDO."), false },
{ 0x00001060, BDBG_STRING("BCHP_VICE_FME_0_RANDOM_TEST_MODE"), BDBG_STRING("Random test mode control"), false },
{ 0x00001064, BDBG_STRING("BCHP_VICE_FME_0_RANDOM_TEST_SEED"), BDBG_STRING("Random test random number generator seed"), false },
{ 0x00001068, BDBG_STRING("BCHP_VICE_FME_0_RANDOM_TEST_MV_BITS"), BDBG_STRING("Random test number of bits for motion vector"), false },
{ 0x0000106c, BDBG_STRING("BCHP_VICE_FME_0_RANDOM_TEST_CU_COST_BITS"), BDBG_STRING("Random test number of bits for CU cost"), false },
{ 0x00001070, BDBG_STRING("BCHP_VICE_FME_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00001074, BDBG_STRING("BCHP_VICE_FME_0_FME_DEBUG_SEL"), BDBG_STRING("FME debug information select register"), false },
{ 0x00001078, BDBG_STRING("BCHP_VICE_FME_0_ERR_STATUS_ENABLE"), BDBG_STRING("FME error status enable register"), false },
{ 0x00001080, BDBG_STRING("BCHP_VICE_FME_0_ERR_STATUS_CLR"), BDBG_STRING("FME error status clear register"), false },
{ 0x00001084, BDBG_STRING("BCHP_VICE_FME_0_REG_STATUS"), BDBG_STRING("FME shadow register status"), false },
{ 0x00001088, BDBG_STRING("BCHP_VICE_FME_0_STATUS"), BDBG_STRING("FME core status"), false },
{ 0x0000108c, BDBG_STRING("BCHP_VICE_FME_0_DINO_DEBUG_MC"), BDBG_STRING("DINO debug register (FME to MC)"), false },
{ 0x00001090, BDBG_STRING("BCHP_VICE_FME_0_DINO_DEBUG_IMD"), BDBG_STRING("DINO debug register (IMD to FME)"), false },
{ 0x00001094, BDBG_STRING("BCHP_VICE_FME_0_DEBUG_INFO_0"), BDBG_STRING("FME debug information data register 0"), false },
{ 0x00001098, BDBG_STRING("BCHP_VICE_FME_0_DEBUG_INFO_1"), BDBG_STRING("FME debug information data register 1"), false },
{ 0x0000109c, BDBG_STRING("BCHP_VICE_FME_0_DEBUG_INFO_2"), BDBG_STRING("FME debug information data register 2"), false },
{ 0x000010a0, BDBG_STRING("BCHP_VICE_FME_0_DEBUG_INFO_3"), BDBG_STRING("FME debug information data register 3"), false },
{ 0x000010ac, BDBG_STRING("BCHP_VICE_FME_0_ERR_STATUS"), BDBG_STRING("FME error status register"), false },
{ 0x00001800, BDBG_STRING("BCHP_VICE_IMD_0_FW_CONTROL"), BDBG_STRING("IMD FW control"), false },
{ 0x00001804, BDBG_STRING("BCHP_VICE_IMD_0_TOP_CONTROL"), BDBG_STRING("IMD control"), false },
{ 0x00001808, BDBG_STRING("BCHP_VICE_IMD_0_PIC_SIZE"), BDBG_STRING("Current and reference picture size"), false },
{ 0x0000180c, BDBG_STRING("BCHP_VICE_IMD_0_SLICE_CONFIG"), BDBG_STRING("Slice configure"), false },
{ 0x00001810, BDBG_STRING("BCHP_VICE_IMD_0_LUMA_ADDR_TOP_FRAME"), BDBG_STRING("DRAM 40-bit starting address for current picture Luma data (top field or frame)"), true },
{ 0x00001818, BDBG_STRING("BCHP_VICE_IMD_0_LUMA_ADDR_BOTTOM"), BDBG_STRING("DRAM 40-bit starting address for current picture Luma data (bottom field)"), true },
{ 0x00001820, BDBG_STRING("BCHP_VICE_IMD_0_CHROMA_ADDR"), BDBG_STRING("DRAM lower 40-bit starting address for current picture Chroma data"), true },
{ 0x00001828, BDBG_STRING("BCHP_VICE_IMD_0_DRAM_MAPPING"), BDBG_STRING("DRAM image mapping"), false },
{ 0x0000182c, BDBG_STRING("BCHP_VICE_IMD_0_DCXV_CONFIGURE"), BDBG_STRING("DCXV Configuration"), false },
{ 0x00001830, BDBG_STRING("BCHP_VICE_IMD_0_AVC_INTRA_CONFIGURE_0"), BDBG_STRING("AVC Intra prediction configuration 0"), false },
{ 0x00001834, BDBG_STRING("BCHP_VICE_IMD_0_AVC_INTRA_CONFIGURE_1"), BDBG_STRING("AVC Intra prediction configuration 1"), false },
{ 0x00001838, BDBG_STRING("BCHP_VICE_IMD_0_QP_CONFIGURE"), BDBG_STRING("Picture level QP Configuration for SATD and RDO cost calculation"), false },
{ 0x0000183c, BDBG_STRING("BCHP_VICE_IMD_0_MODE_BIT"), BDBG_STRING("Mode bit configuration for luma/chroma blocks"), false },
{ 0x00001840, BDBG_STRING("BCHP_VICE_IMD_0_HEADER_BIT"), BDBG_STRING("Header bit configuration"), false },
{ 0x00001844, BDBG_STRING("BCHP_VICE_IMD_0_RDO_CONFIGURE"), BDBG_STRING("RDO Configuration"), false },
{ 0x00001848, BDBG_STRING("BCHP_VICE_IMD_0_CHANNEL_ID"), BDBG_STRING("Channel ID for current picture"), false },
{ 0x00001854, BDBG_STRING("BCHP_VICE_IMD_0_STATUS"), BDBG_STRING("IMD status"), false },
{ 0x00001858, BDBG_STRING("BCHP_VICE_IMD_0_ERR_ENABLE"), BDBG_STRING("IMD error enable"), false },
{ 0x0000185c, BDBG_STRING("BCHP_VICE_IMD_0_ERR_STATUS_CLR"), BDBG_STRING("IMD status clear"), false },
{ 0x00001860, BDBG_STRING("BCHP_VICE_IMD_0_ERR_STATUS"), BDBG_STRING("IMD status"), false },
{ 0x00001864, BDBG_STRING("BCHP_VICE_IMD_0_DINO_DEBUG_FME"), BDBG_STRING("DINO debug register (IMD to FME)"), false },
{ 0x00001868, BDBG_STRING("BCHP_VICE_IMD_0_DINO_DEBUG_MC"), BDBG_STRING("DINO debug register (IMD to MC)"), false },
{ 0x0000186c, BDBG_STRING("BCHP_VICE_IMD_0_DINO_DEBUG_XQ"), BDBG_STRING("DINO debug register (IMD from XQ)"), false },
{ 0x00001870, BDBG_STRING("BCHP_VICE_IMD_0_DINO_DEBUG_ARC"), BDBG_STRING("DINO debug register (IMD from ARC)"), false },
{ 0x00001874, BDBG_STRING("BCHP_VICE_IMD_0_DCDV_INFO"), BDBG_STRING("DCDV information data register"), false },
{ 0x00001878, BDBG_STRING("BCHP_VICE_IMD_0_DEBUG_SEL"), BDBG_STRING("IMD debug information select register"), false },
{ 0x0000187c, BDBG_STRING("BCHP_VICE_IMD_0_DEBUG_INFO"), BDBG_STRING("IMD debug information data register"), false },
{ 0x000019fc, BDBG_STRING("BCHP_VICE_IMD_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00001c00, BDBG_STRING("BCHP_VICE_MAU_0_FW_CONTROL"), BDBG_STRING("MAU FW control"), false },
{ 0x00001c04, BDBG_STRING("BCHP_VICE_MAU_0_CONFIG"), BDBG_STRING("MAU configuration"), false },
{ 0x00001c08, BDBG_STRING("BCHP_VICE_MAU_0_DRAM_CONFIG"), BDBG_STRING("DRAM configuration"), false },
{ 0x00001c0c, BDBG_STRING("BCHP_VICE_MAU_0_DRAM_MAPPING"), BDBG_STRING("DRAM image mapping register"), false },
{ 0x00001c10, BDBG_STRING("BCHP_VICE_MAU_0_PICTURE_SIZE"), BDBG_STRING("Current and reference picture size"), false },
{ 0x00001c14, BDBG_STRING("BCHP_VICE_MAU_0_PFRI_BUDGET"), BDBG_STRING("PFRI Budget control"), false },
{ 0x00001c20, BDBG_STRING("BCHP_VICE_MAU_0_LUMA_ADDR_REF_0"), BDBG_STRING("Luma DRAM base address for reference frame buffer 0"), true },
{ 0x00001c28, BDBG_STRING("BCHP_VICE_MAU_0_LUMA_ADDR_REF_1"), BDBG_STRING("Luma DRAM base address for reference frame buffer 1"), true },
{ 0x00001c30, BDBG_STRING("BCHP_VICE_MAU_0_CHROMA_ADDR_REF_0"), BDBG_STRING("Chroma DRAM base address for reference frame buffer 0"), true },
{ 0x00001c38, BDBG_STRING("BCHP_VICE_MAU_0_CHROMA_ADDR_REF_1"), BDBG_STRING("Chroma DRAM base address for reference frame buffer 1"), true },
{ 0x00001c40, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_SEL"), BDBG_STRING("MAU debug information select register"), false },
{ 0x00001c44, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_SEL1"), BDBG_STRING("MAU debug information select register"), false },
{ 0x00001c48, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_SEL2"), BDBG_STRING("MAU debig information select register"), false },
{ 0x00001c4c, BDBG_STRING("BCHP_VICE_MAU_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00001c50, BDBG_STRING("BCHP_VICE_MAU_0_REG_STATUS"), BDBG_STRING("MAU shadow register status"), false },
{ 0x00001c54, BDBG_STRING("BCHP_VICE_MAU_0_STATUS"), BDBG_STRING("MAU core status"), false },
{ 0x00001c58, BDBG_STRING("BCHP_VICE_MAU_0_PFRI_BUDGET_STATUS"), BDBG_STRING("budget status"), false },
{ 0x00001c60, BDBG_STRING("BCHP_VICE_MAU_0_ERR_STATUS_ENABLE"), BDBG_STRING("MAU error status enable register"), false },
{ 0x00001c64, BDBG_STRING("BCHP_VICE_MAU_0_ERR_STATUS_CLR"), BDBG_STRING("MAU error status enable register"), false },
{ 0x00001c68, BDBG_STRING("BCHP_VICE_MAU_0_ERR_STATUS"), BDBG_STRING("MAU error status register"), false },
{ 0x00001c70, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_PROC_FME_REQ"), BDBG_STRING("Status Register : Prediction Cache process count for previous picture (FME Required Patch)"), false },
{ 0x00001c74, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_PROC_FME_OPT"), BDBG_STRING("Status Register : Prediction Cache process count for previous picture (FME Optional Patch)"), false },
{ 0x00001c78, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_PROC_MC_LUMA"), BDBG_STRING("Status Register : Prediction Cache process count for previous picture (MC Luma Patch)"), false },
{ 0x00001c7c, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_PROC_MC_CHROMA"), BDBG_STRING("Status Register : Prediction Cache process count for previous picture (MC Chroma Patch)"), false },
{ 0x00001c80, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_HIT_FME_REQ"), BDBG_STRING("Status Register : Prediction Cache hit count for previous picture (FME Required Patch)"), false },
{ 0x00001c84, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_HIT_FME_OPT"), BDBG_STRING("Status Register : Prediction Cache hit count for previous picture (FME Optional Patch)"), false },
{ 0x00001c88, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_HIT_MC_LUMA"), BDBG_STRING("Status Register : Prediction Cache hit count for previous picture (MC Luma Patch)"), false },
{ 0x00001c8c, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_HIT_MC_CHROMA"), BDBG_STRING("Status Register : Prediction Cache hit count for previous picture (MC Chroma Patch)"), false },
{ 0x00001c90, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_CACHE_MISS_FME_OPT"), BDBG_STRING("Status Register : Prediction Cache miss count for previous picture (FME Optional Patch)"), false },
{ 0x00001c94, BDBG_STRING("BCHP_VICE_MAU_0_PERFORMANCE_LOG_PFRI_CMD_GROUP_CNT"), BDBG_STRING("Status Register : PFRI command group with different group length count for current picture"), false },
{ 0x00001ca0, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_INFO_0"), BDBG_STRING("MAU debug information data register 0"), false },
{ 0x00001ca4, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_INFO_1"), BDBG_STRING("MAU debug information data register 1"), false },
{ 0x00001ca8, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_INFO_2"), BDBG_STRING("MAU debug information data register 2"), false },
{ 0x00001cac, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_INFO_3"), BDBG_STRING("MAU debug information data register 3"), false },
{ 0x00001cb0, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_COMMAND_FIFO_PTR"), BDBG_STRING("MAU debug PCACHE COMMAND FIFO internal pointer"), false },
{ 0x00001cb4, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_COMMAND_FIFO"), BDBG_STRING("MAU debug PCACHE COMMAND FIFO read address"), false },
{ 0x00001cb8, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_COMMAND_FIFO_RD_LO"), BDBG_STRING("MAU debug PCACHE COMMAND FIFO read lower data"), false },
{ 0x00001cbc, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_COMMAND_FIFO_RD_HI"), BDBG_STRING("MAU debug PCACHE COMMAND FIFO read higher data"), false },
{ 0x00001cc0, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_FME_CMD_INTERFACE"), BDBG_STRING("MAU debug FME CMD interface"), false },
{ 0x00001cc4, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_MC_CMD_INTERFACE"), BDBG_STRING("MAU debug MC CMD interface"), false },
{ 0x00001cc8, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_FME_PATCH_INTERFACE"), BDBG_STRING("MAU debug FME PATCH interface"), false },
{ 0x00001ccc, BDBG_STRING("BCHP_VICE_MAU_0_DEBUG_MC_PATCH_INTERFACE"), BDBG_STRING("MAU debug MC PATCH interface"), false },
{ 0x00002000, BDBG_STRING("BCHP_VICE_MC_0_FW_CONTROL"), BDBG_STRING("MC FW Control Register"), false },
{ 0x00002004, BDBG_STRING("BCHP_VICE_MC_0_CONFIG"), BDBG_STRING("MC Config Register"), false },
{ 0x00002008, BDBG_STRING("BCHP_VICE_MC_0_PICTURE_SIZE"), BDBG_STRING("Picture Size Register"), false },
{ 0x0000200c, BDBG_STRING("BCHP_VICE_MC_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00002010, BDBG_STRING("BCHP_VICE_MC_0_REG_STATUS"), BDBG_STRING("MC shadow register status"), false },
{ 0x00002014, BDBG_STRING("BCHP_VICE_MC_0_STATUS"), BDBG_STRING("MC Core Status"), false },
{ 0x00002018, BDBG_STRING("BCHP_VICE_MC_0_DINO_DEBUG_FME"), BDBG_STRING("DINO Debug Register (FME to MC)"), false },
{ 0x0000201c, BDBG_STRING("BCHP_VICE_MC_0_DINO_DEBUG_IMD"), BDBG_STRING("DINO Debug Register (IMD to MC)"), false },
{ 0x00002020, BDBG_STRING("BCHP_VICE_MC_0_DINO_DEBUG_XQ"), BDBG_STRING("DINO Debug Register (MC to XQ)"), false },
{ 0x00002024, BDBG_STRING("BCHP_VICE_MC_0_DINO_DEBUG_MBARC"), BDBG_STRING("DINO Debug Register (MC to ARCSS)"), false },
{ 0x0000202c, BDBG_STRING("BCHP_VICE_MC_0_DEBUG_SEL"), BDBG_STRING("MC Debug Information Select Register"), false },
{ 0x00002030, BDBG_STRING("BCHP_VICE_MC_0_DEBUG_INFO_0"), BDBG_STRING("MC Debug Information Data Register 0"), false },
{ 0x00002034, BDBG_STRING("BCHP_VICE_MC_0_DEBUG_INFO_1"), BDBG_STRING("MC Debug Information Data Register 1"), false },
{ 0x00002038, BDBG_STRING("BCHP_VICE_MC_0_DEBUG_INFO_2"), BDBG_STRING("MC Debug Information Data Register 2"), false },
{ 0x0000203c, BDBG_STRING("BCHP_VICE_MC_0_DEBUG_INFO_3"), BDBG_STRING("MC Debug Information Data Register 3"), false },
{ 0x00002040, BDBG_STRING("BCHP_VICE_MC_0_ERR_STATUS_ENABLE"), BDBG_STRING("MC Error Status Enable"), false },
{ 0x00002044, BDBG_STRING("BCHP_VICE_MC_0_ERR_STATUS_CLR"), BDBG_STRING("MC Error Status Clear"), false },
{ 0x00002048, BDBG_STRING("BCHP_VICE_MC_0_ERR_STATUS"), BDBG_STRING("MC Error Status Register"), false },
{ 0x00002400, BDBG_STRING("BCHP_VICE_SG_0_FW_CONTROL"), BDBG_STRING("SG Control"), false },
{ 0x00002404, BDBG_STRING("BCHP_VICE_SG_0_CONFIG"), BDBG_STRING("SG Configuration"), false },
{ 0x00002408, BDBG_STRING("BCHP_VICE_SG_0_CODEC"), BDBG_STRING("Codec Select Shadow Register"), false },
{ 0x0000240c, BDBG_STRING("BCHP_VICE_SG_0_PICTURE_SIZE"), BDBG_STRING("Picture Size Shadow Register"), false },
{ 0x00002410, BDBG_STRING("BCHP_VICE_SG_0_PICTURE_CFG"), BDBG_STRING("Picture Configuration Shadow Register"), false },
{ 0x00002414, BDBG_STRING("BCHP_VICE_SG_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00002418, BDBG_STRING("BCHP_VICE_SG_0_MPEG_CONFIG"), BDBG_STRING("MPEG-2 Encoding Configuration Shadow Register"), false },
{ 0x0000241c, BDBG_STRING("BCHP_VICE_SG_0_AVC_HEVC_CONFIG"), BDBG_STRING("AVC and HEVC Encoding Configuration Shadow Register"), false },
{ 0x00002420, BDBG_STRING("BCHP_VICE_SG_0_HEVC_CONFIG"), BDBG_STRING("HEVC Encoding Configuration Shadow Register"), false },
{ 0x00002424, BDBG_STRING("BCHP_VICE_SG_0_VP9_CONFIG"), BDBG_STRING("VP9 Encoding Configuration Shadow Register"), false },
{ 0x00002428, BDBG_STRING("BCHP_VICE_SG_0_STATUS"), BDBG_STRING("SG Core Status"), false },
{ 0x0000242c, BDBG_STRING("BCHP_VICE_SG_0_REG_STATUS"), BDBG_STRING("Shadow Register Status"), false },
{ 0x00002430, BDBG_STRING("BCHP_VICE_SG_0_DEBUG"), BDBG_STRING("SG Internal Debug Register"), false },
{ 0x00002434, BDBG_STRING("BCHP_VICE_SG_0_DINO_DEBUG_XQ"), BDBG_STRING("DINO Debug Register (XQ-to-SG)"), false },
{ 0x00002438, BDBG_STRING("BCHP_VICE_SG_0_DINO_DEBUG_CABAC"), BDBG_STRING("DINO Debug Register (SG-to-CABAC)"), false },
{ 0x0000243c, BDBG_STRING("BCHP_VICE_SG_0_TEST_CFG"), BDBG_STRING("Test Configuration Register"), false },
{ 0x00002440, BDBG_STRING("BCHP_VICE_SG_0_ERROR_STATUS_ENABLE"), BDBG_STRING("Error Status Enable"), false },
{ 0x00002444, BDBG_STRING("BCHP_VICE_SG_0_ERROR_STATUS_CLEAR"), BDBG_STRING("Error Status Clear"), false },
{ 0x00002448, BDBG_STRING("BCHP_VICE_SG_0_ERROR_STATUS"), BDBG_STRING("Error Status Register"), false },
{ 0x00002800, BDBG_STRING("BCHP_VICE_VIP_0_FW_CONTROL"), BDBG_STRING("VIP FW Control"), false },
{ 0x00002804, BDBG_STRING("BCHP_VICE_VIP_0_CONFIG"), BDBG_STRING("VIP Configure"), false },
{ 0x00002808, BDBG_STRING("BCHP_VICE_VIP_0_INPUT_PICTURE_SIZE"), BDBG_STRING("Current Expected Input Picture Size"), false },
{ 0x0000280c, BDBG_STRING("BCHP_VICE_VIP_0_OUTPUT_PICTURE_SIZE"), BDBG_STRING("Current Picture Size"), false },
{ 0x00002810, BDBG_STRING("BCHP_VICE_VIP_0_LUMA_BASE"), BDBG_STRING("Current Picture Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002818, BDBG_STRING("BCHP_VICE_VIP_0_LUMA_CFG"), BDBG_STRING("Current Picture Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002820, BDBG_STRING("BCHP_VICE_VIP_0_DCMH1V_BASE"), BDBG_STRING("Current Picture Horizontal Decimated Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002828, BDBG_STRING("BCHP_VICE_VIP_0_DCMH1V_CFG"), BDBG_STRING("Current Picture Horizontal Decimated Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002830, BDBG_STRING("BCHP_VICE_VIP_0_DCMH2V_BASE"), BDBG_STRING("Current Picture Both Horizontal and Vertical Decimated Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002838, BDBG_STRING("BCHP_VICE_VIP_0_DCMH2V_CFG"), BDBG_STRING("Current Picture Both Horizontal and Vertical Decimated Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002840, BDBG_STRING("BCHP_VICE_VIP_0_CHROMA_420_BASE"), BDBG_STRING("Current Picture 420 Chroma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002848, BDBG_STRING("BCHP_VICE_VIP_0_CHROMA_420_CFG"), BDBG_STRING("Current Picture 420 Chroma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002850, BDBG_STRING("BCHP_VICE_VIP_0_SHIFT_CHROMA_BASE"), BDBG_STRING("Current Picture Shifted Chroma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002858, BDBG_STRING("BCHP_VICE_VIP_0_SHIFT_CHROMA_CFG"), BDBG_STRING("Current Picture Shifted Chroma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002860, BDBG_STRING("BCHP_VICE_VIP_0_PCC_LUMA_BASE"), BDBG_STRING("Previous Picture Frame/Top/Bottom Buffer Address for PCC"), true },
{ 0x00002868, BDBG_STRING("BCHP_VICE_VIP_0_HIST_LUMA_BASE"), BDBG_STRING("Previous Picture Frame/Top/Bottom Buffer Address for Histogram"), true },
{ 0x00002870, BDBG_STRING("BCHP_VICE_VIP_0_PCC_LINE_RANGE"), BDBG_STRING("PCC Line Range"), false },
{ 0x00002874, BDBG_STRING("BCHP_VICE_VIP_0_PCC_CORE_VALUE"), BDBG_STRING("PCC Core Value"), false },
{ 0x00002878, BDBG_STRING("BCHP_VICE_VIP_0_HIST_LINE_RANGE"), BDBG_STRING("Histogram Line Range"), false },
{ 0x0000287c, BDBG_STRING("BCHP_VICE_VIP_0_HISTOGRAM_0"), BDBG_STRING("Histogram Threshold 0~1"), false },
{ 0x00002880, BDBG_STRING("BCHP_VICE_VIP_0_HISTOGRAM_1"), BDBG_STRING("Histogram Threshold 2~4"), false },
{ 0x00002884, BDBG_STRING("BCHP_VICE_VIP_0_BVB_PADDING_DATA"), BDBG_STRING("BVB PADDING DATA"), false },
{ 0x00002888, BDBG_STRING("BCHP_VICE_VIP_0_BVB_STATUS_CLEAR"), BDBG_STRING("BVB Status Clear"), false },
{ 0x0000288c, BDBG_STRING("BCHP_VICE_VIP_0_BVB_STATUS"), BDBG_STRING("BVB Status"), false },
{ 0x00002890, BDBG_STRING("BCHP_VICE_VIP_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00002894, BDBG_STRING("BCHP_VICE_VIP_0_HIST_STATUS_0"), BDBG_STRING("Histogram Status 0"), false },
{ 0x00002898, BDBG_STRING("BCHP_VICE_VIP_0_HIST_STATUS_1"), BDBG_STRING("Histogram Status 1"), false },
{ 0x0000289c, BDBG_STRING("BCHP_VICE_VIP_0_HIST_STATUS_2"), BDBG_STRING("Histogram Status 2"), false },
{ 0x000028a0, BDBG_STRING("BCHP_VICE_VIP_0_HIST_STATUS_3"), BDBG_STRING("Histogram Status 3"), false },
{ 0x000028a4, BDBG_STRING("BCHP_VICE_VIP_0_HIST_STATUS_4"), BDBG_STRING("Histogram Status 4"), false },
{ 0x000028a8, BDBG_STRING("BCHP_VICE_VIP_0_SINGLE_PCC_STATUS"), BDBG_STRING("PCC Status 0"), false },
{ 0x000028ac, BDBG_STRING("BCHP_VICE_VIP_0_DOUBLE_PCC_STATUS"), BDBG_STRING("PCC Status 1"), false },
{ 0x000028b0, BDBG_STRING("BCHP_VICE_VIP_0_STATUS"), BDBG_STRING("VIP Status"), false },
{ 0x000028b4, BDBG_STRING("BCHP_VICE_VIP_0_REG_STATUS"), BDBG_STRING("REG Status"), false },
{ 0x000028b8, BDBG_STRING("BCHP_VICE_VIP_0_DEBUG"), BDBG_STRING("DEBUG"), false },
{ 0x000028c0, BDBG_STRING("BCHP_VICE_VIP_0_ERR_STATUS_ENABLE"), BDBG_STRING("ERR_STATUS_ENABLE"), false },
{ 0x000028c4, BDBG_STRING("BCHP_VICE_VIP_0_ERR_STATUS_CLR"), BDBG_STRING("ERR_STATUS_CLR"), false },
{ 0x000028c8, BDBG_STRING("BCHP_VICE_VIP_0_ERR_STATUS"), BDBG_STRING("ERR_STATUS"), false },
{ 0x00002900, BDBG_STRING("BCHP_VICE_VIP_0_DCXV_CFG"), BDBG_STRING("DCXV Configuration"), false },
{ 0x00002904, BDBG_STRING("BCHP_VICE_VIP_0_DCDV_DEBUG"), BDBG_STRING("DCDV Debug Infomation"), false },
{ 0x00002c00, BDBG_STRING("BCHP_VICE_VIP1_0_FW_CONTROL"), BDBG_STRING("VIP FW Control"), false },
{ 0x00002c04, BDBG_STRING("BCHP_VICE_VIP1_0_CONFIG"), BDBG_STRING("VIP Configure"), false },
{ 0x00002c08, BDBG_STRING("BCHP_VICE_VIP1_0_INPUT_PICTURE_SIZE"), BDBG_STRING("Current Expected Input Picture Size"), false },
{ 0x00002c0c, BDBG_STRING("BCHP_VICE_VIP1_0_OUTPUT_PICTURE_SIZE"), BDBG_STRING("Current Picture Size"), false },
{ 0x00002c10, BDBG_STRING("BCHP_VICE_VIP1_0_LUMA_BASE"), BDBG_STRING("Current Picture Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002c18, BDBG_STRING("BCHP_VICE_VIP1_0_LUMA_CFG"), BDBG_STRING("Current Picture Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002c20, BDBG_STRING("BCHP_VICE_VIP1_0_DCMH1V_BASE"), BDBG_STRING("Current Picture Horizontal Decimated Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002c28, BDBG_STRING("BCHP_VICE_VIP1_0_DCMH1V_CFG"), BDBG_STRING("Current Picture Horizontal Decimated Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002c30, BDBG_STRING("BCHP_VICE_VIP1_0_DCMH2V_BASE"), BDBG_STRING("Current Picture Both Horizontal and Vertical Decimated Luma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002c38, BDBG_STRING("BCHP_VICE_VIP1_0_DCMH2V_CFG"), BDBG_STRING("Current Picture Both Horizontal and Vertical Decimated Luma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002c40, BDBG_STRING("BCHP_VICE_VIP1_0_CHROMA_420_BASE"), BDBG_STRING("Current Picture 420 Chroma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002c48, BDBG_STRING("BCHP_VICE_VIP1_0_CHROMA_420_CFG"), BDBG_STRING("Current Picture 420 Chroma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002c50, BDBG_STRING("BCHP_VICE_VIP1_0_SHIFT_CHROMA_BASE"), BDBG_STRING("Current Picture Shifted Chroma Frame/Top/Bottom Buffer Address"), true },
{ 0x00002c58, BDBG_STRING("BCHP_VICE_VIP1_0_SHIFT_CHROMA_CFG"), BDBG_STRING("Current Picture Shifted Chroma Frame/Top/Bottom Buffer NMBY and Line Stride"), false },
{ 0x00002c60, BDBG_STRING("BCHP_VICE_VIP1_0_PCC_LUMA_BASE"), BDBG_STRING("Previous Picture Frame/Top/Bottom Buffer Address for PCC"), true },
{ 0x00002c68, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_LUMA_BASE"), BDBG_STRING("Previous Picture Frame/Top/Bottom Buffer Address for Histogram"), true },
{ 0x00002c70, BDBG_STRING("BCHP_VICE_VIP1_0_PCC_LINE_RANGE"), BDBG_STRING("PCC Line Range"), false },
{ 0x00002c74, BDBG_STRING("BCHP_VICE_VIP1_0_PCC_CORE_VALUE"), BDBG_STRING("PCC Core Value"), false },
{ 0x00002c78, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_LINE_RANGE"), BDBG_STRING("Histogram Line Range"), false },
{ 0x00002c7c, BDBG_STRING("BCHP_VICE_VIP1_0_HISTOGRAM_0"), BDBG_STRING("Histogram Threshold 0~1"), false },
{ 0x00002c80, BDBG_STRING("BCHP_VICE_VIP1_0_HISTOGRAM_1"), BDBG_STRING("Histogram Threshold 2~4"), false },
{ 0x00002c84, BDBG_STRING("BCHP_VICE_VIP1_0_BVB_PADDING_DATA"), BDBG_STRING("BVB PADDING DATA"), false },
{ 0x00002c88, BDBG_STRING("BCHP_VICE_VIP1_0_BVB_STATUS_CLEAR"), BDBG_STRING("BVB Status Clear"), false },
{ 0x00002c8c, BDBG_STRING("BCHP_VICE_VIP1_0_BVB_STATUS"), BDBG_STRING("BVB Status"), false },
{ 0x00002c90, BDBG_STRING("BCHP_VICE_VIP1_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00002c94, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_STATUS_0"), BDBG_STRING("Histogram Status 0"), false },
{ 0x00002c98, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_STATUS_1"), BDBG_STRING("Histogram Status 1"), false },
{ 0x00002c9c, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_STATUS_2"), BDBG_STRING("Histogram Status 2"), false },
{ 0x00002ca0, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_STATUS_3"), BDBG_STRING("Histogram Status 3"), false },
{ 0x00002ca4, BDBG_STRING("BCHP_VICE_VIP1_0_HIST_STATUS_4"), BDBG_STRING("Histogram Status 4"), false },
{ 0x00002ca8, BDBG_STRING("BCHP_VICE_VIP1_0_SINGLE_PCC_STATUS"), BDBG_STRING("PCC Status 0"), false },
{ 0x00002cac, BDBG_STRING("BCHP_VICE_VIP1_0_DOUBLE_PCC_STATUS"), BDBG_STRING("PCC Status 1"), false },
{ 0x00002cb0, BDBG_STRING("BCHP_VICE_VIP1_0_STATUS"), BDBG_STRING("VIP Status"), false },
{ 0x00002cb4, BDBG_STRING("BCHP_VICE_VIP1_0_REG_STATUS"), BDBG_STRING("REG Status"), false },
{ 0x00002cb8, BDBG_STRING("BCHP_VICE_VIP1_0_DEBUG"), BDBG_STRING("DEBUG"), false },
{ 0x00002cc0, BDBG_STRING("BCHP_VICE_VIP1_0_ERR_STATUS_ENABLE"), BDBG_STRING("ERR_STATUS_ENABLE"), false },
{ 0x00002cc4, BDBG_STRING("BCHP_VICE_VIP1_0_ERR_STATUS_CLR"), BDBG_STRING("ERR_STATUS_CLR"), false },
{ 0x00002cc8, BDBG_STRING("BCHP_VICE_VIP1_0_ERR_STATUS"), BDBG_STRING("ERR_STATUS"), false },
{ 0x00002d00, BDBG_STRING("BCHP_VICE_VIP1_0_DCXV_CFG"), BDBG_STRING("DCXV Configuration"), false },
{ 0x00002d04, BDBG_STRING("BCHP_VICE_VIP1_0_DCDV_DEBUG"), BDBG_STRING("DCDV Debug Infomation"), false },
{ 0x00003000, BDBG_STRING("BCHP_VICE_VIP2_0_FW_CONTROL"), BDBG_STRING("VIP FW Control"), false },
{ 0x00003100, BDBG_STRING("BCHP_VICE_VIP2_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00003400, BDBG_STRING("BCHP_VICE_VIP3_0_FW_CONTROL"), BDBG_STRING("VIP FW Control"), false },
{ 0x00003500, BDBG_STRING("BCHP_VICE_VIP3_0_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00004000, BDBG_STRING("BCHP_VICE_XQ_0_FW_CONTROL"), BDBG_STRING("XQ FW control"), false },
{ 0x00004004, BDBG_STRING("BCHP_VICE_XQ_0_CONFIG"), BDBG_STRING("XQ configuration control"), false },
{ 0x00004008, BDBG_STRING("BCHP_VICE_XQ_0_CONFIG_PARAM_0"), BDBG_STRING("Quantization-related parameters"), false },
{ 0x0000400c, BDBG_STRING("BCHP_VICE_XQ_0_CONFIG_PARAM_1"), BDBG_STRING("Parameters for small coefficient suppression"), false },
{ 0x00004010, BDBG_STRING("BCHP_VICE_XQ_0_CONFIG_PARAM_2"), BDBG_STRING("Parameters for VP9 QP segment 1 to 5"), false },
{ 0x00004014, BDBG_STRING("BCHP_VICE_XQ_0_CONFIG_PARAM_3"), BDBG_STRING("Parameters for VP9 QP segment 6 to 8"), false },
{ 0x00004018, BDBG_STRING("BCHP_VICE_XQ_0_PICTURE_SIZE"), BDBG_STRING("Current picture size"), false },
{ 0x00004090, BDBG_STRING("BCHP_VICE_XQ_0_SCRATCH"), BDBG_STRING("XQ scratch register"), false },
{ 0x00004094, BDBG_STRING("BCHP_VICE_XQ_0_ERR_STATUS_ENABLE"), BDBG_STRING("XQ Error status enable"), false },
{ 0x00004098, BDBG_STRING("BCHP_VICE_XQ_0_ERR_STATUS_CLR"), BDBG_STRING("XQ Error status clear"), false },
{ 0x0000409c, BDBG_STRING("BCHP_VICE_XQ_0_ERR_STATUS"), BDBG_STRING("XQ Error status"), false },
{ 0x000040a0, BDBG_STRING("BCHP_VICE_XQ_0_STATUS"), BDBG_STRING("XQ status"), false },
{ 0x000040a4, BDBG_STRING("BCHP_VICE_XQ_0_DINO_DEBUG_MC"), BDBG_STRING("DINO Debug Register (MC to XQ)"), false },
{ 0x000040a8, BDBG_STRING("BCHP_VICE_XQ_0_DINO_DEBUG_MBARC"), BDBG_STRING("DINO Debug Register (MBARC to XQ)"), false },
{ 0x000040ac, BDBG_STRING("BCHP_VICE_XQ_0_DINO_DEBUG_SG"), BDBG_STRING("DINO Debug Register (XQ to SG)"), false },
{ 0x000040b0, BDBG_STRING("BCHP_VICE_XQ_0_DINO_DEBUG_ILF"), BDBG_STRING("DINO Debug Register (XQ to ILF)"), false },
{ 0x000040b4, BDBG_STRING("BCHP_VICE_XQ_0_DINO_DEBUG_IMD"), BDBG_STRING("DINO Debug Register (XQ to IMD)"), false },
{ 0x00020000, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_HOST_IF"), BDBG_STRING("Host I/F"), false },
{ 0x00020004, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_SYNC_LOCAL_RBUS"), BDBG_STRING("Sync Local Rbus"), false },
{ 0x00020010, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_B2B_OOB_DEBUG_ADDR"), BDBG_STRING("B2B out of bound debug address"), false },
{ 0x00020014, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_B2B_OOB_ADDR_INFO"), BDBG_STRING("B2B out of bound address info"), false },
{ 0x00020018, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2SYSTEM_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to system RBUS debug address"), false },
{ 0x00020020, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2SYSTEM_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to system RBUS debug info"), false },
{ 0x00020028, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2GLOBAL_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to global RBUS debug address"), false },
{ 0x00020030, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2GLOBAL_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to global RBUS debug info"), false },
{ 0x00020038, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2LOCAL_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to system RBUS debug address"), false },
{ 0x00020040, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2LOCAL_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to system RBUS debug info"), false },
{ 0x00020044, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_DATA_SPACE_START"), BDBG_STRING("Data Space Start"), false },
{ 0x00020048, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_ARC_DATA_ADDR_OFFSET"), BDBG_STRING("ARC Data address offset"), true },
{ 0x00020050, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_ARC_INSTR_ADDR_OFFSET"), BDBG_STRING("ARC instructions address offset"), true },
{ 0x00020058, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_BVCI2SCB_CACHE_MISS"), BDBG_STRING("BVCI2SCB cache miss"), false },
{ 0x0002005c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_BVCI2SCB_BRIDGE_CTRL"), BDBG_STRING("BVCI2SCB bridge ctrl"), false },
{ 0x00020088, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_DMA_ACTIVE_CHANNEL"), BDBG_STRING("DMA active channel"), false },
{ 0x00020090, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_SYS_WATCHDOG_CTRL"), BDBG_STRING("Watchdog Ctrl"), false },
{ 0x00020094, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_WATCHDOG_COUNTER"), BDBG_STRING("Watchdog Counter"), false },
{ 0x000200a0, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_PROC_CTRL"), BDBG_STRING("Processor control"), false },
{ 0x000200a4, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_PROC_CTRL2"), BDBG_STRING("Processor control2"), false },
{ 0x000200a8, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_INIT_PROC_START"), BDBG_STRING("Processor Start"), false },
{ 0x000200b0, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_DIAG"), BDBG_STRING("Diagnostic Register"), false },
{ 0x000200b4, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_0_DIAG_CTRL"), BDBG_STRING("Diagnostic Register select"), false },
{ 0x00020400, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_STATUS"), BDBG_STRING("Soft interrupt Status Register"), false },
{ 0x00020404, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_SET"), BDBG_STRING("Soft interrupt Set Register"), false },
{ 0x00020408, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_CLEAR"), BDBG_STRING("Soft interrupt Clear Register"), false },
{ 0x0002040c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_MASK_STATUS"), BDBG_STRING("Soft interrupt Mask Status Register"), false },
{ 0x00020410, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_MASK_SET"), BDBG_STRING("Soft interrupt Mask Set Register"), false },
{ 0x00020414, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_0_MASK_CLEAR"), BDBG_STRING("Soft interrupt Mask Clear Register"), false },
{ 0x00020600, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_STATUS"), BDBG_STRING("ARC P0 interrupt Status Register"), false },
{ 0x00020604, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_SET"), BDBG_STRING("ARC P0 interrupt Set Register"), false },
{ 0x00020608, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_CLEAR"), BDBG_STRING("ARC P0 interrupt Clear Register"), false },
{ 0x0002060c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_MASK_STATUS"), BDBG_STRING("ARC P0 interrupt Mask Status Register"), false },
{ 0x00020610, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_MASK_SET"), BDBG_STRING("ARC P0 interrupt Mask Set Register"), false },
{ 0x00020614, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P0_MASK_CLEAR"), BDBG_STRING("ARC P0 interrupt Mask Clear Register"), false },
{ 0x00020618, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_STATUS"), BDBG_STRING("ARC P1 interrupt Status Register"), false },
{ 0x0002061c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_SET"), BDBG_STRING("ARC P1 interrupt Set Register"), false },
{ 0x00020620, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_CLEAR"), BDBG_STRING("ARC P1 interrupt Clear Register"), false },
{ 0x00020624, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_MASK_STATUS"), BDBG_STRING("ARC P1 interrupt Mask Status Register"), false },
{ 0x00020628, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_MASK_SET"), BDBG_STRING("ARC P1 interrupt Mask Set Register"), false },
{ 0x0002062c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_0_ARC_P1_MASK_CLEAR"), BDBG_STRING("ARC P1 interrupt Mask Clear Register"), false },
{ 0x00060000, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_HOST_IF"), BDBG_STRING("Host I/F"), false },
{ 0x00060004, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_SYNC_LOCAL_RBUS"), BDBG_STRING("Sync Local Rbus"), false },
{ 0x00060010, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_B2B_OOB_DEBUG_ADDR"), BDBG_STRING("B2B out of bound debug address"), false },
{ 0x00060014, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_B2B_OOB_ADDR_INFO"), BDBG_STRING("B2B out of bound address info"), false },
{ 0x00060018, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2SYSTEM_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to system RBUS debug address"), false },
{ 0x00060020, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2SYSTEM_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to system RBUS debug info"), false },
{ 0x00060028, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2GLOBAL_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to global RBUS debug address"), false },
{ 0x00060030, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2GLOBAL_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to global RBUS debug info"), false },
{ 0x00060038, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2LOCAL_RBUS_DEBUG_ADDR"), BDBG_STRING("BVCI to system RBUS debug address"), false },
{ 0x00060040, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2LOCAL_RBUS_DEBUG_INFO"), BDBG_STRING("BVCI to system RBUS debug info"), false },
{ 0x00060044, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_DATA_SPACE_START"), BDBG_STRING("Data Space Start"), false },
{ 0x00060048, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_ARC_DATA_ADDR_OFFSET"), BDBG_STRING("ARC Data address offset"), true },
{ 0x00060050, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_ARC_INSTR_ADDR_OFFSET"), BDBG_STRING("ARC instructions address offset"), true },
{ 0x00060058, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_BVCI2SCB_CACHE_MISS"), BDBG_STRING("BVCI2SCB cache miss"), false },
{ 0x0006005c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_BVCI2SCB_BRIDGE_CTRL"), BDBG_STRING("BVCI2SCB bridge ctrl"), false },
{ 0x00060088, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_DMA_ACTIVE_CHANNEL"), BDBG_STRING("DMA active channel"), false },
{ 0x00060090, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_SYS_WATCHDOG_CTRL"), BDBG_STRING("Watchdog Ctrl"), false },
{ 0x00060094, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_WATCHDOG_COUNTER"), BDBG_STRING("Watchdog Counter"), false },
{ 0x000600a0, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_PROC_CTRL"), BDBG_STRING("Processor control"), false },
{ 0x000600a4, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_PROC_CTRL2"), BDBG_STRING("Processor control2"), false },
{ 0x000600a8, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_INIT_PROC_START"), BDBG_STRING("Processor Start"), false },
{ 0x000600b0, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_DIAG"), BDBG_STRING("Diagnostic Register"), false },
{ 0x000600b4, BDBG_STRING("BCHP_VICE_ARCSS_ESS_CTRL_1_DIAG_CTRL"), BDBG_STRING("Diagnostic Register select"), false },
{ 0x00060400, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_STATUS"), BDBG_STRING("Soft interrupt Status Register"), false },
{ 0x00060404, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_SET"), BDBG_STRING("Soft interrupt Set Register"), false },
{ 0x00060408, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_CLEAR"), BDBG_STRING("Soft interrupt Clear Register"), false },
{ 0x0006040c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_MASK_STATUS"), BDBG_STRING("Soft interrupt Mask Status Register"), false },
{ 0x00060410, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_MASK_SET"), BDBG_STRING("Soft interrupt Mask Set Register"), false },
{ 0x00060414, BDBG_STRING("BCHP_VICE_ARCSS_ESS_FLAG_INTR2_1_MASK_CLEAR"), BDBG_STRING("Soft interrupt Mask Clear Register"), false },
{ 0x00060600, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_STATUS"), BDBG_STRING("ARC P0 interrupt Status Register"), false },
{ 0x00060604, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_SET"), BDBG_STRING("ARC P0 interrupt Set Register"), false },
{ 0x00060608, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_CLEAR"), BDBG_STRING("ARC P0 interrupt Clear Register"), false },
{ 0x0006060c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_MASK_STATUS"), BDBG_STRING("ARC P0 interrupt Mask Status Register"), false },
{ 0x00060610, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_MASK_SET"), BDBG_STRING("ARC P0 interrupt Mask Set Register"), false },
{ 0x00060614, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P0_MASK_CLEAR"), BDBG_STRING("ARC P0 interrupt Mask Clear Register"), false },
{ 0x00060618, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_STATUS"), BDBG_STRING("ARC P1 interrupt Status Register"), false },
{ 0x0006061c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_SET"), BDBG_STRING("ARC P1 interrupt Set Register"), false },
{ 0x00060620, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_CLEAR"), BDBG_STRING("ARC P1 interrupt Clear Register"), false },
{ 0x00060624, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_MASK_STATUS"), BDBG_STRING("ARC P1 interrupt Mask Status Register"), false },
{ 0x00060628, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_MASK_SET"), BDBG_STRING("ARC P1 interrupt Mask Set Register"), false },
{ 0x0006062c, BDBG_STRING("BCHP_VICE_ARCSS_ESS_P1_INTR2_1_ARC_P1_MASK_CLEAR"), BDBG_STRING("ARC P1 interrupt Mask Clear Register"), false },
{ 0x00081000, BDBG_STRING("BCHP_VICE_MISC_REVISION"), BDBG_STRING("VICE Revision"), false },
{ 0x00081004, BDBG_STRING("BCHP_VICE_MISC_SW_INIT_SET"), BDBG_STRING("VICE Soft Init Set"), false },
{ 0x00081008, BDBG_STRING("BCHP_VICE_MISC_SW_INIT_CLR"), BDBG_STRING("VICE Soft Init Clear"), false },
{ 0x0008100c, BDBG_STRING("BCHP_VICE_MISC_SW_INIT_CONTROL"), BDBG_STRING("VICE Soft Init Control"), false },
{ 0x00081010, BDBG_STRING("BCHP_VICE_MISC_TEST_PORT_SEL"), BDBG_STRING("VICE Test Port Select"), false },
{ 0x00081014, BDBG_STRING("BCHP_VICE_MISC_TEST_PORT_DATA"), BDBG_STRING("VICE Test Port Status"), false },
{ 0x00081018, BDBG_STRING("BCHP_VICE_MISC_VICE_ERR_STATUS"), BDBG_STRING("VICE Error Status"), false },
{ 0x0008101c, BDBG_STRING("BCHP_VICE_MISC_VICE_CLOCK_CTRL"), BDBG_STRING("VICE clock control register"), false },
{ 0x00081020, BDBG_STRING("BCHP_VICE_MISC_SCRATCH"), BDBG_STRING("Scratch Register"), false },
{ 0x00081024, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB0_SW_INIT_ACK_STATUS"), BDBG_STRING("VICE SCB0 SW INIT ACK Status"), false },
{ 0x00081028, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB1_SW_INIT_ACK_STATUS"), BDBG_STRING("VICE SCB1 SW INIT ACK Status"), false },
{ 0x0008102c, BDBG_STRING("BCHP_VICE_MISC_PDA_POWER_UP_STATUS"), BDBG_STRING("PDA POWER UP STATUS"), false },
{ 0x00081030, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB2_SW_INIT_ACK_STATUS"), BDBG_STRING("VICE SCB2 SW INIT ACK Status"), false },
{ 0x00081034, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB0_REQ_STATUS"), BDBG_STRING("VICE SCB0 REQ Status"), false },
{ 0x00081038, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB1_REQ_STATUS"), BDBG_STRING("VICE SCB1 REQ Status"), false },
{ 0x0008103c, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB2_REQ_STATUS"), BDBG_STRING("VICE SCB2 REQ Status"), false },
{ 0x00081040, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB0_ACK_STATUS"), BDBG_STRING("VICE SCB0 ACK Status"), false },
{ 0x00081044, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB1_ACK_STATUS"), BDBG_STRING("VICE SCB1 ACK Status"), false },
{ 0x00081048, BDBG_STRING("BCHP_VICE_MISC_VICE_SCB2_ACK_STATUS"), BDBG_STRING("VICE SCB2 ACK Status"), false },
{ 0x0008104c, BDBG_STRING("BCHP_VICE_MISC_VICE_MB_PIPELINE_READY_STATUS"), BDBG_STRING("VICE MB PIPELINE READY Status"), false },
{ 0x00081050, BDBG_STRING("BCHP_VICE_MISC_VICE_MB_PIPELINE_ACCEPT_STATUS"), BDBG_STRING("VICE MB PIPELINE ACCEPT Status"), false },
{ 0x00081060, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE1"), BDBG_STRING("Storage1 Register"), false },
{ 0x00081064, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE2"), BDBG_STRING("Storage2 Register"), false },
{ 0x00081068, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE3"), BDBG_STRING("Storage3 Register"), false },
{ 0x0008106c, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE4"), BDBG_STRING("Storage4 Register"), false },
{ 0x00081070, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE5"), BDBG_STRING("Storage5 Register"), false },
{ 0x00081074, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE6"), BDBG_STRING("Storage6 Register"), false },
{ 0x00081078, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE7"), BDBG_STRING("Storage7 Register"), false },
{ 0x0008107c, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE8"), BDBG_STRING("Storage8 Register"), false },
{ 0x00081080, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE9"), BDBG_STRING("Storage9 Register"), false },
{ 0x00081084, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE10"), BDBG_STRING("Storage10 Register"), false },
{ 0x00081088, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE11"), BDBG_STRING("Storage11 Register"), false },
{ 0x0008108c, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE12"), BDBG_STRING("Storage12 Register"), false },
{ 0x00081090, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE13"), BDBG_STRING("Storage13 Register"), false },
{ 0x00081094, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE14"), BDBG_STRING("Storage14 Register"), false },
{ 0x00081098, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE15"), BDBG_STRING("Storage15 Register"), false },
{ 0x0008109c, BDBG_STRING("BCHP_VICE_MISC_FW_STORAGE16"), BDBG_STRING("Storage16 Register"), false },
{ 0x00081100, BDBG_STRING("BCHP_VICE_L2_CPU_STATUS"), BDBG_STRING("CPU interrupt Status Register"), false },
{ 0x00081104, BDBG_STRING("BCHP_VICE_L2_CPU_SET"), BDBG_STRING("CPU interrupt Set Register"), false },
{ 0x00081108, BDBG_STRING("BCHP_VICE_L2_CPU_CLEAR"), BDBG_STRING("CPU interrupt Clear Register"), false },
{ 0x0008110c, BDBG_STRING("BCHP_VICE_L2_CPU_MASK_STATUS"), BDBG_STRING("CPU interrupt Mask Status Register"), false },
{ 0x00081110, BDBG_STRING("BCHP_VICE_L2_CPU_MASK_SET"), BDBG_STRING("CPU interrupt Mask Set Register"), false },
{ 0x00081114, BDBG_STRING("BCHP_VICE_L2_CPU_MASK_CLEAR"), BDBG_STRING("CPU interrupt Mask Clear Register"), false },
{ 0x00081118, BDBG_STRING("BCHP_VICE_L2_PCI_STATUS"), BDBG_STRING("PCI interrupt Status Register"), false },
{ 0x0008111c, BDBG_STRING("BCHP_VICE_L2_PCI_SET"), BDBG_STRING("PCI interrupt Set Register"), false },
{ 0x00081120, BDBG_STRING("BCHP_VICE_L2_PCI_CLEAR"), BDBG_STRING("PCI interrupt Clear Register"), false },
{ 0x00081124, BDBG_STRING("BCHP_VICE_L2_PCI_MASK_STATUS"), BDBG_STRING("PCI interrupt Mask Status Register"), false },
{ 0x00081128, BDBG_STRING("BCHP_VICE_L2_PCI_MASK_SET"), BDBG_STRING("PCI interrupt Mask Set Register"), false },
{ 0x0008112c, BDBG_STRING("BCHP_VICE_L2_PCI_MASK_CLEAR"), BDBG_STRING("PCI interrupt Mask Clear Register"), false },
{ 0x00082000, BDBG_STRING("BCHP_VICE_ARCSS_MISC_SYNC_GLOBAL_RBUS"), BDBG_STRING("Sync Global Rbus"), false },
{ 0x00082008, BDBG_STRING("BCHP_VICE_ARCSS_MISC_INIT_SYS_REG_ADDR_OFFSET"), BDBG_STRING("System Registers Address Space Offset"), true },
{ 0x0008201c, BDBG_STRING("BCHP_VICE_ARCSS_MISC_JTAG"), BDBG_STRING("JTAG"), false },
{ 0x00082020, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC0_LOWER"), BDBG_STRING("STC0 LOWER 32bit"), false },
{ 0x00082024, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC0_UPPER"), BDBG_STRING("STC0 UPPER 10bit"), false },
{ 0x00082028, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC1_LOWER"), BDBG_STRING("STC1 LOWER 32bit"), false },
{ 0x0008202c, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC1_UPPER"), BDBG_STRING("STC1 UPPER 10bit"), false },
{ 0x00082030, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC2_LOWER"), BDBG_STRING("STC2 LOWER 32bit"), false },
{ 0x00082034, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC2_UPPER"), BDBG_STRING("STC2 UPPER 10bit"), false },
{ 0x00082038, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC3_LOWER"), BDBG_STRING("STC3 LOWER 32bit"), false },
{ 0x0008203c, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC3_UPPER"), BDBG_STRING("STC3 UPPER 10bit"), false },
{ 0x00082040, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC0_CTRL"), BDBG_STRING("STC 0 Control"), false },
{ 0x00082044, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC1_CTRL"), BDBG_STRING("STC 1 Control"), false },
{ 0x00082048, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC2_CTRL"), BDBG_STRING("STC 2 Control"), false },
{ 0x0008204c, BDBG_STRING("BCHP_VICE_ARCSS_MISC_STC3_CTRL"), BDBG_STRING("STC 3 Control"), false },
{ 0x00082070, BDBG_STRING("BCHP_VICE_ARCSS_MISC_MISC_CTRL"), BDBG_STRING("MISC Control"), false },
{ 0x00082074, BDBG_STRING("BCHP_VICE_ARCSS_MISC_SCB_STATUS"), BDBG_STRING("ARCSS SCB Status Register"), false },
{ 0x000820b0, BDBG_STRING("BCHP_VICE_ARCSS_MISC_TIMER0_COUNTER"), BDBG_STRING("Timer0 Counter"), false },
{ 0x000820b4, BDBG_STRING("BCHP_VICE_ARCSS_MISC_TIMER0_PERIOD"), BDBG_STRING("Timer0 Period"), false },
{ 0x000820b8, BDBG_STRING("BCHP_VICE_ARCSS_MISC_TIMER0_CONTROL"), BDBG_STRING("Timer0 Control"), false },
#else
{0, "", "", false },
#endif
};

#if BDBG_DEBUG_BUILD
const unsigned s_uiViceHardwareRegistersCount = 574;
#else
const unsigned s_uiViceHardwareRegistersCount = 0;
#endif

/* End of File */
