/***************************************************************************
 *     Copyright (c) 2003-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

BVCE_MEMCONFIG_FIELD(uiPictureMemSize)
BVCE_MEMCONFIG_FIELD(uiSecureMemSize)
BVCE_MEMCONFIG_FIELD(uiGeneralMemSize)
BVCE_MEMCONFIG_FIELD(uiFirmwareMemSize)
BVCE_MEMCONFIG_FIELD(uiIndexMemSize)
BVCE_MEMCONFIG_FIELD(uiDataMemSize)
#undef BVCE_MEMCONFIG_FIELD
