/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Feb 23 15:26:07 2016
 *                 Full Compile MD5 Checksum  4b84f30a4b3665aac5b824a1ed76e56c
 *                     (minus title and desc)
 *                 MD5 Checksum               4894bba0ec078aee10b5b5954262d56e
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     804
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /home/pntruong/sbin/combo_header.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_DS_A_00_OI_H__
#define BCHP_DS_A_00_OI_H__

/***************************************************************************
 *DS_A_00_OI - Downstream Output Interface Registers
 ***************************************************************************/
#define BCHP_DS_A_00_OI_STATUS                   0x04321200 /* [RO] OI status */
#define BCHP_DS_A_00_OI_NCON                     0x04321204 /* [CFG] OI Clock Rate NCO Numerator */
#define BCHP_DS_A_00_OI_NCODL                    0x04321208 /* [CFG] OI Clock Rate NCO Delta */
#define BCHP_DS_A_00_OI_FIFO_CTL                 0x0432120c /* [CFG] FIFO control */
#define BCHP_DS_A_00_OI_CTL                      0x04321210 /* [CFG] OI Control */
#define BCHP_DS_A_00_OI_OUT                      0x04321214 /* [RW] OI Output override Control */
#define BCHP_DS_A_00_OI_MPEG_CNT                 0x04321218 /* [RO] OI MPEG Count */
#define BCHP_DS_A_00_OI_BERT_CTL                 0x04321224 /* [CFG] OI BERT Control Register */
#define BCHP_DS_A_00_OI_BERT_IT                  0x04321228 /* [CFG] OI BERT integration period and threshold */
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H           0x0432122c /* [RO] OI BERT bit Counter snapshot value, higher bits */
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_L           0x04321230 /* [RO] OI BERT bit Counter snapshot value, lower bits */
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H           0x04321234 /* [RO] OI BERT error Counter snapshot value, higher bits */
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_L           0x04321238 /* [RO] OI BERT error Counter snapshot value, lower bits */
#define BCHP_DS_A_00_OI_BERT_ST                  0x0432123c /* [RO] OI BERT status register */

/***************************************************************************
 *STATUS - OI status
 ***************************************************************************/
/* DS_A_00_OI :: STATUS :: reserved0 [31:16] */
#define BCHP_DS_A_00_OI_STATUS_reserved0_MASK                      0xffff0000
#define BCHP_DS_A_00_OI_STATUS_reserved0_SHIFT                     16

/* DS_A_00_OI :: STATUS :: FEC_LS_STATUS [15:15] */
#define BCHP_DS_A_00_OI_STATUS_FEC_LS_STATUS_MASK                  0x00008000
#define BCHP_DS_A_00_OI_STATUS_FEC_LS_STATUS_SHIFT                 15
#define BCHP_DS_A_00_OI_STATUS_FEC_LS_STATUS_DEFAULT               0x00000000

/* DS_A_00_OI :: STATUS :: SYNC_HDR_ERR [14:14] */
#define BCHP_DS_A_00_OI_STATUS_SYNC_HDR_ERR_MASK                   0x00004000
#define BCHP_DS_A_00_OI_STATUS_SYNC_HDR_ERR_SHIFT                  14
#define BCHP_DS_A_00_OI_STATUS_SYNC_HDR_ERR_DEFAULT                0x00000000

/* DS_A_00_OI :: STATUS :: OB_FIFO_OVERFLOW [13:13] */
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_OVERFLOW_MASK               0x00002000
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_OVERFLOW_SHIFT              13
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_OVERFLOW_DEFAULT            0x00000000

/* DS_A_00_OI :: STATUS :: OB_FIFO_UNDERFLOW [12:12] */
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_UNDERFLOW_MASK              0x00001000
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_UNDERFLOW_SHIFT             12
#define BCHP_DS_A_00_OI_STATUS_OB_FIFO_UNDERFLOW_DEFAULT           0x00000000

/* DS_A_00_OI :: STATUS :: F1B_FIFO_OVERFLOW [11:11] */
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_OVERFLOW_MASK              0x00000800
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_OVERFLOW_SHIFT             11
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_OVERFLOW_DEFAULT           0x00000000

/* DS_A_00_OI :: STATUS :: F1B_FIFO_UNDERFLOW [10:10] */
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_UNDERFLOW_MASK             0x00000400
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_UNDERFLOW_SHIFT            10
#define BCHP_DS_A_00_OI_STATUS_F1B_FIFO_UNDERFLOW_DEFAULT          0x00000000

/* DS_A_00_OI :: STATUS :: ERR_BIT_FIFO_OVERFLOW [09:09] */
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_OVERFLOW_MASK          0x00000200
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_OVERFLOW_SHIFT         9
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_OVERFLOW_DEFAULT       0x00000000

/* DS_A_00_OI :: STATUS :: ERR_BIT_FIFO_UNDERFLOW [08:08] */
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_UNDERFLOW_MASK         0x00000100
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_UNDERFLOW_SHIFT        8
#define BCHP_DS_A_00_OI_STATUS_ERR_BIT_FIFO_UNDERFLOW_DEFAULT      0x00000000

/* DS_A_00_OI :: STATUS :: BK_US_FIFO_OVERFLOW [07:07] */
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_OVERFLOW_MASK            0x00000080
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_OVERFLOW_SHIFT           7
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_OVERFLOW_DEFAULT         0x00000000

/* DS_A_00_OI :: STATUS :: BK_US_FIFO_UNDERFLOW [06:06] */
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_UNDERFLOW_MASK           0x00000040
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_UNDERFLOW_SHIFT          6
#define BCHP_DS_A_00_OI_STATUS_BK_US_FIFO_UNDERFLOW_DEFAULT        0x00000000

/* DS_A_00_OI :: STATUS :: PRI_US_FIFO_OVERFLOW [05:05] */
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_OVERFLOW_MASK           0x00000020
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_OVERFLOW_SHIFT          5
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_OVERFLOW_DEFAULT        0x00000000

/* DS_A_00_OI :: STATUS :: PRI_US_FIFO_UNDERFLOW [04:04] */
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_UNDERFLOW_MASK          0x00000010
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_UNDERFLOW_SHIFT         4
#define BCHP_DS_A_00_OI_STATUS_PRI_US_FIFO_UNDERFLOW_DEFAULT       0x00000000

/* DS_A_00_OI :: STATUS :: DATA_FIFO_OVERFLOW [03:03] */
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_OVERFLOW_MASK             0x00000008
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_OVERFLOW_SHIFT            3
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_OVERFLOW_DEFAULT          0x00000000

/* DS_A_00_OI :: STATUS :: DATA_FIFO_UNDERFLOW [02:02] */
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_UNDERFLOW_MASK            0x00000004
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_UNDERFLOW_SHIFT           2
#define BCHP_DS_A_00_OI_STATUS_DATA_FIFO_UNDERFLOW_DEFAULT         0x00000000

/* DS_A_00_OI :: STATUS :: NCO_FIFO_OVERFLOW [01:01] */
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_OVERFLOW_MASK              0x00000002
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_OVERFLOW_SHIFT             1
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_OVERFLOW_DEFAULT           0x00000000

/* DS_A_00_OI :: STATUS :: NCO_FIFO_UNDERFLOW [00:00] */
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_UNDERFLOW_MASK             0x00000001
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_UNDERFLOW_SHIFT            0
#define BCHP_DS_A_00_OI_STATUS_NCO_FIFO_UNDERFLOW_DEFAULT          0x00000000

/***************************************************************************
 *NCON - OI Clock Rate NCO Numerator
 ***************************************************************************/
/* DS_A_00_OI :: NCON :: reserved0 [31:24] */
#define BCHP_DS_A_00_OI_NCON_reserved0_MASK                        0xff000000
#define BCHP_DS_A_00_OI_NCON_reserved0_SHIFT                       24

/* DS_A_00_OI :: NCON :: FECOUT_NCON [23:00] */
#define BCHP_DS_A_00_OI_NCON_FECOUT_NCON_MASK                      0x00ffffff
#define BCHP_DS_A_00_OI_NCON_FECOUT_NCON_SHIFT                     0
#define BCHP_DS_A_00_OI_NCON_FECOUT_NCON_DEFAULT                   0x0000026d

/***************************************************************************
 *NCODL - OI Clock Rate NCO Delta
 ***************************************************************************/
/* DS_A_00_OI :: NCODL :: reserved0 [31:24] */
#define BCHP_DS_A_00_OI_NCODL_reserved0_MASK                       0xff000000
#define BCHP_DS_A_00_OI_NCODL_reserved0_SHIFT                      24

/* DS_A_00_OI :: NCODL :: FECOUT_NCODL [23:00] */
#define BCHP_DS_A_00_OI_NCODL_FECOUT_NCODL_MASK                    0x00ffffff
#define BCHP_DS_A_00_OI_NCODL_FECOUT_NCODL_SHIFT                   0
#define BCHP_DS_A_00_OI_NCODL_FECOUT_NCODL_DEFAULT                 0x00000277

/***************************************************************************
 *FIFO_CTL - FIFO control
 ***************************************************************************/
/* DS_A_00_OI :: FIFO_CTL :: NZS [31:27] */
#define BCHP_DS_A_00_OI_FIFO_CTL_NZS_MASK                          0xf8000000
#define BCHP_DS_A_00_OI_FIFO_CTL_NZS_SHIFT                         27
#define BCHP_DS_A_00_OI_FIFO_CTL_NZS_DEFAULT                       0x00000000

/* DS_A_00_OI :: FIFO_CTL :: FIFO_ERR_NO_DVLD [26:26] */
#define BCHP_DS_A_00_OI_FIFO_CTL_FIFO_ERR_NO_DVLD_MASK             0x04000000
#define BCHP_DS_A_00_OI_FIFO_CTL_FIFO_ERR_NO_DVLD_SHIFT            26
#define BCHP_DS_A_00_OI_FIFO_CTL_FIFO_ERR_NO_DVLD_DEFAULT          0x00000000

/* DS_A_00_OI :: FIFO_CTL :: DISABLE_LOCK [25:25] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DISABLE_LOCK_MASK                 0x02000000
#define BCHP_DS_A_00_OI_FIFO_CTL_DISABLE_LOCK_SHIFT                25
#define BCHP_DS_A_00_OI_FIFO_CTL_DISABLE_LOCK_DEFAULT              0x00000000

/* DS_A_00_OI :: FIFO_CTL :: HDR_ERR_STS_CLR [24:24] */
#define BCHP_DS_A_00_OI_FIFO_CTL_HDR_ERR_STS_CLR_MASK              0x01000000
#define BCHP_DS_A_00_OI_FIFO_CTL_HDR_ERR_STS_CLR_SHIFT             24
#define BCHP_DS_A_00_OI_FIFO_CTL_HDR_ERR_STS_CLR_DEFAULT           0x00000000

/* DS_A_00_OI :: FIFO_CTL :: NCO_FIFO_ERR_RESYNC_EN [23:23] */
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_ERR_RESYNC_EN_MASK       0x00800000
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_ERR_RESYNC_EN_SHIFT      23
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_ERR_RESYNC_EN_DEFAULT    0x00000001

/* DS_A_00_OI :: FIFO_CTL :: DATA_FIFO_ERR_RESYNC_EN [22:22] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_ERR_RESYNC_EN_MASK      0x00400000
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_ERR_RESYNC_EN_SHIFT     22
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_ERR_RESYNC_EN_DEFAULT   0x00000001

/* DS_A_00_OI :: FIFO_CTL :: DATA_FIFO_HE_RESYNC_EN [21:21] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_HE_RESYNC_EN_MASK       0x00200000
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_HE_RESYNC_EN_SHIFT      21
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_HE_RESYNC_EN_DEFAULT    0x00000000

/* DS_A_00_OI :: FIFO_CTL :: DATA_FIFO_LS_RESYNC_EN [20:20] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_LS_RESYNC_EN_MASK       0x00100000
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_LS_RESYNC_EN_SHIFT      20
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_LS_RESYNC_EN_DEFAULT    0x00000001

/* DS_A_00_OI :: FIFO_CTL :: ECO_SPARE_0 [19:19] */
#define BCHP_DS_A_00_OI_FIFO_CTL_ECO_SPARE_0_MASK                  0x00080000
#define BCHP_DS_A_00_OI_FIFO_CTL_ECO_SPARE_0_SHIFT                 19
#define BCHP_DS_A_00_OI_FIFO_CTL_ECO_SPARE_0_DEFAULT               0x00000000

/* DS_A_00_OI :: FIFO_CTL :: FEC_LS_STS_CLR [18:18] */
#define BCHP_DS_A_00_OI_FIFO_CTL_FEC_LS_STS_CLR_MASK               0x00040000
#define BCHP_DS_A_00_OI_FIFO_CTL_FEC_LS_STS_CLR_SHIFT              18
#define BCHP_DS_A_00_OI_FIFO_CTL_FEC_LS_STS_CLR_DEFAULT            0x00000000

/* DS_A_00_OI :: FIFO_CTL :: NCO_FIFO_EN [17:17] */
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_EN_MASK                  0x00020000
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_EN_SHIFT                 17
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_EN_DEFAULT               0x00000000

/* DS_A_00_OI :: FIFO_CTL :: DATA_FIFO_EN [16:16] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_EN_MASK                 0x00010000
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_EN_SHIFT                16
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_EN_DEFAULT              0x00000000

/* DS_A_00_OI :: FIFO_CTL :: NCO_FIFO_THR [15:08] */
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_THR_MASK                 0x0000ff00
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_THR_SHIFT                8
#define BCHP_DS_A_00_OI_FIFO_CTL_NCO_FIFO_THR_DEFAULT              0x00000060

/* DS_A_00_OI :: FIFO_CTL :: DATA_FIFO_THR [07:00] */
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_THR_MASK                0x000000ff
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_THR_SHIFT               0
#define BCHP_DS_A_00_OI_FIFO_CTL_DATA_FIFO_THR_DEFAULT             0x00000080

/***************************************************************************
 *CTL - OI Control
 ***************************************************************************/
/* DS_A_00_OI :: CTL :: RESET_DATA [31:31] */
#define BCHP_DS_A_00_OI_CTL_RESET_DATA_MASK                        0x80000000
#define BCHP_DS_A_00_OI_CTL_RESET_DATA_SHIFT                       31
#define BCHP_DS_A_00_OI_CTL_RESET_DATA_DEFAULT                     0x00000000

/* DS_A_00_OI :: CTL :: RESET [30:30] */
#define BCHP_DS_A_00_OI_CTL_RESET_MASK                             0x40000000
#define BCHP_DS_A_00_OI_CTL_RESET_SHIFT                            30
#define BCHP_DS_A_00_OI_CTL_RESET_DEFAULT                          0x00000000

/* DS_A_00_OI :: CTL :: reserved0 [29:28] */
#define BCHP_DS_A_00_OI_CTL_reserved0_MASK                         0x30000000
#define BCHP_DS_A_00_OI_CTL_reserved0_SHIFT                        28

/* DS_A_00_OI :: CTL :: NEW_FIFO_SEL [27:27] */
#define BCHP_DS_A_00_OI_CTL_NEW_FIFO_SEL_MASK                      0x08000000
#define BCHP_DS_A_00_OI_CTL_NEW_FIFO_SEL_SHIFT                     27
#define BCHP_DS_A_00_OI_CTL_NEW_FIFO_SEL_DEFAULT                   0x00000001

/* DS_A_00_OI :: CTL :: TOP_RESET [26:26] */
#define BCHP_DS_A_00_OI_CTL_TOP_RESET_MASK                         0x04000000
#define BCHP_DS_A_00_OI_CTL_TOP_RESET_SHIFT                        26
#define BCHP_DS_A_00_OI_CTL_TOP_RESET_DEFAULT                      0x00000000

/* DS_A_00_OI :: CTL :: PN_RST [25:25] */
#define BCHP_DS_A_00_OI_CTL_PN_RST_MASK                            0x02000000
#define BCHP_DS_A_00_OI_CTL_PN_RST_SHIFT                           25
#define BCHP_DS_A_00_OI_CTL_PN_RST_DEFAULT                         0x00000000

/* DS_A_00_OI :: CTL :: PN_EN [24:24] */
#define BCHP_DS_A_00_OI_CTL_PN_EN_MASK                             0x01000000
#define BCHP_DS_A_00_OI_CTL_PN_EN_SHIFT                            24
#define BCHP_DS_A_00_OI_CTL_PN_EN_DEFAULT                          0x00000000

/* DS_A_00_OI :: CTL :: reserved1 [23:20] */
#define BCHP_DS_A_00_OI_CTL_reserved1_MASK                         0x00f00000
#define BCHP_DS_A_00_OI_CTL_reserved1_SHIFT                        20

/* DS_A_00_OI :: CTL :: DELH [19:19] */
#define BCHP_DS_A_00_OI_CTL_DELH_MASK                              0x00080000
#define BCHP_DS_A_00_OI_CTL_DELH_SHIFT                             19
#define BCHP_DS_A_00_OI_CTL_DELH_DEFAULT                           0x00000000

/* DS_A_00_OI :: CTL :: HEADER4 [18:18] */
#define BCHP_DS_A_00_OI_CTL_HEADER4_MASK                           0x00040000
#define BCHP_DS_A_00_OI_CTL_HEADER4_SHIFT                          18
#define BCHP_DS_A_00_OI_CTL_HEADER4_DEFAULT                        0x00000000

/* DS_A_00_OI :: CTL :: SYNC1 [17:17] */
#define BCHP_DS_A_00_OI_CTL_SYNC1_MASK                             0x00020000
#define BCHP_DS_A_00_OI_CTL_SYNC1_SHIFT                            17
#define BCHP_DS_A_00_OI_CTL_SYNC1_DEFAULT                          0x00000000

/* DS_A_00_OI :: CTL :: reserved2 [16:16] */
#define BCHP_DS_A_00_OI_CTL_reserved2_MASK                         0x00010000
#define BCHP_DS_A_00_OI_CTL_reserved2_SHIFT                        16

/* DS_A_00_OI :: CTL :: IVD_DA_SUP [15:15] */
#define BCHP_DS_A_00_OI_CTL_IVD_DA_SUP_MASK                        0x00008000
#define BCHP_DS_A_00_OI_CTL_IVD_DA_SUP_SHIFT                       15
#define BCHP_DS_A_00_OI_CTL_IVD_DA_SUP_DEFAULT                     0x00000000

/* DS_A_00_OI :: CTL :: IVD_CK_SUP [14:14] */
#define BCHP_DS_A_00_OI_CTL_IVD_CK_SUP_MASK                        0x00004000
#define BCHP_DS_A_00_OI_CTL_IVD_CK_SUP_SHIFT                       14
#define BCHP_DS_A_00_OI_CTL_IVD_CK_SUP_DEFAULT                     0x00000000

/* DS_A_00_OI :: CTL :: ERR_CK_SUP [13:13] */
#define BCHP_DS_A_00_OI_CTL_ERR_CK_SUP_MASK                        0x00002000
#define BCHP_DS_A_00_OI_CTL_ERR_CK_SUP_SHIFT                       13
#define BCHP_DS_A_00_OI_CTL_ERR_CK_SUP_DEFAULT                     0x00000000

/* DS_A_00_OI :: CTL :: SY_CK_SUP [12:12] */
#define BCHP_DS_A_00_OI_CTL_SY_CK_SUP_MASK                         0x00001000
#define BCHP_DS_A_00_OI_CTL_SY_CK_SUP_SHIFT                        12
#define BCHP_DS_A_00_OI_CTL_SY_CK_SUP_DEFAULT                      0x00000000

/* DS_A_00_OI :: CTL :: ERR_SY_SUP [11:11] */
#define BCHP_DS_A_00_OI_CTL_ERR_SY_SUP_MASK                        0x00000800
#define BCHP_DS_A_00_OI_CTL_ERR_SY_SUP_SHIFT                       11
#define BCHP_DS_A_00_OI_CTL_ERR_SY_SUP_DEFAULT                     0x00000000

/* DS_A_00_OI :: CTL :: reserved3 [10:08] */
#define BCHP_DS_A_00_OI_CTL_reserved3_MASK                         0x00000700
#define BCHP_DS_A_00_OI_CTL_reserved3_SHIFT                        8

/* DS_A_00_OI :: CTL :: INV_ERR [07:07] */
#define BCHP_DS_A_00_OI_CTL_INV_ERR_MASK                           0x00000080
#define BCHP_DS_A_00_OI_CTL_INV_ERR_SHIFT                          7
#define BCHP_DS_A_00_OI_CTL_INV_ERR_DEFAULT                        0x00000000

/* DS_A_00_OI :: CTL :: INV_SYN [06:06] */
#define BCHP_DS_A_00_OI_CTL_INV_SYN_MASK                           0x00000040
#define BCHP_DS_A_00_OI_CTL_INV_SYN_SHIFT                          6
#define BCHP_DS_A_00_OI_CTL_INV_SYN_DEFAULT                        0x00000000

/* DS_A_00_OI :: CTL :: INV_VAL [05:05] */
#define BCHP_DS_A_00_OI_CTL_INV_VAL_MASK                           0x00000020
#define BCHP_DS_A_00_OI_CTL_INV_VAL_SHIFT                          5
#define BCHP_DS_A_00_OI_CTL_INV_VAL_DEFAULT                        0x00000000

/* DS_A_00_OI :: CTL :: INV_CLK [04:04] */
#define BCHP_DS_A_00_OI_CTL_INV_CLK_MASK                           0x00000010
#define BCHP_DS_A_00_OI_CTL_INV_CLK_SHIFT                          4
#define BCHP_DS_A_00_OI_CTL_INV_CLK_DEFAULT                        0x00000000

/* DS_A_00_OI :: CTL :: LFSR_XMT_EN [03:03] */
#define BCHP_DS_A_00_OI_CTL_LFSR_XMT_EN_MASK                       0x00000008
#define BCHP_DS_A_00_OI_CTL_LFSR_XMT_EN_SHIFT                      3
#define BCHP_DS_A_00_OI_CTL_LFSR_XMT_EN_DEFAULT                    0x00000000

/* DS_A_00_OI :: CTL :: TOGGLE_EN [02:02] */
#define BCHP_DS_A_00_OI_CTL_TOGGLE_EN_MASK                         0x00000004
#define BCHP_DS_A_00_OI_CTL_TOGGLE_EN_SHIFT                        2
#define BCHP_DS_A_00_OI_CTL_TOGGLE_EN_DEFAULT                      0x00000000

/* DS_A_00_OI :: CTL :: STD_P_CLK [01:01] */
#define BCHP_DS_A_00_OI_CTL_STD_P_CLK_MASK                         0x00000002
#define BCHP_DS_A_00_OI_CTL_STD_P_CLK_SHIFT                        1
#define BCHP_DS_A_00_OI_CTL_STD_P_CLK_DEFAULT                      0x00000001

/* DS_A_00_OI :: CTL :: SERIAL [00:00] */
#define BCHP_DS_A_00_OI_CTL_SERIAL_MASK                            0x00000001
#define BCHP_DS_A_00_OI_CTL_SERIAL_SHIFT                           0
#define BCHP_DS_A_00_OI_CTL_SERIAL_DEFAULT                         0x00000001

/***************************************************************************
 *OUT - OI Output override Control
 ***************************************************************************/
/* DS_A_00_OI :: OUT :: BERT_HEADER4 [31:31] */
#define BCHP_DS_A_00_OI_OUT_BERT_HEADER4_MASK                      0x80000000
#define BCHP_DS_A_00_OI_OUT_BERT_HEADER4_SHIFT                     31
#define BCHP_DS_A_00_OI_OUT_BERT_HEADER4_DEFAULT                   0x00000000

/* DS_A_00_OI :: OUT :: ECO_SPARE_1 [30:28] */
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_1_MASK                       0x70000000
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_1_SHIFT                      28
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_1_DEFAULT                    0x00000000

/* DS_A_00_OI :: OUT :: CTL_ERR [27:27] */
#define BCHP_DS_A_00_OI_OUT_CTL_ERR_MASK                           0x08000000
#define BCHP_DS_A_00_OI_OUT_CTL_ERR_SHIFT                          27
#define BCHP_DS_A_00_OI_OUT_CTL_ERR_DEFAULT                        0x00000001

/* DS_A_00_OI :: OUT :: CTL_SYN [26:26] */
#define BCHP_DS_A_00_OI_OUT_CTL_SYN_MASK                           0x04000000
#define BCHP_DS_A_00_OI_OUT_CTL_SYN_SHIFT                          26
#define BCHP_DS_A_00_OI_OUT_CTL_SYN_DEFAULT                        0x00000001

/* DS_A_00_OI :: OUT :: CTL_VAL [25:25] */
#define BCHP_DS_A_00_OI_OUT_CTL_VAL_MASK                           0x02000000
#define BCHP_DS_A_00_OI_OUT_CTL_VAL_SHIFT                          25
#define BCHP_DS_A_00_OI_OUT_CTL_VAL_DEFAULT                        0x00000001

/* DS_A_00_OI :: OUT :: CTL_CLK [24:24] */
#define BCHP_DS_A_00_OI_OUT_CTL_CLK_MASK                           0x01000000
#define BCHP_DS_A_00_OI_OUT_CTL_CLK_SHIFT                          24
#define BCHP_DS_A_00_OI_OUT_CTL_CLK_DEFAULT                        0x00000001

/* DS_A_00_OI :: OUT :: CTL_DATA [23:16] */
#define BCHP_DS_A_00_OI_OUT_CTL_DATA_MASK                          0x00ff0000
#define BCHP_DS_A_00_OI_OUT_CTL_DATA_SHIFT                         16
#define BCHP_DS_A_00_OI_OUT_CTL_DATA_DEFAULT                       0x000000ff

/* DS_A_00_OI :: OUT :: ECO_SPARE_0 [15:12] */
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_0_MASK                       0x0000f000
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_0_SHIFT                      12
#define BCHP_DS_A_00_OI_OUT_ECO_SPARE_0_DEFAULT                    0x00000000

/* DS_A_00_OI :: OUT :: ERR_STATE [11:11] */
#define BCHP_DS_A_00_OI_OUT_ERR_STATE_MASK                         0x00000800
#define BCHP_DS_A_00_OI_OUT_ERR_STATE_SHIFT                        11
#define BCHP_DS_A_00_OI_OUT_ERR_STATE_DEFAULT                      0x00000000

/* DS_A_00_OI :: OUT :: SYN_STATE [10:10] */
#define BCHP_DS_A_00_OI_OUT_SYN_STATE_MASK                         0x00000400
#define BCHP_DS_A_00_OI_OUT_SYN_STATE_SHIFT                        10
#define BCHP_DS_A_00_OI_OUT_SYN_STATE_DEFAULT                      0x00000000

/* DS_A_00_OI :: OUT :: VAL_STATE [09:09] */
#define BCHP_DS_A_00_OI_OUT_VAL_STATE_MASK                         0x00000200
#define BCHP_DS_A_00_OI_OUT_VAL_STATE_SHIFT                        9
#define BCHP_DS_A_00_OI_OUT_VAL_STATE_DEFAULT                      0x00000000

/* DS_A_00_OI :: OUT :: CLK_STATE [08:08] */
#define BCHP_DS_A_00_OI_OUT_CLK_STATE_MASK                         0x00000100
#define BCHP_DS_A_00_OI_OUT_CLK_STATE_SHIFT                        8
#define BCHP_DS_A_00_OI_OUT_CLK_STATE_DEFAULT                      0x00000000

/* DS_A_00_OI :: OUT :: DATA_STATE [07:00] */
#define BCHP_DS_A_00_OI_OUT_DATA_STATE_MASK                        0x000000ff
#define BCHP_DS_A_00_OI_OUT_DATA_STATE_SHIFT                       0
#define BCHP_DS_A_00_OI_OUT_DATA_STATE_DEFAULT                     0x00000000

/***************************************************************************
 *MPEG_CNT - OI MPEG Count
 ***************************************************************************/
/* DS_A_00_OI :: MPEG_CNT :: mpeg_errcnt [31:16] */
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_errcnt_MASK                  0xffff0000
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_errcnt_SHIFT                 16
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_errcnt_DEFAULT               0x00000000

/* DS_A_00_OI :: MPEG_CNT :: mpeg_cnt [15:00] */
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_cnt_MASK                     0x0000ffff
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_cnt_SHIFT                    0
#define BCHP_DS_A_00_OI_MPEG_CNT_mpeg_cnt_DEFAULT                  0x00000000

/***************************************************************************
 *BERT_CTL - OI BERT Control Register
 ***************************************************************************/
/* DS_A_00_OI :: BERT_CTL :: reserved0 [31:20] */
#define BCHP_DS_A_00_OI_BERT_CTL_reserved0_MASK                    0xfff00000
#define BCHP_DS_A_00_OI_BERT_CTL_reserved0_SHIFT                   20

/* DS_A_00_OI :: BERT_CTL :: BERT_SNAP_MODE [19:19] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_MODE_MASK               0x00080000
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_MODE_SHIFT              19
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_MODE_DEFAULT            0x00000000

/* DS_A_00_OI :: BERT_CTL :: BERT_SNAP [18:18] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_MASK                    0x00040000
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_SHIFT                   18
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_SNAP_DEFAULT                 0x00000000

/* DS_A_00_OI :: BERT_CTL :: BERT_MODE [17:16] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_MODE_MASK                    0x00030000
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_MODE_SHIFT                   16
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_MODE_DEFAULT                 0x00000000

/* DS_A_00_OI :: BERT_CTL :: reserved1 [15:10] */
#define BCHP_DS_A_00_OI_BERT_CTL_reserved1_MASK                    0x0000fc00
#define BCHP_DS_A_00_OI_BERT_CTL_reserved1_SHIFT                   10

/* DS_A_00_OI :: BERT_CTL :: BERT_INV [09:09] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_INV_MASK                     0x00000200
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_INV_SHIFT                    9
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_INV_DEFAULT                  0x00000001

/* DS_A_00_OI :: BERT_CTL :: BERT_CNT_RST [08:08] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_CNT_RST_MASK                 0x00000100
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_CNT_RST_SHIFT                8
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_CNT_RST_DEFAULT              0x00000000

/* DS_A_00_OI :: BERT_CTL :: reserved2 [07:02] */
#define BCHP_DS_A_00_OI_BERT_CTL_reserved2_MASK                    0x000000fc
#define BCHP_DS_A_00_OI_BERT_CTL_reserved2_SHIFT                   2

/* DS_A_00_OI :: BERT_CTL :: BERT_EN [01:01] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_EN_MASK                      0x00000002
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_EN_SHIFT                     1
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_EN_DEFAULT                   0x00000000

/* DS_A_00_OI :: BERT_CTL :: BERT_RST [00:00] */
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_RST_MASK                     0x00000001
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_RST_SHIFT                    0
#define BCHP_DS_A_00_OI_BERT_CTL_BERT_RST_DEFAULT                  0x00000000

/***************************************************************************
 *BERT_IT - OI BERT integration period and threshold
 ***************************************************************************/
/* DS_A_00_OI :: BERT_IT :: iperiod [31:16] */
#define BCHP_DS_A_00_OI_BERT_IT_iperiod_MASK                       0xffff0000
#define BCHP_DS_A_00_OI_BERT_IT_iperiod_SHIFT                      16
#define BCHP_DS_A_00_OI_BERT_IT_iperiod_DEFAULT                    0x000000ff

/* DS_A_00_OI :: BERT_IT :: threshold [15:00] */
#define BCHP_DS_A_00_OI_BERT_IT_threshold_MASK                     0x0000ffff
#define BCHP_DS_A_00_OI_BERT_IT_threshold_SHIFT                    0
#define BCHP_DS_A_00_OI_BERT_IT_threshold_DEFAULT                  0x0000003f

/***************************************************************************
 *BERT_BIT_CNT_H - OI BERT bit Counter snapshot value, higher bits
 ***************************************************************************/
/* DS_A_00_OI :: BERT_BIT_CNT_H :: reserved0 [31:16] */
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H_reserved0_MASK              0xffff0000
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H_reserved0_SHIFT             16

/* DS_A_00_OI :: BERT_BIT_CNT_H :: bert_bit_cnt_ss_h [15:00] */
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H_bert_bit_cnt_ss_h_MASK      0x0000ffff
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H_bert_bit_cnt_ss_h_SHIFT     0
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_H_bert_bit_cnt_ss_h_DEFAULT   0x00000000

/***************************************************************************
 *BERT_BIT_CNT_L - OI BERT bit Counter snapshot value, lower bits
 ***************************************************************************/
/* DS_A_00_OI :: BERT_BIT_CNT_L :: bert_bit_cnt_ss_l [31:00] */
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_L_bert_bit_cnt_ss_l_MASK      0xffffffff
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_L_bert_bit_cnt_ss_l_SHIFT     0
#define BCHP_DS_A_00_OI_BERT_BIT_CNT_L_bert_bit_cnt_ss_l_DEFAULT   0x00000000

/***************************************************************************
 *BERT_ERR_CNT_H - OI BERT error Counter snapshot value, higher bits
 ***************************************************************************/
/* DS_A_00_OI :: BERT_ERR_CNT_H :: reserved0 [31:08] */
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H_reserved0_MASK              0xffffff00
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H_reserved0_SHIFT             8

/* DS_A_00_OI :: BERT_ERR_CNT_H :: bert_err_cnt_ss_h [07:00] */
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H_bert_err_cnt_ss_h_MASK      0x000000ff
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H_bert_err_cnt_ss_h_SHIFT     0
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_H_bert_err_cnt_ss_h_DEFAULT   0x00000000

/***************************************************************************
 *BERT_ERR_CNT_L - OI BERT error Counter snapshot value, lower bits
 ***************************************************************************/
/* DS_A_00_OI :: BERT_ERR_CNT_L :: bert_err_cnt_ss_l [31:00] */
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_L_bert_err_cnt_ss_l_MASK      0xffffffff
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_L_bert_err_cnt_ss_l_SHIFT     0
#define BCHP_DS_A_00_OI_BERT_ERR_CNT_L_bert_err_cnt_ss_l_DEFAULT   0x00000000

/***************************************************************************
 *BERT_ST - OI BERT status register
 ***************************************************************************/
/* DS_A_00_OI :: BERT_ST :: reserved0 [31:28] */
#define BCHP_DS_A_00_OI_BERT_ST_reserved0_MASK                     0xf0000000
#define BCHP_DS_A_00_OI_BERT_ST_reserved0_SHIFT                    28

/* DS_A_00_OI :: BERT_ST :: bert_sync_rise_ss [27:27] */
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_rise_ss_MASK             0x08000000
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_rise_ss_SHIFT            27
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_rise_ss_DEFAULT          0x00000000

/* DS_A_00_OI :: BERT_ST :: bert_sync_fall_ss [26:26] */
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_fall_ss_MASK             0x04000000
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_fall_ss_SHIFT            26
#define BCHP_DS_A_00_OI_BERT_ST_bert_sync_fall_ss_DEFAULT          0x00000000

/* DS_A_00_OI :: BERT_ST :: sync [25:25] */
#define BCHP_DS_A_00_OI_BERT_ST_sync_MASK                          0x02000000
#define BCHP_DS_A_00_OI_BERT_ST_sync_SHIFT                         25
#define BCHP_DS_A_00_OI_BERT_ST_sync_DEFAULT                       0x00000000

/* DS_A_00_OI :: BERT_ST :: reserved1 [24:00] */
#define BCHP_DS_A_00_OI_BERT_ST_reserved1_MASK                     0x01ffffff
#define BCHP_DS_A_00_OI_BERT_ST_reserved1_SHIFT                    0

#endif /* #ifndef BCHP_DS_A_00_OI_H__ */

/* End of File */
