#!/bin/bash

CVS_ROOT=/projects/cvsroot/CVSROOT

# define a directory to hold the logs
LOG_DIR=/home/pmoutarl/logdir


# touching some files to make sure they exist
touch "$LOG_DIR/linux.log"
touch $LOG_DIR/src.log
touch $LOG_DIR/prev_logs

# move previous logs
mv $LOG_DIR/linux.log $LOG_DIR/linux_prev.log 
mv $LOG_DIR/src.log $LOG_DIR/src_prev.log

# save current logs
cp $CVS_ROOT/linux.log $LOG_DIR/linux.log
cp $CVS_ROOT/src.log $LOG_DIR/src.log

# if not accumulating, delete previous logs
if [ "$1" != "-a" ]; then
    rm $LOG_DIR/prev_logs 
    touch $LOG_DIR/prev_logs
else
# if accumulating, save previous logs
    mv $LOG_DIR/latest_logs $LOG_DIR/prev_logs
fi

# run diffs between previous and current
diff  $LOG_DIR/linux.log $LOG_DIR/linux_prev.log > $LOG_DIR/tmp
diff  $LOG_DIR/src.log $LOG_DIR/src_prev.log >> $LOG_DIR/tmp

# elminate logs which disapeared since last time. They are due to 
# truncation
grep ^\< $LOG_DIR/tmp > $LOG_DIR/tmp2

# cat with previous logs
cat $LOG_DIR/prev_logs $LOG_DIR/tmp2 > $LOG_DIR/latest_logs

