/*******************************************************************************
 * Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/


#define BDSP_IMG_AACHEADTS_IDS_INTER_FRAME_SIZE                      ((uint32_t)16960)
#define BDSP_IMG_AACHEADTS_IDS_SIZE                                  ((uint32_t)33576)
#define BDSP_IMG_AACHELOAS_IDS_INTER_FRAME_SIZE                      ((uint32_t)16960)
#define BDSP_IMG_AACHELOAS_IDS_SIZE                                  ((uint32_t)35104)
#define BDSP_IMG_CDB_PASSTHRU_CODE_SIZE                              ((uint32_t)31576)
#define BDSP_IMG_CDB_PASSTHRU_INTER_FRAME_SIZE                       ((uint32_t)852)
#define BDSP_IMG_CDB_PASSTHRU_TABLES_SIZE                            ((uint32_t)640)
#define BDSP_IMG_DOLBY_AACHE_DECODE_INTER_FRAME_SIZE                 ((uint32_t)211772)
#define BDSP_IMG_DOLBY_AACHE_DECODE_SIZE                             ((uint32_t)244184)
#define BDSP_IMG_DOLBY_AACHE_DECODE_TABLES_SIZE                      ((uint32_t)640)
#define BDSP_IMG_MPEG1_DECODE_INTER_FRAME_SIZE                       ((uint32_t)9300)
#define BDSP_IMG_MPEG1_DECODE_SIZE                                   ((uint32_t)55572)
#define BDSP_IMG_MPEG1_DECODE_TABLES_SIZE                            ((uint32_t)640)
#define BDSP_IMG_MPEG1_IDS_INTER_FRAME_SIZE                          ((uint32_t)16960)
#define BDSP_IMG_MPEG1_IDS_SIZE                                      ((uint32_t)39616)
#define BDSP_IMG_PCMWAV_DECODE_INTER_FRAME_SIZE                      ((uint32_t)56)
#define BDSP_IMG_PCMWAV_DECODE_SIZE                                  ((uint32_t)14684)
#define BDSP_IMG_PCMWAV_DECODE_TABLES_SIZE                           ((uint32_t)640)
#define BDSP_IMG_PCMWAV_IDS_INTER_FRAME_SIZE                         ((uint32_t)16960)
#define BDSP_IMG_PCMWAV_IDS_SIZE                                     ((uint32_t)34872)
#define BDSP_IMG_SRC_CODE_SIZE                                       ((uint32_t)23436)
#define BDSP_IMG_SRC_INTER_FRAME_SIZE                                ((uint32_t)13028)
#define BDSP_IMG_SRC_TABLES_SIZE                                     ((uint32_t)640)
#define BDSP_IMG_SYSTEM_KERNEL_SIZE                                  ((uint32_t)180736)
#define BDSP_IMG_SYSTEM_ROMFS_SIZE                                   ((uint32_t)818180)
#define BDSP_IMG_UDC_DECODE_INTER_FRAME_SIZE                         ((uint32_t)566488)
#define BDSP_IMG_UDC_DECODE_SIZE                                     ((uint32_t)236664)
#define BDSP_IMG_UDC_DECODE_TABLES_SIZE                              ((uint32_t)640)
#define BDSP_IMG_UDC_IDS_INTER_FRAME_SIZE                            ((uint32_t)16960)
#define BDSP_IMG_UDC_IDS_SIZE                                        ((uint32_t)40912)
#define BDSP_IMG_VIDIDSCOMMON_CODE_SIZE                              ((uint32_t)11772)
#define BDSP_IMG_VIDIDSCOMMON_INTER_FRAME_SIZE                       ((uint32_t)2208)
#define BDSP_IMG_SYSTEM_RDBVARS_SIZE                               	 ((uint32_t)1024)
#define BDSP_IMG_KERNEL_RW_IMG_SIZE                               	 ((uint32_t)4321280)
#define BDSP_TB_BUF_START_ADDR                               		 ((uint32_t)0x10001a80)
#define BDSP_TB_BUF_MEM_SIZE                               			 ((uint32_t)4194304)
#define BDSP_IMG_AACHE_DECODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_AACHE_DECODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_AACHE_DECODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AACHE_ENCODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_AACHE_ENCODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_AACHE_ENCODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AC3_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_AC3_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_AC3_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_AC3_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AC3_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_AC4_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_AC4_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_AC4_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_AC4_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AC4_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_ADPCM_DECODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_ADPCM_DECODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_ADPCM_DECODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_ALGOLIB_CODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_ALS_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_ALS_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_ALS_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_ALS_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_ALS_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_AMRWB_DECODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_AMRWB_DECODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_AMRWB_DECODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AMRWB_ENCODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_AMRWB_ENCODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_AMRWB_ENCODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_AMR_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_AMR_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_AMR_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_AMR_ENCODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_AMR_ENCODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_AMR_ENCODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_BRCM_3DSURROUND_CODE_SIZE                           ((uint32_t)0)
#define BDSP_IMG_BRCM_3DSURROUND_INTER_FRAME_SIZE                    ((uint32_t)0)
#define BDSP_IMG_BRCM_3DSURROUND_TABLES_SIZE                         ((uint32_t)0)
#define BDSP_IMG_BRCM_AVL_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_BRCM_AVL_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_BRCM_AVL_TABLES_SIZE                                ((uint32_t)0)
#define BDSP_IMG_BTSCENC_CODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_BTSCENC_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_BTSCENC_TABLES_SIZE                                 ((uint32_t)0)
#define BDSP_IMG_CUSTOMVOICE_CODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_CUSTOMVOICE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_CUSTOMVOICE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_DDP_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_DDP_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DDP_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DDP_ENCODE_CODE_SIZE                                ((uint32_t)0)
#define BDSP_IMG_DDP_ENCODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_DDP_ENCODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DPCMR_CODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DPCMR_INTER_FRAME_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DPCMR_TABLES_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_MIXER_DAPV2_CODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_MIXER_DAPV2_IDS_INTER_FRAME_SIZE                    ((uint32_t)0)
#define BDSP_IMG_MIXER_DAPV2_IDS_SIZE                                ((uint32_t)0)
#define BDSP_IMG_MIXER_DAPV2_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_MIXER_DAPV2_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_DDRE_CODE_SIZE                                      ((uint32_t)0)
#define BDSP_IMG_DDRE_INTER_FRAME_SIZE                               ((uint32_t)0)
#define BDSP_IMG_DDRE_TABLES_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_DD_TRANSCODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_DD_TRANSCODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_DD_TRANSCODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DOLBY_MS_DDP_DECODE_INTER_FRAME_SIZE                ((uint32_t)0)
#define BDSP_IMG_DOLBY_MS_DDP_DECODE_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DOLBY_MS_DDP_DECODE_TABLES_SIZE                     ((uint32_t)0)
#define BDSP_IMG_DOLBY_PULSE_DECODE_INTER_FRAME_SIZE                 ((uint32_t)0)
#define BDSP_IMG_DOLBY_PULSE_DECODE_SIZE                             ((uint32_t)0)
#define BDSP_IMG_DOLBY_PULSE_DECODE_TABLES_SIZE                      ((uint32_t)0)
#define BDSP_IMG_DRA_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_DRA_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DRA_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DRA_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DRA_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_DSOLA_CODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DSOLA_INTER_FRAME_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DSOLA_TABLES_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_DTSHD_DECODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_DTSHD_DECODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_DTSHD_DECODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DTSHD_IDS_SIZE                                      ((uint32_t)0)
#define BDSP_IMG_DTS_ENCODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_DTS_ENCODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DTS_ENCODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DTS_EXPRESS_DECODE_INTER_FRAME_SIZE                 ((uint32_t)0)
#define BDSP_IMG_DTS_EXPRESS_DECODE_SIZE                             ((uint32_t)0)
#define BDSP_IMG_DTS_EXPRESS_DECODE_TABLES_SIZE                      ((uint32_t)0)
#define BDSP_IMG_DTS_EXPRESS_IDS_DECODE_SIZE                         ((uint32_t)0)
#define BDSP_IMG_DTS_EXPRESS_IDS_INTER_FRAME_SIZE                    ((uint32_t)0)
#define BDSP_IMG_DTS_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DTS_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_DV258_CODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_DV258_INTER_FRAME_SIZE                              ((uint32_t)0)
#define BDSP_IMG_DV258_TABLES_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_DVDLPCM_IDS_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_DVDLPCM_IDS_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_FADECTRL_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_FADECTRL_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_FADECTRL_TABLES_SIZE                                ((uint32_t)0)
#define BDSP_IMG_FLAC_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_FLAC_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_FLAC_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_FLAC_IDS_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_FLAC_IDS_SIZE                                       ((uint32_t)0)
#define BDSP_IMG_G711_G726_DECODE_INTER_FRAME_SIZE                   ((uint32_t)0)
#define BDSP_IMG_G711_G726_DECODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_G711_G726_DECODE_TABLES_SIZE                        ((uint32_t)0)
#define BDSP_IMG_G711_G726_ENCODE_INTER_FRAME_SIZE                   ((uint32_t)0)
#define BDSP_IMG_FW_MIXER_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_FW_MIXER_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_FW_MIXER_TABLES_SIZE                                ((uint32_t)0)
#define BDSP_IMG_GEN_CDBITB_CODE_SIZE                                ((uint32_t)0)
#define BDSP_IMG_GEN_CDBITB_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_GEN_CDBITB_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_MIXER_IDS_INTER_FRAME_SIZE                          ((uint32_t)0)
#define BDSP_IMG_MIXER_IDS_SIZE                                      ((uint32_t)0)
#define BDSP_IMG_G711_G726_ENCODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_G711_G726_ENCODE_TABLES_SIZE                        ((uint32_t)0)
#define BDSP_IMG_G722_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_G722_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_G722_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_G723_1_DECODE_INTER_FRAME_SIZE                      ((uint32_t)0)
#define BDSP_IMG_G723_1_DECODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_G723_1_DECODE_TABLES_SIZE                           ((uint32_t)0)
#define BDSP_IMG_G723_1_ENCODE_INTER_FRAME_SIZE                      ((uint32_t)0)
#define BDSP_IMG_G723_1_ENCODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_G723_1_ENCODE_TABLES_SIZE                           ((uint32_t)0)
#define BDSP_IMG_G729_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_G729_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_G729_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_G729_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_G729_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_G729_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_H264_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_H264_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_H264_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_IDSCOMMON_CODE_SIZE                                 ((uint32_t)0)
#define BDSP_IMG_ILBC_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_ILBC_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_ILBC_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_ILBC_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_ILBC_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_ILBC_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_ISAC_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_ISAC_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_ISAC_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_ISAC_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_ISAC_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_ISAC_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_KARAOKE_CODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_KARAOKE_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_KARAOKE_TABLES_SIZE                                 ((uint32_t)0)
#define BDSP_IMG_LPCM_DECODE_CODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_LPCM_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_LPCM_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_LPCM_ENCODE_CODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_LPCM_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_LPCM_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_MAC_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_MAC_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_MAC_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_MAC_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_MAC_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_MLP_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_MLP_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_MLP_PASSTHROUGH_CODE_SIZE                           ((uint32_t)0)
#define BDSP_IMG_MLP_PASSTHROUGH_INTER_FRAME_SIZE                    ((uint32_t)0)
#define BDSP_IMG_MLP_PASSTHROUGH_TABLES_SIZE                         ((uint32_t)0)
#define BDSP_IMG_MP3_ENCODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_MP3_ENCODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_MP3_ENCODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_OPUS_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_OPUS_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_OPUS_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_OPUS_ENCODE_CODE_SIZE                               ((uint32_t)0)
#define BDSP_IMG_OPUS_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_OPUS_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_OUTPUTFORMATTER_CODE_SIZE                           ((uint32_t)0)
#define BDSP_IMG_OUTPUTFORMATTER_INTER_FRAME_SIZE                    ((uint32_t)0)
#define BDSP_IMG_OUTPUTFORMATTER_TABLES_SIZE                         ((uint32_t)0)
#define BDSP_IMG_PCM_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_PCM_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_RALBR_DECODE_INTER_FRAME_SIZE                       ((uint32_t)0)
#define BDSP_IMG_RALBR_DECODE_SIZE                                   ((uint32_t)0)
#define BDSP_IMG_RALBR_DECODE_TABLES_SIZE                            ((uint32_t)0)
#define BDSP_IMG_RALBR_IDS_INTER_FRAME_SIZE                          ((uint32_t)0)
#define BDSP_IMG_RALBR_IDS_SIZE                                      ((uint32_t)0)
#define BDSP_IMG_SCM1_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_SCM1_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_SCM1_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_SCM2_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_SCM2_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_SCM2_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_SCM3_DECODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_SCM3_DECODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_SCM3_DECODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_SCM_TASK_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_SPEEXAEC_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_SPEEXAEC_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_SPEEXAEC_TABLES_SIZE                                ((uint32_t)0)
#define BDSP_IMG_SRS_TRUSURROUNDHD_CODE_SIZE                         ((uint32_t)0)
#define BDSP_IMG_SRS_TRUSURROUNDHD_INTER_FRAME_SIZE                  ((uint32_t)0)
#define BDSP_IMG_SRS_TRUSURROUNDHD_TABLES_SIZE                       ((uint32_t)0)
#define BDSP_IMG_SRS_TVOL_CODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_SRS_TVOL_INTER_FRAME_SIZE                           ((uint32_t)0)
#define BDSP_IMG_SRS_TVOL_TABLES_SIZE                                ((uint32_t)0)
#define BDSP_IMG_SYSLIB_CODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_SYSTEM_CODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_TRUEHD_DECODE_INTER_FRAME_SIZE                      ((uint32_t)0)
#define BDSP_IMG_TRUEHD_DECODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_TRUEHD_DECODE_TABLES_SIZE                           ((uint32_t)0)
#define BDSP_IMG_TSMCORRECTION_INTER_FRAME_SIZE                      ((uint32_t)0)
#define BDSP_IMG_TSMCORRECTION_CODE_SIZE                             ((uint32_t)0)
#define BDSP_IMG_TSMCORRECTION_TABLES_SIZE                           ((uint32_t)0)
#define BDSP_IMG_VIDEO_DECODE_TASK_CODE_SIZE                         ((uint32_t)0)
#define BDSP_IMG_VIDEO_ENCODE_TASK_CODE_SIZE                         ((uint32_t)0)
#define BDSP_IMG_VOCALS_CODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_VOCALS_INTER_FRAME_SIZE                             ((uint32_t)0)
#define BDSP_IMG_VOCALS_TABLES_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_VORBIS_DECODE_INTER_FRAME_SIZE                      ((uint32_t)0)
#define BDSP_IMG_VORBIS_DECODE_SIZE                                  ((uint32_t)0)
#define BDSP_IMG_VORBIS_DECODE_TABLES_SIZE                           ((uint32_t)0)
#define BDSP_IMG_VORBIS_IDS_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_VORBIS_IDS_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_VP6_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_VP6_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_VP6_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_VP6_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_VP6_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_WMA_DECODE_INTER_FRAME_SIZE                         ((uint32_t)0)
#define BDSP_IMG_WMA_DECODE_SIZE                                     ((uint32_t)0)
#define BDSP_IMG_WMA_DECODE_TABLES_SIZE                              ((uint32_t)0)
#define BDSP_IMG_WMA_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_WMA_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_WMA_PRO_DECODE_INTER_FRAME_SIZE                     ((uint32_t)0)
#define BDSP_IMG_WMA_PRO_DECODE_SIZE                                 ((uint32_t)0)
#define BDSP_IMG_WMA_PRO_DECODE_TABLES_SIZE                          ((uint32_t)0)
#define BDSP_IMG_WMA_PRO_IDS_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_WMA_PRO_IDS_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_X264_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_X264_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_X264_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_XVP8_ENCODE_INTER_FRAME_SIZE                        ((uint32_t)0)
#define BDSP_IMG_XVP8_ENCODE_SIZE                                    ((uint32_t)0)
#define BDSP_IMG_XVP8_ENCODE_TABLES_SIZE                             ((uint32_t)0)
#define BDSP_IMG_SYSTEM_SCM1_DIGEST_SIZE 							   ((uint32_t)0)
#define BDSP_IMG_SYSTEM_SCM2_DIGEST_SIZE 							   ((uint32_t)0)
#define BDSP_IMG_DDP_IDS_SIZE                                        ((uint32_t)0)
#define BDSP_IMG_DDP_IDS_INTER_FRAME_SIZE                            ((uint32_t)0)
#define BDSP_IMG_DTSHD_IDS_INTER_FRAME_SIZE                          ((uint32_t)0)
