/******************************************************************************
* Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
*
* This program is the proprietary software of Broadcom and/or its
* licensors, and may only be used, duplicated, modified or distributed pursuant
* to the terms and conditions of a separate, written license agreement executed
* between you and Broadcom (an "Authorized License").  Except as set forth in
* an Authorized License, Broadcom grants no license (express or implied), right
* to use, or waiver of any kind with respect to the Software, and Broadcom
* expressly reserves all rights in and to the Software and all intellectual
* property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
* HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
* NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
*
* Except as expressly set forth in the Authorized License,
*
* 1. This program, including its structure, sequence and organization,
*    constitutes the valuable trade secrets of Broadcom, and you shall use all
*    reasonable efforts to protect the confidentiality thereof, and to use
*    this information only in connection with your use of Broadcom integrated
*    circuit products.
*
* 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
*    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
*    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
*    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
*    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
*    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
*    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
*    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
*
* 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
*    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
*    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
*    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
*    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
*    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
*    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
*    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/*******************************************************************
*
* These values came from Yongsheng Yuan and appear to have come from an XLS file
*   at: May 11, 2016
*   for: Platform 7584/MemC 0 (32-bit DDR3@866MHz) w/277.0MHz  clock)
*
*******************************************************************/

#define BCHP_MEMC_ARB_0_CLIENT_INFO_0_VAL         0x42A014     /* XPT_WR_RS */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_1_VAL         0x80294029     /* XPT_WR_XC */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_2_VAL         0x804F6011     /* XPT_WR_CDB */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_3_VAL         0x804A001B     /* XPT_WR_ITB_MSG */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_4_VAL         0x8039701A     /* XPT_RD_RS */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_5_VAL         0x80572025     /* XPT_RD_XC_RMX_MSG */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_6_VAL         0x804F6012     /* XPT_RD_XC_RAVE */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_7_VAL         0x80EDA02A     /* XPT_RD_PB */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_8_VAL         0x8000002D     /* SDIO_CARD AVD__DBLK */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_9_VAL         0x8010D02E     /* AVD_ILCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_10_VAL         0x8025A009     /* AVD_OLCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_11_VAL         0x53D013     /* AVD_CAB */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_12_VAL         0x3CD00B     /* AVD_ILSI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_13_VAL         0x8005402D     /* SVD_DBLK */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_14_VAL         0x8019F02E     /* SVD_ILCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_15_VAL         0x80729009     /* SVD_OLCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_16_VAL         0x53D013     /* SVD_CAB */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_17_VAL         0x26700B     /* SVD_ILSI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_18_VAL         0x8013D000     /* SVD_BLCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_19_VAL         0x805B1017     /* SVD_BLSI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_20_VAL         0x80655015     /* SVD_MVSCL */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_21_VAL         0x80000031     /* SVD_SPIXSTR */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_22_VAL         0x8383E021     /* BSP */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_23_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_24_VAL         0x7FFF03E     /* SVD_DBLK_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_25_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_26_VAL         0x8087B03F     /* SATA */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_27_VAL         0x87FFF03B     /* TPCAP */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_28_VAL         0x80195027     /* CPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_29_VAL         0x299E041     /* SUN_MCIF_RD */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_30_VAL         0x299E042     /* SUN_MCIF_WR */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_31_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_32_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_33_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_34_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_35_VAL         0x8707E040     /* SDIO_CARD_0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_36_VAL         0x8707E040     /* EMMC_CARD_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_37_VAL         0x816FC01D     /* GENET0_WR */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_38_VAL         0x81A2102C     /* GENET0_RD */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_39_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_40_VAL         0x801BC010     /* GENET1_WR */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_41_VAL         0x807F402B     /* GENET1_RD */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_42_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_43_VAL         0x87FFF034     /* USB_HI_0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_44_VAL         0x87FFF036     /* USB_LO_0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_45_VAL         0x87FFF035     /* USB_HI_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_46_VAL         0x87FFF037     /* USB_LO_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_47_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_48_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_49_VAL         0x35E03F     /* RAAGA */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_50_VAL         0x19C1020     /* AUD_AIO */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_51_VAL         0x8011E00A     /* RAAGA_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_52_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_53_VAL         0x1AE001     /* BVN_RDC */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_54_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_55_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_56_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_57_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_58_VAL         0x3F300E     /* BVN_MFD1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_59_VAL         0x1F803F     /* BVN_MFD1_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_60_VAL         0x3F300D     /* BVN_MFD0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_61_VAL         0x1F8003     /* BVN_MFD0_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_60_VAL_75845         0x2F600D     /* BVN_MFD0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_61_VAL_75845         0x17A003     /* BVN_MFD0_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_62_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_63_VAL         0x11DB01C     /* BVN_CAP3 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_64_VAL         0xA66019     /* BVN_CAP2 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_65_VAL         0x21200F     /* BVN_CAP1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_66_VAL         0x212004     /* BVN_CAP0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_67_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_68_VAL         0x17D101F     /* BVN_VFD3 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_69_VAL         0x17D101E     /* BVN_VFD2 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_70_VAL         0x212007     /* BVN_VFD1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_71_VAL         0x212006     /* BVN_VFD0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_72_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_73_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_74_VAL         0x3F100C     /* BVN_MAD_PIX_CAP */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_75_VAL         0x1F7002     /* BVN_MAD_PIX_FD */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_76_VAL         0x2C5008     /* BVN_MAD_QUANT */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_77_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_78_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_79_VAL         0x9FB018     /* BVN_GFD1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_80_VAL         0x106005     /* BVN_GFD0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_81_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_82_VAL         0x46DE024     /* VEC_VBI_ENC1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_83_VAL         0x46DE023     /* VEC_VBI_ENC0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_84_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_85_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_86_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_87_VAL         0x8039C028     /* M2M_DMA0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_88_VAL         0x87FFF03C     /* VC4_3D_0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_89_VAL         0x87FFF03D     /* VC4_3D_1 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_90_VAL         0x87FFF039     /* M2MC0 */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_91_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_92_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_93_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_94_VAL         0x8707E03F     /* SID */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_95_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_96_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_97_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_98_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_99_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_100_VAL         0x8707E040     /* SCPU */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_101_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_102_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_103_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_104_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_105_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_106_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_107_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_108_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_109_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_110_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_111_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_112_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_113_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_114_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_115_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_116_VAL         0x80000030     /* SVD_SPIXSCALE */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_117_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_118_VAL         0x87FFF03A     /* MSA */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_119_VAL         0x87FFF038     /* DIS */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_120_VAL         0x8000002F     /* SVD_PRFI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_121_VAL         0x80000043     /* AVD_PRFI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_122_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_123_VAL         0x7FFF03F     /* UNASSIGNED */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_124_VAL         0x800C9026     /* CPU_LMB_HI */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_125_VAL         0x80000032     /* CPU_LMB_LO */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_126_VAL         0x87FFF033     /* DRAM_INIT */
#define BCHP_MEMC_ARB_0_CLIENT_INFO_127_VAL         0x8C8016     /* REFRESH */
