/************************************************************************
 * Copyright (C) 2018 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ************************************************************************/

/***
 *                           ##                   #
 *                          #  # #####  ##  ###  ###
 *                          #      #   #  # #  # ###
 *                           ##    #   #  # #  #  #
 *                             #   #   #  # ###   #
 *                          #  #   #   #  # #
 *                           ##    #    ##  #     #
 *
 *
 *    #   #  # ###  ##       ###  #### #    # #### ###    #   ### #### ###
 *   # #  #  #  #  #  #     #     #    ##   # #    #  #  # #   #  #    #  #
 *  #   # #  #  #  #  # ### #  ## ###  # #  # ###  ###  #   #  #  ###  #  #
 *  ##### #  #  #  #  #     #   # #    #  # # #    # #  #####  #  #    #  #
 *  #   #  ##   #   ##       ###  #### #   ## #### #  # #   #  #  #### ###
 */

/* Check for legacy configuration macros */
#ifndef _CHIP_H_
#if defined(HOST_BM)
#  error "Found HOST_BM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(HOST_SI)
#  error "Found HOST_SI already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_POSIX)
#  error "Found OS_POSIX already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_FREERTOS)
#  error "Found OS_FREERTOS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_CIRCULAR)
#  error "Found TB_CIRCULAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_LINEAR)
#  error "Found TB_LINEAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPLOG_MEMORY_SINK)
#  error "Found DSPLOG_MEMORY_SINK already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_MAGNUM)
#  error "Found RAAGA_HOST_SI_MAGNUM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_ROCKFORD)
#  error "Found RAAGA_HOST_SI_ROCKFORD already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_BIG_ENDIAN)
#  error "Found BCM_BIG_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_LITTLE_ENDIAN)
#  error "Found BCM_LITTLE_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPCONTROL_VOM)
#  error "Found DSPCONTROL_VOM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(LIBDSPCONTROL_DSPLESS)
#  error "Found LIBDSPCONTROL_DSPLESS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#endif /* _CHIP_H_*/

#ifndef _CHIP_H_
#define _CHIP_H_

/* We have to give a value to any macro we use as a literal or they will all default to 0 */
#define BCM68460A0_hpi                                                      42
#define BCM68460A0_si                                                       43
#define BCM93160A0_OFDMA_Rx_bm                                              44
#define BCM93160A0_OFDMA_Rx_si                                              45
#define BCM93160B0_USOOB_bm                                                 46
#define BCM93160_wkstn                                                      47
#define BCM93465                                                            48
#define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO                            49
#define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_YES                           50
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF                 51
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER                  52
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP               53
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE                          54
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE                       55
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET                     56
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK               57
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER        58
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE                     59
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_SOCKET                   60
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY                     61
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL                       62
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO                      63
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED   64
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED 65
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG                          66
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE                       67
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE                      68
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE                    69
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED              70
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED               71
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED                  72
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING                      73
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED                            74
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED                      75
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED                    76
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS                       77
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX                          78
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM                   79
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR                    80
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER                 81
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE                        82
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_BM                                    83
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS                              84
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON                               85
#define GenericFP4015_bm                                                    86
#define GenericFPM1015_bm                                                   87
#define GenericFPM1017_bm                                                   88
#define Pike_bm                                                             89
#define Pike_haps                                                           90
#define Pike_wkstn                                                          91
#define RaagaFP4015_barebone                                                92
#define RaagaFP4015_bm                                                      93
#define RaagaFP4015_haps_bare                                               94
#define RaagaFP4015_haps_bm                                                 95
#define RaagaFP4015_haps_fpos                                               96
#define RaagaFP4015_si_magnum                                               97
#define RaagaFP4015_si_magnum_permissive                                    98
#define RaagaFP4015_wkstn                                                   99
#define SMCFPM1017_bm                                                       100
#define YellowstoneA0_bm                                                    101
#define YellowstoneA0_si                                                    102

/* Only one, recognisable, TARGET_SOC defined */
#if !defined(BFPSDK_LIBDSPCONTROL_TARGET_SOC)
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be defined and be one of GenericFPM1015_bm, RaagaFP4015_si_magnum, BCM68460A0_si, BCM93160B0_USOOB_bm, RaagaFP4015_wkstn, YellowstoneA0_si, RaagaFP4015_si_magnum_permissive, YellowstoneA0_bm, GenericFPM1017_bm, BCM68460A0_hpi, RaagaFP4015_haps_bm, BCM93160A0_OFDMA_Rx_si, BCM93465, GenericFP4015_bm, SMCFPM1017_bm, RaagaFP4015_bm, BCM93160A0_OFDMA_Rx_bm, RaagaFP4015_barebone, Pike_haps, Pike_bm, Pike_wkstn, BCM93160_wkstn, RaagaFP4015_haps_bare, RaagaFP4015_haps_fpos"
#elif !((BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1017_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_hpi) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93465) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFP4015_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == SMCFPM1017_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bare) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_fpos))
#  error "An unsupported BFPSDK_LIBDSPCONTROL_TARGET_SOC has been provided"
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be one of GenericFPM1015_bm, RaagaFP4015_si_magnum, BCM68460A0_si, BCM93160B0_USOOB_bm, RaagaFP4015_wkstn, YellowstoneA0_si, RaagaFP4015_si_magnum_permissive, YellowstoneA0_bm, GenericFPM1017_bm, BCM68460A0_hpi, RaagaFP4015_haps_bm, BCM93160A0_OFDMA_Rx_si, BCM93465, GenericFP4015_bm, SMCFPM1017_bm, RaagaFP4015_bm, BCM93160A0_OFDMA_Rx_bm, RaagaFP4015_barebone, Pike_haps, Pike_bm, Pike_wkstn, BCM93160_wkstn, RaagaFP4015_haps_bare, RaagaFP4015_haps_fpos"
#endif

/* Is CHIP defined from outside or should we set it from the TARGET_SOC? */
#if (defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC))
/* Check if multiple CHIPs are defined */
#  if !(!((defined(PIKE) && ((defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(RAAGA) && ((defined(PIKE) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(GENERIC) && ((defined(PIKE) || defined(RAAGA) || defined(MCPHY) || defined(PMC3) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(PMC3) && ((defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(MCPHY) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(MCPHY) && ((defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(YELLOWSTONE) && ((defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(LEAP_PHY_BCM3465) || defined(SMC)))) || (defined(LEAP_PHY_BCM3465) && ((defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(YELLOWSTONE) || defined(SMC)))) || (defined(SMC) && ((defined(PIKE) || defined(RAAGA) || defined(GENERIC) || defined(PMC3) || defined(MCPHY) || defined(YELLOWSTONE) || defined(LEAP_PHY_BCM3465))))))
#    error "Multiple 'CHIP' macros defined - check your external defines"
#  endif
#else
/* Define CHIP from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#    define GENERIC 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_si
#    define PMC3 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#    define MCPHY 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#    define YELLOWSTONE 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#    define YELLOWSTONE 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1017_bm
#    define GENERIC 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_hpi
#    define PMC3 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#    define MCPHY 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93465
#    define LEAP_PHY_BCM3465 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFP4015_bm
#    define GENERIC 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == SMCFPM1017_bm
#    define SMC 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#    define MCPHY 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define PIKE 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define PIKE 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define PIKE 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#    define MCPHY 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bare
#    define RAAGA 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_fpos
#    define RAAGA 1
#  endif
#endif

/* Is MACH defined from outside or should we set it from the TARGET_SOC? */
#if (defined(__FPM1015__) || defined(__FP4014__) || defined(__FPM1017__) || defined(__FP4015__) || defined(__FP2012__))
/* Check if multiple MACHs are defined */
#  if !(!((defined(__FPM1015__) && ((defined(__FP4014__) || defined(__FP2012__) || defined(__FP4015__) || defined(__FPM1017__)))) || (defined(__FPM1017__) && ((defined(__FPM1015__) || defined(__FP4014__) || defined(__FP4015__) || defined(__FP2012__)))) || (defined(__FP2012__) && ((defined(__FPM1015__) || defined(__FP4014__) || defined(__FP4015__) || defined(__FPM1017__)))) || (defined(__FP4015__) && ((defined(__FP4014__) || defined(__FPM1015__) || defined(__FP2012__) || defined(__FPM1017__)))) || (defined(__FP4014__) && ((defined(__FPM1015__) || defined(__FP2012__) || defined(__FP4015__) || defined(__FPM1017__))))))
#    error "Multiple 'MACH' macros defined - check your external defines"
#  endif
#else
/* Define MACH from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#    define __FPM1015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_si
#    define __FPM1015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#    define __FP2012__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#    define __FP4014__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#    define __FP4014__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1017_bm
#    define __FPM1017__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_hpi
#    define __FPM1015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#    define __FP2012__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93465
#    define __FPM1015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFP4015_bm
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == SMCFPM1017_bm
#    define __FPM1017__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#    define __FP2012__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define __FP4014__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define __FP4014__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define __FP4014__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#    define __FP2012__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bare
#    define __FP4015__ 1
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_fpos
#    define __FP4015__ 1
#  endif
#endif

/* Per-TARGET_SOC features */
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "GenericFPM1015_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_si_magnum"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_si
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM68460A0_si"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160B0_USOOB_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "YellowstoneA0_si"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_si_magnum_permissive"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "YellowstoneA0_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1017_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "GenericFPM1017_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM68460A0_hpi
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM68460A0_hpi"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_haps_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160A0_OFDMA_Rx_si"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93465
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93465"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFP4015_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "GenericFP4015_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == SMCFPM1017_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "SMCFPM1017_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160A0_OFDMA_Rx_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_barebone"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_YES
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_haps"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bare
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_haps_bare"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_fpos
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_haps_fpos"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK_BUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif

/* Utility macros */
#define IS_TARGET(target)      (BFPSDK_LIBDSPCONTROL_TARGET_SOC == target)
#define IS_HOST(host)          (BFPSDK_LIBDSPCONTROL_HOST_ENV == BFPSDK_LIBDSPCONTROL_HOST_ENV_ ## host)
#define HAS_FEATURE(feat)      (BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat)
#define FEATURE_IS(feat,value) (BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat == BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat ## _ ## value)

#endif /* _CHIP_H_ */
