/************************************************************************
 * Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 ************************************************************************/

/***
 *                           ##                   #
 *                          #  # #####  ##  ###  ###
 *                          #      #   #  # #  # ###
 *                           ##    #   #  # #  #  #
 *                             #   #   #  # ###   #
 *                          #  #   #   #  # #
 *                           ##    #    ##  #     #
 *
 *
 *    #   #  # ###  ##       ###  #### #    # #### ###    #   ### #### ###
 *   # #  #  #  #  #  #     #     #    ##   # #    #  #  # #   #  #    #  #
 *  #   # #  #  #  #  # ### #  ## ###  # #  # ###  ###  #   #  #  ###  #  #
 *  ##### #  #  #  #  #     #   # #    #  # # #    # #  #####  #  #    #  #
 *  #   #  ##   #   ##       ###  #### #   ## #### #  # #   #  #  #### ###
 */

/* Check for legacy configuration macros */
#ifndef _CHIP_H_
#if defined(HOST_BM)
#  error "Found HOST_BM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(HOST_SI)
#  error "Found HOST_SI already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_POSIX)
#  error "Found OS_POSIX already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(OS_FREERTOS)
#  error "Found OS_FREERTOS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_CIRCULAR)
#  error "Found TB_CIRCULAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(TB_LINEAR)
#  error "Found TB_LINEAR already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPLOG_MEMORY_SINK)
#  error "Found DSPLOG_MEMORY_SINK already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_MAGNUM)
#  error "Found RAAGA_HOST_SI_MAGNUM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(RAAGA_HOST_SI_ROCKFORD)
#  error "Found RAAGA_HOST_SI_ROCKFORD already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_BIG_ENDIAN)
#  error "Found BCM_BIG_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(BCM_LITTLE_ENDIAN)
#  error "Found BCM_LITTLE_ENDIAN already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(DSPCONTROL_VOM)
#  error "Found DSPCONTROL_VOM already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#if defined(LIBDSPCONTROL_DSPLESS)
#  error "Found LIBDSPCONTROL_DSPLESS already defined. This legacy way of configuring libdspcontrol is no more supported."
#endif
#endif /* _CHIP_H_*/

#ifndef _CHIP_H_
#define _CHIP_H_

/* We have to give a value to any macro we use as a literal or they will all default to 0 */
#define BCM93160A0_OFDMA_Rx_bm                                              42
#define BCM93160A0_OFDMA_Rx_si                                              43
#define BCM93160B0_USOOB_bm                                                 44
#define BCM93160_wkstn                                                      45
#define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO                            46
#define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_YES                           47
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF                   48
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF                 49
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER                  50
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP               51
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE                          52
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE                       53
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET                     54
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG               55
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_LOOPBACK                 56
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK               57
#define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE                     58
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY                     59
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL                       60
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO                      61
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED   62
#define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED 63
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG                          64
#define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE                       65
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE                      66
#define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE                    67
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED              68
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED               69
#define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED                  70
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING                      71
#define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED                            72
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED                      73
#define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED                    74
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS                       75
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX                          76
#define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM                   77
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR                    78
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER                 79
#define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE                        80
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_BM                                    81
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS                              82
#define BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON                               83
#define GenericFPM1015_bm                                                   84
#define Leap_Phy_bm                                                         85
#define Pike_bm                                                             86
#define Pike_haps                                                           87
#define Pike_wkstn                                                          88
#define RaagaFP4015_barebone                                                89
#define RaagaFP4015_bm                                                      90
#define RaagaFP4015_haps                                                    91
#define RaagaFP4015_haps_bm                                                 92
#define RaagaFP4015_si_magnum                                               93
#define RaagaFP4015_si_magnum_permissive                                    94
#define RaagaFP4015_wkstn                                                   95
#define YellowstoneA0_bm                                                    96
#define YellowstoneA0_si                                                    97

/* Only one, recognisable, TARGET_SOC defined */
#if !defined(BFPSDK_LIBDSPCONTROL_TARGET_SOC)
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be defined and be one of Pike_wkstn, Pike_haps, BCM93160A0_OFDMA_Rx_si, YellowstoneA0_si, RaagaFP4015_si_magnum_permissive, RaagaFP4015_bm, YellowstoneA0_bm, BCM93160_wkstn, BCM93160A0_OFDMA_Rx_bm, Leap_Phy_bm, GenericFPM1015_bm, RaagaFP4015_haps_bm, RaagaFP4015_barebone, RaagaFP4015_si_magnum, BCM93160B0_USOOB_bm, RaagaFP4015_haps, RaagaFP4015_wkstn, Pike_bm"
#elif !((BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Leap_Phy_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn) || (BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm))
#  error "An unsupported BFPSDK_LIBDSPCONTROL_TARGET_SOC has been provided"
#  error "BFPSDK_LIBDSPCONTROL_TARGET_SOC must be one of Pike_wkstn, Pike_haps, BCM93160A0_OFDMA_Rx_si, YellowstoneA0_si, RaagaFP4015_si_magnum_permissive, RaagaFP4015_bm, YellowstoneA0_bm, BCM93160_wkstn, BCM93160A0_OFDMA_Rx_bm, Leap_Phy_bm, GenericFPM1015_bm, RaagaFP4015_haps_bm, RaagaFP4015_barebone, RaagaFP4015_si_magnum, BCM93160B0_USOOB_bm, RaagaFP4015_haps, RaagaFP4015_wkstn, Pike_bm"
#endif

/* Is CHIP defined from outside or should we set it from the TARGET_SOC? */
#if (defined(PIKE) || defined(RAAGA) || defined(LEAP_PHY) || defined(MCPHY) || defined(GENERIC) || defined(YELLOWSTONE))
/* Check if multiple CHIPs are defined */
#  if !(!((defined(PIKE) && ((defined(GENERIC) || defined(MCPHY) || defined(YELLOWSTONE) || defined(RAAGA) || defined(LEAP_PHY)))) || (defined(YELLOWSTONE) && ((defined(GENERIC) || defined(PIKE) || defined(RAAGA) || defined(LEAP_PHY) || defined(MCPHY)))) || (defined(RAAGA) && ((defined(GENERIC) || defined(PIKE) || defined(YELLOWSTONE) || defined(LEAP_PHY) || defined(MCPHY)))) || (defined(LEAP_PHY) && ((defined(GENERIC) || defined(PIKE) || defined(YELLOWSTONE) || defined(RAAGA) || defined(MCPHY)))) || (defined(GENERIC) && ((defined(MCPHY) || defined(PIKE) || defined(YELLOWSTONE) || defined(RAAGA) || defined(LEAP_PHY)))) || (defined(MCPHY) && ((defined(GENERIC) || defined(PIKE) || defined(YELLOWSTONE) || defined(RAAGA) || defined(LEAP_PHY))))))
#    error "Multiple 'CHIP' macros defined - check your external defines"
#  endif
#else
/* Define CHIP from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define PIKE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define PIKE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#    define YELLOWSTONE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#    define YELLOWSTONE
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Leap_Phy_bm
#    define LEAP_PHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#    define GENERIC
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#    define MCPHY
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#    define RAAGA
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define PIKE
#  endif
#endif

/* Is MACH defined from outside or should we set it from the TARGET_SOC? */
#if (defined(__FPM1015__) || defined(__FP2012__) || defined(__FP4015__) || defined(__FP4014__))
/* Check if multiple MACHs are defined */
#  if !(!((defined(__FPM1015__) && ((defined(__FP2012__) || defined(__FP4015__) || defined(__FP4014__)))) || (defined(__FP4014__) && ((defined(__FPM1015__) || defined(__FP4015__) || defined(__FP2012__)))) || (defined(__FP4015__) && ((defined(__FPM1015__) || defined(__FP2012__) || defined(__FP4014__)))) || (defined(__FP2012__) && ((defined(__FPM1015__) || defined(__FP4015__) || defined(__FP4014__))))))
#    error "Multiple 'MACH' macros defined - check your external defines"
#  endif
#else
/* Define MACH from TARGET_SOC */
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#    define __FP4014__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Leap_Phy_bm
#    define __FPM1015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#    define __FPM1015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#    define __FP2012__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#    define __FP4015__
#  endif
#  if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#    define __FP4014__
#  endif
#endif

/* Per-TARGET_SOC features */
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_UNBUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_haps
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_haps"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_si
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160A0_OFDMA_Rx_si"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_MEMORY
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_si
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "YellowstoneA0_si"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_BIG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum_permissive
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_si_magnum_permissive"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == YellowstoneA0_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "YellowstoneA0_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160A0_OFDMA_Rx_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160A0_OFDMA_Rx_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Leap_Phy_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Leap_Phy_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_BRIDGE_BUFF
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_LOOPBACK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == GenericFPM1015_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "GenericFPM1015_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_haps_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_barebone
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_barebone"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_YES
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_si_magnum
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_si_magnum"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_FREESTANDING
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_NULL
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_RAAGA_MAGNUM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_UNAVAILABLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == BCM93160B0_USOOB_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "BCM93160B0_USOOB_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_FREERTOS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_haps
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_haps"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_SILICON
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER_MP
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_FPOS_DEBUG
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == RaagaFP4015_wkstn
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "RaagaFP4015_wkstn"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_DSP_LESS
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_MULTIBUFFER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_NONE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif
#if BFPSDK_LIBDSPCONTROL_TARGET_SOC == Pike_bm
#  define BFPSDK_LIBDSPCONTROL_TARGET_NAME                        "Pike_bm"
#  define BFPSDK_LIBDSPCONTROL_HOST_ENV                           BFPSDK_LIBDSPCONTROL_HOST_ENV_BM
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY               BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VERIFY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE                   BFPSDK_LIBDSPCONTROL_FEATURE_BAREBONE_NO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE                   BFPSDK_LIBDSPCONTROL_FEATURE_DBG_CORE_DEBUG_SERVER
#  define BFPSDK_LIBDSPCONTROL_FEATURE_LIBC                       BFPSDK_LIBDSPCONTROL_FEATURE_LIBC_HOSTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM                  BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_VOM_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT                 BFPSDK_LIBDSPCONTROL_FEATURE_TB_VARIANT_CIRCULAR
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF              BFPSDK_LIBDSPCONTROL_FEATURE_DBG_TARGET_IF_MISC_BLOCK
#  define BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS                  BFPSDK_LIBDSPCONTROL_FEATURE_ENDIANESS_LITTLE
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF                BFPSDK_LIBDSPCONTROL_FEATURE_DBG_HOST_IF_SOCKET
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS BFPSDK_LIBDSPCONTROL_FEATURE_DSP_SYS_ADDR_DIRECT_ACCESS_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK                BFPSDK_LIBDSPCONTROL_FEATURE_DSPLOG_SINK_STDIO
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST                    BFPSDK_LIBDSPCONTROL_FEATURE_SW_HOST_LINUX
#  define BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY              BFPSDK_LIBDSPCONTROL_FEATURE_IMAGE_OVERLAY_UNSUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS                    BFPSDK_LIBDSPCONTROL_FEATURE_SOCKETS_SUPPORTED
#  define BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO                    BFPSDK_LIBDSPCONTROL_FEATURE_FILE_IO_AVAILABLE
#endif

/* Utility macros */
#define IS_TARGET(target)      (BFPSDK_LIBDSPCONTROL_TARGET_SOC == target)
#define IS_HOST(host)          (BFPSDK_LIBDSPCONTROL_HOST_ENV == BFPSDK_LIBDSPCONTROL_HOST_ENV_ ## host)
#define HAS_FEATURE(feat)      (defined(BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat))
#define FEATURE_IS(feat,value) (BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat == BFPSDK_LIBDSPCONTROL_FEATURE_ ## feat ## _ ## value)

#endif /* _CHIP_H_ */
