/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Apr 13 10:09:31 2017
 *                 Full Compile MD5 Checksum  7f180d7646477bba2bae1a701efd9ef5
 *                     (minus title and desc)
 *                 MD5 Checksum               a2a4a53aa20c0c2f46073b879159b85d
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1395
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              tools/dvtsw/current/Linux/combo_header.pl
 *                 DVTSWVER                   LOCAL tools/dvtsw/current/Linux/combo_header.pl
 *
 *
********************************************************************************/

#ifndef BCHP_CMP_2_H__
#define BCHP_CMP_2_H__

/***************************************************************************
 *CMP_2 - Video Compositor 2 Registers
 ***************************************************************************/
#define BCHP_CMP_2_REVISION                      0x0002d000 /* [RO][32] Compositor Revision ID */
#define BCHP_CMP_2_HW_CONFIGURATION              0x0002d004 /* [RO][32] Compositor HW Configuration */
#define BCHP_CMP_2_CANVAS_CTRL                   0x0002d008 /* [RW][32] Canvas control */
#define BCHP_CMP_2_CANVAS_SIZE                   0x0002d00c /* [CFG][32] Canvas Vertical and Horizontal Size */
#define BCHP_CMP_2_BG_COLOR                      0x0002d010 /* [CFG][32] Background color register */
#define BCHP_CMP_2_BLEND_0_CTRL                  0x0002d014 /* [CFG][32] Blending Control for First stage Blender */
#define BCHP_CMP_2_BLEND_1_CTRL                  0x0002d018 /* [CFG][32] Blending Control for Second stage Blender */
#define BCHP_CMP_2_CMP_CTRL                      0x0002d028 /* [CFG][32] Compositor Control */
#define BCHP_CMP_2_CMP_OUT_CTRL                  0x0002d040 /* [CFG][32] Compositor Output Control */
#define BCHP_CMP_2_CRC_CTRL                      0x0002d044 /* [CFG][32] BVN CRC Control Register */
#define BCHP_CMP_2_CRC_Y_STATUS                  0x0002d048 /* [RO][32] BVN CRC Luma Status Register */
#define BCHP_CMP_2_CRC_CB_STATUS                 0x0002d04c /* [RO][32] BVN CRC Chroma(Cb) Status Register */
#define BCHP_CMP_2_CRC_CR_STATUS                 0x0002d050 /* [RO][32] BVN CRC Chroma(Cr) Status Register */
#define BCHP_CMP_2_READBACK_POSITION             0x0002d054 /* [CFG][32] Compositor Position For CMP Output Readback */
#define BCHP_CMP_2_READBACK_VALUE                0x0002d058 /* [RO][64] Compositor Readback Y Value at Specified Position */
#define BCHP_CMP_2_CSC_DEMO_SETTING              0x0002d060 /* [CFG][32] Compositor Color Space Converter Demo Setting */
#define BCHP_CMP_2_SCRATCH_REGISTER              0x0002d064 /* [CFG][32] Compositor Scratch Register */
#define BCHP_CMP_2_TEST_REGISTER                 0x0002d06c /* [CFG][32] Compositor Test Register */
#define BCHP_CMP_2_TEST_REGISTER1                0x0002d070 /* [RO][32] Compositor Test Register1 */
#define BCHP_CMP_2_CMP_STATUS_CLEAR              0x0002d080 /* [WO][32] CMP Status Clear */
#define BCHP_CMP_2_CMP_STATUS                    0x0002d084 /* [RO][32] CMP Status */
#define BCHP_CMP_2_G0_SURFACE_SIZE               0x0002d180 /* [CFG][32] Graphics Surface 0 Vertical and Horizontal Size */
#define BCHP_CMP_2_G0_SURFACE_OFFSET             0x0002d184 /* [CFG][32] Graphics Surface 0 Vertical and Horizontal Offset */
#define BCHP_CMP_2_G0_DISPLAY_SIZE               0x0002d188 /* [CFG][32] Graphics Surface 0 Display Vertical and Horizontal Size1 */
#define BCHP_CMP_2_G0_CANVAS_OFFSET              0x0002d18c /* [CFG][32] Graphics Surface 0 Canvas Vertical and Horizontal Offset */
#define BCHP_CMP_2_G0_CANVAS_X_OFFSET_R          0x0002d190 /* [CFG][32] Graphics Surface 0 Canvas Horizontal Offset For Right or Under Window in 3D mode */
#define BCHP_CMP_2_G0_SURFACE_CTRL               0x0002d194 /* [CFG][32] Graphics Surface 0 Control */
#define BCHP_CMP_2_G0_BVB_IN_STATUS_CLEAR        0x0002d198 /* [WO][32] Graphics Surface 0 BVB Input Status Clear */
#define BCHP_CMP_2_G0_BVB_IN_STATUS              0x0002d19c /* [RO][32] Graphics Surface 0 BVB Input Status */
#define BCHP_CMP_2_V0_SURFACE_SIZE               0x0002d200 /* [CFG][32] Video Surface 0 Vertical and Horizontal Size */
#define BCHP_CMP_2_V0_SURFACE_OFFSET             0x0002d204 /* [CFG][32] Video Surface 0 Vertical and Horizontal Offset */
#define BCHP_CMP_2_V0_DISPLAY_SIZE               0x0002d208 /* [CFG][32] Video Surface 0 Display Vertical and Horizontal Size */
#define BCHP_CMP_2_V0_CANVAS_OFFSET              0x0002d20c /* [CFG][32] Video Surface 0 Canvas Vertical and Horizontal Offset */
#define BCHP_CMP_2_V0_CANVAS_X_OFFSET_R          0x0002d210 /* [CFG][32] Video Surface 0 Canvas Horizontal Offset For Right or Under Window in 3D mode */
#define BCHP_CMP_2_V0_SURFACE_CTRL               0x0002d214 /* [CFG][32] Video Surface 0 Control */
#define BCHP_CMP_2_V0_BVB_IN_STATUS_CLEAR        0x0002d218 /* [WO][32] Video Surface 0 BVB Input Status Clear */
#define BCHP_CMP_2_V0_BVB_IN_STATUS              0x0002d21c /* [RO][32] Video Surface 0 BVB Input Status */
#define BCHP_CMP_2_V0_CONST_COLOR                0x0002d220 /* [CFG][32] Video Surface 0 Constant Color Register */
#define BCHP_CMP_2_V0_CB_KEYING                  0x0002d224 /* [CFG][32] Video Surface 0 Chroma (Blue) Key */
#define BCHP_CMP_2_V0_CR_KEYING                  0x0002d228 /* [CFG][32] Video Surface 0 Chroma (Red) Key */
#define BCHP_CMP_2_V0_LUMA_KEYING                0x0002d22c /* [CFG][32] Video Surface 0 Luma Key */
#define BCHP_CMP_2_V0_RECT_CSC_INDEX_0           0x0002d230 /* [CFG][32] Video Surface 0 rectangle CSC index 0 */
#define BCHP_CMP_2_V0_RECT_CSC_INDEX_1           0x0002d234 /* [CFG][32] Video Surface 0 rectangle CSC index 1 */
#define BCHP_CMP_2_V0_RECT_COLOR                 0x0002d238 /* [CFG][32] Video Surface 0 Rectangle Function Color Register */
#define BCHP_CMP_2_V0_RECT_TOP_CTRL              0x0002d23c /* [CFG][32] Video Surface 0 Top Level Rectangle Control for Mosaic or See Through. */
#define BCHP_CMP_2_V0_RECT_ENABLE_MASK           0x0002d240 /* [CFG][32] Video Surface 0 Rectangle Function Enable Mask */
#define BCHP_CMP_2_V0_NL_CSC_CTRL                0x0002d2d0 /* [CFG][32] Video Surface 0 Nonconstant Luminance CSC Control */
#define BCHP_CMP_2_V0_REV_CCA_CTRL               0x0002d2d4 /* [CFG][32] Video Surface 0 Reverse CCA Control */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C00            0x0002d504 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c00 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C01            0x0002d508 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c01 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C02            0x0002d50c /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c02 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C03            0x0002d510 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c03 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C10            0x0002d514 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c10 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C11            0x0002d518 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c11 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C12            0x0002d51c /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c12 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C13            0x0002d520 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c13 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C20            0x0002d524 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c20 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C21            0x0002d528 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c21 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C22            0x0002d52c /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c22 */
#define BCHP_CMP_2_V0_R0_MC_COEFF_C23            0x0002d530 /* [CFG][32] Video Surface 0 Color Matrix C R0 coefficient c23 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C00            0x0002d538 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c00 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C01            0x0002d53c /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c01 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C02            0x0002d540 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c02 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C03            0x0002d544 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c03 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C10            0x0002d548 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c10 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C11            0x0002d54c /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c11 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C12            0x0002d550 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c12 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C13            0x0002d554 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c13 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C20            0x0002d558 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c20 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C21            0x0002d55c /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c21 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C22            0x0002d560 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c22 */
#define BCHP_CMP_2_V0_R1_MC_COEFF_C23            0x0002d564 /* [CFG][32] Video Surface 0 Color Matrix C R1 coefficient c23 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C00            0x0002d56c /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c00 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C01            0x0002d570 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c01 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C02            0x0002d574 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c02 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C03            0x0002d578 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c03 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C10            0x0002d57c /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c10 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C11            0x0002d580 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c11 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C12            0x0002d584 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c12 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C13            0x0002d588 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c13 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C20            0x0002d58c /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c20 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C21            0x0002d590 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c21 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C22            0x0002d594 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c22 */
#define BCHP_CMP_2_V0_R2_MC_COEFF_C23            0x0002d598 /* [CFG][32] Video Surface 0 Color Matrix C R2 coefficient c23 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C00            0x0002d5a0 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c00 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C01            0x0002d5a4 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c01 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C02            0x0002d5a8 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c02 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C03            0x0002d5ac /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c03 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C10            0x0002d5b0 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c10 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C11            0x0002d5b4 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c11 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C12            0x0002d5b8 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c12 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C13            0x0002d5bc /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c13 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C20            0x0002d5c0 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c20 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C21            0x0002d5c4 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c21 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C22            0x0002d5c8 /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c22 */
#define BCHP_CMP_2_V0_R3_MC_COEFF_C23            0x0002d5cc /* [CFG][32] Video Surface 0 Color Matrix C R3 coefficient c23 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C00            0x0002d5d4 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c00 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C01            0x0002d5d8 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c01 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C02            0x0002d5dc /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c02 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C03            0x0002d5e0 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c03 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C10            0x0002d5e4 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c10 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C11            0x0002d5e8 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c11 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C12            0x0002d5ec /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c12 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C13            0x0002d5f0 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c13 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C20            0x0002d5f4 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c20 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C21            0x0002d5f8 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c21 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C22            0x0002d5fc /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c22 */
#define BCHP_CMP_2_V0_R4_MC_COEFF_C23            0x0002d600 /* [CFG][32] Video Surface 0 Color Matrix C R4 coefficient c23 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C00            0x0002d608 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c00 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C01            0x0002d60c /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c01 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C02            0x0002d610 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c02 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C03            0x0002d614 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c03 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C10            0x0002d618 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c10 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C11            0x0002d61c /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c11 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C12            0x0002d620 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c12 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C13            0x0002d624 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c13 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C20            0x0002d628 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c20 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C21            0x0002d62c /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c21 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C22            0x0002d630 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c22 */
#define BCHP_CMP_2_V0_R5_MC_COEFF_C23            0x0002d634 /* [CFG][32] Video Surface 0 Color Matrix C R5 coefficient c23 */
#define BCHP_CMP_2_V0_IN_DITHER_422_CTRL         0x0002d6ac /* [CFG][32] Video Surface 0 In Dither CTRL (10 to 8 bits conversion) */
#define BCHP_CMP_2_V0_IN_DITHER_LFSR_INIT        0x0002d6b0 /* [CFG][32] Video Surface 0 Input Dither LFSR Init value and control (10 to 8 bits conversion) */
#define BCHP_CMP_2_V0_IN_DITHER_LFSR_CTRL        0x0002d6b4 /* [CFG][32] Video Surface 0 Input Dither LFSR control (10 to 8 bits conversion) */

/***************************************************************************
 *V0_RECT_SIZE%i - Rectangle Vertical and Horizontal Size.
 ***************************************************************************/
#define BCHP_CMP_2_V0_RECT_SIZEi_ARRAY_BASE                        0x0002d250
#define BCHP_CMP_2_V0_RECT_SIZEi_ARRAY_START                       0
#define BCHP_CMP_2_V0_RECT_SIZEi_ARRAY_END                         15
#define BCHP_CMP_2_V0_RECT_SIZEi_ARRAY_ELEMENT_SIZE                32

/***************************************************************************
 *V0_RECT_SIZE%i - Rectangle Vertical and Horizontal Size.
 ***************************************************************************/
/* CMP_2 :: V0_RECT_SIZEi :: reserved0 [31:29] */
#define BCHP_CMP_2_V0_RECT_SIZEi_reserved0_MASK                    0xe0000000
#define BCHP_CMP_2_V0_RECT_SIZEi_reserved0_SHIFT                   29

/* CMP_2 :: V0_RECT_SIZEi :: HSIZE [28:16] */
#define BCHP_CMP_2_V0_RECT_SIZEi_HSIZE_MASK                        0x1fff0000
#define BCHP_CMP_2_V0_RECT_SIZEi_HSIZE_SHIFT                       16
#define BCHP_CMP_2_V0_RECT_SIZEi_HSIZE_DEFAULT                     0x00000000

/* CMP_2 :: V0_RECT_SIZEi :: reserved1 [15:12] */
#define BCHP_CMP_2_V0_RECT_SIZEi_reserved1_MASK                    0x0000f000
#define BCHP_CMP_2_V0_RECT_SIZEi_reserved1_SHIFT                   12

/* CMP_2 :: V0_RECT_SIZEi :: VSIZE [11:00] */
#define BCHP_CMP_2_V0_RECT_SIZEi_VSIZE_MASK                        0x00000fff
#define BCHP_CMP_2_V0_RECT_SIZEi_VSIZE_SHIFT                       0
#define BCHP_CMP_2_V0_RECT_SIZEi_VSIZE_DEFAULT                     0x00000000


/***************************************************************************
 *V0_RECT_OFFSET%i - Rectangle Starting Point Offset from Surface Origin.
 ***************************************************************************/
#define BCHP_CMP_2_V0_RECT_OFFSETi_ARRAY_BASE                      0x0002d290
#define BCHP_CMP_2_V0_RECT_OFFSETi_ARRAY_START                     0
#define BCHP_CMP_2_V0_RECT_OFFSETi_ARRAY_END                       15
#define BCHP_CMP_2_V0_RECT_OFFSETi_ARRAY_ELEMENT_SIZE              32

/***************************************************************************
 *V0_RECT_OFFSET%i - Rectangle Starting Point Offset from Surface Origin.
 ***************************************************************************/
/* CMP_2 :: V0_RECT_OFFSETi :: reserved0 [31:29] */
#define BCHP_CMP_2_V0_RECT_OFFSETi_reserved0_MASK                  0xe0000000
#define BCHP_CMP_2_V0_RECT_OFFSETi_reserved0_SHIFT                 29

/* CMP_2 :: V0_RECT_OFFSETi :: X_OFFSET [28:16] */
#define BCHP_CMP_2_V0_RECT_OFFSETi_X_OFFSET_MASK                   0x1fff0000
#define BCHP_CMP_2_V0_RECT_OFFSETi_X_OFFSET_SHIFT                  16
#define BCHP_CMP_2_V0_RECT_OFFSETi_X_OFFSET_DEFAULT                0x00000000

/* CMP_2 :: V0_RECT_OFFSETi :: reserved1 [15:12] */
#define BCHP_CMP_2_V0_RECT_OFFSETi_reserved1_MASK                  0x0000f000
#define BCHP_CMP_2_V0_RECT_OFFSETi_reserved1_SHIFT                 12

/* CMP_2 :: V0_RECT_OFFSETi :: Y_OFFSET [11:00] */
#define BCHP_CMP_2_V0_RECT_OFFSETi_Y_OFFSET_MASK                   0x00000fff
#define BCHP_CMP_2_V0_RECT_OFFSETi_Y_OFFSET_SHIFT                  0
#define BCHP_CMP_2_V0_RECT_OFFSETi_Y_OFFSET_DEFAULT                0x00000000


#endif /* #ifndef BCHP_CMP_2_H__ */

/* End of File */
