/******************************************************************************
 *  Copyright (C) 2018 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.

 ******************************************************************************/

/******************************************************************************
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Tue Jan  9 16:23:04 2018
 *                 Full Compile MD5 Checksum  2ff608fe362eb86bea5ba570b815521f
 *                     (minus title and desc)
 *                 MD5 Checksum               f58b8ef6a7a1966baf956e0d7af563c5
 *
 * lock_release:   r_1777
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1859
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              home/pt902453/sbin/combo_header.pl
 *                 DVTSWVER                   LOCAL home/pt902453/sbin/combo_header.pl
 *
 *
********************************************************************************/

#ifndef BCHP_SCPU_HOST_INTR2_H__
#define BCHP_SCPU_HOST_INTR2_H__

/***************************************************************************
 *SCPU_HOST_INTR2 - SCPU to Host Level 2 Interrupt Controller Registers
 ***************************************************************************/
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS          0x00311040 /* [RO][32] CPU interrupt Status Register */
#define BCHP_SCPU_HOST_INTR2_CPU_SET             0x00311044 /* [WO][32] CPU interrupt Set Register */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR           0x00311048 /* [WO][32] CPU interrupt Clear Register */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS     0x0031104c /* [RO][32] CPU interrupt Mask Status Register */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET        0x00311050 /* [WO][32] CPU interrupt Mask Set Register */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR      0x00311054 /* [WO][32] CPU interrupt Mask Clear Register */
#define BCHP_SCPU_HOST_INTR2_PCI_STATUS          0x00311058 /* [RO][32] PCI interrupt Status Register */
#define BCHP_SCPU_HOST_INTR2_PCI_SET             0x0031105c /* [WO][32] PCI interrupt Set Register */
#define BCHP_SCPU_HOST_INTR2_PCI_CLEAR           0x00311060 /* [WO][32] PCI interrupt Clear Register */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_STATUS     0x00311064 /* [RO][32] PCI interrupt Mask Status Register */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_SET        0x00311068 /* [WO][32] PCI interrupt Mask Set Register */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_CLEAR      0x0031106c /* [WO][32] PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_STATUS :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_reserved0_MASK             0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_reserved0_SHIFT            4

/* SCPU_HOST_INTR2 :: CPU_STATUS :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_MICH_INST_RD_INTR_MASK 0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_MICH_INST_RD_INTR_SHIFT 3
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000000

/* SCPU_HOST_INTR2 :: CPU_STATUS :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_TIMER_MASK            0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_TIMER_SHIFT           2
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_TIMER_DEFAULT         0x00000000

/* SCPU_HOST_INTR2 :: CPU_STATUS :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_OLOAD_MASK       0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_OLOAD_SHIFT      1
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_OLOAD_DEFAULT    0x00000000

/* SCPU_HOST_INTR2 :: CPU_STATUS :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_DRDY_MASK        0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_DRDY_SHIFT       0
#define BCHP_SCPU_HOST_INTR2_CPU_STATUS_SCPU_HOST_DRDY_DEFAULT     0x00000000

/***************************************************************************
 *CPU_SET - CPU interrupt Set Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_SET :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_SET_reserved0_MASK                0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_SET_reserved0_SHIFT               4

/* SCPU_HOST_INTR2 :: CPU_SET :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_MICH_INST_RD_INTR_MASK   0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_MICH_INST_RD_INTR_SHIFT  3
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000000

/* SCPU_HOST_INTR2 :: CPU_SET :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_TIMER_MASK               0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_TIMER_SHIFT              2
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_TIMER_DEFAULT            0x00000000

/* SCPU_HOST_INTR2 :: CPU_SET :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_OLOAD_MASK          0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_OLOAD_SHIFT         1
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_OLOAD_DEFAULT       0x00000000

/* SCPU_HOST_INTR2 :: CPU_SET :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_DRDY_MASK           0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_DRDY_SHIFT          0
#define BCHP_SCPU_HOST_INTR2_CPU_SET_SCPU_HOST_DRDY_DEFAULT        0x00000000

/***************************************************************************
 *CPU_CLEAR - CPU interrupt Clear Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_CLEAR :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_reserved0_MASK              0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_reserved0_SHIFT             4

/* SCPU_HOST_INTR2 :: CPU_CLEAR :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_MICH_INST_RD_INTR_MASK 0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_MICH_INST_RD_INTR_SHIFT 3
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000000

/* SCPU_HOST_INTR2 :: CPU_CLEAR :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_TIMER_MASK             0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_TIMER_SHIFT            2
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_TIMER_DEFAULT          0x00000000

/* SCPU_HOST_INTR2 :: CPU_CLEAR :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_OLOAD_MASK        0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_OLOAD_SHIFT       1
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_OLOAD_DEFAULT     0x00000000

/* SCPU_HOST_INTR2 :: CPU_CLEAR :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_DRDY_MASK         0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_DRDY_SHIFT        0
#define BCHP_SCPU_HOST_INTR2_CPU_CLEAR_SCPU_HOST_DRDY_DEFAULT      0x00000000

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_MASK_STATUS :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_reserved0_MASK        0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_reserved0_SHIFT       4

/* SCPU_HOST_INTR2 :: CPU_MASK_STATUS :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_MICH_INST_RD_INTR_MASK 0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_MICH_INST_RD_INTR_SHIFT 3
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_STATUS :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_TIMER_MASK       0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_TIMER_SHIFT      2
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_TIMER_DEFAULT    0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_STATUS :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_OLOAD_MASK  0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_OLOAD_SHIFT 1
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_OLOAD_DEFAULT 0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_STATUS :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_DRDY_MASK   0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_DRDY_SHIFT  0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_STATUS_SCPU_HOST_DRDY_DEFAULT 0x00000001

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_MASK_SET :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_reserved0_MASK           0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_reserved0_SHIFT          4

/* SCPU_HOST_INTR2 :: CPU_MASK_SET :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_MICH_INST_RD_INTR_MASK 0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_MICH_INST_RD_INTR_SHIFT 3
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_SET :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_TIMER_MASK          0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_TIMER_SHIFT         2
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_TIMER_DEFAULT       0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_SET :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_OLOAD_MASK     0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_OLOAD_SHIFT    1
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_OLOAD_DEFAULT  0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_SET :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_DRDY_MASK      0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_DRDY_SHIFT     0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_SET_SCPU_HOST_DRDY_DEFAULT   0x00000001

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: CPU_MASK_CLEAR :: reserved0 [31:04] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_reserved0_MASK         0xfffffff0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_reserved0_SHIFT        4

/* SCPU_HOST_INTR2 :: CPU_MASK_CLEAR :: SCPU_MICH_INST_RD_INTR [03:03] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_MICH_INST_RD_INTR_MASK 0x00000008
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_MICH_INST_RD_INTR_SHIFT 3
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_MICH_INST_RD_INTR_DEFAULT 0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_CLEAR :: SCPU_TIMER [02:02] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_TIMER_MASK        0x00000004
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_TIMER_SHIFT       2
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_TIMER_DEFAULT     0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_CLEAR :: SCPU_HOST_OLOAD [01:01] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_OLOAD_MASK   0x00000002
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_OLOAD_SHIFT  1
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_OLOAD_DEFAULT 0x00000001

/* SCPU_HOST_INTR2 :: CPU_MASK_CLEAR :: SCPU_HOST_DRDY [00:00] */
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_DRDY_MASK    0x00000001
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_DRDY_SHIFT   0
#define BCHP_SCPU_HOST_INTR2_CPU_MASK_CLEAR_SCPU_HOST_DRDY_DEFAULT 0x00000001

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_STATUS :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_STATUS_UNUSED_MASK                0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_STATUS_UNUSED_SHIFT               0
#define BCHP_SCPU_HOST_INTR2_PCI_STATUS_UNUSED_DEFAULT             0x00000000

/***************************************************************************
 *PCI_SET - PCI interrupt Set Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_SET :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_SET_UNUSED_MASK                   0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_SET_UNUSED_SHIFT                  0
#define BCHP_SCPU_HOST_INTR2_PCI_SET_UNUSED_DEFAULT                0x00000000

/***************************************************************************
 *PCI_CLEAR - PCI interrupt Clear Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_CLEAR :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_CLEAR_UNUSED_MASK                 0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_CLEAR_UNUSED_SHIFT                0
#define BCHP_SCPU_HOST_INTR2_PCI_CLEAR_UNUSED_DEFAULT              0x00000000

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_MASK_STATUS :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_STATUS_UNUSED_MASK           0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_STATUS_UNUSED_SHIFT          0
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_STATUS_UNUSED_DEFAULT        0xffffffff

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_MASK_SET :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_SET_UNUSED_MASK              0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_SET_UNUSED_SHIFT             0
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_SET_UNUSED_DEFAULT           0xffffffff

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* SCPU_HOST_INTR2 :: PCI_MASK_CLEAR :: UNUSED [31:00] */
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_CLEAR_UNUSED_MASK            0xffffffff
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_CLEAR_UNUSED_SHIFT           0
#define BCHP_SCPU_HOST_INTR2_PCI_MASK_CLEAR_UNUSED_DEFAULT         0xffffffff

#endif /* #ifndef BCHP_SCPU_HOST_INTR2_H__ */

/* End of File */
