/***************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *
 * Module Description:
 *
 ***************************************************************************/

#ifndef BMRC_PRIV_H
#define BMRC_PRIV_H

#include "bchp.h"                /* Chip information */

#ifdef __cplusplus
extern "C" {
#endif


/* chip specific defines */
#if (BCHP_CHIP == 7271) || (BCHP_CHIP == 7268) || (BCHP_CHIP == 7260)
#define BMRC_P_MEMC_NUM 1

#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 8
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1


#elif (BCHP_CHIP == 3548)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 3556)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 3560)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 1
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 3563)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7038)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 1
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7118)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7125)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7135)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7145)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7250)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1


#elif (BCHP_CHIP == 7325)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7335)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7336)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7340)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7342)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7400)
#define BMRC_P_MEMC_NUM 3
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 2
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 2
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#if (BCHP_VER >= BCHP_VER_B0)
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1
#else
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0
#endif

#elif (BCHP_CHIP == 7401)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7403)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7405)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7408)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7420)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#if (BCHP_VER >= BCHP_VER_B0)
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#else
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#endif
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7422)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7425)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7435)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 2
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7445)
#define BMRC_P_MEMC_NUM 3
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 8
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7344)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif ((BCHP_CHIP == 7346) || (BCHP_CHIP == 73465))
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7231)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7584)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 75845)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7438)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 1
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7440)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7640)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7468)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7550)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7601)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 96
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7635)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 96
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 0
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 0

#elif (BCHP_CHIP == 7630)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 64
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif ((BCHP_CHIP == 7563) || (BCHP_CHIP == 75635))
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 35230)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 35233)
#if (BCHP_VER == A0)
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#else
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#endif
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 35125)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7358)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7552)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif ((BCHP_CHIP == 7429) || (BCHP_CHIP == 74295))
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7360)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7362) || (BCHP_CHIP == 7228) || (BCHP_CHIP == 73625)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1


#elif (BCHP_CHIP == 7366)
#if (BCHP_VER < BCHP_VER_B0)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#else
#define BMRC_P_MEMC_NUM 2
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#endif
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7543 || BCHP_CHIP == 75525)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 4
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 0
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 0
#define BMRC_P_CLIENTS_MAX 128
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7439) || (BCHP_CHIP == 74371)
#if (BCHP_VER < BCHP_VER_B0)
#define BMRC_P_MEMC_NUM 1
#else
#define BMRC_P_MEMC_NUM 2
#endif
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 8
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1

#elif (BCHP_CHIP == 7364 || BCHP_CHIP==7586)
#define BMRC_P_MEMC_NUM 1
#define BMRC_P_MEMC_0_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_1_CHECKER_COUNT_MAX 8
#define BMRC_P_MEMC_2_CHECKER_COUNT_MAX 8
#define BMRC_P_CLIENTS_MAX 256
#define BMRC_P_CHECKER_USE_MEMC_GEN_VER 0
#define BMRC_P_CHECKER_USE_MEMC_ARC_VER 1
#define BMRC_P_CHECKER_USE_NEW_NAME_SUFFIX 1
#define BMRC_P_CHECKER_USE_NMBX_ID 0
#define BMRC_P_CHECKER_USE_VIOLATION_INFO_CLEAR 1
#else
#error "Platform not supported in MRC."
#endif


/* include platform specific header files */
#if ((BCHP_CHIP == 3560) || (BCHP_CHIP == 3563) || (BCHP_CHIP == 7038) || (BCHP_CHIP == 7118) || \
       (BCHP_CHIP == 7400) || (BCHP_CHIP == 7401) || (BCHP_CHIP == 7403) || (BCHP_CHIP == 7438))
#include "bchp_int_id_bvnf_intr2_2.h"
#endif

#if (BMRC_P_CHECKER_USE_MEMC_GEN_VER)
#include "bchp_int_id_memc_l2_0.h"
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_1_0.h"
#endif

#if (BMRC_P_MEMC_NUM > 1)
#include "bchp_int_id_memc_l2_1.h"
#if (BMRC_P_MEMC_1_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_1_1.h"
#endif
#endif

#if (BMRC_P_MEMC_NUM > 2)
#include "bchp_int_id_memc_l2_2.h"
#if (BMRC_P_MEMC_2_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_1_2.h"
#endif
#endif /* #if (BMRC_P_CHECKER_USE_MEMC_GEN_VER) */


#elif (BMRC_P_CHECKER_USE_MEMC_ARC_VER)
#include "bchp_int_id_memc_l2_0_0.h"
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_0_1.h"
#endif

#if (BMRC_P_MEMC_NUM > 1)
#include "bchp_int_id_memc_l2_1_0.h"
#if (BMRC_P_MEMC_1_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_1_1.h"
#endif
#endif

#if (BMRC_P_MEMC_NUM > 2)
#include "bchp_int_id_memc_l2_2_0.h"
#if (BMRC_P_MEMC_2_CHECKER_COUNT_MAX > 4)
#include "bchp_int_id_memc_l2_2_1.h"
#endif
#endif /* #if (BMRC_P_CHECKER_USE_MEMC_ARC_VER) */


#elif (BCHP_CHIP == 3563)
#include "bchp_int_id_memc_1_intr2.h"

#elif ((BCHP_CHIP == 7400) && (BCHP_VER < BCHP_VER_B0))
#include "bchp_int_id_memc16_intr2_0.h"

#elif ((BCHP_CHIP == 7400) && (BCHP_VER >= BCHP_VER_B0)) || (BCHP_CHIP == 7405)
#include "bchp_int_id_memc16_gfx_l2.h"
#if (BCHP_CHIP == 7405)
#include "bchp_int_id_memc64_gfx_l2.h"
#endif

#elif (BCHP_CHIP == 7325) || (BCHP_CHIP == 7335) || (BCHP_CHIP == 7336) || (BCHP_CHIP == 7420) || \
      (BCHP_CHIP == 3548) || (BCHP_CHIP == 3556) || (BCHP_CHIP == 35230) || (BCHP_CHIP == 35233)
#include "bchp_int_id_memc_0_l2.h"
#if (BMRC_P_MEMC_NUM > 1)
#include "bchp_int_id_memc_1_l2.h"
#endif

#elif (BCHP_CHIP == 7440)
#include "bchp_int_id_arb_top_config_regs.h"

#elif (BCHP_CHIP==7601) || (BCHP_CHIP==7635) || (BCHP_CHIP==7630)
#include "bchp_int_id_l2_reg_0.h"

#elif (BCHP_CHIP==7640)
#include "bchp_int_id_pri_arb_arc_l2_regs.h"
#endif


#define BMRC_P_CLIENTS_ARRAY_ELEMENT_SIZE 32
#define BMRC_P_CLIENTS_ARRAY_SIZE (BMRC_P_CLIENTS_MAX / BMRC_P_CLIENTS_ARRAY_ELEMENT_SIZE)


/* chip specific ARC INTR configuration */
/* memc 0 */
#if BMRC_P_CHECKER_USE_MEMC_GEN_VER && (BMRC_P_MEMC_NUM > 1)
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_0_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_0_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_0_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_0_ARC_3_INTR
#if (BMRC_P_CHECKER_USE_MEMC_GEN_VER > 1) && (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_0_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_4_INTR
#define BMRC_P_MEMC_0_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_5_INTR
#define BMRC_P_MEMC_0_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_6_INTR
#define BMRC_P_MEMC_0_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_7_INTR
#else
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0
#endif /*(BMRC_P_CHECKER_USE_MEMC_GEN_VER > 1) && (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4) */

#elif BMRC_P_CHECKER_USE_MEMC_ARC_VER
#if BMRC_P_MEMC_NUM==1 && !BCHP_P_MEMC_INT_ID_GENERIC
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_ARC_3_INTR
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_0_ARC_4_INTR    BCHP_INT_ID_ARC_4_INTR
#define BMRC_P_MEMC_0_ARC_5_INTR    BCHP_INT_ID_ARC_5_INTR
#define BMRC_P_MEMC_0_ARC_6_INTR    BCHP_INT_ID_ARC_6_INTR
#define BMRC_P_MEMC_0_ARC_7_INTR    BCHP_INT_ID_ARC_7_INTR
#else
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0
#endif
#else
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_0_0_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_0_0_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_0_0_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_0_0_ARC_3_INTR
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_0_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_0_1_ARC_4_INTR
#define BMRC_P_MEMC_0_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_0_1_ARC_5_INTR
#define BMRC_P_MEMC_0_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_0_1_ARC_6_INTR
#define BMRC_P_MEMC_0_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_0_1_ARC_7_INTR
#else /*(BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4) */
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0
#endif /*(BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4) */
#endif

#elif ((BCHP_CHIP == 7325) || (BCHP_CHIP == 7335) || (BCHP_CHIP==7336) || (BCHP_CHIP == 7420))
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_MEMC_0_L2_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_MEMC_0_L2_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_MEMC_0_L2_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_MEMC_0_L2_ARC_3_INTR
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0

#elif ((BCHP_CHIP == 3563) && (BCHP_VER >= BCHP_VER_C0))
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_BVNF_INTR2_2_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_BVNF_INTR2_2_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_BVNF_INTR2_2_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_BVNF_INTR2_2_ARC_3_INTR
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0

#else /* ((BCHP_CHIP == 3563) && (BCHP_VER >= BCHP_VER_C0)) */
#define BMRC_P_MEMC_0_ARC_0_INTR    BCHP_INT_ID_ARC_0_INTR
#define BMRC_P_MEMC_0_ARC_1_INTR    BCHP_INT_ID_ARC_1_INTR
#define BMRC_P_MEMC_0_ARC_2_INTR    BCHP_INT_ID_ARC_2_INTR
#define BMRC_P_MEMC_0_ARC_3_INTR    BCHP_INT_ID_ARC_3_INTR
#define BMRC_P_MEMC_0_ARC_4_INTR    0
#define BMRC_P_MEMC_0_ARC_5_INTR    0
#define BMRC_P_MEMC_0_ARC_6_INTR    0
#define BMRC_P_MEMC_0_ARC_7_INTR    0
#endif /* ((BCHP_CHIP == 3563) && (BCHP_VER >= BCHP_VER_C0)) */

/* memc 1 */
#if BMRC_P_CHECKER_USE_MEMC_GEN_VER && (BMRC_P_MEMC_NUM > 1)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_1_ARC_0_INTR
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_1_ARC_1_INTR
#define BMRC_P_MEMC_1_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_1_ARC_2_INTR
#define BMRC_P_MEMC_1_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_1_ARC_3_INTR
#if (BMRC_P_CHECKER_USE_MEMC_GEN_VER > 1) && (BMRC_P_MEMC_1_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_1_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_4_INTR
#define BMRC_P_MEMC_1_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_5_INTR
#define BMRC_P_MEMC_1_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_6_INTR
#define BMRC_P_MEMC_1_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_7_INTR
#else
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0
#endif

#elif BMRC_P_CHECKER_USE_MEMC_ARC_VER && (BMRC_P_MEMC_NUM > 1)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_0_INTR
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_1_INTR
#define BMRC_P_MEMC_1_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_2_INTR
#define BMRC_P_MEMC_1_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_1_0_ARC_3_INTR
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_1_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_4_INTR
#define BMRC_P_MEMC_1_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_5_INTR
#define BMRC_P_MEMC_1_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_6_INTR
#define BMRC_P_MEMC_1_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_1_1_ARC_7_INTR
#else
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0
#endif

#elif (BCHP_CHIP == 7325) || (BCHP_CHIP == 7335) || (BCHP_CHIP==7336) || (BCHP_CHIP == 7420)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_MEMC_1_L2_ARC_0_INTR
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_MEMC_1_L2_ARC_1_INTR
#define BMRC_P_MEMC_1_ARC_2_INTR    BCHP_INT_ID_MEMC_1_L2_ARC_2_INTR
#define BMRC_P_MEMC_1_ARC_3_INTR    BCHP_INT_ID_MEMC_1_L2_ARC_3_INTR
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0

#elif (BCHP_CHIP==3563)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_MEMC_1_INTR2_ARC_0_INTR
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_MEMC_1_INTR2_ARC_1_INTR
#define BMRC_P_MEMC_1_ARC_2_INTR    BCHP_INT_ID_MEMC_1_INTR2_ARC_2_INTR
#define BMRC_P_MEMC_1_ARC_3_INTR    BCHP_INT_ID_MEMC_1_INTR2_ARC_3_INTR
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0

#elif (BCHP_CHIP==7400)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_ARC_0_INTR_1
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_ARC_1_INTR_1
#define BMRC_P_MEMC_1_ARC_2_INTR    0
#define BMRC_P_MEMC_1_ARC_3_INTR    0
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0

#elif (BCHP_CHIP==7405)
#define BMRC_P_MEMC_1_ARC_0_INTR    BCHP_INT_ID_ARC_0_INTR_1
#define BMRC_P_MEMC_1_ARC_1_INTR    BCHP_INT_ID_ARC_1_INTR_1
#define BMRC_P_MEMC_1_ARC_2_INTR    BCHP_INT_ID_ARC_0_INTR_2
#define BMRC_P_MEMC_1_ARC_3_INTR    BCHP_INT_ID_ARC_1_INTR_2
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0

#elif (BMRC_P_MEMC_NUM > 1)
#error "Port for MEMC 1 interrupts needed."

#else
#define BMRC_P_MEMC_1_ARC_0_INTR    0
#define BMRC_P_MEMC_1_ARC_1_INTR    0
#define BMRC_P_MEMC_1_ARC_2_INTR    0
#define BMRC_P_MEMC_1_ARC_3_INTR    0
#define BMRC_P_MEMC_1_ARC_4_INTR    0
#define BMRC_P_MEMC_1_ARC_5_INTR    0
#define BMRC_P_MEMC_1_ARC_6_INTR    0
#define BMRC_P_MEMC_1_ARC_7_INTR    0
#endif

/* memc 2 */
#if BMRC_P_CHECKER_USE_MEMC_GEN_VER && (BMRC_P_MEMC_NUM > 2)
#define BMRC_P_MEMC_2_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_2_ARC_0_INTR
#define BMRC_P_MEMC_2_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_2_ARC_1_INTR
#define BMRC_P_MEMC_2_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_2_ARC_2_INTR
#define BMRC_P_MEMC_2_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_2_ARC_3_INTR
#if (BMRC_P_CHECKER_USE_MEMC_GEN_VER > 1) && (BMRC_P_MEMC_2_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_2_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_1_2_ARC_4_INTR
#define BMRC_P_MEMC_2_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_1_2_ARC_5_INTR
#define BMRC_P_MEMC_2_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_1_2_ARC_6_INTR
#define BMRC_P_MEMC_2_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_1_2_ARC_7_INTR
#else
#define BMRC_P_MEMC_2_ARC_4_INTR    0
#define BMRC_P_MEMC_2_ARC_5_INTR    0
#define BMRC_P_MEMC_2_ARC_6_INTR    0
#define BMRC_P_MEMC_2_ARC_7_INTR    0
#endif

#elif BMRC_P_CHECKER_USE_MEMC_ARC_VER && (BMRC_P_MEMC_NUM > 2)
#define BMRC_P_MEMC_2_ARC_0_INTR    BCHP_INT_ID_MEMC_L2_2_0_ARC_0_INTR
#define BMRC_P_MEMC_2_ARC_1_INTR    BCHP_INT_ID_MEMC_L2_2_0_ARC_1_INTR
#define BMRC_P_MEMC_2_ARC_2_INTR    BCHP_INT_ID_MEMC_L2_2_0_ARC_2_INTR
#define BMRC_P_MEMC_2_ARC_3_INTR    BCHP_INT_ID_MEMC_L2_2_0_ARC_3_INTR
#if (BMRC_P_MEMC_0_CHECKER_COUNT_MAX > 4)
#define BMRC_P_MEMC_2_ARC_4_INTR    BCHP_INT_ID_MEMC_L2_2_1_ARC_4_INTR
#define BMRC_P_MEMC_2_ARC_5_INTR    BCHP_INT_ID_MEMC_L2_2_1_ARC_5_INTR
#define BMRC_P_MEMC_2_ARC_6_INTR    BCHP_INT_ID_MEMC_L2_2_1_ARC_6_INTR
#define BMRC_P_MEMC_2_ARC_7_INTR    BCHP_INT_ID_MEMC_L2_2_1_ARC_7_INTR
#else
#define BMRC_P_MEMC_2_ARC_4_INTR    0
#define BMRC_P_MEMC_2_ARC_5_INTR    0
#define BMRC_P_MEMC_2_ARC_6_INTR    0
#define BMRC_P_MEMC_2_ARC_7_INTR    0
#endif

#elif (BCHP_CHIP==7400)
#define BMRC_P_MEMC_2_ARC_0_INTR    BCHP_INT_ID_ARC_0_INTR_2
#define BMRC_P_MEMC_2_ARC_1_INTR    BCHP_INT_ID_ARC_1_INTR_2
#define BMRC_P_MEMC_2_ARC_2_INTR    0
#define BMRC_P_MEMC_2_ARC_3_INTR    0
#define BMRC_P_MEMC_2_ARC_4_INTR    0
#define BMRC_P_MEMC_2_ARC_5_INTR    0
#define BMRC_P_MEMC_2_ARC_6_INTR    0
#define BMRC_P_MEMC_2_ARC_7_INTR    0

#elif (BMRC_P_MEMC_NUM > 2)
#error "Port for MEMC 2 interrupts needed."

#else
#define BMRC_P_MEMC_2_ARC_0_INTR    0
#define BMRC_P_MEMC_2_ARC_1_INTR    0
#define BMRC_P_MEMC_2_ARC_2_INTR    0
#define BMRC_P_MEMC_2_ARC_3_INTR    0
#define BMRC_P_MEMC_2_ARC_4_INTR    0
#define BMRC_P_MEMC_2_ARC_5_INTR    0
#define BMRC_P_MEMC_2_ARC_6_INTR    0
#define BMRC_P_MEMC_2_ARC_7_INTR    0
#endif


#ifdef __cplusplus
}
#endif

#endif
/* End of File */
