/******************************************************************************
 *  Broadcom Proprietary and Confidential. (c)2008-2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to the terms and
 * conditions of a separate, written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 * no license (express or implied), right to use, or waiver of any kind with respect to the
 * Software, and Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 * secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 * AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 * WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 * THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 * OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 * LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 * OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 * USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 * LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 * EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 * USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 * ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 * LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 * ANY LIMITED REMEDY.
 *
 *****************************************************************************/

#ifndef BXPT_DMA_HELPER_H__
#define BXPT_DMA_HELPER_H__

/* various helper define's for backward-compatibility */

#if (!BXPT_DMA_HAS_WDMA_CHX)
#define BCHP_XPT_WDMA_CH0_FIRST_DESC_ADDR        BCHP_XPT_WDMA_RAMS_FIRST_DESC_ADDR
#define BCHP_XPT_WDMA_CH0_NEXT_DESC_ADDR         BCHP_XPT_WDMA_RAMS_NEXT_DESC_ADDR
#define BCHP_XPT_WDMA_CH0_COMPLETED_DESC_ADDRESS BCHP_XPT_WDMA_RAMS_COMPLETED_DESC_ADDRESS
#define BCHP_XPT_WDMA_CH0_BTP_PACKET_GROUP_ID    BCHP_XPT_WDMA_RAMS_BTP_PACKET_GROUP_ID
#define BCHP_XPT_WDMA_CH0_RUN_VERSION_CONFIG     BCHP_XPT_WDMA_RAMS_RUN_VERSION_CONFIG
#define BCHP_XPT_WDMA_CH0_OVERFLOW_REASONS       BCHP_XPT_WDMA_RAMS_OVERFLOW_REASONS
#define BCHP_XPT_WDMA_CH0_DMQ_CONTROL_STRUCT     BCHP_XPT_WDMA_RAMS_DMQ_CONTROL_STRUCT

#define XPT_WDMA_CH0_FIRST_DESC_ADDR        XPT_WDMA_RAMS_FIRST_DESC_ADDR
#define XPT_WDMA_CH0_NEXT_DESC_ADDR         XPT_WDMA_RAMS_NEXT_DESC_ADDR
#define XPT_WDMA_CH0_COMPLETED_DESC_ADDRESS XPT_WDMA_RAMS_COMPLETED_DESC_ADDRESS
#define XPT_WDMA_CH0_BTP_PACKET_GROUP_ID    XPT_WDMA_RAMS_BTP_PACKET_GROUP_ID
#define XPT_WDMA_CH0_RUN_VERSION_CONFIG     XPT_WDMA_RAMS_RUN_VERSION_CONFIG
#define XPT_WDMA_CH0_OVERFLOW_REASONS       XPT_WDMA_RAMS_OVERFLOW_REASONS
#define XPT_WDMA_CH0_DMQ_CONTROL_STRUCT     XPT_WDMA_RAMS_DMQ_CONTROL_STRUCT

#define BCHP_XPT_WDMA_CH0_RUN_VERSION_CONFIG_RUN_VERSION_MASK  BCHP_XPT_WDMA_RAMS_RUN_VERSION_CONFIG_RUN_VERSION_MASK
#define BCHP_XPT_WDMA_CH0_RUN_VERSION_CONFIG_RUN_VERSION_SHIFT BCHP_XPT_WDMA_RAMS_RUN_VERSION_CONFIG_RUN_VERSION_SHIFT
#endif

#if (!BXPT_DMA_HAS_MEMDMA_MCPB)
#define BCHP_XPT_MEMDMA_MCPB_RUN_SET_CLEAR                          BCHP_XPT_MCPB_RUN_SET_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_WAKE_SET                               BCHP_XPT_MCPB_WAKE_SET
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AT_DESC_READ_CLEAR               BCHP_XPT_MCPB_PAUSE_AT_DESC_READ_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AT_DESC_END_CLEAR                BCHP_XPT_MCPB_PAUSE_AT_DESC_END_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AFTER_GROUP_PACKETS_CLEAR        BCHP_XPT_MCPB_PAUSE_AFTER_GROUP_PACKETS_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_CRC_COMPARE_ERROR_PAUSE_CLEAR          BCHP_XPT_MCPB_CRC_COMPARE_ERROR_PAUSE_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_MICRO_PAUSE_SET_CLEAR                  BCHP_XPT_MCPB_MICRO_PAUSE_SET_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_RUN_STATUS_0_31                        BCHP_XPT_MCPB_RUN_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_WAKE_STATUS_0_31                       BCHP_XPT_MCPB_WAKE_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AT_DESC_READ_STATUS_0_31         BCHP_XPT_MCPB_PAUSE_AT_DESC_READ_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AT_DESC_END_STATUS_0_31          BCHP_XPT_MCPB_PAUSE_AT_DESC_END_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_PAUSE_AFTER_GROUP_PACKETS_STATUS_0_31  BCHP_XPT_MCPB_PAUSE_AFTER_GROUP_PACKETS_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_CRC_COMPARE_ERROR_PAUSE_STATUS_0_31    BCHP_XPT_MCPB_CRC_COMPARE_ERROR_PAUSE_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_MICRO_PAUSE_STATUS_0_31                BCHP_XPT_MCPB_MICRO_PAUSE_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_HW_PAUSE_STATUS_0_31                   BCHP_XPT_MCPB_HW_PAUSE_STATUS_0_31
#define BCHP_XPT_MEMDMA_MCPB_DESC_RD_IN_PROGRESS_0_31               BCHP_XPT_MCPB_DESC_RD_IN_PROGRESS_0_31
#define BCHP_XPT_MEMDMA_MCPB_DATA_RD_IN_PROGRESS_0_31               BCHP_XPT_MCPB_DATA_RD_IN_PROGRESS_0_31
#define BCHP_XPT_MEMDMA_MCPB_LAST_DESC_REACHED_0_31                 BCHP_XPT_MCPB_LAST_DESC_REACHED_0_31
#define BCHP_XPT_MEMDMA_MCPB_BUFF_DATA_RDY_0_31                     BCHP_XPT_MCPB_BUFF_DATA_RDY_0_31

#define XPT_MEMDMA_MCPB_RUN_SET_CLEAR                           XPT_MCPB_RUN_SET_CLEAR
#define XPT_MEMDMA_MCPB_WAKE_SET                                XPT_MCPB_WAKE_SET
#define XPT_MEMDMA_MCPB_PAUSE_AT_DESC_READ_CLEAR                XPT_MCPB_PAUSE_AT_DESC_READ_CLEAR
#define XPT_MEMDMA_MCPB_PAUSE_AT_DESC_END_CLEAR                 XPT_MCPB_PAUSE_AT_DESC_END_CLEAR
#define XPT_MEMDMA_MCPB_PAUSE_AFTER_GROUP_PACKETS_CLEAR         XPT_MCPB_PAUSE_AFTER_GROUP_PACKETS_CLEAR
#define XPT_MEMDMA_MCPB_CRC_COMPARE_ERROR_PAUSE_CLEAR           XPT_MCPB_CRC_COMPARE_ERROR_PAUSE_CLEAR
#define XPT_MEMDMA_MCPB_MICRO_PAUSE_SET_CLEAR                   XPT_MCPB_MICRO_PAUSE_SET_CLEAR
#define XPT_MEMDMA_MCPB_RUN_STATUS_0_31                         XPT_MCPB_RUN_STATUS_0_31
#define XPT_MEMDMA_MCPB_WAKE_STATUS_0_31                        XPT_MCPB_WAKE_STATUS_0_31
#define XPT_MEMDMA_MCPB_PAUSE_AT_DESC_READ_STATUS_0_31          XPT_MCPB_PAUSE_AT_DESC_READ_STATUS_0_31
#define XPT_MEMDMA_MCPB_PAUSE_AT_DESC_END_STATUS_0_31           XPT_MCPB_PAUSE_AT_DESC_END_STATUS_0_31
#define XPT_MEMDMA_MCPB_PAUSE_AFTER_GROUP_PACKETS_STATUS_0_31   XPT_MCPB_PAUSE_AFTER_GROUP_PACKETS_STATUS_0_31
#define XPT_MEMDMA_MCPB_CRC_COMPARE_ERROR_PAUSE_STATUS_0_31     XPT_MCPB_CRC_COMPARE_ERROR_PAUSE_STATUS_0_31
#define XPT_MEMDMA_MCPB_MICRO_PAUSE_STATUS_0_31                 XPT_MCPB_MICRO_PAUSE_STATUS_0_31
#define XPT_MEMDMA_MCPB_HW_PAUSE_STATUS_0_31                    XPT_MCPB_HW_PAUSE_STATUS_0_31
#define XPT_MEMDMA_MCPB_DESC_RD_IN_PROGRESS_0_31                XPT_MCPB_DESC_RD_IN_PROGRESS_0_31
#define XPT_MEMDMA_MCPB_DATA_RD_IN_PROGRESS_0_31                XPT_MCPB_DATA_RD_IN_PROGRESS_0_31
#define XPT_MEMDMA_MCPB_LAST_DESC_REACHED_0_31                  XPT_MCPB_LAST_DESC_REACHED_0_31
#define XPT_MEMDMA_MCPB_BUFF_DATA_RDY_0_31                      XPT_MCPB_BUFF_DATA_RDY_0_31

#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DESC_CONTROL               BCHP_XPT_MCPB_CH0_DMA_DESC_CONTROL
#define BCHP_XPT_MEMDMA_MCPB_CH1_DMA_DESC_CONTROL               BCHP_XPT_MCPB_CH1_DMA_DESC_CONTROL
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DATA_CONTROL               BCHP_XPT_MCPB_CH0_DMA_DATA_CONTROL
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_CURR_DESC_ADDRESS          BCHP_XPT_MCPB_CH0_DMA_CURR_DESC_ADDRESS
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_NEXT_DESC_ADDRESS          BCHP_XPT_MCPB_CH0_DMA_NEXT_DESC_ADDRESS
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_PKT_LEN                     BCHP_XPT_MCPB_CH0_SP_PKT_LEN
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_PARSER_CTRL                 BCHP_XPT_MCPB_CH0_SP_PARSER_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_PARSER_CTRL1                BCHP_XPT_MCPB_CH0_SP_PARSER_CTRL1
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_TS_CONFIG                   BCHP_XPT_MCPB_CH0_SP_TS_CONFIG
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_PES_ES_CONFIG               BCHP_XPT_MCPB_CH0_SP_PES_ES_CONFIG
#define BCHP_XPT_MEMDMA_MCPB_CH0_SP_PES_SYNC_COUNTER            BCHP_XPT_MCPB_CH0_SP_PES_SYNC_COUNTER
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_BBUFF_CTRL                 BCHP_XPT_MCPB_CH0_DMA_BBUFF_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_BBUFF_CRC                  BCHP_XPT_MCPB_CH0_DMA_BBUFF_CRC
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_BLOCKOUT_CTRL             BCHP_XPT_MCPB_CH0_TMEU_BLOCKOUT_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_CTRL               BCHP_XPT_MCPB_CH0_TMEU_TIMING_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_TS_ERR_BOUND_EARLY        BCHP_XPT_MCPB_CH0_TMEU_TS_ERR_BOUND_EARLY
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_TS_ERR_BOUND_LATE         BCHP_XPT_MCPB_CH0_TMEU_TS_ERR_BOUND_LATE
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_PES_PACING_CTRL           BCHP_XPT_MCPB_CH0_TMEU_PES_PACING_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_INFO_LAST_TIMESTAMP_DELTA BCHP_XPT_MCPB_CH0_TMEU_TIMING_INFO_LAST_TIMESTAMP_DELTA
#define BCHP_XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_INFO_LAST_NEXT_TIMESTAMP  BCHP_XPT_MCPB_CH0_TMEU_TIMING_INFO_LAST_NEXT_TIMESTAMP
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_STATUS                    BCHP_XPT_MCPB_CH0_DCPM_STATUS
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_DESC_ADDR                 BCHP_XPT_MCPB_CH0_DCPM_DESC_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_DESC_DONE_INT_ADDR        BCHP_XPT_MCPB_CH0_DCPM_DESC_DONE_INT_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_PAUSE_AFTER_GROUP_PACKETS_CTRL BCHP_XPT_MCPB_CH0_DCPM_PAUSE_AFTER_GROUP_PACKETS_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_LOCAL_PACKET_COUNTER      BCHP_XPT_MCPB_CH0_DCPM_LOCAL_PACKET_COUNTER
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_DATA_ADDR_UPPER           BCHP_XPT_MCPB_CH0_DCPM_DATA_ADDR_UPPER
#define BCHP_XPT_MEMDMA_MCPB_CH0_DCPM_DATA_ADDR_LOWER           BCHP_XPT_MCPB_CH0_DCPM_DATA_ADDR_LOWER

#define XPT_MEMDMA_MCPB_CH0_DMA_DESC_CONTROL            XPT_MCPB_CH0_DMA_DESC_CONTROL
#define XPT_MEMDMA_MCPB_CH1_DMA_DESC_CONTROL            XPT_MCPB_CH1_DMA_DESC_CONTROL
#define XPT_MEMDMA_MCPB_CH0_DMA_DATA_CONTROL            XPT_MCPB_CH0_DMA_DATA_CONTROL
#define XPT_MEMDMA_MCPB_CH0_DMA_CURR_DESC_ADDRESS       XPT_MCPB_CH0_DMA_CURR_DESC_ADDRESS
#define XPT_MEMDMA_MCPB_CH0_DMA_NEXT_DESC_ADDRESS       XPT_MCPB_CH0_DMA_NEXT_DESC_ADDRESS
#define XPT_MEMDMA_MCPB_CH0_SP_PKT_LEN                  XPT_MCPB_CH0_SP_PKT_LEN
#define XPT_MEMDMA_MCPB_CH0_SP_PARSER_CTRL              XPT_MCPB_CH0_SP_PARSER_CTRL
#define XPT_MEMDMA_MCPB_CH0_SP_PARSER_CTRL1             XPT_MCPB_CH0_SP_PARSER_CTRL1
#define XPT_MEMDMA_MCPB_CH0_SP_TS_CONFIG                XPT_MCPB_CH0_SP_TS_CONFIG
#define XPT_MEMDMA_MCPB_CH0_SP_PES_ES_CONFIG            XPT_MCPB_CH0_SP_PES_ES_CONFIG
#define XPT_MEMDMA_MCPB_CH0_SP_PES_SYNC_COUNTER         XPT_MCPB_CH0_SP_PES_SYNC_COUNTER
#define XPT_MEMDMA_MCPB_CH0_DMA_BBUFF_CTRL              XPT_MCPB_CH0_DMA_BBUFF_CTRL
#define XPT_MEMDMA_MCPB_CH0_DMA_BBUFF_CRC               XPT_MCPB_CH0_DMA_BBUFF_CRC
#define XPT_MEMDMA_MCPB_CH0_TMEU_BLOCKOUT_CTRL          XPT_MCPB_CH0_TMEU_BLOCKOUT_CTRL
#define XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_CTRL            XPT_MCPB_CH0_TMEU_TIMING_CTRL
#define XPT_MEMDMA_MCPB_CH0_TMEU_TS_ERR_BOUND_EARLY     XPT_MCPB_CH0_TMEU_TS_ERR_BOUND_EARLY
#define XPT_MEMDMA_MCPB_CH0_TMEU_TS_ERR_BOUND_LATE      XPT_MCPB_CH0_TMEU_TS_ERR_BOUND_LATE
#define XPT_MEMDMA_MCPB_CH0_TMEU_PES_PACING_CTRL        XPT_MCPB_CH0_TMEU_PES_PACING_CTRL
#define XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_INFO_LAST_TIMESTAMP_DELTA XPT_MCPB_CH0_TMEU_TIMING_INFO_LAST_TIMESTAMP_DELTA
#define XPT_MEMDMA_MCPB_CH0_TMEU_TIMING_INFO_LAST_NEXT_TIMESTAMP  XPT_MCPB_CH0_TMEU_TIMING_INFO_LAST_NEXT_TIMESTAMP
#define XPT_MEMDMA_MCPB_CH0_DCPM_STATUS                 XPT_MCPB_CH0_DCPM_STATUS
#define XPT_MEMDMA_MCPB_CH0_DCPM_DESC_ADDR              XPT_MCPB_CH0_DCPM_DESC_ADDR
#define XPT_MEMDMA_MCPB_CH0_DCPM_DESC_DONE_INT_ADDR     XPT_MCPB_CH0_DCPM_DESC_DONE_INT_ADDR
#define XPT_MEMDMA_MCPB_CH0_DCPM_PAUSE_AFTER_GROUP_PACKETS_CTRL XPT_MCPB_CH0_DCPM_PAUSE_AFTER_GROUP_PACKETS_CTRL
#define XPT_MEMDMA_MCPB_CH0_DCPM_LOCAL_PACKET_COUNTER   XPT_MCPB_CH0_DCPM_LOCAL_PACKET_COUNTER
#define XPT_MEMDMA_MCPB_CH0_DCPM_DATA_ADDR_UPPER        XPT_MCPB_CH0_DCPM_DATA_ADDR_UPPER
#define XPT_MEMDMA_MCPB_CH0_DCPM_DATA_ADDR_LOWER        XPT_MCPB_CH0_DCPM_DATA_ADDR_LOWER

#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_STATUS      BCHP_XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_STATUS
#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS BCHP_XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS
#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_SET    BCHP_XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_SET
#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR  BCHP_XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR

#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_STATUS      XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_STATUS
#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS
#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_SET    XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_SET
#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR  XPT_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR
#endif

#ifdef BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DATA_CTRL
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DATA_CONTROL BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DATA_CTRL
#define XPT_MEMDMA_MCPB_CH0_DMA_DATA_CONTROL XPT_MEMDMA_MCPB_CH0_DMA_DATA_CTRL
#endif
#ifdef BCHP_XPT_MEMDMA_MCPB_CH0_DMA_CURR_DESC_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_CURR_DESC_ADDRESS  BCHP_XPT_MEMDMA_MCPB_CH0_DMA_CURR_DESC_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_NEXT_DESC_ADDRESS  BCHP_XPT_MEMDMA_MCPB_CH0_DMA_NEXT_DESC_ADDR
#endif
#ifdef BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DESC_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DESC_CONTROL BCHP_XPT_MEMDMA_MCPB_CH0_DMA_DESC_ADDR
#define BCHP_XPT_MEMDMA_MCPB_CH1_DMA_DESC_CONTROL BCHP_XPT_MEMDMA_MCPB_CH1_DMA_DESC_ADDR
#endif
#ifdef BCHP_XPT_MEMDMA_MCPB_HOST_INTR_AGGREGATOR_INTR_W0_MASK_STATUS
#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_STATUS BCHP_XPT_MEMDMA_MCPB_HOST_INTR_AGGREGATOR_INTR_W0_MASK_STATUS
#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR XPT_MEMDMA_MCPB_HOST_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR
#define BCHP_XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR BCHP_XPT_MEMDMA_MCPB_HOST_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR
#define XPT_MEMDMA_MCPB_CPU_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR XPT_MEMDMA_MCPB_HOST_INTR_AGGREGATOR_INTR_W0_MASK_CLEAR
#endif

#endif
