/***************************************************************************
*	   (c)2007-2013 Broadcom Corporation
*
* This program is the proprietary software of Broadcom Corporation and/or its licensors,
* and may only be used, duplicated, modified or distributed pursuant to the terms and
* conditions of a separate, written license agreement executed between you and Broadcom
* (an "Authorized License").	Except as set forth in an Authorized License, Broadcom grants
* no license (express or implied), right to use, or waiver of any kind with respect to the
* Software, and Broadcom expressly reserves all rights in and to the Software and all
* intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
* HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
* NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
*
* Except as expressly set forth in the Authorized License,
*
* 1.	   This program, including its structure, sequence and organization, constitutes the valuable trade
* secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
* and to use this information only in connection with your use of Broadcom integrated circuit products.
*
*	2.	   TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
* AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
* WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
* THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
* OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
* LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
* OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
* USE OR PERFORMANCE OF THE SOFTWARE.
*
* 3.	   TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
* LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
* EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
* USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
* ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
* LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
* ANY LIMITED REMEDY.
*
* $brcm_Workfile: $
* $brcm_Revision: $
* $brcm_Date: $
*
* Module Description:
*
* Revision History:
*
* $brcm_Log: $
*
***************************************************************************/
#ifndef BCEC_PRIV_H__
#define BCEC_PRIV_H__

#include "bcec.h"
#include "bchp_common.h"

#ifdef __cplusplus
extern "C" {
#endif


#if BCEC_CONFIG_40NM_SUPPORT \
 || BCEC_CONFIG_28NM_SUPPORT
#include "bchp_aon_hdmi_tx.h"
#include "bchp_hdmi_tx_intr2.h"
#include "bchp_int_id_hdmi_tx_intr2.h"
#include "bchp_int_id_aon_pm_l2.h"
#include "bchp_int_id_aon_l2.h"

#elif BCEC_CONFIG_65NM_SUPPORT
#include "bchp_hdmi_intr2.h"
#include "bchp_int_id_hdmi_intr2.h"
#include "bchp_hdmi_tx_phy.h"

#else
#include "bchp_hdmi_intr2.h"
#include "bchp_int_id_hdmi_intr2.h"
#endif

#if BCEC_CONFIG_HAS_HDMI_RX
#include "bchp_aon_hdmi_rx.h"
#endif

/* Get the offset of two groups of register. */
#define BCEC_P_GET_REG_OFFSET(eCecHdmiPath, ulRxReg, ulTxReg) \
	((BCEC_Hdmi_eTx0 == (eCecHdmiPath)) ? 0x0 : ((ulRxReg) - (ulTxReg)))


#if BCEC_CONFIG_40NM_SUPPORT || BCEC_CONFIG_28NM_SUPPORT
#define BCHP_MASK_DVP(Register,Field) BCHP_AON_HDMI_TX_##Register##_##Field##_MASK

#define BCHP_MASK_CEC_CNTRL(Register,Field) BCHP_AON_HDMI_TX_##Register##_##Field##_MASK

#define REGADDR_CEC_CNTRL_1 BCHP_AON_HDMI_TX_CEC_CNTRL_1
#define REGNAME_CEC_CNTRL_1 AON_HDMI_TX_CEC_CNTRL_1

#define REGADDR_CEC_CNTRL_2 BCHP_AON_HDMI_TX_CEC_CNTRL_2
#define REGNAME_CEC_CNTRL_2 AON_HDMI_TX_CEC_CNTRL_2

#define REGADDR_CEC_CNTRL_3 BCHP_AON_HDMI_TX_CEC_CNTRL_3
#define REGNAME_CEC_CNTRL_3 AON_HDMI_TX_CEC_CNTRL_3

#define REGADDR_CEC_CNTRL_4 BCHP_AON_HDMI_TX_CEC_CNTRL_4
#define REGNAME_CEC_CNTRL_4 AON_HDMI_TX_CEC_CNTRL_4

#define REGADDR_CEC_CNTRL_5 BCHP_AON_HDMI_TX_CEC_CNTRL_5
#define REGNAME_CEC_CNTRL_5 AON_HDMI_TX_CEC_CNTRL_5

#define REGADDR_CEC_CNTRL_6 BCHP_AON_HDMI_TX_CEC_CNTRL_6
#define REGNAME_CEC_CNTRL_6 AON_HDMI_TX_CEC_CNTRL_6

#define REGADDR_CEC_TX_DATA_1 BCHP_AON_HDMI_TX_CEC_TX_DATA_1
#define REGNAME_CEC_TX_DATA_1 AON_HDMI_TX_CEC_TX_DATA_1

#define REGADDR_CEC_RX_DATA_1 BCHP_AON_HDMI_TX_CEC_RX_DATA_1
#define REGNAME_CEC_RX_DATA_1 AON_HDMI_TX_CEC_RX_DATA_1

#define REGADDR_CEC_TX_AUTO_CEC_CFG BCHP_AON_HDMI_TX_AUTO_CEC_CFG
#define REGNAME_CEC_TX_AUTO_CEC_CFG AON_HDMI_TX_AUTO_CEC_CFG

#define REGADDR_CEC_TX_AUTO_CEC_CNTRL BCHP_AON_HDMI_TX_AUTO_CEC_CNTRL
#define REGNAME_CEC_TX_AUTO_CEC_CNTRL AON_HDMI_TX_AUTO_CEC_CNTRL

#define REGADDR_CEC_TX_AUTO_CEC_FEATURE_ABORT_CFG BCHP_AON_HDMI_TX_AUTO_CEC_FEATURE_ABORT_CFG
#define REGNAME_CEC_TX_AUTO_CEC_FEATURE_ABORT_CFG AON_HDMI_TX_AUTO_CEC_FEATURE_ABORT_CFG

#define REGADDR_CEC_TX_AUTO_CEC_POWER_STATUS_CFG BCHP_AON_HDMI_TX_AUTO_CEC_POWER_STATUS_CFG
#define REGNAME_CEC_TX_AUTO_CEC_POWER_STATUS_CFG AON_HDMI_TX_AUTO_CEC_POWER_STATUS_CFG

#define REGADDR_CEC_TX_AUTO_CEC_GIVE_FEATURES_CFG_0 BCHP_AON_HDMI_TX_AUTO_CEC_GIVE_FEATURES_CFG_0
#define REGNAME_CEC_TX_AUTO_CEC_GIVE_FEATURES_CFG_0 AON_HDMI_TX_AUTO_CEC_GIVE_FEATURES_CFG_0

#define REGADDR_CEC_TX_AUTO_CEC_GIVE_FEATURES_CFG_1 BCHP_AON_HDMI_TX_AUTO_CEC_GIVE_FEATURES_CFG_1
#define REGNAME_CEC_TX_AUTO_CEC_GIVE_FEATURES_CFG_1 AON_HDMI_TX_AUTO_CEC_GIVE_FEATURES_CFG_1

#define REGADDR_CEC_TX_AUTO_CEC_GIVE_VERSION_CFG BCHP_AON_HDMI_TX_AUTO_CEC_GIVE_VERSION_CFG
#define REGNAME_CEC_TX_AUTO_CEC_GIVE_VERSION_CFG AON_HDMI_TX_AUTO_CEC_GIVE_VERSION_CFG

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_STANDBY_CFG BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_STANDBY_CFG
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_STANDBY_CFG AON_HDMI_TX_AUTO_CEC_CHECK_STANDBY_CFG

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_0 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_0
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_0 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_0

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_1 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_1
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_1 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_1

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_2 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_2
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_2 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_2

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_3 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_3
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE1_CFG_3 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE1_CFG_3

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_0 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_0
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_0 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_0

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_1 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_1
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_1 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_1

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_2 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_2
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE2_CFG_2 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE2_CFG_2

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_0 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_0
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_0 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_0

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_1 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_1
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_1 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_1

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_2 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_2
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE3_CFG_2 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE3_CFG_2

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_0 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_0
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_0 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_0

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_1 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_1
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_1 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_1

#define REGADDR_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_2 BCHP_AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_2
#define REGNAME_CEC_TX_AUTO_CEC_CHECK_WAKE4_CFG_2 AON_HDMI_TX_AUTO_CEC_CHECK_WAKE4_CFG_2

#define REGADDR_CEC_TX_AUTO_CEC_STATUS_0 BCHP_AON_HDMI_TX_AUTO_CEC_STATUS_0
#define REGNAME_CEC_TX_AUTO_CEC_STATUS_0 AON_HDMI_TX_AUTO_CEC_STATUS_0

#define REGADDR_CEC_TX_AUTO_CEC_STATUS_1 BCHP_AON_HDMI_TX_AUTO_CEC_STATUS_1
#define REGNAME_CEC_TX_AUTO_CEC_STATUS_1 AON_HDMI_TX_AUTO_CEC_STATUS_1

#define REGADDR_CEC_TX_CEC_ENERGYSTAR_CFG1 BCHP_AON_HDMI_TX_CEC_ENERGYSTAR_CFG1
#define REGNAME_CEC_TX_CEC_ENERGYSTAR_CFG1 AON_HDMI_TX_CEC_ENERGYSTAR_CFG1

#define REGADDR_CEC_TX_CEC_ENERGYSTAR_CFG2 BCHP_AON_HDMI_TX_CEC_ENERGYSTAR_CFG2
#define REGNAME_CEC_TX_CEC_ENERGYSTAR_CFG2 AON_HDMI_TX_CEC_ENERGYSTAR_CFG2

#define REGADDR_CEC_TX_CEC_ENERGYSTAR_CNTRL BCHP_AON_HDMI_TX_CEC_ENERGYSTAR_CNTRL
#define REGNAME_CEC_TX_CEC_ENERGYSTAR_CNTRL AON_HDMI_TX_CEC_ENERGYSTAR_CNTRL

#define REGADDR_CEC_TX_CEC_ENERGYSTAR_STATUS BCHP_AON_HDMI_TX_CEC_ENERGYSTAR_STATUS
#define REGNAME_CEC_TX_CEC_ENERGYSTAR_STATUS AON_HDMI_TX_CEC_ENERGYSTAR_STATUS


#elif BCEC_CONFIG_65NM_SUPPORT

#define BCHP_MASK_CEC_CNTRL(Register,Field) BCHP_HDMI_##Register##_##Field##_MASK

#define REGADDR_CEC_CNTRL_1 BCHP_HDMI_CEC_CNTRL_1
#define REGNAME_CEC_CNTRL_1 HDMI_CEC_CNTRL_1

#define REGADDR_CEC_CNTRL_2 BCHP_HDMI_CEC_CNTRL_2
#define REGNAME_CEC_CNTRL_2 HDMI_CEC_CNTRL_2

#define REGADDR_CEC_CNTRL_3 BCHP_HDMI_CEC_CNTRL_3
#define REGNAME_CEC_CNTRL_3 HDMI_CEC_CNTRL_3

#define REGADDR_CEC_CNTRL_4 BCHP_HDMI_CEC_CNTRL_4
#define REGNAME_CEC_CNTRL_4 HDMI_CEC_CNTRL_4

#define REGADDR_CEC_CNTRL_5 BCHP_HDMI_CEC_CNTRL_5
#define REGNAME_CEC_CNTRL_5 HDMI_CEC_CNTRL_5


#define REGADDR_CEC_TX_DATA_1 BCHP_HDMI_CEC_TX_DATA_1
#define REGNAME_CEC_TX_DATA_1 HDMI_CEC_TX_DATA_1

#define REGADDR_CEC_RX_DATA_1 BCHP_HDMI_CEC_RX_DATA_1
#define REGNAME_CEC_RX_DATA_1 HDMI_CEC_RX_DATA_1

#else
#define BCHP_MASK_DVP(Register,Field) BCHP_HDMI_##Register##_##Field##_MASK
#define BCHP_MASK_CEC_CNTRL(Register,Field) BCHP_HDMI_##Register##_##Field##_MASK

#define REGADDR_CEC_CNTRL_1 BCHP_HDMI_CEC_CNTRL_1
#define REGNAME_CEC_CNTRL_1 HDMI_CEC_CNTRL_1

#define REGADDR_CEC_CNTRL_2 BCHP_HDMI_CEC_CNTRL_2
#define REGNAME_CEC_CNTRL_2 HDMI_CEC_CNTRL_2

#define REGADDR_CEC_CNTRL_3 BCHP_HDMI_CEC_CNTRL_3
#define REGNAME_CEC_CNTRL_3 HDMI_CEC_CNTRL_3

#define REGADDR_CEC_CNTRL_4 BCHP_HDMI_CEC_CNTRL_4
#define REGNAME_CEC_CNTRL_4 HDMI_CEC_CNTRL_4

#define REGADDR_CEC_CNTRL_5 BCHP_HDMI_CEC_CNTRL_5
#define REGNAME_CEC_CNTRL_5 HDMI_CEC_CNTRL_5

#define REGADDR_CEC_TX_DATA_1 BCHP_HDMI_CEC_TX_DATA_1
#define REGNAME_CEC_TX_DATA_1 HDMI_CEC_TX_DATA_1

#define REGADDR_CEC_RX_DATA_1 BCHP_HDMI_CEC_RX_DATA_1
#define REGNAME_CEC_RX_DATA_1 HDMI_CEC_RX_DATA_1
#endif


#if BCEC_CONFIG_HAS_HDMI_RX
#define REGADDR_CEC_RX_CEC_ENERGYSTAR_CFG1 BCHP_AON_HDMI_RX_CEC_ENERGYSTAR_CFG1
#define REGNAME_CEC_RX_CEC_ENERGYSTAR_CFG1 AON_HDMI_RX_CEC_ENERGYSTAR_CFG1

#define REGADDR_CEC_RX_CEC_ENERGYSTAR_CFG2 BCHP_AON_HDMI_RX_CEC_ENERGYSTAR_CFG2
#define REGNAME_CEC_RX_CEC_ENERGYSTAR_CFG2 AON_HDMI_RX_CEC_ENERGYSTAR_CFG2

#define REGADDR_CEC_RX_CEC_ENERGYSTAR_CNTRL BCHP_AON_HDMI_RX_CEC_ENERGYSTAR_CNTRL
#define REGNAME_CEC_RX_CEC_ENERGYSTAR_CNTRL AON_HDMI_RX_CEC_ENERGYSTAR_CNTRL

#define REGADDR_CEC_RX_CEC_ENERGYSTAR_STATUS BCHP_AON_HDMI_RX_CEC_ENERGYSTAR_STATUS
#define REGNAME_CEC_RX_CEC_ENERGYSTAR_STATUS AON_HDMI_RX_CEC_ENERGYSTAR_STATUS

#define REGADDR_CEC_RX_AUTO_CEC_FEATURE_ABORT_CFG BCHP_AON_HDMI_RX_AUTO_CEC_FEATURE_ABORT_CFG
#define REGNAME_CEC_RX_AUTO_CEC_FEATURE_ABORT_CFG AON_HDMI_RX_AUTO_CEC_FEATURE_ABORT_CFG
#endif


/* CEC default timings */
#if (BCHP_CHIP == 7038) || (BCHP_CHIP == 7401) || (BCHP_CHIP == 7403) || \
	(BCHP_CHIP == 7440) || (BCHP_CHIP == 7400) || (BCHP_CHIP == 7405) || \
	(BCHP_CHIP == 7325) || (BCHP_CHIP == 7335)
/* Optimal settings for HDMI CEC control registers for 108Mhz system clock */
#define BCEC_CNTRL_1_DIV_CLK_CNT_VALUE			0xa8b
#define BCEC_CNTRL_2_CNT_TO_400_US_VALUE		0x00e
#define BCEC_CNTRL_2_CNT_TO_600_US_VALUE		0x018
#define BCEC_CNTRL_2_CNT_TO_800_US_VALUE		0x022
#define BCEC_CNTRL_2_CNT_TO_1300_US_VALUE		0x032
#define BCEC_CNTRL_2_CNT_TO_1500_US_VALUE		0x03c
#define BCEC_CNTRL_3_CNT_TO_1700_US_VALUE		0x046
#define BCEC_CNTRL_3_CNT_TO_2050_US_VALUE		0x050
#define BCEC_CNTRL_3_CNT_TO_2400_US_VALUE		0x062
#define BCEC_CNTRL_3_CNT_TO_2750_US_VALUE		0x070
#define BCEC_CNTRL_4_CNT_TO_3500_US_VALUE		0x08A
#define BCEC_CNTRL_4_CNT_TO_3600_US_VALUE		0x094
#define BCEC_CNTRL_4_CNT_TO_3900_US_VALUE		0x09e
#define BCEC_CNTRL_4_CNT_TO_4300_US_VALUE		0x0aa
#define BCEC_CNTRL_5_CNT_TO_4500_US_VALUE		0x0b4
#define BCEC_CNTRL_5_CNT_TO_4700_US_VALUE		0x0be

#else
/* Optimal settings for HDMI CEC control registers for 27Mhz system clock */
#define BCEC_CNTRL_1_DIV_CLK_CNT_VALUE			0x545
#define BCEC_CNTRL_2_CNT_TO_400_US_VALUE		0x007
#define BCEC_CNTRL_2_CNT_TO_600_US_VALUE		0x00c
#define BCEC_CNTRL_2_CNT_TO_800_US_VALUE		0x011
#define BCEC_CNTRL_2_CNT_TO_1300_US_VALUE		0x019
#define BCEC_CNTRL_2_CNT_TO_1500_US_VALUE		0x01e
#define BCEC_CNTRL_3_CNT_TO_1700_US_VALUE		0x023
#define BCEC_CNTRL_3_CNT_TO_2050_US_VALUE		0x028
#define BCEC_CNTRL_3_CNT_TO_2400_US_VALUE		0x031
#define BCEC_CNTRL_3_CNT_TO_2750_US_VALUE		0x038
#define BCEC_CNTRL_4_CNT_TO_3500_US_VALUE		0x045
#define BCEC_CNTRL_4_CNT_TO_3600_US_VALUE		0x04a
#define BCEC_CNTRL_4_CNT_TO_3900_US_VALUE		0x04f
#define BCEC_CNTRL_4_CNT_TO_4300_US_VALUE		0x055
#define BCEC_CNTRL_5_CNT_TO_4500_US_VALUE		0x05a
#define BCEC_CNTRL_5_CNT_TO_4700_US_VALUE		0x05f
#endif



#define BCEC_MAKE_INTR_ENUM(IntName) BCEC_INTR_e##IntName
#define BCEC_MAKE_INTR_NAME(IntName) "BCEC_" #IntName


#define BCEC_Wake_Reason_1_ImageViewOn 1
#define BCEC_Wake_Reason_1_TextViewOn 2
#define BCEC_Wake_Reason_1_PowerOnFunction 4
#define BCEC_Wake_Reason_1_PowerToggleFunction 8
#define BCEC_Wake_Reason_1_ActiveSource 16

#define BCEC_Wake_Reason_2_PlayForward 1
#define BCEC_Wake_Reason_2_DeckControl_Eject 2

#define BCEC_Wake_Reason_3_SetStreamPath 1

#define BCEC_Wake_Reason_4_UserControlPress_Power 1


#define BCEC_MAX_OPCODES 62
typedef struct
{
	uint8_t opCode ;
	const char *opText ;
} BCEC_OpcodeTextTable ;


/******************************************************************************
Summary:
Enumeration of BCEC_Interrupts
*******************************************************************************/
typedef enum
{
#if BCEC_CONFIG_DUAL_INTERRUPT
	/* 00 */ BCEC_MAKE_INTR_ENUM(RECEIVED),
	/* 01 */ BCEC_MAKE_INTR_ENUM(SENT),
#else
	/* 00 */ BCEC_MAKE_INTR_ENUM(CEC),
#endif
	/* 01 */ BCEC_MAKE_INTR_ENUM(LAST)
} BCEC_P_InterruptMask ;


typedef struct BCEC_P_ReceivedMessageInfo
{
	BAVC_HDMI_CEC_MessageData data;
	BCEC_MessageStatus status;
} BCEC_P_ReceivedMessageInfo ;


/*******************************************************************************
Private CEC Handle Declaration
*******************************************************************************/
BDBG_OBJECT_ID_DECLARE(BCEC_P_Handle);

typedef struct BCEC_P_Handle
{
	BDBG_OBJECT(BCEC_P_Handle)
	BCEC_Dependencies stDependencies;
	BTMR_TimerHandle hTimer;
	BTMR_Settings stTmrSettings;
	BCEC_Settings stSettings;
	BINT_CallbackHandle hCallback[BCEC_MAKE_INTR_ENUM(LAST)] ;

	BKNI_EventHandle BCEC_EventCec_Transmitted ;
	BKNI_EventHandle BCEC_EventCec_Received;
	BCEC_MessageStatus lastTransmitMessageStatus ;
	BCEC_MessageStatus lastReceivedMessageStatus ;
	bool firstCecMessage ;

	bool standby; /* true if in standby */
	bool enableAutoOn;
	uint8_t wakeReason1;
	uint8_t wakeReason2;
	uint8_t wakeReason3;
	uint8_t wakeReason4;
	uint32_t ulRegisterOffset;
} BCEC_P_Handle ;


void BCEC_P_HandleInterrupt_isr(
	void *pParam1,						/* [in] Device handle */
	int parm2							/* [in] not used */
);


void BCEC_P_MaskWakeupEvents(
	BCEC_Handle hCEC,
	uint32_t ConfigRegisterAddr,
	uint32_t ConfigRegisterAddr2
);

void BCEC_P_ClearWakeupStatus(
	BCEC_Handle hCEC,
	uint32_t StatusControlRegAddr) ;


#if BCEC_CONFIG_AUTO_ON_SUPPORT
void BCEC_P_EnableAutoOn(
	BCEC_Handle hCEC,
	bool enable
);
#endif


#ifdef __cplusplus
 }
#endif

#endif /* BCEC_PRIV_H__ */


