/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 ******************************************************************************/
#pragma once

#include "libs/core/v3d/v3d_ver.h"

#include <stdint.h>

/* Different types of uniform */
typedef enum {
   BACKEND_UNIFORM_UNASSIGNED = 0,
   BACKEND_UNIFORM_PLAIN,
   BACKEND_UNIFORM_PLAIN_FPACK,
   BACKEND_UNIFORM_LITERAL,
   BACKEND_UNIFORM_ADDRESS,
   BACKEND_UNIFORM_UBO_ADDRESS,
   BACKEND_UNIFORM_SSBO_ADDRESS,
   BACKEND_UNIFORM_ATOMIC_ADDRESS,
   BACKEND_UNIFORM_UBO_LOAD,
   BACKEND_UNIFORM_SSBO_SIZE,
   BACKEND_UNIFORM_SSBO_ARRAY_LENGTH,  // Returns array_length_of_buf(unif & 0x1f) - (unif >> 5);
   BACKEND_UNIFORM_UBO_SIZE,           // These don't make any sense, UBOs cannot have dynamically sized arrays.
   BACKEND_UNIFORM_UBO_ARRAY_LENGTH,
   BACKEND_UNIFORM_TEX_PARAM0,
   BACKEND_UNIFORM_TEX_PARAM1,
#if V3D_VER_AT_LEAST(4,0,2,0)
   BACKEND_UNIFORM_TEX_PARAM1_UNNORMS,
#endif
   BACKEND_UNIFORM_TEX_SIZE_X,
   BACKEND_UNIFORM_TEX_SIZE_Y,
   BACKEND_UNIFORM_TEX_SIZE_Z,
   BACKEND_UNIFORM_TEX_LEVELS,
   BACKEND_UNIFORM_IMG_PARAM0,
#if !V3D_VER_AT_LEAST(4,0,2,0)
   BACKEND_UNIFORM_IMG_PARAM1,
   BACKEND_UNIFORM_TEX_BASE_LEVEL,
   BACKEND_UNIFORM_TEX_BASE_LEVEL_FLOAT,
   BACKEND_UNIFORM_IMAGE_ARR_STRIDE,
   BACKEND_UNIFORM_IMAGE_SWIZZLING,
   BACKEND_UNIFORM_IMAGE_XOR_ADDR,
   BACKEND_UNIFORM_IMAGE_LX_ADDR,
   BACKEND_UNIFORM_IMAGE_LX_PITCH,
   BACKEND_UNIFORM_IMAGE_LX_SLICE_PITCH,
#endif
   BACKEND_UNIFORM_IMG_SIZE_X,
   BACKEND_UNIFORM_IMG_SIZE_Y,
   BACKEND_UNIFORM_IMG_SIZE_Z,
   BACKEND_UNIFORM_SPECIAL,
   BACKEND_UNIFORM_LAST_ELEMENT = BACKEND_UNIFORM_SPECIAL
} BackendUniformFlavour;

/* Valid values for BACKEND_UNIFORM_SPECIALs. */
typedef enum {
   BACKEND_SPECIAL_UNIFORM_VP_SCALE_X,
   BACKEND_SPECIAL_UNIFORM_VP_SCALE_Y,
   BACKEND_SPECIAL_UNIFORM_VP_SCALE_Z,
   BACKEND_SPECIAL_UNIFORM_VP_OFFSET_Z,
   BACKEND_SPECIAL_UNIFORM_DEPTHRANGE_NEAR,
   BACKEND_SPECIAL_UNIFORM_DEPTHRANGE_FAR,
   BACKEND_SPECIAL_UNIFORM_DEPTHRANGE_DIFF,
#if !V3D_VER_AT_LEAST(4,1,34,0)
   BACKEND_SPECIAL_UNIFORM_SAMPLE_MASK,
#endif
   BACKEND_SPECIAL_UNIFORM_NUMWORKGROUPS_X,
   BACKEND_SPECIAL_UNIFORM_NUMWORKGROUPS_Y,
   BACKEND_SPECIAL_UNIFORM_NUMWORKGROUPS_Z,
   BACKEND_SPECIAL_UNIFORM_SHARED_PTR,
   BACKEND_SPECIAL_UNIFORM_FB_MAX_LAYER,
   BACKEND_SPECIAL_UNIFORM_LAST_ELEMENT = BACKEND_SPECIAL_UNIFORM_FB_MAX_LAYER
} BackendSpecialUniformFlavour;

typedef struct {
   BackendUniformFlavour type;
   uint32_t              value;
} umap_entry;
