COMMON_SRC_FILES := \
	libs/khrn/common/khrn_int_hash.c \
	libs/khrn/common/khrn_options.c \
	libs/khrn/glxx/glxx_client_skin.c \
	libs/util/dglenum/dglenum.c \
	libs/util/log/log.c \
	libs/khrn/common/khrn_fmem.c \
	libs/khrn/common/khrn_fmem_pool.c \
	libs/khrn/common/khrn_fmem_debug_info.c \
	libs/khrn/common/khrn_counters.c \
	libs/khrn/common/khrn_event_monitor.c \
	libs/khrn/common/khrn_render_state.c \
	libs/khrn/common/khrn_blob.c \
	libs/khrn/common/khrn_image.c \
	libs/khrn/common/khrn_interlock.c \
	libs/khrn/common/khrn_map.c \
	libs/khrn/common/khrn_res_interlock.c \
	libs/khrn/common/khrn_mem.c \
	libs/khrn/common/khrn_process.c \
	libs/khrn/common/khrn_process_debug.c \
	libs/khrn/common/khrn_uintptr_vector.c \
	libs/khrn/common/khrn_synclist.c \
	libs/khrn/common/khrn_fence.c \
	libs/khrn/common/khrn_timeline.c \
	libs/khrn/common/khrn_record.c \
	libs/khrn/egl/egl_attrib_list.c \
	libs/khrn/egl/egl_config.c \
	libs/khrn/egl/egl_context_base.c \
	libs/khrn/egl/egl_context.c \
	libs/khrn/egl/egl_context_gl.c \
	libs/khrn/egl/egl_display.c \
	libs/khrn/egl/egl_map.c \
	libs/khrn/egl/egl_pbuffer_surface.c \
	libs/khrn/egl/egl_process.c \
	libs/khrn/egl/egl_surface_base.c \
	libs/khrn/egl/egl_surface.c \
	libs/khrn/egl/egl_thread.c \
	libs/khrn/egl/egl_image.c \
	libs/khrn/egl/egl_image_texture.c \
	libs/khrn/egl/egl_image_renderbuffer.c \
	libs/khrn/egl/egl_image_framebuffer.c \
	libs/khrn/egl/egl_sync.c \
	libs/khrn/egl/egl_synckhr.c \
	libs/khrn/egl/egl_proc_address.c \
	libs/khrn/egl/egl_platform.c \
	libs/khrn/ext/egl_brcm_perf_counters.c \
	libs/khrn/ext/egl_brcm_event_monitor.c \
	libs/khrn/ext/gl_ext_base_instance.c \
	libs/khrn/ext/gl_ext_multi_draw_indirect.c \
	libs/khrn/ext/gl_ext_texture_border_clamp.c \
	libs/khrn/ext/gl_brcm_texture_1d.c \
	libs/khrn/ext/gl_brcm_polygon_mode.c \
	libs/khrn/ext/gl_brcm_provoking_vertex.c \
	libs/khrn/ext/gl_ext_draw_elements_base_vertex.c \
	libs/khrn/ext/gl_ext_robustness.c \
	libs/khrn/ext/gl_oes_draw_texture.c \
	libs/khrn/ext/gl_oes_map_buffer.c \
	libs/khrn/ext/gl_oes_matrix_palette.c \
	libs/khrn/ext/gl_oes_query_matrix.c \
	libs/khrn/ext/gl_oes_texture_border_clamp.c \
	libs/khrn/ext/gl_khr_debug.c \
	libs/khrn/ext/gl_khr_debug_msgs.c \
	libs/khrn/gl11/gl11_shader.c \
	libs/khrn/gl11/gl11_vshader.c \
	libs/khrn/gl11/gl11_fshader.c \
	libs/khrn/gl11/gl11_shadercache.c \
	libs/khrn/gl11/gl11_matrix.c \
	libs/khrn/gl11/gl11_server.c \
	libs/khrn/gl11/gl11_draw.c \
	libs/khrn/gl11/gl_oes_framebuffer_object.c \
	libs/khrn/gl20/gl20_program.c \
	libs/khrn/gl20/gl20_server.c \
	libs/khrn/gl20/gl20_shader.c \
	libs/khrn/glsl/glsl_unique_index_queue.c \
	libs/khrn/glsl/glsl_mem_layout.c \
	libs/khrn/glsl/glsl_symbols.c \
	libs/khrn/glsl/glsl_symbol_table.c \
	libs/khrn/glsl/glsl_stringbuilder.c \
	libs/khrn/glsl/glsl_stackmem.c \
	libs/khrn/glsl/glsl_source.c \
	libs/khrn/glsl/glsl_shader_interfaces.c \
	libs/khrn/glsl/glsl_scoped_map.c \
	libs/khrn/glsl/glsl_safemem.c \
	libs/khrn/glsl/glsl_program.c \
	libs/khrn/glsl/glsl_precision.c \
	libs/khrn/glsl/glsl_map.c \
	libs/khrn/glsl/glsl_layout.c \
	libs/khrn/glsl/glsl_ir_shader.c \
	libs/khrn/glsl/glsl_ir_program.c \
	libs/khrn/glsl/glsl_intrinsic_ir_builder.c \
	libs/khrn/glsl/glsl_intrinsic.c \
	libs/khrn/glsl/glsl_intern.c \
	libs/khrn/glsl/glsl_globals.c \
	libs/khrn/glsl/glsl_file_utils.c \
	libs/khrn/glsl/glsl_fastmem.c \
	libs/khrn/glsl/glsl_extensions.c \
	libs/khrn/glsl/glsl_errors.c \
	libs/khrn/glsl/glsl_dataflow_visitor.c \
	libs/khrn/glsl/glsl_dataflow_simplify.c \
	libs/khrn/glsl/glsl_dataflow_print.c \
	libs/khrn/glsl/glsl_dataflow_builder.c \
	libs/khrn/glsl/glsl_dataflow_cse.c \
	libs/khrn/glsl/glsl_dataflow.c \
	libs/khrn/glsl/glsl_dataflow_image.c \
	libs/khrn/glsl/glsl_linker.c \
	libs/khrn/glsl/glsl_compiler.c \
	libs/khrn/glsl/glsl_builders.c \
	libs/khrn/glsl/glsl_binary_shader.c \
	libs/khrn/glsl/glsl_binary_program.c \
	libs/khrn/glsl/glsl_backflow_visitor.c \
	libs/khrn/glsl/glsl_backflow_print.c \
	libs/khrn/glsl/glsl_backflow.c \
	libs/khrn/glsl/glsl_backflow_combine.c \
	libs/khrn/glsl/glsl_backend.c \
	libs/khrn/glsl/glsl_ast_visitor.c \
	libs/khrn/glsl/glsl_ast_print.c \
	libs/khrn/glsl/glsl_ast.c \
	libs/khrn/glsl/glsl_arenamem.c \
	libs/khrn/glsl/glsl_alloc_tracker.c \
	libs/khrn/glsl/glsl_basic_block.c \
	libs/khrn/glsl/glsl_basic_block_builder.c \
	libs/khrn/glsl/glsl_basic_block_flatten.c \
	libs/khrn/glsl/glsl_basic_block_print.c \
	libs/khrn/glsl/glsl_nast.c \
	libs/khrn/glsl/glsl_nast_builder.c \
	libs/khrn/glsl/glsl_nast_print.c \
	libs/khrn/glsl/glsl_dominators.c \
	libs/khrn/glsl/glsl_scheduler.c \
	libs/khrn/glsl/glsl_quals.c \
	libs/khrn/glsl/prepro/glsl_prepro_directive.c \
	libs/khrn/glsl/prepro/glsl_prepro_eval.c \
	libs/khrn/glsl/prepro/glsl_prepro_expand.c \
	libs/khrn/glsl/prepro/glsl_prepro_token.c \
	libs/khrn/glsl/prepro/glsl_prepro_macro.c \
	libs/khrn/glxx/gl32_stubs.c \
	libs/khrn/glxx/glxx_ez.c \
	libs/khrn/glxx/glxx_hw.c \
	libs/khrn/glxx/glxx_inner.c \
	libs/khrn/glxx/glxx_shader_ops.c \
	libs/khrn/glxx/glxx_shader.c \
	libs/khrn/glxx/glxx_hw_tile_list.c \
	libs/khrn/glxx/glxx_hw_clear.c \
	libs/khrn/glxx/glxx_hw_render_state.c \
	libs/khrn/glxx/glxx_buffer.c \
	libs/khrn/glxx/glxx_ds_to_color.c \
	libs/khrn/glxx/glxx_draw.c \
	libs/khrn/glxx/glxx_framebuffer.c \
	libs/khrn/glxx/glxx_renderbuffer.c \
	libs/khrn/glxx/glxx_server.c \
	libs/khrn/glxx/glxx_server_barrier.c \
	libs/khrn/glxx/glxx_server_debug.c \
	libs/khrn/glxx/glxx_textures.c \
	libs/khrn/glxx/glxx_server_texture.c \
	libs/khrn/glxx/glxx_server_buffer.c \
	libs/khrn/glxx/glxx_query.c \
	libs/khrn/glxx/glxx_server_query.c \
	libs/khrn/glxx/glxx_server_get.c \
	libs/khrn/glxx/glxx_server_framebuffer.c \
	libs/khrn/glxx/glxx_server_transform_feedback.c \
	libs/khrn/glxx/glxx_server_vao.c \
	libs/khrn/glxx/glxx_server_sampler.c \
	libs/khrn/glxx/glxx_server_pipeline.c \
	libs/khrn/glxx/glxx_server_sync.c \
	libs/khrn/glxx/glxx_server_program_interface.c \
	libs/khrn/glxx/glxx_shader_cache.c \
	libs/khrn/glxx/glxx_shared.c \
	libs/khrn/glxx/glxx_compressed_paletted_texture.c \
	libs/khrn/glxx/glxx_texture.c \
	libs/khrn/glxx/glxx_texture_utils.c \
	libs/khrn/glxx/glxx_fencesync.c \
	libs/khrn/glxx/glxx_blit.c \
	libs/khrn/glxx/glxx_tmu_blit.c \
	libs/khrn/glxx/glxx_tlb_blit.c \
	libs/khrn/glxx/glxx_utils.c \
	libs/khrn/glxx/glxx_compute.c \
	libs/khrn/glxx/glxx_texlevel_param.c \
	libs/khrn/glxx/glxx_image_unit.c \
	libs/util/desc_map/desc_map.c \
	libs/util/gfx_util/gfx_util_morton.c \
	libs/util/gfx_util/gfx_util_hrsize.c \
	libs/util/gfx_util/gfx_util_file.c \
	libs/util/gfx_util/gfx_util.c \
	libs/util/gfx_util/gfx_util_term_col.c \
	libs/util/gfx_util/gfx_util_wildcard.c \
	libs/util/gfx_options/gfx_options.c \
	libs/core/lfmt/lfmt_translate_v3d.c \
	libs/core/lfmt/lfmt_fmt_detail.c \
	libs/core/lfmt/lfmt.c \
	libs/core/lfmt/lfmt_block.c \
	libs/core/lfmt/lfmt_desc.c \
	libs/core/lfmt/lfmt_desc_maps.c \
	libs/core/lfmt_translate_gl/lfmt_translate_gl.c \
	libs/core/gfx_buffer/gfx_buffer_v3d_tfu_srgb_conversions.c \
	libs/core/gfx_buffer/gfx_buffer_uif_config.c \
	libs/core/gfx_buffer/gfx_buffer_translate_v3d.c \
	libs/core/gfx_buffer/gfx_buffer_compare.c \
	libs/core/gfx_buffer/gfx_buffer_bc.c \
	libs/core/gfx_buffer/gfx_buffer.c \
	libs/core/gfx_buffer/gfx_buffer_bstc.c \
	libs/core/gfx_buffer/gfx_buffer_desc_gen.c \
	libs/core/gfx_buffer/gfx_buffer_slow_conv_compr.c \
	libs/core/gfx_buffer/gfx_buffer_slow_conv_xform.c \
	libs/core/gfx_buffer/gfx_buffer_slow_conv.c \
	libs/util/gfx_args/gfx_args.c \
	libs/core/v3d/v3d_choose_supertile.c \
	libs/core/v3d/v3d_cl.c \
	libs/core/v3d/v3d_cl_compr.c \
	libs/core/v3d/v3d_gen.c \
	libs/core/v3d/v3d_ident.c \
	libs/core/v3d/v3d_printer.c \
	libs/core/v3d/v3d_tfu.c \
	libs/core/v3d/v3d_tlb_decimate.c \
	libs/core/v3d/v3d_tmu.c \
	libs/core/v3d/v3d_vpm.c \
	libs/platform/v3d_imgconv.c \
	libs/platform/v3d_imgconv_c.c \
	libs/platform/v3d_imgconv_neon.c \
	libs/platform/v3d_imgconv_extra_neon.c \
	libs/platform/v3d_imgconv_gfx_blit.c \
	libs/platform/v3d_scheduler.c \
	libs/platform/v3d_imgconv_tfu.c \
	libs/platform/v3d_imgconv_tlb.c \
	libs/platform/v3d_parallel.c \
	libs/platform/bcg_abstract/gmem_abstract.c \
	libs/platform/bcg_abstract/gmem_talloc.c \
	libs/platform/bcg_abstract/sched_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_platform_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_window_surface_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_surface_common_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_pixmap_surface_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_image_native_buffer_abstract.c \
	libs/khrn/egl/platform/bcg_abstract/egl_wl_bind_display_abstract.c \
	libs/core/vcos/posix/vcos_pthreads.c \
	libs/core/vcos/posix/vcos_thread_posix.c \
	libs/core/vcos/posix/vcos_mutex_posix.c \
	libs/core/vcos/generic/vcos_generic_safe_string.c \
	libs/core/vcos/generic/vcos_init.c \
	libs/core/vcos/generic/vcos_properties.c \
	libs/sim/qpu_float/qpu_float.c \
	libs/sim/sfu/sfu.c \

COMMON_GENERATED_SRC_FILES := \
	glsl_intrinsic_lookup.auto.c \
	glsl_layout.auto.c \
	glsl_lexer.c \
	glsl_numbers.c \
	glsl_parser.c \
	glsl_primitive_types.auto.c \
	glsl_version.c \
	glsl_stdlib.auto.c
