//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WpsWizard.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_WPSMODESELECTIONPG          103
#define IDD_PBCMODEPG                   104
#define IDD_PINMODEPG                   105
#define IDD_CONFIGSTATUSPG              106
#define IDD_WELCOMEPG                   107
#define IDD_WIZARDPROPPG                108
#define IDD_SELECT_AP                   109
#define IDR_MAINFRAME                   121
#define IDR_PN_ERROR                    122
#define IDR_SES_ERROR                   123
#define IDR_EZ_DEFAULT_ERROR            124
#define IDR_NO_NICS_ERROR               125
#define IDR_HELP_ROUTER_SEL             126
#define IDR_PRIVACY_NOTE                127
#define IDR_RTF_ERROR_SEARCHAP          128
#define IDR_RTF_ERROR_CONNECTING        129
#define IDR_RTF_ERROR_CONFIGUATING      130
#define IDD_WPSROLESELECTIONPG          130
#define IDR_RTF_ERROR_TESTING           131
#define IDD_CONFIGAPPG                  131
#define IDR_RTF_ERROR_ESTABLISHING      132
#define IDD_WPSFINISHPG                 132
#define IDR_RTF_ERROR_GET_IP            133
#define IDD_VERSELECTIONPG              133
#define IDR_MORE_INFO                   134
#define IDR_RTF_ERROR_2CLIENTS          135
#define IDB_BITMAP_WPSLOGO_VERT         204
#define IDB_IDLE                        208
#define IDB_SUCCESS                     209
#define IDB_FAIL                        210
#define IDB_BITMAP_COMPANY_VT           214
#define IDC_BUTTON1                     1000
#define IDC_CANCEL_WPS                  1000
#define IDC_GENERATE_DEFAULT            1000
#define IDC_SCAN_NETWORK                1000
#define IDC_MODE_PIN                    1002
#define IDC_MODE_PBC                    1003
#define IDC_PINCODE                     1003
#define IDC_REG_PINCODE                 1003
#define IDC_AP_LIST                     1004
#define IDC_STATUS_LOG                  1004
#define IDC_LABEL_ENTER_PIN             1006
#define IDC_LABEL_SEARCHING_AP          1007
#define IDC_LABEL_NEGOTIATING_RETRIEVING 1008
#define IDC_LABEL_CREATING_PROFILE      1009
#define IDC_LABEL_RESTORING_NETWORK_ENV 1010
#define IDC_LABEL_INITIALIZING_WPS      1011
#define IDC_AP_PIN                      1011
#define IDC_TXTINDICATOR_WPS_INITIALIZING 1012
#define IDC_STATIC_ENTER_AP_PIN         1012
#define IDC_TXTINDICATOR_SEARCHING_AP   1013
#define IDC_LABEL_JOINING_AP            1014
#define IDC_SECURITY_METHOD             1014
#define IDC_TXTINDICATOR_JOINING_AP     1015
#define IDC_STATIC_SECURITY_METHOD      1015
#define IDC_TXTINDICATOR_NEGOTIATING_RETRIEVING 1016
#define IDC_STATIC_DATA_ENCR            1016
#define IDC_TXTINDICATOR_CREATING_PROFILE 1017
#define IDC_STATIC_NETWORK_KEY          1017
#define IDC_TXTINDICATOR_RESTORING_NETWORK_ENV 1018
#define IDC_ENCR_TYPE                   1018
#define IDC_BMPINDICATOR_WPS_INITIALIZING 1019
#define IDC_NW_KEY                      1019
#define IDC_BMPINDICATOR_SEARCHING_AP   1020
#define IDC_STATIC_SELECT_MODE          1020
#define IDC_STATIC_SSID                 1020
#define IDC_BMPINDICATOR_JOINING_AP     1021
#define IDC_BMPINDICATOR_NEGOTIATING_RETRIEVING 1022
#define IDC_STATIC_PBC_DESCRIPTION      1022
#define IDC_BMPINDICATOR_CREATING_PROFILE 1023
#define IDC_GROUP_PBC_MODE              1023
#define IDC_SSID                        1023
#define IDC_BMPINDICATOR_RESTORING_NETWORK_ENV 1024
#define IDC_STATIC_PIN_DESCRIPTOIN      1024
#define IDC_STATIC_LEFTBK               1025
#define IDC_STATIC_SECUREEZ_BITMAP      1026
#define IDC_STATIC_LEFTBK2              1026
#define IDC_STATIC_RIGHTBK              1027
#define IDC_STATIC_PRIVACY              1028
#define IDC_STATIC_RIGHTBK2             1028
#define IDC_STATIC_PIN                  1028
#define IDC_STATIC_SECUREEZ_BITMAP2     1028
#define IDC_BUTTON_SETUP                1029
#define IDC_LABLE_CONFIG_STATUS         1029
#define IDC_LABEL_CONFIG_STATUS         1029
#define IDC_STATIC_TITLE_TEXT           1030
#define IDC_GROUP_PIN_MODE              1030
#define IDC_LABEL_RESULT                1030
#define IDC_STATIC_DESCRIPTION          1031
#define IDC_STATIC_BITMAP_STEP1         1032
#define IDC_STATIC_TEXT_STEP1           1033
#define IDC_STATIC_BITMAP_STEP2         1034
#define IDC_SEL_AUTO_CONNECT            1034
#define IDC_STATIC_TEXT_STEP2           1035
#define IDC_GROUP_SELECT_MODE           1035
#define IDC_STATIC_MORE_INFO            1036
#define IDC_ROLE_JOIN_AP                1036
#define IDC_ROLE_CONFIG_AP              1037
#define IDC_CHECK_HIDE_CHAR             1038
#define IDC_COMPANY_LOGO                1039
#define IDC_STAENR_GET_SETTINGS         1040
#define IDC_COMPANY_LOGO2               1040
#define IDC_STAER_GET_SETTINGS          1041
#define IDC_GROUP_NETWORK_SETTINGS      1042
#define IDC_STATIC_KEY_DESC             1043
#define IDC_STATIC_RESULT_DESC          1044
#define IDC_STATIC_NETWORK_SSID         1045
#define IDC_LABEL_SSID                  1045
#define IDC_ENROLLEE_PINCODE            1046
#define IDC_LABEL_PIN                   1047
#define IDC_LABEL_SEL_NETWORK           1048
#define IDC_STATIC_AUTO_SEL_DESC        1049
#define IDC_STATIC_SEL_MODE_DESC        1050
#define IDC_STATIC_AP_PIN_DESC          1051
#define IDC_GEN_DEFAULT_DESC            1052
#define IDC_INST_CABLE_CONNECT_AP       1053
#define IDC_GROUP_VER_SELECTION         1055
#define IDC_WPS_V1                      1056
#define IDC_WPS_V2                      1057
#define IDC_CHECK1                      1057
#define IDC_SHOW_AUTH_AP                1057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
